import type { InterfaceLanguage } from "@/types";

/** Short UI-language definitions for English-course vocabulary (key = English lemma). */
export const ENGLISH_VOCAB_DEFINITION: Partial<
  Record<InterfaceLanguage, Record<string, string>>
> = {
  ru: {
  "a blessing in disguise": "скрытое благословение.",
  "a double-edged sword": "палка о двух концах.",
  "a rule of thumb": "практическое правило.",
  "abundant": "Обильный.",
  "account": "Счет.",
  "account for": "Приходиться.",
  "accurate": "Точный.",
  "address": "Адрес.",
  "address an issue": "Решите проблему.",
  "admittedly": "По общему признанию.",
  "afford": "Предоставлять.",
  "afraid": "Испуганный.",
  "afternoon": "Полдень.",
  "age": "Возраст.",
  "ailment": "Болезнь.",
  "airport": "Аэропорт.",
  "alarm clock": "Будильник.",
  "albeit": "Хотя.",
  "allegory": "Аллегория.",
  "always": "Всегда.",
  "ambiguous": "Двусмысленный.",
  "apologise": "Извиняться.",
  "app": "Приложение.",
  "apply": "Применять.",
  "appointment": "Встреча.",
  "apprehensive": "Опасаясь.",
  "approach": "Подход.",
  "aptitude": "Способности.",
  "arcane": "Тайный.",
  "arguably": "Возможно.",
  "argue": "Спорить.",
  "argument": "Аргумент.",
  "arrival": "Прибытие.",
  "arrive": "Приехать.",
  "artificial intelligence": "Искусственный интеллект.",
  "as a result": "Как результат.",
  "ask": "Спросить.",
  "assess": "Оценивать.",
  "assignment": "Назначение.",
  "astonished": "Пораженный.",
  "at the end of the day": "В конце дня.",
  "atm": "Банкомат.",
  "audience": "Аудитория.",
  "automate": "Автоматизировать.",
  "automation": "Автоматизация.",
  "autumn": "Осень.",
  "awareness": "Осведомленность.",
  "backup": "Резервное копирование.",
  "balance": "Баланс.",
  "ban": "Бан.",
  "bank": "Банк.",
  "bargain": "Торговаться.",
  "bargain hunter": "Охотник за выгодными покупками.",
  "bathroom": "Ванная комната.",
  "bear in mind": "Имейте в виду.",
  "beautiful": "Красивый.",
  "bedroom": "Спальня.",
  "beneficial": "Выгодный.",
  "between": "Между.",
  "bias": "Предвзятость.",
  "big": "Большой.",
  "bill": "Счет.",
  "biodiversity": "Биоразнообразие.",
  "bittersweet": "Горько-сладкий.",
  "black": "Черный.",
  "blue": "Синий.",
  "boarding pass": "Посадочный талон.",
  "book": "Книга.",
  "booked": "Забронировано.",
  "booking": "Бронирование.",
  "borrow": "Брать взаймы.",
  "brand": "Бренд.",
  "bread": "Хлеб.",
  "break down": "Чтобы сломаться.",
  "break the ice": "чтобы сломать лед.",
  "breakfast": "Завтрак.",
  "breakthrough": "Прорыв.",
  "bring about": "Чтобы осуществить.",
  "bring up": "Воспитывать.",
  "broadcast": "Транслировать.",
  "brother": "Брат.",
  "brown": "Коричневый.",
  "brush": "Щетка.",
  "brush teeth": "чистить зубы.",
  "budget": "Бюджет.",
  "burn the candle at both ends": "сжечь свечу с обоих концов.",
  "burn the midnight oil": "Сожгите полуночное масло.",
  "burnout": "Выгорание.",
  "burst into tears": "разрыдаться.",
  "bus": "Автобус.",
  "call": "Чтобы позвонить.",
  "call for": "Позвать.",
  "call it a day": "положить конец.",
  "campaign": "Кампания.",
  "cancel": "Отмена.",
  "cancelled": "Отменено.",
  "carbon footprint": "Углеродный след.",
  "card": "Карта.",
  "carry out": "Выполнять.",
  "cash": "Наличные.",
  "cash register": "Кассовый аппарат.",
  "cast doubt": "Вызывайте сомнение.",
  "catch up": "Настигнуть.",
  "celebrate": "Празднуйте.",
  "cemetery": "Кладбище.",
  "censorship": "Цензура.",
  "change": "Чтобы измениться.",
  "charge": "Заряжать.",
  "cheap": "Дешевый.",
  "cheaper": "Дешевле.",
  "check in": "Регистрироваться.",
  "check-up": "Проверять.",
  "checkout": "Проверить.",
  "cheese": "Сыр.",
  "chicken": "Курица.",
  "child": "Ребенок.",
  "chronic": "Хронический.",
  "citizen": "Гражданин.",
  "claim": "Требовать.",
  "classmate": "Одноклассник.",
  "clean": "Чистить.",
  "climate": "Климат.",
  "climb the ladder": "чтобы подняться по лестнице.",
  "close": "Закрывать.",
  "cloud": "Облако.",
  "cloudy": "Облачно.",
  "club": "Клуб.",
  "coffee": "Кофе.",
  "coherent": "Последовательный.",
  "cold": "Холодный.",
  "colleague": "Коллега.",
  "collect": "Собирать.",
  "come across": "Чтобы встретиться.",
  "come into force": "Вступить в силу.",
  "come to terms with": "Чтобы смириться.",
  "come up with": "Чтобы придумать.",
  "comfortable": "Комфортный.",
  "commitment": "Обязательство.",
  "community": "Сообщество.",
  "commute": "ездить на работу.",
  "compelling": "Неотразимый.",
  "comprehensive": "Всесторонний.",
  "conclude": "Сделайте вывод.",
  "conscientious": "Добросовестный.",
  "consequence": "Последствие.",
  "conservation": "Сохранение.",
  "conserve": "Сохранить.",
  "consist of": "Состоят из.",
  "contentious": "Спорный.",
  "contribute": "Способствовать.",
  "controversial": "Спорный.",
  "conversation": "Беседа.",
  "conversely": "Наоборот.",
  "cook": "Готовить.",
  "cool": "Прохладный.",
  "corner": "Угол.",
  "correlate": "коррелировать.",
  "corroborate": "чтобы подтвердить.",
  "costume": "Костюм.",
  "cotton": "Хлопок.",
  "crime": "Преступление.",
  "crisis": "Кризис.",
  "cross that bridge when we come to it": "Пересеките этот мост, когда мы подойдем к нему.",
  "crossroads": "Перекресток.",
  "crucially": "Крайне важно.",
  "currency": "Валюта.",
  "curriculum": "Учебный план.",
  "customer": "Клиент.",
  "customs": "Таможня.",
  "cut corners": "Чтобы срезать углы.",
  "cut down on": "Чтобы сократить.",
  "cybersecurity": "Кибербезопасность.",
  "dance": "Танец.",
  "data": "Данные.",
  "deadline": "Крайний срок.",
  "debate": "Дебаты.",
  "debt": "Долг.",
  "decisive": "Решительный.",
  "degree": "Степень.",
  "delay": "Задерживать.",
  "delayed": "Отложенный.",
  "deliberate": "Преднамеренный.",
  "delicious": "Вкусный.",
  "deliver": "Доставлять.",
  "delivery": "Доставка.",
  "demonstrate": "Продемонстрируйте.",
  "denouement": "Развязка.",
  "depart": "Уйти.",
  "departure": "Отправление.",
  "detrimental": "Вредно.",
  "device": "Устройство.",
  "diet": "Диета.",
  "dinner": "Ужин.",
  "direction": "Направление.",
  "dirty": "Грязный.",
  "discount": "Скидка.",
  "discourse": "Дискурс.",
  "discover": "Обнаружить.",
  "dissertation": "Диссертация.",
  "diversity": "Разнообразие.",
  "document": "Документировать.",
  "download": "Чтобы скачать.",
  "draw": "Рисовать.",
  "draw a conclusion": "Чтобы сделать вывод.",
  "dress": "Одеваться.",
  "drought": "Засуха.",
  "early": "Рано.",
  "earn": "Чтобы заработать.",
  "eco-friendly": "Экологичный.",
  "ecstatic": "В восторге.",
  "edit": "Редактировать.",
  "efficiency": "Эффективность.",
  "efficient": "Эффективный.",
  "election": "Выборы.",
  "eloquent": "Красноречиво.",
  "elucidate": "Разъясните.",
  "email": "Электронная почта.",
  "emission": "Эмиссия.",
  "emissions": "Выбросы.",
  "emphasise": "Подчеркивать.",
  "empirical": "Эмпирический.",
  "energy": "Энергия.",
  "engineer": "Инженер.",
  "enjoy": "Чтобы насладиться.",
  "enrol": "записаться.",
  "entrepreneurship": "Предпринимательство.",
  "equality": "Равенство.",
  "equivocal": "Двусмысленно.",
  "essentially": "По сути.",
  "estimate": "Оценивать.",
  "evening": "Вечер.",
  "evidence": "Доказательство.",
  "exacerbate": "Обострить.",
  "exam": "Экзамен.",
  "exchange": "Обмен.",
  "exercise": "Упражнение.",
  "expensive": "Дорогой.",
  "experience": "Опыт.",
  "experiment": "Экспериментируйте.",
  "explain": "Чтобы объяснить.",
  "extinct": "Вымерший.",
  "extracurricular": "Внеклассное.",
  "extrapolate": "экстраполировать.",
  "eyes": "Глаза.",
  "factor": "Фактор.",
  "fall behind": "Отставать.",
  "family": "Семья.",
  "fashion": "Мода.",
  "feasible": "Достижимый.",
  "figure out": "Понимать.",
  "film": "Фильм.",
  "fish": "Рыба.",
  "fit": "Соответствовать.",
  "fitness": "Фитнес.",
  "fitting room": "Примерочная.",
  "flat": "Плоский.",
  "flight": "Полет.",
  "flood": "Наводнение.",
  "fluctuate": "Колебаться.",
  "food for thought": "Пища для размышлений.",
  "football": "Футбол.",
  "forecast": "Прогноз.",
  "foreshadow": "предвещать.",
  "forest": "Лес.",
  "forgive": "Простить.",
  "form": "Форма.",
  "fossil fuel": "Ископаемое топливо.",
  "free time": "Свободное время.",
  "freedom": "Свобода.",
  "freelancer": "Фрилансер.",
  "freeze": "Замри.",
  "friendship": "Дружба.",
  "fruit": "Фрукты.",
  "frustrated": "Расстроенный.",
  "furniture": "Мебель.",
  "furthermore": "Более того.",
  "gadget": "Гаджет.",
  "gain insight": "Получите понимание.",
  "game": "Игра.",
  "garden": "Сад.",
  "gate": "Ворота.",
  "get along": "Чтобы ладить.",
  "get away with": "Чтобы сойти с рук.",
  "get out of hand": "выйти из-под контроля.",
  "get to grips with": "Чтобы разобраться.",
  "get up": "Чтобы встать.",
  "ghost": "Призрак.",
  "gift": "Подарок.",
  "go home": "Пойти домой.",
  "go the extra mile": "Чтобы пройти лишнюю милю.",
  "go through": "Чтобы пройти.",
  "go to work": "Чтобы пойти на работу.",
  "green": "Зеленый.",
  "greet": "поприветствовать.",
  "grey": "Серый.",
  "guarantee": "Гарантия.",
  "guidebook": "Путеводитель.",
  "gym": "Спортзал.",
  "habit": "Привычка.",
  "habitat": "Среда обитания.",
  "hair": "Волосы.",
  "handsome": "Красивый.",
  "hang on": "Подожди.",
  "haunted": "Преследуемый.",
  "have breakfast": "Позавтракать.",
  "have dinner": "Поужинать.",
  "have lunch": "Пообедать.",
  "headline": "Заголовок.",
  "healthy": "Здоровый.",
  "heartfelt": "Душевный.",
  "help": "Чтобы помочь.",
  "hence": "Следовательно.",
  "hesitate": "колебаться.",
  "hire": "Нанимать.",
  "hit the nail on the head": "чтобы попасть в точку.",
  "hobby": "Хобби.",
  "hold true": "Держитесь правды.",
  "hometown": "Родной город.",
  "honest": "Честный.",
  "hospital": "Больница.",
  "hostel": "Общежитие.",
  "hot": "Горячий.",
  "hotel": "Отель.",
  "hour": "Час.",
  "hundred": "Сто.",
  "hungry": "Голодный.",
  "husband": "Муж.",
  "hypothesis": "Гипотеза.",
  "illness": "Болезнь.",
  "illustrate": "Проиллюстрируйте.",
  "immune system": "Иммунная система.",
  "impact": "Влияние.",
  "implausible": "Неправдоподобно.",
  "implication": "Импликация.",
  "impulsive": "Импульсивный.",
  "in contrast": "В отличие.",
  "in the long run": "В долгосрочной перспективе.",
  "in the same boat": "В той же лодке.",
  "indecisive": "Нерешительный.",
  "indicate": "Указывать.",
  "inequality": "Неравенство.",
  "inevitable": "Неизбежный.",
  "inference": "Вывод.",
  "influence": "Влияние.",
  "infrastructure": "Инфраструктура.",
  "initially": "Изначально.",
  "injury": "Рана.",
  "innovation": "Инновации.",
  "innovative": "Инновационный.",
  "insurance": "Страхование.",
  "interest": "Интерес.",
  "internship": "Стажировка.",
  "interview": "Интервью.",
  "introduce": "представить.",
  "invent": "Изобретать.",
  "invest": "Инвестируйте.",
  "invite": "Приглашать.",
  "itinerary": "Маршрут.",
  "jacket": "Куртка.",
  "journalist": "Журналист.",
  "journey": "Путешествие.",
  "juice": "Сок.",
  "justice": "Справедливость.",
  "juxtaposition": "Сопоставление.",
  "keep in touch": "Чтобы оставаться на связи.",
  "keep one's word": "Чтобы сдержать свое слово.",
  "keep up with": "Чтобы не отставать.",
  "key": "Ключ.",
  "keys": "Ключи.",
  "kitchen": "Кухня.",
  "lab": "Лаб.",
  "laptop": "Ноутбук.",
  "late": "Поздно.",
  "law": "Закон.",
  "layoff": "Отвянь.",
  "leather": "Кожа.",
  "lecture": "Лекция.",
  "lend": "Одолжить.",
  "likewise": "Так же.",
  "listen": "Слушать.",
  "literacy": "Грамотность.",
  "living room": "Гостиная.",
  "lonely": "Одинокий.",
  "long": "Длинный.",
  "look": "Посмотреть.",
  "look down on": "Чтобы посмотреть вниз.",
  "look up to": "Чтобы равняться.",
  "lost": "Потерянный.",
  "loyal": "Лояльный.",
  "luggage": "Багаж.",
  "lunch": "Обед.",
  "make a decision": "Чтобы принять решение.",
  "make up for": "Чтобы компенсировать это.",
  "map": "Карта.",
  "married": "Женатый.",
  "mask": "Маска.",
  "meanwhile": "Тем временем.",
  "measure": "Мера.",
  "medicine": "Лекарство.",
  "meet": "Встретиться.",
  "meeting": "К встрече.",
  "melancholy": "Меланхолия.",
  "melt": "Таять.",
  "mental health": "Психическое здоровье.",
  "menu": "Меню.",
  "methodology": "Методология.",
  "minute": "Минута.",
  "miss": "Пропустить.",
  "miss the point": "Чтобы упустить суть.",
  "missed": "Пропущенный.",
  "mitigate": "чтобы смягчить.",
  "monster": "Монстр.",
  "month": "Месяц.",
  "more expensive": "Дороже.",
  "moreover": "Более того.",
  "morning": "Утро.",
  "move": "Переехать.",
  "music": "Музыка.",
  "name": "К данному имени.",
  "namely": "А именно.",
  "nationality": "Национальность, гражданство.",
  "nearby": "Рядом.",
  "negligible": "Незначительный.",
  "negotiate": "вести переговоры.",
  "neighbour": "Сосед.",
  "neighbourhood": "Район.",
  "network": "Сеть.",
  "never": "Никогда.",
  "nevertheless": "Тем не менее.",
  "night": "Ночь.",
  "nonetheless": "Тем не менее.",
  "nostalgic": "Ностальгия.",
  "notably": "Примечательно.",
  "notebook": "Блокнот.",
  "notification": "Уведомление.",
  "nuanced": "Нюансы.",
  "o'clock": "Час.",
  "objective": "Цель.",
  "observe": "Наблюдать.",
  "occupation": "Работа, профессия.",
  "ocean": "Океан.",
  "offline": "Офлайн.",
  "often": "Часто.",
  "old": "Старый.",
  "on the fence": "На заборе.",
  "on the whole": "В целом.",
  "on thin ice": "По тонкому льду.",
  "once in a blue moon": "Однажды в голубую луну.",
  "one": "Один.",
  "online": "Онлайн.",
  "online shopping": "Интернет-шопинг.",
  "open": "Открыть.",
  "opposite": "Противоположный.",
  "orange": "Апельсин.",
  "order": "Заказ.",
  "organic": "Органический.",
  "outweigh": "перевесить.",
  "overall": "Общий.",
  "overtime": "Через некоторое время.",
  "overweight": "Лишний вес.",
  "overwhelmed": "Перегруженный.",
  "overwhelming": "Подавляющий.",
  "owe": "Быть должным.",
  "paint": "Рисовать.",
  "paradigm": "Парадигма.",
  "paramount": "Первостепенное.",
  "parents": "Родители.",
  "parking": "Стоянка.",
  "parsimonious": "Скромный.",
  "partner": "Партнер.",
  "party": "Вечеринка.",
  "passenger": "Пассажир.",
  "passport": "Паспорт.",
  "password": "Пароль.",
  "patent": "Патент.",
  "pedestrian": "Пешеход.",
  "perspective": "Перспектива.",
  "persuade": "Убеждать.",
  "pharmacy": "Аптека.",
  "phenomenon": "Феномен.",
  "phone number": "Номер телефона.",
  "photograph": "Фотография.",
  "pink": "Розовый.",
  "plagiarism": "Плагиат.",
  "platform": "Платформа.",
  "plausible": "Правдоподобно.",
  "play a role": "Чтобы сыграть роль.",
  "play it by ear": "Чтобы играть на слух.",
  "poignant": "Пронзительно.",
  "point out": "Укажите.",
  "police": "Полиция.",
  "policy": "Политика.",
  "polite": "Вежливый.",
  "pollution": "Загрязнение.",
  "pose a threat": "Представлять угрозу.",
  "post office": "Почтовое отделение.",
  "precise": "Точный.",
  "prefer": "Предпочитать.",
  "prescribe": "прописать.",
  "presumably": "Предположительно.",
  "prevention": "Профилактика.",
  "price": "Цена.",
  "prioritize": "расставить приоритеты.",
  "privacy": "Конфиденциальность.",
  "proliferate": "размножаться.",
  "promote": "Продвигать.",
  "promotion": "Повышение.",
  "proportion": "Пропорция.",
  "prose": "Проза.",
  "prospective": "Перспективный.",
  "protest": "Протест.",
  "prototype": "Прототип.",
  "provide evidence": "Чтобы предоставить доказательства.",
  "publish": "Публиковать.",
  "pull someone's leg": "тянуть чью-либо ногу.",
  "pumpkin": "Тыква.",
  "put forward": "Выдвигать.",
  "put off": "Отложить.",
  "put up with": "Мириться.",
  "qualitative": "Качественный.",
  "quality": "Качество.",
  "quantitative": "Количественный.",
  "queue": "Очередь.",
  "quiet": "Тихий.",
  "quintessential": "Квинтэссенция.",
  "rain": "Дождь.",
  "rainy": "Дождливо.",
  "raise awareness": "Повышайте осведомленность.",
  "rarely": "Редко.",
  "reach an agreement": "Достичь соглашения.",
  "read": "Читать.",
  "read between the lines": "читать между строк.",
  "receipt": "Квитанция.",
  "reckon": "считать, предполагать.",
  "reconcile": "Примириться.",
  "recover": "восстановиться.",
  "recycle": "Переработка.",
  "red": "Красный.",
  "redundancy": "Избыточность.",
  "refugee": "Беженец.",
  "refund": "Возвращать деньги.",
  "register": "Зарегистрируйтесь.",
  "relative": "Родственник.",
  "relax": "Расслабляться.",
  "reliable": "Надежный.",
  "renewable": "Возобновляемый.",
  "rent": "Арендовать.",
  "repair": "Ремонт.",
  "research": "Исследовать.",
  "resentful": "Обиженный.",
  "reservation": "Бронирование.",
  "resign": "Подать в отставку.",
  "resolution": "Разрешение.",
  "respect": "Уважать.",
  "respectively": "Соответственно.",
  "responsible": "Ответственный.",
  "rest": "Отдых.",
  "restaurant": "Ресторан.",
  "return": "Вернуться.",
  "rhetoric": "Риторика.",
  "rights": "Права.",
  "risk": "Риск.",
  "robot": "Робот.",
  "roundabout": "Карусель.",
  "rude": "Грубый.",
  "rumour": "Слух.",
  "run out of": "Чтобы иссякнуть.",
  "running": "Чтобы бежать.",
  "salary": "Зарплата.",
  "sale": "Распродажа.",
  "satirical": "Сатирический.",
  "save": "Чтобы сохранить.",
  "scarce": "Редко.",
  "scared": "Испуганный.",
  "scary": "Страшный.",
  "schedule": "Расписание.",
  "scholarship": "Стипендия.",
  "seaside": "Приморский.",
  "sedentary": "Сидячий.",
  "seminar": "Семинар.",
  "series": "Ряд.",
  "set the bar high": "Установите высокую планку.",
  "set up": "Настраивать.",
  "share": "Поделиться.",
  "shift": "Сдвиг.",
  "shirt": "Рубашка.",
  "shoes": "Обувь.",
  "shop assistant": "Продавец-консультант.",
  "short": "Короткий.",
  "sightseeing": "Осмотр достопримечательностей.",
  "sign": "Знак.",
  "significant": "Значительный.",
  "sing": "Петь.",
  "single": "Одинокий.",
  "sister": "Сестра.",
  "size": "Размер.",
  "skill": "Навык.",
  "sleep": "Спать.",
  "small": "Маленький.",
  "smartphone": "Смартфон.",
  "smile": "Улыбка.",
  "snow": "Снег.",
  "snowy": "Снежный.",
  "software": "Программное обеспечение.",
  "soil": "Земля.",
  "sometimes": "Иногда.",
  "source": "Источник.",
  "souvenir": "Сувенир.",
  "species": "Разновидность.",
  "specifically": "Конкретно.",
  "spell": "писать.",
  "spend": "Тратить.",
  "sport": "Спорт.",
  "sprain": "Растяжение.",
  "spring": "Весна.",
  "stamina": "Выносливость.",
  "stand out": "Чтобы выделиться.",
  "start": "Для начала.",
  "station": "Станция.",
  "storm": "Шторм.",
  "streaming": "Стриминг.",
  "stress": "Стресс.",
  "study": "Учиться.",
  "subjective": "Субъективно.",
  "subscription": "Подписка.",
  "subsequently": "Впоследствии.",
  "substantial": "Существенный.",
  "substantiate": "обосновать.",
  "subtle": "Тонкий.",
  "suitcase": "Чемодан.",
  "summer": "Лето.",
  "sunny": "Солнечно.",
  "sunshine": "Солнечный свет.",
  "supermarket": "Супермаркет.",
  "support": "Поддерживать.",
  "surname": "Фамилия.",
  "sustainability": "Устойчивость.",
  "sustainable": "Устойчивый.",
  "swimming": "Плавание.",
  "symptom": "Симптом.",
  "synthesize": "синтезировать.",
  "take aback": "ошеломить.",
  "take into account": "Чтобы принять во внимание.",
  "take with a grain of salt": "Принимать с недоверием.",
  "tall": "Высокий.",
  "taste": "По вкусу.",
  "tax": "Налог.",
  "tea": "Чай.",
  "temperature": "Температура.",
  "ten": "Десять.",
  "tentative": "Пробный.",
  "terse": "Кратковременно.",
  "the ball is in your court": "мяч на вашей площадке.",
  "the best": "лучшее.",
  "the bottom line": "нижняя строка.",
  "the tip of the iceberg": "верхушка айсберга.",
  "theory": "Теория.",
  "therefore": "Поэтому.",
  "thesis": "Диссертация.",
  "think outside the box": "Думать нестандартно.",
  "thirsty": "Испытывающий жажду.",
  "threat": "Угроза.",
  "three": "Три.",
  "thus": "Таким образом.",
  "ticket": "Билет.",
  "timetable": "Расписание.",
  "to a large extent": "в значительной степени.",
  "today": "Сегодня.",
  "tomorrow": "Завтра.",
  "town hall": "Ратуша.",
  "train": "Тренироваться.",
  "transfer": "Передача.",
  "trend": "Тренд.",
  "trick or treat": "Кошелек или жизнь.",
  "trousers": "Брюки.",
  "trust": "Доверять.",
  "try on": "Чтобы примерить.",
  "tuition": "Обучение.",
  "turn down": "Отказаться.",
  "turn out": "Чтобы получиться.",
  "two": "Два.",
  "ultimately": "В конечном счете.",
  "umbrella": "Зонтик.",
  "undermine": "подорвать.",
  "underscore": "Подчеркивание.",
  "unprecedented": "Беспрецедентный.",
  "update": "Обновлять.",
  "upload": "Загрузить.",
  "urbanisation": "Урбанизация.",
  "usually": "Обычно.",
  "vaccine": "Вакцина.",
  "vampire": "Вампир.",
  "vegetable": "Овощной.",
  "vernacular": "Народный.",
  "viral": "Популярный.",
  "visa": "Виза.",
  "wait": "Ждать.",
  "wake up": "проснуться.",
  "walk": "Гулять.",
  "wallet": "Кошелек.",
  "warm": "Теплый.",
  "warranty": "Гарантия.",
  "wash": "Мыть.",
  "waste": "Напрасно тратить.",
  "watch": "Смотреть.",
  "water": "Вода.",
  "wear": "Носить.",
  "weather": "Погода.",
  "weather the storm": "Выдержите шторм.",
  "week": "Неделя.",
  "weekend": "Выходные.",
  "weigh up": "взвесить.",
  "wellbeing": "Благополучие.",
  "wellness": "Оздоровление.",
  "whereas": "Тогда как.",
  "whilst": "Пока.",
  "white": "Белый.",
  "wi-fi": "Wi-Fi.",
  "wife": "Жена.",
  "wildlife": "Дикая природа.",
  "wind": "Ветер.",
  "windy": "Ветрено.",
  "winter": "Зима.",
  "witch": "Ведьма.",
  "with regard to": "В отношении к.",
  "work": "Работать.",
  "work out": "Чтобы потренироваться.",
  "workload": "К загруженности.",
  "worth": "Ценность.",
  "write": "Писать.",
  "year": "Год.",
  "yellow": "Желтый.",
  "yesterday": "Вчера.",
  "young": "Молодой.",
  },
  en: {
  "a blessing in disguise": "a blessing in disguise.",
  "a double-edged sword": "a double-edged sword.",
  "a rule of thumb": "a rule of thumb.",
  "abundant": "Abundant.",
  "account": "Account.",
  "account for": "Account for.",
  "accurate": "Accurate.",
  "address": "Address.",
  "address an issue": "Address an issue.",
  "admittedly": "Admittedly.",
  "afford": "Afford.",
  "afraid": "Afraid.",
  "afternoon": "Afternoon.",
  "age": "Age.",
  "ailment": "Ailment.",
  "airport": "Airport.",
  "alarm clock": "Alarm clock.",
  "albeit": "Albeit.",
  "allegory": "Allegory.",
  "always": "Always.",
  "ambiguous": "Ambiguous.",
  "apologise": "Apologise.",
  "app": "App.",
  "apply": "Apply.",
  "appointment": "Appointment.",
  "apprehensive": "Apprehensive.",
  "approach": "Approach.",
  "aptitude": "Aptitude.",
  "arcane": "Arcane.",
  "arguably": "Arguably.",
  "argue": "Argue.",
  "argument": "Argument.",
  "arrival": "Arrival.",
  "arrive": "To arrive.",
  "artificial intelligence": "Artificial intelligence.",
  "as a result": "As a result.",
  "ask": "To ask.",
  "assess": "Assess.",
  "assignment": "Assignment.",
  "astonished": "Astonished.",
  "at the end of the day": "At the end of the day.",
  "atm": "ATM.",
  "audience": "Audience.",
  "automate": "Automate.",
  "automation": "Automation.",
  "autumn": "Autumn.",
  "awareness": "Awareness.",
  "backup": "Backup.",
  "balance": "Balance.",
  "ban": "Ban.",
  "bank": "Bank.",
  "bargain": "Bargain.",
  "bargain hunter": "Bargain hunter.",
  "bathroom": "Bathroom.",
  "bear in mind": "Bear in mind.",
  "beautiful": "Beautiful.",
  "bedroom": "Bedroom.",
  "beneficial": "Beneficial.",
  "between": "Between.",
  "bias": "Bias.",
  "big": "Big.",
  "bill": "Bill.",
  "biodiversity": "Biodiversity.",
  "bittersweet": "Bittersweet.",
  "black": "Black.",
  "blue": "Blue.",
  "boarding pass": "Boarding pass.",
  "book": "Book.",
  "booked": "Booked.",
  "booking": "Booking.",
  "borrow": "To borrow.",
  "brand": "Brand.",
  "bread": "Bread.",
  "break down": "To break down.",
  "break the ice": "to break the ice.",
  "breakfast": "Breakfast.",
  "breakthrough": "Breakthrough.",
  "bring about": "To bring about.",
  "bring up": "To bring up.",
  "broadcast": "Broadcast.",
  "brother": "Brother.",
  "brown": "Brown.",
  "brush": "Brush.",
  "brush teeth": "to brush one's teeth.",
  "budget": "Budget.",
  "burn the candle at both ends": "to burn the candle at both ends.",
  "burn the midnight oil": "Burn the midnight oil.",
  "burnout": "Burnout.",
  "burst into tears": "to burst into tears.",
  "bus": "Bus.",
  "call": "To call.",
  "call for": "To call for.",
  "call it a day": "to call it a day.",
  "campaign": "Campaign.",
  "cancel": "Cancel.",
  "cancelled": "Cancelled.",
  "carbon footprint": "Carbon footprint.",
  "card": "Card.",
  "carry out": "Carry out.",
  "cash": "Cash.",
  "cash register": "Cash register.",
  "cast doubt": "Cast doubt.",
  "catch up": "Catch up.",
  "celebrate": "Celebrate.",
  "cemetery": "Cemetery.",
  "censorship": "Censorship.",
  "change": "To change.",
  "charge": "Charge.",
  "cheap": "Cheap.",
  "cheaper": "Cheaper.",
  "check in": "Check in.",
  "check-up": "Check-up.",
  "checkout": "Checkout.",
  "cheese": "Cheese.",
  "chicken": "Chicken.",
  "child": "Child.",
  "chronic": "Chronic.",
  "citizen": "Citizen.",
  "claim": "Claim.",
  "classmate": "Classmate.",
  "clean": "To clean.",
  "climate": "Climate.",
  "climb the ladder": "to climb the ladder.",
  "close": "Close.",
  "cloud": "Cloud.",
  "cloudy": "Cloudy.",
  "club": "Club.",
  "coffee": "Coffee.",
  "coherent": "Coherent.",
  "cold": "Cold.",
  "colleague": "Colleague.",
  "collect": "Collect.",
  "come across": "To come across.",
  "come into force": "To come into force.",
  "come to terms with": "To come to terms with.",
  "come up with": "To come up with.",
  "comfortable": "Comfortable.",
  "commitment": "Commitment.",
  "community": "Community.",
  "commute": "to commute.",
  "compelling": "Compelling.",
  "comprehensive": "Comprehensive.",
  "conclude": "Conclude.",
  "conscientious": "Conscientious.",
  "consequence": "Consequence.",
  "conservation": "Conservation.",
  "conserve": "Conserve.",
  "consist of": "Consist of.",
  "contentious": "Contentious.",
  "contribute": "Contribute.",
  "controversial": "Controversial.",
  "conversation": "Conversation.",
  "conversely": "Conversely.",
  "cook": "To cook.",
  "cool": "Cool.",
  "corner": "Corner.",
  "correlate": "to correlate.",
  "corroborate": "to corroborate.",
  "costume": "Costume.",
  "cotton": "Cotton.",
  "crime": "Crime.",
  "crisis": "Crisis.",
  "cross that bridge when we come to it": "Cross that bridge when we come to it.",
  "crossroads": "Crossroads.",
  "crucially": "Crucially.",
  "currency": "Currency.",
  "curriculum": "Curriculum.",
  "customer": "Customer.",
  "customs": "Customs.",
  "cut corners": "To cut corners.",
  "cut down on": "To cut down on.",
  "cybersecurity": "Cybersecurity.",
  "dance": "Dance.",
  "data": "Data.",
  "deadline": "Deadline.",
  "debate": "Debate.",
  "debt": "Debt.",
  "decisive": "Decisive.",
  "degree": "Degree.",
  "delay": "Delay.",
  "delayed": "Delayed.",
  "deliberate": "Deliberate.",
  "delicious": "Delicious.",
  "deliver": "Deliver.",
  "delivery": "Delivery.",
  "demonstrate": "Demonstrate.",
  "denouement": "Denouement.",
  "depart": "Depart.",
  "departure": "Departure.",
  "detrimental": "Detrimental.",
  "device": "Device.",
  "diet": "Diet.",
  "dinner": "Dinner.",
  "direction": "Direction.",
  "dirty": "Dirty.",
  "discount": "Discount.",
  "discourse": "Discourse.",
  "discover": "Discover.",
  "dissertation": "Dissertation.",
  "diversity": "Diversity.",
  "document": "To document.",
  "download": "To download.",
  "draw": "To draw.",
  "draw a conclusion": "To draw a conclusion.",
  "dress": "Dress.",
  "drought": "Drought.",
  "early": "Early.",
  "earn": "To earn.",
  "eco-friendly": "Eco-friendly.",
  "ecstatic": "Ecstatic.",
  "edit": "Edit.",
  "efficiency": "Efficiency.",
  "efficient": "Efficient.",
  "election": "Election.",
  "eloquent": "Eloquent.",
  "elucidate": "Elucidate.",
  "email": "Email.",
  "emission": "Emission.",
  "emissions": "Emissions.",
  "emphasise": "Emphasise.",
  "empirical": "Empirical.",
  "energy": "Energy.",
  "engineer": "Engineer.",
  "enjoy": "To enjoy.",
  "enrol": "to enrol.",
  "entrepreneurship": "Entrepreneurship.",
  "equality": "Equality.",
  "equivocal": "Equivocal.",
  "essentially": "Essentially.",
  "estimate": "Estimate.",
  "evening": "Evening.",
  "evidence": "Evidence.",
  "exacerbate": "Exacerbate.",
  "exam": "Exam.",
  "exchange": "Exchange.",
  "exercise": "Exercise.",
  "expensive": "Expensive.",
  "experience": "Experience.",
  "experiment": "Experiment.",
  "explain": "To explain.",
  "extinct": "Extinct.",
  "extracurricular": "Extracurricular.",
  "extrapolate": "to extrapolate.",
  "eyes": "Eyes.",
  "factor": "Factor.",
  "fall behind": "To fall behind.",
  "family": "Family.",
  "fashion": "Fashion.",
  "feasible": "Feasible.",
  "figure out": "Figure out.",
  "film": "Film.",
  "fish": "Fish.",
  "fit": "Fit.",
  "fitness": "Fitness.",
  "fitting room": "Fitting room.",
  "flat": "Flat.",
  "flight": "Flight.",
  "flood": "Flood.",
  "fluctuate": "Fluctuate.",
  "food for thought": "Food for thought.",
  "football": "Football.",
  "forecast": "Forecast.",
  "foreshadow": "to foreshadow.",
  "forest": "Forest.",
  "forgive": "Forgive.",
  "form": "Form.",
  "fossil fuel": "Fossil fuel.",
  "free time": "Free time.",
  "freedom": "Freedom.",
  "freelancer": "Freelancer.",
  "freeze": "Freeze.",
  "friendship": "Friendship.",
  "fruit": "Fruit.",
  "frustrated": "Frustrated.",
  "furniture": "Furniture.",
  "furthermore": "Furthermore.",
  "gadget": "Gadget.",
  "gain insight": "Gain insight.",
  "game": "Game.",
  "garden": "Garden.",
  "gate": "Gate.",
  "get along": "To get along.",
  "get away with": "To get away with.",
  "get out of hand": "to get out of hand.",
  "get to grips with": "To get to grips with.",
  "get up": "To get up.",
  "ghost": "Ghost.",
  "gift": "Gift.",
  "go home": "To go home.",
  "go the extra mile": "To go the extra mile.",
  "go through": "To go through.",
  "go to work": "To go to work.",
  "green": "Green.",
  "greet": "to greet.",
  "grey": "Grey.",
  "guarantee": "Guarantee.",
  "guidebook": "Guidebook.",
  "gym": "Gym.",
  "habit": "Habit.",
  "habitat": "Habitat.",
  "hair": "Hair.",
  "handsome": "Handsome.",
  "hang on": "Hang on.",
  "haunted": "Haunted.",
  "have breakfast": "To have breakfast.",
  "have dinner": "To have dinner.",
  "have lunch": "To have lunch.",
  "headline": "Headline.",
  "healthy": "Healthy.",
  "heartfelt": "Heartfelt.",
  "help": "To help.",
  "hence": "Hence.",
  "hesitate": "to hesitate.",
  "hire": "Hire.",
  "hit the nail on the head": "to hit the nail on the head.",
  "hobby": "Hobby.",
  "hold true": "Hold true.",
  "hometown": "Hometown.",
  "honest": "Honest.",
  "hospital": "Hospital.",
  "hostel": "Hostel.",
  "hot": "Hot.",
  "hotel": "Hotel.",
  "hour": "Hour.",
  "hundred": "Hundred.",
  "hungry": "Hungry.",
  "husband": "Husband.",
  "hypothesis": "Hypothesis.",
  "illness": "Illness.",
  "illustrate": "Illustrate.",
  "immune system": "Immune system.",
  "impact": "Impact.",
  "implausible": "Implausible.",
  "implication": "Implication.",
  "impulsive": "Impulsive.",
  "in contrast": "In contrast.",
  "in the long run": "In the long run.",
  "in the same boat": "In the same boat.",
  "indecisive": "Indecisive.",
  "indicate": "Indicate.",
  "inequality": "Inequality.",
  "inevitable": "Inevitable.",
  "inference": "Inference.",
  "influence": "Influence.",
  "infrastructure": "Infrastructure.",
  "initially": "Initially.",
  "injury": "Injury.",
  "innovation": "Innovation.",
  "innovative": "Innovative.",
  "insurance": "Insurance.",
  "interest": "Interest.",
  "internship": "Internship.",
  "interview": "Interview.",
  "introduce": "to introduce.",
  "invent": "Invent.",
  "invest": "Invest.",
  "invite": "Invite.",
  "itinerary": "Itinerary.",
  "jacket": "Jacket.",
  "journalist": "Journalist.",
  "journey": "Journey.",
  "juice": "Juice.",
  "justice": "Justice.",
  "juxtaposition": "Juxtaposition.",
  "keep in touch": "To keep in touch.",
  "keep one's word": "To keep one's word.",
  "keep up with": "To keep up with.",
  "key": "Key.",
  "keys": "Keys.",
  "kitchen": "Kitchen.",
  "lab": "Lab.",
  "laptop": "Laptop.",
  "late": "Late.",
  "law": "Law.",
  "layoff": "Layoff.",
  "leather": "Leather.",
  "lecture": "Lecture.",
  "lend": "To lend.",
  "likewise": "Likewise.",
  "listen": "To listen.",
  "literacy": "Literacy.",
  "living room": "Living room.",
  "lonely": "Lonely.",
  "long": "Long.",
  "look": "To look.",
  "look down on": "To look down on.",
  "look up to": "To look up to.",
  "lost": "Lost.",
  "loyal": "Loyal.",
  "luggage": "Luggage.",
  "lunch": "Lunch.",
  "make a decision": "To make a decision.",
  "make up for": "To make up for.",
  "map": "Map.",
  "married": "Married.",
  "mask": "Mask.",
  "meanwhile": "Meanwhile.",
  "measure": "Measure.",
  "medicine": "Medicine.",
  "meet": "To meet.",
  "meeting": "To meeting.",
  "melancholy": "Melancholy.",
  "melt": "Melt.",
  "mental health": "Mental health.",
  "menu": "Menu.",
  "methodology": "Methodology.",
  "minute": "Minute.",
  "miss": "To miss.",
  "miss the point": "To miss the point.",
  "missed": "Missed.",
  "mitigate": "to mitigate.",
  "monster": "Monster.",
  "month": "Month.",
  "more expensive": "More expensive.",
  "moreover": "Moreover.",
  "morning": "Morning.",
  "move": "To move.",
  "music": "Music.",
  "name": "To given name.",
  "namely": "Namely.",
  "nationality": "Nationality, citizenship.",
  "nearby": "Nearby.",
  "negligible": "Negligible.",
  "negotiate": "to negotiate.",
  "neighbour": "Neighbour.",
  "neighbourhood": "Neighbourhood.",
  "network": "Network.",
  "never": "Never.",
  "nevertheless": "Nevertheless.",
  "night": "Night.",
  "nonetheless": "Nonetheless.",
  "nostalgic": "Nostalgic.",
  "notably": "Notably.",
  "notebook": "Notebook.",
  "notification": "Notification.",
  "nuanced": "Nuanced.",
  "o'clock": "O'clock.",
  "objective": "Objective.",
  "observe": "Observe.",
  "occupation": "Job, profession.",
  "ocean": "Ocean.",
  "offline": "Offline.",
  "often": "Often.",
  "old": "Old.",
  "on the fence": "On the fence.",
  "on the whole": "On the whole.",
  "on thin ice": "On thin ice.",
  "once in a blue moon": "Once in a blue moon.",
  "one": "One.",
  "online": "Online.",
  "online shopping": "Online shopping.",
  "open": "To open.",
  "opposite": "Opposite.",
  "orange": "Orange.",
  "order": "Order.",
  "organic": "Organic.",
  "outweigh": "to outweigh.",
  "overall": "Overall.",
  "overtime": "Overtime.",
  "overweight": "Overweight.",
  "overwhelmed": "Overwhelmed.",
  "overwhelming": "Overwhelming.",
  "owe": "Owe.",
  "paint": "To paint.",
  "paradigm": "Paradigm.",
  "paramount": "Paramount.",
  "parents": "Parents.",
  "parking": "Parking.",
  "parsimonious": "Parsimonious.",
  "partner": "Partner.",
  "party": "Party.",
  "passenger": "Passenger.",
  "passport": "Passport.",
  "password": "Password.",
  "patent": "Patent.",
  "pedestrian": "Pedestrian.",
  "perspective": "Perspective.",
  "persuade": "Persuade.",
  "pharmacy": "Pharmacy.",
  "phenomenon": "Phenomenon.",
  "phone number": "Phone number.",
  "photograph": "Photograph.",
  "pink": "Pink.",
  "plagiarism": "Plagiarism.",
  "platform": "Platform.",
  "plausible": "Plausible.",
  "play a role": "To play a role.",
  "play it by ear": "To play it by ear.",
  "poignant": "Poignant.",
  "point out": "Point out.",
  "police": "Police.",
  "policy": "Policy.",
  "polite": "Polite.",
  "pollution": "Pollution.",
  "pose a threat": "Pose a threat.",
  "post office": "Post office.",
  "precise": "Precise.",
  "prefer": "To prefer.",
  "prescribe": "to prescribe.",
  "presumably": "Presumably.",
  "prevention": "Prevention.",
  "price": "Price.",
  "prioritize": "to prioritize.",
  "privacy": "Privacy.",
  "proliferate": "to proliferate.",
  "promote": "Promote.",
  "promotion": "Promotion.",
  "proportion": "Proportion.",
  "prose": "Prose.",
  "prospective": "Prospective.",
  "protest": "Protest.",
  "prototype": "Prototype.",
  "provide evidence": "To provide evidence.",
  "publish": "Publish.",
  "pull someone's leg": "to pull someone's leg.",
  "pumpkin": "Pumpkin.",
  "put forward": "To put forward.",
  "put off": "To put off.",
  "put up with": "To put up with.",
  "qualitative": "Qualitative.",
  "quality": "Quality.",
  "quantitative": "Quantitative.",
  "queue": "Queue.",
  "quiet": "Quiet.",
  "quintessential": "Quintessential.",
  "rain": "Rain.",
  "rainy": "Rainy.",
  "raise awareness": "Raise awareness.",
  "rarely": "Rarely.",
  "reach an agreement": "Reach an agreement.",
  "read": "To read.",
  "read between the lines": "to read between the lines.",
  "receipt": "Receipt.",
  "reckon": "to reckon, to suppose.",
  "reconcile": "Reconcile.",
  "recover": "to recover.",
  "recycle": "Recycle.",
  "red": "Red.",
  "redundancy": "Redundancy.",
  "refugee": "Refugee.",
  "refund": "Refund.",
  "register": "Register.",
  "relative": "Relative.",
  "relax": "Relax.",
  "reliable": "Reliable.",
  "renewable": "Renewable.",
  "rent": "Rent.",
  "repair": "Repair.",
  "research": "Research.",
  "resentful": "Resentful.",
  "reservation": "Reservation.",
  "resign": "Resign.",
  "resolution": "Resolution.",
  "respect": "Respect.",
  "respectively": "Respectively.",
  "responsible": "Responsible.",
  "rest": "Rest.",
  "restaurant": "Restaurant.",
  "return": "To return.",
  "rhetoric": "Rhetoric.",
  "rights": "Rights.",
  "risk": "Risk.",
  "robot": "Robot.",
  "roundabout": "Roundabout.",
  "rude": "Rude.",
  "rumour": "Rumour.",
  "run out of": "To run out of.",
  "running": "To running.",
  "salary": "Salary.",
  "sale": "Sale.",
  "satirical": "Satirical.",
  "save": "To save.",
  "scarce": "Scarce.",
  "scared": "Scared.",
  "scary": "Scary.",
  "schedule": "Schedule.",
  "scholarship": "Scholarship.",
  "seaside": "Seaside.",
  "sedentary": "Sedentary.",
  "seminar": "Seminar.",
  "series": "Series.",
  "set the bar high": "Set the bar high.",
  "set up": "Set up.",
  "share": "To share.",
  "shift": "Shift.",
  "shirt": "Shirt.",
  "shoes": "Shoes.",
  "shop assistant": "Shop assistant.",
  "short": "Short.",
  "sightseeing": "Sightseeing.",
  "sign": "Sign.",
  "significant": "Significant.",
  "sing": "To sing.",
  "single": "Single.",
  "sister": "Sister.",
  "size": "Size.",
  "skill": "Skill.",
  "sleep": "To sleep.",
  "small": "Small.",
  "smartphone": "Smartphone.",
  "smile": "Smile.",
  "snow": "Snow.",
  "snowy": "Snowy.",
  "software": "Software.",
  "soil": "Soil.",
  "sometimes": "Sometimes.",
  "source": "Source.",
  "souvenir": "Souvenir.",
  "species": "Species.",
  "specifically": "Specifically.",
  "spell": "to spell.",
  "spend": "To spend.",
  "sport": "Sport.",
  "sprain": "Sprain.",
  "spring": "Spring.",
  "stamina": "Stamina.",
  "stand out": "To stand out.",
  "start": "To start.",
  "station": "Station.",
  "storm": "Storm.",
  "streaming": "Streaming.",
  "stress": "Stress.",
  "study": "To study.",
  "subjective": "Subjective.",
  "subscription": "Subscription.",
  "subsequently": "Subsequently.",
  "substantial": "Substantial.",
  "substantiate": "to substantiate.",
  "subtle": "Subtle.",
  "suitcase": "Suitcase.",
  "summer": "Summer.",
  "sunny": "Sunny.",
  "sunshine": "Sunshine.",
  "supermarket": "Supermarket.",
  "support": "Support.",
  "surname": "Family name.",
  "sustainability": "Sustainability.",
  "sustainable": "Sustainable.",
  "swimming": "Swimming.",
  "symptom": "Symptom.",
  "synthesize": "to synthesize.",
  "take aback": "to take aback.",
  "take into account": "To take into account.",
  "take with a grain of salt": "To take with a grain of salt.",
  "tall": "Tall.",
  "taste": "To taste.",
  "tax": "Tax.",
  "tea": "Tea.",
  "temperature": "Temperature.",
  "ten": "Ten.",
  "tentative": "Tentative.",
  "terse": "Terse.",
  "the ball is in your court": "the ball is in your court.",
  "the best": "the best.",
  "the bottom line": "the bottom line.",
  "the tip of the iceberg": "the tip of the iceberg.",
  "theory": "Theory.",
  "therefore": "Therefore.",
  "thesis": "Thesis.",
  "think outside the box": "To think outside the box.",
  "thirsty": "Thirsty.",
  "threat": "Threat.",
  "three": "Three.",
  "thus": "Thus.",
  "ticket": "Ticket.",
  "timetable": "Timetable.",
  "to a large extent": "to a large extent.",
  "today": "Today.",
  "tomorrow": "Tomorrow.",
  "town hall": "Town hall.",
  "train": "Train.",
  "transfer": "Transfer.",
  "trend": "Trend.",
  "trick or treat": "Trick or treat.",
  "trousers": "Trousers.",
  "trust": "Trust.",
  "try on": "To try on.",
  "tuition": "Tuition.",
  "turn down": "To turn down.",
  "turn out": "To turn out.",
  "two": "Two.",
  "ultimately": "Ultimately.",
  "umbrella": "Umbrella.",
  "undermine": "to undermine.",
  "underscore": "Underscore.",
  "unprecedented": "Unprecedented.",
  "update": "Update.",
  "upload": "Upload.",
  "urbanisation": "Urbanisation.",
  "usually": "Usually.",
  "vaccine": "Vaccine.",
  "vampire": "Vampire.",
  "vegetable": "Vegetable.",
  "vernacular": "Vernacular.",
  "viral": "Viral.",
  "visa": "Visa.",
  "wait": "To wait.",
  "wake up": "to wake up.",
  "walk": "To walk.",
  "wallet": "Wallet.",
  "warm": "Warm.",
  "warranty": "Warranty.",
  "wash": "To wash.",
  "waste": "Waste.",
  "watch": "To watch.",
  "water": "Water.",
  "wear": "To wear.",
  "weather": "Weather.",
  "weather the storm": "Weather the storm.",
  "week": "Week.",
  "weekend": "Weekend.",
  "weigh up": "to weigh up.",
  "wellbeing": "Wellbeing.",
  "wellness": "Wellness.",
  "whereas": "Whereas.",
  "whilst": "Whilst.",
  "white": "White.",
  "wi-fi": "Wi-Fi.",
  "wife": "Wife.",
  "wildlife": "Wildlife.",
  "wind": "Wind.",
  "windy": "Windy.",
  "winter": "Winter.",
  "witch": "Witch.",
  "with regard to": "With regard to.",
  "work": "To work.",
  "work out": "To work out.",
  "workload": "To workload.",
  "worth": "Worth.",
  "write": "To write.",
  "year": "Year.",
  "yellow": "Yellow.",
  "yesterday": "Yesterday.",
  "young": "Young.",
  },
  es: {
  "a blessing in disguise": "una bendición disfrazada.",
  "a double-edged sword": "un arma de doble filo.",
  "a rule of thumb": "una regla general.",
  "abundant": "Abundante.",
  "account": "Cuenta.",
  "account for": "Explicar.",
  "accurate": "Precisa",
  "address": "DIRECCIÓN.",
  "address an issue": "Abordar un problema.",
  "admittedly": "Cierto es que.",
  "afford": "Poder pagar.",
  "afraid": "Asustada.",
  "afternoon": "Tarde.",
  "age": "Edad.",
  "ailment": "Enfermedad.",
  "airport": "Aeropuerto.",
  "alarm clock": "Despertador.",
  "albeit": "Aunque.",
  "allegory": "Alegoría.",
  "always": "Siempre.",
  "ambiguous": "Ambigua.",
  "apologise": "Disculparse.",
  "app": "Aplicación.",
  "apply": "Aplicar.",
  "appointment": "Cita.",
  "apprehensive": "Aprensiva.",
  "approach": "Acercarse.",
  "aptitude": "Aptitud.",
  "arcane": "Arcana.",
  "arguably": "Podría decirse que.",
  "argue": "Argumentar.",
  "argument": "Argumento.",
  "arrival": "Llegada.",
  "arrive": "Para llegar.",
  "artificial intelligence": "Inteligencia artificial.",
  "as a result": "Como resultado.",
  "ask": "Para preguntar.",
  "assess": "Evaluar.",
  "assignment": "Asignación.",
  "astonished": "Asombrada.",
  "at the end of the day": "Al final del día.",
  "atm": "CAJERO AUTOMÁTICO.",
  "audience": "Audiencia.",
  "automate": "Automatizar.",
  "automation": "Automatización.",
  "autumn": "Otoño.",
  "awareness": "Conciencia.",
  "backup": "Respaldo.",
  "balance": "Balance.",
  "ban": "Prohibición.",
  "bank": "Banco.",
  "bargain": "Negociar.",
  "bargain hunter": "Cazador de gangas.",
  "bathroom": "Baño.",
  "bear in mind": "Tener en cuenta.",
  "beautiful": "Hermosa.",
  "bedroom": "Dormitorio.",
  "beneficial": "Beneficiosa.",
  "between": "Entre.",
  "bias": "Inclinación.",
  "big": "Grande.",
  "bill": "Factura.",
  "biodiversity": "Biodiversidad.",
  "bittersweet": "Agridulce.",
  "black": "Negra.",
  "blue": "Azul.",
  "boarding pass": "Pase de abordar.",
  "book": "Libro.",
  "booked": "Reservado.",
  "booking": "Reserva.",
  "borrow": "Para pedir prestado.",
  "brand": "Marca.",
  "bread": "Pan.",
  "break down": "Para descomponerse.",
  "break the ice": "para romper el hielo.",
  "breakfast": "Desayuno.",
  "breakthrough": "Descubrimiento.",
  "bring about": "Para lograr.",
  "bring up": "Para criar.",
  "broadcast": "Transmisión.",
  "brother": "Hermano.",
  "brown": "Marrón.",
  "brush": "Cepillar.",
  "brush teeth": "cepillarse los dientes.",
  "budget": "Presupuesto.",
  "burn the candle at both ends": "quemar la vela en ambos extremos.",
  "burn the midnight oil": "Quema el aceite de medianoche.",
  "burnout": "Agotamiento.",
  "burst into tears": "estallar en lágrimas.",
  "bus": "Autobús.",
  "call": "Para llamar.",
  "call for": "Para llamar.",
  "call it a day": "para dar por terminado el día.",
  "campaign": "Campaña.",
  "cancel": "Cancelar.",
  "cancelled": "Cancelada.",
  "carbon footprint": "Huella de carbono.",
  "card": "Tarjeta.",
  "carry out": "Realizar.",
  "cash": "Dinero en efectivo.",
  "cash register": "Caja registradora.",
  "cast doubt": "Sembrar dudas.",
  "catch up": "Ponerse al día.",
  "celebrate": "Celebrar.",
  "cemetery": "Cementerio.",
  "censorship": "Censura.",
  "change": "Para cambiar.",
  "charge": "Cargar.",
  "cheap": "Barata.",
  "cheaper": "Más económico.",
  "check in": "Registrarse.",
  "check-up": "Chequeo.",
  "checkout": "Verificar.",
  "cheese": "Queso.",
  "chicken": "Pollo.",
  "child": "Niña.",
  "chronic": "Crónica.",
  "citizen": "Ciudadana.",
  "claim": "Afirmar.",
  "classmate": "Compañera de clase",
  "clean": "Para limpiar.",
  "climate": "Clima.",
  "climb the ladder": "para subir la escalera.",
  "close": "Cerca.",
  "cloud": "Nube.",
  "cloudy": "Nublada.",
  "club": "Club.",
  "coffee": "Café.",
  "coherent": "Coherente.",
  "cold": "Fría.",
  "colleague": "Colega.",
  "collect": "Recolectar.",
  "come across": "Para cruzar.",
  "come into force": "Para entrar en vigor.",
  "come to terms with": "Para llegar a un acuerdo.",
  "come up with": "Para llegar a.",
  "comfortable": "Cómoda.",
  "commitment": "Compromiso.",
  "community": "Comunidad.",
  "commute": "para desplazarse.",
  "compelling": "Irresistible.",
  "comprehensive": "Integral.",
  "conclude": "Concluir.",
  "conscientious": "Concienzuda.",
  "consequence": "Consecuencia.",
  "conservation": "Conservación.",
  "conserve": "Conservar.",
  "consist of": "Consistir en.",
  "contentious": "Contenciosa.",
  "contribute": "Contribuir.",
  "controversial": "Controversial.",
  "conversation": "Conversación.",
  "conversely": "En cambio.",
  "cook": "Para cocinar.",
  "cool": "Fresco.",
  "corner": "Esquina.",
  "correlate": "para correlacionar.",
  "corroborate": "para corroborar.",
  "costume": "Traje.",
  "cotton": "Algodón.",
  "crime": "Crimen.",
  "crisis": "Crisis.",
  "cross that bridge when we come to it": "Cruza ese puente cuando lleguemos a él.",
  "crossroads": "Encrucijada.",
  "crucially": "Fundamentalmente.",
  "currency": "Divisa.",
  "curriculum": "Plan de estudios.",
  "customer": "Cliente.",
  "customs": "Aduanas.",
  "cut corners": "Para tomar atajos.",
  "cut down on": "Para reducir.",
  "cybersecurity": "Ciberseguridad.",
  "dance": "Bailar.",
  "data": "Datos.",
  "deadline": "Fecha límite.",
  "debate": "Debate.",
  "debt": "Deuda.",
  "decisive": "Decisiva.",
  "degree": "Grado.",
  "delay": "Demora.",
  "delayed": "Demorada.",
  "deliberate": "Adrede.",
  "delicious": "Deliciosa.",
  "deliver": "Entregar.",
  "delivery": "Entrega.",
  "demonstrate": "Demostrar.",
  "denouement": "Desenlace.",
  "depart": "Salir.",
  "departure": "Partida.",
  "detrimental": "Perjudicial.",
  "device": "Dispositivo.",
  "diet": "Dieta.",
  "dinner": "Cena.",
  "direction": "Dirección.",
  "dirty": "Sucia.",
  "discount": "Descuento.",
  "discourse": "Discurso.",
  "discover": "Descubrir.",
  "dissertation": "Disertación.",
  "diversity": "Diversidad.",
  "document": "Para documentar.",
  "download": "Para descargar.",
  "draw": "Para dibujar.",
  "draw a conclusion": "Para sacar una conclusión.",
  "dress": "Vestido.",
  "drought": "Sequía.",
  "early": "Temprana",
  "earn": "Para ganar.",
  "eco-friendly": "Ecológica.",
  "ecstatic": "Extática.",
  "edit": "Editar.",
  "efficiency": "Eficiencia.",
  "efficient": "Eficiente.",
  "election": "Elección.",
  "eloquent": "Elocuente.",
  "elucidate": "Dilucidar.",
  "email": "Correo electrónico.",
  "emission": "Emisión.",
  "emissions": "Emisiones.",
  "emphasise": "Enfatizar.",
  "empirical": "Empírica.",
  "energy": "Energía.",
  "engineer": "Ingeniera.",
  "enjoy": "Para disfrutar.",
  "enrol": "para inscribirse.",
  "entrepreneurship": "Emprendimiento.",
  "equality": "Igualdad.",
  "equivocal": "Equívoco.",
  "essentially": "Esencialmente.",
  "estimate": "Estimar.",
  "evening": "Noche.",
  "evidence": "Evidencia.",
  "exacerbate": "Exacerbar.",
  "exam": "Examen.",
  "exchange": "Intercambio.",
  "exercise": "Ejercicio.",
  "expensive": "Cara.",
  "experience": "Experiencia.",
  "experiment": "Experimento.",
  "explain": "Para explicar.",
  "extinct": "Extinguida.",
  "extracurricular": "Extraescolar.",
  "extrapolate": "para extrapolar.",
  "eyes": "Ojos.",
  "factor": "Factora.",
  "fall behind": "Quedarse atrás.",
  "family": "Familia.",
  "fashion": "Moda.",
  "feasible": "Factible.",
  "figure out": "Averiguar.",
  "film": "Película.",
  "fish": "Pez.",
  "fit": "Adaptar.",
  "fitness": "Aptitud física.",
  "fitting room": "Probador.",
  "flat": "Departamento.",
  "flight": "Vuelo.",
  "flood": "Inundación.",
  "fluctuate": "Fluctuar.",
  "food for thought": "Alimento para el pensamiento.",
  "football": "Fútbol americano.",
  "forecast": "Pronóstico.",
  "foreshadow": "para presagiar.",
  "forest": "Bosque.",
  "forgive": "Perdonar.",
  "form": "Forma.",
  "fossil fuel": "Combustible fósil.",
  "free time": "Tiempo libre.",
  "freedom": "Libertad.",
  "freelancer": "Persona de libre dedicación.",
  "freeze": "Congelar.",
  "friendship": "Amistad.",
  "fruit": "Fruta.",
  "frustrated": "Frustrada.",
  "furniture": "Muebles.",
  "furthermore": "Además.",
  "gadget": "Artilugio.",
  "gain insight": "Obtenga información.",
  "game": "Juego.",
  "garden": "Jardín.",
  "gate": "Puerta.",
  "get along": "Para llevarse bien.",
  "get away with": "Para salirse con la suya.",
  "get out of hand": "salirse de control.",
  "get to grips with": "Para afrontarlo.",
  "get up": "Para levantarse.",
  "ghost": "Fantasma.",
  "gift": "Regalo.",
  "go home": "Para volver a casa.",
  "go the extra mile": "Para hacer un esfuerzo adicional.",
  "go through": "Para pasar.",
  "go to work": "Para ir a trabajar.",
  "green": "Verde.",
  "greet": "para saludar.",
  "grey": "Gris.",
  "guarantee": "Garantizar.",
  "guidebook": "Guía.",
  "gym": "Gimnasia.",
  "habit": "Hábito.",
  "habitat": "Hábitat.",
  "hair": "Cabello.",
  "handsome": "Guapa",
  "hang on": "Aférrate.",
  "haunted": "Obsesionada.",
  "have breakfast": "Para desayunar.",
  "have dinner": "Para cenar.",
  "have lunch": "Para almorzar.",
  "headline": "Titular.",
  "healthy": "Saludable.",
  "heartfelt": "Sentida.",
  "help": "Para ayudar.",
  "hence": "Por eso.",
  "hesitate": "dudar.",
  "hire": "Contratar.",
  "hit the nail on the head": "para dar en el clavo.",
  "hobby": "Pasatiempo.",
  "hold true": "Juzgar verdadero.",
  "hometown": "Ciudad natal.",
  "honest": "Honesta.",
  "hospital": "Hospital.",
  "hostel": "Albergue.",
  "hot": "Caliente.",
  "hotel": "Hotel.",
  "hour": "Hora.",
  "hundred": "Centenar.",
  "hungry": "Hambrienta.",
  "husband": "Marido.",
  "hypothesis": "Hipótesis.",
  "illness": "Enfermedad.",
  "illustrate": "Ilustrar.",
  "immune system": "Sistema inmunitario.",
  "impact": "Impacto.",
  "implausible": "Increíble.",
  "implication": "Implicación.",
  "impulsive": "Impulsiva.",
  "in contrast": "En contraste.",
  "in the long run": "A la larga.",
  "in the same boat": "En la misma situación.",
  "indecisive": "Indecisa.",
  "indicate": "Indicar.",
  "inequality": "Desigualdad.",
  "inevitable": "Inevitable.",
  "inference": "Inferencia.",
  "influence": "Influencia.",
  "infrastructure": "Infraestructura.",
  "initially": "Inicialmente.",
  "injury": "Lesión.",
  "innovation": "Innovación.",
  "innovative": "Innovadora.",
  "insurance": "Seguro.",
  "interest": "Interés.",
  "internship": "Pasantía.",
  "interview": "Entrevista.",
  "introduce": "para presentar.",
  "invent": "Inventar.",
  "invest": "Invertir.",
  "invite": "Invitar.",
  "itinerary": "Itineraria.",
  "jacket": "Chaqueta.",
  "journalist": "Periodista.",
  "journey": "Viaje.",
  "juice": "Jugo.",
  "justice": "Justicia.",
  "juxtaposition": "Yuxtaposición.",
  "keep in touch": "Para mantenerse en contacto.",
  "keep one's word": "Para cumplir la palabra.",
  "keep up with": "Para mantenerse al día.",
  "key": "Llave.",
  "keys": "Llaves.",
  "kitchen": "Cocina.",
  "lab": "Laboratorio.",
  "laptop": "Computadora portátil.",
  "late": "Tarde.",
  "law": "Ley.",
  "layoff": "Suspender.",
  "leather": "Cuero.",
  "lecture": "Conferencia.",
  "lend": "Para prestar.",
  "likewise": "Asimismo.",
  "listen": "Para escuchar.",
  "literacy": "Alfabetismo.",
  "living room": "Sala de estar.",
  "lonely": "Solitaria.",
  "long": "Larga.",
  "look": "Para mirar.",
  "look down on": "Para mirar hacia abajo.",
  "look up to": "Para admirar.",
  "lost": "Perdida.",
  "loyal": "Leal.",
  "luggage": "Equipaje.",
  "lunch": "Almuerza.",
  "make a decision": "Para tomar una decisión.",
  "make up for": "Para compensar.",
  "map": "Mapa.",
  "married": "Casada.",
  "mask": "Mascarilla.",
  "meanwhile": "Mientras tanto.",
  "measure": "Medida.",
  "medicine": "Medicamento.",
  "meet": "Para encontrarse.",
  "meeting": "A la reunión.",
  "melancholy": "Melancolía.",
  "melt": "Derretir.",
  "mental health": "Salud mental.",
  "menu": "Menú.",
  "methodology": "Metodología.",
  "minute": "Minuto.",
  "miss": "Extrañar.",
  "miss the point": "Perder el punto.",
  "missed": "Omitido.",
  "mitigate": "para mitigar.",
  "monster": "Monstruo.",
  "month": "Mes.",
  "more expensive": "Más caro.",
  "moreover": "Además.",
  "morning": "Mañana.",
  "move": "Para moverse.",
  "music": "Música.",
  "name": "Al nombre de pila.",
  "namely": "A saber.",
  "nationality": "Nacionalidad, ciudadanía.",
  "nearby": "Cercana.",
  "negligible": "Despreciable.",
  "negotiate": "para negociar.",
  "neighbour": "Vecina.",
  "neighbourhood": "Vecindario.",
  "network": "Red.",
  "never": "Nunca.",
  "nevertheless": "Sin embargo.",
  "night": "Noche.",
  "nonetheless": "Sin embargo.",
  "nostalgic": "Nostálgica.",
  "notably": "Notablemente.",
  "notebook": "Computadora portátil.",
  "notification": "Notificación.",
  "nuanced": "Matizada.",
  "o'clock": "En punto.",
  "objective": "Objetiva.",
  "observe": "Observar.",
  "occupation": "Trabajo, profesión.",
  "ocean": "Océano.",
  "offline": "Desconectada.",
  "often": "A menudo.",
  "old": "Vieja.",
  "on the fence": "En la valla.",
  "on the whole": "En general.",
  "on thin ice": "Sobre hielo fino.",
  "once in a blue moon": "Una vez en una luna azul.",
  "one": "Una.",
  "online": "En línea.",
  "online shopping": "Compras en línea.",
  "open": "Para abrir.",
  "opposite": "Opuesta.",
  "orange": "Naranja.",
  "order": "Orden.",
  "organic": "Orgánica.",
  "outweigh": "para pesar más.",
  "overall": "En general.",
  "overtime": "Con el tiempo.",
  "overweight": "Sobrepeso.",
  "overwhelmed": "Abrumada.",
  "overwhelming": "Abrumadora.",
  "owe": "Deber.",
  "paint": "Para pintar.",
  "paradigm": "Paradigma.",
  "paramount": "Suprema.",
  "parents": "Madres.",
  "parking": "Aparcamiento.",
  "parsimonious": "Parsimoniosa.",
  "partner": "Compañera",
  "party": "Fiesta.",
  "passenger": "Pasajera.",
  "passport": "Pasaporte.",
  "password": "Contraseña.",
  "patent": "Patentar.",
  "pedestrian": "Peatonal.",
  "perspective": "Perspectiva.",
  "persuade": "Persuadir.",
  "pharmacy": "Farmacia.",
  "phenomenon": "Fenómeno.",
  "phone number": "Número de teléfono.",
  "photograph": "Fotografía.",
  "pink": "Rosa.",
  "plagiarism": "Plagio.",
  "platform": "Plataforma.",
  "plausible": "Plausible.",
  "play a role": "Para desempeñar un papel.",
  "play it by ear": "Para tocarlo de oído.",
  "poignant": "Conmovedora.",
  "point out": "Indicar.",
  "police": "Policía.",
  "policy": "Política.",
  "polite": "Educada.",
  "pollution": "Contaminación.",
  "pose a threat": "Representar una amenaza.",
  "post office": "Oficina de correos.",
  "precise": "Precisa.",
  "prefer": "Preferir.",
  "prescribe": "prescribir.",
  "presumably": "Presumiblemente.",
  "prevention": "Prevención.",
  "price": "Precio.",
  "prioritize": "para priorizar.",
  "privacy": "Privacidad.",
  "proliferate": "para proliferar.",
  "promote": "Promover.",
  "promotion": "Promoción.",
  "proportion": "Proporción.",
  "prose": "Prosa.",
  "prospective": "Futura.",
  "protest": "Protesta.",
  "prototype": "Prototipo.",
  "provide evidence": "Para aportar pruebas.",
  "publish": "Publicar.",
  "pull someone's leg": "tomarle el pelo a alguien.",
  "pumpkin": "Calabaza.",
  "put forward": "Para presentar.",
  "put off": "Para posponer.",
  "put up with": "Para aguantar.",
  "qualitative": "Cualitativa.",
  "quality": "Calidad.",
  "quantitative": "Cuantitativa.",
  "queue": "Cola.",
  "quiet": "Tranquila",
  "quintessential": "Por excelencia.",
  "rain": "Lluvia.",
  "rainy": "Lluviosa.",
  "raise awareness": "Crear conciencia.",
  "rarely": "Casi nunca.",
  "reach an agreement": "Concertarse.",
  "read": "Para leer.",
  "read between the lines": "para leer entre líneas.",
  "receipt": "Recibo.",
  "reckon": "contar, suponer.",
  "reconcile": "Conciliar.",
  "recover": "para recuperarse.",
  "recycle": "Reciclar.",
  "red": "Roja.",
  "redundancy": "Redundancia.",
  "refugee": "Refugiada.",
  "refund": "Reembolso.",
  "register": "Registro.",
  "relative": "Relativa.",
  "relax": "Relajarse.",
  "reliable": "Confiable.",
  "renewable": "Renovable.",
  "rent": "Alquilar.",
  "repair": "Reparar.",
  "research": "Investigación.",
  "resentful": "Resentida.",
  "reservation": "Reserva.",
  "resign": "Renunciar.",
  "resolution": "Resolución.",
  "respect": "Respeto.",
  "respectively": "Respectivamente.",
  "responsible": "Responsable.",
  "rest": "Descansar.",
  "restaurant": "Restaurante.",
  "return": "Para volver.",
  "rhetoric": "Retórica.",
  "rights": "Derechos.",
  "risk": "Riesgo.",
  "robot": "Robot.",
  "roundabout": "Rotonda.",
  "rude": "Brusca.",
  "rumour": "Rumor.",
  "run out of": "Para quedarse sin.",
  "running": "A correr.",
  "salary": "Salario.",
  "sale": "Venta.",
  "satirical": "Satírica.",
  "save": "Para ahorrar.",
  "scarce": "Escasa.",
  "scared": "Asustada.",
  "scary": "Aterradora.",
  "schedule": "Cronograma.",
  "scholarship": "Beca.",
  "seaside": "Playa.",
  "sedentary": "Sedentaria.",
  "seminar": "Seminario.",
  "series": "Serie.",
  "set the bar high": "Pon el listón alto.",
  "set up": "Configuración.",
  "share": "Para compartir.",
  "shift": "Cambio.",
  "shirt": "Camisa.",
  "shoes": "Zapatos.",
  "shop assistant": "Asistente de tienda.",
  "short": "Corta.",
  "sightseeing": "Pasear.",
  "sign": "Firmar.",
  "significant": "Significativa.",
  "sing": "Para cantar.",
  "single": "Soltera.",
  "sister": "Hermana.",
  "size": "Tamaño.",
  "skill": "Habilidad.",
  "sleep": "Para dormir.",
  "small": "Pequeña",
  "smartphone": "Teléfono inteligente.",
  "smile": "Sonrisa.",
  "snow": "Nieve.",
  "snowy": "De mucha nieve.",
  "software": "Software.",
  "soil": "Suelo.",
  "sometimes": "A veces.",
  "source": "Fuente.",
  "souvenir": "Recuerdo.",
  "species": "Especies.",
  "specifically": "Específicamente.",
  "spell": "deletrear.",
  "spend": "Para gastar.",
  "sport": "Deporte.",
  "sprain": "Esguince.",
  "spring": "Primavera.",
  "stamina": "Aguante.",
  "stand out": "Para destacar.",
  "start": "Para empezar.",
  "station": "Estación.",
  "storm": "Tormenta.",
  "streaming": "Transmisión.",
  "stress": "Estrés.",
  "study": "Para estudiar.",
  "subjective": "Subjetiva.",
  "subscription": "Suscripción.",
  "subsequently": "Después.",
  "substantial": "Sustancial.",
  "substantiate": "para fundamentar.",
  "subtle": "Sutil.",
  "suitcase": "Maleta.",
  "summer": "Verano.",
  "sunny": "Soleada.",
  "sunshine": "Luz solar.",
  "supermarket": "Supermercado.",
  "support": "Apoyo.",
  "surname": "Apellido.",
  "sustainability": "Sostenibilidad.",
  "sustainable": "Sostenible.",
  "swimming": "Nadar.",
  "symptom": "Síntoma.",
  "synthesize": "para sintetizar.",
  "take aback": "para sorprenderse.",
  "take into account": "Para tener en cuenta.",
  "take with a grain of salt": "Para tomar con pinzas.",
  "tall": "Alta.",
  "taste": "Al gusto.",
  "tax": "Impuesto.",
  "tea": "Té.",
  "temperature": "Temperatura.",
  "ten": "Diez.",
  "tentative": "Tentativa.",
  "terse": "Breve.",
  "the ball is in your court": "la pelota está en tu tejado.",
  "the best": "La mejor",
  "the bottom line": "el resultado final.",
  "the tip of the iceberg": "la punta del iceberg.",
  "theory": "Teoría.",
  "therefore": "Por lo tanto.",
  "thesis": "Tesis.",
  "think outside the box": "Pensar fuera de lo común.",
  "thirsty": "Sedienta.",
  "threat": "Amenaza.",
  "three": "Tres.",
  "thus": "De este modo.",
  "ticket": "Boleto.",
  "timetable": "Calendario.",
  "to a large extent": "en gran medida.",
  "today": "Hoy.",
  "tomorrow": "Mañana.",
  "town hall": "Ayuntamiento.",
  "train": "Tren.",
  "transfer": "Transferir.",
  "trend": "Tendencia.",
  "trick or treat": "Truco o trato.",
  "trousers": "Pantalones.",
  "trust": "Confianza.",
  "try on": "Para probarlo.",
  "tuition": "Matrícula.",
  "turn down": "Rechazar.",
  "turn out": "Para salir.",
  "two": "Dos.",
  "ultimately": "Al final.",
  "umbrella": "Paraguas.",
  "undermine": "para socavar.",
  "underscore": "Subrayar.",
  "unprecedented": "Sin precedentes.",
  "update": "Actualizar.",
  "upload": "Subir.",
  "urbanisation": "Urbanización.",
  "usually": "Generalmente.",
  "vaccine": "Vacuna.",
  "vampire": "Vampira.",
  "vegetable": "Verdura.",
  "vernacular": "Vernácula.",
  "viral": "Viral.",
  "visa": "Visa.",
  "wait": "Esperar.",
  "wake up": "para despertar.",
  "walk": "Para caminar.",
  "wallet": "Billetera.",
  "warm": "Cálida.",
  "warranty": "Garantía.",
  "wash": "Para lavar.",
  "waste": "Desperdiciar.",
  "watch": "Para mirar.",
  "water": "Agua.",
  "wear": "Para usar.",
  "weather": "Clima.",
  "weather the storm": "Capear la tormenta.",
  "week": "Semana.",
  "weekend": "Fin de semana.",
  "weigh up": "para sopesar.",
  "wellbeing": "Bienestar.",
  "wellness": "Bienestar.",
  "whereas": "Mientras que.",
  "whilst": "Mientras que.",
  "white": "Blanca.",
  "wi-fi": "Wifi.",
  "wife": "Esposa.",
  "wildlife": "Fauna.",
  "wind": "Viento.",
  "windy": "Ventosa.",
  "winter": "Invierno.",
  "witch": "Bruja.",
  "with regard to": "Con respecto a.",
  "work": "Para trabajar.",
  "work out": "Para hacer ejercicio.",
  "workload": "A la carga de trabajo.",
  "worth": "Valer.",
  "write": "Para escribir.",
  "year": "Año.",
  "yellow": "Amarilla.",
  "yesterday": "Ayer.",
  "young": "Joven.",
  },
  de: {
  "a blessing in disguise": "ein Segen im Unglück.",
  "a double-edged sword": "ein zweischneidiges Schwert.",
  "a rule of thumb": "eine Faustregel.",
  "abundant": "Reichlich.",
  "account": "Konto.",
  "account for": "Konto für.",
  "accurate": "Genau.",
  "address": "Adresse.",
  "address an issue": "Beheben Sie ein Problem.",
  "admittedly": "Freilich.",
  "afford": "Leisten.",
  "afraid": "Besorgt.",
  "afternoon": "Nachmittag.",
  "age": "Alter.",
  "ailment": "Leiden.",
  "airport": "Flughafen.",
  "alarm clock": "Wecker.",
  "albeit": "Allerdings.",
  "allegory": "Allegorie.",
  "always": "Stets.",
  "ambiguous": "Mehrdeutig.",
  "apologise": "Sich entschuldigen.",
  "app": "App.",
  "apply": "Anwenden.",
  "appointment": "Termin.",
  "apprehensive": "Besorgt.",
  "approach": "Ansatz.",
  "aptitude": "Eignung.",
  "arcane": "Arkan.",
  "arguably": "Wohl.",
  "argue": "Argumentieren.",
  "argument": "Argument.",
  "arrival": "Ankunft.",
  "arrive": "Ankommen.",
  "artificial intelligence": "Künstliche Intelligenz.",
  "as a result": "Infolge.",
  "ask": "Zu fragen.",
  "assess": "Bewerten.",
  "assignment": "Abtretung.",
  "astonished": "Erstaunt.",
  "at the end of the day": "Am Ende des Tages.",
  "atm": "GELDAUTOMAT.",
  "audience": "Publikum.",
  "automate": "Automatisieren.",
  "automation": "Automatisierung.",
  "autumn": "Herbst.",
  "awareness": "Bewusstsein.",
  "backup": "Sicherung.",
  "balance": "Gleichgewicht.",
  "ban": "Verbot.",
  "bank": "Bank.",
  "bargain": "Schnäppchen.",
  "bargain hunter": "Schnäppchenjäger.",
  "bathroom": "Badezimmer.",
  "bear in mind": "Denken Sie daran.",
  "beautiful": "Schön.",
  "bedroom": "Schlafzimmer.",
  "beneficial": "Vorteilhaft.",
  "between": "Zwischen.",
  "bias": "Voreingenommenheit.",
  "big": "Groß.",
  "bill": "Rechnung.",
  "biodiversity": "Biodiversität.",
  "bittersweet": "Bittersüß.",
  "black": "Schwarz.",
  "blue": "Blau.",
  "boarding pass": "Bordkarte.",
  "book": "Buch.",
  "booked": "Gebucht.",
  "booking": "Buchung.",
  "borrow": "Zum Ausleihen.",
  "brand": "Marke.",
  "bread": "Brot.",
  "break down": "Zusammenbrechen.",
  "break the ice": "um das Eis zu brechen.",
  "breakfast": "Frühstück.",
  "breakthrough": "Durchbruch.",
  "bring about": "Herbeiführen.",
  "bring up": "Zur Sprache bringen.",
  "broadcast": "Übertragen.",
  "brother": "Bruder.",
  "brown": "Braun.",
  "brush": "Bürste.",
  "brush teeth": "sich die Zähne putzen.",
  "budget": "Budget.",
  "burn the candle at both ends": "um die Kerze an beiden Enden abzubrennen.",
  "burn the midnight oil": "Verbrenne das Mitternachtsöl.",
  "burnout": "Burnout.",
  "burst into tears": "in Tränen ausbrechen.",
  "bus": "Bus.",
  "call": "Zum Anrufen.",
  "call for": "Zum Aufrufen.",
  "call it a day": "Schluss machen.",
  "campaign": "Kampagne.",
  "cancel": "Stornieren.",
  "cancelled": "Abgesagt.",
  "carbon footprint": "CO2-Fußabdruck.",
  "card": "Karte.",
  "carry out": "Durchführen.",
  "cash": "Kasse.",
  "cash register": "Kasse.",
  "cast doubt": "Zweifel aufkommen lassen.",
  "catch up": "Aufholen.",
  "celebrate": "Feiern.",
  "cemetery": "Friedhof.",
  "censorship": "Zensur.",
  "change": "Zu ändern.",
  "charge": "Aufladung.",
  "cheap": "Billig.",
  "cheaper": "Günstiger.",
  "check in": "Einchecken.",
  "check-up": "Untersuchung.",
  "checkout": "Kasse.",
  "cheese": "Käse.",
  "chicken": "Huhn.",
  "child": "Kind.",
  "chronic": "Chronisch.",
  "citizen": "Bürgerin.",
  "claim": "Beanspruchen.",
  "classmate": "Mitschülerin.",
  "clean": "Zum Reinigen.",
  "climate": "Klima.",
  "climb the ladder": "die Leiter hinaufsteigen.",
  "close": "Schließen.",
  "cloud": "Wolke.",
  "cloudy": "Wolkig.",
  "club": "Verein.",
  "coffee": "Kaffee.",
  "coherent": "Kohärent.",
  "cold": "Kalt.",
  "colleague": "Kollegin.",
  "collect": "Sammeln.",
  "come across": "Zu stoßen.",
  "come into force": "In Kraft treten.",
  "come to terms with": "Sich damit abfinden.",
  "come up with": "Zu erfinden.",
  "comfortable": "Komfortabel.",
  "commitment": "Engagement.",
  "community": "Gemeinschaft.",
  "commute": "pendeln.",
  "compelling": "Zwingend.",
  "comprehensive": "Umfassend.",
  "conclude": "Abschließen.",
  "conscientious": "Gewissenhaft.",
  "consequence": "Folge.",
  "conservation": "Erhaltung.",
  "conserve": "Sparen.",
  "consist of": "Bestehen aus.",
  "contentious": "Umstritten.",
  "contribute": "Beitragen.",
  "controversial": "Umstritten.",
  "conversation": "Gespräch.",
  "conversely": "Umgekehrt.",
  "cook": "Zum Kochen.",
  "cool": "Cool.",
  "corner": "Ecke.",
  "correlate": "korrelieren.",
  "corroborate": "zu bestätigen.",
  "costume": "Kostüm.",
  "cotton": "Baumwolle.",
  "crime": "Verbrechen.",
  "crisis": "Krise.",
  "cross that bridge when we come to it": "Überqueren Sie die Brücke, wenn wir dort ankommen.",
  "crossroads": "Kreuzung.",
  "crucially": "Entscheidend.",
  "currency": "Währung.",
  "curriculum": "Lehrplan.",
  "customer": "Kundin.",
  "customs": "Zoll.",
  "cut corners": "Um Abstriche zu machen.",
  "cut down on": "Zum Reduzieren.",
  "cybersecurity": "Cybersicherheit.",
  "dance": "Tanzen.",
  "data": "Daten.",
  "deadline": "Frist.",
  "debate": "Debatte.",
  "debt": "Schulden.",
  "decisive": "Entscheidend.",
  "degree": "Grad.",
  "delay": "Verzögerung.",
  "delayed": "Verzögert.",
  "deliberate": "Absichtlich.",
  "delicious": "Lecker.",
  "deliver": "Liefern.",
  "delivery": "Lieferung.",
  "demonstrate": "Zeigen.",
  "denouement": "Auflösung.",
  "depart": "Abweichen.",
  "departure": "Abfahrt.",
  "detrimental": "Schädlich.",
  "device": "Gerät.",
  "diet": "Diät.",
  "dinner": "Abendessen.",
  "direction": "Richtung.",
  "dirty": "Schmutzig.",
  "discount": "Rabatt.",
  "discourse": "Diskurs.",
  "discover": "Entdecken.",
  "dissertation": "Dissertation.",
  "diversity": "Diversität.",
  "document": "Zu dokumentieren.",
  "download": "Zum Herunterladen.",
  "draw": "Zeichnen.",
  "draw a conclusion": "Um ein Fazit zu ziehen.",
  "dress": "Kleid.",
  "drought": "Trockenheit.",
  "early": "Früh.",
  "earn": "Zu verdienen.",
  "eco-friendly": "Umweltfreundlich.",
  "ecstatic": "Ekstatisch.",
  "edit": "Bearbeiten.",
  "efficiency": "Effizienz.",
  "efficient": "Effizient.",
  "election": "Wahl.",
  "eloquent": "Beredt.",
  "elucidate": "Aufklären.",
  "email": "E-Mail.",
  "emission": "Emission.",
  "emissions": "Emissionen.",
  "emphasise": "Betonen.",
  "empirical": "Empirisch.",
  "energy": "Energie.",
  "engineer": "Ingenieurin.",
  "enjoy": "Zum Genießen.",
  "enrol": "einschreiben.",
  "entrepreneurship": "Unternehmertum.",
  "equality": "Gleichwertigkeit.",
  "equivocal": "Zweideutig.",
  "essentially": "Im Wesentlichen.",
  "estimate": "Schätzen.",
  "evening": "Abend.",
  "evidence": "Beweis.",
  "exacerbate": "Verschärfen.",
  "exam": "Prüfung.",
  "exchange": "Austausch.",
  "exercise": "Übung.",
  "expensive": "Teuer.",
  "experience": "Erfahrung.",
  "experiment": "Experiment.",
  "explain": "Zur Erklärung.",
  "extinct": "Ausgestorben.",
  "extracurricular": "Außerschulisch.",
  "extrapolate": "extrapolieren.",
  "eyes": "Augen.",
  "factor": "Faktor.",
  "fall behind": "Zurückfallen.",
  "family": "Familie.",
  "fashion": "Mode.",
  "feasible": "Machbar.",
  "figure out": "Finde es heraus.",
  "film": "Film.",
  "fish": "Fisch.",
  "fit": "Fit.",
  "fitness": "Fitness.",
  "fitting room": "Umkleidekabine.",
  "flat": "Wohnung.",
  "flight": "Flug.",
  "flood": "Flut.",
  "fluctuate": "Schwanken.",
  "food for thought": "Denkanstöße.",
  "football": "Fußball.",
  "forecast": "Vorhersage.",
  "foreshadow": "vorwegnehmen.",
  "forest": "Wald.",
  "forgive": "Verzeihen.",
  "form": "Bilden.",
  "fossil fuel": "Fossiler Brennstoff.",
  "free time": "Freizeit.",
  "freedom": "Freiheit.",
  "freelancer": "Freiberuflerin.",
  "freeze": "Einfrieren.",
  "friendship": "Freundschaft.",
  "fruit": "Obst.",
  "frustrated": "Frustriert.",
  "furniture": "Möbel.",
  "furthermore": "Außerdem.",
  "gadget": "Gerät.",
  "gain insight": "Einblick gewinnen.",
  "game": "Spiel.",
  "garden": "Garten.",
  "gate": "Tor.",
  "get along": "Um miteinander auszukommen.",
  "get away with": "Um damit durchzukommen.",
  "get out of hand": "außer Kontrolle geraten.",
  "get to grips with": "Zum Anfassen.",
  "get up": "Aufstehen.",
  "ghost": "Geist.",
  "gift": "Geschenk.",
  "go home": "Nach Hause gehen.",
  "go the extra mile": "Die Extrameile gehen.",
  "go through": "Durchgehen.",
  "go to work": "Zur Arbeit gehen.",
  "green": "Grün.",
  "greet": "grüßen.",
  "grey": "Grau.",
  "guarantee": "Garantie.",
  "guidebook": "Reiseführer.",
  "gym": "Fitnessstudio.",
  "habit": "Gewohnheit.",
  "habitat": "Lebensraum.",
  "hair": "Haar.",
  "handsome": "Gutaussehend.",
  "hang on": "Abwarten.",
  "haunted": "Verfolgt.",
  "have breakfast": "Zum Frühstücken.",
  "have dinner": "Zum Abendessen.",
  "have lunch": "Zum Mittagessen.",
  "headline": "Überschrift.",
  "healthy": "Gesund.",
  "heartfelt": "Herzlich.",
  "help": "Um zu helfen.",
  "hence": "Somit.",
  "hesitate": "zögern.",
  "hire": "Mieten.",
  "hit the nail on the head": "den Nagel auf den Kopf treffen.",
  "hobby": "Hobby.",
  "hold true": "Bleiben Sie wahr.",
  "hometown": "Heimatstadt.",
  "honest": "Ehrlich.",
  "hospital": "Krankenhaus.",
  "hostel": "Herberge.",
  "hot": "Heiß.",
  "hotel": "Hotel.",
  "hour": "Stunde.",
  "hundred": "Hundert.",
  "hungry": "Hungrig.",
  "husband": "Ehemann.",
  "hypothesis": "Hypothese.",
  "illness": "Erkrankung.",
  "illustrate": "Veranschaulichen.",
  "immune system": "Immunsystem.",
  "impact": "Auswirkungen.",
  "implausible": "Unglaubwürdig.",
  "implication": "Implikation.",
  "impulsive": "Treibend.",
  "in contrast": "Im Gegensatz.",
  "in the long run": "Auf Dauer.",
  "in the same boat": "Im selben Boot.",
  "indecisive": "Unentschlossen.",
  "indicate": "Angeben.",
  "inequality": "Ungleichheit.",
  "inevitable": "Unvermeidlich.",
  "inference": "Schlussfolgerung.",
  "influence": "Beeinflussen.",
  "infrastructure": "Infrastruktur.",
  "initially": "Anfänglich.",
  "injury": "Verletzung.",
  "innovation": "Innovation.",
  "innovative": "Innovativ.",
  "insurance": "Versicherung.",
  "interest": "Interesse.",
  "internship": "Praktikum.",
  "interview": "Interview.",
  "introduce": "vorstellen.",
  "invent": "Erfinden.",
  "invest": "Investieren.",
  "invite": "Einladen.",
  "itinerary": "Route.",
  "jacket": "Jacke.",
  "journalist": "Journalistin.",
  "journey": "Reise.",
  "juice": "Saft.",
  "justice": "Gerechtigkeit.",
  "juxtaposition": "Nebeneinander.",
  "keep in touch": "Um in Kontakt zu bleiben.",
  "keep one's word": "Sein Wort halten.",
  "keep up with": "Um mitzuhalten.",
  "key": "Schlüssel.",
  "keys": "Schlüssel.",
  "kitchen": "Küche.",
  "lab": "Labor.",
  "laptop": "Laptop.",
  "late": "Spät.",
  "law": "Gesetz.",
  "layoff": "Entlassung.",
  "leather": "Leder.",
  "lecture": "Vortrag.",
  "lend": "Ausleihen.",
  "likewise": "Ebenfalls.",
  "listen": "Zuhören.",
  "literacy": "Alphabetisierung.",
  "living room": "Wohnzimmer.",
  "lonely": "Einsam.",
  "long": "Lang.",
  "look": "Zu schauen.",
  "look down on": "Auf den man herabschauen kann.",
  "look up to": "Zum Aufschauen.",
  "lost": "Verloren.",
  "loyal": "Treu.",
  "luggage": "Gepäck.",
  "lunch": "Mittagessen.",
  "make a decision": "Eine Entscheidung treffen.",
  "make up for": "Um das auszugleichen.",
  "map": "Karte.",
  "married": "Verheiratet.",
  "mask": "Maske.",
  "meanwhile": "In der Zwischenzeit.",
  "measure": "Messen.",
  "medicine": "Medizin.",
  "meet": "Treffen.",
  "meeting": "Zum Treffen.",
  "melancholy": "Melancholie.",
  "melt": "Schmelzen.",
  "mental health": "Psychische Gesundheit.",
  "menu": "Speisekarte.",
  "methodology": "Methodik.",
  "minute": "Minute.",
  "miss": "Zu verpassen.",
  "miss the point": "Den Punkt verfehlen.",
  "missed": "Verpasst.",
  "mitigate": "zu mildern.",
  "monster": "Monster.",
  "month": "Monat.",
  "more expensive": "Teurer.",
  "moreover": "Darüber hinaus.",
  "morning": "Morgen.",
  "move": "Sich bewegen.",
  "music": "Musik.",
  "name": "Zum Vornamen.",
  "namely": "Nämlich.",
  "nationality": "Nationalität, Staatsbürgerschaft.",
  "nearby": "Nahe.",
  "negligible": "Vernachlässigbar.",
  "negotiate": "zu verhandeln.",
  "neighbour": "Nachbarin.",
  "neighbourhood": "Nachbarschaft.",
  "network": "Netzwerk.",
  "never": "Niemals.",
  "nevertheless": "Trotzdem.",
  "night": "Nacht.",
  "nonetheless": "Dennoch.",
  "nostalgic": "Nostalgisch.",
  "notably": "Vor allem.",
  "notebook": "Notizbuch.",
  "notification": "Benachrichtigung.",
  "nuanced": "Nuanciert.",
  "o'clock": "Uhr.",
  "objective": "Objektiv.",
  "observe": "Beobachten.",
  "occupation": "Job, Beruf.",
  "ocean": "Ozean.",
  "offline": "Offline.",
  "often": "Oft.",
  "old": "Alt.",
  "on the fence": "Am Zaun.",
  "on the whole": "Im Großen und Ganzen.",
  "on thin ice": "Auf dünnem Eis.",
  "once in a blue moon": "Alle Jubeljahre einmal.",
  "one": "Eins.",
  "online": "Online.",
  "online shopping": "Online-Shopping.",
  "open": "Zum Öffnen.",
  "opposite": "Gegenteil.",
  "orange": "Orange.",
  "order": "Befehl.",
  "organic": "Bio.",
  "outweigh": "überwiegen.",
  "overall": "Gesamt.",
  "overtime": "Im Laufe der Zeit.",
  "overweight": "Übergewicht.",
  "overwhelmed": "Überwältigt.",
  "overwhelming": "Überwältigend.",
  "owe": "Verdanken.",
  "paint": "Malen.",
  "paradigm": "Paradigma.",
  "paramount": "Von größter Bedeutung.",
  "parents": "Eltern.",
  "parking": "Parken.",
  "parsimonious": "Sparsam.",
  "partner": "Partner.",
  "party": "Party.",
  "passenger": "Passagier.",
  "passport": "Reisepass.",
  "password": "Passwort.",
  "patent": "Patent.",
  "pedestrian": "Fußgängerin.",
  "perspective": "Perspektive.",
  "persuade": "Überreden.",
  "pharmacy": "Apotheke.",
  "phenomenon": "Phänomen.",
  "phone number": "Telefonnummer.",
  "photograph": "Foto.",
  "pink": "Rosa.",
  "plagiarism": "Plagiat.",
  "platform": "Plattform.",
  "plausible": "Plausibel.",
  "play a role": "Eine Rolle spielen.",
  "play it by ear": "Um es nach Gehör zu spielen.",
  "poignant": "Ergreifend.",
  "point out": "Weisen Sie darauf hin.",
  "police": "Polizei.",
  "policy": "Politik.",
  "polite": "Höflich.",
  "pollution": "Verschmutzung.",
  "pose a threat": "Stellen Sie eine Bedrohung dar.",
  "post office": "Postamt.",
  "precise": "Präzise.",
  "prefer": "Zu bevorzugen.",
  "prescribe": "verschreiben.",
  "presumably": "Vermutlich.",
  "prevention": "Verhütung.",
  "price": "Preis.",
  "prioritize": "zu priorisieren.",
  "privacy": "Privatsphäre.",
  "proliferate": "sich vermehren.",
  "promote": "Fördern.",
  "promotion": "Förderung.",
  "proportion": "Anteil.",
  "prose": "Prosa.",
  "prospective": "Prospektiv.",
  "protest": "Protest.",
  "prototype": "Prototyp.",
  "provide evidence": "Beweise liefern.",
  "publish": "Veröffentlichen.",
  "pull someone's leg": "jemanden am Bein ziehen.",
  "pumpkin": "Kürbis.",
  "put forward": "Vorbringen.",
  "put off": "Zum Aufschieben.",
  "put up with": "Zu ertragen.",
  "qualitative": "Qualitativ.",
  "quality": "Qualität.",
  "quantitative": "Quantitativ.",
  "queue": "Warteschlange.",
  "quiet": "Ruhig.",
  "quintessential": "Quintessenz.",
  "rain": "Regen.",
  "rainy": "Regnerisch.",
  "raise awareness": "Sensibilisierung.",
  "rarely": "Selten.",
  "reach an agreement": "Treffen Sie eine Einigung.",
  "read": "Zum Lesen.",
  "read between the lines": "zwischen den Zeilen lesen.",
  "receipt": "Quittung.",
  "reckon": "rechnen, annehmen.",
  "reconcile": "Versöhnen.",
  "recover": "sich erholen.",
  "recycle": "Recyceln.",
  "red": "Rot.",
  "redundancy": "Redundanz.",
  "refugee": "Flüchtling.",
  "refund": "Erstattung.",
  "register": "Registrieren.",
  "relative": "Relativ.",
  "relax": "Entspannen.",
  "reliable": "Zuverlässig.",
  "renewable": "Verlängerbar.",
  "rent": "Mieten.",
  "repair": "Reparieren.",
  "research": "Forschung.",
  "resentful": "Nachtragend.",
  "reservation": "Reservierung.",
  "resign": "Zurücktreten.",
  "resolution": "Auflösung.",
  "respect": "Respektieren.",
  "respectively": "Jeweils.",
  "responsible": "Verantwortlich.",
  "rest": "Ausruhen.",
  "restaurant": "Restaurant.",
  "return": "Zurückkehren.",
  "rhetoric": "Rhetorik.",
  "rights": "Rechte.",
  "risk": "Risiko.",
  "robot": "Roboter.",
  "roundabout": "Kreisel.",
  "rude": "Unhöflich.",
  "rumour": "Gerücht.",
  "run out of": "Ausgehen.",
  "running": "Zum Laufen.",
  "salary": "Gehalt.",
  "sale": "Verkauf.",
  "satirical": "Satirisch.",
  "save": "Zum Sparen.",
  "scarce": "Spärlich.",
  "scared": "Verängstigt.",
  "scary": "Beängstigend.",
  "schedule": "Zeitplan.",
  "scholarship": "Stipendium.",
  "seaside": "Meer.",
  "sedentary": "Sitzend.",
  "seminar": "Seminar.",
  "series": "Serie.",
  "set the bar high": "Legen Sie die Messlatte hoch.",
  "set up": "Aufstellen.",
  "share": "Zum Teilen.",
  "shift": "Schicht.",
  "shirt": "Hemd.",
  "shoes": "Schuhe.",
  "shop assistant": "Verkäufer.",
  "short": "Kurz.",
  "sightseeing": "Besichtigung.",
  "sign": "Zeichen.",
  "significant": "Bedeutsam.",
  "sing": "Zum Singen.",
  "single": "Einzel.",
  "sister": "Schwester.",
  "size": "Größe.",
  "skill": "Fähigkeit.",
  "sleep": "Zum Schlafen.",
  "small": "Klein.",
  "smartphone": "Smartphone.",
  "smile": "Lächeln.",
  "snow": "Schnee.",
  "snowy": "Schneebedeckt.",
  "software": "Software.",
  "soil": "Boden.",
  "sometimes": "Manchmal.",
  "source": "Quelle.",
  "souvenir": "Souvenir.",
  "species": "Spezies.",
  "specifically": "Speziell.",
  "spell": "buchstabieren.",
  "spend": "Ausgeben.",
  "sport": "Sport.",
  "sprain": "Verstauchung.",
  "spring": "Frühling.",
  "stamina": "Ausdauer.",
  "stand out": "Auffallen.",
  "start": "Um zu beginnen.",
  "station": "Station.",
  "storm": "Sturm.",
  "streaming": "Streaming.",
  "stress": "Stress.",
  "study": "Zum Lernen.",
  "subjective": "Subjektiv.",
  "subscription": "Abonnement.",
  "subsequently": "Anschließend.",
  "substantial": "Wesentlich.",
  "substantiate": "zu begründen.",
  "subtle": "Subtil.",
  "suitcase": "Koffer.",
  "summer": "Sommer.",
  "sunny": "Sonnig.",
  "sunshine": "Sonnenschein.",
  "supermarket": "Supermarkt.",
  "support": "Unterstützung.",
  "surname": "Nachname.",
  "sustainability": "Nachhaltigkeit.",
  "sustainable": "Nachhaltig.",
  "swimming": "Baden.",
  "symptom": "Symptom.",
  "synthesize": "zu synthetisieren.",
  "take aback": "verblüffen.",
  "take into account": "Zu berücksichtigen.",
  "take with a grain of salt": "Mit einem Körnchen Salz einnehmen.",
  "tall": "Groß.",
  "taste": "Nach Geschmack.",
  "tax": "Steuer.",
  "tea": "Tee.",
  "temperature": "Temperatur.",
  "ten": "Zehn.",
  "tentative": "Vorläufig.",
  "terse": "Knapp.",
  "the ball is in your court": "Der Ball liegt bei Ihnen.",
  "the best": "der beste.",
  "the bottom line": "das Endergebnis.",
  "the tip of the iceberg": "die Spitze des Eisbergs.",
  "theory": "Theorie.",
  "therefore": "Daher.",
  "thesis": "These.",
  "think outside the box": "Über den Tellerrand hinaus denken.",
  "thirsty": "Durstig.",
  "threat": "Gefahr.",
  "three": "Drei.",
  "thus": "Daher.",
  "ticket": "Ticket.",
  "timetable": "Zeitplan.",
  "to a large extent": "weitgehend.",
  "today": "Heute.",
  "tomorrow": "Morgen.",
  "town hall": "Rathaus.",
  "train": "Zug.",
  "transfer": "Überweisen.",
  "trend": "Trend.",
  "trick or treat": "Süßes oder Saures.",
  "trousers": "Hose.",
  "trust": "Vertrauen.",
  "try on": "Zum Anprobieren.",
  "tuition": "Unterricht.",
  "turn down": "Ablehnen.",
  "turn out": "Sich herausstellen.",
  "two": "Zwei.",
  "ultimately": "Letztlich.",
  "umbrella": "Regenschirm.",
  "undermine": "untergraben.",
  "underscore": "Unterstreichen.",
  "unprecedented": "Beispiellos.",
  "update": "Aktualisieren.",
  "upload": "Hochladen.",
  "urbanisation": "Urbanisierung.",
  "usually": "Normalerweise.",
  "vaccine": "Impfstoff.",
  "vampire": "Vampir.",
  "vegetable": "Gemüse.",
  "vernacular": "Umgangssprachlich.",
  "viral": "Viral.",
  "visa": "Visum.",
  "wait": "Warten.",
  "wake up": "aufwachen.",
  "walk": "Zu Fuß gehen.",
  "wallet": "Geldbörse.",
  "warm": "Warm.",
  "warranty": "Garantie.",
  "wash": "Zum Waschen.",
  "waste": "Abfall.",
  "watch": "Zu sehen.",
  "water": "Wasser.",
  "wear": "Zum Tragen.",
  "weather": "Wetter.",
  "weather the storm": "Überstehen Sie den Sturm.",
  "week": "Woche.",
  "weekend": "Wochenende.",
  "weigh up": "abwägen.",
  "wellbeing": "Wohlbefinden.",
  "wellness": "Wellness.",
  "whereas": "Wohingegen.",
  "whilst": "Während.",
  "white": "Weiß.",
  "wi-fi": "W-lan.",
  "wife": "Gattin.",
  "wildlife": "Tierwelt.",
  "wind": "Wind.",
  "windy": "Windig.",
  "winter": "Winter.",
  "witch": "Hexe.",
  "with regard to": "Hinsichtlich.",
  "work": "Zur Arbeit.",
  "work out": "Um zu trainieren.",
  "workload": "Zur Arbeitsbelastung.",
  "worth": "Wert.",
  "write": "Zu schreiben.",
  "year": "Jahr.",
  "yellow": "Gelb.",
  "yesterday": "Gestern.",
  "young": "Jung.",
  },
};
