import type { InterfaceLanguage } from "@/types";

/** Interface-language glosses for the English course vocabulary (key = English lemma). */
export const ENGLISH_VOCAB_GLOSS: Partial<
  Record<InterfaceLanguage, Record<string, string>>
> = {
  ru: {
  "name": "имя",
  "surname": "фамилия",
  "nationality": "национальность, гражданство",
  "address": "адрес",
  "occupation": "род занятий, профессия",
  "married": "женатый, замужняя",
  "single": "неженатый, незамужняя",
  "greet": "приветствовать",
  "introduce": "представлять, знакомить",
  "spell": "произносить по буквам, писать по буквам",
  "age": "возраст",
  "email": "электронная почта",
  "phone number": "номер телефона",
  "hometown": "родной город",
  "wake up": "просыпаться",
  "breakfast": "завтрак",
  "brush teeth": "чистить зубы",
  "commute": "ездить на работу и обратно",
  "schedule": "расписание, график",
  "alarm clock": "будильник",
  "notebook": "тетрадь, блокнот",
  "laptop": "ноутбук",
  "umbrella": "зонт",
  "wallet": "кошелёк",
  "keys": "ключи",
  "habit": "привычка",
  "usually": "обычно",
  "rarely": "редко",
  "bank": "банк",
  "pharmacy": "аптека",
  "post office": "почта, почтовое отделение",
  "supermarket": "супермаркет",
  "roundabout": "круговое движение, кольцо",
  "corner": "угол (улицы)",
  "opposite": "напротив",
  "between": "между",
  "nearby": "рядом, поблизости",
  "pedestrian": "пешеход",
  "crossroads": "перекрёсток",
  "town hall": "ратуша, мэрия",
  "atm": "банкомат",
  "parking": "парковка",
  "departure": "отправление, отбытие",
  "arrival": "прибытие",
  "delay": "задержка",
  "boarding pass": "посадочный талон",
  "customs": "таможня",
  "luggage": "багаж",
  "sightseeing": "осмотр достопримечательностей",
  "souvenir": "сувенир",
  "booked": "забронированный",
  "cancelled": "отменённый",
  "missed": "пропущенный (рейс, поезд)",
  "delayed": "задержанный",
  "platform": "платформа (на вокзале)",
  "itinerary": "маршрут, план поездки",
  "bargain": "выгодная покупка, сделка",
  "refund": "возврат денег",
  "discount": "скидка",
  "fitting room": "примерочная",
  "cash register": "касса",
  "receipt": "чек",
  "cheaper": "дешевле",
  "more expensive": "дороже",
  "the best": "лучший",
  "bargain hunter": "любитель выгодных покупок",
  "exchange": "обменять, заменить (товар)",
  "warranty": "гарантия",
  "brand": "бренд, марка",
  "checkout": "касса (зона оплаты)",
  "smartphone": "смартфон",
  "app": "приложение",
  "update": "обновление",
  "wi-fi": "беспроводной интернет",
  "streaming": "стриминг, потоковая передача",
  "subscription": "подписка",
  "notification": "уведомление",
  "backup": "резервная копия",
  "cloud": "облако (облачное хранилище)",
  "gadget": "гаджет, устройство",
  "online": "онлайн, в интернете",
  "offline": "офлайн, без интернета",
  "password": "пароль",
  "cybersecurity": "кибербезопасность",
  "decisive": "решительный",
  "indecisive": "нерешительный",
  "conscientious": "добросовестный, ответственный",
  "impulsive": "импульсивный",
  "deliberate": "обдуманный, намеренный",
  "prioritize": "расставлять приоритеты",
  "commitment": "обязательство, приверженность",
  "hesitate": "колебаться, сомневаться",
  "reckon": "полагать, считать (разг.)",
  "weigh up": "взвешивать (варианты), обдумывать",
  "resolution": "решимость; решение (New Year's ~)",
  "tentative": "предварительный, неокончательный",
  "overwhelmed": "перегруженный, подавленный (эмоциями)",
  "nostalgic": "тоскующий по прошлому, ностальгический",
  "bittersweet": "горько-сладкий (о чувствах)",
  "astonished": "изумлённый, поражённый",
  "frustrated": "расстроенный, раздражённый",
  "ecstatic": "в восторге, на седьмом небе",
  "melancholy": "меланхолия, грусть",
  "resentful": "обиженный, испытывающий негодование",
  "apprehensive": "тревожный, опасающийся",
  "heartfelt": "искренний, от всего сердца",
  "burst into tears": "разразиться слезами, расплакаться",
  "take aback": "ошеломить, застать врасплох",
  "symptom": "симптом, признак болезни",
  "chronic": "хронический (о болезни)",
  "recover": "выздороветь, восстановиться",
  "prescribe": "назначать (лекарство, лечение)",
  "immune system": "иммунная система",
  "stamina": "выносливость, запас сил",
  "ailment": "недомогание, лёгкая болезнь",
  "sprain": "растяжение (связок)",
  "fitness": "физическая форма",
  "wellness": "благополучие, здоровый образ жизни",
  "check-up": "медосмотр, профилактический осмотр",
  "sedentary": "малоподвижный, сидячий",
  "promotion": "повышение (по службе)",
  "redundancy": "сокращение (увольнение по сокращению штатов)",
  "freelancer": "фрилансер",
  "deadline": "крайний срок, дедлайн",
  "negotiate": "вести переговоры",
  "internship": "стажировка",
  "burnout": "выгорание (на работе)",
  "entrepreneurship": "предпринимательство",
  "layoff": "увольнение (массовое сокращение)",
  "workload": "рабочая нагрузка",
  "prospective": "потенциальный, будущий (о кандидате, клиенте)",
  "climb the ladder": "подниматься по карьерной лестнице",
  "curriculum": "учебная программа, curriculum",
  "tuition": "обучение; плата за обучение",
  "dissertation": "диссертация",
  "seminar": "семинар",
  "plagiarism": "плагиат",
  "enrol": "записаться, зачислиться (на курс)",
  "scholarship": "стипендия, грант на обучение",
  "literacy": "грамотность",
  "aptitude": "способность, склонность, дар",
  "extracurricular": "внеучебный, внеурочный",
  "thesis": "дипломная/магистерская работа, тезис",
  "lecture": "лекция",
  "sustainability": "устойчивое развитие, экологичность",
  "carbon footprint": "углеродный след",
  "renewable": "возобновляемый (об энергии)",
  "drought": "засуха",
  "biodiversity": "биоразнообразие",
  "emissions": "выбросы (загрязняющих веществ)",
  "conservation": "охрана природы, сохранение",
  "urbanisation": "урбанизация",
  "inequality": "неравенство",
  "refugee": "беженец",
  "infrastructure": "инфраструктура",
  "mitigate": "смягчать, уменьшать (вред, риск)",
  "break the ice": "растопить лёд, начать разговор",
  "hit the nail on the head": "попасть в точку, сказать в самое сердце",
  "once in a blue moon": "очень редко, раз в сто лет",
  "the ball is in your court": "ход за тобой, решать тебе",
  "burn the candle at both ends": "перегружать себя, не давать себе отдыха",
  "equivocal": "двусмысленный, неоднозначный",
  "quintessential": "типичный, образцовый, квинтэссенциальный",
  "pull someone's leg": "разыграть, подшутить над кем-то",
  "read between the lines": "читать между строк",
  "call it a day": "закончить на сегодня, остановиться",
  "get out of hand": "выйти из-под контроля",
  "parsimonious": "скупой, чрезмерно экономный",
  "hypothesis": "гипотеза",
  "methodology": "методология",
  "empirical": "эмпирический, основанный на наблюдении",
  "substantiate": "подтверждать, обосновывать",
  "paradigm": "парадигма, модель",
  "correlate": "коррелировать, находиться в связи",
  "inference": "вывод, умозаключение",
  "discourse": "дискурс, речь, обсуждение",
  "synthesize": "синтезировать, обобщать",
  "qualitative": "качественный (о методе исследования)",
  "quantitative": "количественный (о методе исследования)",
  "extrapolate": "экстраполировать, делать вывод на основе данных",
  "allegory": "аллегория",
  "prose": "проза",
  "rhetoric": "риторика, красноречие",
  "poignant": "пронзительный, трогательный",
  "eloquent": "красноречивый, выразительный",
  "terse": "лаконичный, сухой, резкий",
  "vernacular": "разговорный язык, народный язык",
  "foreshadow": "предвещать, предзнаменовать",
  "denouement": "развязка (сюжета)",
  "register": "регистр (стиль языка)",
  "satirical": "сатирический",
  "arcane": "тайный, малоизвестный, эзотерический",
  "juxtaposition": "сопоставление, juxtaposition",
  "nuanced": "нюансированный, тонкий (о аргументе)",
  "corroborate": "подтверждать, corroborate",
  "coherent": "связный, логичный, coherent",
  "contentious": "спорный, вызывающий разногласия",
  "proliferate": "распространяться, proliferate",
  "undermine": "подрывать, ослаблять",
  "comprehensive": "всесторонний, comprehensive",
  "outweigh": "перевешивать, outweigh",
  "feasible": "осуществимый, feasible",
  "negligible": "незначительный, negligible",
  "paramount": "первостепенный, paramount"
},
  en: {
  "name": "given name",
  "surname": "family name",
  "nationality": "nationality, citizenship",
  "address": "address",
  "occupation": "job, profession",
  "married": "married",
  "single": "single",
  "greet": "to greet",
  "introduce": "to introduce",
  "spell": "to spell",
  "age": "age",
  "email": "email",
  "phone number": "phone number",
  "hometown": "hometown",
  "wake up": "to wake up",
  "breakfast": "breakfast",
  "brush teeth": "to brush one's teeth",
  "commute": "to commute",
  "schedule": "schedule",
  "alarm clock": "alarm clock",
  "notebook": "notebook",
  "laptop": "laptop",
  "umbrella": "umbrella",
  "wallet": "wallet",
  "keys": "keys",
  "habit": "habit",
  "usually": "usually",
  "rarely": "rarely",
  "bank": "bank",
  "pharmacy": "pharmacy",
  "post office": "post office",
  "supermarket": "supermarket",
  "roundabout": "roundabout",
  "corner": "corner",
  "opposite": "opposite",
  "between": "between",
  "nearby": "nearby",
  "pedestrian": "pedestrian",
  "crossroads": "crossroads",
  "town hall": "town hall",
  "atm": "ATM",
  "parking": "parking",
  "departure": "departure",
  "arrival": "arrival",
  "delay": "delay",
  "boarding pass": "boarding pass",
  "customs": "customs",
  "luggage": "luggage",
  "sightseeing": "sightseeing",
  "souvenir": "souvenir",
  "booked": "booked",
  "cancelled": "cancelled",
  "missed": "missed",
  "delayed": "delayed",
  "platform": "platform",
  "itinerary": "itinerary",
  "bargain": "bargain",
  "refund": "refund",
  "discount": "discount",
  "fitting room": "fitting room",
  "cash register": "cash register",
  "receipt": "receipt",
  "cheaper": "cheaper",
  "more expensive": "more expensive",
  "the best": "the best",
  "bargain hunter": "bargain hunter",
  "exchange": "exchange",
  "warranty": "warranty",
  "brand": "brand",
  "checkout": "checkout",
  "smartphone": "smartphone",
  "app": "app",
  "update": "update",
  "wi-fi": "Wi-Fi",
  "streaming": "streaming",
  "subscription": "subscription",
  "notification": "notification",
  "backup": "backup",
  "cloud": "cloud",
  "gadget": "gadget",
  "online": "online",
  "offline": "offline",
  "password": "password",
  "cybersecurity": "cybersecurity",
  "decisive": "decisive",
  "indecisive": "indecisive",
  "conscientious": "conscientious",
  "impulsive": "impulsive",
  "deliberate": "deliberate",
  "prioritize": "to prioritize",
  "commitment": "commitment",
  "hesitate": "to hesitate",
  "reckon": "to reckon, to suppose",
  "weigh up": "to weigh up",
  "resolution": "resolution",
  "tentative": "tentative",
  "overwhelmed": "overwhelmed",
  "nostalgic": "nostalgic",
  "bittersweet": "bittersweet",
  "astonished": "astonished",
  "frustrated": "frustrated",
  "ecstatic": "ecstatic",
  "melancholy": "melancholy",
  "resentful": "resentful",
  "apprehensive": "apprehensive",
  "heartfelt": "heartfelt",
  "burst into tears": "to burst into tears",
  "take aback": "to take aback",
  "symptom": "symptom",
  "chronic": "chronic",
  "recover": "to recover",
  "prescribe": "to prescribe",
  "immune system": "immune system",
  "stamina": "stamina",
  "ailment": "ailment",
  "sprain": "sprain",
  "fitness": "fitness",
  "wellness": "wellness",
  "check-up": "check-up",
  "sedentary": "sedentary",
  "promotion": "promotion",
  "redundancy": "redundancy",
  "freelancer": "freelancer",
  "deadline": "deadline",
  "negotiate": "to negotiate",
  "internship": "internship",
  "burnout": "burnout",
  "entrepreneurship": "entrepreneurship",
  "layoff": "layoff",
  "workload": "workload",
  "prospective": "prospective",
  "climb the ladder": "to climb the ladder",
  "curriculum": "curriculum",
  "tuition": "tuition",
  "dissertation": "dissertation",
  "seminar": "seminar",
  "plagiarism": "plagiarism",
  "enrol": "to enrol",
  "scholarship": "scholarship",
  "literacy": "literacy",
  "aptitude": "aptitude",
  "extracurricular": "extracurricular",
  "thesis": "thesis",
  "lecture": "lecture",
  "sustainability": "sustainability",
  "carbon footprint": "carbon footprint",
  "renewable": "renewable",
  "drought": "drought",
  "biodiversity": "biodiversity",
  "emissions": "emissions",
  "conservation": "conservation",
  "urbanisation": "urbanisation",
  "inequality": "inequality",
  "refugee": "refugee",
  "infrastructure": "infrastructure",
  "mitigate": "to mitigate",
  "break the ice": "to break the ice",
  "hit the nail on the head": "to hit the nail on the head",
  "once in a blue moon": "once in a blue moon",
  "the ball is in your court": "the ball is in your court",
  "burn the candle at both ends": "to burn the candle at both ends",
  "equivocal": "equivocal",
  "quintessential": "quintessential",
  "pull someone's leg": "to pull someone's leg",
  "read between the lines": "to read between the lines",
  "call it a day": "to call it a day",
  "get out of hand": "to get out of hand",
  "parsimonious": "parsimonious",
  "hypothesis": "hypothesis",
  "methodology": "methodology",
  "empirical": "empirical",
  "substantiate": "to substantiate",
  "paradigm": "paradigm",
  "correlate": "to correlate",
  "inference": "inference",
  "discourse": "discourse",
  "synthesize": "to synthesize",
  "qualitative": "qualitative",
  "quantitative": "quantitative",
  "extrapolate": "to extrapolate",
  "allegory": "allegory",
  "prose": "prose",
  "rhetoric": "rhetoric",
  "poignant": "poignant",
  "eloquent": "eloquent",
  "terse": "terse",
  "vernacular": "vernacular",
  "foreshadow": "to foreshadow",
  "denouement": "denouement",
  "register": "register",
  "satirical": "satirical",
  "arcane": "arcane",
  "juxtaposition": "juxtaposition",
  "nuanced": "nuanced",
  "corroborate": "to corroborate",
  "coherent": "coherent",
  "contentious": "contentious",
  "proliferate": "to proliferate",
  "undermine": "to undermine",
  "comprehensive": "comprehensive",
  "outweigh": "to outweigh",
  "feasible": "feasible",
  "negligible": "negligible",
  "paramount": "paramount"
},
  es: {
  "name": "nombre",
  "surname": "apellido",
  "nationality": "nacionalidad",
  "address": "dirección",
  "occupation": "ocupación, profesión",
  "married": "casado/a",
  "single": "soltero/a",
  "greet": "saludar",
  "introduce": "presentar(se)",
  "spell": "deletrear",
  "age": "edad",
  "email": "correo electrónico",
  "phone number": "número de teléfono",
  "hometown": "ciudad natal",
  "wake up": "despertarse",
  "breakfast": "desayuno",
  "brush teeth": "cepillarse los dientes",
  "commute": "desplazarse al trabajo",
  "schedule": "horario",
  "alarm clock": "despertador",
  "notebook": "cuaderno",
  "laptop": "portátil",
  "umbrella": "paraguas",
  "wallet": "cartera",
  "keys": "llaves",
  "habit": "hábito",
  "usually": "normalmente",
  "rarely": "rara vez",
  "bank": "banco",
  "pharmacy": "farmacia",
  "post office": "oficina de correos",
  "supermarket": "supermercado",
  "roundabout": "rotonda",
  "corner": "esquina",
  "opposite": "enfrente de",
  "between": "entre",
  "nearby": "cerca",
  "pedestrian": "peatón",
  "crossroads": "cruce",
  "town hall": "ayuntamiento",
  "atm": "cajero automático",
  "parking": "aparcamiento",
  "departure": "salida",
  "arrival": "llegada",
  "delay": "retraso",
  "boarding pass": "tarjeta de embarque",
  "customs": "aduanas",
  "luggage": "equipaje",
  "sightseeing": "turismo",
  "souvenir": "recuerdo",
  "booked": "reservado",
  "cancelled": "cancelado",
  "missed": "perdido",
  "delayed": "retrasado",
  "platform": "andén",
  "itinerary": "itinerario",
  "bargain": "ganga",
  "refund": "reembolso",
  "discount": "descuento",
  "fitting room": "probador",
  "cash register": "caja",
  "receipt": "recibo",
  "cheaper": "más barato",
  "more expensive": "más caro",
  "the best": "el mejor",
  "bargain hunter": "cazador de gangas",
  "exchange": "cambio",
  "warranty": "garantía",
  "brand": "marca",
  "checkout": "pago",
  "smartphone": "smartphone",
  "app": "aplicación",
  "update": "actualización",
  "wi-fi": "Wi-Fi",
  "streaming": "streaming",
  "subscription": "suscripción",
  "notification": "notificación",
  "backup": "copia de seguridad",
  "cloud": "nube",
  "gadget": "dispositivo",
  "online": "en línea",
  "offline": "sin conexión",
  "password": "contraseña",
  "cybersecurity": "ciberseguridad",
  "decisive": "decisivo",
  "indecisive": "indeciso",
  "conscientious": "consciente",
  "impulsive": "impulsivo",
  "deliberate": "deliberado",
  "prioritize": "priorizar",
  "commitment": "compromiso",
  "hesitate": "dudar",
  "reckon": "creer, suponer",
  "weigh up": "sopesar",
  "resolution": "resolución",
  "tentative": "tentativo",
  "overwhelmed": "abrumado",
  "nostalgic": "nostálgico",
  "bittersweet": "agridulce",
  "astonished": "asombrado",
  "frustrated": "frustrado",
  "ecstatic": "extasiado",
  "melancholy": "melancolía",
  "resentful": "resentido",
  "apprehensive": "aprensivo",
  "heartfelt": "sentido",
  "burst into tears": "echarse a llorar",
  "take aback": "sorprender",
  "symptom": "síntoma",
  "chronic": "crónico",
  "recover": "recuperarse",
  "prescribe": "recetar",
  "immune system": "sistema inmunitario",
  "stamina": "resistencia",
  "ailment": "dolencia",
  "sprain": "esguince",
  "fitness": "forma física",
  "wellness": "bienestar",
  "check-up": "revisión médica",
  "sedentary": "sedentario",
  "promotion": "ascenso",
  "redundancy": "despido",
  "freelancer": "autónomo",
  "deadline": "fecha límite",
  "negotiate": "negociar",
  "internship": "prácticas",
  "burnout": "agotamiento",
  "entrepreneurship": "espíritu empresarial",
  "layoff": "despido",
  "workload": "carga de trabajo",
  "prospective": "potencial",
  "climb the ladder": "ascender",
  "curriculum": "plan de estudios",
  "tuition": "matrícula",
  "dissertation": "tesis doctoral",
  "seminar": "seminario",
  "plagiarism": "plagio",
  "enrol": "matricularse",
  "scholarship": "beca",
  "literacy": "alfabetización",
  "aptitude": "aptitud",
  "extracurricular": "extraescolar",
  "thesis": "tesis",
  "lecture": "conferencia",
  "sustainability": "sostenibilidad",
  "carbon footprint": "huella de carbono",
  "renewable": "renovable",
  "drought": "sequía",
  "biodiversity": "biodiversidad",
  "emissions": "emisiones",
  "conservation": "conservación",
  "urbanisation": "urbanización",
  "inequality": "desigualdad",
  "refugee": "refugiado",
  "infrastructure": "infraestructura",
  "mitigate": "mitigar",
  "break the ice": "romper el hielo",
  "hit the nail on the head": "dar en el clavo",
  "once in a blue moon": "muy de vez en cuando",
  "the ball is in your court": "te toca a ti",
  "burn the candle at both ends": "quemarse las pestañas",
  "equivocal": "equívoco",
  "quintessential": "quintesencial",
  "pull someone's leg": "tomar el pelo",
  "read between the lines": "leer entre líneas",
  "call it a day": "dar por terminado",
  "get out of hand": "salirse de control",
  "parsimonious": "parsimonious",
  "hypothesis": "hipótesis",
  "methodology": "metodología",
  "empirical": "empírico",
  "substantiate": "fundamentar",
  "paradigm": "paradigma",
  "correlate": "correlacionar",
  "inference": "inferencia",
  "discourse": "discurso",
  "synthesize": "sintetizar",
  "qualitative": "cualitativo",
  "quantitative": "cuantitativo",
  "extrapolate": "extrapolar",
  "allegory": "alegoría",
  "prose": "prosa",
  "rhetoric": "retórica",
  "poignant": "conmovedor",
  "eloquent": "elocuente",
  "terse": "lacónico",
  "vernacular": "vernáculo",
  "foreshadow": "presagiar",
  "denouement": "desenlace",
  "register": "registro",
  "satirical": "satírico",
  "arcane": "arcano",
  "juxtaposition": "yuxtaposición",
  "nuanced": "matizado",
  "corroborate": "corroborar",
  "coherent": "coherente",
  "contentious": "polémico",
  "proliferate": "proliferar",
  "undermine": "minar",
  "comprehensive": "exhaustivo",
  "outweigh": "superar en importancia",
  "feasible": "factible",
  "negligible": "insignificante",
  "paramount": "primordial"
},
  de: {
  "name": "given name",
  "surname": "family name",
  "nationality": "nationality, citizenship",
  "address": "address",
  "occupation": "job, profession",
  "married": "married",
  "single": "single",
  "greet": "to greet",
  "introduce": "to introduce",
  "spell": "to spell",
  "age": "age",
  "email": "email",
  "phone number": "phone number",
  "hometown": "hometown",
  "wake up": "to wake up",
  "breakfast": "breakfast",
  "brush teeth": "to brush one's teeth",
  "commute": "to commute",
  "schedule": "schedule",
  "alarm clock": "alarm clock",
  "notebook": "notebook",
  "laptop": "laptop",
  "umbrella": "umbrella",
  "wallet": "wallet",
  "keys": "keys",
  "habit": "habit",
  "usually": "usually",
  "rarely": "rarely",
  "bank": "bank",
  "pharmacy": "pharmacy",
  "post office": "post office",
  "supermarket": "supermarket",
  "roundabout": "roundabout",
  "corner": "corner",
  "opposite": "opposite",
  "between": "between",
  "nearby": "nearby",
  "pedestrian": "pedestrian",
  "crossroads": "crossroads",
  "town hall": "town hall",
  "atm": "ATM",
  "parking": "parking",
  "departure": "departure",
  "arrival": "arrival",
  "delay": "delay",
  "boarding pass": "boarding pass",
  "customs": "customs",
  "luggage": "luggage",
  "sightseeing": "sightseeing",
  "souvenir": "souvenir",
  "booked": "booked",
  "cancelled": "cancelled",
  "missed": "missed",
  "delayed": "delayed",
  "platform": "platform",
  "itinerary": "itinerary",
  "bargain": "bargain",
  "refund": "refund",
  "discount": "discount",
  "fitting room": "fitting room",
  "cash register": "cash register",
  "receipt": "receipt",
  "cheaper": "cheaper",
  "more expensive": "more expensive",
  "the best": "the best",
  "bargain hunter": "bargain hunter",
  "exchange": "exchange",
  "warranty": "warranty",
  "brand": "brand",
  "checkout": "checkout",
  "smartphone": "smartphone",
  "app": "app",
  "update": "update",
  "wi-fi": "Wi-Fi",
  "streaming": "streaming",
  "subscription": "subscription",
  "notification": "notification",
  "backup": "backup",
  "cloud": "cloud",
  "gadget": "gadget",
  "online": "online",
  "offline": "offline",
  "password": "password",
  "cybersecurity": "cybersecurity",
  "decisive": "decisive",
  "indecisive": "indecisive",
  "conscientious": "conscientious",
  "impulsive": "impulsive",
  "deliberate": "deliberate",
  "prioritize": "to prioritize",
  "commitment": "commitment",
  "hesitate": "to hesitate",
  "reckon": "to reckon, to suppose",
  "weigh up": "to weigh up",
  "resolution": "resolution",
  "tentative": "tentative",
  "overwhelmed": "overwhelmed",
  "nostalgic": "nostalgic",
  "bittersweet": "bittersweet",
  "astonished": "astonished",
  "frustrated": "frustrated",
  "ecstatic": "ecstatic",
  "melancholy": "melancholy",
  "resentful": "resentful",
  "apprehensive": "apprehensive",
  "heartfelt": "heartfelt",
  "burst into tears": "to burst into tears",
  "take aback": "to take aback",
  "symptom": "symptom",
  "chronic": "chronic",
  "recover": "to recover",
  "prescribe": "to prescribe",
  "immune system": "immune system",
  "stamina": "stamina",
  "ailment": "ailment",
  "sprain": "sprain",
  "fitness": "fitness",
  "wellness": "wellness",
  "check-up": "check-up",
  "sedentary": "sedentary",
  "promotion": "promotion",
  "redundancy": "redundancy",
  "freelancer": "freelancer",
  "deadline": "deadline",
  "negotiate": "to negotiate",
  "internship": "internship",
  "burnout": "burnout",
  "entrepreneurship": "entrepreneurship",
  "layoff": "layoff",
  "workload": "workload",
  "prospective": "prospective",
  "climb the ladder": "to climb the ladder",
  "curriculum": "curriculum",
  "tuition": "tuition",
  "dissertation": "dissertation",
  "seminar": "seminar",
  "plagiarism": "plagiarism",
  "enrol": "to enrol",
  "scholarship": "scholarship",
  "literacy": "literacy",
  "aptitude": "aptitude",
  "extracurricular": "extracurricular",
  "thesis": "thesis",
  "lecture": "lecture",
  "sustainability": "sustainability",
  "carbon footprint": "carbon footprint",
  "renewable": "renewable",
  "drought": "drought",
  "biodiversity": "biodiversity",
  "emissions": "emissions",
  "conservation": "conservation",
  "urbanisation": "urbanisation",
  "inequality": "inequality",
  "refugee": "refugee",
  "infrastructure": "infrastructure",
  "mitigate": "to mitigate",
  "break the ice": "to break the ice",
  "hit the nail on the head": "to hit the nail on the head",
  "once in a blue moon": "once in a blue moon",
  "the ball is in your court": "the ball is in your court",
  "burn the candle at both ends": "to burn the candle at both ends",
  "equivocal": "equivocal",
  "quintessential": "quintessential",
  "pull someone's leg": "to pull someone's leg",
  "read between the lines": "to read between the lines",
  "call it a day": "to call it a day",
  "get out of hand": "to get out of hand",
  "parsimonious": "parsimonious",
  "hypothesis": "hypothesis",
  "methodology": "methodology",
  "empirical": "empirical",
  "substantiate": "to substantiate",
  "paradigm": "paradigm",
  "correlate": "to correlate",
  "inference": "inference",
  "discourse": "discourse",
  "synthesize": "to synthesize",
  "qualitative": "qualitative",
  "quantitative": "quantitative",
  "extrapolate": "to extrapolate",
  "allegory": "allegory",
  "prose": "prose",
  "rhetoric": "rhetoric",
  "poignant": "poignant",
  "eloquent": "eloquent",
  "terse": "terse",
  "vernacular": "vernacular",
  "foreshadow": "to foreshadow",
  "denouement": "denouement",
  "register": "register",
  "satirical": "satirical",
  "arcane": "arcane",
  "juxtaposition": "juxtaposition",
  "nuanced": "nuanced",
  "corroborate": "to corroborate",
  "coherent": "coherent",
  "contentious": "contentious",
  "proliferate": "to proliferate",
  "undermine": "to undermine",
  "comprehensive": "comprehensive",
  "outweigh": "to outweigh",
  "feasible": "feasible",
  "negligible": "negligible",
  "paramount": "paramount"
},
};
