import { w, topic } from "./helpers";
import type { VocabTopic } from "@/types";

/**
 * Extra English vocabulary topics to close the gap with the Spanish bank.
 * Aim: everyday + exam-useful coverage at ~20–25 words per topic.
 */
export const ENGLISH_VOCAB_EXPAND: VocabTopic[] = [
  topic(
    {
      slug: "eng-a1-family-home",
      level: "A1",
      topic: "Семья и дом",
      topicEs: "Family & home",
      topicEn: "Family & home",
      icon: "🏠",
      chapterSlug: "eng-ch1-first-steps",
    },
    [
      w({ word: "family", transcription: "/ˈfæməli/", partOfSpeech: "noun", translation: "семья", examples: ["I have a big family.", "Family is important to me."], frequency: "core", level: "A1", tags: ["family"], chapterSlug: "eng-ch1-first-steps", synonyms: ["relatives"] }),
      w({ word: "parents", transcription: "/ˈpeərənts/", partOfSpeech: "noun", translation: "родители", examples: ["My parents live in Moscow.", "Do your parents speak English?"], frequency: "core", level: "A1", tags: ["family"], chapterSlug: "eng-ch1-first-steps" }),
      w({ word: "brother", transcription: "/ˈbrʌðə/", partOfSpeech: "noun", translation: "брат", examples: ["I have one brother.", "My brother is a student."], frequency: "core", level: "A1", tags: ["family"], chapterSlug: "eng-ch1-first-steps" }),
      w({ word: "sister", transcription: "/ˈsɪstə/", partOfSpeech: "noun", translation: "сестра", examples: ["She is my sister.", "My sister works in a bank."], frequency: "core", level: "A1", tags: ["family"], chapterSlug: "eng-ch1-first-steps" }),
      w({ word: "husband", transcription: "/ˈhʌzbənd/", partOfSpeech: "noun", translation: "муж", examples: ["Her husband is a teacher.", "This is my husband, Mark."], frequency: "core", level: "A1", tags: ["family"], chapterSlug: "eng-ch1-first-steps" }),
      w({ word: "wife", transcription: "/waɪf/", partOfSpeech: "noun", translation: "жена", examples: ["His wife is from Spain.", "I'd like you to meet my wife."], frequency: "core", level: "A1", tags: ["family"], chapterSlug: "eng-ch1-first-steps" }),
      w({ word: "child", transcription: "/tʃaɪld/", partOfSpeech: "noun", translation: "ребёнок", examples: ["They have one child.", "Every child needs love."], frequency: "core", level: "A1", tags: ["family"], chapterSlug: "eng-ch1-first-steps", synonyms: ["kid"], commonMistakes: ["Мн.ч. children, не *childs."] }),
      w({ word: "kitchen", transcription: "/ˈkɪtʃɪn/", partOfSpeech: "noun", translation: "кухня", examples: ["The kitchen is small but bright.", "We're in the kitchen."], frequency: "core", level: "A1", tags: ["home"], chapterSlug: "eng-ch1-first-steps" }),
      w({ word: "bedroom", transcription: "/ˈbedruːm/", partOfSpeech: "noun", translation: "спальня", examples: ["My bedroom faces the garden.", "There are two bedrooms."], frequency: "core", level: "A1", tags: ["home"], chapterSlug: "eng-ch1-first-steps" }),
      w({ word: "bathroom", transcription: "/ˈbɑːθruːm/", partOfSpeech: "noun", translation: "ванная", examples: ["Where is the bathroom?", "The bathroom is upstairs."], frequency: "core", level: "A1", tags: ["home"], chapterSlug: "eng-ch1-first-steps" }),
      w({ word: "living room", transcription: "/ˈlɪvɪŋ ruːm/", partOfSpeech: "noun", translation: "гостиная", examples: ["We watch TV in the living room.", "The living room is cosy."], frequency: "core", level: "A1", tags: ["home"], chapterSlug: "eng-ch1-first-steps", synonyms: ["lounge"] }),
      w({ word: "furniture", transcription: "/ˈfɜːnɪtʃə/", partOfSpeech: "noun", translation: "мебель", examples: ["The furniture is modern.", "We need new furniture."], frequency: "common", level: "A1", tags: ["home"], chapterSlug: "eng-ch1-first-steps", commonMistakes: ["Furniture неисчисляемое: some furniture, не *furnitures."] }),
      w({ word: "neighbour", transcription: "/ˈneɪbə/", partOfSpeech: "noun", translation: "сосед", examples: ["Our neighbours are friendly.", "I borrowed sugar from my neighbour."], frequency: "common", level: "A1", tags: ["home"], chapterSlug: "eng-ch1-first-steps", synonyms: ["neighbor (US)"] }),
      w({ word: "flat", transcription: "/flæt/", partOfSpeech: "noun", translation: "квартира", examples: ["I live in a flat.", "Their flat is on the third floor."], frequency: "core", level: "A1", tags: ["home"], chapterSlug: "eng-ch1-first-steps", synonyms: ["apartment"] }),
      w({ word: "garden", transcription: "/ˈɡɑːdn/", partOfSpeech: "noun", translation: "сад", examples: ["The children play in the garden.", "We have a small garden."], frequency: "common", level: "A1", tags: ["home"], chapterSlug: "eng-ch1-first-steps" }),
      w({ word: "key", transcription: "/kiː/", partOfSpeech: "noun", translation: "ключ", examples: ["I lost my keys.", "Here's the key to the door."], frequency: "core", level: "A1", tags: ["home"], chapterSlug: "eng-ch1-first-steps" }),
      w({ word: "clean", transcription: "/kliːn/", partOfSpeech: "adjective", translation: "чистый", examples: ["Keep your room clean.", "The kitchen is clean."], frequency: "core", level: "A1", tags: ["home"], chapterSlug: "eng-ch1-first-steps" }),
      w({ word: "dirty", transcription: "/ˈdɜːti/", partOfSpeech: "adjective", translation: "грязный", examples: ["These shoes are dirty.", "Don't sit on the dirty floor."], frequency: "common", level: "A1", tags: ["home"], chapterSlug: "eng-ch1-first-steps" }),
      w({ word: "quiet", transcription: "/ˈkwaɪət/", partOfSpeech: "adjective", translation: "тихий", examples: ["It's a quiet street.", "Please be quiet."], frequency: "common", level: "A1", tags: ["home"], chapterSlug: "eng-ch1-first-steps" }),
      w({ word: "comfortable", transcription: "/ˈkʌmftəbl/", partOfSpeech: "adjective", translation: "удобный", examples: ["This sofa is comfortable.", "Wear comfortable shoes."], frequency: "common", level: "A1", tags: ["home"], chapterSlug: "eng-ch1-first-steps" }),
      w({ word: "rent", transcription: "/rent/", partOfSpeech: "verb", translation: "снимать (жильё)", examples: ["We rent a flat near the park.", "They rent a car every summer."], frequency: "common", level: "A1", tags: ["home"], chapterSlug: "eng-ch1-first-steps" }),
      w({ word: "move", transcription: "/muːv/", partOfSpeech: "verb", translation: "переезжать", examples: ["We moved to London last year.", "When did you move house?"], frequency: "common", level: "A1", tags: ["home"], chapterSlug: "eng-ch1-first-steps" }),
    ],
  ),
  topic(
    {
      slug: "eng-a1-food-drink",
      level: "A1",
      topic: "Еда и напитки",
      topicEs: "Food & drink",
      topicEn: "Food & drink",
      icon: "🍽️",
      chapterSlug: "eng-ch2-routines",
    },
    [
      w({ word: "breakfast", transcription: "/ˈbrekfəst/", partOfSpeech: "noun", translation: "завтрак", examples: ["I have breakfast at eight.", "What's for breakfast?"], frequency: "core", level: "A1", tags: ["food"], chapterSlug: "eng-ch2-routines" }),
      w({ word: "lunch", transcription: "/lʌntʃ/", partOfSpeech: "noun", translation: "обед", examples: ["Let's have lunch together.", "Lunch is at one."], frequency: "core", level: "A1", tags: ["food"], chapterSlug: "eng-ch2-routines" }),
      w({ word: "dinner", transcription: "/ˈdɪnə/", partOfSpeech: "noun", translation: "ужин", examples: ["Dinner is ready.", "We had fish for dinner."], frequency: "core", level: "A1", tags: ["food"], chapterSlug: "eng-ch2-routines" }),
      w({ word: "hungry", transcription: "/ˈhʌŋɡri/", partOfSpeech: "adjective", translation: "голодный", examples: ["I'm hungry.", "The children are hungry."], frequency: "core", level: "A1", tags: ["food"], chapterSlug: "eng-ch2-routines" }),
      w({ word: "thirsty", transcription: "/ˈθɜːsti/", partOfSpeech: "adjective", translation: "хочет пить", examples: ["I'm thirsty — I need water.", "Are you thirsty?"], frequency: "core", level: "A1", tags: ["food"], chapterSlug: "eng-ch2-routines" }),
      w({ word: "bread", transcription: "/bred/", partOfSpeech: "noun", translation: "хлеб", examples: ["Buy some bread, please.", "This bread is fresh."], frequency: "core", level: "A1", tags: ["food"], chapterSlug: "eng-ch2-routines" }),
      w({ word: "cheese", transcription: "/tʃiːz/", partOfSpeech: "noun", translation: "сыр", examples: ["I like cheese.", "Cheese and bread, please."], frequency: "core", level: "A1", tags: ["food"], chapterSlug: "eng-ch2-routines" }),
      w({ word: "chicken", transcription: "/ˈtʃɪkɪn/", partOfSpeech: "noun", translation: "курица", examples: ["We had chicken for dinner.", "Is the chicken ready?"], frequency: "core", level: "A1", tags: ["food"], chapterSlug: "eng-ch2-routines" }),
      w({ word: "fish", transcription: "/fɪʃ/", partOfSpeech: "noun", translation: "рыба", examples: ["I don't eat fish.", "Fresh fish is expensive."], frequency: "core", level: "A1", tags: ["food"], chapterSlug: "eng-ch2-routines" }),
      w({ word: "vegetable", transcription: "/ˈvedʒtəbl/", partOfSpeech: "noun", translation: "овощ", examples: ["Eat more vegetables.", "Carrots are vegetables."], frequency: "core", level: "A1", tags: ["food"], chapterSlug: "eng-ch2-routines" }),
      w({ word: "fruit", transcription: "/fruːt/", partOfSpeech: "noun", translation: "фрукты", examples: ["Fruit is healthy.", "Would you like some fruit?"], frequency: "core", level: "A1", tags: ["food"], chapterSlug: "eng-ch2-routines" }),
      w({ word: "coffee", transcription: "/ˈkɒfi/", partOfSpeech: "noun", translation: "кофе", examples: ["I drink coffee every morning.", "Two coffees, please."], frequency: "core", level: "A1", tags: ["food"], chapterSlug: "eng-ch2-routines" }),
      w({ word: "tea", transcription: "/tiː/", partOfSpeech: "noun", translation: "чай", examples: ["Would you like some tea?", "British people drink a lot of tea."], frequency: "core", level: "A1", tags: ["food"], chapterSlug: "eng-ch2-routines" }),
      w({ word: "water", transcription: "/ˈwɔːtə/", partOfSpeech: "noun", translation: "вода", examples: ["Can I have some water?", "Drink more water."], frequency: "core", level: "A1", tags: ["food"], chapterSlug: "eng-ch2-routines" }),
      w({ word: "juice", transcription: "/dʒuːs/", partOfSpeech: "noun", translation: "сок", examples: ["Orange juice, please.", "I prefer apple juice."], frequency: "common", level: "A1", tags: ["food"], chapterSlug: "eng-ch2-routines" }),
      w({ word: "menu", transcription: "/ˈmenjuː/", partOfSpeech: "noun", translation: "меню", examples: ["Can I see the menu?", "The menu looks great."], frequency: "common", level: "A1", tags: ["food"], chapterSlug: "eng-ch2-routines" }),
      w({ word: "bill", transcription: "/bɪl/", partOfSpeech: "noun", translation: "счёт", examples: ["Could we have the bill?", "The bill is on me."], frequency: "common", level: "A1", tags: ["food"], chapterSlug: "eng-ch2-routines", synonyms: ["check (US)"] }),
      w({ word: "delicious", transcription: "/dɪˈlɪʃəs/", partOfSpeech: "adjective", translation: "очень вкусный", examples: ["This soup is delicious.", "The cake was delicious."], frequency: "common", level: "A1", tags: ["food"], chapterSlug: "eng-ch2-routines" }),
      w({ word: "order", transcription: "/ˈɔːdə/", partOfSpeech: "verb", translation: "заказывать", examples: ["I'd like to order, please.", "We ordered pizza."], frequency: "core", level: "A1", tags: ["food"], chapterSlug: "eng-ch2-routines" }),
      w({ word: "cook", transcription: "/kʊk/", partOfSpeech: "verb", translation: "готовить", examples: ["I cook every evening.", "Who cooked this?"], frequency: "core", level: "A1", tags: ["food"], chapterSlug: "eng-ch2-routines" }),
      w({ word: "taste", transcription: "/teɪst/", partOfSpeech: "verb", translation: "пробовать на вкус", examples: ["Taste this sauce.", "It tastes sweet."], frequency: "common", level: "A1", tags: ["food"], chapterSlug: "eng-ch2-routines" }),
      w({ word: "restaurant", transcription: "/ˈrestrɒnt/", partOfSpeech: "noun", translation: "ресторан", examples: ["Let's go to a restaurant.", "This restaurant is busy."], frequency: "core", level: "A1", tags: ["food"], chapterSlug: "eng-ch2-routines" }),
    ],
  ),
  topic(
    {
      slug: "eng-a2-clothes-shopping",
      level: "A2",
      topic: "Одежда и покупки",
      topicEs: "Clothes & shopping",
      topicEn: "Clothes & shopping",
      icon: "🛍️",
      chapterSlug: "eng-ch3-around-town",
    },
    [
      w({ word: "shirt", transcription: "/ʃɜːt/", partOfSpeech: "noun", translation: "рубашка", examples: ["I need a new shirt.", "This shirt is too small."], frequency: "core", level: "A2", tags: ["clothes"], chapterSlug: "eng-ch3-around-town" }),
      w({ word: "trousers", transcription: "/ˈtraʊzəz/", partOfSpeech: "noun", translation: "брюки", examples: ["These trousers are comfortable.", "Black trousers, please."], frequency: "core", level: "A2", tags: ["clothes"], chapterSlug: "eng-ch3-around-town", synonyms: ["pants (US)"], commonMistakes: ["Всегда мн.ч. в BrE: trousers are…"] }),
      w({ word: "dress", transcription: "/dres/", partOfSpeech: "noun", translation: "платье", examples: ["She wore a blue dress.", "This dress fits perfectly."], frequency: "core", level: "A2", tags: ["clothes"], chapterSlug: "eng-ch3-around-town" }),
      w({ word: "jacket", transcription: "/ˈdʒækɪt/", partOfSpeech: "noun", translation: "куртка", examples: ["Take a jacket — it's cold.", "I like your jacket."], frequency: "core", level: "A2", tags: ["clothes"], chapterSlug: "eng-ch3-around-town" }),
      w({ word: "shoes", transcription: "/ʃuːz/", partOfSpeech: "noun", translation: "туфли, обувь", examples: ["These shoes are new.", "Take off your shoes."], frequency: "core", level: "A2", tags: ["clothes"], chapterSlug: "eng-ch3-around-town" }),
      w({ word: "size", transcription: "/saɪz/", partOfSpeech: "noun", translation: "размер", examples: ["What size are you?", "Do you have this in a larger size?"], frequency: "core", level: "A2", tags: ["shopping"], chapterSlug: "eng-ch3-around-town" }),
      w({ word: "fit", transcription: "/fɪt/", partOfSpeech: "verb", translation: "сидеть (по размеру)", examples: ["These jeans fit well.", "It doesn't fit me."], frequency: "common", level: "A2", tags: ["clothes"], chapterSlug: "eng-ch3-around-town" }),
      w({ word: "try on", transcription: "/traɪ ɒn/", partOfSpeech: "verb", translation: "примерять", examples: ["Can I try this on?", "She tried on three dresses."], frequency: "common", level: "A2", tags: ["shopping"], chapterSlug: "eng-ch3-around-town" }),
      w({ word: "price", transcription: "/praɪs/", partOfSpeech: "noun", translation: "цена", examples: ["What's the price?", "The price is too high."], frequency: "core", level: "A2", tags: ["shopping"], chapterSlug: "eng-ch3-around-town" }),
      w({ word: "expensive", transcription: "/ɪkˈspensɪv/", partOfSpeech: "adjective", translation: "дорогой", examples: ["This bag is expensive.", "London is expensive."], frequency: "core", level: "A2", tags: ["shopping"], chapterSlug: "eng-ch3-around-town" }),
      w({ word: "cheap", transcription: "/tʃiːp/", partOfSpeech: "adjective", translation: "дешёвый", examples: ["These shoes were cheap.", "I need something cheaper."], frequency: "core", level: "A2", tags: ["shopping"], chapterSlug: "eng-ch3-around-town" }),
      w({ word: "discount", transcription: "/ˈdɪskaʊnt/", partOfSpeech: "noun", translation: "скидка", examples: ["Is there a discount?", "Students get a discount."], frequency: "common", level: "A2", tags: ["shopping"], chapterSlug: "eng-ch3-around-town" }),
      w({ word: "receipt", transcription: "/rɪˈsiːt/", partOfSpeech: "noun", translation: "чек", examples: ["Keep the receipt.", "Can I have a receipt?"], frequency: "common", level: "A2", tags: ["shopping"], chapterSlug: "eng-ch3-around-town" }),
      w({ word: "cash", transcription: "/kæʃ/", partOfSpeech: "noun", translation: "наличные", examples: ["Do you take cash?", "I paid in cash."], frequency: "core", level: "A2", tags: ["shopping"], chapterSlug: "eng-ch3-around-town" }),
      w({ word: "card", transcription: "/kɑːd/", partOfSpeech: "noun", translation: "карта", examples: ["I'll pay by card.", "Contactless card, please."], frequency: "core", level: "A2", tags: ["shopping"], chapterSlug: "eng-ch3-around-town" }),
      w({ word: "customer", transcription: "/ˈkʌstəmə/", partOfSpeech: "noun", translation: "покупатель", examples: ["The customer is waiting.", "We listen to our customers."], frequency: "common", level: "A2", tags: ["shopping"], chapterSlug: "eng-ch3-around-town" }),
      w({ word: "shop assistant", transcription: "/ʃɒp əˈsɪstənt/", partOfSpeech: "noun", translation: "продавец", examples: ["Ask the shop assistant.", "The shop assistant was helpful."], frequency: "common", level: "A2", tags: ["shopping"], chapterSlug: "eng-ch3-around-town" }),
      w({ word: "return", transcription: "/rɪˈtɜːn/", partOfSpeech: "verb", translation: "вернуть товар", examples: ["Can I return this?", "I returned the jacket yesterday."], frequency: "common", level: "A2", tags: ["shopping"], chapterSlug: "eng-ch3-around-town" }),
      w({ word: "fashion", transcription: "/ˈfæʃn/", partOfSpeech: "noun", translation: "мода", examples: ["Fashion changes quickly.", "She's interested in fashion."], frequency: "common", level: "A2", tags: ["clothes"], chapterSlug: "eng-ch3-around-town" }),
      w({ word: "comfortable", transcription: "/ˈkʌmftəbl/", partOfSpeech: "adjective", translation: "удобный", examples: ["These shoes are comfortable.", "I want something comfortable."], frequency: "common", level: "A2", tags: ["clothes"], chapterSlug: "eng-ch3-around-town" }),
      w({ word: "cotton", transcription: "/ˈkɒtn/", partOfSpeech: "noun", translation: "хлопок", examples: ["This shirt is cotton.", "I prefer cotton clothes."], frequency: "common", level: "A2", tags: ["clothes"], chapterSlug: "eng-ch3-around-town" }),
      w({ word: "leather", transcription: "/ˈleðə/", partOfSpeech: "noun", translation: "кожа (материал)", examples: ["a leather jacket", "leather shoes"], frequency: "common", level: "A2", tags: ["clothes"], chapterSlug: "eng-ch3-around-town" }),
    ],
  ),
  topic(
    {
      slug: "eng-a2-travel-transport",
      level: "A2",
      topic: "Путешествия и транспорт",
      topicEs: "Travel & transport",
      topicEn: "Travel & transport",
      icon: "✈️",
      chapterSlug: "eng-ch3-around-town",
    },
    [
      w({ word: "airport", transcription: "/ˈeəpɔːt/", partOfSpeech: "noun", translation: "аэропорт", examples: ["We arrived at the airport early.", "Which airport are you flying from?"], frequency: "core", level: "A2", tags: ["travel"], chapterSlug: "eng-ch3-around-town" }),
      w({ word: "passport", transcription: "/ˈpɑːspɔːt/", partOfSpeech: "noun", translation: "паспорт", examples: ["Don't forget your passport.", "Show your passport, please."], frequency: "core", level: "A2", tags: ["travel"], chapterSlug: "eng-ch3-around-town" }),
      w({ word: "ticket", transcription: "/ˈtɪkɪt/", partOfSpeech: "noun", translation: "билет", examples: ["I bought a train ticket.", "Have you got your tickets?"], frequency: "core", level: "A2", tags: ["travel"], chapterSlug: "eng-ch3-around-town" }),
      w({ word: "flight", transcription: "/flaɪt/", partOfSpeech: "noun", translation: "рейс, полёт", examples: ["Our flight is delayed.", "Have a nice flight!"], frequency: "core", level: "A2", tags: ["travel"], chapterSlug: "eng-ch3-around-town" }),
      w({ word: "train", transcription: "/treɪn/", partOfSpeech: "noun", translation: "поезд", examples: ["The train leaves at 9.", "We went by train."], frequency: "core", level: "A2", tags: ["travel"], chapterSlug: "eng-ch3-around-town" }),
      w({ word: "bus", transcription: "/bʌs/", partOfSpeech: "noun", translation: "автобус", examples: ["Take the bus to the centre.", "Which bus goes to the station?"], frequency: "core", level: "A2", tags: ["travel"], chapterSlug: "eng-ch3-around-town" }),
      w({ word: "station", transcription: "/ˈsteɪʃn/", partOfSpeech: "noun", translation: "вокзал, станция", examples: ["Meet me at the station.", "The metro station is nearby."], frequency: "core", level: "A2", tags: ["travel"], chapterSlug: "eng-ch3-around-town" }),
      w({ word: "luggage", transcription: "/ˈlʌɡɪdʒ/", partOfSpeech: "noun", translation: "багаж", examples: ["Where is the luggage?", "How much luggage can I take?"], frequency: "common", level: "A2", tags: ["travel"], chapterSlug: "eng-ch3-around-town", synonyms: ["baggage"], commonMistakes: ["Неисчисляемое: some luggage."] }),
      w({ word: "delay", transcription: "/dɪˈleɪ/", partOfSpeech: "noun", translation: "задержка", examples: ["There is a short delay.", "Sorry for the delay."], frequency: "common", level: "A2", tags: ["travel"], chapterSlug: "eng-ch3-around-town" }),
      w({ word: "booking", transcription: "/ˈbʊkɪŋ/", partOfSpeech: "noun", translation: "бронь", examples: ["I have a booking under Smith.", "Cancel the booking."], frequency: "common", level: "A2", tags: ["travel"], chapterSlug: "eng-ch3-around-town", synonyms: ["reservation"] }),
      w({ word: "hotel", transcription: "/həʊˈtel/", partOfSpeech: "noun", translation: "отель", examples: ["We're staying at a hotel.", "The hotel is near the beach."], frequency: "core", level: "A2", tags: ["travel"], chapterSlug: "eng-ch3-around-town" }),
      w({ word: "map", transcription: "/mæp/", partOfSpeech: "noun", translation: "карта", examples: ["Look at the map.", "I need a city map."], frequency: "common", level: "A2", tags: ["travel"], chapterSlug: "eng-ch3-around-town" }),
      w({ word: "direction", transcription: "/dəˈrekʃn/", partOfSpeech: "noun", translation: "направление", examples: ["Can you give me directions?", "We walked in the wrong direction."], frequency: "common", level: "A2", tags: ["travel"], chapterSlug: "eng-ch3-around-town" }),
      w({ word: "platform", transcription: "/ˈplætfɔːm/", partOfSpeech: "noun", translation: "платформа", examples: ["The train is on platform 4.", "Which platform?"], frequency: "common", level: "A2", tags: ["travel"], chapterSlug: "eng-ch3-around-town" }),
      w({ word: "passenger", transcription: "/ˈpæsɪndʒə/", partOfSpeech: "noun", translation: "пассажир", examples: ["Passengers must wait.", "All passengers, please board."], frequency: "common", level: "A2", tags: ["travel"], chapterSlug: "eng-ch3-around-town" }),
      w({ word: "arrive", transcription: "/əˈraɪv/", partOfSpeech: "verb", translation: "прибывать", examples: ["We arrive at 6.", "When did you arrive?"], frequency: "core", level: "A2", tags: ["travel"], chapterSlug: "eng-ch3-around-town" }),
      w({ word: "depart", transcription: "/dɪˈpɑːt/", partOfSpeech: "verb", translation: "отправляться", examples: ["The bus departs at noon.", "What time do we depart?"], frequency: "common", level: "A2", tags: ["travel"], chapterSlug: "eng-ch3-around-town" }),
      w({ word: "miss", transcription: "/mɪs/", partOfSpeech: "verb", translation: "опоздать на (транспорт)", examples: ["I missed the train.", "Don't miss your flight."], frequency: "core", level: "A2", tags: ["travel"], chapterSlug: "eng-ch3-around-town" }),
      w({ word: "suitcase", transcription: "/ˈsuːtkeɪs/", partOfSpeech: "noun", translation: "чемодан", examples: ["Pack your suitcase.", "My suitcase is heavy."], frequency: "common", level: "A2", tags: ["travel"], chapterSlug: "eng-ch3-around-town" }),
      w({ word: "seaside", transcription: "/ˈsiːsaɪd/", partOfSpeech: "noun", translation: "море, побережье", examples: ["We went to the seaside.", "a seaside town"], frequency: "common", level: "A2", tags: ["travel"], chapterSlug: "eng-ch3-around-town" }),
      w({ word: "journey", transcription: "/ˈdʒɜːni/", partOfSpeech: "noun", translation: "поездка, путь", examples: ["Have a safe journey!", "The journey takes three hours."], frequency: "common", level: "A2", tags: ["travel"], chapterSlug: "eng-ch3-around-town", synonyms: ["trip"] }),
      w({ word: "timetable", transcription: "/ˈtaɪmteɪbl/", partOfSpeech: "noun", translation: "расписание", examples: ["Check the timetable.", "According to the timetable…"], frequency: "common", level: "A2", tags: ["travel"], chapterSlug: "eng-ch3-around-town", synonyms: ["schedule"] }),
    ],
  ),
  topic(
    {
      slug: "eng-b1-work-study",
      level: "B1",
      topic: "Работа и учёба",
      topicEs: "Work & study",
      topicEn: "Work & study",
      icon: "💼",
      chapterSlug: "eng-ch6-experiences",
    },
    [
      w({ word: "colleague", transcription: "/ˈkɒliːɡ/", partOfSpeech: "noun", translation: "коллега", examples: ["She's a great colleague.", "I asked my colleagues for help."], frequency: "common", level: "B1", tags: ["work"], chapterSlug: "eng-ch6-experiences" }),
      w({ word: "deadline", transcription: "/ˈdedlaɪn/", partOfSpeech: "noun", translation: "срок сдачи", examples: ["The deadline is Friday.", "We missed the deadline."], frequency: "common", level: "B1", tags: ["work"], chapterSlug: "eng-ch6-experiences" }),
      w({ word: "meeting", transcription: "/ˈmiːtɪŋ/", partOfSpeech: "noun", translation: "встреча, совещание", examples: ["I have a meeting at 10.", "The meeting was cancelled."], frequency: "core", level: "B1", tags: ["work"], chapterSlug: "eng-ch6-experiences" }),
      w({ word: "salary", transcription: "/ˈsæləri/", partOfSpeech: "noun", translation: "зарплата", examples: ["The salary is competitive.", "What's the starting salary?"], frequency: "common", level: "B1", tags: ["work"], chapterSlug: "eng-ch6-experiences" }),
      w({ word: "interview", transcription: "/ˈɪntəvjuː/", partOfSpeech: "noun", translation: "собеседование", examples: ["I have a job interview tomorrow.", "How did the interview go?"], frequency: "common", level: "B1", tags: ["work"], chapterSlug: "eng-ch6-experiences" }),
      w({ word: "experience", transcription: "/ɪkˈspɪəriəns/", partOfSpeech: "noun", translation: "опыт", examples: ["Do you have experience in marketing?", "She has five years' experience."], frequency: "core", level: "B1", tags: ["work"], chapterSlug: "eng-ch6-experiences" }),
      w({ word: "skill", transcription: "/skɪl/", partOfSpeech: "noun", translation: "навык", examples: ["Communication is a key skill.", "I'm improving my language skills."], frequency: "core", level: "B1", tags: ["work"], chapterSlug: "eng-ch6-experiences" }),
      w({ word: "apply", transcription: "/əˈplaɪ/", partOfSpeech: "verb", translation: "подавать заявку", examples: ["I'd like to apply for this job.", "She applied to three universities."], frequency: "core", level: "B1", tags: ["work"], chapterSlug: "eng-ch6-experiences" }),
      w({ word: "resign", transcription: "/rɪˈzaɪn/", partOfSpeech: "verb", translation: "увольняться", examples: ["He resigned last month.", "I'm thinking of resigning."], frequency: "common", level: "B1", tags: ["work"], chapterSlug: "eng-ch6-experiences" }),
      w({ word: "promote", transcription: "/prəˈməʊt/", partOfSpeech: "verb", translation: "повышать в должности", examples: ["She was promoted to manager.", "They promote from within."], frequency: "common", level: "B1", tags: ["work"], chapterSlug: "eng-ch6-experiences" }),
      w({ word: "exam", transcription: "/ɪɡˈzæm/", partOfSpeech: "noun", translation: "экзамен", examples: ["I have an exam on Monday.", "Good luck with your exams!"], frequency: "core", level: "B1", tags: ["study"], chapterSlug: "eng-ch6-experiences" }),
      w({ word: "assignment", transcription: "/əˈsaɪnmənt/", partOfSpeech: "noun", translation: "задание", examples: ["Submit the assignment by Friday.", "This assignment is difficult."], frequency: "common", level: "B1", tags: ["study"], chapterSlug: "eng-ch6-experiences" }),
      w({ word: "lecture", transcription: "/ˈlektʃə/", partOfSpeech: "noun", translation: "лекция", examples: ["The lecture starts at 9.", "I missed the lecture."], frequency: "common", level: "B1", tags: ["study"], chapterSlug: "eng-ch6-experiences" }),
      w({ word: "degree", transcription: "/dɪˈɡriː/", partOfSpeech: "noun", translation: "степень, диплом", examples: ["She has a degree in biology.", "I'm doing a master's degree."], frequency: "common", level: "B1", tags: ["study"], chapterSlug: "eng-ch6-experiences" }),
      w({ word: "research", transcription: "/rɪˈsɜːtʃ/", partOfSpeech: "noun", translation: "исследование", examples: ["My research focuses on climate.", "This is interesting research."], frequency: "common", level: "B1", tags: ["study"], chapterSlug: "eng-ch6-experiences" }),
      w({ word: "deadline", transcription: "/ˈdedlaɪn/", partOfSpeech: "noun", translation: "срок сдачи", examples: ["The deadline is Friday.", "We missed the deadline."], frequency: "common", level: "B1", tags: ["work"], chapterSlug: "eng-ch6-experiences" }),
      w({ word: "responsible", transcription: "/rɪˈspɒnsəbl/", partOfSpeech: "adjective", translation: "ответственный", examples: ["I'm responsible for the budget.", "Be responsible for your work."], frequency: "core", level: "B1", tags: ["work"], chapterSlug: "eng-ch6-experiences" }),
      w({ word: "efficient", transcription: "/ɪˈfɪʃnt/", partOfSpeech: "adjective", translation: "эффективный", examples: ["We need a more efficient process.", "She's very efficient."], frequency: "common", level: "B1", tags: ["work"], chapterSlug: "eng-ch6-experiences" }),
      w({ word: "shift", transcription: "/ʃɪft/", partOfSpeech: "noun", translation: "смена", examples: ["I work the night shift.", "Who's on the early shift?"], frequency: "common", level: "B1", tags: ["work"], chapterSlug: "eng-ch6-experiences" }),
      w({ word: "overtime", transcription: "/ˈəʊvətaɪm/", partOfSpeech: "noun", translation: "сверхурочные", examples: ["I did three hours of overtime.", "Overtime is paid double."], frequency: "common", level: "B1", tags: ["work"], chapterSlug: "eng-ch6-experiences" }),
      w({ word: "internship", transcription: "/ˈɪntɜːnʃɪp/", partOfSpeech: "noun", translation: "стажировка", examples: ["I did an internship in Madrid.", "Apply for a summer internship."], frequency: "common", level: "B1", tags: ["work"], chapterSlug: "eng-ch6-experiences" }),
      w({ word: "curriculum", transcription: "/kəˈrɪkjələm/", partOfSpeech: "noun", translation: "учебная программа", examples: ["The curriculum includes writing.", "They updated the curriculum."], frequency: "common", level: "B1", tags: ["study"], chapterSlug: "eng-ch6-experiences" }),
    ],
  ),
  topic(
    {
      slug: "eng-b1-health-lifestyle",
      level: "B1",
      topic: "Здоровье и образ жизни",
      topicEs: "Health & lifestyle",
      topicEn: "Health & lifestyle",
      icon: "💪",
      chapterSlug: "eng-ch7-future-plans",
    },
    [
      w({ word: "healthy", transcription: "/ˈhelθi/", partOfSpeech: "adjective", translation: "здоровый", examples: ["Eat a healthy diet.", "She's very healthy."], frequency: "core", level: "B1", tags: ["health"], chapterSlug: "eng-ch7-future-plans" }),
      w({ word: "exercise", transcription: "/ˈeksəsaɪz/", partOfSpeech: "noun", translation: "физическая нагрузка", examples: ["Exercise helps reduce stress.", "I do exercise three times a week."], frequency: "core", level: "B1", tags: ["health"], chapterSlug: "eng-ch7-future-plans" }),
      w({ word: "gym", transcription: "/dʒɪm/", partOfSpeech: "noun", translation: "спортзал", examples: ["I go to the gym after work.", "Is the gym open on Sundays?"], frequency: "core", level: "B1", tags: ["health"], chapterSlug: "eng-ch7-future-plans" }),
      w({ word: "diet", transcription: "/ˈdaɪət/", partOfSpeech: "noun", translation: "рацион, диета", examples: ["I'm on a healthy diet.", "Cut sugar from your diet."], frequency: "common", level: "B1", tags: ["health"], chapterSlug: "eng-ch7-future-plans" }),
      w({ word: "stress", transcription: "/stres/", partOfSpeech: "noun", translation: "стресс", examples: ["Work causes a lot of stress.", "Try to manage stress."], frequency: "core", level: "B1", tags: ["health"], chapterSlug: "eng-ch7-future-plans" }),
      w({ word: "sleep", transcription: "/sliːp/", partOfSpeech: "noun", translation: "сон", examples: ["I need more sleep.", "Sleep is essential."], frequency: "core", level: "B1", tags: ["health"], chapterSlug: "eng-ch7-future-plans" }),
      w({ word: "illness", transcription: "/ˈɪlnəs/", partOfSpeech: "noun", translation: "болезнь", examples: ["She missed work due to illness.", "a serious illness"], frequency: "common", level: "B1", tags: ["health"], chapterSlug: "eng-ch7-future-plans" }),
      w({ word: "symptom", transcription: "/ˈsɪmptəm/", partOfSpeech: "noun", translation: "симптом", examples: ["What are your symptoms?", "Fever is a common symptom."], frequency: "common", level: "B1", tags: ["health"], chapterSlug: "eng-ch7-future-plans" }),
      w({ word: "appointment", transcription: "/əˈpɔɪntmənt/", partOfSpeech: "noun", translation: "приём (у врача)", examples: ["I have a doctor's appointment.", "Book an appointment online."], frequency: "common", level: "B1", tags: ["health"], chapterSlug: "eng-ch7-future-plans" }),
      w({ word: "medicine", transcription: "/ˈmedsn/", partOfSpeech: "noun", translation: "лекарство", examples: ["Take this medicine twice a day.", "Do you need any medicine?"], frequency: "core", level: "B1", tags: ["health"], chapterSlug: "eng-ch7-future-plans" }),
      w({ word: "recover", transcription: "/rɪˈkʌvə/", partOfSpeech: "verb", translation: "выздоравливать", examples: ["He's recovering well.", "It took weeks to recover."], frequency: "common", level: "B1", tags: ["health"], chapterSlug: "eng-ch7-future-plans" }),
      w({ word: "injury", transcription: "/ˈɪndʒəri/", partOfSpeech: "noun", translation: "травма", examples: ["He has a knee injury.", "a sports injury"], frequency: "common", level: "B1", tags: ["health"], chapterSlug: "eng-ch7-future-plans" }),
      w({ word: "energy", transcription: "/ˈenədʒi/", partOfSpeech: "noun", translation: "энергия", examples: ["I have no energy today.", "Exercise gives you energy."], frequency: "core", level: "B1", tags: ["health"], chapterSlug: "eng-ch7-future-plans" }),
      w({ word: "habit", transcription: "/ˈhæbɪt/", partOfSpeech: "noun", translation: "привычка", examples: ["Smoking is a bad habit.", "Build better habits."], frequency: "common", level: "B1", tags: ["health"], chapterSlug: "eng-ch7-future-plans" }),
      w({ word: "balance", transcription: "/ˈbæləns/", partOfSpeech: "noun", translation: "баланс", examples: ["Find a work-life balance.", "Eat a balanced diet."], frequency: "common", level: "B1", tags: ["health"], chapterSlug: "eng-ch7-future-plans" }),
      w({ word: "mental health", transcription: "/ˌmentl ˈhelθ/", partOfSpeech: "noun", translation: "ментальное здоровье", examples: ["Mental health matters.", "Talk about mental health openly."], frequency: "common", level: "B1", tags: ["health"], chapterSlug: "eng-ch7-future-plans" }),
      w({ word: "relax", transcription: "/rɪˈlæks/", partOfSpeech: "verb", translation: "расслабляться", examples: ["I relax by reading.", "Try to relax before the exam."], frequency: "core", level: "B1", tags: ["health"], chapterSlug: "eng-ch7-future-plans" }),
      w({ word: "fit", transcription: "/fɪt/", partOfSpeech: "adjective", translation: "в форме", examples: ["He looks fit.", "Stay fit as you age."], frequency: "common", level: "B1", tags: ["health"], chapterSlug: "eng-ch7-future-plans" }),
      w({ word: "overweight", transcription: "/ˌəʊvəˈweɪt/", partOfSpeech: "adjective", translation: "с избыточным весом", examples: ["Being overweight increases risk.", "a slightly overweight patient"], frequency: "common", level: "B1", tags: ["health"], chapterSlug: "eng-ch7-future-plans" }),
      w({ word: "vaccine", transcription: "/ˈvæksiːn/", partOfSpeech: "noun", translation: "вакцина", examples: ["Have you had the vaccine?", "Vaccines save lives."], frequency: "common", level: "B1", tags: ["health"], chapterSlug: "eng-ch7-future-plans" }),
      w({ word: "prevention", transcription: "/prɪˈvenʃn/", partOfSpeech: "noun", translation: "профилактика", examples: ["Prevention is better than cure.", "disease prevention"], frequency: "common", level: "B1", tags: ["health"], chapterSlug: "eng-ch7-future-plans" }),
      w({ word: "wellbeing", transcription: "/ˌwelˈbiːɪŋ/", partOfSpeech: "noun", translation: "благополучие", examples: ["employee wellbeing", "Focus on your wellbeing."], frequency: "common", level: "B1", tags: ["health"], chapterSlug: "eng-ch7-future-plans" }),
    ],
  ),
  topic(
    {
      slug: "eng-b2-media-opinions",
      level: "B2",
      topic: "Медиа и мнения",
      topicEs: "Media & opinions",
      topicEn: "Media & opinions",
      icon: "📰",
      chapterSlug: "eng-ch9-real-world",
    },
    [
      w({ word: "headline", transcription: "/ˈhedlaɪn/", partOfSpeech: "noun", translation: "заголовок", examples: ["The headline was misleading.", "I only read the headlines."], frequency: "common", level: "B2", tags: ["media"], chapterSlug: "eng-ch9-real-world" }),
      w({ word: "source", transcription: "/sɔːs/", partOfSpeech: "noun", translation: "источник", examples: ["Check your sources.", "an reliable source"], frequency: "core", level: "B2", tags: ["media"], chapterSlug: "eng-ch9-real-world" }),
      w({ word: "bias", transcription: "/ˈbaɪəs/", partOfSpeech: "noun", translation: "предвзятость", examples: ["The report shows bias.", "media bias"], frequency: "common", level: "B2", tags: ["media"], chapterSlug: "eng-ch9-real-world" }),
      w({ word: "claim", transcription: "/kleɪm/", partOfSpeech: "verb", translation: "утверждать", examples: ["They claim the product works.", "He claimed he was innocent."], frequency: "core", level: "B2", tags: ["opinions"], chapterSlug: "eng-ch9-real-world" }),
      w({ word: "evidence", transcription: "/ˈevɪdəns/", partOfSpeech: "noun", translation: "доказательства", examples: ["Where is the evidence?", "scientific evidence"], frequency: "core", level: "B2", tags: ["opinions"], chapterSlug: "eng-ch9-real-world" }),
      w({ word: "debate", transcription: "/dɪˈbeɪt/", partOfSpeech: "noun", translation: "дебаты", examples: ["There is an ongoing debate.", "a public debate"], frequency: "common", level: "B2", tags: ["opinions"], chapterSlug: "eng-ch9-real-world" }),
      w({ word: "persuade", transcription: "/pəˈsweɪd/", partOfSpeech: "verb", translation: "убеждать", examples: ["She persuaded me to stay.", "It's hard to persuade him."], frequency: "common", level: "B2", tags: ["opinions"], chapterSlug: "eng-ch9-real-world" }),
      w({ word: "influence", transcription: "/ˈɪnfluəns/", partOfSpeech: "noun", translation: "влияние", examples: ["Social media has huge influence.", "under the influence of peers"], frequency: "core", level: "B2", tags: ["media"], chapterSlug: "eng-ch9-real-world" }),
      w({ word: "audience", transcription: "/ˈɔːdiəns/", partOfSpeech: "noun", translation: "аудитория", examples: ["The audience loved the show.", "target audience"], frequency: "common", level: "B2", tags: ["media"], chapterSlug: "eng-ch9-real-world" }),
      w({ word: "viral", transcription: "/ˈvaɪrəl/", partOfSpeech: "adjective", translation: "вирусный (о контенте)", examples: ["The video went viral.", "a viral campaign"], frequency: "common", level: "B2", tags: ["media"], chapterSlug: "eng-ch9-real-world" }),
      w({ word: "perspective", transcription: "/pəˈspektɪv/", partOfSpeech: "noun", translation: "точка зрения", examples: ["From my perspective…", "a different perspective"], frequency: "common", level: "B2", tags: ["opinions"], chapterSlug: "eng-ch9-real-world", synonyms: ["point of view"] }),
      w({ word: "objective", transcription: "/əbˈdʒektɪv/", partOfSpeech: "adjective", translation: "объективный", examples: ["Try to be objective.", "an objective report"], frequency: "common", level: "B2", tags: ["opinions"], chapterSlug: "eng-ch9-real-world" }),
      w({ word: "subjective", transcription: "/səbˈdʒektɪv/", partOfSpeech: "adjective", translation: "субъективный", examples: ["Taste is subjective.", "a subjective opinion"], frequency: "common", level: "B2", tags: ["opinions"], chapterSlug: "eng-ch9-real-world" }),
      w({ word: "controversial", transcription: "/ˌkɒntrəˈvɜːʃl/", partOfSpeech: "adjective", translation: "спорный", examples: ["a controversial decision", "The topic is controversial."], frequency: "common", level: "B2", tags: ["opinions"], chapterSlug: "eng-ch9-real-world" }),
      w({ word: "reliable", transcription: "/rɪˈlaɪəbl/", partOfSpeech: "adjective", translation: "надёжный", examples: ["Is this source reliable?", "a reliable newspaper"], frequency: "core", level: "B2", tags: ["media"], chapterSlug: "eng-ch9-real-world" }),
      w({ word: "broadcast", transcription: "/ˈbrɔːdkɑːst/", partOfSpeech: "verb", translation: "транслировать", examples: ["The match was broadcast live.", "They broadcast news 24/7."], frequency: "common", level: "B2", tags: ["media"], chapterSlug: "eng-ch9-real-world" }),
      w({ word: "journalist", transcription: "/ˈdʒɜːnəlɪst/", partOfSpeech: "noun", translation: "журналист", examples: ["She's a freelance journalist.", "Investigative journalists…"], frequency: "common", level: "B2", tags: ["media"], chapterSlug: "eng-ch9-real-world" }),
      w({ word: "edit", transcription: "/ˈedɪt/", partOfSpeech: "verb", translation: "редактировать", examples: ["Edit your essay carefully.", "The video was heavily edited."], frequency: "common", level: "B2", tags: ["media"], chapterSlug: "eng-ch9-real-world" }),
      w({ word: "publish", transcription: "/ˈpʌblɪʃ/", partOfSpeech: "verb", translation: "публиковать", examples: ["They published the results.", "Don't publish private data."], frequency: "common", level: "B2", tags: ["media"], chapterSlug: "eng-ch9-real-world" }),
      w({ word: "argument", transcription: "/ˈɑːɡjumənt/", partOfSpeech: "noun", translation: "аргумент; спор", examples: ["That's a strong argument.", "They had an argument."], frequency: "core", level: "B2", tags: ["opinions"], chapterSlug: "eng-ch9-real-world" }),
      w({ word: "conclude", transcription: "/kənˈkluːd/", partOfSpeech: "verb", translation: "делать вывод", examples: ["We can conclude that…", "The study concludes…"], frequency: "common", level: "B2", tags: ["opinions"], chapterSlug: "eng-ch9-real-world" }),
      w({ word: "emphasise", transcription: "/ˈemfəsaɪz/", partOfSpeech: "verb", translation: "подчёркивать", examples: ["I want to emphasise this point.", "The report emphasises safety."], frequency: "common", level: "B2", tags: ["opinions"], chapterSlug: "eng-ch9-real-world", synonyms: ["emphasize (US)"] }),
    ],
  ),
  topic(
    {
      slug: "eng-b2-environment-tech",
      level: "B2",
      topic: "Экология и технологии",
      topicEs: "Environment & technology",
      topicEn: "Environment & technology",
      icon: "🌍",
      chapterSlug: "eng-ch10-what-if",
    },
    [
      w({ word: "climate", transcription: "/ˈklaɪmət/", partOfSpeech: "noun", translation: "климат", examples: ["climate change", "a mild climate"], frequency: "core", level: "B2", tags: ["environment"], chapterSlug: "eng-ch10-what-if" }),
      w({ word: "pollution", transcription: "/pəˈluːʃn/", partOfSpeech: "noun", translation: "загрязнение", examples: ["Air pollution is high.", "reduce pollution"], frequency: "core", level: "B2", tags: ["environment"], chapterSlug: "eng-ch10-what-if" }),
      w({ word: "recycle", transcription: "/ˌriːˈsaɪkl/", partOfSpeech: "verb", translation: "перерабатывать", examples: ["We recycle plastic.", "Recycle your bottles."], frequency: "common", level: "B2", tags: ["environment"], chapterSlug: "eng-ch10-what-if" }),
      w({ word: "sustainable", transcription: "/səˈsteɪnəbl/", partOfSpeech: "adjective", translation: "устойчивый (эко)", examples: ["sustainable energy", "a sustainable lifestyle"], frequency: "common", level: "B2", tags: ["environment"], chapterSlug: "eng-ch10-what-if" }),
      w({ word: "renewable", transcription: "/rɪˈnjuːəbl/", partOfSpeech: "adjective", translation: "возобновляемый", examples: ["renewable energy", "Renewable sources…"], frequency: "common", level: "B2", tags: ["environment"], chapterSlug: "eng-ch10-what-if" }),
      w({ word: "emission", transcription: "/ɪˈmɪʃn/", partOfSpeech: "noun", translation: "выброс", examples: ["carbon emissions", "cut emissions"], frequency: "common", level: "B2", tags: ["environment"], chapterSlug: "eng-ch10-what-if" }),
      w({ word: "device", transcription: "/dɪˈvaɪs/", partOfSpeech: "noun", translation: "устройство", examples: ["a mobile device", "Turn off unused devices."], frequency: "core", level: "B2", tags: ["tech"], chapterSlug: "eng-ch10-what-if" }),
      w({ word: "software", transcription: "/ˈsɒftweə/", partOfSpeech: "noun", translation: "ПО", examples: ["Update your software.", "software engineer"], frequency: "core", level: "B2", tags: ["tech"], chapterSlug: "eng-ch10-what-if" }),
      w({ word: "artificial intelligence", transcription: "/ˌɑːtɪˈfɪʃl ɪnˈtelɪdʒəns/", partOfSpeech: "noun", translation: "ИИ", examples: ["AI is changing education.", "artificial intelligence tools"], frequency: "common", level: "B2", tags: ["tech"], chapterSlug: "eng-ch10-what-if", synonyms: ["AI"] }),
      w({ word: "data", transcription: "/ˈdeɪtə/", partOfSpeech: "noun", translation: "данные", examples: ["Protect your data.", "data analysis"], frequency: "core", level: "B2", tags: ["tech"], chapterSlug: "eng-ch10-what-if" }),
      w({ word: "privacy", transcription: "/ˈprɪvəsi/", partOfSpeech: "noun", translation: "конфиденциальность", examples: ["online privacy", "Privacy settings…"], frequency: "common", level: "B2", tags: ["tech"], chapterSlug: "eng-ch10-what-if" }),
      w({ word: "innovative", transcription: "/ˈɪnəveɪtɪv/", partOfSpeech: "adjective", translation: "инновационный", examples: ["an innovative solution", "innovative design"], frequency: "common", level: "B2", tags: ["tech"], chapterSlug: "eng-ch10-what-if" }),
      w({ word: "automate", transcription: "/ˈɔːtəmeɪt/", partOfSpeech: "verb", translation: "автоматизировать", examples: ["We automated the tests.", "Automate routine tasks."], frequency: "common", level: "B2", tags: ["tech"], chapterSlug: "eng-ch10-what-if" }),
      w({ word: "impact", transcription: "/ˈɪmpækt/", partOfSpeech: "noun", translation: "влияние, эффект", examples: ["the impact of tourism", "a positive impact"], frequency: "core", level: "B2", tags: ["environment"], chapterSlug: "eng-ch10-what-if" }),
      w({ word: "wildlife", transcription: "/ˈwaɪldlaɪf/", partOfSpeech: "noun", translation: "живая природа", examples: ["protect wildlife", "local wildlife"], frequency: "common", level: "B2", tags: ["environment"], chapterSlug: "eng-ch10-what-if" }),
      w({ word: "waste", transcription: "/weɪst/", partOfSpeech: "noun", translation: "отходы", examples: ["Reduce waste.", "plastic waste"], frequency: "common", level: "B2", tags: ["environment"], chapterSlug: "eng-ch10-what-if" }),
      w({ word: "charge", transcription: "/tʃɑːdʒ/", partOfSpeech: "verb", translation: "заряжать", examples: ["Charge your phone.", "The battery is charging."], frequency: "core", level: "B2", tags: ["tech"], chapterSlug: "eng-ch10-what-if" }),
      w({ word: "upload", transcription: "/ˌʌpˈləʊd/", partOfSpeech: "verb", translation: "загружать (на сервер)", examples: ["Upload the file.", "I uploaded the photos."], frequency: "common", level: "B2", tags: ["tech"], chapterSlug: "eng-ch10-what-if" }),
      w({ word: "download", transcription: "/ˌdaʊnˈləʊd/", partOfSpeech: "verb", translation: "скачивать", examples: ["Download the app.", "Don't download unknown files."], frequency: "common", level: "B2", tags: ["tech"], chapterSlug: "eng-ch10-what-if" }),
      w({ word: "network", transcription: "/ˈnetwɜːk/", partOfSpeech: "noun", translation: "сеть", examples: ["a wireless network", "social network"], frequency: "core", level: "B2", tags: ["tech"], chapterSlug: "eng-ch10-what-if" }),
      w({ word: "efficiency", transcription: "/ɪˈfɪʃnsi/", partOfSpeech: "noun", translation: "эффективность", examples: ["energy efficiency", "improve efficiency"], frequency: "common", level: "B2", tags: ["environment"], chapterSlug: "eng-ch10-what-if" }),
      w({ word: "crisis", transcription: "/ˈkraɪsɪs/", partOfSpeech: "noun", translation: "кризис", examples: ["a climate crisis", "in times of crisis"], frequency: "common", level: "B2", tags: ["environment"], chapterSlug: "eng-ch10-what-if" }),
    ],
  ),
  topic(
    {
      slug: "eng-c1-academic-writing-lexis",
      level: "C1",
      topic: "Академическая лексика для письма",
      topicEs: "Academic writing lexis",
      topicEn: "Academic writing lexis",
      icon: "✍️",
      chapterSlug: "eng-ch16-ielts",
    },
    [
      w({ word: "significant", transcription: "/sɪɡˈnɪfɪkənt/", partOfSpeech: "adjective", translation: "значительный", examples: ["a significant increase", "The difference is significant."], frequency: "core", level: "C1", tags: ["academic"], chapterSlug: "eng-ch16-ielts" }),
      w({ word: "substantial", transcription: "/səbˈstænʃl/", partOfSpeech: "adjective", translation: "существенный", examples: ["a substantial amount", "substantial evidence"], frequency: "common", level: "C1", tags: ["academic"], chapterSlug: "eng-ch16-ielts" }),
      w({ word: "whereas", transcription: "/weərˈæz/", partOfSpeech: "conjunction", translation: "тогда как", examples: ["Oil prices rose, whereas gas fell.", "She is quiet, whereas he is loud."], frequency: "common", level: "C1", tags: ["academic"], chapterSlug: "eng-ch16-ielts" }),
      w({ word: "nevertheless", transcription: "/ˌnevəðəˈles/", partOfSpeech: "adverb", translation: "тем не менее", examples: ["It was hard; nevertheless, we finished.", "Nevertheless, progress was made."], frequency: "common", level: "C1", tags: ["academic"], chapterSlug: "eng-ch16-ielts" }),
      w({ word: "furthermore", transcription: "/ˌfɜːðəˈmɔː/", partOfSpeech: "adverb", translation: "более того", examples: ["Furthermore, costs are rising.", "The plan is cheap; furthermore, it is quick."], frequency: "common", level: "C1", tags: ["academic"], chapterSlug: "eng-ch16-ielts" }),
      w({ word: "implication", transcription: "/ˌɪmplɪˈkeɪʃn/", partOfSpeech: "noun", translation: "следствие, намёк", examples: ["the implications of the study", "political implications"], frequency: "common", level: "C1", tags: ["academic"], chapterSlug: "eng-ch16-ielts" }),
      w({ word: "assess", transcription: "/əˈses/", partOfSpeech: "verb", translation: "оценивать", examples: ["Assess the risks carefully.", "Teachers assess writing."], frequency: "common", level: "C1", tags: ["academic"], chapterSlug: "eng-ch16-ielts" }),
      w({ word: "demonstrate", transcription: "/ˈdemənstreɪt/", partOfSpeech: "verb", translation: "демонстрировать", examples: ["The data demonstrate a trend.", "Demonstrate your skills."], frequency: "common", level: "C1", tags: ["academic"], chapterSlug: "eng-ch16-ielts" }),
      w({ word: "indicate", transcription: "/ˈɪndɪkeɪt/", partOfSpeech: "verb", translation: "указывать", examples: ["Results indicate improvement.", "This indicates a problem."], frequency: "common", level: "C1", tags: ["academic"], chapterSlug: "eng-ch16-ielts" }),
      w({ word: "contribute", transcription: "/kənˈtrɪbjuːt/", partOfSpeech: "verb", translation: "вносить вклад", examples: ["Many factors contribute to success.", "She contributed to the article."], frequency: "common", level: "C1", tags: ["academic"], chapterSlug: "eng-ch16-ielts" }),
      w({ word: "consequence", transcription: "/ˈkɒnsɪkwəns/", partOfSpeech: "noun", translation: "последствие", examples: ["as a consequence", "negative consequences"], frequency: "common", level: "C1", tags: ["academic"], chapterSlug: "eng-ch16-ielts" }),
      w({ word: "approach", transcription: "/əˈprəʊtʃ/", partOfSpeech: "noun", translation: "подход", examples: ["a practical approach", "a new approach to teaching"], frequency: "core", level: "C1", tags: ["academic"], chapterSlug: "eng-ch16-ielts" }),
      w({ word: "factor", transcription: "/ˈfæktə/", partOfSpeech: "noun", translation: "фактор", examples: ["key factors", "an important factor"], frequency: "core", level: "C1", tags: ["academic"], chapterSlug: "eng-ch16-ielts" }),
      w({ word: "phenomenon", transcription: "/fəˈnɒmɪnən/", partOfSpeech: "noun", translation: "явление", examples: ["a social phenomenon", "This phenomenon is increasing."], frequency: "common", level: "C1", tags: ["academic"], chapterSlug: "eng-ch16-ielts", commonMistakes: ["Мн.ч. phenomena."] }),
      w({ word: "hypothesis", transcription: "/haɪˈpɒθəsɪs/", partOfSpeech: "noun", translation: "гипотеза", examples: ["test a hypothesis", "The hypothesis was rejected."], frequency: "common", level: "C1", tags: ["academic"], chapterSlug: "eng-ch16-ielts" }),
      w({ word: "methodology", transcription: "/ˌmeθəˈdɒlədʒi/", partOfSpeech: "noun", translation: "методология", examples: ["research methodology", "The methodology is described below."], frequency: "common", level: "C1", tags: ["academic"], chapterSlug: "eng-ch16-ielts" }),
      w({ word: "estimate", transcription: "/ˈestɪmət/", partOfSpeech: "verb", translation: "оценивать (примерно)", examples: ["Experts estimate the cost at…", "It is estimated that…"], frequency: "common", level: "C1", tags: ["academic"], chapterSlug: "eng-ch16-ielts" }),
      w({ word: "fluctuate", transcription: "/ˈflʌktʃueɪt/", partOfSpeech: "verb", translation: "колебаться", examples: ["Prices fluctuate daily.", "The figures fluctuated."], frequency: "common", level: "C1", tags: ["academic"], chapterSlug: "eng-ch16-ielts" }),
      w({ word: "proportion", transcription: "/prəˈpɔːʃn/", partOfSpeech: "noun", translation: "доля, пропорция", examples: ["a large proportion of students", "in proportion to"], frequency: "common", level: "C1", tags: ["academic"], chapterSlug: "eng-ch16-ielts" }),
      w({ word: "trend", transcription: "/trend/", partOfSpeech: "noun", translation: "тенденция", examples: ["an upward trend", "follow the trend"], frequency: "core", level: "C1", tags: ["academic"], chapterSlug: "eng-ch16-ielts" }),
      w({ word: "illustrate", transcription: "/ˈɪləstreɪt/", partOfSpeech: "verb", translation: "иллюстрировать", examples: ["This example illustrates the point.", "The chart illustrates…"], frequency: "common", level: "C1", tags: ["academic"], chapterSlug: "eng-ch16-ielts" }),
      w({ word: "respectively", transcription: "/rɪˈspektɪvli/", partOfSpeech: "adverb", translation: "соответственно", examples: ["A and B scored 10 and 12 respectively.", "…in France and Spain respectively."], frequency: "common", level: "C1", tags: ["academic"], chapterSlug: "eng-ch16-ielts" }),
    ],
  ),
];
