import { w, topic } from "./helpers";
import type { VocabTopic } from "@/types";

const CH7 = "eng-ch7-future-plans";
const CH8 = "eng-ch8-storytelling";
const CH9 = "eng-ch9-real-world";
const CH10 = "eng-ch10-what-if";
const CH11 = "eng-ch11-passive";
const CH12 = "eng-ch12-beyond-borders";
const CH13 = "eng-ch13-advanced-structures";
const CH14 = "eng-ch14-art-language";
const CH15 = "eng-ch15-mastery";
const CH16 = "eng-ch16-ielts";

export const ENGLISH_VOCAB_B1_C2: VocabTopic[] = [
  topic(
    {
      slug: "eng-b1-personality",
      level: "B1",
      topic: "Характер и решения",
      topicEs: "Personality & Decisions",
      icon: "💭",
      chapterSlug: CH7,
    },
    [
      w({
        word: "decisive",
        transcription: "/dɪˈsaɪsɪv/",
        partOfSpeech: "adjective",
        translation: "решительный",
        examples: [
          "She is decisive when choosing a career path.",
          "A decisive leader helps the team move forward quickly.",
        ],
        commonMistakes: [
          "Do not confuse with 'decision' (noun) — use 'decisive' for people or actions.",
          "Avoid 'very decisive' in formal writing; prefer 'highly decisive'.",
        ],
        synonyms: ["determined", "resolute"],
        frequency: "common",
        level: "B1",
        tags: ["personality", "decisions", "character"],
        chapterSlug: CH7,
      }),
      w({
        word: "indecisive",
        transcription: "/ˌɪndɪˈsaɪsɪv/",
        partOfSpeech: "adjective",
        translation: "нерешительный",
        examples: [
          "He felt indecisive about accepting the job offer.",
          "Indecisive shoppers often leave the store empty-handed.",
        ],
        commonMistakes: [
          "Use 'indecisive about + noun/gerund', not 'indecisive for'.",
        ],
        synonyms: ["hesitant", "uncertain"],
        frequency: "common",
        level: "B1",
        tags: ["personality", "decisions"],
        chapterSlug: CH7,
      }),
      w({
        word: "conscientious",
        transcription: "/ˌkɒnʃiˈenʃəs/",
        partOfSpeech: "adjective",
        translation: "добросовестный, ответственный",
        examples: [
          "Conscientious students always meet their deadlines.",
          "She is a conscientious worker who checks every detail.",
        ],
        commonMistakes: [
          "Pronunciation stress is on 'en', not 'sci'.",
          "Do not spell it 'conscious' — that means 'aware'.",
        ],
        synonyms: ["diligent", "meticulous"],
        frequency: "common",
        level: "B1",
        tags: ["personality", "work ethic"],
        chapterSlug: CH7,
      }),
      w({
        word: "impulsive",
        transcription: "/ɪmˈpʌlsɪv/",
        partOfSpeech: "adjective",
        translation: "импульсивный",
        examples: [
          "Impulsive decisions can lead to regret later.",
          "He made an impulsive purchase online at midnight.",
        ],
        commonMistakes: [
          "Use 'impulsive' for people/actions, 'on impulse' for adverbial use.",
        ],
        synonyms: ["spontaneous", "hasty"],
        frequency: "common",
        level: "B1",
        tags: ["personality", "decisions"],
        chapterSlug: CH7,
      }),
      w({
        word: "deliberate",
        transcription: "/dɪˈlɪbərət/",
        partOfSpeech: "adjective",
        translation: "обдуманный, намеренный",
        examples: [
          "Making a deliberate choice takes time and reflection.",
          "It was a deliberate decision to move to Dublin.",
        ],
        commonMistakes: [
          "As a verb /dɪˈlɪbəreɪt/ means 'to discuss carefully' — stress changes meaning.",
        ],
        synonyms: ["intentional", "calculated"],
        frequency: "common",
        level: "B1",
        tags: ["decisions", "planning"],
        chapterSlug: CH7,
      }),
      w({
        word: "prioritize",
        transcription: "/praɪˈɒrətaɪz/",
        partOfSpeech: "verb",
        translation: "расставлять приоритеты",
        examples: [
          "You should prioritize your health over extra work.",
          "We need to prioritize saving money for the trip.",
        ],
        commonMistakes: [
          "British spelling: 'prioritise'; American: 'prioritize'.",
          "Use 'prioritize + noun/gerund', not 'prioritize to + verb'.",
        ],
        synonyms: ["rank", "focus on"],
        frequency: "common",
        level: "B1",
        tags: ["planning", "decisions"],
        chapterSlug: CH7,
      }),
      w({
        word: "commitment",
        transcription: "/kəˈmɪtmənt/",
        partOfSpeech: "noun",
        translation: "обязательство, приверженность",
        examples: [
          "Learning English requires long-term commitment.",
          "She showed full commitment to the project.",
        ],
        commonMistakes: [
          "Use 'commitment to + noun/gerund', not 'commitment for'.",
        ],
        synonyms: ["dedication", "obligation"],
        frequency: "core",
        level: "B1",
        tags: ["decisions", "responsibility"],
        chapterSlug: CH7,
      }),
      w({
        word: "hesitate",
        transcription: "/ˈhezɪteɪt/",
        partOfSpeech: "verb",
        translation: "колебаться, сомневаться",
        examples: [
          "Don't hesitate to ask for help with your future plans.",
          "He hesitated before signing the contract.",
        ],
        commonMistakes: [
          "Use 'hesitate to + infinitive' or 'hesitate about + gerund'.",
        ],
        synonyms: ["pause", "waver"],
        frequency: "common",
        level: "B1",
        tags: ["decisions", "uncertainty"],
        chapterSlug: CH7,
      }),
      w({
        word: "reckon",
        transcription: "/ˈrekən/",
        partOfSpeech: "verb",
        translation: "полагать, считать (разг.)",
        examples: [
          "I reckon we should leave early tomorrow.",
          "What do you reckon about studying abroad?",
        ],
        commonMistakes: [
          "Informal in British English; use 'think' or 'believe' in formal IELTS writing.",
        ],
        synonyms: ["suppose", "think"],
        frequency: "common",
        level: "B1",
        tags: ["opinion", "decisions"],
        chapterSlug: CH7,
      }),
      w({
        word: "weigh up",
        transcription: "/weɪ ʌp/",
        partOfSpeech: "phrase",
        translation: "взвешивать (варианты), обдумывать",
        examples: [
          "She weighed up the pros and cons before moving.",
          "You need to weigh up all your options carefully.",
        ],
        commonMistakes: [
          "Separable phrasal verb: 'weigh the options up' is also correct.",
        ],
        synonyms: ["consider", "evaluate"],
        frequency: "common",
        level: "B1",
        tags: ["decisions", "phrasal verb"],
        chapterSlug: CH7,
      }),
      w({
        word: "resolution",
        transcription: "/ˌrezəˈluːʃən/",
        partOfSpeech: "noun",
        translation: "решимость; решение (New Year's ~)",
        examples: [
          "Her New Year's resolution was to study every day.",
          "It took great resolution to finish the marathon.",
        ],
        commonMistakes: [
          "Do not confuse with 'solution' (answer to a problem).",
        ],
        synonyms: ["determination", "decision"],
        frequency: "common",
        level: "B1",
        tags: ["goals", "decisions"],
        chapterSlug: CH7,
      }),
      w({
        word: "tentative",
        transcription: "/ˈtentətɪv/",
        partOfSpeech: "adjective",
        translation: "предварительный, неокончательный",
        examples: [
          "We made a tentative plan to visit Dublin next spring.",
          "She gave a tentative answer until she had more information.",
        ],
        commonMistakes: [
          "Use 'tentative' for plans/answers, not people (except 'tentative smile').",
        ],
        synonyms: ["provisional", "uncertain"],
        frequency: "uncommon",
        level: "B1",
        tags: ["planning", "uncertainty"],
        chapterSlug: CH7,
      }),
    ],
  ),

  topic(
    {
      slug: "eng-b1-feelings",
      level: "B1",
      topic: "Чувства и эмоции",
      topicEs: "Feelings & Emotions",
      icon: "😊",
      chapterSlug: CH8,
    },
    [
      w({
        word: "overwhelmed",
        transcription: "/ˌəʊvəˈwelmd/",
        partOfSpeech: "adjective",
        translation: "перегруженный, подавленный (эмоциями)",
        examples: [
          "She felt overwhelmed by all the exam preparation.",
          "The storyteller was overwhelmed with emotion on stage.",
        ],
        commonMistakes: [
          "Use 'overwhelmed by/with', not 'overwhelmed from'.",
        ],
        synonyms: ["swamped", "stressed"],
        frequency: "common",
        level: "B1",
        tags: ["emotions", "storytelling"],
        chapterSlug: CH8,
      }),
      w({
        word: "nostalgic",
        transcription: "/nɒˈstældʒɪk/",
        partOfSpeech: "adjective",
        translation: "тоскующий по прошлому, ностальгический",
        examples: [
          "Listening to old songs made him feel nostalgic.",
          "The photo album left her nostalgic for childhood summers.",
        ],
        commonMistakes: [
          "Use 'nostalgic about/for', not 'nostalgic of'.",
        ],
        synonyms: ["sentimental", "wistful"],
        frequency: "common",
        level: "B1",
        tags: ["emotions", "past"],
        chapterSlug: CH8,
      }),
      w({
        word: "bittersweet",
        transcription: "/ˌbɪtəˈswiːt/",
        partOfSpeech: "adjective",
        translation: "горько-сладкий (о чувствах)",
        examples: [
          "Graduation day was a bittersweet moment for the class.",
          "The film had a bittersweet ending that stayed with me.",
        ],
        commonMistakes: [
          "Usually one word; 'bitter sweet' as two words is incorrect.",
        ],
        synonyms: ["mixed", "poignant"],
        frequency: "common",
        level: "B1",
        tags: ["emotions", "storytelling"],
        chapterSlug: CH8,
      }),
      w({
        word: "astonished",
        transcription: "/əˈstɒnɪʃt/",
        partOfSpeech: "adjective",
        translation: "изумлённый, поражённый",
        examples: [
          "We were astonished by the twist at the end of the story.",
          "She looked astonished when she heard the news.",
        ],
        commonMistakes: [
          "Use 'astonished at/by', not 'astonished from'.",
        ],
        synonyms: ["amazed", "stunned"],
        frequency: "common",
        level: "B1",
        tags: ["emotions", "surprise"],
        chapterSlug: CH8,
      }),
      w({
        word: "frustrated",
        transcription: "/frʌˈstreɪtɪd/",
        partOfSpeech: "adjective",
        translation: "расстроенный, раздражённый",
        examples: [
          "He grew frustrated when he couldn't remember the word.",
          "Frustrated learners often need a short break.",
        ],
        commonMistakes: [
          "Use 'frustrated with/at', not 'frustrated by someone' when blaming a person.",
        ],
        synonyms: ["annoyed", "irritated"],
        frequency: "core",
        level: "B1",
        tags: ["emotions", "negative"],
        chapterSlug: CH8,
      }),
      w({
        word: "ecstatic",
        transcription: "/ɪkˈstætɪk/",
        partOfSpeech: "adjective",
        translation: "в восторге, на седьмом небе",
        examples: [
          "She was ecstatic when she passed the interview.",
          "The crowd was ecstatic after the final goal.",
        ],
        commonMistakes: [
          "Stronger than 'happy' — do not use for mild pleasure.",
        ],
        synonyms: ["thrilled", "delighted"],
        frequency: "common",
        level: "B1",
        tags: ["emotions", "positive"],
        chapterSlug: CH8,
      }),
      w({
        word: "melancholy",
        transcription: "/ˈmelənkəli/",
        partOfSpeech: "noun",
        translation: "меланхолия, грусть",
        examples: [
          "A sense of melancholy filled the room after the story ended.",
          "Rainy afternoons often bring melancholy to old cities.",
        ],
        commonMistakes: [
          "Can be noun or adjective; do not use as a verb.",
        ],
        synonyms: ["sadness", "sorrow"],
        frequency: "uncommon",
        level: "B1",
        tags: ["emotions", "literature"],
        chapterSlug: CH8,
      }),
      w({
        word: "resentful",
        transcription: "/rɪˈzentfəl/",
        partOfSpeech: "adjective",
        translation: "обиженный, испытывающий негодование",
        examples: [
          "He felt resentful about being left out of the plan.",
          "Resentful feelings can damage long friendships.",
        ],
        commonMistakes: [
          "Use 'resentful about/at', not 'resentful against' a person.",
        ],
        synonyms: ["bitter", "indignant"],
        frequency: "uncommon",
        level: "B1",
        tags: ["emotions", "negative"],
        chapterSlug: CH8,
      }),
      w({
        word: "apprehensive",
        transcription: "/ˌæprɪˈhensɪv/",
        partOfSpeech: "adjective",
        translation: "тревожный, опасающийся",
        examples: [
          "She was apprehensive about telling her story in public.",
          "Many students feel apprehensive before speaking exams.",
        ],
        commonMistakes: [
          "Do not confuse with 'comprehensive' (complete/thorough).",
        ],
        synonyms: ["anxious", "uneasy"],
        frequency: "uncommon",
        level: "B1",
        tags: ["emotions", "worry"],
        chapterSlug: CH8,
      }),
      w({
        word: "heartfelt",
        transcription: "/ˈhɑːtfelt/",
        partOfSpeech: "adjective",
        translation: "искренний, от всего сердца",
        examples: [
          "She wrote a heartfelt letter to her grandmother.",
          "The audience gave a heartfelt round of applause.",
        ],
        commonMistakes: [
          "Usually comes before a noun: 'heartfelt thanks', not 'thanks heartfelt'.",
        ],
        synonyms: ["sincere", "genuine"],
        frequency: "common",
        level: "B1",
        tags: ["emotions", "expression"],
        chapterSlug: CH8,
      }),
      w({
        word: "burst into tears",
        transcription: "/bɜːst ˈɪntuː tɪəz/",
        partOfSpeech: "phrase",
        translation: "разразиться слезами, расплакаться",
        examples: [
          "When she heard the ending, she burst into tears.",
          "The child burst into tears after losing his toy.",
        ],
        commonMistakes: [
          "Use 'burst into tears', not 'burst in tears' or 'burst to tears'.",
        ],
        synonyms: ["cry suddenly", "break down"],
        frequency: "common",
        level: "B1",
        tags: ["emotions", "storytelling"],
        chapterSlug: CH8,
      }),
      w({
        word: "take aback",
        transcription: "/teɪk əˈbæk/",
        partOfSpeech: "phrase",
        translation: "ошеломить, застать врасплох",
        examples: [
          "The unexpected plot twist took the audience aback.",
          "I was taken aback by how emotional the story was.",
        ],
        commonMistakes: [
          "Always passive in practice: 'was taken aback', rarely active 'took someone aback'.",
        ],
        synonyms: ["surprise", "shock"],
        frequency: "uncommon",
        level: "B1",
        tags: ["emotions", "surprise"],
        chapterSlug: CH8,
      }),
    ],
  ),

  topic(
    {
      slug: "eng-b1-health-body",
      level: "B1",
      topic: "Здоровье и тело",
      topicEs: "Health & Body",
      icon: "🏥",
      chapterSlug: CH9,
    },
    [
      w({
        word: "symptom",
        transcription: "/ˈsɪmptəm/",
        partOfSpeech: "noun",
        translation: "симптом, признак болезни",
        examples: [
          "A high fever is a common symptom of flu.",
          "If symptoms persist, you should see a doctor.",
        ],
        commonMistakes: [
          "Use 'symptom of', not 'symptom for'.",
        ],
        synonyms: ["sign", "indicator"],
        frequency: "core",
        level: "B1",
        tags: ["health", "medicine"],
        chapterSlug: CH9,
      }),
      w({
        word: "chronic",
        transcription: "/ˈkrɒnɪk/",
        partOfSpeech: "adjective",
        translation: "хронический (о болезни)",
        examples: [
          "Chronic back pain affects many office workers.",
          "She manages a chronic condition with daily medication.",
        ],
        commonMistakes: [
          "In informal speech 'chronic' can mean 'very bad' — avoid in medical contexts.",
        ],
        synonyms: ["long-term", "persistent"],
        frequency: "common",
        level: "B1",
        tags: ["health", "medicine"],
        chapterSlug: CH9,
      }),
      w({
        word: "recover",
        transcription: "/rɪˈkʌvə(r)/",
        partOfSpeech: "verb",
        translation: "выздороветь, восстановиться",
        examples: [
          "It took two weeks to recover from the illness.",
          "Athletes need time to recover after intense training.",
        ],
        commonMistakes: [
          "Use 'recover from', not 'recover of'.",
        ],
        synonyms: ["get better", "heal"],
        frequency: "core",
        level: "B1",
        tags: ["health", "recovery"],
        chapterSlug: CH9,
      }),
      w({
        word: "prescribe",
        transcription: "/prɪˈskraɪb/",
        partOfSpeech: "verb",
        translation: "назначать (лекарство, лечение)",
        examples: [
          "The doctor prescribed antibiotics for the infection.",
          "Regular exercise is often prescribed for stress relief.",
        ],
        commonMistakes: [
          "Use 'prescribe something for someone', not 'prescribe someone something'.",
        ],
        synonyms: ["recommend", "order"],
        frequency: "common",
        level: "B1",
        tags: ["health", "medicine"],
        chapterSlug: CH9,
      }),
      w({
        word: "immune system",
        transcription: "/ɪˈmjuːn ˈsɪstəm/",
        partOfSpeech: "noun",
        translation: "иммунная система",
        examples: [
          "Sleep helps strengthen your immune system.",
          "A balanced diet supports a healthy immune system.",
        ],
        commonMistakes: [
          "Always plural 'system' — not 'immune systems' when referring to one person.",
        ],
        synonyms: ["body defences", "immunity"],
        frequency: "common",
        level: "B1",
        tags: ["health", "body"],
        chapterSlug: CH9,
      }),
      w({
        word: "stamina",
        transcription: "/ˈstæmɪnə/",
        partOfSpeech: "noun",
        translation: "выносливость, запас сил",
        examples: [
          "Running builds stamina over time.",
          "She lacked the stamina to finish the long hike.",
        ],
        commonMistakes: [
          "Uncountable noun — do not say 'a stamina' or 'staminas'.",
        ],
        synonyms: ["endurance", "energy"],
        frequency: "common",
        level: "B1",
        tags: ["health", "fitness"],
        chapterSlug: CH9,
      }),
      w({
        word: "ailment",
        transcription: "/ˈeɪlmənt/",
        partOfSpeech: "noun",
        translation: "недомогание, лёгкая болезнь",
        examples: [
          "Minor ailments like colds are common in winter.",
          "The clinic treats everyday ailments quickly.",
        ],
        commonMistakes: [
          "Refers to minor illnesses — not used for serious diseases.",
        ],
        synonyms: ["illness", "complaint"],
        frequency: "uncommon",
        level: "B1",
        tags: ["health", "medicine"],
        chapterSlug: CH9,
      }),
      w({
        word: "sprain",
        transcription: "/spreɪn/",
        partOfSpeech: "noun",
        translation: "растяжение (связок)",
        examples: [
          "He got a sprain in his ankle during football.",
          "Rest and ice help treat a mild sprain.",
        ],
        commonMistakes: [
          "Do not confuse 'sprain' (ligaments) with 'strain' (muscles).",
        ],
        synonyms: ["twist", "injury"],
        frequency: "common",
        level: "B1",
        tags: ["health", "injury"],
        chapterSlug: CH9,
      }),
      w({
        word: "fitness",
        transcription: "/ˈfɪtnəs/",
        partOfSpeech: "noun",
        translation: "физическая форма",
        examples: [
          "Regular swimming improves overall fitness.",
          "The gym offers classes for all fitness levels.",
        ],
        commonMistakes: [
          "Use 'physical fitness', not 'body fitness'.",
        ],
        synonyms: ["condition", "health"],
        frequency: "core",
        level: "B1",
        tags: ["health", "exercise"],
        chapterSlug: CH9,
      }),
      w({
        word: "wellness",
        transcription: "/ˈwelnəs/",
        partOfSpeech: "noun",
        translation: "благополучие, здоровый образ жизни",
        examples: [
          "The company promotes employee wellness programmes.",
          "Wellness includes mental as well as physical health.",
        ],
        commonMistakes: [
          "Uncountable — avoid 'a wellness' or 'wellnesses'.",
        ],
        synonyms: ["wellbeing", "health"],
        frequency: "common",
        level: "B1",
        tags: ["health", "lifestyle"],
        chapterSlug: CH9,
      }),
      w({
        word: "check-up",
        transcription: "/ˈtʃek ʌp/",
        partOfSpeech: "noun",
        translation: "медосмотр, профилактический осмотр",
        examples: [
          "You should have an annual check-up with your GP.",
          "The check-up showed that everything was normal.",
        ],
        commonMistakes: [
          "Hyphenated as a noun; as a verb write 'check up on'.",
        ],
        synonyms: ["examination", "screening"],
        frequency: "common",
        level: "B1",
        tags: ["health", "prevention"],
        chapterSlug: CH9,
      }),
      w({
        word: "sedentary",
        transcription: "/ˈsedntri/",
        partOfSpeech: "adjective",
        translation: "малоподвижный, сидячий",
        examples: [
          "A sedentary lifestyle increases health risks.",
          "Office workers often lead sedentary lives.",
        ],
        commonMistakes: [
          "Pronounced /ˈsedntri/ — the 'a' is silent.",
        ],
        synonyms: ["inactive", "stationary"],
        frequency: "uncommon",
        level: "B1",
        tags: ["health", "lifestyle"],
        chapterSlug: CH9,
      }),
    ],
  ),

  topic(
    {
      slug: "eng-b2-work-jobs",
      level: "B2",
      topic: "Работа и карьера",
      topicEs: "Work & Careers",
      icon: "💼",
      chapterSlug: CH10,
    },
    [
      w({
        word: "promotion",
        transcription: "/prəˈməʊʃn/",
        partOfSpeech: "noun",
        translation: "повышение (по службе)",
        examples: [
          "If I got a promotion, I would move to New York.",
          "She worked hard and earned a well-deserved promotion.",
        ],
        commonMistakes: [
          "Use 'promotion to + position', not 'promotion at'.",
        ],
        synonyms: ["advancement", "elevation"],
        frequency: "core",
        level: "B2",
        tags: ["career", "work"],
        chapterSlug: CH10,
      }),
      w({
        word: "redundancy",
        transcription: "/rɪˈdʌndənsi/",
        partOfSpeech: "noun",
        translation: "сокращение (увольнение по сокращению штатов)",
        examples: [
          "Many workers faced redundancy after the factory closed.",
          "Redundancy pay helped him during the job search.",
        ],
        commonMistakes: [
          "British term; Americans often say 'layoff' instead.",
        ],
        synonyms: ["layoff", "dismissal"],
        frequency: "uncommon",
        level: "B2",
        tags: ["career", "employment"],
        chapterSlug: CH10,
      }),
      w({
        word: "freelancer",
        transcription: "/ˈfriːlɑːnsə(r)/",
        partOfSpeech: "noun",
        translation: "фрилансер",
        examples: [
          "As a freelancer, she chooses her own projects.",
          "If he were a freelancer, he would have more flexibility.",
        ],
        commonMistakes: [
          "Use 'work as a freelancer', not 'work like freelancer'.",
        ],
        synonyms: ["contractor", "self-employed worker"],
        frequency: "common",
        level: "B2",
        tags: ["career", "modern work"],
        chapterSlug: CH10,
      }),
      w({
        word: "deadline",
        transcription: "/ˈdedlaɪn/",
        partOfSpeech: "noun",
        translation: "крайний срок, дедлайн",
        examples: [
          "We would miss the deadline if the client delayed approval.",
          "Meeting deadlines is essential in project management.",
        ],
        commonMistakes: [
          "Use 'meet a deadline', not 'reach a deadline'.",
        ],
        synonyms: ["due date", "time limit"],
        frequency: "core",
        level: "B2",
        tags: ["work", "time management"],
        chapterSlug: CH10,
      }),
      w({
        word: "negotiate",
        transcription: "/nɪˈɡəʊʃieɪt/",
        partOfSpeech: "verb",
        translation: "вести переговоры",
        examples: [
          "She negotiated a higher salary before accepting the offer.",
          "If they negotiated better terms, the deal would succeed.",
        ],
        commonMistakes: [
          "Use 'negotiate with someone about something'.",
        ],
        synonyms: ["bargain", "discuss"],
        frequency: "common",
        level: "B2",
        tags: ["career", "business"],
        chapterSlug: CH10,
      }),
      w({
        word: "internship",
        transcription: "/ˈɪntɜːnʃɪp/",
        partOfSpeech: "noun",
        translation: "стажировка",
        examples: [
          "An internship in finance would boost her CV.",
          "He completed a summer internship at a law firm.",
        ],
        commonMistakes: [
          "Use 'do an internship', not 'make an internship'.",
        ],
        synonyms: ["placement", "traineeship"],
        frequency: "common",
        level: "B2",
        tags: ["career", "education"],
        chapterSlug: CH10,
      }),
      w({
        word: "burnout",
        transcription: "/ˈbɜːnaʊt/",
        partOfSpeech: "noun",
        translation: "выгорание (на работе)",
        examples: [
          "Without rest, employees risk burnout.",
          "Burnout is common among healthcare workers.",
        ],
        commonMistakes: [
          "One word as a noun; 'burn out' is the verb phrase.",
        ],
        synonyms: ["exhaustion", "fatigue"],
        frequency: "common",
        level: "B2",
        tags: ["work", "mental health"],
        chapterSlug: CH10,
      }),
      w({
        word: "entrepreneurship",
        transcription: "/ˌɒntrəprəˈnɜːʃɪp/",
        partOfSpeech: "noun",
        translation: "предпринимательство",
        examples: [
          "Entrepreneurship requires courage and persistence.",
          "The course explores entrepreneurship in the digital age.",
        ],
        commonMistakes: [
          "Uncountable — do not use 'an entrepreneurship'.",
        ],
        synonyms: ["enterprise", "business creation"],
        frequency: "uncommon",
        level: "B2",
        tags: ["career", "business"],
        chapterSlug: CH10,
      }),
      w({
        word: "layoff",
        transcription: "/ˈleɪɒf/",
        partOfSpeech: "noun",
        translation: "увольнение (массовое сокращение)",
        examples: [
          "The company announced layoffs after poor sales.",
          "If layoffs happened, many families would struggle.",
        ],
        commonMistakes: [
          "American English; British often uses 'redundancy'.",
        ],
        synonyms: ["redundancy", "job cut"],
        frequency: "common",
        level: "B2",
        tags: ["career", "employment"],
        chapterSlug: CH10,
      }),
      w({
        word: "workload",
        transcription: "/ˈwɜːkləʊd/",
        partOfSpeech: "noun",
        translation: "рабочая нагрузка",
        examples: [
          "Her workload increased after two colleagues left.",
          "A heavy workload can lead to stress and burnout.",
        ],
        commonMistakes: [
          "One word — not 'work load'.",
        ],
        synonyms: ["work burden", "responsibilities"],
        frequency: "common",
        level: "B2",
        tags: ["work", "stress"],
        chapterSlug: CH10,
      }),
      w({
        word: "prospective",
        transcription: "/prəˈspektɪv/",
        partOfSpeech: "adjective",
        translation: "потенциальный, будущий (о кандидате, клиенте)",
        examples: [
          "Prospective employers review your online profile.",
          "The manager interviewed three prospective candidates.",
        ],
        commonMistakes: [
          "Use before a noun: 'prospective employer', not 'employer prospective'.",
        ],
        synonyms: ["potential", "future"],
        frequency: "common",
        level: "B2",
        tags: ["career", "business"],
        chapterSlug: CH10,
      }),
      w({
        word: "climb the ladder",
        transcription: "/klaɪm ðə ˈlædə(r)/",
        partOfSpeech: "phrase",
        translation: "подниматься по карьерной лестнице",
        examples: [
          "She climbed the ladder from intern to director.",
          "If you worked harder, you might climb the ladder faster.",
        ],
        commonMistakes: [
          "Idiomatic — use 'climb the career ladder' for clarity in formal writing.",
        ],
        synonyms: ["advance", "progress"],
        frequency: "common",
        level: "B2",
        tags: ["career", "idiom"],
        chapterSlug: CH10,
      }),
    ],
  ),

  topic(
    {
      slug: "eng-b2-education",
      level: "B2",
      topic: "Образование и обучение",
      topicEs: "Education & Learning",
      icon: "🎓",
      chapterSlug: CH11,
    },
    [
      w({
        word: "curriculum",
        transcription: "/kəˈrɪkjələm/",
        partOfSpeech: "noun",
        translation: "учебная программа, curriculum",
        examples: [
          "The curriculum is designed by the education department.",
          "New subjects were added to the national curriculum.",
        ],
        commonMistakes: [
          "Plural is 'curricula' or 'curriculums' — not 'curriculum's'.",
        ],
        synonyms: ["syllabus", "programme"],
        frequency: "common",
        level: "B2",
        tags: ["education", "school"],
        chapterSlug: CH11,
      }),
      w({
        word: "tuition",
        transcription: "/tjuˈɪʃn/",
        partOfSpeech: "noun",
        translation: "обучение; плата за обучение",
        examples: [
          "Tuition fees have risen at many universities.",
          "Private tuition is offered in maths and science.",
        ],
        commonMistakes: [
          "Can mean 'teaching' or 'fees' — context determines meaning.",
        ],
        synonyms: ["instruction", "fees"],
        frequency: "common",
        level: "B2",
        tags: ["education", "university"],
        chapterSlug: CH11,
      }),
      w({
        word: "dissertation",
        transcription: "/ˌdɪsəˈteɪʃn/",
        partOfSpeech: "noun",
        translation: "диссертация",
        examples: [
          "Her dissertation was published in an academic journal.",
          "Students must submit a dissertation to graduate.",
        ],
        commonMistakes: [
          "British 'dissertation' (undergraduate/postgrad); American 'thesis' is often used similarly.",
        ],
        synonyms: ["thesis", "research paper"],
        frequency: "uncommon",
        level: "B2",
        tags: ["education", "university"],
        chapterSlug: CH11,
      }),
      w({
        word: "seminar",
        transcription: "/ˈsemɪnɑː(r)/",
        partOfSpeech: "noun",
        translation: "семинар",
        examples: [
          "The seminar on passive voice was held in Boston.",
          "Students are expected to participate actively in seminars.",
        ],
        commonMistakes: [
          "Use 'attend a seminar', not 'visit a seminar'.",
        ],
        synonyms: ["workshop", "class"],
        frequency: "common",
        level: "B2",
        tags: ["education", "university"],
        chapterSlug: CH11,
      }),
      w({
        word: "plagiarism",
        transcription: "/ˈpleɪdʒərɪzəm/",
        partOfSpeech: "noun",
        translation: "плагиат",
        examples: [
          "Plagiarism is taken seriously at every university.",
          "Copying text without citation counts as plagiarism.",
        ],
        commonMistakes: [
          "Uncountable — say 'an act of plagiarism', not 'a plagiarism'.",
        ],
        synonyms: ["copying", "academic dishonesty"],
        frequency: "common",
        level: "B2",
        tags: ["education", "academic integrity"],
        chapterSlug: CH11,
      }),
      w({
        word: "enrol",
        transcription: "/ɪnˈrəʊl/",
        partOfSpeech: "verb",
        translation: "записаться, зачислиться (на курс)",
        examples: [
          "Over 500 students enrolled in the online course.",
          "She enrolled on a part-time MBA programme.",
        ],
        commonMistakes: [
          "British 'enrol/enrolment'; American 'enroll/enrollment'.",
          "Use 'enrol on/in a course', not 'enrol to a course'.",
        ],
        synonyms: ["register", "sign up"],
        frequency: "common",
        level: "B2",
        tags: ["education", "registration"],
        chapterSlug: CH11,
      }),
      w({
        word: "scholarship",
        transcription: "/ˈskɒləʃɪp/",
        partOfSpeech: "noun",
        translation: "стипендия, грант на обучение",
        examples: [
          "He won a scholarship to study engineering.",
          "Scholarships are awarded based on merit and need.",
        ],
        commonMistakes: [
          "Use 'win/receive a scholarship', not 'get a scholarship' in formal writing.",
        ],
        synonyms: ["grant", "bursary"],
        frequency: "common",
        level: "B2",
        tags: ["education", "finance"],
        chapterSlug: CH11,
      }),
      w({
        word: "literacy",
        transcription: "/ˈlɪtərəsi/",
        partOfSpeech: "noun",
        translation: "грамотность",
        examples: [
          "Digital literacy is taught in modern schools.",
          "Literacy rates have improved across the region.",
        ],
        commonMistakes: [
          "Use 'literacy in + subject': 'literacy in maths', not 'maths literacy' in formal texts.",
        ],
        synonyms: ["reading ability", "competence"],
        frequency: "common",
        level: "B2",
        tags: ["education", "skills"],
        chapterSlug: CH11,
      }),
      w({
        word: "aptitude",
        transcription: "/ˈæptɪtjuːd/",
        partOfSpeech: "noun",
        translation: "способность, склонность, дар",
        examples: [
          "She showed a natural aptitude for languages.",
          "Aptitude tests are used in university admissions.",
        ],
        commonMistakes: [
          "Use 'aptitude for', not 'aptitude to' or 'aptitude in'.",
        ],
        synonyms: ["talent", "ability"],
        frequency: "uncommon",
        level: "B2",
        tags: ["education", "skills"],
        chapterSlug: CH11,
      }),
      w({
        word: "extracurricular",
        transcription: "/ˌekstrəkəˈrɪkjələ(r)/",
        partOfSpeech: "adjective",
        translation: "внеучебный, внеурочный",
        examples: [
          "Extracurricular activities strengthen university applications.",
          "Sports and clubs are popular extracurricular options.",
        ],
        commonMistakes: [
          "One word — not 'extra curricular'.",
        ],
        synonyms: ["non-academic", "after-school"],
        frequency: "common",
        level: "B2",
        tags: ["education", "school life"],
        chapterSlug: CH11,
      }),
      w({
        word: "thesis",
        transcription: "/ˈθiːsɪs/",
        partOfSpeech: "noun",
        translation: "дипломная/магистерская работа, тезис",
        examples: [
          "His thesis explores how language is processed in the brain.",
          "The central thesis of the book is clearly stated.",
        ],
        commonMistakes: [
          "Plural 'theses' /ˈθiːsiːz/ — do not say 'thesises'.",
        ],
        synonyms: ["dissertation", "argument"],
        frequency: "common",
        level: "B2",
        tags: ["education", "academic writing"],
        chapterSlug: CH11,
      }),
      w({
        word: "lecture",
        transcription: "/ˈlektʃə(r)/",
        partOfSpeech: "noun",
        translation: "лекция",
        examples: [
          "The lecture on passive voice was recorded for students.",
          "Attendance at lectures is compulsory in the first year.",
        ],
        commonMistakes: [
          "Use 'give/deliver a lecture', not 'make a lecture'.",
        ],
        synonyms: ["talk", "presentation"],
        frequency: "core",
        level: "B2",
        tags: ["education", "university"],
        chapterSlug: CH11,
      }),
    ],
  ),

  topic(
    {
      slug: "eng-b2-environment",
      level: "B2",
      topic: "Экология и общество",
      topicEs: "Environment & Society",
      icon: "🌍",
      chapterSlug: CH12,
    },
    [
      w({
        word: "sustainability",
        transcription: "/səˌsteɪnəˈbɪləti/",
        partOfSpeech: "noun",
        translation: "устойчивое развитие, экологичность",
        examples: [
          "Sustainability is a key goal for cities beyond borders.",
          "Companies report on sustainability every year.",
        ],
        commonMistakes: [
          "Uncountable — avoid 'a sustainability'.",
        ],
        synonyms: ["viability", "eco-friendliness"],
        frequency: "common",
        level: "B2",
        tags: ["environment", "society"],
        chapterSlug: CH12,
      }),
      w({
        word: "carbon footprint",
        transcription: "/ˈkɑːbən ˈfʊtprɪnt/",
        partOfSpeech: "noun",
        translation: "углеродный след",
        examples: [
          "Flying less reduces your carbon footprint.",
          "The report measured the city's carbon footprint.",
        ],
        commonMistakes: [
          "Use 'reduce/lowering your carbon footprint', not 'decrease footprint of carbon'.",
        ],
        synonyms: ["emissions impact", "CO₂ output"],
        frequency: "common",
        level: "B2",
        tags: ["environment", "climate"],
        chapterSlug: CH12,
      }),
      w({
        word: "renewable",
        transcription: "/rɪˈnjuːəbl/",
        partOfSpeech: "adjective",
        translation: "возобновляемый (об энергии)",
        examples: [
          "Renewable energy sources include wind and solar power.",
          "The country invested heavily in renewable technology.",
        ],
        commonMistakes: [
          "Use 'renewable energy', not 'renewable electricity' in general contexts.",
        ],
        synonyms: ["sustainable", "green"],
        frequency: "common",
        level: "B2",
        tags: ["environment", "energy"],
        chapterSlug: CH12,
      }),
      w({
        word: "drought",
        transcription: "/draʊt/",
        partOfSpeech: "noun",
        translation: "засуха",
        examples: [
          "A severe drought destroyed crops across the region.",
          "Climate change may increase the frequency of droughts.",
        ],
        commonMistakes: [
          "Pronounced /draʊt/ — the 'gh' is silent.",
        ],
        synonyms: ["dry spell", "water shortage"],
        frequency: "common",
        level: "B2",
        tags: ["environment", "climate"],
        chapterSlug: CH12,
      }),
      w({
        word: "biodiversity",
        transcription: "/ˌbaɪəʊdaɪˈvɜːsəti/",
        partOfSpeech: "noun",
        translation: "биоразнообразие",
        examples: [
          "Rainforests contain extraordinary biodiversity.",
          "Protecting biodiversity benefits future generations.",
        ],
        commonMistakes: [
          "Uncountable — do not use 'biodiversities'.",
        ],
        synonyms: ["ecological variety", "species richness"],
        frequency: "common",
        level: "B2",
        tags: ["environment", "nature"],
        chapterSlug: CH12,
      }),
      w({
        word: "emissions",
        transcription: "/ɪˈmɪʃnz/",
        partOfSpeech: "noun",
        translation: "выбросы (загрязняющих веществ)",
        examples: [
          "Vehicle emissions contribute to air pollution.",
          "The factory cut its carbon emissions by 30%.",
        ],
        commonMistakes: [
          "Usually plural — 'emission' singular refers to one release.",
        ],
        synonyms: ["discharge", "pollutants"],
        frequency: "common",
        level: "B2",
        tags: ["environment", "climate"],
        chapterSlug: CH12,
      }),
      w({
        word: "conservation",
        transcription: "/ˌkɒnsəˈveɪʃn/",
        partOfSpeech: "noun",
        translation: "охрана природы, сохранение",
        examples: [
          "Wildlife conservation requires international cooperation.",
          "Water conservation saves resources in dry regions.",
        ],
        commonMistakes: [
          "Use 'conservation of', not 'conservation for'.",
        ],
        synonyms: ["preservation", "protection"],
        frequency: "common",
        level: "B2",
        tags: ["environment", "nature"],
        chapterSlug: CH12,
      }),
      w({
        word: "urbanisation",
        transcription: "/ˌɜːbənaɪˈzeɪʃn/",
        partOfSpeech: "noun",
        translation: "урбанизация",
        examples: [
          "Rapid urbanisation creates pressure on housing.",
          "Urbanisation has transformed landscapes worldwide.",
        ],
        commonMistakes: [
          "British spelling; American: 'urbanization'.",
        ],
        synonyms: ["city growth", "metropolitan expansion"],
        frequency: "uncommon",
        level: "B2",
        tags: ["society", "cities"],
        chapterSlug: CH12,
      }),
      w({
        word: "inequality",
        transcription: "/ˌɪnɪˈkwɒləti/",
        partOfSpeech: "noun",
        translation: "неравенство",
        examples: [
          "Economic inequality remains a global challenge.",
          "Education can help reduce social inequality.",
        ],
        commonMistakes: [
          "Use 'inequality between/in', not 'inequality of people'.",
        ],
        synonyms: ["disparity", "unfairness"],
        frequency: "common",
        level: "B2",
        tags: ["society", "politics"],
        chapterSlug: CH12,
      }),
      w({
        word: "refugee",
        transcription: "/ˌrefjuˈdʒiː/",
        partOfSpeech: "noun",
        translation: "беженец",
        examples: [
          "Millions of refugees cross borders seeking safety.",
          "The camp provides shelter for refugee families.",
        ],
        commonMistakes: [
          "Do not confuse 'refugee' (fleeing country) with 'migrant' (broader term).",
        ],
        synonyms: ["displaced person", "asylum seeker"],
        frequency: "common",
        level: "B2",
        tags: ["society", "migration"],
        chapterSlug: CH12,
      }),
      w({
        word: "infrastructure",
        transcription: "/ˈɪnfrəstrʌktʃə(r)/",
        partOfSpeech: "noun",
        translation: "инфраструктура",
        examples: [
          "Investment in infrastructure supports economic growth.",
          "Poor infrastructure limits access to remote areas.",
        ],
        commonMistakes: [
          "Uncountable — avoid 'infrastructures' except in technical contexts.",
        ],
        synonyms: ["facilities", "framework"],
        frequency: "common",
        level: "B2",
        tags: ["society", "development"],
        chapterSlug: CH12,
      }),
      w({
        word: "mitigate",
        transcription: "/ˈmɪtɪɡeɪt/",
        partOfSpeech: "verb",
        translation: "смягчать, уменьшать (вред, риск)",
        examples: [
          "Governments must mitigate the effects of climate change.",
          "Planting trees helps mitigate flood risks.",
        ],
        commonMistakes: [
          "Formal register — use 'reduce' in everyday speech.",
          "Use 'mitigate the effects/impact of', not 'mitigate against'.",
        ],
        synonyms: ["alleviate", "lessen"],
        frequency: "uncommon",
        level: "B2",
        tags: ["environment", "formal"],
        chapterSlug: CH12,
      }),
    ],
  ),

  topic(
    {
      slug: "eng-c1-idioms",
      level: "C1",
      topic: "Идиомы и выражения",
      topicEs: "Idioms & Expressions",
      icon: "💬",
      chapterSlug: CH13,
    },
    [
      w({
        word: "break the ice",
        transcription: "/breɪk ði aɪs/",
        partOfSpeech: "phrase",
        translation: "растопить лёд, начать разговор",
        examples: [
          "He told a joke to break the ice at the meeting.",
          "Small talk helps break the ice with new colleagues.",
        ],
        commonMistakes: [
          "Idiom — do not translate literally word for word in your own speech.",
        ],
        synonyms: ["ease tension", "start conversation"],
        frequency: "common",
        level: "C1",
        tags: ["idiom", "communication"],
        chapterSlug: CH13,
      }),
      w({
        word: "hit the nail on the head",
        transcription: "/hɪt ðə neɪl ɒn ðə hed/",
        partOfSpeech: "phrase",
        translation: "попасть в точку, сказать в самое сердце",
        examples: [
          "You hit the nail on the head with that analysis.",
          "Her comment hit the nail on the head about the problem.",
        ],
        commonMistakes: [
          "Use for accurate statements — not for physical actions.",
        ],
        synonyms: ["be exactly right", "get it spot on"],
        frequency: "common",
        level: "C1",
        tags: ["idiom", "accuracy"],
        chapterSlug: CH13,
      }),
      w({
        word: "once in a blue moon",
        transcription: "/wʌns ɪn ə bluː muːn/",
        partOfSpeech: "phrase",
        translation: "очень редко, раз в сто лет",
        examples: [
          "We eat out once in a blue moon these days.",
          "She visits her hometown once in a blue moon.",
        ],
        commonMistakes: [
          "Means 'very rarely' — not literally related to the moon.",
        ],
        synonyms: ["hardly ever", "rarely"],
        frequency: "common",
        level: "C1",
        tags: ["idiom", "frequency"],
        chapterSlug: CH13,
      }),
      w({
        word: "the ball is in your court",
        transcription: "/ðə bɔːl ɪz ɪn jɔː kɔːt/",
        partOfSpeech: "phrase",
        translation: "ход за тобой, решать тебе",
        examples: [
          "I've sent the proposal — now the ball is in your court.",
          "After the interview, the ball was in the employer's court.",
        ],
        commonMistakes: [
          "Use when someone else must take the next action.",
        ],
        synonyms: ["it's your move", "it's up to you"],
        frequency: "common",
        level: "C1",
        tags: ["idiom", "decisions"],
        chapterSlug: CH13,
      }),
      w({
        word: "burn the candle at both ends",
        transcription: "/bɜːn ðə ˈkændl æt bəʊθ endz/",
        partOfSpeech: "phrase",
        translation: "перегружать себя, не давать себе отдыха",
        examples: [
          "She burned the candle at both ends during exam season.",
          "Burning the candle at both ends leads to exhaustion.",
        ],
        commonMistakes: [
          "Use past 'burned' or 'burnt' — both are acceptable in British English.",
        ],
        synonyms: ["overwork", "push yourself too hard"],
        frequency: "uncommon",
        level: "C1",
        tags: ["idiom", "lifestyle"],
        chapterSlug: CH13,
      }),
      w({
        word: "equivocal",
        transcription: "/ɪˈkwɪvəkl/",
        partOfSpeech: "adjective",
        translation: "двусмысленный, неоднозначный",
        examples: [
          "The politician gave an equivocal answer to the journalist.",
          "Equivocal evidence made the verdict difficult.",
        ],
        commonMistakes: [
          "Do not confuse with 'equivalent' (equal in value).",
        ],
        synonyms: ["ambiguous", "unclear"],
        frequency: "advanced",
        level: "C2",
        tags: ["formal", "communication"],
        chapterSlug: CH13,
      }),
      w({
        word: "quintessential",
        transcription: "/ˌkwɪntɪˈsenʃl/",
        partOfSpeech: "adjective",
        translation: "типичный, образцовый, квинтэссенциальный",
        examples: [
          "Fish and chips is the quintessential British dish.",
          "She is the quintessential professional — calm and precise.",
        ],
        commonMistakes: [
          "Often used with 'the quintessential + noun'.",
        ],
        synonyms: ["typical", "archetypal"],
        frequency: "advanced",
        level: "C2",
        tags: ["formal", "description"],
        chapterSlug: CH13,
      }),
      w({
        word: "pull someone's leg",
        transcription: "/pʊl ˈsʌmwʌnz leɡ/",
        partOfSpeech: "phrase",
        translation: "разыграть, подшутить над кем-то",
        examples: [
          "Don't worry — I was just pulling your leg.",
          "He pulled her leg about failing the easy test.",
        ],
        commonMistakes: [
          "Informal — avoid in formal IELTS Writing Task 2.",
        ],
        synonyms: ["tease", "joke with"],
        frequency: "common",
        level: "C1",
        tags: ["idiom", "humour"],
        chapterSlug: CH13,
      }),
      w({
        word: "read between the lines",
        transcription: "/riːd bɪˈtwiːn ðə laɪnz/",
        partOfSpeech: "phrase",
        translation: "читать между строк",
        examples: [
          "If you read between the lines, she is not happy at work.",
          "Advanced readers learn to read between the lines in news reports.",
        ],
        commonMistakes: [
          "Always plural 'lines' — not 'read between the line'.",
        ],
        synonyms: ["infer", "interpret subtly"],
        frequency: "common",
        level: "C1",
        tags: ["idiom", "comprehension"],
        chapterSlug: CH13,
      }),
      w({
        word: "call it a day",
        transcription: "/kɔːl ɪt ə deɪ/",
        partOfSpeech: "phrase",
        translation: "закончить на сегодня, остановиться",
        examples: [
          "After eight hours of revision, we called it a day.",
          "Let's call it a day and continue tomorrow.",
        ],
        commonMistakes: [
          "Refers to stopping work — not ending a relationship.",
        ],
        synonyms: ["stop for today", "wrap up"],
        frequency: "common",
        level: "C1",
        tags: ["idiom", "work"],
        chapterSlug: CH13,
      }),
      w({
        word: "get out of hand",
        transcription: "/ɡet aʊt əv hænd/",
        partOfSpeech: "phrase",
        translation: "выйти из-под контроля",
        examples: [
          "Costs got out of hand during the renovation.",
          "The debate got out of hand and had to be stopped.",
        ],
        commonMistakes: [
          "Use 'get out of hand', not 'get out of hands'.",
        ],
        synonyms: ["escalate", "become uncontrollable"],
        frequency: "common",
        level: "C1",
        tags: ["idiom", "problems"],
        chapterSlug: CH13,
      }),
      w({
        word: "parsimonious",
        transcription: "/ˌpɑːsɪˈməʊniəs/",
        partOfSpeech: "adjective",
        translation: "скупой, чрезмерно экономный",
        examples: [
          "A parsimonious explanation uses the fewest assumptions.",
          "The review praised the author's parsimonious use of language.",
        ],
        commonMistakes: [
          "In academic contexts means 'economical' — not only 'stingy'.",
        ],
        synonyms: ["frugal", "sparing"],
        frequency: "advanced",
        level: "C2",
        tags: ["formal", "academic"],
        chapterSlug: CH13,
      }),
    ],
  ),

  topic(
    {
      slug: "eng-c1-academic",
      level: "C1",
      topic: "Академический язык",
      topicEs: "Academic Language",
      icon: "📖",
      chapterSlug: CH14,
    },
    [
      w({
        word: "hypothesis",
        transcription: "/haɪˈpɒθəsɪs/",
        partOfSpeech: "noun",
        translation: "гипотеза",
        examples: [
          "The researchers tested their hypothesis with a controlled experiment.",
          "A clear hypothesis guides the design of academic studies.",
        ],
        commonMistakes: [
          "Plural is 'hypotheses' /haɪˈpɒθəsiːz/ — not 'hypothesis's'.",
        ],
        synonyms: ["theory", "proposition"],
        frequency: "common",
        level: "C1",
        tags: ["academic", "research"],
        chapterSlug: CH14,
      }),
      w({
        word: "methodology",
        transcription: "/ˌmeθəˈdɒlədʒi/",
        partOfSpeech: "noun",
        translation: "методология",
        examples: [
          "The methodology section explains how data were collected.",
          "Qualitative methodology was chosen for this social study.",
        ],
        commonMistakes: [
          "Use 'methodology' for the overall approach; 'method' for specific techniques.",
        ],
        synonyms: ["approach", "framework"],
        frequency: "common",
        level: "C1",
        tags: ["academic", "research"],
        chapterSlug: CH14,
      }),
      w({
        word: "empirical",
        transcription: "/ɪmˈpɪrɪkl/",
        partOfSpeech: "adjective",
        translation: "эмпирический, основанный на наблюдении",
        examples: [
          "Empirical evidence supports the claim in the article.",
          "The study provides empirical data on language learning.",
        ],
        commonMistakes: [
          "Use 'empirical evidence/data', not 'empirical prove'.",
        ],
        synonyms: ["observational", "experimental"],
        frequency: "uncommon",
        level: "C1",
        tags: ["academic", "research"],
        chapterSlug: CH14,
      }),
      w({
        word: "substantiate",
        transcription: "/səbˈstænʃieɪt/",
        partOfSpeech: "verb",
        translation: "подтверждать, обосновывать",
        examples: [
          "You must substantiate your argument with reliable sources.",
          "The figures substantiate the report's main conclusion.",
        ],
        commonMistakes: [
          "Formal — use 'support' or 'back up' in informal speech.",
        ],
        synonyms: ["verify", "corroborate"],
        frequency: "advanced",
        level: "C2",
        tags: ["academic", "formal"],
        chapterSlug: CH14,
      }),
      w({
        word: "paradigm",
        transcription: "/ˈpærədaɪm/",
        partOfSpeech: "noun",
        translation: "парадигма, модель",
        examples: [
          "The discovery shifted the paradigm in cognitive science.",
          "A new paradigm emerged in how we teach languages.",
        ],
        commonMistakes: [
          "Singular and plural are both 'paradigms' — avoid 'paradigma'.",
        ],
        synonyms: ["model", "framework"],
        frequency: "uncommon",
        level: "C1",
        tags: ["academic", "theory"],
        chapterSlug: CH14,
      }),
      w({
        word: "correlate",
        transcription: "/ˈkɒrəleɪt/",
        partOfSpeech: "verb",
        translation: "коррелировать, находиться в связи",
        examples: [
          "Sleep quality correlates with academic performance.",
          "Researchers correlated income levels with access to education.",
        ],
        commonMistakes: [
          "Correlation does not imply causation — do not say 'causes'.",
        ],
        synonyms: ["correspond", "be linked"],
        frequency: "uncommon",
        level: "C1",
        tags: ["academic", "statistics"],
        chapterSlug: CH14,
      }),
      w({
        word: "inference",
        transcription: "/ˈɪnfərəns/",
        partOfSpeech: "noun",
        translation: "вывод, умозаключение",
        examples: [
          "The inference drawn from the data was cautiously optimistic.",
          "Readers make inferences based on context and evidence.",
        ],
        commonMistakes: [
          "Use 'draw/make an inference', not 'do an inference'.",
        ],
        synonyms: ["conclusion", "deduction"],
        frequency: "uncommon",
        level: "C1",
        tags: ["academic", "logic"],
        chapterSlug: CH14,
      }),
      w({
        word: "discourse",
        transcription: "/ˈdɪskɔːs/",
        partOfSpeech: "noun",
        translation: "дискурс, речь, обсуждение",
        examples: [
          "Academic discourse requires precise vocabulary and structure.",
          "Public discourse on climate change has intensified.",
        ],
        commonMistakes: [
          "As a noun: /ˈdɪskɔːs/; as a verb: /dɪsˈkɔːs/ — stress changes.",
        ],
        synonyms: ["discussion", "communication"],
        frequency: "uncommon",
        level: "C1",
        tags: ["academic", "language"],
        chapterSlug: CH14,
      }),
      w({
        word: "synthesize",
        transcription: "/ˈsɪnθəsaɪz/",
        partOfSpeech: "verb",
        translation: "синтезировать, обобщать",
        examples: [
          "A good essay synthesizes ideas from several sources.",
          "The author synthesizes decades of research in one chapter.",
        ],
        commonMistakes: [
          "British 'synthesise'; American 'synthesize'.",
        ],
        synonyms: ["combine", "integrate"],
        frequency: "uncommon",
        level: "C1",
        tags: ["academic", "writing"],
        chapterSlug: CH14,
      }),
      w({
        word: "qualitative",
        transcription: "/ˈkwɒlɪtətɪv/",
        partOfSpeech: "adjective",
        translation: "качественный (о методе исследования)",
        examples: [
          "Qualitative interviews reveal how learners feel about exams.",
          "The study used qualitative analysis of student journals.",
        ],
        commonMistakes: [
          "Do not confuse with 'qualitative' (quality) vs 'quantitative' (quantity).",
        ],
        synonyms: ["descriptive", "non-numerical"],
        frequency: "uncommon",
        level: "C1",
        tags: ["academic", "research"],
        chapterSlug: CH14,
      }),
      w({
        word: "quantitative",
        transcription: "/ˈkwɒntɪtətɪv/",
        partOfSpeech: "adjective",
        translation: "количественный (о методе исследования)",
        examples: [
          "Quantitative methods rely on statistical analysis.",
          "The report includes both qualitative and quantitative findings.",
        ],
        commonMistakes: [
          "Pair with 'analysis/data/methods' — not 'quantitative information' alone.",
        ],
        synonyms: ["numerical", "statistical"],
        frequency: "uncommon",
        level: "C1",
        tags: ["academic", "research"],
        chapterSlug: CH14,
      }),
      w({
        word: "extrapolate",
        transcription: "/ɪkˈstræpəleɪt/",
        partOfSpeech: "verb",
        translation: "экстраполировать, делать вывод на основе данных",
        examples: [
          "We cannot extrapolate these results to all age groups.",
          "Scientists extrapolated future trends from current data.",
        ],
        commonMistakes: [
          "Use 'extrapolate from', not 'extrapolate to' without careful context.",
        ],
        synonyms: ["project", "infer"],
        frequency: "advanced",
        level: "C2",
        tags: ["academic", "statistics"],
        chapterSlug: CH14,
      }),
    ],
  ),

  topic(
    {
      slug: "eng-c1-literary",
      level: "C1",
      topic: "Литературный и официальный стиль",
      topicEs: "Literary & Formal Register",
      icon: "🎭",
      chapterSlug: CH15,
    },
    [
      w({
        word: "allegory",
        transcription: "/ˈæləɡəri/",
        partOfSpeech: "noun",
        translation: "аллегория",
        examples: [
          "The novel works as an allegory of political oppression.",
          "Readers discussed the allegory beneath the surface narrative.",
        ],
        commonMistakes: [
          "An allegory represents abstract ideas as characters/events.",
        ],
        synonyms: ["symbolic tale", "parable"],
        frequency: "uncommon",
        level: "C1",
        tags: ["literature", "analysis"],
        chapterSlug: CH15,
      }),
      w({
        word: "prose",
        transcription: "/prəʊz/",
        partOfSpeech: "noun",
        translation: "проза",
        examples: [
          "Her prose is elegant and finely controlled.",
          "The exam asked students to compare poetry and prose.",
        ],
        commonMistakes: [
          "Uncountable — do not say 'a prose' unless 'a prose passage'.",
        ],
        synonyms: ["written text", "non-verse writing"],
        frequency: "common",
        level: "C1",
        tags: ["literature", "writing"],
        chapterSlug: CH15,
      }),
      w({
        word: "rhetoric",
        transcription: "/ˈretərɪk/",
        partOfSpeech: "noun",
        translation: "риторика, красноречие",
        examples: [
          "The speech was admired for its powerful rhetoric.",
          "Empty rhetoric without action frustrates voters.",
        ],
        commonMistakes: [
          "Can be neutral (skill) or negative (empty words) — context matters.",
        ],
        synonyms: ["oratory", "eloquence"],
        frequency: "uncommon",
        level: "C1",
        tags: ["literature", "persuasion"],
        chapterSlug: CH15,
      }),
      w({
        word: "poignant",
        transcription: "/ˈpɔɪnjənt/",
        partOfSpeech: "adjective",
        translation: "пронзительный, трогательный",
        examples: [
          "The final chapter offers a poignant reflection on loss.",
          "There was a poignant silence after the story ended.",
        ],
        commonMistakes: [
          "Pronounced /ˈpɔɪnjənt/ — do not pronounce the 'g'.",
        ],
        synonyms: ["moving", "touching"],
        frequency: "uncommon",
        level: "C1",
        tags: ["literature", "emotion"],
        chapterSlug: CH15,
      }),
      w({
        word: "eloquent",
        transcription: "/ˈeləkwənt/",
        partOfSpeech: "adjective",
        translation: "красноречивый, выразительный",
        examples: [
          "An eloquent speaker can hold an audience without notes.",
          "The letter was an eloquent plea for reconciliation.",
        ],
        commonMistakes: [
          "Use 'eloquent about/on', not 'eloquent in speaking' redundantly.",
        ],
        synonyms: ["articulate", "expressive"],
        frequency: "uncommon",
        level: "C1",
        tags: ["literature", "communication"],
        chapterSlug: CH15,
      }),
      w({
        word: "terse",
        transcription: "/tɜːs/",
        partOfSpeech: "adjective",
        translation: "лаконичный, сухой, резкий",
        examples: [
          "His terse reply suggested he did not wish to continue.",
          "The editor praised the terse clarity of the opening paragraph.",
        ],
        commonMistakes: [
          "Can sound negative (abrupt) — not always a compliment.",
        ],
        synonyms: ["brief", "curt"],
        frequency: "advanced",
        level: "C2",
        tags: ["literature", "formal register"],
        chapterSlug: CH15,
      }),
      w({
        word: "vernacular",
        transcription: "/vəˈnækjələ(r)/",
        partOfSpeech: "noun",
        translation: "разговорный язык, народный язык",
        examples: [
          "The poet blended formal English with local vernacular.",
          "Academic writing avoids excessive vernacular expressions.",
        ],
        commonMistakes: [
          "Often 'the vernacular' — refers to everyday speech of a region.",
        ],
        synonyms: ["colloquial language", "dialect"],
        frequency: "advanced",
        level: "C2",
        tags: ["literature", "register"],
        chapterSlug: CH15,
      }),
      w({
        word: "foreshadow",
        transcription: "/fɔːˈʃædəʊ/",
        partOfSpeech: "verb",
        translation: "предвещать, предзнаменовать",
        examples: [
          "Dark clouds foreshadow the tragedy in the next chapter.",
          "Early dialogue foreshadows the hero's final decision.",
        ],
        commonMistakes: [
          "Literary term — use 'hint at' in everyday conversation.",
        ],
        synonyms: ["hint", "presage"],
        frequency: "uncommon",
        level: "C1",
        tags: ["literature", "narrative"],
        chapterSlug: CH15,
      }),
      w({
        word: "denouement",
        transcription: "/deɪˈnuːmɑ̃/",
        partOfSpeech: "noun",
        translation: "развязка (сюжета)",
        examples: [
          "The denouement ties together every subplot neatly.",
          "Readers found the denouement both surprising and satisfying.",
        ],
        commonMistakes: [
          "French origin — often kept in literary criticism.",
        ],
        synonyms: ["resolution", "conclusion"],
        frequency: "advanced",
        level: "C2",
        tags: ["literature", "narrative"],
        chapterSlug: CH15,
      }),
      w({
        word: "register",
        transcription: "/ˈredʒɪstə(r)/",
        partOfSpeech: "noun",
        translation: "регистр (стиль языка)",
        examples: [
          "Formal register is expected in academic essays.",
          "The author shifts register to reflect the character's background.",
        ],
        commonMistakes: [
          "In linguistics, 'register' means style level — not 'registration'.",
        ],
        synonyms: ["style", "tone"],
        frequency: "uncommon",
        level: "C1",
        tags: ["linguistics", "formal register"],
        chapterSlug: CH15,
      }),
      w({
        word: "satirical",
        transcription: "/səˈtɪrɪkl/",
        partOfSpeech: "adjective",
        translation: "сатирический",
        examples: [
          "The satirical novel mocks bureaucracy and greed.",
          "Satirical writing uses humour to criticise society.",
        ],
        commonMistakes: [
          "Use 'satirical' for works; 'satirise' (verb) for the act of mocking.",
        ],
        synonyms: ["mocking", "ironic"],
        frequency: "uncommon",
        level: "C1",
        tags: ["literature", "humour"],
        chapterSlug: CH15,
      }),
      w({
        word: "arcane",
        transcription: "/ɑːˈkeɪn/",
        partOfSpeech: "adjective",
        translation: "тайный, малоизвестный, эзотерический",
        examples: [
          "The text references arcane rituals described in medieval manuscripts.",
          "Legal documents sometimes contain arcane terminology.",
        ],
        commonMistakes: [
          "Implies mysterious and little-known — not simply 'old'.",
        ],
        synonyms: ["obscure", "esoteric"],
        frequency: "advanced",
        level: "C2",
        tags: ["literature", "formal register"],
        chapterSlug: CH15,
      }),
    ],
  ),

  topic(
    {
      slug: "eng-c1-exam",
      level: "C1",
      topic: "Словарь для IELTS и экзаменов",
      topicEs: "IELTS & Exam Vocabulary",
      icon: "🏰",
      chapterSlug: CH16,
    },
    [
      w({
        word: "juxtaposition",
        transcription: "/ˌdʒʌkstəpəˈzɪʃn/",
        partOfSpeech: "noun",
        translation: "сопоставление, juxtaposition",
        examples: [
          "The essay explores the juxtaposition of tradition and modernity.",
          "Juxtaposition of images creates tension in the film review.",
        ],
        commonMistakes: [
          "Formal IELTS word — use 'contrast' if unsure of correct collocation.",
        ],
        synonyms: ["contrast", "comparison"],
        frequency: "advanced",
        level: "C2",
        tags: ["IELTS", "writing"],
        chapterSlug: CH16,
      }),
      w({
        word: "nuanced",
        transcription: "/ˈnjuːɑːnst/",
        partOfSpeech: "adjective",
        translation: "нюансированный, тонкий (о аргументе)",
        examples: [
          "A nuanced argument considers multiple perspectives.",
          "Band 8 writing often presents nuanced views on complex topics.",
        ],
        commonMistakes: [
          "Use 'nuanced understanding/argument/view', not 'nuanced details' awkwardly.",
        ],
        synonyms: ["subtle", "refined"],
        frequency: "advanced",
        level: "C2",
        tags: ["IELTS", "writing"],
        chapterSlug: CH16,
      }),
      w({
        word: "corroborate",
        transcription: "/kəˈrɒbəreɪt/",
        partOfSpeech: "verb",
        translation: "подтверждать, corroborate",
        examples: [
          "Witness statements corroborate the main findings.",
          "Further data corroborated the initial hypothesis.",
        ],
        commonMistakes: [
          "Formal — 'confirm' or 'support' are safer in Speaking.",
        ],
        synonyms: ["confirm", "substantiate"],
        frequency: "advanced",
        level: "C2",
        tags: ["IELTS", "academic"],
        chapterSlug: CH16,
      }),
      w({
        word: "coherent",
        transcription: "/kəʊˈhɪərənt/",
        partOfSpeech: "adjective",
        translation: "связный, логичный, coherent",
        examples: [
          "Your essay must present a coherent line of reasoning.",
          "Coherent paragraphs link ideas with clear transitions.",
        ],
        commonMistakes: [
          "IELTS criteria use 'coherence and cohesion' — learn both terms.",
        ],
        synonyms: ["logical", "consistent"],
        frequency: "common",
        level: "C1",
        tags: ["IELTS", "writing"],
        chapterSlug: CH16,
      }),
      w({
        word: "contentious",
        transcription: "/kənˈtenʃəs/",
        partOfSpeech: "adjective",
        translation: "спорный, вызывающий разногласия",
        examples: [
          "Immigration remains a contentious issue in many countries.",
          "Avoid overly contentious language in Task 2 unless well supported.",
        ],
        commonMistakes: [
          "Use 'contentious issue/topic', not 'contentious problem' (less common).",
        ],
        synonyms: ["controversial", "disputed"],
        frequency: "uncommon",
        level: "C1",
        tags: ["IELTS", "debate"],
        chapterSlug: CH16,
      }),
      w({
        word: "proliferate",
        transcription: "/prəˈlɪfəreɪt/",
        partOfSpeech: "verb",
        translation: "распространяться, proliferate",
        examples: [
          "Online courses have proliferated since 2020.",
          "Misinformation tends to proliferate on social media.",
        ],
        commonMistakes: [
          "Formal — use 'spread quickly' in Speaking Part 1–2.",
        ],
        synonyms: ["multiply", "spread rapidly"],
        frequency: "advanced",
        level: "C2",
        tags: ["IELTS", "formal"],
        chapterSlug: CH16,
      }),
      w({
        word: "undermine",
        transcription: "/ˌʌndəˈmaɪn/",
        partOfSpeech: "verb",
        translation: "подрывать, ослаблять",
        examples: [
          "Constant criticism can undermine a student's confidence.",
          "Poor evidence undermines an otherwise strong argument.",
        ],
        commonMistakes: [
          "Use 'undermine + noun' (trust, authority), not 'undermine to do'.",
        ],
        synonyms: ["weaken", "erode"],
        frequency: "uncommon",
        level: "C1",
        tags: ["IELTS", "argument"],
        chapterSlug: CH16,
      }),
      w({
        word: "comprehensive",
        transcription: "/ˌkɒmprɪˈhensɪv/",
        partOfSpeech: "adjective",
        translation: "всесторонний, comprehensive",
        examples: [
          "A comprehensive review covers all parts of the syllabus.",
          "The report provides a comprehensive analysis of exam trends.",
        ],
        commonMistakes: [
          "Do not confuse with 'comprehensible' (easy to understand).",
        ],
        synonyms: ["thorough", "complete"],
        frequency: "common",
        level: "C1",
        tags: ["IELTS", "academic"],
        chapterSlug: CH16,
      }),
      w({
        word: "outweigh",
        transcription: "/aʊtˈweɪ/",
        partOfSpeech: "verb",
        translation: "перевешивать, outweigh",
        examples: [
          "The benefits outweigh the drawbacks in most cases.",
          "Do the advantages outweigh the disadvantages? — a classic IELTS prompt.",
        ],
        commonMistakes: [
          "Use 'outweigh' without 'more': 'benefits outweigh risks', not 'outweigh more'.",
        ],
        synonyms: ["exceed", "be greater than"],
        frequency: "common",
        level: "C1",
        tags: ["IELTS", "essay"],
        chapterSlug: CH16,
      }),
      w({
        word: "feasible",
        transcription: "/ˈfiːzəbl/",
        partOfSpeech: "adjective",
        translation: "осуществимый, feasible",
        examples: [
          "Is it feasible to finish the project before the exam?",
          "The plan is ambitious but technically feasible.",
        ],
        commonMistakes: [
          "Use 'feasible to + infinitive' or 'feasible for someone'.",
        ],
        synonyms: ["viable", "practicable"],
        frequency: "uncommon",
        level: "C1",
        tags: ["IELTS", "formal"],
        chapterSlug: CH16,
      }),
      w({
        word: "negligible",
        transcription: "/ˈneɡlɪdʒəbl/",
        partOfSpeech: "adjective",
        translation: "незначительный, negligible",
        examples: [
          "The difference in scores was negligible.",
          "IELTS examiners ignore negligible errors if meaning is clear.",
        ],
        commonMistakes: [
          "Means 'so small it can be ignored' — not 'negative'.",
        ],
        synonyms: ["insignificant", "minimal"],
        frequency: "advanced",
        level: "C2",
        tags: ["IELTS", "formal"],
        chapterSlug: CH16,
      }),
      w({
        word: "paramount",
        transcription: "/ˈpærəmaʊnt/",
        partOfSpeech: "adjective",
        translation: "первостепенный, paramount",
        examples: [
          "Accuracy is paramount in IELTS Writing Task 1.",
          "Student welfare is of paramount importance.",
        ],
        commonMistakes: [
          "Use 'of paramount importance', not 'very paramount' (already absolute).",
        ],
        synonyms: ["supreme", "primary"],
        frequency: "advanced",
        level: "C2",
        tags: ["IELTS", "formal"],
        chapterSlug: CH16,
      }),
    ],
  ),
];
