import { w, topic } from "./helpers";
import type { VocabTopic } from "@/types";

export const ENGLISH_VOCAB_A1_A2: VocabTopic[] = [
  topic(
    {
      slug: "eng-a1-personal-info",
      level: "A1",
      topic: "Личная информация",
      topicEs: "Información Personal",
      icon: "👤",
      chapterSlug: "eng-ch1-first-steps",
    },
    [
      w({
        word: "name",
        transcription: "/neɪm/",
        partOfSpeech: "noun",
        translation: "имя",
        examples: [
          "What is your name?",
          "My name is Anna.",
        ],
        commonMistakes: [
          "Не путайте name (имя) и surname (фамилия) — в английском обычно спрашивают оба отдельно.",
        ],
        synonyms: ["first name", "given name"],
        frequency: "core",
        level: "A1",
        tags: ["personal", "identity"],
        chapterSlug: "eng-ch1-first-steps",
      }),
      w({
        word: "surname",
        transcription: "/ˈsɜːrneɪm/",
        partOfSpeech: "noun",
        translation: "фамилия",
        examples: [
          "My surname is Petrova.",
          "Please write your surname in capital letters.",
        ],
        commonMistakes: [
          "Family name и surname — синонимы; last name тоже часто используется в США.",
        ],
        synonyms: ["family name", "last name"],
        frequency: "core",
        level: "A1",
        tags: ["personal", "identity"],
        chapterSlug: "eng-ch1-first-steps",
      }),
      w({
        word: "nationality",
        transcription: "/ˌnæʃəˈnæləti/",
        partOfSpeech: "noun",
        translation: "национальность, гражданство",
        examples: [
          "What is your nationality?",
          "Her nationality is Russian, but she lives in Spain.",
        ],
        commonMistakes: [
          "Nationality описывает гражданство/происхождение, а не язык: Russian, не Russia.",
        ],
        synonyms: ["citizenship"],
        frequency: "common",
        level: "A1",
        tags: ["personal", "identity"],
        chapterSlug: "eng-ch1-first-steps",
      }),
      w({
        word: "address",
        transcription: "/əˈdres/",
        partOfSpeech: "noun",
        translation: "адрес",
        examples: [
          "What is your home address?",
          "Please send the letter to this address.",
        ],
        commonMistakes: [
          "Address — исчисляемое существительное: an address, two addresses.",
        ],
        synonyms: ["location", "residence"],
        frequency: "core",
        level: "A1",
        tags: ["personal", "contact"],
        chapterSlug: "eng-ch1-first-steps",
      }),
      w({
        word: "occupation",
        transcription: "/ˌɒkjʊˈpeɪʃn/",
        partOfSpeech: "noun",
        translation: "род занятий, профессия",
        examples: [
          "What is your occupation?",
          "His occupation is software engineer.",
        ],
        commonMistakes: [
          "Occupation — формальное слово; в разговоре чаще спрашивают What do you do?",
        ],
        synonyms: ["job", "profession"],
        frequency: "common",
        level: "A1",
        tags: ["personal", "work"],
        chapterSlug: "eng-ch1-first-steps",
      }),
      w({
        word: "married",
        transcription: "/ˈmærid/",
        partOfSpeech: "adjective",
        translation: "женатый, замужняя",
        examples: [
          "She is married with two children.",
          "Are you married or single?",
        ],
        commonMistakes: [
          "Married to someone, не married with: She is married to John.",
        ],
        synonyms: ["wed"],
        frequency: "common",
        level: "A1",
        tags: ["personal", "family"],
        chapterSlug: "eng-ch1-first-steps",
      }),
      w({
        word: "single",
        transcription: "/ˈsɪŋɡl/",
        partOfSpeech: "adjective",
        translation: "неженатый, незамужняя",
        examples: [
          "He is single and lives alone.",
          "I'm single, but I'm not looking for a partner.",
        ],
        commonMistakes: [
          "Single описывает семейное положение, а не одиночество: lonely — «одинокий».",
        ],
        synonyms: ["unmarried"],
        frequency: "common",
        level: "A1",
        tags: ["personal", "family"],
        chapterSlug: "eng-ch1-first-steps",
      }),
      w({
        word: "greet",
        transcription: "/ɡriːt/",
        partOfSpeech: "verb",
        translation: "приветствовать",
        examples: [
          "Always greet your teacher in the morning.",
          "She greeted us with a smile.",
        ],
        commonMistakes: [
          "Greet — формальнее, чем say hello; greet someone, не greet to someone.",
        ],
        synonyms: ["welcome", "say hello"],
        frequency: "common",
        level: "A1",
        tags: ["communication", "social"],
        chapterSlug: "eng-ch1-first-steps",
      }),
      w({
        word: "introduce",
        transcription: "/ˌɪntrəˈdjuːs/",
        partOfSpeech: "verb",
        translation: "представлять, знакомить",
        examples: [
          "Let me introduce my colleague.",
          "Nice to meet you — I'll introduce myself: I'm Alex.",
        ],
        commonMistakes: [
          "Introduce someone to someone: Let me introduce you to Maria.",
        ],
        synonyms: ["present"],
        frequency: "core",
        level: "A1",
        tags: ["communication", "social"],
        chapterSlug: "eng-ch1-first-steps",
      }),
      w({
        word: "spell",
        transcription: "/spel/",
        partOfSpeech: "verb",
        translation: "произносить по буквам, писать по буквам",
        examples: [
          "Can you spell your surname, please?",
          "My name is Elena — that's E-L-E-N-A.",
        ],
        commonMistakes: [
          "How do you spell it? — правильный вопрос; не How do you write it?",
        ],
        synonyms: ["write letter by letter"],
        frequency: "common",
        level: "A1",
        tags: ["communication", "forms"],
        chapterSlug: "eng-ch1-first-steps",
      }),
      w({
        word: "age",
        transcription: "/eɪdʒ/",
        partOfSpeech: "noun",
        translation: "возраст",
        examples: [
          "What is your age?",
          "Children under the age of 12 travel free.",
        ],
        commonMistakes: [
          "В разговоре чаще: How old are you? — не What is your age?",
        ],
        synonyms: ["years old"],
        frequency: "core",
        level: "A1",
        tags: ["personal", "identity"],
        chapterSlug: "eng-ch1-first-steps",
      }),
      w({
        word: "email",
        transcription: "/ˈiːmeɪl/",
        partOfSpeech: "noun",
        translation: "электронная почта",
        examples: [
          "What's your email address?",
          "I'll send you the details by email.",
        ],
        commonMistakes: [
          "Email — и email address часто используются вместе; не пишите e-mail с дефисом.",
        ],
        synonyms: ["e-mail", "electronic mail"],
        frequency: "core",
        level: "A1",
        tags: ["personal", "contact"],
        chapterSlug: "eng-ch1-first-steps",
      }),
      w({
        word: "phone number",
        transcription: "/fəʊn ˈnʌmbə(r)/",
        partOfSpeech: "phrase",
        translation: "номер телефона",
        examples: [
          "Can I have your phone number?",
          "My phone number is 07700 900123.",
        ],
        commonMistakes: [
          "Mobile number — мобильный; landline — стационарный телефон.",
        ],
        synonyms: ["telephone number", "mobile number"],
        frequency: "core",
        level: "A1",
        tags: ["personal", "contact"],
        chapterSlug: "eng-ch1-first-steps",
      }),
      w({
        word: "hometown",
        transcription: "/ˈhəʊmtaʊn/",
        partOfSpeech: "noun",
        translation: "родной город",
        examples: [
          "Where is your hometown?",
          "My hometown is a small city in the north of England.",
        ],
        commonMistakes: [
          "Hometown — город, где вы выросли; не обязательно где живёте сейчас.",
        ],
        synonyms: ["home city", "native town"],
        frequency: "common",
        level: "A1",
        tags: ["personal", "places"],
        chapterSlug: "eng-ch1-first-steps",
      }),
    ],
  ),

  topic(
    {
      slug: "eng-a1-everyday-objects",
      level: "A1",
      topic: "Повседневная жизнь и предметы",
      topicEs: "Vida Diaria y Objetos",
      icon: "📚",
      chapterSlug: "eng-ch2-routines",
    },
    [
      w({
        word: "wake up",
        transcription: "/weɪk ʌp/",
        partOfSpeech: "verb",
        translation: "просыпаться",
        examples: [
          "I wake up at seven every day.",
          "Don't wake up the baby!",
        ],
        commonMistakes: [
          "Wake up — проснуться; get up — встать с кровати. Это разные действия.",
        ],
        synonyms: ["get awake", "rise"],
        frequency: "core",
        level: "A1",
        tags: ["routine", "daily"],
        chapterSlug: "eng-ch2-routines",
      }),
      w({
        word: "breakfast",
        transcription: "/ˈbrekfəst/",
        partOfSpeech: "noun",
        translation: "завтрак",
        examples: [
          "I always have breakfast before work.",
          "What do you usually eat for breakfast?",
        ],
        commonMistakes: [
          "Have breakfast, не do breakfast или make breakfast (хотя make — тоже возможно).",
        ],
        synonyms: ["morning meal"],
        frequency: "core",
        level: "A1",
        tags: ["routine", "food"],
        chapterSlug: "eng-ch2-routines",
      }),
      w({
        word: "brush teeth",
        transcription: "/brʌʃ tiːθ/",
        partOfSpeech: "phrase",
        translation: "чистить зубы",
        examples: [
          "I brush my teeth twice a day.",
          "Remember to brush your teeth before bed.",
        ],
        commonMistakes: [
          "Brush my teeth — нужен притяжательный местоимение: my, your, his.",
        ],
        synonyms: ["clean teeth"],
        frequency: "core",
        level: "A1",
        tags: ["routine", "hygiene"],
        chapterSlug: "eng-ch2-routines",
      }),
      w({
        word: "commute",
        transcription: "/kəˈmjuːt/",
        partOfSpeech: "verb",
        translation: "ездить на работу и обратно",
        examples: [
          "I commute to London every day by train.",
          "She commutes for an hour each way.",
        ],
        commonMistakes: [
          "Commute подразумевает регулярную поездку на работу, не разовую поездку.",
        ],
        synonyms: ["travel to work"],
        frequency: "common",
        level: "A1",
        tags: ["routine", "transport"],
        chapterSlug: "eng-ch2-routines",
      }),
      w({
        word: "schedule",
        transcription: "/ˈʃedjuːl/",
        partOfSpeech: "noun",
        translation: "расписание, график",
        examples: [
          "My schedule is very busy this week.",
          "The train schedule is on the wall.",
        ],
        commonMistakes: [
          "В британском английском schedule = /ˈʃedjuːl/; в американском — /ˈskedʒuːl/.",
        ],
        synonyms: ["timetable", "plan"],
        frequency: "common",
        level: "A1",
        tags: ["routine", "time"],
        chapterSlug: "eng-ch2-routines",
      }),
      w({
        word: "alarm clock",
        transcription: "/əˈlɑːm klɒk/",
        partOfSpeech: "noun",
        translation: "будильник",
        examples: [
          "My alarm clock rings at 6:30.",
          "I forgot to set the alarm clock last night.",
        ],
        commonMistakes: [
          "Set the alarm — поставить будильник; turn off the alarm — выключить.",
        ],
        synonyms: ["alarm", "clock"],
        frequency: "common",
        level: "A1",
        tags: ["objects", "time"],
        chapterSlug: "eng-ch2-routines",
      }),
      w({
        word: "notebook",
        transcription: "/ˈnəʊtbʊk/",
        partOfSpeech: "noun",
        translation: "тетрадь, блокнот",
        examples: [
          "Write the new words in your notebook.",
          "I always carry a notebook to class.",
        ],
        commonMistakes: [
          "Notebook — бумажная тетрадь; laptop — переносной компьютер.",
        ],
        synonyms: ["notepad", "exercise book"],
        frequency: "common",
        level: "A1",
        tags: ["objects", "school"],
        chapterSlug: "eng-ch2-routines",
      }),
      w({
        word: "laptop",
        transcription: "/ˈlæptɒp/",
        partOfSpeech: "noun",
        translation: "ноутбук",
        examples: [
          "I work on my laptop at the café.",
          "Don't forget to charge your laptop.",
        ],
        commonMistakes: [
          "Laptop и notebook computer — синонимы; notebook alone — тетрадь.",
        ],
        synonyms: ["notebook computer", "portable computer"],
        frequency: "core",
        level: "A1",
        tags: ["objects", "technology"],
        chapterSlug: "eng-ch2-routines",
      }),
      w({
        word: "umbrella",
        transcription: "/ʌmˈbrelə/",
        partOfSpeech: "noun",
        translation: "зонт",
        examples: [
          "Take an umbrella — it's going to rain.",
          "I left my umbrella on the bus.",
        ],
        commonMistakes: [
          "An umbrella — для дождя; a parasol — от солнца.",
        ],
        synonyms: ["parasol", "brolly"],
        frequency: "common",
        level: "A1",
        tags: ["objects", "weather"],
        chapterSlug: "eng-ch2-routines",
      }),
      w({
        word: "wallet",
        transcription: "/ˈwɒlɪt/",
        partOfSpeech: "noun",
        translation: "кошелёк",
        examples: [
          "I can't find my wallet anywhere.",
          "He kept his ID in his wallet.",
        ],
        commonMistakes: [
          "Wallet — для денег и карт; purse — дамская сумочка (BrE) или кошелёк (AmE).",
        ],
        synonyms: ["purse", "billfold"],
        frequency: "common",
        level: "A1",
        tags: ["objects", "daily"],
        chapterSlug: "eng-ch2-routines",
      }),
      w({
        word: "keys",
        transcription: "/kiːz/",
        partOfSpeech: "noun",
        translation: "ключи",
        examples: [
          "Where are my keys?",
          "Don't forget your keys when you leave.",
        ],
        commonMistakes: [
          "Keys — всегда множественное число, когда речь о связке ключей.",
        ],
        synonyms: ["key ring"],
        frequency: "core",
        level: "A1",
        tags: ["objects", "daily"],
        chapterSlug: "eng-ch2-routines",
      }),
      w({
        word: "habit",
        transcription: "/ˈhæbɪt/",
        partOfSpeech: "noun",
        translation: "привычка",
        examples: [
          "Reading before bed is a good habit.",
          "Smoking is a bad habit.",
        ],
        commonMistakes: [
          "Habit of doing something: the habit of waking up early.",
        ],
        synonyms: ["routine", "custom"],
        frequency: "common",
        level: "A1",
        tags: ["routine", "behaviour"],
        chapterSlug: "eng-ch2-routines",
      }),
      w({
        word: "usually",
        transcription: "/ˈjuːʒuəli/",
        partOfSpeech: "adverb",
        translation: "обычно",
        examples: [
          "I usually take the bus to work.",
          "She usually drinks tea in the morning.",
        ],
        commonMistakes: [
          "Usually стоит перед основным глаголом, но после глагола to be.",
        ],
        synonyms: ["normally", "generally"],
        frequency: "core",
        level: "A1",
        tags: ["frequency", "adverbs"],
        chapterSlug: "eng-ch2-routines",
      }),
      w({
        word: "rarely",
        transcription: "/ˈreəli/",
        partOfSpeech: "adverb",
        translation: "редко",
        examples: [
          "I rarely eat fast food.",
          "He rarely arrives on time.",
        ],
        commonMistakes: [
          "Rarely уже отрицает — не добавляйте don't: I rarely go, не I don't rarely go.",
        ],
        synonyms: ["seldom", "hardly ever"],
        frequency: "common",
        level: "A1",
        tags: ["frequency", "adverbs"],
        chapterSlug: "eng-ch2-routines",
      }),
    ],
  ),

  topic(
    {
      slug: "eng-a1-places-town",
      level: "A1",
      topic: "Места в городе",
      topicEs: "Lugares de la Ciudad",
      icon: "🏙️",
      chapterSlug: "eng-ch3-around-town",
    },
    [
      w({
        word: "bank",
        transcription: "/bæŋk/",
        partOfSpeech: "noun",
        translation: "банк",
        examples: [
          "The bank closes at five o'clock.",
          "I need to go to the bank to withdraw money.",
        ],
        commonMistakes: [
          "Go to the bank — с артиклем the, когда речь о конкретном банке.",
        ],
        synonyms: ["financial institution"],
        frequency: "core",
        level: "A1",
        tags: ["places", "services"],
        chapterSlug: "eng-ch3-around-town",
      }),
      w({
        word: "pharmacy",
        transcription: "/ˈfɑːməsi/",
        partOfSpeech: "noun",
        translation: "аптека",
        examples: [
          "Is there a pharmacy near here?",
          "You can buy medicine at the pharmacy.",
        ],
        commonMistakes: [
          "Pharmacy (AmE) = chemist's (BrE) — оба означают аптеку.",
        ],
        synonyms: ["chemist's", "drugstore"],
        frequency: "core",
        level: "A1",
        tags: ["places", "health"],
        chapterSlug: "eng-ch3-around-town",
      }),
      w({
        word: "post office",
        transcription: "/pəʊst ˈɒfɪs/",
        partOfSpeech: "noun",
        translation: "почта, почтовое отделение",
        examples: [
          "The post office is on Main Street.",
          "I sent the package from the post office.",
        ],
        commonMistakes: [
          "Post office — два слова; не postoffice одним словом.",
        ],
        synonyms: ["mail office"],
        frequency: "common",
        level: "A1",
        tags: ["places", "services"],
        chapterSlug: "eng-ch3-around-town",
      }),
      w({
        word: "supermarket",
        transcription: "/ˈsuːpəmɑːkɪt/",
        partOfSpeech: "noun",
        translation: "супермаркет",
        examples: [
          "We buy food at the supermarket every Saturday.",
          "The supermarket opens at eight.",
        ],
        commonMistakes: [
          "Supermarket — большой магазин; corner shop — небольшой магазин у дома.",
        ],
        synonyms: ["grocery store", "hypermarket"],
        frequency: "core",
        level: "A1",
        tags: ["places", "shopping"],
        chapterSlug: "eng-ch3-around-town",
      }),
      w({
        word: "roundabout",
        transcription: "/ˈraʊndəbaʊt/",
        partOfSpeech: "noun",
        translation: "круговое движение, кольцо",
        examples: [
          "Take the second exit at the roundabout.",
          "There is a roundabout at the end of this road.",
        ],
        commonMistakes: [
          "At the roundabout — на кольце; in the UK круговое движение очень распространено.",
        ],
        synonyms: ["traffic circle", "rotary"],
        frequency: "common",
        level: "A1",
        tags: ["places", "transport"],
        chapterSlug: "eng-ch3-around-town",
      }),
      w({
        word: "corner",
        transcription: "/ˈkɔːnə(r)/",
        partOfSpeech: "noun",
        translation: "угол (улицы)",
        examples: [
          "The café is on the corner of High Street and Park Road.",
          "Turn left at the corner.",
        ],
        commonMistakes: [
          "On the corner — на углу; around the corner — за углом, рядом.",
        ],
        synonyms: ["street corner"],
        frequency: "core",
        level: "A1",
        tags: ["places", "directions"],
        chapterSlug: "eng-ch3-around-town",
      }),
      w({
        word: "opposite",
        transcription: "/ˈɒpəzɪt/",
        partOfSpeech: "preposition",
        translation: "напротив",
        examples: [
          "The bank is opposite the supermarket.",
          "We sat opposite each other.",
        ],
        commonMistakes: [
          "Opposite — без of: opposite the bank, не opposite of the bank.",
        ],
        synonyms: ["across from", "facing"],
        frequency: "core",
        level: "A1",
        tags: ["directions", "prepositions"],
        chapterSlug: "eng-ch3-around-town",
      }),
      w({
        word: "between",
        transcription: "/bɪˈtwiːn/",
        partOfSpeech: "preposition",
        translation: "между",
        examples: [
          "The pharmacy is between the bank and the post office.",
          "Sit between Tom and Anna.",
        ],
        commonMistakes: [
          "Between — для двух объектов; among — для трёх и более.",
        ],
        synonyms: ["in the middle of"],
        frequency: "core",
        level: "A1",
        tags: ["directions", "prepositions"],
        chapterSlug: "eng-ch3-around-town",
      }),
      w({
        word: "nearby",
        transcription: "/ˌnɪəˈbaɪ/",
        partOfSpeech: "adverb",
        translation: "рядом, поблизости",
        examples: [
          "Is there a café nearby?",
          "We found a hotel nearby.",
        ],
        commonMistakes: [
          "Nearby может быть и прилагательным: a nearby café.",
        ],
        synonyms: ["close by", "near"],
        frequency: "common",
        level: "A1",
        tags: ["directions", "places"],
        chapterSlug: "eng-ch3-around-town",
      }),
      w({
        word: "pedestrian",
        transcription: "/pəˈdestriən/",
        partOfSpeech: "noun",
        translation: "пешеход",
        examples: [
          "Pedestrians must use the crossing.",
          "The city centre is closed to cars — only pedestrians.",
        ],
        commonMistakes: [
          "Pedestrian crossing — пешеходный переход; zebra crossing — «зебра».",
        ],
        synonyms: ["walker", "foot traveller"],
        frequency: "common",
        level: "A1",
        tags: ["transport", "safety"],
        chapterSlug: "eng-ch3-around-town",
      }),
      w({
        word: "crossroads",
        transcription: "/ˈkrɒsrəʊdz/",
        partOfSpeech: "noun",
        translation: "перекрёсток",
        examples: [
          "Turn right at the crossroads.",
          "The accident happened at a busy crossroads.",
        ],
        commonMistakes: [
          "Crossroads — обычно единственное число: a crossroads, the crossroads.",
        ],
        synonyms: ["intersection", "junction"],
        frequency: "common",
        level: "A1",
        tags: ["places", "directions"],
        chapterSlug: "eng-ch3-around-town",
      }),
      w({
        word: "town hall",
        transcription: "/taʊn hɔːl/",
        partOfSpeech: "noun",
        translation: "ратуша, мэрия",
        examples: [
          "The town hall is in the city centre.",
          "We got married at the town hall.",
        ],
        commonMistakes: [
          "Town hall — административное здание; city hall — то же в крупных городах.",
        ],
        synonyms: ["city hall", "municipal building"],
        frequency: "uncommon",
        level: "A1",
        tags: ["places", "government"],
        chapterSlug: "eng-ch3-around-town",
      }),
      w({
        word: "ATM",
        transcription: "/ˌeɪ tiː ˈem/",
        partOfSpeech: "noun",
        translation: "банкомат",
        examples: [
          "There's an ATM inside the bank.",
          "I withdrew cash from the ATM.",
        ],
        commonMistakes: [
          "Cash machine (BrE) и ATM (AmE) — одно и то же.",
        ],
        synonyms: ["cash machine", "cashpoint"],
        frequency: "core",
        level: "A1",
        tags: ["places", "money"],
        chapterSlug: "eng-ch3-around-town",
      }),
      w({
        word: "parking",
        transcription: "/ˈpɑːkɪŋ/",
        partOfSpeech: "noun",
        translation: "парковка",
        examples: [
          "Is there parking near the supermarket?",
          "Parking is free on Sundays.",
        ],
        commonMistakes: [
          "Parking — неисчисляемое: parking is available, не a parking.",
        ],
        synonyms: ["car park", "parking lot"],
        frequency: "common",
        level: "A1",
        tags: ["places", "transport"],
        chapterSlug: "eng-ch3-around-town",
      }),
    ],
  ),

  topic(
    {
      slug: "eng-a2-travel",
      level: "A2",
      topic: "Путешествия и прошлые события",
      topicEs: "Viajes y Eventos del Pasado",
      icon: "✈️",
      chapterSlug: "eng-ch4-past-stories",
    },
    [
      w({
        word: "departure",
        transcription: "/dɪˈpɑːtʃə(r)/",
        partOfSpeech: "noun",
        translation: "отправление, отбытие",
        examples: [
          "The departure time is 10:45.",
          "We arrived at the airport two hours before departure.",
        ],
        commonMistakes: [
          "Departure — отправление; arrival — прибытие. Не путайте эти пары.",
        ],
        synonyms: ["leaving", "take-off"],
        frequency: "common",
        level: "A2",
        tags: ["travel", "transport"],
        chapterSlug: "eng-ch4-past-stories",
      }),
      w({
        word: "arrival",
        transcription: "/əˈraɪvl/",
        partOfSpeech: "noun",
        translation: "прибытие",
        examples: [
          "The arrival gate is on the left.",
          "On arrival, we took a taxi to the hotel.",
        ],
        commonMistakes: [
          "On arrival — по прибытии; at arrival — реже используется.",
        ],
        synonyms: ["coming", "landing"],
        frequency: "common",
        level: "A2",
        tags: ["travel", "transport"],
        chapterSlug: "eng-ch4-past-stories",
      }),
      w({
        word: "delay",
        transcription: "/dɪˈleɪ/",
        partOfSpeech: "noun",
        translation: "задержка",
        examples: [
          "There was a two-hour delay at the airport.",
          "Sorry for the delay — the train is late.",
        ],
        commonMistakes: [
          "Delay — существительное; delayed — прилагательное: a delayed flight.",
        ],
        synonyms: ["hold-up", "postponement"],
        frequency: "common",
        level: "A2",
        tags: ["travel", "problems"],
        chapterSlug: "eng-ch4-past-stories",
      }),
      w({
        word: "boarding pass",
        transcription: "/ˈbɔːdɪŋ pɑːs/",
        partOfSpeech: "noun",
        translation: "посадочный талон",
        examples: [
          "Show your boarding pass at the gate.",
          "I downloaded my boarding pass on my phone.",
        ],
        commonMistakes: [
          "Boarding pass — для посадки; ticket — билет на рейс. Это разные документы.",
        ],
        synonyms: ["boarding card", "e-ticket"],
        frequency: "common",
        level: "A2",
        tags: ["travel", "airport"],
        chapterSlug: "eng-ch4-past-stories",
      }),
      w({
        word: "customs",
        transcription: "/ˈkʌstəmz/",
        partOfSpeech: "noun",
        translation: "таможня",
        examples: [
          "We went through customs after landing.",
          "Do you have anything to declare at customs?",
        ],
        commonMistakes: [
          "Customs — всегда множественное число; go through customs.",
        ],
        synonyms: ["border control", "immigration"],
        frequency: "common",
        level: "A2",
        tags: ["travel", "airport"],
        chapterSlug: "eng-ch4-past-stories",
      }),
      w({
        word: "luggage",
        transcription: "/ˈlʌɡɪdʒ/",
        partOfSpeech: "noun",
        translation: "багаж",
        examples: [
          "My luggage was lost at the airport.",
          "How much luggage can I take on the plane?",
        ],
        commonMistakes: [
          "Luggage — неисчисляемое; baggage — синоним. Suitcases — чемоданы.",
        ],
        synonyms: ["baggage", "suitcases"],
        frequency: "core",
        level: "A2",
        tags: ["travel", "airport"],
        chapterSlug: "eng-ch4-past-stories",
      }),
      w({
        word: "sightseeing",
        transcription: "/ˈsaɪtsiːɪŋ/",
        partOfSpeech: "noun",
        translation: "осмотр достопримечательностей",
        examples: [
          "We went sightseeing in York yesterday.",
          "Sightseeing in London takes at least three days.",
        ],
        commonMistakes: [
          "Go sightseeing — без артикля; do sightseeing — тоже возможно.",
        ],
        synonyms: ["touring", "visiting sights"],
        frequency: "common",
        level: "A2",
        tags: ["travel", "tourism"],
        chapterSlug: "eng-ch4-past-stories",
      }),
      w({
        word: "souvenir",
        transcription: "/ˌsuːvəˈnɪə(r)/",
        partOfSpeech: "noun",
        translation: "сувенир",
        examples: [
          "I bought a souvenir for my friend.",
          "The shop sells souvenirs from Scotland.",
        ],
        commonMistakes: [
          "Souvenir from a place: a souvenir from Edinburgh.",
        ],
        synonyms: ["memento", "keepsake"],
        frequency: "common",
        level: "A2",
        tags: ["travel", "shopping"],
        chapterSlug: "eng-ch4-past-stories",
      }),
      w({
        word: "booked",
        transcription: "/bʊkt/",
        partOfSpeech: "adjective",
        translation: "забронированный",
        examples: [
          "We booked a hotel near the station.",
          "I booked my flight online last week.",
        ],
        commonMistakes: [
          "Booked — past participle: I have booked / I booked. Не I have book.",
        ],
        synonyms: ["reserved", "scheduled"],
        frequency: "core",
        level: "A2",
        tags: ["travel", "past"],
        chapterSlug: "eng-ch4-past-stories",
      }),
      w({
        word: "cancelled",
        transcription: "/ˈkænsəld/",
        partOfSpeech: "adjective",
        translation: "отменённый",
        examples: [
          "Our flight was cancelled because of the storm.",
          "The concert was cancelled at the last minute.",
        ],
        commonMistakes: [
          "BrE: cancelled (две l); AmE: canceled (одна l).",
        ],
        synonyms: ["called off", "aborted"],
        frequency: "common",
        level: "A2",
        tags: ["travel", "past"],
        chapterSlug: "eng-ch4-past-stories",
      }),
      w({
        word: "missed",
        transcription: "/mɪst/",
        partOfSpeech: "adjective",
        translation: "пропущенный (рейс, поезд)",
        examples: [
          "We missed the train and had to wait an hour.",
          "I missed my flight because of traffic.",
        ],
        commonMistakes: [
          "Miss the bus/train — опоздать; lose — потерять (ключи, багаж).",
        ],
        synonyms: ["failed to catch"],
        frequency: "common",
        level: "A2",
        tags: ["travel", "past"],
        chapterSlug: "eng-ch4-past-stories",
      }),
      w({
        word: "delayed",
        transcription: "/dɪˈleɪd/",
        partOfSpeech: "adjective",
        translation: "задержанный",
        examples: [
          "The delayed flight finally departed at midnight.",
          "Our train was delayed by forty minutes.",
        ],
        commonMistakes: [
          "Delayed by + время: delayed by two hours.",
        ],
        synonyms: ["late", "held up"],
        frequency: "common",
        level: "A2",
        tags: ["travel", "problems"],
        chapterSlug: "eng-ch4-past-stories",
      }),
      w({
        word: "platform",
        transcription: "/ˈplætfɔːm/",
        partOfSpeech: "noun",
        translation: "платформа (на вокзале)",
        examples: [
          "The train to Edinburgh leaves from platform 4.",
          "Wait on the platform until the train arrives.",
        ],
        commonMistakes: [
          "Platform — на вокзале; gate — в аэропорту.",
        ],
        synonyms: ["track", "departure point"],
        frequency: "core",
        level: "A2",
        tags: ["travel", "transport"],
        chapterSlug: "eng-ch4-past-stories",
      }),
      w({
        word: "itinerary",
        transcription: "/aɪˈtɪnərəri/",
        partOfSpeech: "noun",
        translation: "маршрут, план поездки",
        examples: [
          "Our itinerary includes three cities in one week.",
          "The travel agent sent us a detailed itinerary.",
        ],
        commonMistakes: [
          "Itinerary — план по дням; route — географический маршрут.",
        ],
        synonyms: ["schedule", "travel plan"],
        frequency: "uncommon",
        level: "A2",
        tags: ["travel", "planning"],
        chapterSlug: "eng-ch4-past-stories",
      }),
    ],
  ),

  topic(
    {
      slug: "eng-a2-shopping",
      level: "A2",
      topic: "Покупки и сравнения",
      topicEs: "Compras y Comparaciones",
      icon: "🛒",
      chapterSlug: "eng-ch5-choices",
    },
    [
      w({
        word: "bargain",
        transcription: "/ˈbɑːɡən/",
        partOfSpeech: "noun",
        translation: "выгодная покупка, сделка",
        examples: [
          "This jacket was a real bargain — only £20!",
          "I love finding bargains in the sales.",
        ],
        commonMistakes: [
          "A bargain — хорошая цена; expensive — дорого. Не путайте с discount.",
        ],
        synonyms: ["good deal", "steal"],
        frequency: "common",
        level: "A2",
        tags: ["shopping", "money"],
        chapterSlug: "eng-ch5-choices",
      }),
      w({
        word: "refund",
        transcription: "/ˈriːfʌnd/",
        partOfSpeech: "noun",
        translation: "возврат денег",
        examples: [
          "Can I get a refund if the shoes don't fit?",
          "The shop gave me a full refund.",
        ],
        commonMistakes: [
          "Refund (сущ.) /rˈiːfʌnd/; refund (гл.) /rɪˈfʌnd/ — ударение меняется.",
        ],
        synonyms: ["money back", "reimbursement"],
        frequency: "common",
        level: "A2",
        tags: ["shopping", "money"],
        chapterSlug: "eng-ch5-choices",
      }),
      w({
        word: "discount",
        transcription: "/ˈdɪskaʊnt/",
        partOfSpeech: "noun",
        translation: "скидка",
        examples: [
          "Students get a 10% discount.",
          "Is there a discount on this coat?",
        ],
        commonMistakes: [
          "Discount on something: a discount on electronics.",
        ],
        synonyms: ["reduction", "markdown"],
        frequency: "core",
        level: "A2",
        tags: ["shopping", "money"],
        chapterSlug: "eng-ch5-choices",
      }),
      w({
        word: "fitting room",
        transcription: "/ˈfɪtɪŋ ruːm/",
        partOfSpeech: "noun",
        translation: "примерочная",
        examples: [
          "The fitting rooms are at the back of the shop.",
          "Can I use the fitting room, please?",
        ],
        commonMistakes: [
          "Fitting room (BrE) = changing room — оба варианта правильны.",
        ],
        synonyms: ["changing room", "dressing room"],
        frequency: "common",
        level: "A2",
        tags: ["shopping", "clothes"],
        chapterSlug: "eng-ch5-choices",
      }),
      w({
        word: "cash register",
        transcription: "/kæʃ ˈredʒɪstə(r)/",
        partOfSpeech: "noun",
        translation: "касса",
        examples: [
          "Pay at the cash register near the exit.",
          "The cash register wasn't working, so we paid by card.",
        ],
        commonMistakes: [
          "Till (BrE) — разговорное слово для кассы.",
        ],
        synonyms: ["till", "checkout counter"],
        frequency: "common",
        level: "A2",
        tags: ["shopping", "money"],
        chapterSlug: "eng-ch5-choices",
      }),
      w({
        word: "receipt",
        transcription: "/rɪˈsiːt/",
        partOfSpeech: "noun",
        translation: "чек",
        examples: [
          "Keep the receipt in case you want to return it.",
          "Can I have a receipt, please?",
        ],
        commonMistakes: [
          "Receipt — чек; recipe — рецепт. Произношение разное!",
        ],
        synonyms: ["proof of purchase", "slip"],
        frequency: "core",
        level: "A2",
        tags: ["shopping", "money"],
        chapterSlug: "eng-ch5-choices",
      }),
      w({
        word: "cheaper",
        transcription: "/ˈtʃiːpə(r)/",
        partOfSpeech: "adjective",
        translation: "дешевле",
        examples: [
          "This phone is cheaper than the one in the other shop.",
          "It's cheaper to buy online.",
        ],
        commonMistakes: [
          "Cheaper than, не cheaper from: cheaper than the original price.",
        ],
        synonyms: ["less expensive", "more affordable"],
        frequency: "core",
        level: "A2",
        tags: ["shopping", "comparisons"],
        chapterSlug: "eng-ch5-choices",
      }),
      w({
        word: "more expensive",
        transcription: "/mɔː(r) ɪkˈspensɪv/",
        partOfSpeech: "phrase",
        translation: "дороже",
        examples: [
          "Organic food is more expensive than regular food.",
          "This brand is more expensive, but the quality is better.",
        ],
        commonMistakes: [
          "More expensive — сравнительная степень от expensive; не expensiver.",
        ],
        synonyms: ["costlier", "pricier"],
        frequency: "core",
        level: "A2",
        tags: ["shopping", "comparisons"],
        chapterSlug: "eng-ch5-choices",
      }),
      w({
        word: "the best",
        transcription: "/ðə best/",
        partOfSpeech: "phrase",
        translation: "лучший",
        examples: [
          "This is the best coffee in town.",
          "She always buys the best quality she can afford.",
        ],
        commonMistakes: [
          "The best — превосходная степень; good → better → the best.",
        ],
        synonyms: ["the finest", "top-quality"],
        frequency: "core",
        level: "A2",
        tags: ["shopping", "comparisons"],
        chapterSlug: "eng-ch5-choices",
      }),
      w({
        word: "bargain hunter",
        transcription: "/ˈbɑːɡən ˌhʌntə(r)/",
        partOfSpeech: "noun",
        translation: "любитель выгодных покупок",
        examples: [
          "My mum is a real bargain hunter — she never pays full price.",
          "Bargain hunters queue early on the first day of the sale.",
        ],
        commonMistakes: [
          "Bargain hunter — устойчивое выражение; hunter alone — «охотник».",
        ],
        synonyms: ["deal seeker", "smart shopper"],
        frequency: "uncommon",
        level: "A2",
        tags: ["shopping", "people"],
        chapterSlug: "eng-ch5-choices",
      }),
      w({
        word: "exchange",
        transcription: "/ɪksˈtʃeɪndʒ/",
        partOfSpeech: "verb",
        translation: "обменять, заменить (товар)",
        examples: [
          "Can I exchange this shirt for a larger size?",
          "She exchanged the broken lamp for a new one.",
        ],
        commonMistakes: [
          "Exchange for — обменять на; return — вернуть и получить деньги.",
        ],
        synonyms: ["swap", "replace"],
        frequency: "common",
        level: "A2",
        tags: ["shopping", "returns"],
        chapterSlug: "eng-ch5-choices",
      }),
      w({
        word: "warranty",
        transcription: "/ˈwɒrənti/",
        partOfSpeech: "noun",
        translation: "гарантия",
        examples: [
          "The laptop comes with a two-year warranty.",
          "Is the repair covered by the warranty?",
        ],
        commonMistakes: [
          "Under warranty — по гарантии; guarantee — близкий синоним.",
        ],
        synonyms: ["guarantee", "assurance"],
        frequency: "common",
        level: "A2",
        tags: ["shopping", "products"],
        chapterSlug: "eng-ch5-choices",
      }),
      w({
        word: "brand",
        transcription: "/brænd/",
        partOfSpeech: "noun",
        translation: "бренд, марка",
        examples: [
          "Which brand of trainers do you prefer?",
          "Famous brands are often more expensive.",
        ],
        commonMistakes: [
          "Brand — марка товара; make — тоже «марка» (What make is your car?).",
        ],
        synonyms: ["make", "label"],
        frequency: "common",
        level: "A2",
        tags: ["shopping", "products"],
        chapterSlug: "eng-ch5-choices",
      }),
      w({
        word: "checkout",
        transcription: "/ˈtʃekaʊt/",
        partOfSpeech: "noun",
        translation: "касса (зона оплаты)",
        examples: [
          "There was a long queue at the checkout.",
          "Self-checkout machines are popular in supermarkets.",
        ],
        commonMistakes: [
          "Checkout — зона оплаты; cash register — сама касса (аппарат).",
        ],
        synonyms: ["till", "pay point"],
        frequency: "core",
        level: "A2",
        tags: ["shopping", "money"],
        chapterSlug: "eng-ch5-choices",
      }),
    ],
  ),

  topic(
    {
      slug: "eng-a2-technology",
      level: "A2",
      topic: "Технологии и современная жизнь",
      topicEs: "Tecnología y Vida Moderna",
      icon: "📱",
      chapterSlug: "eng-ch6-experiences",
    },
    [
      w({
        word: "smartphone",
        transcription: "/ˈsmɑːtfəʊn/",
        partOfSpeech: "noun",
        translation: "смартфон",
        examples: [
          "I use my smartphone for everything — maps, email, photos.",
          "Most teenagers have a smartphone.",
        ],
        commonMistakes: [
          "Smartphone — одно слово; mobile phone — более общее.",
        ],
        synonyms: ["mobile phone", "cell phone"],
        frequency: "core",
        level: "A2",
        tags: ["technology", "devices"],
        chapterSlug: "eng-ch6-experiences",
      }),
      w({
        word: "app",
        transcription: "/æp/",
        partOfSpeech: "noun",
        translation: "приложение",
        examples: [
          "Download the app to track your progress.",
          "There is an app for learning English.",
        ],
        commonMistakes: [
          "App — сокращение от application; download an app, не load an app.",
        ],
        synonyms: ["application", "program"],
        frequency: "core",
        level: "A2",
        tags: ["technology", "software"],
        chapterSlug: "eng-ch6-experiences",
      }),
      w({
        word: "update",
        transcription: "/ʌpˈdeɪt/",
        partOfSpeech: "noun",
        translation: "обновление",
        examples: [
          "Install the latest update for your phone.",
          "The app update fixed several bugs.",
        ],
        commonMistakes: [
          "Update (сущ.) /ˈʌpdeɪt/; update (гл.) /ʌpˈdeɪt/ — ударение смещается.",
        ],
        synonyms: ["upgrade", "patch"],
        frequency: "core",
        level: "A2",
        tags: ["technology", "software"],
        chapterSlug: "eng-ch6-experiences",
      }),
      w({
        word: "Wi-Fi",
        transcription: "/ˈwaɪ faɪ/",
        partOfSpeech: "noun",
        translation: "беспроводной интернет",
        examples: [
          "What's the Wi-Fi password?",
          "The café offers free Wi-Fi for customers.",
        ],
        commonMistakes: [
          "Wi-Fi — неисчисляемое; connect to Wi-Fi, не connect Wi-Fi.",
        ],
        synonyms: ["wireless internet", "WLAN"],
        frequency: "core",
        level: "A2",
        tags: ["technology", "internet"],
        chapterSlug: "eng-ch6-experiences",
      }),
      w({
        word: "streaming",
        transcription: "/ˈstriːmɪŋ/",
        partOfSpeech: "noun",
        translation: "стриминг, потоковая передача",
        examples: [
          "Streaming films is cheaper than buying DVDs.",
          "Music streaming services are very popular.",
        ],
        commonMistakes: [
          "Stream (гл.) — смотреть/слушать онлайн; streaming — процесс.",
        ],
        synonyms: ["live broadcast", "on-demand viewing"],
        frequency: "common",
        level: "A2",
        tags: ["technology", "media"],
        chapterSlug: "eng-ch6-experiences",
      }),
      w({
        word: "subscription",
        transcription: "/səbˈskrɪpʃn/",
        partOfSpeech: "noun",
        translation: "подписка",
        examples: [
          "I cancelled my music subscription last month.",
          "The app requires a monthly subscription.",
        ],
        commonMistakes: [
          "Subscription to a service: a subscription to Netflix.",
        ],
        synonyms: ["membership", "plan"],
        frequency: "common",
        level: "A2",
        tags: ["technology", "money"],
        chapterSlug: "eng-ch6-experiences",
      }),
      w({
        word: "notification",
        transcription: "/ˌnəʊtɪfɪˈkeɪʃn/",
        partOfSpeech: "noun",
        translation: "уведомление",
        examples: [
          "I turned off notifications at night.",
          "You will receive a notification when the package arrives.",
        ],
        commonMistakes: [
          "Notification — уведомление на экране; notice — объявление, заметка.",
        ],
        synonyms: ["alert", "message"],
        frequency: "common",
        level: "A2",
        tags: ["technology", "communication"],
        chapterSlug: "eng-ch6-experiences",
      }),
      w({
        word: "backup",
        transcription: "/ˈbækʌp/",
        partOfSpeech: "noun",
        translation: "резервная копия",
        examples: [
          "Always make a backup of your photos.",
          "The backup saved all my files after the crash.",
        ],
        commonMistakes: [
          "Backup (сущ.) /ˈbækʌp/; back up (гл.) /bæk ˈʌp/ — два слова.",
        ],
        synonyms: ["copy", "archive"],
        frequency: "common",
        level: "A2",
        tags: ["technology", "data"],
        chapterSlug: "eng-ch6-experiences",
      }),
      w({
        word: "cloud",
        transcription: "/klaʊd/",
        partOfSpeech: "noun",
        translation: "облако (облачное хранилище)",
        examples: [
          "I store my documents in the cloud.",
          "Cloud storage is convenient when you travel.",
        ],
        commonMistakes: [
          "The cloud — облачное хранилище; a cloud — облако в небе.",
        ],
        synonyms: ["cloud storage", "online storage"],
        frequency: "common",
        level: "A2",
        tags: ["technology", "data"],
        chapterSlug: "eng-ch6-experiences",
      }),
      w({
        word: "gadget",
        transcription: "/ˈɡædʒɪt/",
        partOfSpeech: "noun",
        translation: "гаджет, устройство",
        examples: [
          "He loves buying the latest gadgets.",
          "Smart watches are popular gadgets.",
        ],
        commonMistakes: [
          "Gadget — разговорное; device — более нейтральное.",
        ],
        synonyms: ["device", "tool"],
        frequency: "common",
        level: "A2",
        tags: ["technology", "devices"],
        chapterSlug: "eng-ch6-experiences",
      }),
      w({
        word: "online",
        transcription: "/ˌɒnˈlaɪn/",
        partOfSpeech: "adjective",
        translation: "онлайн, в интернете",
        examples: [
          "I do most of my shopping online.",
          "Are you online right now?",
        ],
        commonMistakes: [
          "Online — без the: shop online, не shop on the online.",
        ],
        synonyms: ["on the internet", "connected"],
        frequency: "core",
        level: "A2",
        tags: ["technology", "internet"],
        chapterSlug: "eng-ch6-experiences",
      }),
      w({
        word: "offline",
        transcription: "/ˌɒfˈlaɪn/",
        partOfSpeech: "adjective",
        translation: "офлайн, без интернета",
        examples: [
          "You can download videos to watch offline.",
          "The app works offline too.",
        ],
        commonMistakes: [
          "Go offline — отключиться; online — подключиться.",
        ],
        synonyms: ["disconnected", "without internet"],
        frequency: "common",
        level: "A2",
        tags: ["technology", "internet"],
        chapterSlug: "eng-ch6-experiences",
      }),
      w({
        word: "password",
        transcription: "/ˈpɑːswɜːd/",
        partOfSpeech: "noun",
        translation: "пароль",
        examples: [
          "Choose a strong password with numbers and symbols.",
          "I forgot my password and had to reset it.",
        ],
        commonMistakes: [
          "Password — одно слово; passcode — PIN-код.",
        ],
        synonyms: ["passcode", "PIN"],
        frequency: "core",
        level: "A2",
        tags: ["technology", "security"],
        chapterSlug: "eng-ch6-experiences",
      }),
      w({
        word: "cybersecurity",
        transcription: "/ˌsaɪbəsɪˈkjʊərəti/",
        partOfSpeech: "noun",
        translation: "кибербезопасность",
        examples: [
          "Cybersecurity is important for every business.",
          "Learn basic cybersecurity to protect your accounts.",
        ],
        commonMistakes: [
          "Cybersecurity — одно слово; cyber security — тоже встречается.",
        ],
        synonyms: ["information security", "digital safety"],
        frequency: "uncommon",
        level: "A2",
        tags: ["technology", "security"],
        chapterSlug: "eng-ch6-experiences",
      }),
    ],
  ),
];
