/** Hand-crafted supplements — generated by scripts/build-curated-supplements.mjs */
export const ENGLISH_CURATED_SUPPLEMENTS = {
  "eng-ch4-past-stories": [
    {
      "type": "translation",
      "question": "Вчера я ходил в музей.",
      "answer": "I went to the museum yesterday",
      "instruction": "Past simple",
      "explanation": "go → went. I went to the museum."
    },
    {
      "type": "translation",
      "question": "Она не пришла на встречу.",
      "answer": "She didn't come to the meeting",
      "instruction": "Past simple negative",
      "explanation": "didn't + base verb."
    },
    {
      "type": "translation",
      "question": "Мы смотрели фильм вчера вечером.",
      "answer": "We watched a film last night",
      "instruction": "Past simple regular",
      "explanation": "watch → watched."
    },
    {
      "type": "translation",
      "question": "Он потерял ключи.",
      "answer": "He lost his keys",
      "instruction": "Past simple irregular",
      "explanation": "lose → lost."
    },
    {
      "type": "translation",
      "question": "Ты когда-нибудь был в Париже?",
      "answer": "Did you ever visit Paris?",
      "instruction": "Past simple question",
      "explanation": "Did you ever + base verb?",
      "acceptableAnswers": [
        "Have you ever been to Paris?",
        "Have you ever visited Paris?"
      ]
    },
    {
      "type": "translation",
      "question": "Они приехали поздно.",
      "answer": "They arrived late",
      "instruction": "Past simple",
      "explanation": "arrive → arrived."
    },
    {
      "type": "translation",
      "question": "Я не понял вопрос.",
      "answer": "I didn't understand the question",
      "instruction": "Past simple negative",
      "explanation": "understand → understood (same form)."
    },
    {
      "type": "translation",
      "question": "Мы встретили старых друзей.",
      "answer": "We met old friends",
      "instruction": "Past simple irregular",
      "explanation": "meet → met."
    },
    {
      "type": "translation",
      "question": "Она написала длинное письмо.",
      "answer": "She wrote a long letter",
      "instruction": "Past simple irregular",
      "explanation": "write → wrote."
    },
    {
      "type": "translation",
      "question": "Он не ответил на звонок.",
      "answer": "He didn't answer the call",
      "instruction": "Past simple negative",
      "explanation": "didn't answer."
    },
    {
      "type": "translation",
      "question": "Я ел суши впервые.",
      "answer": "I tried sushi for the first time",
      "instruction": "Past simple",
      "explanation": "try → tried."
    },
    {
      "type": "translation",
      "question": "Мы провели отличные выходные.",
      "answer": "We had a great weekend",
      "instruction": "Past simple — have",
      "explanation": "have → had."
    },
    {
      "type": "translation",
      "question": "Она родилась в Лондоне.",
      "answer": "She was born in London",
      "instruction": "Past simple passive",
      "explanation": "was born in London."
    },
    {
      "type": "translation",
      "question": "Они не знали правду.",
      "answer": "They didn't know the truth",
      "instruction": "Past simple",
      "explanation": "know → knew."
    }
  ],
  "eng-ch5-choices": [
    {
      "type": "sentence_building",
      "question": "This / book / is / more / interesting / than / that / one",
      "options": [
        "This",
        "book",
        "is",
        "more",
        "interesting",
        "than",
        "that",
        "one"
      ],
      "answer": "This book is more interesting than that one",
      "instruction": "Build a comparative",
      "explanation": "more interesting than…"
    },
    {
      "type": "sentence_building",
      "question": "She / is / the / best / student / in / the / class",
      "options": [
        "She",
        "is",
        "the",
        "best",
        "student",
        "in",
        "the",
        "class"
      ],
      "answer": "She is the best student in the class",
      "instruction": "Build a superlative",
      "explanation": "the best — irregular good → best."
    },
    {
      "type": "sentence_building",
      "question": "He / runs / faster / than / I / do",
      "options": [
        "He",
        "runs",
        "faster",
        "than",
        "I",
        "do"
      ],
      "answer": "He runs faster than I do",
      "instruction": "Build a comparison",
      "explanation": "faster than I do — do replaces verb."
    },
    {
      "type": "sentence_building",
      "question": "My / car / is / as / fast / as / yours",
      "options": [
        "My",
        "car",
        "is",
        "as",
        "fast",
        "as",
        "yours"
      ],
      "answer": "My car is as fast as yours",
      "instruction": "Build as…as",
      "explanation": "as fast as yours."
    },
    {
      "type": "sentence_building",
      "question": "This / is / the / most / difficult / exercise / today",
      "options": [
        "This",
        "is",
        "the",
        "most",
        "difficult",
        "exercise",
        "today"
      ],
      "answer": "This is the most difficult exercise today",
      "instruction": "Build superlative",
      "explanation": "most difficult — 3+ syllables."
    },
    {
      "type": "sentence_building",
      "question": "London / is / bigger / than / Oxford",
      "options": [
        "London",
        "is",
        "bigger",
        "than",
        "Oxford"
      ],
      "answer": "London is bigger than Oxford",
      "instruction": "Build -er comparative",
      "explanation": "bigger — double g."
    },
    {
      "type": "sentence_building",
      "question": "She / speaks / English / better / than / her / brother",
      "options": [
        "She",
        "speaks",
        "English",
        "better",
        "than",
        "her",
        "brother"
      ],
      "answer": "She speaks English better than her brother",
      "instruction": "Build adverb comparative",
      "explanation": "better — irregular well → better."
    },
    {
      "type": "sentence_building",
      "question": "It / was / the / worst / film / I've / ever / seen",
      "options": [
        "It",
        "was",
        "the",
        "worst",
        "film",
        "I've",
        "ever",
        "seen"
      ],
      "answer": "It was the worst film I've ever seen",
      "instruction": "Build superlative",
      "explanation": "worst — irregular bad → worst."
    },
    {
      "type": "sentence_building",
      "question": "This / restaurant / is / less / expensive / than / that / one",
      "options": [
        "This",
        "restaurant",
        "is",
        "less",
        "expensive",
        "than",
        "that",
        "one"
      ],
      "answer": "This restaurant is less expensive than that one",
      "instruction": "Build less…than",
      "explanation": "less expensive than…"
    },
    {
      "type": "sentence_building",
      "question": "He / is / taller / than / his / father",
      "options": [
        "He",
        "is",
        "taller",
        "than",
        "his",
        "father"
      ],
      "answer": "He is taller than his father",
      "instruction": "Build -er comparative",
      "explanation": "taller than…"
    },
    {
      "type": "sentence_building",
      "question": "This / route / is / shorter / than / the / other",
      "options": [
        "This",
        "route",
        "is",
        "shorter",
        "than",
        "the",
        "other"
      ],
      "answer": "This route is shorter than the other",
      "instruction": "Build comparison",
      "explanation": "shorter than the other."
    },
    {
      "type": "sentence_building",
      "question": "She / is / not / as / tall / as / her / sister",
      "options": [
        "She",
        "is",
        "not",
        "as",
        "tall",
        "as",
        "her",
        "sister"
      ],
      "answer": "She is not as tall as her sister",
      "instruction": "Build negative as…as",
      "explanation": "not as tall as…"
    },
    {
      "type": "sentence_building",
      "question": "It / is / by / far / the / best / option",
      "options": [
        "It",
        "is",
        "by",
        "far",
        "the",
        "best",
        "option"
      ],
      "answer": "It is by far the best option",
      "instruction": "Build emphatic superlative",
      "explanation": "by far the best."
    },
    {
      "type": "sentence_building",
      "question": "The / more / you / practice / the / better / you / get",
      "options": [
        "The",
        "more",
        "you",
        "practice",
        "the",
        "better",
        "you",
        "get"
      ],
      "answer": "The more you practice, the better you get",
      "instruction": "Build correlative comparative",
      "explanation": "The more… the better…"
    },
    {
      "type": "sentence_building",
      "question": "This / phone / is / cheaper / than / mine",
      "options": [
        "This",
        "phone",
        "is",
        "cheaper",
        "than",
        "mine"
      ],
      "answer": "This phone is cheaper than mine",
      "instruction": "Build comparative",
      "explanation": "cheaper than mine."
    }
  ],
  "eng-ch6-experiences": [
    {
      "type": "translation",
      "question": "Я никогда не был в Японии.",
      "answer": "I have never been to Japan",
      "instruction": "Present perfect + never",
      "explanation": "have never been to…"
    },
    {
      "type": "translation",
      "question": "Она уже закончила домашнее задание.",
      "answer": "She has already finished her homework",
      "instruction": "Present perfect + already",
      "explanation": "has already + V3."
    },
    {
      "type": "translation",
      "question": "Мы только что приехали.",
      "answer": "We have just arrived",
      "instruction": "Present perfect + just",
      "explanation": "have just + V3."
    },
    {
      "type": "translation",
      "question": "Ты когда-нибудь пробовал суши?",
      "answer": "Have you ever tried sushi?",
      "instruction": "Present perfect question",
      "explanation": "Have you ever + V3?"
    },
    {
      "type": "translation",
      "question": "Он потерял паспорт.",
      "answer": "He has lost his passport",
      "instruction": "Present perfect",
      "explanation": "has lost — recent/relevant result."
    },
    {
      "type": "translation",
      "question": "Они ещё не ответили.",
      "answer": "They haven't replied yet",
      "instruction": "Present perfect negative",
      "explanation": "haven't + V3 + yet."
    },
    {
      "type": "translation",
      "question": "Я видел этот фильм три раза.",
      "answer": "I have seen this film three times",
      "instruction": "Present perfect + frequency",
      "explanation": "have seen… three times."
    },
    {
      "type": "translation",
      "question": "Она жила в Берлине пять лет.",
      "answer": "She has lived in Berlin for five years",
      "instruction": "Present perfect + duration",
      "explanation": "has lived… for five years."
    },
    {
      "type": "translation",
      "question": "Мы не встречались давно.",
      "answer": "We haven't met for ages",
      "instruction": "Present perfect",
      "explanation": "haven't met for ages."
    },
    {
      "type": "translation",
      "question": "Он написал две книги.",
      "answer": "He has written two books",
      "instruction": "Present perfect",
      "explanation": "has written two books."
    },
    {
      "type": "translation",
      "question": "Ты когда-нибудь летал на воздушном шаре?",
      "answer": "Have you ever flown in a hot air balloon?",
      "instruction": "Present perfect question",
      "explanation": "Have you ever flown…?"
    },
    {
      "type": "translation",
      "question": "Я ещё не ел сегодня.",
      "answer": "I haven't eaten today",
      "instruction": "Present perfect",
      "explanation": "haven't eaten today."
    },
    {
      "type": "translation",
      "question": "Она уехала в командировку.",
      "answer": "She has gone on a business trip",
      "instruction": "Present perfect — go",
      "explanation": "has gone = уехала и ещё там."
    },
    {
      "type": "translation",
      "question": "Мы знаем друг друга с детства.",
      "answer": "We have known each other since childhood",
      "instruction": "Present perfect + since",
      "explanation": "have known… since childhood."
    }
  ],
  "eng-ch7-future-plans": [
    {
      "type": "translation",
      "question": "Я позвоню тебе завтра.",
      "answer": "I will call you tomorrow",
      "instruction": "Will — promise",
      "explanation": "will + base verb."
    },
    {
      "type": "translation",
      "question": "Она приедет в пятницу.",
      "answer": "She will arrive on Friday",
      "instruction": "Will — prediction",
      "explanation": "will arrive on Friday."
    },
    {
      "type": "translation",
      "question": "Мы не опоздаем.",
      "answer": "We won't be late",
      "instruction": "Will negative",
      "explanation": "won't be late."
    },
    {
      "type": "translation",
      "question": "Если пойдёт дождь, я останусь дома.",
      "answer": "If it rains, I will stay home",
      "instruction": "First conditional",
      "explanation": "If + present, will + base."
    },
    {
      "type": "translation",
      "question": "Я помогу тебе с этим.",
      "answer": "I will help you with this",
      "instruction": "Will — offer",
      "explanation": "will help you."
    },
    {
      "type": "translation",
      "question": "Они, наверное, не придут.",
      "answer": "They probably won't come",
      "instruction": "Will — prediction",
      "explanation": "probably won't come."
    },
    {
      "type": "translation",
      "question": "Ты успеешь?",
      "answer": "Will you make it in time?",
      "instruction": "Will — question",
      "explanation": "Will you make it…?"
    },
    {
      "type": "translation",
      "question": "Это будет сложно.",
      "answer": "It will be difficult",
      "instruction": "Will + be",
      "explanation": "will be difficult."
    },
    {
      "type": "translation",
      "question": "Я думаю, что он согласится.",
      "answer": "I think he will agree",
      "instruction": "Will — opinion",
      "explanation": "will agree."
    },
    {
      "type": "translation",
      "question": "Мы проведём отпуск в Италии.",
      "answer": "We will spend our holiday in Italy",
      "instruction": "Will — plan",
      "explanation": "will spend…"
    },
    {
      "type": "translation",
      "question": "Она не забудет.",
      "answer": "She won't forget",
      "instruction": "Will negative",
      "explanation": "won't forget."
    },
    {
      "type": "translation",
      "question": "Через год я буду говорить по-английски свободно.",
      "answer": "In a year I will speak English fluently",
      "instruction": "Will — future state",
      "explanation": "will speak… fluently."
    },
    {
      "type": "translation",
      "question": "Он сделает всё возможное.",
      "answer": "He will do his best",
      "instruction": "Will — determination",
      "explanation": "will do his best."
    },
    {
      "type": "translation",
      "question": "Мы увидимся скоро.",
      "answer": "We will see each other soon",
      "instruction": "Will — future meeting",
      "explanation": "will see each other soon."
    },
    {
      "type": "translation",
      "question": "Это изменит всё.",
      "answer": "It will change everything",
      "instruction": "Will — consequence",
      "explanation": "will change everything."
    }
  ],
  "eng-ch8-storytelling": [
    {
      "type": "error_correction",
      "question": "I was read when she called.",
      "answer": "I was reading when she called.",
      "instruction": "Past continuous",
      "explanation": "was reading — not was read."
    },
    {
      "type": "error_correction",
      "question": "They was watching TV.",
      "answer": "They were watching TV.",
      "instruction": "Past continuous plural",
      "explanation": "They → were watching."
    },
    {
      "type": "error_correction",
      "question": "When I arrived, the train already left.",
      "answer": "When I arrived, the train had already left.",
      "instruction": "Past perfect",
      "explanation": "had already left — before arrival."
    },
    {
      "type": "error_correction",
      "question": "I used to played tennis.",
      "answer": "I used to play tennis.",
      "instruction": "Used to + base",
      "explanation": "used to + base verb (no -ed)."
    },
    {
      "type": "error_correction",
      "question": "She was cook when I came.",
      "answer": "She was cooking when I came.",
      "instruction": "Past continuous",
      "explanation": "was cooking — V-ing."
    },
    {
      "type": "error_correction",
      "question": "While we walked, it started to rain.",
      "answer": "While we were walking, it started to rain.",
      "instruction": "While + past continuous",
      "explanation": "While we were walking…"
    },
    {
      "type": "error_correction",
      "question": "He had finish before I arrived.",
      "answer": "He had finished before I arrived.",
      "instruction": "Past perfect",
      "explanation": "had finished — V3."
    },
    {
      "type": "error_correction",
      "question": "I was study all night.",
      "answer": "I was studying all night.",
      "instruction": "Past continuous",
      "explanation": "was studying — V-ing."
    },
    {
      "type": "error_correction",
      "question": "They had went home before midnight.",
      "answer": "They had gone home before midnight.",
      "instruction": "Past perfect irregular",
      "explanation": "go → gone (V3)."
    },
    {
      "type": "error_correction",
      "question": "She used to lives in Paris.",
      "answer": "She used to live in Paris.",
      "instruction": "Used to",
      "explanation": "used to live — base verb."
    },
    {
      "type": "error_correction",
      "question": "I read a book when the phone rang.",
      "answer": "I was reading a book when the phone rang.",
      "instruction": "Interrupted action",
      "explanation": "was reading when…"
    },
    {
      "type": "error_correction",
      "question": "We was having dinner at eight.",
      "answer": "We were having dinner at eight.",
      "instruction": "Past continuous",
      "explanation": "We → were having."
    },
    {
      "type": "error_correction",
      "question": "By the time I got there, they leave.",
      "answer": "By the time I got there, they had left.",
      "instruction": "Past perfect",
      "explanation": "had left — before got there."
    },
    {
      "type": "error_correction",
      "question": "He was work when I saw him.",
      "answer": "He was working when I saw him.",
      "instruction": "Past continuous",
      "explanation": "was working."
    },
    {
      "type": "error_correction",
      "question": "I had never saw such a thing.",
      "answer": "I had never seen such a thing.",
      "instruction": "Past perfect irregular",
      "explanation": "see → seen (V3)."
    }
  ],
  "eng-ch9-real-world": [
    {
      "type": "translation",
      "question": "Я устал — я бегал.",
      "answer": "I'm tired — I've been running",
      "instruction": "Present perfect continuous",
      "explanation": "I've been running — visible result."
    },
    {
      "type": "translation",
      "question": "Она работает здесь с 2020 года.",
      "answer": "She has been working here since 2020",
      "instruction": "Present perfect continuous + since",
      "explanation": "has been working since 2020."
    },
    {
      "type": "translation",
      "question": "Сколько времени ты ждёшь?",
      "answer": "How long have you been waiting?",
      "instruction": "PPC question",
      "explanation": "How long have you been + V-ing?"
    },
    {
      "type": "translation",
      "question": "Они учат испанский два года.",
      "answer": "They have been studying Spanish for two years",
      "instruction": "PPC + for",
      "explanation": "have been studying… for two years."
    },
    {
      "type": "translation",
      "question": "Дождь идёт с утра.",
      "answer": "It has been raining since morning",
      "instruction": "PPC — rain",
      "explanation": "has been raining since morning."
    },
    {
      "type": "translation",
      "question": "Я давно не видел его.",
      "answer": "I haven't seen him for a long time",
      "instruction": "Present perfect",
      "explanation": "haven't seen… for a long time."
    },
    {
      "type": "translation",
      "question": "Она весь день готовит.",
      "answer": "She has been cooking all day",
      "instruction": "PPC — duration",
      "explanation": "has been cooking all day."
    },
    {
      "type": "translation",
      "question": "Мы живём здесь с прошлого года.",
      "answer": "We have been living here since last year",
      "instruction": "PPC + since",
      "explanation": "have been living since last year."
    },
    {
      "type": "translation",
      "question": "Он весь вечер играл в футбол.",
      "answer": "He has been playing football all evening",
      "instruction": "PPC — activity",
      "explanation": "has been playing… all evening."
    },
    {
      "type": "translation",
      "question": "Сколько времени ты изучаешь английский?",
      "answer": "How long have you been learning English?",
      "instruction": "PPC question",
      "explanation": "How long have you been learning…?"
    },
    {
      "type": "translation",
      "question": "Я давно хочу посетить Японию.",
      "answer": "I have been wanting to visit Japan for ages",
      "instruction": "PPC — want",
      "explanation": "have been wanting… for ages."
    },
    {
      "type": "translation",
      "question": "Они ремонтируют дом уже три месяца.",
      "answer": "They have been renovating the house for three months",
      "instruction": "PPC + for",
      "explanation": "have been renovating… for three months."
    },
    {
      "type": "translation",
      "question": "Ты давно здесь?",
      "answer": "Have you been here long?",
      "instruction": "PPC question",
      "explanation": "Have you been here long?"
    },
    {
      "type": "translation",
      "question": "Она весь день говорит по телефону.",
      "answer": "She has been on the phone all day",
      "instruction": "PPC — state",
      "explanation": "has been on the phone all day."
    }
  ],
  "eng-ch10-what-if": [
    {
      "type": "error_correction",
      "question": "If I will have time, I will call you.",
      "answer": "If I have time, I will call you.",
      "instruction": "First conditional",
      "explanation": "If-clause: present, not will."
    },
    {
      "type": "error_correction",
      "question": "If I was rich, I would travel.",
      "answer": "If I were rich, I would travel.",
      "instruction": "Second conditional",
      "explanation": "If I were — subjunctive form."
    },
    {
      "type": "error_correction",
      "question": "If she would study, she would pass.",
      "answer": "If she studied, she would pass.",
      "instruction": "Second conditional",
      "explanation": "If-clause: past simple, not would."
    },
    {
      "type": "error_correction",
      "question": "If I had knew, I would have told you.",
      "answer": "If I had known, I would have told you.",
      "instruction": "Third conditional",
      "explanation": "know → known (V3)."
    },
    {
      "type": "error_correction",
      "question": "If it rains, I would stay home.",
      "answer": "If it rains, I will stay home.",
      "instruction": "First conditional",
      "explanation": "Result: will, not would."
    },
    {
      "type": "error_correction",
      "question": "If I would be you, I would accept.",
      "answer": "If I were you, I would accept.",
      "instruction": "Second conditional",
      "explanation": "If I were you — fixed phrase."
    },
    {
      "type": "error_correction",
      "question": "If he had went, he would have seen it.",
      "answer": "If he had gone, he would have seen it.",
      "instruction": "Third conditional",
      "explanation": "go → gone (V3)."
    },
    {
      "type": "error_correction",
      "question": "If you heat ice, it would melt.",
      "answer": "If you heat ice, it melts.",
      "instruction": "Zero conditional",
      "explanation": "Zero: present + present."
    },
    {
      "type": "error_correction",
      "question": "If I had more time, I will learn French.",
      "answer": "If I had more time, I would learn French.",
      "instruction": "Second conditional",
      "explanation": "Result: would, not will."
    },
    {
      "type": "error_correction",
      "question": "If she had studied harder, she will pass.",
      "answer": "If she had studied harder, she would have passed.",
      "instruction": "Third conditional",
      "explanation": "Result: would have + V3."
    },
    {
      "type": "error_correction",
      "question": "If I win the lottery, I would buy a house.",
      "answer": "If I won the lottery, I would buy a house.",
      "instruction": "Second conditional",
      "explanation": "If-clause: past simple."
    },
    {
      "type": "error_correction",
      "question": "If they had arrived earlier, they would catch the train.",
      "answer": "If they had arrived earlier, they would have caught the train.",
      "instruction": "Third conditional",
      "explanation": "would have caught."
    },
    {
      "type": "error_correction",
      "question": "If you will ask nicely, he might help.",
      "answer": "If you ask nicely, he might help.",
      "instruction": "First conditional",
      "explanation": "If-clause: present."
    },
    {
      "type": "error_correction",
      "question": "If I was taller, I would play basketball.",
      "answer": "If I were taller, I would play basketball.",
      "instruction": "Second conditional",
      "explanation": "If I were — formal subjunctive."
    },
    {
      "type": "error_correction",
      "question": "If we had leave earlier, we wouldn't be late.",
      "answer": "If we had left earlier, we wouldn't be late.",
      "instruction": "Mixed conditional",
      "explanation": "had left — V3."
    },
    {
      "type": "error_correction",
      "question": "If I would have known, I would come.",
      "answer": "If I had known, I would have come.",
      "instruction": "Third conditional",
      "explanation": "If I had known…"
    }
  ],
  "eng-ch11-passive": [
    {
      "type": "translation",
      "question": "Книга написана в 1990 году.",
      "answer": "The book was written in 1990",
      "instruction": "Past passive",
      "explanation": "was written in 1990."
    },
    {
      "type": "translation",
      "question": "Дом построен в прошлом веке.",
      "answer": "The house was built in the last century",
      "instruction": "Past passive",
      "explanation": "was built in the last century."
    },
    {
      "type": "translation",
      "question": "Письмо отправлено вчера.",
      "answer": "The letter was sent yesterday",
      "instruction": "Past passive",
      "explanation": "was sent yesterday."
    },
    {
      "type": "translation",
      "question": "Английский говорят во всём мире.",
      "answer": "English is spoken all over the world",
      "instruction": "Present passive",
      "explanation": "is spoken all over the world."
    },
    {
      "type": "translation",
      "question": "Решение принято правительством.",
      "answer": "The decision was made by the government",
      "instruction": "Past passive + agent",
      "explanation": "was made by the government."
    },
    {
      "type": "translation",
      "question": "Окна открыты.",
      "answer": "The windows are open",
      "instruction": "State passive / adjective",
      "explanation": "are open — state."
    },
    {
      "type": "translation",
      "question": "Еда приготовлена мамой.",
      "answer": "The food was prepared by my mother",
      "instruction": "Past passive",
      "explanation": "was prepared by my mother."
    },
    {
      "type": "translation",
      "question": "Проблема решена.",
      "answer": "The problem has been solved",
      "instruction": "Present perfect passive",
      "explanation": "has been solved."
    },
    {
      "type": "translation",
      "question": "Закон принят в прошлом году.",
      "answer": "The law was passed last year",
      "instruction": "Past passive",
      "explanation": "was passed last year."
    },
    {
      "type": "translation",
      "question": "Новый мост строят сейчас.",
      "answer": "A new bridge is being built now",
      "instruction": "Present continuous passive",
      "explanation": "is being built now."
    },
    {
      "type": "translation",
      "question": "Его пригласили на конференцию.",
      "answer": "He was invited to the conference",
      "instruction": "Past passive",
      "explanation": "was invited to the conference."
    },
    {
      "type": "translation",
      "question": "Комнату убирают каждый день.",
      "answer": "The room is cleaned every day",
      "instruction": "Present passive habit",
      "explanation": "is cleaned every day."
    },
    {
      "type": "translation",
      "question": "Картина была украдена.",
      "answer": "The painting was stolen",
      "instruction": "Past passive",
      "explanation": "was stolen."
    },
    {
      "type": "translation",
      "question": "Работа будет закончена завтра.",
      "answer": "The work will be finished tomorrow",
      "instruction": "Future passive",
      "explanation": "will be finished tomorrow."
    }
  ],
  "eng-ch12-beyond-borders": [
    {
      "type": "error_correction",
      "question": "She said: \"I am tired.\"",
      "answer": "She said (that) she was tired.",
      "instruction": "Reported speech — present",
      "explanation": "am → was."
    },
    {
      "type": "error_correction",
      "question": "He told me: \"I will come tomorrow.\"",
      "answer": "He told me (that) he would come the next day.",
      "instruction": "Reported speech — will",
      "explanation": "will → would; tomorrow → the next day."
    },
    {
      "type": "error_correction",
      "question": "They asked: \"Where is the station?\"",
      "answer": "They asked where the station was.",
      "instruction": "Reported question",
      "explanation": "Where is → where… was."
    },
    {
      "type": "error_correction",
      "question": "She said: \"I have finished.\"",
      "answer": "She said (that) she had finished.",
      "instruction": "Reported speech — perfect",
      "explanation": "have finished → had finished."
    },
    {
      "type": "error_correction",
      "question": "He said: \"I went home yesterday.\"",
      "answer": "He said (that) he had gone home the day before.",
      "instruction": "Reported speech — past",
      "explanation": "went → had gone; yesterday → the day before."
    },
    {
      "type": "error_correction",
      "question": "She asked: \"Can you help me?\"",
      "answer": "She asked if I could help her.",
      "instruction": "Reported question",
      "explanation": "Can → could; me → her."
    },
    {
      "type": "error_correction",
      "question": "He said: \"I live in London.\"",
      "answer": "He said (that) he lived in London.",
      "instruction": "Reported speech",
      "explanation": "live → lived."
    },
    {
      "type": "error_correction",
      "question": "They said: \"We are leaving now.\"",
      "answer": "They said (that) they were leaving then.",
      "instruction": "Reported speech — continuous",
      "explanation": "are leaving → were leaving; now → then."
    },
    {
      "type": "error_correction",
      "question": "She told him: \"I love you.\"",
      "answer": "She told him (that) she loved him.",
      "instruction": "Reported speech",
      "explanation": "love → loved."
    },
    {
      "type": "error_correction",
      "question": "He asked: \"What time is it?\"",
      "answer": "He asked what time it was.",
      "instruction": "Reported question",
      "explanation": "is → was."
    },
    {
      "type": "error_correction",
      "question": "She said: \"I can't swim.\"",
      "answer": "She said (that) she couldn't swim.",
      "instruction": "Reported speech — modal",
      "explanation": "can't → couldn't."
    },
    {
      "type": "error_correction",
      "question": "They explained: \"We will arrive at six.\"",
      "answer": "They explained (that) they would arrive at six.",
      "instruction": "Reported speech — future",
      "explanation": "will → would."
    },
    {
      "type": "error_correction",
      "question": "He said: \"I must go.\"",
      "answer": "He said (that) he had to go.",
      "instruction": "Reported speech — must",
      "explanation": "must → had to."
    },
    {
      "type": "error_correction",
      "question": "She asked: \"Do you like coffee?\"",
      "answer": "She asked if I liked coffee.",
      "instruction": "Reported yes/no question",
      "explanation": "Do you like → if I liked."
    },
    {
      "type": "error_correction",
      "question": "He said: \"I have never been there.\"",
      "answer": "He said (that) he had never been there.",
      "instruction": "Reported perfect",
      "explanation": "have never been → had never been."
    }
  ],
  "eng-ch16-ielts": [
    {
      "type": "translation",
      "question": "Более того, это важно для экзамена.",
      "answer": "Furthermore, this is important for the exam",
      "instruction": "Formal connector",
      "explanation": "Furthermore/Moreover add information."
    },
    {
      "type": "translation",
      "question": "Тем не менее, результаты неоднозначны.",
      "answer": "Nevertheless, the results are inconclusive",
      "instruction": "Contrast connector",
      "explanation": "Nevertheless = however."
    },
    {
      "type": "translation",
      "question": "Следовательно, нужны дальнейшие исследования.",
      "answer": "Therefore, further research is needed",
      "instruction": "Result connector",
      "explanation": "Therefore = as a result."
    },
    {
      "type": "translation",
      "question": "С одной стороны, это дешевле.",
      "answer": "On the one hand, it is cheaper",
      "instruction": "Discourse marker",
      "explanation": "On the one hand…"
    },
    {
      "type": "translation",
      "question": "С другой стороны, качество ниже.",
      "answer": "On the other hand, the quality is lower",
      "instruction": "Discourse marker",
      "explanation": "On the other hand…"
    },
    {
      "type": "translation",
      "question": "В заключение, преимущества перевешивают недостатки.",
      "answer": "In conclusion, the advantages outweigh the disadvantages",
      "instruction": "Conclusion",
      "explanation": "In conclusion…"
    },
    {
      "type": "translation",
      "question": "Несмотря на трудности, проект успешен.",
      "answer": "Despite the difficulties, the project is successful",
      "instruction": "Despite + noun",
      "explanation": "Despite the difficulties…"
    },
    {
      "type": "translation",
      "question": "Благодаря новым технологиям прогресс ускорился.",
      "answer": "Thanks to new technology, progress has accelerated",
      "instruction": "Thanks to",
      "explanation": "Thanks to new technology…"
    },
    {
      "type": "translation",
      "question": "В то время как одни согласны, другие возражают.",
      "answer": "Whereas some agree, others object",
      "instruction": "Contrast — whereas",
      "explanation": "Whereas = while (formal)."
    },
    {
      "type": "translation",
      "question": "Кроме того, следует учитывать экологический аспект.",
      "answer": "In addition, the environmental aspect should be considered",
      "instruction": "Addition",
      "explanation": "In addition…"
    },
    {
      "type": "translation",
      "question": "По моему мнению, это справедливое решение.",
      "answer": "In my opinion, this is a fair decision",
      "instruction": "Opinion phrase",
      "explanation": "In my opinion…"
    },
    {
      "type": "translation",
      "question": "Согласно исследованию, цифры выросли.",
      "answer": "According to the study, the figures have risen",
      "instruction": "Reference",
      "explanation": "According to the study…"
    },
    {
      "type": "translation",
      "question": "В отличие от предыдущего отчёта, данные точнее.",
      "answer": "Unlike the previous report, the data is more accurate",
      "instruction": "Contrast — unlike",
      "explanation": "Unlike the previous report…"
    },
    {
      "type": "translation",
      "question": "В целом, тенденция положительная.",
      "answer": "Overall, the trend is positive",
      "instruction": "Summary",
      "explanation": "Overall…"
    },
    {
      "type": "translation",
      "question": "Например, в развивающихся странах…",
      "answer": "For instance, in developing countries…",
      "instruction": "Example marker",
      "explanation": "For instance = for example."
    },
    {
      "type": "error_correction",
      "question": "The results are inconclusive, however the trend is clear.",
      "answer": "The results are inconclusive; however, the trend is clear.",
      "instruction": "However — punctuation",
      "explanation": "However after semicolon or new sentence."
    },
    {
      "type": "error_correction",
      "question": "Despite of the rain, we went out.",
      "answer": "Despite the rain, we went out.",
      "instruction": "Despite — no of",
      "explanation": "Despite + noun (no «of»)."
    },
    {
      "type": "error_correction",
      "question": "On contrary, I disagree.",
      "answer": "On the contrary, I disagree.",
      "instruction": "Fixed phrase",
      "explanation": "On the contrary — with «the»."
    },
    {
      "type": "error_correction",
      "question": "In spite the weather, we continued.",
      "answer": "In spite of the weather, we continued.",
      "instruction": "In spite of",
      "explanation": "In spite of — needs «of»."
    },
    {
      "type": "error_correction",
      "question": "The data suggest that climate is changing.",
      "answer": "The data suggest that the climate is changing.",
      "instruction": "Article with climate",
      "explanation": "the climate — specific topic."
    },
    {
      "type": "error_correction",
      "question": "According the report, sales fell.",
      "answer": "According to the report, sales fell.",
      "instruction": "According to",
      "explanation": "According to — needs «to»."
    },
    {
      "type": "error_correction",
      "question": "Furthermore, it is importance for the exam.",
      "answer": "Furthermore, it is important for the exam.",
      "instruction": "Adjective not noun",
      "explanation": "important (adj), not importance."
    },
    {
      "type": "error_correction",
      "question": "Nevertheless, the results is inconclusive.",
      "answer": "Nevertheless, the results are inconclusive.",
      "instruction": "Subject-verb agreement",
      "explanation": "results → are."
    },
    {
      "type": "error_correction",
      "question": "In addition to this, we must to consider costs.",
      "answer": "In addition to this, we must consider costs.",
      "instruction": "Must + base",
      "explanation": "must + base verb (no «to»)."
    },
    {
      "type": "error_correction",
      "question": "On the one hand it is cheap on the other hand quality is low.",
      "answer": "On the one hand, it is cheap; on the other hand, quality is low.",
      "instruction": "Punctuation",
      "explanation": "Commas and semicolon needed."
    },
    {
      "type": "error_correction",
      "question": "Whereas some agree, but others object.",
      "answer": "Whereas some agree, others object.",
      "instruction": "Double connector",
      "explanation": "Whereas already shows contrast — no «but»."
    },
    {
      "type": "error_correction",
      "question": "Thanks for new technology, progress accelerated.",
      "answer": "Thanks to new technology, progress has accelerated.",
      "instruction": "Thanks to",
      "explanation": "Thanks to — not «thanks for»."
    },
    {
      "type": "error_correction",
      "question": "In conclusion, the advantages outweighs the disadvantages.",
      "answer": "In conclusion, the advantages outweigh the disadvantages.",
      "instruction": "Subject-verb agreement",
      "explanation": "advantages → outweigh."
    },
    {
      "type": "error_correction",
      "question": "For instance, in developing country…",
      "answer": "For instance, in developing countries…",
      "instruction": "Plural",
      "explanation": "developing countries — plural."
    },
    {
      "type": "sentence_building",
      "question": "Furthermore / this / is / important / for / the / exam",
      "options": [
        "Furthermore",
        "this",
        "is",
        "important",
        "for",
        "the",
        "exam"
      ],
      "answer": "Furthermore, this is important for the exam",
      "instruction": "Build formal connector sentence",
      "explanation": "Furthermore at start."
    },
    {
      "type": "sentence_building",
      "question": "Nevertheless / the / results / are / inconclusive",
      "options": [
        "Nevertheless",
        "the",
        "results",
        "are",
        "inconclusive"
      ],
      "answer": "Nevertheless, the results are inconclusive",
      "instruction": "Build contrast sentence",
      "explanation": "Nevertheless — contrast."
    },
    {
      "type": "sentence_building",
      "question": "Therefore / further / research / is / needed",
      "options": [
        "Therefore",
        "further",
        "research",
        "is",
        "needed"
      ],
      "answer": "Therefore, further research is needed",
      "instruction": "Build result sentence",
      "explanation": "Therefore — consequence."
    },
    {
      "type": "sentence_building",
      "question": "On / the / one / hand / it / is / cheaper",
      "options": [
        "On",
        "the",
        "one",
        "hand",
        "it",
        "is",
        "cheaper"
      ],
      "answer": "On the one hand, it is cheaper",
      "instruction": "Build discourse marker",
      "explanation": "On the one hand…"
    },
    {
      "type": "sentence_building",
      "question": "On / the / other / hand / quality / is / lower",
      "options": [
        "On",
        "the",
        "other",
        "hand",
        "quality",
        "is",
        "lower"
      ],
      "answer": "On the other hand, quality is lower",
      "instruction": "Build contrast pair",
      "explanation": "On the other hand…"
    },
    {
      "type": "sentence_building",
      "question": "In / conclusion / the / advantages / outweigh / the / disadvantages",
      "options": [
        "In",
        "conclusion",
        "the",
        "advantages",
        "outweigh",
        "the",
        "disadvantages"
      ],
      "answer": "In conclusion, the advantages outweigh the disadvantages",
      "instruction": "Build conclusion",
      "explanation": "In conclusion…"
    },
    {
      "type": "sentence_building",
      "question": "Despite / the / difficulties / the / project / is / successful",
      "options": [
        "Despite",
        "the",
        "difficulties",
        "the",
        "project",
        "is",
        "successful"
      ],
      "answer": "Despite the difficulties, the project is successful",
      "instruction": "Build despite sentence",
      "explanation": "Despite + noun."
    },
    {
      "type": "sentence_building",
      "question": "According / to / the / study / the / figures / have / risen",
      "options": [
        "According",
        "to",
        "the",
        "study",
        "the",
        "figures",
        "have",
        "risen"
      ],
      "answer": "According to the study, the figures have risen",
      "instruction": "Build reference sentence",
      "explanation": "According to the study…"
    },
    {
      "type": "sentence_building",
      "question": "Overall / the / trend / is / positive",
      "options": [
        "Overall",
        "the",
        "trend",
        "is",
        "positive"
      ],
      "answer": "Overall, the trend is positive",
      "instruction": "Build summary",
      "explanation": "Overall…"
    },
    {
      "type": "sentence_building",
      "question": "In / my / opinion / this / is / a / fair / decision",
      "options": [
        "In",
        "my",
        "opinion",
        "this",
        "is",
        "a",
        "fair",
        "decision"
      ],
      "answer": "In my opinion, this is a fair decision",
      "instruction": "Build opinion phrase",
      "explanation": "In my opinion…"
    },
    {
      "type": "sentence_building",
      "question": "Unlike / the / previous / report / the / data / is / more / accurate",
      "options": [
        "Unlike",
        "the",
        "previous",
        "report",
        "the",
        "data",
        "is",
        "more",
        "accurate"
      ],
      "answer": "Unlike the previous report, the data is more accurate",
      "instruction": "Build unlike sentence",
      "explanation": "Unlike + noun."
    },
    {
      "type": "sentence_building",
      "question": "For / instance / in / developing / countries / access / is / limited",
      "options": [
        "For",
        "instance",
        "in",
        "developing",
        "countries",
        "access",
        "is",
        "limited"
      ],
      "answer": "For instance, in developing countries access is limited",
      "instruction": "Build example",
      "explanation": "For instance…"
    },
    {
      "type": "sentence_building",
      "question": "Thanks / to / new / technology / progress / has / accelerated",
      "options": [
        "Thanks",
        "to",
        "new",
        "technology",
        "progress",
        "has",
        "accelerated"
      ],
      "answer": "Thanks to new technology, progress has accelerated",
      "instruction": "Build thanks to",
      "explanation": "Thanks to…"
    },
    {
      "type": "sentence_building",
      "question": "Whereas / some / agree / others / object",
      "options": [
        "Whereas",
        "some",
        "agree",
        "others",
        "object"
      ],
      "answer": "Whereas some agree, others object",
      "instruction": "Build whereas",
      "explanation": "Whereas = formal while."
    },
    {
      "type": "sentence_building",
      "question": "In / addition / the / environmental / aspect / should / be / considered",
      "options": [
        "In",
        "addition",
        "the",
        "environmental",
        "aspect",
        "should",
        "be",
        "considered"
      ],
      "answer": "In addition, the environmental aspect should be considered",
      "instruction": "Build addition",
      "explanation": "In addition…"
    },
    {
      "type": "sentence_building",
      "question": "Furthermore / this / supports / the / thesis",
      "options": [
        "Furthermore",
        "this",
        "supports",
        "the",
        "thesis"
      ],
      "answer": "Furthermore, this supports the thesis",
      "instruction": "Build connector sentence",
      "explanation": "Furthermore — formal addition"
    }
  ],
  "eng-ch20-going-to": [
    {
      "type": "translation",
      "question": "Мы собираемся путешествовать летом.",
      "answer": "We are going to travel in the summer",
      "instruction": "Going to — plan",
      "explanation": "are going to + base verb."
    },
    {
      "type": "translation",
      "question": "Она собирается переехать в Лондон.",
      "answer": "She is going to move to London",
      "instruction": "Going to",
      "explanation": "is going to move…"
    },
    {
      "type": "translation",
      "question": "Смотри на облака — скоро пойдёт дождь.",
      "answer": "Look at the clouds — it's going to rain",
      "instruction": "Going to — prediction",
      "explanation": "it's going to rain — evidence."
    },
    {
      "type": "translation",
      "question": "Ты собираешься прийти?",
      "answer": "Are you going to come?",
      "instruction": "Going to question",
      "explanation": "Are you going to…?"
    },
    {
      "type": "translation",
      "question": "Они не собираются покупать машину.",
      "answer": "They aren't going to buy a car",
      "instruction": "Going to negative",
      "explanation": "aren't going to buy…"
    },
    {
      "type": "translation",
      "question": "Я собираюсь выучить испанский.",
      "answer": "I'm going to learn Spanish",
      "instruction": "Going to — intention",
      "explanation": "going to learn Spanish."
    },
    {
      "type": "translation",
      "question": "Он собирается позвонить тебе.",
      "answer": "He is going to call you",
      "instruction": "Going to",
      "explanation": "is going to call you."
    },
    {
      "type": "translation",
      "question": "Мы собираемся ужинать в ресторане.",
      "answer": "We are going to have dinner at a restaurant",
      "instruction": "Going to",
      "explanation": "going to have dinner…"
    },
    {
      "type": "translation",
      "question": "Она собирается сдать экзамен.",
      "answer": "She is going to take the exam",
      "instruction": "Going to",
      "explanation": "going to take the exam."
    },
    {
      "type": "translation",
      "question": "Ты собираешься рано ложиться?",
      "answer": "Are you going to go to bed early?",
      "instruction": "Going to question",
      "explanation": "Are you going to go to bed…?"
    },
    {
      "type": "translation",
      "question": "Они собираются жениться.",
      "answer": "They are going to get married",
      "instruction": "Going to",
      "explanation": "going to get married."
    },
    {
      "type": "translation",
      "question": "Я собираюсь начать новую работу.",
      "answer": "I'm going to start a new job",
      "instruction": "Going to — plan",
      "explanation": "going to start a new job."
    },
    {
      "type": "translation",
      "question": "Смотри — машина собирается повернуть.",
      "answer": "Look — the car is going to turn",
      "instruction": "Going to — imminent",
      "explanation": "is going to turn — about to happen."
    },
    {
      "type": "translation",
      "question": "Мы не собираемся сдаваться.",
      "answer": "We aren't going to give up",
      "instruction": "Going to negative",
      "explanation": "aren't going to give up."
    },
    {
      "type": "translation",
      "question": "Они собираются переехать.",
      "answer": "They are going to move",
      "instruction": "Going to",
      "explanation": "They are going to move"
    }
  ],
  "eng-ch21-quantifiers": [
    {
      "type": "error_correction",
      "question": "I don't have much friends.",
      "answer": "I don't have many friends.",
      "instruction": "Countable noun",
      "explanation": "friends = countable → many."
    },
    {
      "type": "error_correction",
      "question": "There is many water in the bottle.",
      "answer": "There is much water in the bottle.",
      "instruction": "Uncountable noun",
      "explanation": "water = uncountable → much."
    },
    {
      "type": "error_correction",
      "question": "I have a few money.",
      "answer": "I have a little money.",
      "instruction": "Uncountable",
      "explanation": "money = uncountable → a little."
    },
    {
      "type": "error_correction",
      "question": "She has less books than me.",
      "answer": "She has fewer books than me.",
      "instruction": "Countable comparison",
      "explanation": "books = countable → fewer."
    },
    {
      "type": "error_correction",
      "question": "There are much people here.",
      "answer": "There are many people here.",
      "instruction": "Countable plural",
      "explanation": "people = countable → many."
    },
    {
      "type": "error_correction",
      "question": "I need a little informations.",
      "answer": "I need a little information.",
      "instruction": "Uncountable — no plural",
      "explanation": "information — uncountable, no -s."
    },
    {
      "type": "error_correction",
      "question": "How much apples do you want?",
      "answer": "How many apples do you want?",
      "instruction": "Countable question",
      "explanation": "apples = countable → how many."
    },
    {
      "type": "error_correction",
      "question": "We have a lot of homeworks.",
      "answer": "We have a lot of homework.",
      "instruction": "Uncountable",
      "explanation": "homework — no plural."
    },
    {
      "type": "error_correction",
      "question": "There isn't many sugar left.",
      "answer": "There isn't much sugar left.",
      "instruction": "Uncountable negative",
      "explanation": "sugar = uncountable → much."
    },
    {
      "type": "error_correction",
      "question": "He drank too much cups of coffee.",
      "answer": "He drank too many cups of coffee.",
      "instruction": "Countable container",
      "explanation": "cups = countable → many."
    },
    {
      "type": "error_correction",
      "question": "I have got fewer time than you.",
      "answer": "I have got less time than you.",
      "instruction": "Uncountable comparison",
      "explanation": "time = uncountable → less, not fewer."
    },
    {
      "type": "error_correction",
      "question": "There are a few water in the glass.",
      "answer": "There is a little water in the glass.",
      "instruction": "Uncountable + verb",
      "explanation": "water → is; a little."
    }
  ],
  "eng-ch22-modals": [
    {
      "type": "translation",
      "question": "Тебе следует отдохнуть.",
      "answer": "You should rest",
      "instruction": "Should — advice",
      "explanation": "should + base verb."
    },
    {
      "type": "translation",
      "question": "Ты должен носить шлем.",
      "answer": "You must wear a helmet",
      "instruction": "Must — obligation",
      "explanation": "must + base verb."
    },
    {
      "type": "translation",
      "question": "Мне нужно работать завтра.",
      "answer": "I have to work tomorrow",
      "instruction": "Have to — external obligation",
      "explanation": "have to + base verb."
    },
    {
      "type": "translation",
      "question": "Здесь нельзя курить.",
      "answer": "You mustn't smoke here",
      "instruction": "Mustn't — prohibition",
      "explanation": "mustn't = prohibition."
    },
    {
      "type": "translation",
      "question": "Тебе не обязательно приходить.",
      "answer": "You don't have to come",
      "instruction": "Don't have to — no obligation",
      "explanation": "don't have to = not necessary."
    },
    {
      "type": "translation",
      "question": "Ты можешь помочь мне?",
      "answer": "Can you help me?",
      "instruction": "Can — permission/ability",
      "explanation": "Can you help me?"
    },
    {
      "type": "translation",
      "question": "Она умеет играть на пианино.",
      "answer": "She can play the piano",
      "instruction": "Can — ability",
      "explanation": "can play the piano."
    },
    {
      "type": "translation",
      "question": "Можно мне войти?",
      "answer": "May I come in?",
      "instruction": "May — formal permission",
      "explanation": "May I come in?"
    },
    {
      "type": "translation",
      "question": "Ты мог бы закрыть окно?",
      "answer": "Could you close the window?",
      "instruction": "Could — polite request",
      "explanation": "Could you…? — polite."
    },
    {
      "type": "translation",
      "question": "Он, должно быть, заблудился.",
      "answer": "He must be lost",
      "instruction": "Must — deduction",
      "explanation": "must be lost — strong deduction."
    },
    {
      "type": "translation",
      "question": "Она не может быть дома — машины нет.",
      "answer": "She can't be at home — her car isn't here",
      "instruction": "Can't — negative deduction",
      "explanation": "can't be — impossible."
    },
    {
      "type": "translation",
      "question": "Тебе следовало позвонить.",
      "answer": "You should have called",
      "instruction": "Should have — regret",
      "explanation": "should have + V3."
    },
    {
      "type": "translation",
      "question": "Он мог бы помочь, но не помог.",
      "answer": "He could have helped but he didn't",
      "instruction": "Could have — past possibility",
      "explanation": "could have + V3."
    },
    {
      "type": "translation",
      "question": "Ты не должен был так говорить.",
      "answer": "You shouldn't have said that",
      "instruction": "Shouldn't have — regret",
      "explanation": "shouldn't have + V3."
    },
    {
      "type": "translation",
      "question": "Мне нужно было раньше уйти.",
      "answer": "I had to leave earlier",
      "instruction": "Had to — past obligation",
      "explanation": "had to + base verb."
    },
    {
      "type": "translation",
      "question": "Тебе следовало позвонить.",
      "answer": "You should have called",
      "instruction": "Modal perfect",
      "explanation": "should have called"
    },
    {
      "type": "translation",
      "question": "Он не мог быть дома.",
      "answer": "He can't have been at home",
      "instruction": "Deduction",
      "explanation": "can't have been"
    }
  ],
  "eng-ch23-spotlight": [
    {
      "type": "translation",
      "question": "Именно Джон сломал вазу.",
      "answer": "It was John who broke the vase",
      "instruction": "It-cleft — person",
      "explanation": "It was John who…"
    },
    {
      "type": "translation",
      "question": "Мне нужен отпуск.",
      "answer": "What I need is a holiday",
      "instruction": "Wh-cleft",
      "explanation": "What I need is…"
    },
    {
      "type": "translation",
      "question": "Именно в Париже я её встретил.",
      "answer": "It was in Paris that I met her",
      "instruction": "It-cleft — place",
      "explanation": "It was in Paris that…"
    },
    {
      "type": "translation",
      "question": "Я правда люблю твою идею.",
      "answer": "I do like your idea",
      "instruction": "Emphatic do",
      "explanation": "I do like — emphatic stress."
    },
    {
      "type": "translation",
      "question": "Причина, по которой я ушёл, — шум.",
      "answer": "The reason why I left was the noise",
      "instruction": "Reason cleft",
      "explanation": "The reason why I left was…"
    },
    {
      "type": "translation",
      "question": "Именно она решила уйти.",
      "answer": "It was she who decided to leave",
      "instruction": "It-cleft — subject",
      "explanation": "It was she who… (formal).",
      "acceptableAnswers": [
        "It was her who decided to leave"
      ]
    },
    {
      "type": "translation",
      "question": "То, что она сделала, — уволилась.",
      "answer": "What she did was resign",
      "instruction": "Wh-cleft — action",
      "explanation": "What she did was resign."
    },
    {
      "type": "translation",
      "question": "Именно вчера это произошло.",
      "answer": "It was yesterday that it happened",
      "instruction": "It-cleft — time",
      "explanation": "It was yesterday that…"
    },
    {
      "type": "translation",
      "question": "Именно ты мне нужен.",
      "answer": "It is you that I need",
      "instruction": "It-cleft — object",
      "explanation": "It is you that I need.",
      "acceptableAnswers": [
        "It is you who I need"
      ]
    },
    {
      "type": "translation",
      "question": "То, что меня беспокоит, — цена.",
      "answer": "What worries me is the price",
      "instruction": "Wh-cleft",
      "explanation": "What worries me is…"
    },
    {
      "type": "translation",
      "question": "Именно из-за дождя мы отменили пикник.",
      "answer": "It was because of the rain that we cancelled the picnic",
      "instruction": "It-cleft — reason",
      "explanation": "It was because of… that…"
    },
    {
      "type": "translation",
      "question": "Я действительно понимаю тебя.",
      "answer": "I do understand you",
      "instruction": "Emphatic do",
      "explanation": "I do understand — emphasis."
    },
    {
      "type": "translation",
      "question": "Именно здесь мы впервые поцеловались.",
      "answer": "It was here that we first kissed",
      "instruction": "It-cleft — place",
      "explanation": "It was here that…"
    },
    {
      "type": "translation",
      "question": "То, чего я хочу, — спокойствие.",
      "answer": "What I want is peace and quiet",
      "instruction": "Wh-cleft",
      "explanation": "What I want is…"
    },
    {
      "type": "translation",
      "question": "Именно они выиграли конкурс.",
      "answer": "It was they who won the competition",
      "instruction": "It-cleft — plural",
      "explanation": "It was they who…",
      "acceptableAnswers": [
        "It was them who won the competition"
      ]
    },
    {
      "type": "translation",
      "question": "Именно сейчас нужно действовать.",
      "answer": "It is now that we must act",
      "instruction": "It-cleft — time",
      "explanation": "It is now that…"
    },
    {
      "type": "translation",
      "question": "То, что произошло, — катастрофа.",
      "answer": "What happened was a disaster",
      "instruction": "Wh-cleft — event",
      "explanation": "What happened was…"
    },
    {
      "type": "translation",
      "question": "Я действительно не согласен.",
      "answer": "I do not agree",
      "instruction": "Emphatic do negative",
      "explanation": "I do not agree — formal emphasis.",
      "acceptableAnswers": [
        "I don't agree"
      ]
    },
    {
      "type": "translation",
      "question": "Именно эта книга изменила мою жизнь.",
      "answer": "It was this book that changed my life",
      "instruction": "It-cleft — thing",
      "explanation": "It was this book that…"
    },
    {
      "type": "translation",
      "question": "То, что важно, — честность.",
      "answer": "What matters is honesty",
      "instruction": "Wh-cleft",
      "explanation": "What matters is honesty."
    },
    {
      "type": "error_correction",
      "question": "It was John which broke the vase.",
      "answer": "It was John who broke the vase.",
      "instruction": "It-cleft — person",
      "explanation": "Person → who, not which."
    },
    {
      "type": "error_correction",
      "question": "What I need is a holiday and relax.",
      "answer": "What I need is a holiday.",
      "instruction": "Wh-cleft — redundancy",
      "explanation": "What I need is a holiday — sufficient."
    },
    {
      "type": "error_correction",
      "question": "It was in Paris who I met her.",
      "answer": "It was in Paris that I met her.",
      "instruction": "It-cleft — place",
      "explanation": "Place → that, not who."
    },
    {
      "type": "error_correction",
      "question": "I am do like your idea.",
      "answer": "I do like your idea.",
      "instruction": "Emphatic do",
      "explanation": "I do like — not am do."
    },
    {
      "type": "error_correction",
      "question": "The reason I left was because the noise.",
      "answer": "The reason I left was the noise.",
      "instruction": "Reason cleft — because",
      "explanation": "The reason was… — no «because»."
    },
    {
      "type": "error_correction",
      "question": "What she did was to resigned.",
      "answer": "What she did was resign.",
      "instruction": "Wh-cleft — infinitive",
      "explanation": "What she did was resign (no «to resigned»)."
    },
    {
      "type": "error_correction",
      "question": "It was yesterday when it happened.",
      "answer": "It was yesterday that it happened.",
      "instruction": "It-cleft — time",
      "explanation": "It was yesterday that… — not when."
    },
    {
      "type": "error_correction",
      "question": "It is you who I need him.",
      "answer": "It is you that I need.",
      "instruction": "It-cleft — object",
      "explanation": "It is you that I need."
    },
    {
      "type": "error_correction",
      "question": "What worries me are the price.",
      "answer": "What worries me is the price.",
      "instruction": "Wh-cleft — agreement",
      "explanation": "What… is (singular)."
    },
    {
      "type": "error_correction",
      "question": "It was because of the rain why we cancelled.",
      "answer": "It was because of the rain that we cancelled.",
      "instruction": "It-cleft — reason",
      "explanation": "…that we cancelled, not why."
    },
    {
      "type": "error_correction",
      "question": "I do understands you.",
      "answer": "I do understand you.",
      "instruction": "Emphatic do",
      "explanation": "do + base verb (understand)."
    },
    {
      "type": "error_correction",
      "question": "It was here when we first kissed.",
      "answer": "It was here that we first kissed.",
      "instruction": "It-cleft — place",
      "explanation": "It was here that…"
    },
    {
      "type": "error_correction",
      "question": "What I want is peace and quiet and silence.",
      "answer": "What I want is peace and quiet.",
      "instruction": "Wh-cleft — redundancy",
      "explanation": "peace and quiet already implies silence."
    },
    {
      "type": "error_correction",
      "question": "It was them who won the competition.",
      "answer": "It was they who won the competition.",
      "instruction": "It-cleft — formal subject",
      "explanation": "Formal: It was they who…",
      "acceptableAnswers": [
        "It was them who won the competition"
      ]
    },
    {
      "type": "error_correction",
      "question": "It is now when we must act.",
      "answer": "It is now that we must act.",
      "instruction": "It-cleft — time",
      "explanation": "It is now that…"
    },
    {
      "type": "error_correction",
      "question": "What happened was a disaster and terrible.",
      "answer": "What happened was a disaster.",
      "instruction": "Wh-cleft — pleonasm",
      "explanation": "a disaster = terrible — redundant."
    },
    {
      "type": "error_correction",
      "question": "I do not agrees.",
      "answer": "I do not agree.",
      "instruction": "Emphatic do",
      "explanation": "do + base verb (agree)."
    },
    {
      "type": "error_correction",
      "question": "It was this book who changed my life.",
      "answer": "It was this book that changed my life.",
      "instruction": "It-cleft — thing",
      "explanation": "Thing → that, not who."
    },
    {
      "type": "error_correction",
      "question": "What matters are honesty.",
      "answer": "What matters is honesty.",
      "instruction": "Wh-cleft — agreement",
      "explanation": "What matters is… (singular)."
    },
    {
      "type": "error_correction",
      "question": "What I need is to a holiday.",
      "answer": "What I need is a holiday.",
      "instruction": "Wh-cleft — article",
      "explanation": "is a holiday — no «to»."
    },
    {
      "type": "sentence_building",
      "question": "It / was / Maria / who / called",
      "options": [
        "It",
        "was",
        "Maria",
        "who",
        "called"
      ],
      "answer": "It was Maria who called",
      "instruction": "It-cleft person",
      "explanation": "It was Maria who…"
    },
    {
      "type": "sentence_building",
      "question": "What / surprised / me / was / his / silence",
      "options": [
        "What",
        "surprised",
        "me",
        "was",
        "his",
        "silence"
      ],
      "answer": "What surprised me was his silence",
      "instruction": "Wh-cleft",
      "explanation": "What surprised me was…"
    },
    {
      "type": "sentence_building",
      "question": "It / is / today / that / we / decide",
      "options": [
        "It",
        "is",
        "today",
        "that",
        "we",
        "decide"
      ],
      "answer": "It is today that we decide",
      "instruction": "It-cleft time",
      "explanation": "It is today that…"
    },
    {
      "type": "sentence_building",
      "question": "What / I / want / is / peace",
      "options": [
        "What",
        "I",
        "want",
        "is",
        "peace"
      ],
      "answer": "What I want is peace",
      "instruction": "Wh-cleft object",
      "explanation": "What I want is…"
    },
    {
      "type": "sentence_building",
      "question": "It / was / in / 2020 / that / it / started",
      "options": [
        "It",
        "was",
        "in",
        "2020",
        "that",
        "it",
        "started"
      ],
      "answer": "It was in 2020 that it started",
      "instruction": "It-cleft year",
      "explanation": "It was in 2020 that…"
    },
    {
      "type": "sentence_building",
      "question": "Never / have / I / felt / so / lost",
      "options": [
        "Never",
        "have",
        "I",
        "felt",
        "so",
        "lost"
      ],
      "answer": "Never have I felt so lost",
      "instruction": "Negative inversion",
      "explanation": "Never have I…"
    },
    {
      "type": "sentence_building",
      "question": "Only / then / did / I / understand",
      "options": [
        "Only",
        "then",
        "did",
        "I",
        "understand"
      ],
      "answer": "Only then did I understand",
      "instruction": "Only inversion",
      "explanation": "Only then did I…"
    },
    {
      "type": "sentence_building",
      "question": "It / was / because / of / rain / that / we / stayed",
      "options": [
        "It",
        "was",
        "because",
        "of",
        "rain",
        "that",
        "we",
        "stayed"
      ],
      "answer": "It was because of rain that we stayed",
      "instruction": "Reason cleft",
      "explanation": "It was because of…"
    },
    {
      "type": "sentence_building",
      "question": "What / they / need / is / time",
      "options": [
        "What",
        "they",
        "need",
        "is",
        "time"
      ],
      "answer": "What they need is time",
      "instruction": "Wh-cleft need",
      "explanation": "What they need is…"
    },
    {
      "type": "sentence_building",
      "question": "It / was / the / manager / who / approved / it",
      "options": [
        "It",
        "was",
        "the",
        "manager",
        "who",
        "approved",
        "it"
      ],
      "answer": "It was the manager who approved it",
      "instruction": "Work cleft",
      "explanation": "It was the manager who…"
    },
    {
      "type": "sentence_building",
      "question": "So / intense / was / the / heat / that / we / left",
      "options": [
        "So",
        "intense",
        "was",
        "the",
        "heat",
        "that",
        "we",
        "left"
      ],
      "answer": "So intense was the heat that we left",
      "instruction": "So inversion",
      "explanation": "So intense was…"
    },
    {
      "type": "sentence_building",
      "question": "It / is / here / that / history / was / made",
      "options": [
        "It",
        "is",
        "here",
        "that",
        "history",
        "was",
        "made"
      ],
      "answer": "It is here that history was made",
      "instruction": "Place cleft",
      "explanation": "It is here that…"
    },
    {
      "type": "sentence_building",
      "question": "What / matters / most / is / honesty",
      "options": [
        "What",
        "matters",
        "most",
        "is",
        "honesty"
      ],
      "answer": "What matters most is honesty",
      "instruction": "Wh-cleft value",
      "explanation": "What matters most is…"
    },
    {
      "type": "sentence_building",
      "question": "I / do / hope / you / understand",
      "options": [
        "I",
        "do",
        "hope",
        "you",
        "understand"
      ],
      "answer": "I do hope you understand",
      "instruction": "Emphatic do",
      "explanation": "I do hope…"
    },
    {
      "type": "sentence_building",
      "question": "Little / did / she / know / what / awaited",
      "options": [
        "Little",
        "did",
        "she",
        "know",
        "what",
        "awaited"
      ],
      "answer": "Little did she know what awaited",
      "instruction": "Little inversion",
      "explanation": "Little did she know…"
    },
    {
      "type": "sentence_building",
      "question": "It / was / not / John / but / Peter / who / came",
      "options": [
        "It",
        "was",
        "not",
        "John",
        "but",
        "Peter",
        "who",
        "came"
      ],
      "answer": "It was not John but Peter who came",
      "instruction": "Contrast cleft",
      "explanation": "not John but Peter…"
    },
    {
      "type": "sentence_building",
      "question": "What / we / discovered / was / unexpected",
      "options": [
        "What",
        "we",
        "discovered",
        "was",
        "unexpected"
      ],
      "answer": "What we discovered was unexpected",
      "instruction": "Discovery cleft",
      "explanation": "What we discovered was…"
    },
    {
      "type": "sentence_building",
      "question": "Rarely / have / I / seen / such / talent",
      "options": [
        "Rarely",
        "have",
        "I",
        "seen",
        "such",
        "talent"
      ],
      "answer": "Rarely have I seen such talent",
      "instruction": "Rarely inversion",
      "explanation": "Rarely have I…"
    },
    {
      "type": "sentence_building",
      "question": "It / was / with / great / joy / that / she / accepted",
      "options": [
        "It",
        "was",
        "with",
        "great",
        "joy",
        "that",
        "she",
        "accepted"
      ],
      "answer": "It was with great joy that she accepted",
      "instruction": "Manner cleft",
      "explanation": "It was with great joy that…"
    }
  ],
  "eng-ch24-unspoken": [
    {
      "type": "translation",
      "question": "Пойдёт дождь? — Надеюсь, нет.",
      "answer": "Will it rain? — I hope not",
      "instruction": "Negative substitution",
      "explanation": "I hope not = I hope it won't rain."
    },
    {
      "type": "translation",
      "question": "Я люблю джаз. — И я.",
      "answer": "I love jazz. — So do I",
      "instruction": "Positive agreement",
      "explanation": "So do I — inversion."
    },
    {
      "type": "translation",
      "question": "Я не умею плавать. — И я не умею.",
      "answer": "I can't swim. — Neither can I",
      "instruction": "Negative agreement",
      "explanation": "Neither can I."
    },
    {
      "type": "translation",
      "question": "Она бегает быстрее меня.",
      "answer": "She runs faster than I do",
      "instruction": "Verb substitution",
      "explanation": "than I do — do replaces verb."
    },
    {
      "type": "translation",
      "question": "Какой торт ты хочешь? — Шоколадный.",
      "answer": "Which cake would you like? — The chocolate one",
      "instruction": "One substitution",
      "explanation": "the chocolate one."
    },
    {
      "type": "translation",
      "question": "Ты придёшь? — Надеюсь, да.",
      "answer": "Will you come? — I hope so",
      "instruction": "Positive substitution",
      "explanation": "I hope so = I hope you will come."
    },
    {
      "type": "translation",
      "question": "Я тоже был в Перу.",
      "answer": "I have been to Peru too. — So have I",
      "instruction": "Perfect agreement",
      "explanation": "So have I.",
      "acceptableAnswers": [
        "So have I"
      ]
    },
    {
      "type": "translation",
      "question": "Я не люблю оливки. — И я.",
      "answer": "I don't like olives. — Neither do I",
      "instruction": "Negative agreement",
      "explanation": "Neither do I."
    },
    {
      "type": "translation",
      "question": "Он работает больше, чем я.",
      "answer": "He works harder than I do",
      "instruction": "Do substitution",
      "explanation": "than I do."
    },
    {
      "type": "translation",
      "question": "Хочешь чай или кофе? — Чай, пожалуйста.",
      "answer": "Would you like tea or coffee? — Tea, please",
      "instruction": "Ellipsis",
      "explanation": "Tea, please — subject/verb omitted."
    },
    {
      "type": "translation",
      "question": "Кто-нибудь звонил? — Да, звонил.",
      "answer": "Did anyone call? — Yes, someone did",
      "instruction": "Auxiliary substitution",
      "explanation": "someone did — did replaces called."
    },
    {
      "type": "translation",
      "question": "Ты видел этот фильм? — Нет, не видел.",
      "answer": "Have you seen this film? — No, I haven't",
      "instruction": "Perfect ellipsis",
      "explanation": "No, I haven't — ellipsis."
    },
    {
      "type": "translation",
      "question": "Она может помочь, а я — нет.",
      "answer": "She can help, but I can't",
      "instruction": "Modal ellipsis",
      "explanation": "I can't — can't replaces can't help."
    },
    {
      "type": "translation",
      "question": "Я бы поехал, если бы мог.",
      "answer": "I would go if I could",
      "instruction": "Conditional ellipsis",
      "explanation": "if I could — ellipsis of go."
    },
    {
      "type": "translation",
      "question": "Он сказал, что придёт, и пришёл.",
      "answer": "He said he would come, and he did",
      "instruction": "Do substitution — past",
      "explanation": "he did = he came."
    },
    {
      "type": "translation",
      "question": "Ты хочешь красное или белое вино? — Красное.",
      "answer": "Do you want red or white wine? — Red",
      "instruction": "Adjective ellipsis",
      "explanation": "Red = red wine."
    },
    {
      "type": "translation",
      "question": "Я не могу сегодня, но завтра — смогу.",
      "answer": "I can't today, but I can tomorrow",
      "instruction": "Time ellipsis",
      "explanation": "I can tomorrow = I can come tomorrow."
    },
    {
      "type": "translation",
      "question": "Она играет лучше, чем когда-либо.",
      "answer": "She plays better than ever",
      "instruction": "Comparative ellipsis",
      "explanation": "than ever — ellipsis."
    },
    {
      "type": "translation",
      "question": "Ты был там? — Нет.",
      "answer": "Were you there? — No",
      "instruction": "Short answer",
      "explanation": "No — ellipsis of I wasn't."
    },
    {
      "type": "translation",
      "question": "Можешь помочь? — Конечно.",
      "answer": "Can you help? — Of course",
      "instruction": "Ellipsis response",
      "explanation": "Of course = of course I can."
    },
    {
      "type": "sentence_building",
      "question": "A / Would / you / like / tea? / B / I'd / love / some",
      "options": [
        "A",
        "Would",
        "you",
        "like",
        "tea?",
        "B",
        "I'd",
        "love",
        "some"
      ],
      "answer": "A: Would you like tea? B: I'd love some",
      "instruction": "Ellipsis some",
      "explanation": "I'd love some = some tea"
    },
    {
      "type": "sentence_building",
      "question": "I / can / swim / Can / you?",
      "options": [
        "I",
        "can",
        "swim",
        "Can",
        "you?"
      ],
      "answer": "I can swim. Can you?",
      "instruction": "Modal ellipsis",
      "explanation": "Can you? = Can you swim?"
    },
    {
      "type": "sentence_building",
      "question": "She / works / harder / than / he / does",
      "options": [
        "She",
        "works",
        "harder",
        "than",
        "he",
        "does"
      ],
      "answer": "She works harder than he does",
      "instruction": "Than he does",
      "explanation": "he does = he works"
    },
    {
      "type": "sentence_building",
      "question": "Will / it / work? / I / hope / so",
      "options": [
        "Will",
        "it",
        "work?",
        "I",
        "hope",
        "so"
      ],
      "answer": "Will it work? I hope so",
      "instruction": "Hope so",
      "explanation": "I hope so"
    },
    {
      "type": "sentence_building",
      "question": "Are / you / coming? / I'm / afraid / not",
      "options": [
        "Are",
        "you",
        "coming?",
        "I'm",
        "afraid",
        "not"
      ],
      "answer": "Are you coming? I'm afraid not",
      "instruction": "Afraid not",
      "explanation": "I'm afraid not"
    },
    {
      "type": "sentence_building",
      "question": "I / don't / like / it / Neither / do / I",
      "options": [
        "I",
        "don't",
        "like",
        "it",
        "Neither",
        "do",
        "I"
      ],
      "answer": "I don't like it. Neither do I",
      "instruction": "Neither do I",
      "explanation": "Neither do I"
    },
    {
      "type": "sentence_building",
      "question": "Who / wants / coffee? / I / do",
      "options": [
        "Who",
        "wants",
        "coffee?",
        "I",
        "do"
      ],
      "answer": "Who wants coffee? I do",
      "instruction": "I do substitution",
      "explanation": "I do = I want coffee"
    },
    {
      "type": "sentence_building",
      "question": "Take / the / blue / one / not / the / red",
      "options": [
        "Take",
        "the",
        "blue",
        "one",
        "not",
        "the",
        "red"
      ],
      "answer": "Take the blue one, not the red",
      "instruction": "One substitution",
      "explanation": "the red = the red one"
    },
    {
      "type": "sentence_building",
      "question": "She / speaks / French / So / does / her / brother",
      "options": [
        "She",
        "speaks",
        "French",
        "So",
        "does",
        "her",
        "brother"
      ],
      "answer": "She speaks French. So does her brother",
      "instruction": "So does",
      "explanation": "So does her brother"
    },
    {
      "type": "sentence_building",
      "question": "I'd / rather / not / if / you / don't / mind",
      "options": [
        "I'd",
        "rather",
        "not",
        "if",
        "you",
        "don't",
        "mind"
      ],
      "answer": "I'd rather not, if you don't mind",
      "instruction": "Rather not",
      "explanation": "I'd rather not"
    },
    {
      "type": "sentence_building",
      "question": "Have / you / finished? / Not / yet",
      "options": [
        "Have",
        "you",
        "finished?",
        "Not",
        "yet"
      ],
      "answer": "Have you finished? Not yet",
      "instruction": "Not yet",
      "explanation": "Not yet"
    },
    {
      "type": "sentence_building",
      "question": "Can / you / help? / I'd / be / glad / to",
      "options": [
        "Can",
        "you",
        "help?",
        "I'd",
        "be",
        "glad",
        "to"
      ],
      "answer": "Can you help? I'd be glad to",
      "instruction": "Glad to",
      "explanation": "I'd be glad to help"
    },
    {
      "type": "sentence_building",
      "question": "Will / she / agree? / I / expect / so",
      "options": [
        "Will",
        "she",
        "agree?",
        "I",
        "expect",
        "so"
      ],
      "answer": "Will she agree? I expect so",
      "instruction": "Expect so",
      "explanation": "I expect so"
    },
    {
      "type": "sentence_building",
      "question": "He / runs / fast / So / do / I",
      "options": [
        "He",
        "runs",
        "fast",
        "So",
        "do",
        "I"
      ],
      "answer": "He runs fast. So do I",
      "instruction": "So do I run",
      "explanation": "So do I"
    },
    {
      "type": "sentence_building",
      "question": "Pass / the / salt / please / Here / you / are",
      "options": [
        "Pass",
        "the",
        "salt",
        "please",
        "Here",
        "you",
        "are"
      ],
      "answer": "Pass the salt, please. Here you are",
      "instruction": "Dialogue ellipsis",
      "explanation": "Short dialogue"
    }
  ],
  "eng-ch25-between-lines": [
    {
      "type": "error_correction",
      "question": "It could be argue that the policy failed.",
      "answer": "It could be argued that the policy failed.",
      "instruction": "Passive hedge",
      "explanation": "could be argued — past participle."
    },
    {
      "type": "error_correction",
      "question": "The results prove to suggest a link.",
      "answer": "The results appear to suggest a link.",
      "instruction": "Hedging verb",
      "explanation": "appear/seem — not prove (too strong)."
    },
    {
      "type": "error_correction",
      "question": "I am wonder if you could help me.",
      "answer": "I was wondering if you could help me.",
      "instruction": "Distancing tense",
      "explanation": "I was wondering — polite distancing."
    },
    {
      "type": "error_correction",
      "question": "It is possible that the data is wrong.",
      "answer": "It is possible that the data are wrong.",
      "instruction": "Formal agreement",
      "explanation": "data can take plural in formal register.",
      "acceptableAnswers": [
        "It is possible that the data is wrong"
      ]
    },
    {
      "type": "error_correction",
      "question": "The policy has definitely failed.",
      "answer": "The policy may have failed.",
      "instruction": "Hedge strong claim",
      "explanation": "may have failed — hedged."
    },
    {
      "type": "error_correction",
      "question": "I think you are completely wrong.",
      "answer": "I'm not entirely sure I agree.",
      "instruction": "Polite disagreement",
      "explanation": "I'm not entirely sure I agree — softened."
    },
    {
      "type": "error_correction",
      "question": "This proves the theory.",
      "answer": "This would seem to support the theory.",
      "instruction": "Academic hedge",
      "explanation": "would seem to support — hedged."
    },
    {
      "type": "error_correction",
      "question": "Everyone knows this is true.",
      "answer": "It is widely accepted that this is the case.",
      "instruction": "Hedging generalisation",
      "explanation": "It is widely accepted — not everyone knows."
    },
    {
      "type": "error_correction",
      "question": "The results are wrong.",
      "answer": "The results may be open to interpretation.",
      "instruction": "Hedging certainty",
      "explanation": "may be open to interpretation."
    },
    {
      "type": "error_correction",
      "question": "You must change your approach.",
      "answer": "You might want to consider changing your approach.",
      "instruction": "Soft suggestion",
      "explanation": "might want to consider — hedged advice."
    },
    {
      "type": "error_correction",
      "question": "This is the best solution.",
      "answer": "This would appear to be a viable solution.",
      "instruction": "Understatement / hedge",
      "explanation": "would appear to be a viable — hedged."
    },
    {
      "type": "error_correction",
      "question": "I disagree with you completely.",
      "answer": "I see what you mean, but I'm not sure I'd go that far.",
      "instruction": "Polite disagreement",
      "explanation": "I see what you mean, but…"
    },
    {
      "type": "error_correction",
      "question": "The experiment failed because of bad design.",
      "answer": "The experiment may have been affected by design limitations.",
      "instruction": "Hedging cause",
      "explanation": "may have been affected — hedged causation."
    },
    {
      "type": "error_correction",
      "question": "She is obviously lying.",
      "answer": "She may not be telling the whole truth.",
      "instruction": "Hedging accusation",
      "explanation": "may not be telling the whole truth."
    },
    {
      "type": "error_correction",
      "question": "This will definitely work.",
      "answer": "This should work in most cases.",
      "instruction": "Hedging prediction",
      "explanation": "should work in most cases."
    },
    {
      "type": "error_correction",
      "question": "The author is wrong.",
      "answer": "The author's position is open to question.",
      "instruction": "Academic hedge",
      "explanation": "open to question — hedged critique."
    },
    {
      "type": "error_correction",
      "question": "We know the answer.",
      "answer": "We have some indication of what the answer might be.",
      "instruction": "Hedging knowledge",
      "explanation": "some indication… might be."
    },
    {
      "type": "error_correction",
      "question": "It's a disaster.",
      "answer": "It's not ideal, to put it mildly.",
      "instruction": "British understatement",
      "explanation": "not ideal, to put it mildly — understatement."
    },
    {
      "type": "error_correction",
      "question": "He's incompetent.",
      "answer": "He may not be fully suited to the role.",
      "instruction": "Hedging criticism",
      "explanation": "may not be fully suited — hedged."
    },
    {
      "type": "error_correction",
      "question": "The plan will fail.",
      "answer": "There is a risk that the plan may not succeed.",
      "instruction": "Formal hedge",
      "explanation": "There is a risk that… may not succeed."
    },
    {
      "type": "sentence_building",
      "question": "It / would / seem / that / costs / have / risen",
      "options": [
        "It",
        "would",
        "seem",
        "that",
        "costs",
        "have",
        "risen"
      ],
      "answer": "It would seem that costs have risen",
      "instruction": "Soft claim",
      "explanation": "It would seem that…"
    },
    {
      "type": "sentence_building",
      "question": "The / data / tend / to / suggest / a / pattern",
      "options": [
        "The",
        "data",
        "tend",
        "to",
        "suggest",
        "a",
        "pattern"
      ],
      "answer": "The data tend to suggest a pattern",
      "instruction": "Hedged suggest",
      "explanation": "tend to suggest"
    },
    {
      "type": "sentence_building",
      "question": "I / would / hesitate / to / call / it / a / failure",
      "options": [
        "I",
        "would",
        "hesitate",
        "to",
        "call",
        "it",
        "a",
        "failure"
      ],
      "answer": "I would hesitate to call it a failure",
      "instruction": "Hedge failure",
      "explanation": "would hesitate to…"
    },
    {
      "type": "sentence_building",
      "question": "There / is / some / evidence / to / support / this / view",
      "options": [
        "There",
        "is",
        "some",
        "evidence",
        "to",
        "support",
        "this",
        "view"
      ],
      "answer": "There is some evidence to support this view",
      "instruction": "Evidence hedge",
      "explanation": "some evidence"
    },
    {
      "type": "sentence_building",
      "question": "One / might / plausibly / argue / otherwise",
      "options": [
        "One",
        "might",
        "plausibly",
        "argue",
        "otherwise"
      ],
      "answer": "One might plausibly argue otherwise",
      "instruction": "Might argue",
      "explanation": "One might plausibly…"
    },
    {
      "type": "sentence_building",
      "question": "The / outcome / is / by / no / means / certain",
      "options": [
        "The",
        "outcome",
        "is",
        "by",
        "no",
        "means",
        "certain"
      ],
      "answer": "The outcome is by no means certain",
      "instruction": "By no means",
      "explanation": "by no means certain"
    },
    {
      "type": "sentence_building",
      "question": "It / is / not / unreasonable / to / assume / as / much",
      "options": [
        "It",
        "is",
        "not",
        "unreasonable",
        "to",
        "assume",
        "as",
        "much"
      ],
      "answer": "It is not unreasonable to assume as much",
      "instruction": "Not unreasonable",
      "explanation": "not unreasonable to assume"
    },
    {
      "type": "sentence_building",
      "question": "To / a / certain / extent / I / share / that / view",
      "options": [
        "To",
        "a",
        "certain",
        "extent",
        "I",
        "share",
        "that",
        "view"
      ],
      "answer": "To a certain extent, I share that view",
      "instruction": "To a certain extent",
      "explanation": "To a certain extent…"
    },
    {
      "type": "sentence_building",
      "question": "The / figures / are / somewhat / inconclusive",
      "options": [
        "The",
        "figures",
        "are",
        "somewhat",
        "inconclusive"
      ],
      "answer": "The figures are somewhat inconclusive",
      "instruction": "Somewhat",
      "explanation": "somewhat inconclusive"
    },
    {
      "type": "sentence_building",
      "question": "I / wouldn't / go / quite / that / far",
      "options": [
        "I",
        "wouldn't",
        "go",
        "quite",
        "that",
        "far"
      ],
      "answer": "I wouldn't go quite that far",
      "instruction": "Polite limit",
      "explanation": "wouldn't go quite that far"
    },
    {
      "type": "sentence_building",
      "question": "It / may / well / be / that / we / were / wrong",
      "options": [
        "It",
        "may",
        "well",
        "be",
        "that",
        "we",
        "were",
        "wrong"
      ],
      "answer": "It may well be that we were wrong",
      "instruction": "May well be",
      "explanation": "It may well be that…"
    },
    {
      "type": "sentence_building",
      "question": "The / report / is / less / than / definitive",
      "options": [
        "The",
        "report",
        "is",
        "less",
        "than",
        "definitive"
      ],
      "answer": "The report is less than definitive",
      "instruction": "Understatement",
      "explanation": "less than definitive"
    },
    {
      "type": "sentence_building",
      "question": "One / could / make / a / case / for / either / side",
      "options": [
        "One",
        "could",
        "make",
        "a",
        "case",
        "for",
        "either",
        "side"
      ],
      "answer": "One could make a case for either side",
      "instruction": "Make a case",
      "explanation": "One could make a case…"
    },
    {
      "type": "sentence_building",
      "question": "Strictly / speaking / that / isn't / accurate",
      "options": [
        "Strictly",
        "speaking",
        "that",
        "isn't",
        "accurate"
      ],
      "answer": "Strictly speaking, that isn't accurate",
      "instruction": "Strictly speaking",
      "explanation": "Strictly speaking…"
    },
    {
      "type": "sentence_building",
      "question": "The / situation / is / rather / more / complex",
      "options": [
        "The",
        "situation",
        "is",
        "rather",
        "more",
        "complex"
      ],
      "answer": "The situation is rather more complex",
      "instruction": "Rather",
      "explanation": "rather more complex"
    }
  ]
} as const;
