/** Hand-crafted supplements — generated by scripts/build-curated-supplements.mjs */
export const SPANISH_CURATED_SUPPLEMENTS = {
  "chapter-2-primer-dialogo": [
    {
      "type": "translation",
      "question": "Я встаю в семь утра.",
      "answer": "Me levanto a las siete",
      "instruction": "Presente — утренние рутины",
      "explanation": "Me levanto = встаю. a las siete = в семь."
    },
    {
      "type": "translation",
      "question": "Мы завтракаем вместе каждое утро.",
      "answer": "Desayunamos juntos cada mañana",
      "instruction": "Presente nosotros",
      "explanation": "Desayunamos — завтракаем (nosotros)."
    },
    {
      "type": "translation",
      "question": "Она читает книгу каждый вечер.",
      "answer": "Ella lee un libro cada noche",
      "instruction": "Presente ella",
      "explanation": "Ella lee — читает. cada noche = каждый вечер."
    },
    {
      "type": "translation",
      "question": "Они учатся в университете.",
      "answer": "Estudian en la universidad",
      "instruction": "Presente ellos",
      "explanation": "Ellos → estudian (-ar). Sin pronombre posible."
    },
    {
      "type": "translation",
      "question": "Ты готовишь ужин сегодня?",
      "answer": "¿Cocinas la cena hoy?",
      "instruction": "Presente tú — вопрос",
      "explanation": "¿Cocinas…? — готовишь ли ты."
    },
    {
      "type": "translation",
      "question": "Я мою зубы два раза в день.",
      "answer": "Me lavo los dientes dos veces al día",
      "instruction": "Reflexivo + rutina",
      "explanation": "Me lavo = мою (себе). dos veces al día."
    },
    {
      "type": "translation",
      "question": "Мой брат работает в больнице.",
      "answer": "Mi hermano trabaja en un hospital",
      "instruction": "Presente — trabajo",
      "explanation": "Trabaja en un hospital."
    },
    {
      "type": "translation",
      "question": "Мы ужинаем в восемь часов.",
      "answer": "Cenamos a las ocho",
      "instruction": "Presente — cenar",
      "explanation": "Cenamos a las ocho = ужинаем в восемь."
    },
    {
      "type": "translation",
      "question": "Он слушает музыку по дороге на работу.",
      "answer": "Escucha música camino al trabajo",
      "instruction": "Presente él",
      "explanation": "Escucha música. camino al trabajo = по дороге на работу."
    },
    {
      "type": "sentence_building",
      "question": "Me / levanto / a / las / siete / de / la / mañana",
      "options": [
        "Me",
        "levanto",
        "a",
        "las",
        "siete",
        "de",
        "la",
        "mañana"
      ],
      "answer": "Me levanto a las siete de la mañana",
      "instruction": "Соберите утреннюю рутину",
      "explanation": "Me levanto + hora."
    },
    {
      "type": "sentence_building",
      "question": "Desayunamos / juntos / cada / mañana",
      "options": [
        "Desayunamos",
        "juntos",
        "cada",
        "mañana"
      ],
      "answer": "Desayunamos juntos cada mañana",
      "instruction": "Соберите фразу о завтраке",
      "explanation": "Desayunamos = мы завтракаем."
    },
    {
      "type": "sentence_building",
      "question": "Ella / lee / un / libro / cada / noche",
      "options": [
        "Ella",
        "lee",
        "un",
        "libro",
        "cada",
        "noche"
      ],
      "answer": "Ella lee un libro cada noche",
      "instruction": "Соберите вечернюю привычку",
      "explanation": "Ella lee — presente."
    },
    {
      "type": "sentence_building",
      "question": "Yo / estudio / español / todos / los / días",
      "options": [
        "Yo",
        "estudio",
        "español",
        "todos",
        "los",
        "días"
      ],
      "answer": "Yo estudio español todos los días",
      "instruction": "Соберите ежедневную практику",
      "explanation": "Estudio español todos los días."
    },
    {
      "type": "sentence_building",
      "question": "¿Cocinas / la / cena / esta / noche?",
      "options": [
        "¿Cocinas",
        "la",
        "cena",
        "esta",
        "noche?"
      ],
      "answer": "¿Cocinas la cena esta noche?",
      "instruction": "Соберите вопрос",
      "explanation": "¿Cocinas…? — tú."
    },
    {
      "type": "sentence_building",
      "question": "Me / lavo / los / dientes / dos / veces / al / día",
      "options": [
        "Me",
        "lavo",
        "los",
        "dientes",
        "dos",
        "veces",
        "al",
        "día"
      ],
      "answer": "Me lavo los dientes dos veces al día",
      "instruction": "Соберите гигиену",
      "explanation": "Reflexivo: me lavo."
    },
    {
      "type": "sentence_building",
      "question": "Mi / hermano / trabaja / en / un / hospital",
      "options": [
        "Mi",
        "hermano",
        "trabaja",
        "en",
        "un",
        "hospital"
      ],
      "answer": "Mi hermano trabaja en un hospital",
      "instruction": "Соберите фразу о работе",
      "explanation": "Trabaja en un hospital."
    },
    {
      "type": "sentence_building",
      "question": "Cenamos / a / las / ocho / en / familia",
      "options": [
        "Cenamos",
        "a",
        "las",
        "ocho",
        "en",
        "familia"
      ],
      "answer": "Cenamos a las ocho en familia",
      "instruction": "Соберите ужин",
      "explanation": "Cenamos a las ocho."
    }
  ],
  "chapter-3-biblioteca": [
    {
      "type": "translation",
      "question": "В библиотеке есть книга.",
      "answer": "Hay un libro en la biblioteca",
      "instruction": "Hay + artículo",
      "explanation": "Hay un libro en la biblioteca."
    },
    {
      "type": "translation",
      "question": "Где газета?",
      "answer": "¿Dónde está el periódico?",
      "instruction": "El + sustantivo",
      "explanation": "El periódico — определённый артикль."
    },
    {
      "type": "translation",
      "question": "Мне нужна синяя ручка.",
      "answer": "Necesito un bolígrafo azul",
      "instruction": "Un + adjetivo",
      "explanation": "Un bolígrafo azul."
    },
    {
      "type": "translation",
      "question": "На столе лежит журнал.",
      "answer": "Hay una revista en la mesa",
      "instruction": "Hay + una",
      "explanation": "Una revista — женский род."
    },
    {
      "type": "translation",
      "question": "Это интересная статья.",
      "answer": "Es un artículo interesante",
      "instruction": "Un artículo",
      "explanation": "Un artículo interesante."
    },
    {
      "type": "translation",
      "question": "В комнате нет стульев.",
      "answer": "No hay sillas en la habitación",
      "instruction": "No hay + plural",
      "explanation": "No hay sillas — отрицание."
    },
    {
      "type": "translation",
      "question": "Я ищу словарь испанского языка.",
      "answer": "Busco un diccionario de español",
      "instruction": "Buscar + un",
      "explanation": "Busco un diccionario de español."
    },
    {
      "type": "translation",
      "question": "Где находится туалет?",
      "answer": "¿Dónde está el baño?",
      "instruction": "El baño",
      "explanation": "¿Dónde está el baño?"
    },
    {
      "type": "translation",
      "question": "Есть ли здесь Wi-Fi?",
      "answer": "¿Hay Wi-Fi aquí?",
      "instruction": "Hay — вопрос",
      "explanation": "¿Hay Wi-Fi aquí?"
    },
    {
      "type": "sentence_building",
      "question": "Hay / un / libro / en / la / biblioteca",
      "options": [
        "Hay",
        "un",
        "libro",
        "en",
        "la",
        "biblioteca"
      ],
      "answer": "Hay un libro en la biblioteca",
      "instruction": "Соберите hay + un",
      "explanation": "Hay un libro…"
    },
    {
      "type": "sentence_building",
      "question": "¿Dónde / está / el / periódico?",
      "options": [
        "¿Dónde",
        "está",
        "el",
        "periódico?"
      ],
      "answer": "¿Dónde está el periódico?",
      "instruction": "Соберите вопрос с el",
      "explanation": "El periódico."
    },
    {
      "type": "sentence_building",
      "question": "Necesito / un / bolígrafo / azul",
      "options": [
        "Necesito",
        "un",
        "bolígrafo",
        "azul"
      ],
      "answer": "Necesito un bolígrafo azul",
      "instruction": "Соберите un + adj",
      "explanation": "Un bolígrafo azul."
    },
    {
      "type": "sentence_building",
      "question": "Hay / una / revista / en / la / mesa",
      "options": [
        "Hay",
        "una",
        "revista",
        "en",
        "la",
        "mesa"
      ],
      "answer": "Hay una revista en la mesa",
      "instruction": "Соберите una",
      "explanation": "Una revista — femenino."
    },
    {
      "type": "sentence_building",
      "question": "Es / un / artículo / interesante",
      "options": [
        "Es",
        "un",
        "artículo",
        "interesante"
      ],
      "answer": "Es un artículo interesante",
      "instruction": "Соберите es + un",
      "explanation": "Es un artículo…"
    },
    {
      "type": "sentence_building",
      "question": "No / hay / sillas / en / la / habitación",
      "options": [
        "No",
        "hay",
        "sillas",
        "en",
        "la",
        "habitación"
      ],
      "answer": "No hay sillas en la habitación",
      "instruction": "Соберите no hay",
      "explanation": "No hay + plural."
    },
    {
      "type": "sentence_building",
      "question": "Busco / un / diccionario / de / español",
      "options": [
        "Busco",
        "un",
        "diccionario",
        "de",
        "español"
      ],
      "answer": "Busco un diccionario de español",
      "instruction": "Соберите buscar",
      "explanation": "Busco un diccionario…"
    },
    {
      "type": "sentence_building",
      "question": "¿Dónde / está / el / baño?",
      "options": [
        "¿Dónde",
        "está",
        "el",
        "baño?"
      ],
      "answer": "¿Dónde está el baño?",
      "instruction": "Соберите el baño",
      "explanation": "El baño — мужской род."
    },
    {
      "type": "sentence_building",
      "question": "¿Hay / Wi-Fi / aquí?",
      "options": [
        "¿Hay",
        "Wi-Fi",
        "aquí?"
      ],
      "answer": "¿Hay Wi-Fi aquí?",
      "instruction": "Соберите вопрос hay",
      "explanation": "¿Hay… aquí?"
    }
  ],
  "chapter-4-numeros-tiempo": [
    {
      "type": "sentence_building",
      "question": "Son / las / tres / y / cuarto",
      "options": [
        "Son",
        "las",
        "tres",
        "y",
        "cuarto"
      ],
      "answer": "Son las tres y cuarto",
      "instruction": "Соберите время",
      "explanation": "Son las tres y cuarto = 3:15."
    },
    {
      "type": "sentence_building",
      "question": "Es / media / noche",
      "options": [
        "Es",
        "media",
        "noche"
      ],
      "answer": "Es medianoche",
      "instruction": "Соберите полночь",
      "explanation": "Es medianoche — без las."
    }
  ],
  "chapter-5-mercado": [
    {
      "type": "translation",
      "question": "У меня есть два яблока.",
      "answer": "Tengo dos manzanas",
      "instruction": "Tener — количество",
      "explanation": "Tengo dos manzanas."
    },
    {
      "type": "translation",
      "question": "У неё мало денег.",
      "answer": "Ella tiene poco dinero",
      "instruction": "Tener poco",
      "explanation": "Tiene poco dinero."
    },
    {
      "type": "translation",
      "question": "У нас много работы.",
      "answer": "Tenemos mucho trabajo",
      "instruction": "Tener mucho",
      "explanation": "Tenemos mucho trabajo."
    },
    {
      "type": "translation",
      "question": "У тебя есть время?",
      "answer": "¿Tienes tiempo?",
      "instruction": "Tener — вопрос",
      "explanation": "¿Tienes tiempo?"
    },
    {
      "type": "translation",
      "question": "У меня болит голова.",
      "answer": "Tengo dolor de cabeza",
      "instruction": "Tener + sustantivo",
      "explanation": "Tengo dolor de cabeza."
    },
    {
      "type": "translation",
      "question": "У них есть большой дом.",
      "answer": "Tienen una casa grande",
      "instruction": "Tener + objeto",
      "explanation": "Tienen una casa grande."
    },
    {
      "type": "translation",
      "question": "Мне нужно купить хлеб.",
      "answer": "Tengo que comprar pan",
      "instruction": "Tener que + inf",
      "explanation": "Tengo que comprar pan."
    },
    {
      "type": "translation",
      "question": "У него три сестры.",
      "answer": "Tiene tres hermanas",
      "instruction": "Tener — familia",
      "explanation": "Tiene tres hermanas."
    },
    {
      "type": "translation",
      "question": "У меня нет машины.",
      "answer": "No tengo coche",
      "instruction": "No tener",
      "explanation": "No tengo coche (sin artículo)."
    },
    {
      "type": "sentence_building",
      "question": "Tengo / dos / manzanas / en / la / bolsa",
      "options": [
        "Tengo",
        "dos",
        "manzanas",
        "en",
        "la",
        "bolsa"
      ],
      "answer": "Tengo dos manzanas en la bolsa",
      "instruction": "Соберите tener + cantidad",
      "explanation": "Tengo dos manzanas."
    },
    {
      "type": "sentence_building",
      "question": "Ella / tiene / poco / dinero / hoy",
      "options": [
        "Ella",
        "tiene",
        "poco",
        "dinero",
        "hoy"
      ],
      "answer": "Ella tiene poco dinero hoy",
      "instruction": "Соберите poco",
      "explanation": "Tiene poco dinero."
    },
    {
      "type": "sentence_building",
      "question": "Tenemos / mucho / trabajo / esta / semana",
      "options": [
        "Tenemos",
        "mucho",
        "trabajo",
        "esta",
        "semana"
      ],
      "answer": "Tenemos mucho trabajo esta semana",
      "instruction": "Соберите mucho",
      "explanation": "Tenemos mucho trabajo."
    },
    {
      "type": "sentence_building",
      "question": "¿Tienes / tiempo / para / ayudarme?",
      "options": [
        "¿Tienes",
        "tiempo",
        "para",
        "ayudarme?"
      ],
      "answer": "¿Tienes tiempo para ayudarme?",
      "instruction": "Соберите вопрос",
      "explanation": "¿Tienes tiempo…?"
    },
    {
      "type": "sentence_building",
      "question": "Tengo / dolor / de / cabeza",
      "options": [
        "Tengo",
        "dolor",
        "de",
        "cabeza"
      ],
      "answer": "Tengo dolor de cabeza",
      "instruction": "Соберите tener + dolor",
      "explanation": "Tengo dolor de cabeza."
    },
    {
      "type": "sentence_building",
      "question": "Tienen / una / casa / grande / en / el / pueblo",
      "options": [
        "Tienen",
        "una",
        "casa",
        "grande",
        "en",
        "el",
        "pueblo"
      ],
      "answer": "Tienen una casa grande en el pueblo",
      "instruction": "Соберите tener + casa",
      "explanation": "Tienen una casa grande."
    },
    {
      "type": "sentence_building",
      "question": "Tengo / que / comprar / pan / y / leche",
      "options": [
        "Tengo",
        "que",
        "comprar",
        "pan",
        "y",
        "leche"
      ],
      "answer": "Tengo que comprar pan y leche",
      "instruction": "Соберите tener que",
      "explanation": "Tengo que + infinitivo."
    },
    {
      "type": "sentence_building",
      "question": "Tiene / tres / hermanas / mayores",
      "options": [
        "Tiene",
        "tres",
        "hermanas",
        "mayores"
      ],
      "answer": "Tiene tres hermanas mayores",
      "instruction": "Соберите familia",
      "explanation": "Tiene tres hermanas."
    },
    {
      "type": "sentence_building",
      "question": "No / tengo / coche / pero / tengo / bicicleta",
      "options": [
        "No",
        "tengo",
        "coche",
        "pero",
        "tengo",
        "bicicleta"
      ],
      "answer": "No tengo coche pero tengo bicicleta",
      "instruction": "Соберите no tener",
      "explanation": "No tengo coche."
    },
    {
      "type": "sentence_building",
      "question": "¿Cuánto / cuesta? / No / tengo / suficiente / dinero",
      "options": [
        "¿Cuánto",
        "cuesta?",
        "No",
        "tengo",
        "suficiente",
        "dinero"
      ],
      "answer": "¿Cuánto cuesta? No tengo suficiente dinero",
      "instruction": "Соберите на рынке",
      "explanation": "No tengo suficiente dinero."
    }
  ],
  "chapter-6-cuerpo": [
    {
      "type": "translation",
      "question": "Мне нравится плавание.",
      "answer": "Me gusta nadar",
      "instruction": "Gustar + infinitivo",
      "explanation": "Me gusta nadar."
    },
    {
      "type": "translation",
      "question": "Ей нравятся цветы.",
      "answer": "Le gustan las flores",
      "instruction": "Gustar plural",
      "explanation": "Le gustan las flores."
    },
    {
      "type": "translation",
      "question": "Нам нравится эта музыка.",
      "answer": "Nos gusta esta música",
      "instruction": "Gustar nosotros",
      "explanation": "Nos gusta esta música."
    },
    {
      "type": "translation",
      "question": "Тебе нравится этот фильм?",
      "answer": "¿Te gusta esta película?",
      "instruction": "Gustar — вопрос",
      "explanation": "¿Te gusta…?"
    },
    {
      "type": "translation",
      "question": "Ему не нравится холод.",
      "answer": "No le gusta el frío",
      "instruction": "Gustar negativo",
      "explanation": "No le gusta el frío."
    },
    {
      "type": "translation",
      "question": "Мне нравятся испанские блюда.",
      "answer": "Me gustan los platos españoles",
      "instruction": "Gustar + plural",
      "explanation": "Me gustan los platos españoles."
    },
    {
      "type": "translation",
      "question": "Ей нравится читать по вечерам.",
      "answer": "Le gusta leer por las tardes",
      "instruction": "Gustar + inf",
      "explanation": "Le gusta leer por las tardes."
    },
    {
      "type": "translation",
      "question": "Нам не нравится вставать рано.",
      "answer": "No nos gusta levantarnos temprano",
      "instruction": "Gustar + reflexivo",
      "explanation": "No nos gusta levantarnos temprano."
    },
    {
      "type": "translation",
      "question": "Тебе нравится твоя работа?",
      "answer": "¿Te gusta tu trabajo?",
      "instruction": "Gustar + sustantivo",
      "explanation": "¿Te gusta tu trabajo?"
    },
    {
      "type": "sentence_building",
      "question": "Me / gusta / nadar / en / verano",
      "options": [
        "Me",
        "gusta",
        "nadar",
        "en",
        "verano"
      ],
      "answer": "Me gusta nadar en verano",
      "instruction": "Соберите gustar + inf",
      "explanation": "Me gusta nadar."
    },
    {
      "type": "sentence_building",
      "question": "Le / gustan / las / flores / rojas",
      "options": [
        "Le",
        "gustan",
        "las",
        "flores",
        "rojas"
      ],
      "answer": "Le gustan las flores rojas",
      "instruction": "Соберите plural",
      "explanation": "Le gustan las flores."
    },
    {
      "type": "sentence_building",
      "question": "Nos / gusta / esta / música / latina",
      "options": [
        "Nos",
        "gusta",
        "esta",
        "música",
        "latina"
      ],
      "answer": "Nos gusta esta música latina",
      "instruction": "Соберите nos gusta",
      "explanation": "Nos gusta esta música."
    },
    {
      "type": "sentence_building",
      "question": "¿Te / gusta / esta / película?",
      "options": [
        "¿Te",
        "gusta",
        "esta",
        "película?"
      ],
      "answer": "¿Te gusta esta película?",
      "instruction": "Соберите вопрос",
      "explanation": "¿Te gusta…?"
    },
    {
      "type": "sentence_building",
      "question": "No / le / gusta / el / frío / del / invierno",
      "options": [
        "No",
        "le",
        "gusta",
        "el",
        "frío",
        "del",
        "invierno"
      ],
      "answer": "No le gusta el frío del invierno",
      "instruction": "Соберите отрицание",
      "explanation": "No le gusta el frío."
    },
    {
      "type": "sentence_building",
      "question": "Me / gustan / los / platos / españoles",
      "options": [
        "Me",
        "gustan",
        "los",
        "platos",
        "españoles"
      ],
      "answer": "Me gustan los platos españoles",
      "instruction": "Соберите plural gustan",
      "explanation": "Me gustan los platos."
    },
    {
      "type": "sentence_building",
      "question": "Le / gusta / leer / por / las / tardes",
      "options": [
        "Le",
        "gusta",
        "leer",
        "por",
        "las",
        "tardes"
      ],
      "answer": "Le gusta leer por las tardes",
      "instruction": "Соберите leer",
      "explanation": "Le gusta leer…"
    },
    {
      "type": "sentence_building",
      "question": "No / nos / gusta / levantarnos / temprano",
      "options": [
        "No",
        "nos",
        "gusta",
        "levantarnos",
        "temprano"
      ],
      "answer": "No nos gusta levantarnos temprano",
      "instruction": "Соберите reflexivo",
      "explanation": "Levantarnos — infinitivo reflexivo."
    },
    {
      "type": "sentence_building",
      "question": "¿Te / gusta / tu / trabajo / nuevo?",
      "options": [
        "¿Te",
        "gusta",
        "tu",
        "trabajo",
        "nuevo?"
      ],
      "answer": "¿Te gusta tu trabajo nuevo?",
      "instruction": "Соберите trabajo",
      "explanation": "¿Te gusta tu trabajo?"
    }
  ],
  "chapter-7-pasado-perfecto": [
    {
      "type": "translation",
      "question": "Я уже поел.",
      "answer": "Ya he comido",
      "instruction": "Pretérito perfecto",
      "explanation": "Ya he comido — уже поел."
    },
    {
      "type": "translation",
      "question": "Она никогда не была в Аргентине.",
      "answer": "Ella nunca ha estado en Argentina",
      "instruction": "Perfecto + nunca",
      "explanation": "Nunca ha estado en…"
    },
    {
      "type": "translation",
      "question": "Мы только что приехали.",
      "answer": "Acabamos de llegar",
      "instruction": "Acabar de + inf",
      "explanation": "Acabamos de llegar."
    },
    {
      "type": "translation",
      "question": "Ты когда-нибудь пробовал паэлью?",
      "answer": "¿Has probado alguna vez la paella?",
      "instruction": "Perfecto — вопрос",
      "explanation": "¿Has probado alguna vez…?"
    },
    {
      "type": "translation",
      "question": "Они ещё не закончили.",
      "answer": "Todavía no han terminado",
      "instruction": "Perfecto negativo",
      "explanation": "Todavía no han terminado."
    },
    {
      "type": "translation",
      "question": "Я уже видел этот фильм.",
      "answer": "Ya he visto esta película",
      "instruction": "Perfecto — ver",
      "explanation": "He visto — видел."
    },
    {
      "type": "translation",
      "question": "Он потерял ключи.",
      "answer": "Ha perdido las llaves",
      "instruction": "Perfecto reciente",
      "explanation": "Ha perdido las llaves."
    },
    {
      "type": "translation",
      "question": "Мы жили здесь пять лет.",
      "answer": "Hemos vivido aquí cinco años",
      "instruction": "Perfecto + duración",
      "explanation": "Hemos vivido aquí cinco años."
    },
    {
      "type": "translation",
      "question": "Она написала три письма.",
      "answer": "Ha escrito tres cartas",
      "instruction": "Perfecto — escribir",
      "explanation": "Ha escrito tres cartas."
    }
  ],
  "chapter-8-pasado-indefinido": [
    {
      "type": "translation",
      "question": "Вчера я ходил в кино.",
      "answer": "Ayer fui al cine",
      "instruction": "Pretérito indefinido",
      "explanation": "Ayer fui al cine. ir → fui."
    },
    {
      "type": "translation",
      "question": "Она купила новое платье.",
      "answer": "Compró un vestido nuevo",
      "instruction": "Indefinido ella",
      "explanation": "Compró — купила (sin ella)."
    },
    {
      "type": "translation",
      "question": "Мы встретились в парке.",
      "answer": "Nos encontramos en el parque",
      "instruction": "Indefinido reflexivo",
      "explanation": "Nos encontramos en el parque."
    },
    {
      "type": "translation",
      "question": "Он не пришёл на встречу.",
      "answer": "No vino a la reunión",
      "instruction": "Indefinido negativo",
      "explanation": "No vino a la reunión. venir → vino."
    },
    {
      "type": "translation",
      "question": "Они вернулись поздно.",
      "answer": "Volvieron tarde",
      "instruction": "Indefinido — volver",
      "explanation": "Volvieron tarde."
    },
    {
      "type": "translation",
      "question": "Я ел паэлью в Валенсии.",
      "answer": "Comí paella en Valencia",
      "instruction": "Indefinido — comer",
      "explanation": "Comí paella en Valencia."
    },
    {
      "type": "translation",
      "question": "Ты видел это?",
      "answer": "¿Viste eso?",
      "instruction": "Indefinido — вопрос",
      "explanation": "¿Viste eso? ver → viste."
    },
    {
      "type": "translation",
      "question": "Мы провели отличные каникулы.",
      "answer": "Pasamos unas vacaciones estupendas",
      "instruction": "Indefinido — pasar",
      "explanation": "Pasamos unas vacaciones estupendas."
    },
    {
      "type": "translation",
      "question": "Она родилась в 1990 году.",
      "answer": "Nació en 1990",
      "instruction": "Indefinido — nacer",
      "explanation": "Nació en 1990."
    },
    {
      "type": "error_correction",
      "question": "Ayer yo fue al mercado.",
      "answer": "Ayer yo fui al mercado.",
      "instruction": "Спряжение ir",
      "explanation": "Yo → fui (no fue)."
    },
    {
      "type": "error_correction",
      "question": "Ella compró un vestido nuevo ayer mañana.",
      "answer": "Ella compró un vestido nuevo ayer.",
      "instruction": "Redundancia temporal",
      "explanation": "ayer mañana — лишнее."
    },
    {
      "type": "error_correction",
      "question": "Nosotros nos encontramos en el parque ayer y fuimos felices.",
      "answer": "Nos encontramos en el parque ayer.",
      "instruction": "Лишние слова",
      "explanation": "Уберите «nosotros» и лишнее."
    },
    {
      "type": "error_correction",
      "question": "Él no vino a la reunión porque no vino.",
      "answer": "Él no vino a la reunión.",
      "instruction": "Дублирование",
      "explanation": "Повтор «no vino» лишний."
    },
    {
      "type": "error_correction",
      "question": "Volvieron tarde anoche ayer.",
      "answer": "Volvieron tarde anoche.",
      "instruction": "Дублирование времени",
      "explanation": "anoche = вчера вечером."
    },
    {
      "type": "error_correction",
      "question": "Yo comí paella en Valencia el año pasado el mes pasado.",
      "answer": "Comí paella en Valencia el año pasado.",
      "instruction": "Лишний маркер",
      "explanation": "El mes pasado — лишнее."
    },
    {
      "type": "error_correction",
      "question": "¿Viste eso tu ayer?",
      "answer": "¿Viste eso ayer?",
      "instruction": "Лишнее tu",
      "explanation": "¿Viste eso ayer?"
    },
    {
      "type": "error_correction",
      "question": "Pasamos unas vacaciones estupendas muy buenas.",
      "answer": "Pasamos unas vacaciones estupendas.",
      "instruction": "Плеоназм",
      "explanation": "estupendas = muy buenas."
    },
    {
      "type": "sentence_building",
      "question": "Ayer / fui / al / cine / con / amigos",
      "options": [
        "Ayer",
        "fui",
        "al",
        "cine",
        "con",
        "amigos"
      ],
      "answer": "Ayer fui al cine con amigos",
      "instruction": "Соберите indefinido",
      "explanation": "Ayer fui al cine."
    },
    {
      "type": "sentence_building",
      "question": "Compró / un / vestido / nuevo / ayer",
      "options": [
        "Compró",
        "un",
        "vestido",
        "nuevo",
        "ayer"
      ],
      "answer": "Compró un vestido nuevo ayer",
      "instruction": "Соберите comprar",
      "explanation": "Compró — ella."
    },
    {
      "type": "sentence_building",
      "question": "Nos / encontramos / en / el / parque",
      "options": [
        "Nos",
        "encontramos",
        "en",
        "el",
        "parque"
      ],
      "answer": "Nos encontramos en el parque",
      "instruction": "Соберите reflexivo",
      "explanation": "Nos encontramos."
    },
    {
      "type": "sentence_building",
      "question": "No / vino / a / la / reunión",
      "options": [
        "No",
        "vino",
        "a",
        "la",
        "reunión"
      ],
      "answer": "No vino a la reunión",
      "instruction": "Соберите negación",
      "explanation": "No vino a la reunión."
    },
    {
      "type": "sentence_building",
      "question": "Volvieron / tarde / anoche",
      "options": [
        "Volvieron",
        "tarde",
        "anoche"
      ],
      "answer": "Volvieron tarde anoche",
      "instruction": "Соберите volver",
      "explanation": "Volvieron tarde."
    },
    {
      "type": "sentence_building",
      "question": "Comí / paella / en / Valencia",
      "options": [
        "Comí",
        "paella",
        "en",
        "Valencia"
      ],
      "answer": "Comí paella en Valencia",
      "instruction": "Соберите comer",
      "explanation": "Comí paella…"
    },
    {
      "type": "sentence_building",
      "question": "¿Viste / esa / película?",
      "options": [
        "¿Viste",
        "esa",
        "película?"
      ],
      "answer": "¿Viste esa película?",
      "instruction": "Соберите вопрос",
      "explanation": "¿Viste esa película?"
    },
    {
      "type": "sentence_building",
      "question": "Pasamos / unas / vacaciones / estupendas",
      "options": [
        "Pasamos",
        "unas",
        "vacaciones",
        "estupendas"
      ],
      "answer": "Pasamos unas vacaciones estupendas",
      "instruction": "Соберите vacaciones",
      "explanation": "Pasamos unas vacaciones."
    },
    {
      "type": "sentence_building",
      "question": "Nació / en / mil / novecientos / noventa",
      "options": [
        "Nació",
        "en",
        "mil",
        "novecientos",
        "noventa"
      ],
      "answer": "Nació en mil novecientos noventa",
      "instruction": "Соберите nacer",
      "explanation": "Nació en…"
    },
    {
      "type": "translation",
      "question": "Она написала письмо.",
      "answer": "Ella escribió una carta",
      "instruction": "Pretérito",
      "explanation": "escribió — pretérito"
    }
  ],
  "chapter-9-imperfecto": [
    {
      "type": "translation",
      "question": "Когда я был ребёнком, играл в футбол.",
      "answer": "Cuando era niño jugaba al fútbol",
      "instruction": "Imperfecto — привычка",
      "explanation": "Cuando era niño jugaba al fútbol."
    },
    {
      "type": "translation",
      "question": "Было холодно и шёл дождь.",
      "answer": "Hacía frío y llovía",
      "instruction": "Imperfecto — погода",
      "explanation": "Hacía frío y llovía."
    },
    {
      "type": "translation",
      "question": "Она всегда читала перед сном.",
      "answer": "Siempre leía antes de dormir",
      "instruction": "Imperfecto — siempre",
      "explanation": "Siempre leía antes de dormir."
    },
    {
      "type": "translation",
      "question": "Мы жили в маленьком городе.",
      "answer": "Vivíamos en un pueblo pequeño",
      "instruction": "Imperfecto — описание",
      "explanation": "Vivíamos en un pueblo pequeño."
    },
    {
      "type": "translation",
      "question": "Он часто ходил в библиотеку.",
      "answer": "Iba a menudo a la biblioteca",
      "instruction": "Imperfecto — ir",
      "explanation": "Iba a menudo a la biblioteca."
    },
    {
      "type": "translation",
      "question": "Было три часа, когда я позвонил.",
      "answer": "Eran las tres cuando llamé",
      "instruction": "Imperfecto + indefinido",
      "explanation": "Eran las tres cuando llamé."
    },
    {
      "type": "translation",
      "question": "Они были счастливы в те годы.",
      "answer": "Eran felices en aquellos años",
      "instruction": "Imperfecto ser",
      "explanation": "Eran felices en aquellos años."
    },
    {
      "type": "translation",
      "question": "Я думал, что ты дома.",
      "answer": "Pensaba que estabas en casa",
      "instruction": "Imperfecto — мысль",
      "explanation": "Pensaba que estabas en casa."
    },
    {
      "type": "translation",
      "question": "Каждое лето мы ездили на море.",
      "answer": "Cada verano íbamos al mar",
      "instruction": "Imperfecto — привычка",
      "explanation": "Cada verano íbamos al mar."
    },
    {
      "type": "translation",
      "question": "Мы часто ходили в парк.",
      "answer": "Íbamos a menudo al parque",
      "instruction": "Imperfecto hábito",
      "explanation": "Íbamos al parque — привычка"
    }
  ],
  "chapter-10-por-para": [
    {
      "type": "translation",
      "question": "Я учу испанский для работы.",
      "answer": "Estudio español para trabajar",
      "instruction": "Para + infinitivo",
      "explanation": "Para trabajar = для работы."
    },
    {
      "type": "translation",
      "question": "Мы гуляли по парку.",
      "answer": "Paseamos por el parque",
      "instruction": "Por — место",
      "explanation": "Por el parque = по парку."
    },
    {
      "type": "translation",
      "question": "Это подарок для тебя.",
      "answer": "Es un regalo para ti",
      "instruction": "Para — получатель",
      "explanation": "Para ti = для тебя."
    },
    {
      "type": "translation",
      "question": "Он благодарен за помощь.",
      "answer": "Está agradecido por la ayuda",
      "instruction": "Por — причина",
      "explanation": "Por la ayuda = за помощь."
    },
    {
      "type": "translation",
      "question": "Книга написана для детей.",
      "answer": "El libro está escrito para niños",
      "instruction": "Para — аудитория",
      "explanation": "Para niños = для детей."
    },
    {
      "type": "translation",
      "question": "Мы говорили об этом два часа.",
      "answer": "Hablamos de eso por dos horas",
      "instruction": "Por — длительность",
      "explanation": "Por dos horas = в течение двух часов."
    },
    {
      "type": "translation",
      "question": "Я еду в Мадрид для учёбы.",
      "answer": "Voy a Madrid para estudiar",
      "instruction": "Para — цель",
      "explanation": "Para estudiar = для учёбы."
    },
    {
      "type": "translation",
      "question": "Спасибо за всё.",
      "answer": "Gracias por todo",
      "instruction": "Por — благодарность",
      "explanation": "Gracias por todo."
    },
    {
      "type": "translation",
      "question": "Она работает для международной компании.",
      "answer": "Trabaja para una empresa internacional",
      "instruction": "Para — работодатель",
      "explanation": "Para una empresa = для компании."
    },
    {
      "type": "sentence_building",
      "question": "Estudio / español / para / trabajar",
      "options": [
        "Estudio",
        "español",
        "para",
        "trabajar"
      ],
      "answer": "Estudio español para trabajar",
      "instruction": "Соберите para + inf",
      "explanation": "Para trabajar."
    },
    {
      "type": "sentence_building",
      "question": "Paseamos / por / el / parque / cada / tarde",
      "options": [
        "Paseamos",
        "por",
        "el",
        "parque",
        "cada",
        "tarde"
      ],
      "answer": "Paseamos por el parque cada tarde",
      "instruction": "Соберите por — место",
      "explanation": "Por el parque."
    },
    {
      "type": "sentence_building",
      "question": "Es / un / regalo / para / ti",
      "options": [
        "Es",
        "un",
        "regalo",
        "para",
        "ti"
      ],
      "answer": "Es un regalo para ti",
      "instruction": "Соберите para ti",
      "explanation": "Para ti = для тебя."
    },
    {
      "type": "sentence_building",
      "question": "Estoy / agradecido / por / la / ayuda",
      "options": [
        "Estoy",
        "agradecido",
        "por",
        "la",
        "ayuda"
      ],
      "answer": "Estoy agradecido por la ayuda",
      "instruction": "Соберите por — причина",
      "explanation": "Por la ayuda."
    },
    {
      "type": "sentence_building",
      "question": "El / libro / está / escrito / para / niños",
      "options": [
        "El",
        "libro",
        "está",
        "escrito",
        "para",
        "niños"
      ],
      "answer": "El libro está escrito para niños",
      "instruction": "Соберите para niños",
      "explanation": "Para niños."
    },
    {
      "type": "sentence_building",
      "question": "Hablamos / de / eso / por / dos / horas",
      "options": [
        "Hablamos",
        "de",
        "eso",
        "por",
        "dos",
        "horas"
      ],
      "answer": "Hablamos de eso por dos horas",
      "instruction": "Соберите por — duración",
      "explanation": "Por dos horas."
    },
    {
      "type": "sentence_building",
      "question": "Voy / a / Madrid / para / estudiar",
      "options": [
        "Voy",
        "a",
        "Madrid",
        "para",
        "estudiar"
      ],
      "answer": "Voy a Madrid para estudiar",
      "instruction": "Соберите para estudiar",
      "explanation": "Para estudiar."
    },
    {
      "type": "sentence_building",
      "question": "Gracias / por / todo",
      "options": [
        "Gracias",
        "por",
        "todo"
      ],
      "answer": "Gracias por todo",
      "instruction": "Соберите gracias por",
      "explanation": "Gracias por todo."
    },
    {
      "type": "sentence_building",
      "question": "Trabaja / para / una / empresa / internacional",
      "options": [
        "Trabaja",
        "para",
        "una",
        "empresa",
        "internacional"
      ],
      "answer": "Trabaja para una empresa internacional",
      "instruction": "Соберите para — empresa",
      "explanation": "Para una empresa."
    },
    {
      "type": "sentence_building",
      "question": "Lo / hice / por / amor / a / mi / familia",
      "options": [
        "Lo",
        "hice",
        "por",
        "amor",
        "a",
        "mi",
        "familia"
      ],
      "answer": "Lo hice por amor a mi familia",
      "instruction": "Соберите por — motivo",
      "explanation": "Por amor a…"
    }
  ],
  "chapter-11-subjuntivo": [
    {
      "type": "translation",
      "question": "Я хочу, чтобы ты пришёл.",
      "answer": "Quiero que vengas",
      "instruction": "Subjuntivo — deseo",
      "explanation": "Quiero que vengas. venir → vengas."
    },
    {
      "type": "translation",
      "question": "Надеюсь, что она будет счастлива.",
      "answer": "Espero que sea feliz",
      "instruction": "Subjuntivo — esperar",
      "explanation": "Espero que sea feliz."
    },
    {
      "type": "translation",
      "question": "Важно, чтобы вы пришли вовремя.",
      "answer": "Es importante que lleguen a tiempo",
      "instruction": "Subjuntivo — impersonal",
      "explanation": "Es importante que lleguen."
    },
    {
      "type": "translation",
      "question": "Она просит, чтобы мы молчали.",
      "answer": "Pide que callemos",
      "instruction": "Subjuntivo — pedir",
      "explanation": "Pide que callemos."
    },
    {
      "type": "translation",
      "question": "Сомневаюсь, что он прав.",
      "answer": "Dudo que tenga razón",
      "instruction": "Subjuntivo — dudar",
      "explanation": "Dudo que tenga razón."
    },
    {
      "type": "translation",
      "question": "Пока он не придёт, мы подождём.",
      "answer": "Esperaremos hasta que venga",
      "instruction": "Subjuntivo — hasta que",
      "explanation": "Hasta que venga."
    },
    {
      "type": "translation",
      "question": "Мне жаль, что ты уезжаешь.",
      "answer": "Siento que te vayas",
      "instruction": "Subjuntivo — sentir",
      "explanation": "Siento que te vayas."
    },
    {
      "type": "translation",
      "question": "Боюсь, что опоздаю.",
      "answer": "Temo llegar tarde",
      "instruction": "Subjuntivo / infinitivo",
      "explanation": "Temo llegar tarde (o: Temo que llegue tarde).",
      "acceptableAnswers": [
        "Temo que llegue tarde"
      ]
    },
    {
      "type": "translation",
      "question": "Нужно, чтобы ты это сделал.",
      "answer": "Es necesario que lo hagas",
      "instruction": "Subjuntivo — necesario",
      "explanation": "Es necesario que lo hagas."
    }
  ],
  "chapter-12-imperativo": [
    {
      "type": "error_correction",
      "question": "¡Come la fruta tu!",
      "answer": "¡Come la fruta!",
      "instruction": "Imperativo tú — лишнее",
      "explanation": "Уберите «tu» после imperativo."
    },
    {
      "type": "error_correction",
      "question": "No hables tan alto tú.",
      "answer": "¡No hables tan alto!",
      "instruction": "Imperativo negativo",
      "explanation": "Imperativo negativo: No hables…"
    },
    {
      "type": "error_correction",
      "question": "¡Vamos al cine ahora mismo vamos!",
      "answer": "¡Vamos al cine ahora mismo!",
      "instruction": "Redundancia",
      "explanation": "Повтор «vamos» лишний."
    },
    {
      "type": "error_correction",
      "question": "Hable usted más despacio por favor usted.",
      "answer": "Hable usted más despacio, por favor.",
      "instruction": "Imperativo usted",
      "explanation": "Уберите второе «usted»."
    },
    {
      "type": "error_correction",
      "question": "¡Bebe agua tu antes de salir!",
      "answer": "¡Bebe agua antes de salir!",
      "instruction": "Imperativo tú",
      "explanation": "Bebe agua — sin «tu»."
    },
    {
      "type": "error_correction",
      "question": "No corras en el pasillo por favor no corras.",
      "answer": "¡No corras en el pasillo, por favor!",
      "instruction": "Imperativo negativo",
      "explanation": "Один imperativo достаточно."
    },
    {
      "type": "error_correction",
      "question": "¡Abre la ventana abrir!",
      "answer": "¡Abre la ventana!",
      "instruction": "Infinitivo вместо imperativo",
      "explanation": "Abre, не abrir."
    },
    {
      "type": "error_correction",
      "question": "Cierra la puerta tu por favor cierra.",
      "answer": "¡Cierra la puerta, por favor!",
      "instruction": "Imperativo",
      "explanation": "Cierra la puerta."
    },
    {
      "type": "error_correction",
      "question": "¡Escucha atentamente escuchar!",
      "answer": "¡Escucha atentamente!",
      "instruction": "Forma incorrecta",
      "explanation": "Escucha — imperativo."
    },
    {
      "type": "error_correction",
      "question": "No fume usted aquí por favor no fume usted.",
      "answer": "No fume usted aquí, por favor.",
      "instruction": "Imperativo usted negativo",
      "explanation": "No fume usted aquí."
    }
  ],
  "chapter-13-condicional": [
    {
      "type": "translation",
      "question": "Я бы поехал в Испанию.",
      "answer": "Viajaría a España",
      "instruction": "Condicional — deseo",
      "explanation": "Viajaría a España."
    },
    {
      "type": "translation",
      "question": "Что бы ты сделал на моём месте?",
      "answer": "¿Qué harías en mi lugar?",
      "instruction": "Condicional — pregunta",
      "explanation": "¿Qué harías en mi lugar?"
    },
    {
      "type": "translation",
      "question": "Она хотела бы жить у моря.",
      "answer": "Le gustaría vivir junto al mar",
      "instruction": "Condicional — gustaría",
      "explanation": "Le gustaría vivir junto al mar."
    },
    {
      "type": "translation",
      "question": "Мы могли бы встретиться завтра.",
      "answer": "Podríamos vernos mañana",
      "instruction": "Condicional — podría",
      "explanation": "Podríamos vernos mañana."
    },
    {
      "type": "translation",
      "question": "Это было бы здорово.",
      "answer": "Sería genial",
      "instruction": "Condicional ser",
      "explanation": "Sería genial."
    },
    {
      "type": "translation",
      "question": "Я бы купил дом, если бы у меня были деньги.",
      "answer": "Compraría una casa si tuviera dinero",
      "instruction": "Condicional + imperfecto subj",
      "explanation": "Compraría… si tuviera…"
    },
    {
      "type": "translation",
      "question": "Он сказал бы правду.",
      "answer": "Diría la verdad",
      "instruction": "Condicional decir",
      "explanation": "Diría la verdad."
    },
    {
      "type": "translation",
      "question": "Ты должен был позвонить.",
      "answer": "Deberías haber llamado",
      "instruction": "Debería + perfecto",
      "explanation": "Deberías haber llamado.",
      "acceptableAnswers": [
        "Deberías haber llamado"
      ]
    },
    {
      "type": "translation",
      "question": "Было бы лучше остаться дома.",
      "answer": "Sería mejor quedarse en casa",
      "instruction": "Condicional — consejo",
      "explanation": "Sería mejor quedarse en casa."
    },
    {
      "type": "translation",
      "question": "Я бы купил дом.",
      "answer": "Compraría una casa",
      "instruction": "Condicional",
      "explanation": "Compraría — condicional"
    }
  ],
  "chapter-14-estilo-indirecto": [
    {
      "type": "error_correction",
      "question": "María dijo: \"Voy mañana al médico.\"",
      "answer": "María dijo que iba al médico al día siguiente.",
      "instruction": "Estilo indirecto",
      "explanation": "Presente → imperfecto; mañana → al día siguiente."
    },
    {
      "type": "error_correction",
      "question": "Juan afirmó: \"Estoy cansado.\"",
      "answer": "Juan afirmó que estaba cansado.",
      "instruction": "Estilo indirecto — estar",
      "explanation": "Estoy → estaba."
    },
    {
      "type": "error_correction",
      "question": "Ella preguntó: \"¿Dónde está el baño?\"",
      "answer": "Ella preguntó dónde estaba el baño.",
      "instruction": "Pregunta indirecta",
      "explanation": "¿Dónde está? → dónde estaba."
    },
    {
      "type": "error_correction",
      "question": "Pedro explicó: \"Llegaré tarde.\"",
      "answer": "Pedro explicó que llegaría tarde.",
      "instruction": "Futuro → condicional",
      "explanation": "Llegaré → llegaría."
    },
    {
      "type": "error_correction",
      "question": "Ana dijo: \"He terminado el trabajo.\"",
      "answer": "Ana dijo que había terminado el trabajo.",
      "instruction": "Perfecto → pluscuamperfecto",
      "explanation": "He terminado → había terminado."
    },
    {
      "type": "error_correction",
      "question": "Carlos contó: \"Vine ayer.\"",
      "answer": "Carlos contó que había venido el día anterior.",
      "instruction": "Indefinido → pluscuamperfecto",
      "explanation": "Vine → había venido; ayer → el día anterior."
    },
    {
      "type": "error_correction",
      "question": "Laura prometió: \"Te llamaré.\"",
      "answer": "Laura prometió que me llamaría.",
      "instruction": "Promesa indirecta",
      "explanation": "Te llamaré → me llamaría."
    },
    {
      "type": "error_correction",
      "question": "Miguel respondió: \"No puedo ir.\"",
      "answer": "Miguel respondió que no podía ir.",
      "instruction": "Modal → imperfecto",
      "explanation": "No puedo → no podía."
    },
    {
      "type": "error_correction",
      "question": "Sofía dijo: \"Estudio en Madrid.\"",
      "answer": "Sofía dijo que estudiaba en Madrid.",
      "instruction": "Presente → imperfecto",
      "explanation": "Estudio → estudiaba."
    },
    {
      "type": "error_correction",
      "question": "Roberto afirmó: \"Mañana es mi cumpleaños.\"",
      "answer": "Roberto afirmó que al día siguiente era su cumpleaños.",
      "instruction": "Cambio temporal",
      "explanation": "Mañana → al día siguiente; es → era."
    }
  ],
  "chapter-15-voz-pasiva": [
    {
      "type": "translation",
      "question": "Книга написана Габrielем Гарсиа Маркесом.",
      "answer": "El libro fue escrito por Gabriel García Márquez",
      "instruction": "Pasiva — ser + participio",
      "explanation": "Fue escrito por…"
    },
    {
      "type": "translation",
      "question": "Дом построен в 1920 году.",
      "answer": "La casa fue construida en 1920",
      "instruction": "Pasiva — construir",
      "explanation": "Fue construida en 1920."
    },
    {
      "type": "translation",
      "question": "Письмо отправлено вчера.",
      "answer": "La carta fue enviada ayer",
      "instruction": "Pasiva — enviar",
      "explanation": "Fue enviada ayer."
    },
    {
      "type": "translation",
      "question": "Решение принято правительством.",
      "answer": "La decisión fue tomada por el gobierno",
      "instruction": "Pasiva — tomar",
      "explanation": "Fue tomada por el gobierno."
    },
    {
      "type": "translation",
      "question": "Язык говорят в двадцати странах.",
      "answer": "El idioma es hablado en veinte países",
      "instruction": "Pasiva — presente",
      "explanation": "Es hablado en veinte países."
    },
    {
      "type": "translation",
      "question": "Окна открыты.",
      "answer": "Las ventanas están abiertas",
      "instruction": "Pasiva de estado",
      "explanation": "Están abiertas — состояние."
    },
    {
      "type": "translation",
      "question": "Еда приготовлена мамой.",
      "answer": "La comida fue preparada por mi madre",
      "instruction": "Pasiva — preparar",
      "explanation": "Fue preparada por mi madre."
    },
    {
      "type": "translation",
      "question": "Проблема решена.",
      "answer": "El problema ha sido resuelto",
      "instruction": "Pasiva — perfecto",
      "explanation": "Ha sido resuelto."
    },
    {
      "type": "translation",
      "question": "Закон принят в прошлом году.",
      "answer": "La ley fue aprobada el año pasado",
      "instruction": "Pasiva — aprobar",
      "explanation": "Fue aprobada el año pasado."
    }
  ],
  "chapter-18-genero-numero": [
    {
      "type": "translation",
      "question": "Мальчик играет.",
      "answer": "El niño juega",
      "instruction": "Género masculino",
      "explanation": "El niño — masculino."
    },
    {
      "type": "translation",
      "question": "Девочка читает.",
      "answer": "La niña lee",
      "instruction": "Género femenino",
      "explanation": "La niña — femenino."
    },
    {
      "type": "translation",
      "question": "Красные яблоки вкусные.",
      "answer": "Las manzanas rojas están ricas",
      "instruction": "Plural femenino",
      "explanation": "Las manzanas rojas."
    },
    {
      "type": "translation",
      "question": "Чёрные кошки спят.",
      "answer": "Los gatos negros duermen",
      "instruction": "Plural masculino",
      "explanation": "Los gatos negros."
    },
    {
      "type": "translation",
      "question": "Это большая проблема.",
      "answer": "Es un problema grande",
      "instruction": "Problema — masculino",
      "explanation": "Un problema grande (problema = m.)."
    },
    {
      "type": "translation",
      "question": "У меня болит рука.",
      "answer": "Me duele la mano",
      "instruction": "Partes del cuerpo",
      "explanation": "La mano — femenino."
    },
    {
      "type": "translation",
      "question": "Новые студенты пришли.",
      "answer": "Los estudiantes nuevos llegaron",
      "instruction": "Plural + adj",
      "explanation": "Los estudiantes nuevos."
    },
    {
      "type": "translation",
      "question": "Старые фотографии красивые.",
      "answer": "Las fotos antiguas son bonitas",
      "instruction": "Fotos — femenino",
      "explanation": "Las fotos antiguas."
    },
    {
      "type": "translation",
      "question": "Зелёные листья падают.",
      "answer": "Las hojas verdes caen",
      "instruction": "Hojas — femenino",
      "explanation": "Las hojas verdes."
    },
    {
      "type": "error_correction",
      "question": "La niño juega en el parque.",
      "answer": "El niño juega en el parque.",
      "instruction": "Género niño",
      "explanation": "Niño = masculino → el niño."
    },
    {
      "type": "error_correction",
      "question": "Los manzana roja está rica.",
      "answer": "Las manzanas rojas están ricas.",
      "instruction": "Plural + género",
      "explanation": "Manzanas → las; plural → rojas, están."
    },
    {
      "type": "error_correction",
      "question": "El problema grande es difícil la.",
      "answer": "El problema grande es difícil.",
      "instruction": "Artículo incorrecto",
      "explanation": "Problema = masculino."
    },
    {
      "type": "error_correction",
      "question": "Me duele el mano.",
      "answer": "Me duele la mano.",
      "instruction": "Parte del cuerpo",
      "explanation": "La mano — femenino."
    },
    {
      "type": "error_correction",
      "question": "Los estudiante nuevo llegaron.",
      "answer": "Los estudiantes nuevos llegaron.",
      "instruction": "Plural sustantivo",
      "explanation": "Estudiantes + nuevos."
    },
    {
      "type": "error_correction",
      "question": "Las foto antigua son bonita.",
      "answer": "Las fotos antiguas son bonitas.",
      "instruction": "Plural fotos",
      "explanation": "Fotos → plural en todo."
    },
    {
      "type": "error_correction",
      "question": "El hoja verde cae.",
      "answer": "La hoja verde cae.",
      "instruction": "Hoja — femenino",
      "explanation": "La hoja verde."
    },
    {
      "type": "error_correction",
      "question": "Un agua fría por favor.",
      "answer": "Agua fría, por favor.",
      "instruction": "Agua — excepción",
      "explanation": "Agua fría sin «un»."
    },
    {
      "type": "error_correction",
      "question": "Los problema son difícil.",
      "answer": "Los problemas son difíciles.",
      "instruction": "Plural problemas",
      "explanation": "Problemas → dificiles."
    },
    {
      "type": "sentence_building",
      "question": "El / niño / juega / en / el / parque",
      "options": [
        "El",
        "niño",
        "juega",
        "en",
        "el",
        "parque"
      ],
      "answer": "El niño juega en el parque",
      "instruction": "Соберите el + sustantivo",
      "explanation": "El niño — masculino."
    },
    {
      "type": "sentence_building",
      "question": "La / niña / lee / un / libro",
      "options": [
        "La",
        "niña",
        "lee",
        "un",
        "libro"
      ],
      "answer": "La niña lee un libro",
      "instruction": "Соберите la + sustantivo",
      "explanation": "La niña — femenino."
    },
    {
      "type": "sentence_building",
      "question": "Las / manzanas / rojas / están / ricas",
      "options": [
        "Las",
        "manzanas",
        "rojas",
        "están",
        "ricas"
      ],
      "answer": "Las manzanas rojas están ricas",
      "instruction": "Соберите plural fem",
      "explanation": "Las manzanas rojas."
    },
    {
      "type": "sentence_building",
      "question": "Los / gatos / negros / duermen / mucho",
      "options": [
        "Los",
        "gatos",
        "negros",
        "duermen",
        "mucho"
      ],
      "answer": "Los gatos negros duermen mucho",
      "instruction": "Соберите plural masc",
      "explanation": "Los gatos negros."
    },
    {
      "type": "sentence_building",
      "question": "Es / un / problema / grande",
      "options": [
        "Es",
        "un",
        "problema",
        "grande"
      ],
      "answer": "Es un problema grande",
      "instruction": "Соберите problema",
      "explanation": "Un problema — m."
    },
    {
      "type": "sentence_building",
      "question": "Me / duele / la / mano / derecha",
      "options": [
        "Me",
        "duele",
        "la",
        "mano",
        "derecha"
      ],
      "answer": "Me duele la mano derecha",
      "instruction": "Соберите la mano",
      "explanation": "La mano — femenino."
    },
    {
      "type": "sentence_building",
      "question": "Los / estudiantes / nuevos / llegaron / hoy",
      "options": [
        "Los",
        "estudiantes",
        "nuevos",
        "llegaron",
        "hoy"
      ],
      "answer": "Los estudiantes nuevos llegaron hoy",
      "instruction": "Соберите plural",
      "explanation": "Los estudiantes nuevos."
    },
    {
      "type": "sentence_building",
      "question": "Las / fotos / antiguas / son / bonitas",
      "options": [
        "Las",
        "fotos",
        "antiguas",
        "son",
        "bonitas"
      ],
      "answer": "Las fotos antiguas son bonitas",
      "instruction": "Соберите fotos",
      "explanation": "Las fotos antiguas."
    },
    {
      "type": "sentence_building",
      "question": "Las / hojas / verdes / caen / en / otoño",
      "options": [
        "Las",
        "hojas",
        "verdes",
        "caen",
        "en",
        "otoño"
      ],
      "answer": "Las hojas verdes caen en otoño",
      "instruction": "Соберите hojas",
      "explanation": "Las hojas verdes."
    }
  ],
  "chapter-19-preposiciones": [
    {
      "type": "translation",
      "question": "Книга на столе.",
      "answer": "El libro está en la mesa",
      "instruction": "En — поверхность",
      "explanation": "En la mesa = на столе."
    },
    {
      "type": "translation",
      "question": "Кошка под кроватью.",
      "answer": "El gato está debajo de la cama",
      "instruction": "Debajo de",
      "explanation": "Debajo de la cama."
    },
    {
      "type": "translation",
      "question": "Магазин рядом с банком.",
      "answer": "La tienda está al lado del banco",
      "instruction": "Al lado de",
      "explanation": "Al lado del banco."
    },
    {
      "type": "translation",
      "question": "Я живу между двумя парками.",
      "answer": "Vivo entre dos parques",
      "instruction": "Entre",
      "explanation": "Entre dos parques."
    },
    {
      "type": "translation",
      "question": "Он стоит перед зеркалом.",
      "answer": "Está delante del espejo",
      "instruction": "Delante de",
      "explanation": "Delante del espejo."
    },
    {
      "type": "translation",
      "question": "Машина за домом.",
      "answer": "El coche está detrás de la casa",
      "instruction": "Detrás de",
      "explanation": "Detrás de la casa."
    },
    {
      "type": "translation",
      "question": "Мы идём к реке.",
      "answer": "Vamos hacia el río",
      "instruction": "Hacia",
      "explanation": "Hacia el río = к реке."
    },
    {
      "type": "translation",
      "question": "Картина висит на стене.",
      "answer": "El cuadro cuelga de la pared",
      "instruction": "De — откуда",
      "explanation": "Cuelga de la pared."
    },
    {
      "type": "translation",
      "question": "Они идут по улице.",
      "answer": "Caminan por la calle",
      "instruction": "Por — вдоль",
      "explanation": "Por la calle = по улице."
    },
    {
      "type": "sentence_building",
      "question": "El / libro / está / en / la / mesa",
      "options": [
        "El",
        "libro",
        "está",
        "en",
        "la",
        "mesa"
      ],
      "answer": "El libro está en la mesa",
      "instruction": "Соберите en",
      "explanation": "En la mesa."
    },
    {
      "type": "sentence_building",
      "question": "El / gato / está / debajo / de / la / cama",
      "options": [
        "El",
        "gato",
        "está",
        "debajo",
        "de",
        "la",
        "cama"
      ],
      "answer": "El gato está debajo de la cama",
      "instruction": "Соберите debajo de",
      "explanation": "Debajo de la cama."
    },
    {
      "type": "sentence_building",
      "question": "La / tienda / está / al / lado / del / banco",
      "options": [
        "La",
        "tienda",
        "está",
        "al",
        "lado",
        "del",
        "banco"
      ],
      "answer": "La tienda está al lado del banco",
      "instruction": "Соберите al lado de",
      "explanation": "Al lado del banco."
    },
    {
      "type": "sentence_building",
      "question": "Vivo / entre / dos / parques",
      "options": [
        "Vivo",
        "entre",
        "dos",
        "parques"
      ],
      "answer": "Vivo entre dos parques",
      "instruction": "Соберите entre",
      "explanation": "Entre dos parques."
    },
    {
      "type": "sentence_building",
      "question": "Está / delante / del / espejo",
      "options": [
        "Está",
        "delante",
        "del",
        "espejo"
      ],
      "answer": "Está delante del espejo",
      "instruction": "Соберите delante de",
      "explanation": "Delante del espejo."
    },
    {
      "type": "sentence_building",
      "question": "El / coche / está / detrás / de / la / casa",
      "options": [
        "El",
        "coche",
        "está",
        "detrás",
        "de",
        "la",
        "casa"
      ],
      "answer": "El coche está detrás de la casa",
      "instruction": "Соберите detrás de",
      "explanation": "Detrás de la casa."
    },
    {
      "type": "sentence_building",
      "question": "Vamos / hacia / el / río",
      "options": [
        "Vamos",
        "hacia",
        "el",
        "río"
      ],
      "answer": "Vamos hacia el río",
      "instruction": "Соберите hacia",
      "explanation": "Hacia el río."
    },
    {
      "type": "sentence_building",
      "question": "El / cuadro / cuelga / de / la / pared",
      "options": [
        "El",
        "cuadro",
        "cuelga",
        "de",
        "la",
        "pared"
      ],
      "answer": "El cuadro cuelga de la pared",
      "instruction": "Соберите de",
      "explanation": "Cuelga de la pared."
    },
    {
      "type": "sentence_building",
      "question": "Caminan / por / la / calle / principal",
      "options": [
        "Caminan",
        "por",
        "la",
        "calle",
        "principal"
      ],
      "answer": "Caminan por la calle principal",
      "instruction": "Соберите por",
      "explanation": "Por la calle."
    },
    {
      "type": "sentence_building",
      "question": "Hay / un / café / en / la / esquina",
      "options": [
        "Hay",
        "un",
        "café",
        "en",
        "la",
        "esquina"
      ],
      "answer": "Hay un café en la esquina",
      "instruction": "Соберите en la esquina",
      "explanation": "En la esquina = на углу."
    },
    {
      "type": "translation",
      "question": "Книга на столе.",
      "answer": "El libro está en la mesa",
      "instruction": "Preposición en",
      "explanation": "en la mesa — на столе"
    }
  ],
  "chapter-20-preguntas": [
    {
      "type": "translation",
      "question": "Как тебя зовут?",
      "answer": "¿Cómo te llamas?",
      "instruction": "Pregunta — nombre",
      "explanation": "¿Cómo te llamas?"
    },
    {
      "type": "translation",
      "question": "Сколько тебе лет?",
      "answer": "¿Cuántos años tienes?",
      "instruction": "Pregunta — edad",
      "explanation": "¿Cuántos años tienes?"
    },
    {
      "type": "translation",
      "question": "Откуда ты?",
      "answer": "¿De dónde eres?",
      "instruction": "Pregunta — origen",
      "explanation": "¿De dónde eres?"
    },
    {
      "type": "translation",
      "question": "Что ты делаешь?",
      "answer": "¿Qué haces?",
      "instruction": "Pregunta — actividad",
      "explanation": "¿Qué haces?"
    },
    {
      "type": "translation",
      "question": "Почему ты опоздал?",
      "answer": "¿Por qué llegaste tarde?",
      "instruction": "Pregunta — razón",
      "explanation": "¿Por qué llegaste tarde?"
    },
    {
      "type": "translation",
      "question": "Когда начинается фильм?",
      "answer": "¿Cuándo empieza la película?",
      "instruction": "Pregunta — tiempo",
      "explanation": "¿Cuándo empieza la película?"
    },
    {
      "type": "translation",
      "question": "С кем ты идёшь?",
      "answer": "¿Con quién vas?",
      "instruction": "Pregunta — compañía",
      "explanation": "¿Con quién vas?"
    },
    {
      "type": "translation",
      "question": "Какой это цвет?",
      "answer": "¿De qué color es?",
      "instruction": "Pregunta — color",
      "explanation": "¿De qué color es?"
    },
    {
      "type": "translation",
      "question": "Сколько это стоит?",
      "answer": "¿Cuánto cuesta?",
      "instruction": "Pregunta — precio",
      "explanation": "¿Cuánto cuesta?"
    },
    {
      "type": "sentence_building",
      "question": "¿Cómo / te / llamas?",
      "options": [
        "¿Cómo",
        "te",
        "llamas?"
      ],
      "answer": "¿Cómo te llamas?",
      "instruction": "Соберите вопрос",
      "explanation": "¿Cómo te llamas?"
    },
    {
      "type": "sentence_building",
      "question": "¿Cuántos / años / tienes?",
      "options": [
        "¿Cuántos",
        "años",
        "tienes?"
      ],
      "answer": "¿Cuántos años tienes?",
      "instruction": "Соберите edad",
      "explanation": "¿Cuántos años tienes?"
    },
    {
      "type": "sentence_building",
      "question": "¿De / dónde / eres?",
      "options": [
        "¿De",
        "dónde",
        "eres?"
      ],
      "answer": "¿De dónde eres?",
      "instruction": "Соберите origen",
      "explanation": "¿De dónde eres?"
    },
    {
      "type": "sentence_building",
      "question": "¿Qué / haces / este / fin / de / semana?",
      "options": [
        "¿Qué",
        "haces",
        "este",
        "fin",
        "de",
        "semana?"
      ],
      "answer": "¿Qué haces este fin de semana?",
      "instruction": "Соберите actividad",
      "explanation": "¿Qué haces…?"
    },
    {
      "type": "sentence_building",
      "question": "¿Por / qué / llegaste / tarde?",
      "options": [
        "¿Por",
        "qué",
        "llegaste",
        "tarde?"
      ],
      "answer": "¿Por qué llegaste tarde?",
      "instruction": "Соберите por qué",
      "explanation": "¿Por qué…?"
    },
    {
      "type": "sentence_building",
      "question": "¿Cuándo / empieza / la / película?",
      "options": [
        "¿Cuándo",
        "empieza",
        "la",
        "película?"
      ],
      "answer": "¿Cuándo empieza la película?",
      "instruction": "Соберите cuándo",
      "explanation": "¿Cuándo empieza…?"
    },
    {
      "type": "sentence_building",
      "question": "¿Con / quién / vas / al / cine?",
      "options": [
        "¿Con",
        "quién",
        "vas",
        "al",
        "cine?"
      ],
      "answer": "¿Con quién vas al cine?",
      "instruction": "Соберите con quién",
      "explanation": "¿Con quién vas…?"
    },
    {
      "type": "sentence_building",
      "question": "¿Cuánto / cuesta / este / bolso?",
      "options": [
        "¿Cuánto",
        "cuesta",
        "este",
        "bolso?"
      ],
      "answer": "¿Cuánto cuesta este bolso?",
      "instruction": "Соберите precio",
      "explanation": "¿Cuánto cuesta?"
    },
    {
      "type": "translation",
      "question": "Сколько это стоит?",
      "answer": "¿Cuánto cuesta?",
      "instruction": "Pregunta con cuánto",
      "explanation": "¿Cuánto cuesta?"
    },
    {
      "type": "translation",
      "question": "Зачем ты здесь?",
      "answer": "¿Para qué estás aquí?",
      "instruction": "Para qué",
      "explanation": "¿Para qué estás aquí?"
    }
  ],
  "chapter-21-comparativos": [
    {
      "type": "translation",
      "question": "Мадрид больше, чем Толедо.",
      "answer": "Madrid es más grande que Toledo",
      "instruction": "Comparativo",
      "explanation": "Más grande que Toledo."
    },
    {
      "type": "translation",
      "question": "Она такая же высокая, как её мать.",
      "answer": "Es tan alta como su madre",
      "instruction": "Tan… como",
      "explanation": "Tan alta como su madre."
    },
    {
      "type": "translation",
      "question": "Это самый красивый город.",
      "answer": "Es la ciudad más bonita",
      "instruction": "Superlativo",
      "explanation": "La ciudad más bonita."
    },
    {
      "type": "translation",
      "question": "Испанский проще, чем я думал.",
      "answer": "El español es más fácil de lo que pensaba",
      "instruction": "Comparativo — pensar",
      "explanation": "Más fácil de lo que pensaba."
    },
    {
      "type": "translation",
      "question": "Он бегает быстрее меня.",
      "answer": "Corre más rápido que yo",
      "instruction": "Comparativo — adverbio",
      "explanation": "Más rápido que yo."
    },
    {
      "type": "translation",
      "question": "Сегодня холоднее, чем вчера.",
      "answer": "Hoy hace más frío que ayer",
      "instruction": "Comparativo — clima",
      "explanation": "Más frío que ayer."
    },
    {
      "type": "translation",
      "question": "У неё меньше проблем, чем у меня.",
      "answer": "Tiene menos problemas que yo",
      "instruction": "Menos… que",
      "explanation": "Menos problemas que yo."
    },
    {
      "type": "translation",
      "question": "Это лучший ресторан в городе.",
      "answer": "Es el mejor restaurante de la ciudad",
      "instruction": "Superlativo irregular",
      "explanation": "El mejor restaurante."
    },
    {
      "type": "translation",
      "question": "Она самая умная в классе.",
      "answer": "Es la más inteligente de la clase",
      "instruction": "Superlativo relativo",
      "explanation": "La más inteligente de la clase."
    },
    {
      "type": "translation",
      "question": "Этот фильм интереснее.",
      "answer": "Esta película es más interesante",
      "instruction": "Comparativo",
      "explanation": "más interesante"
    }
  ],
  "chapter-22-futuro": [
    {
      "type": "translation",
      "question": "Завтра я позвоню тебе.",
      "answer": "Mañana te llamaré",
      "instruction": "Futuro simple",
      "explanation": "Te llamaré — позвоню."
    },
    {
      "type": "translation",
      "question": "Она приедет в пятницу.",
      "answer": "Llegará el viernes",
      "instruction": "Futuro — llegar",
      "explanation": "Llegará el viernes."
    },
    {
      "type": "translation",
      "question": "Мы будем жить в Барcelona.",
      "answer": "Viviremos en Barcelona",
      "instruction": "Futuro — vivir",
      "explanation": "Viviremos en Barcelona."
    },
    {
      "type": "translation",
      "question": "Это будет сложно.",
      "answer": "Será difícil",
      "instruction": "Futuro ser",
      "explanation": "Será difícil."
    },
    {
      "type": "translation",
      "question": "Они не придут.",
      "answer": "No vendrán",
      "instruction": "Futuro negativo",
      "explanation": "No vendrán. venir → vendrán."
    },
    {
      "type": "translation",
      "question": "Ты успеешь?",
      "answer": "¿Llegarás a tiempo?",
      "instruction": "Futuro — pregunta",
      "explanation": "¿Llegarás a tiempo?"
    },
    {
      "type": "translation",
      "question": "Я думаю, что будет дождь.",
      "answer": "Creo que lloverá",
      "instruction": "Futuro — llover",
      "explanation": "Lloverá — будет дождь."
    },
    {
      "type": "translation",
      "question": "Он сделает домашнее задание.",
      "answer": "Hará los deberes",
      "instruction": "Futuro — hacer",
      "explanation": "Hará los deberes. hacer → hará."
    },
    {
      "type": "translation",
      "question": "Через год я буду говорить по-испански.",
      "answer": "Dentro de un año hablaré español",
      "instruction": "Futuro — hablar",
      "explanation": "Hablaré español."
    },
    {
      "type": "translation",
      "question": "Наверное, сейчас десять часов.",
      "answer": "Serán las diez ahora",
      "instruction": "Futuro de probabilidad",
      "explanation": "Serán las diez = наверное, десять."
    }
  ],
  "chapter-31-verbos-frecuentes": [
    {
      "type": "sentence_building",
      "question": "No / puedo / ir / hoy / pero / quiero / ir / mañana",
      "options": [
        "No",
        "puedo",
        "ir",
        "hoy",
        "pero",
        "quiero",
        "ir",
        "mañana"
      ],
      "answer": "No puedo ir hoy pero quiero ir mañana",
      "instruction": "Соберите poder / querer",
      "explanation": "No puedo… pero quiero…"
    },
    {
      "type": "sentence_building",
      "question": "Voy / al / supermercado / ahora / mismo",
      "options": [
        "Voy",
        "al",
        "supermercado",
        "ahora",
        "mismo"
      ],
      "answer": "Voy al supermercado ahora mismo",
      "instruction": "Соберите ir",
      "explanation": "Voy al supermercado."
    }
  ]
} as const;
