import type { Chapter } from "@/types";

// =====================================================================
// English Course — Chapters (~22, aligned with Spanish journey length)
// Story: journey through the English-speaking world
// Existing slugs stay stable for progress; new chapters insert in order.
// =====================================================================

export const ENGLISH_CHAPTERS: Chapter[] = [
  {
    slug: "eng-ch1-first-steps",
    number: 1,
    title: "First Steps",
    titleEs: "Los Primeros Pasos",
    level: "A1",
    location: "London",
    icon: "🇬🇧",
    summary: "be (am/is/are), greetings, personal information.",
    grammarTopic: "eng-a1-be",
    vocabTopic: "eng-a1-personal-info",
    exerciseTypes: ["multiple_choice", "fill_blank"],
    estimatedMinutes: 8,
  },
  {
    slug: "eng-ch2-routines",
    number: 2,
    title: "Daily Routines",
    titleEs: "La Rutina Diaria",
    level: "A1",
    location: "Oxford",
    icon: "📚",
    summary: "Present simple, adverbs of frequency, everyday activities.",
    grammarTopic: "eng-a1-present-simple",
    vocabTopic: "eng-a1-everyday-objects",
    exerciseTypes: ["multiple_choice", "fill_blank", "translation"],
    prereqChapter: "eng-ch1-first-steps",
    estimatedMinutes: 10,
  },
  {
    slug: "eng-ch17-questions",
    number: 3,
    title: "Ask the Guide",
    titleEs: "Pregunta al Guía",
    level: "A1",
    location: "Bath",
    icon: "❓",
    summary: "Wh- questions: what, who, where, when, why, how.",
    grammarTopic: "eng-a1-questions",
    vocabTopic: "eng-a1-personal-info",
    exerciseTypes: ["multiple_choice", "fill_blank", "translation"],
    prereqChapter: "eng-ch2-routines",
    estimatedMinutes: 9,
  },
  {
    slug: "eng-ch3-around-town",
    number: 4,
    title: "Around Town",
    titleEs: "Por la Ciudad",
    level: "A1",
    location: "Cambridge",
    icon: "🏘️",
    summary: "there is / there are, some/any with places in town.",
    grammarTopic: "eng-a1-there-is-are",
    vocabTopic: "eng-a1-places-town",
    exerciseTypes: ["multiple_choice", "fill_blank"],
    prereqChapter: "eng-ch17-questions",
    estimatedMinutes: 9,
  },
  {
    slug: "eng-ch18-can",
    number: 5,
    title: "I Can Do It",
    titleEs: "Puedo Hacerlo",
    level: "A1",
    location: "Brighton",
    icon: "🏄",
    summary: "can / can't — ability, permission, and requests.",
    grammarTopic: "eng-a1-can",
    vocabTopic: "eng-a1-everyday-objects",
    exerciseTypes: ["multiple_choice", "fill_blank", "translation"],
    prereqChapter: "eng-ch3-around-town",
    estimatedMinutes: 9,
  },
  {
    slug: "eng-ch19-prepositions",
    number: 6,
    title: "Find Your Way",
    titleEs: "Encuentra el Camino",
    level: "A1",
    location: "Bristol",
    icon: "🗺️",
    summary: "Prepositions of place: in, on, at, under, between, next to.",
    grammarTopic: "eng-a1-prepositions",
    vocabTopic: "eng-a1-places-town",
    exerciseTypes: ["multiple_choice", "fill_blank", "sentence_building"],
    prereqChapter: "eng-ch18-can",
    estimatedMinutes: 9,
  },
  {
    slug: "eng-ch4-past-stories",
    number: 7,
    title: "Past Stories",
    titleEs: "Historias del Pasado",
    level: "A2",
    location: "York",
    icon: "⚔️",
    summary: "Past simple (regular & irregular), questions, travel verbs.",
    grammarTopic: "eng-a2-past-simple",
    vocabTopic: "eng-a2-travel",
    exerciseTypes: ["multiple_choice", "fill_blank", "translation"],
    prereqChapter: "eng-ch19-prepositions",
    estimatedMinutes: 10,
  },
  {
    slug: "eng-ch5-choices",
    number: 8,
    title: "The Right Choice",
    titleEs: "La Elección Correcta",
    level: "A2",
    location: "Edinburgh",
    icon: "⚖️",
    summary: "Comparatives and superlatives.",
    grammarTopic: "eng-a2-comparatives",
    vocabTopic: "eng-a2-shopping",
    exerciseTypes: ["multiple_choice", "fill_blank", "sentence_building"],
    prereqChapter: "eng-ch4-past-stories",
    estimatedMinutes: 10,
  },
  {
    slug: "eng-ch20-going-to",
    number: 9,
    title: "Plans Ahead",
    titleEs: "Planes por Delante",
    level: "A2",
    location: "Glasgow",
    icon: "🧳",
    summary: "be going to — intentions and near-future plans.",
    grammarTopic: "eng-a2-going-to",
    vocabTopic: "eng-a2-travel",
    exerciseTypes: ["multiple_choice", "fill_blank", "translation"],
    prereqChapter: "eng-ch5-choices",
    estimatedMinutes: 9,
  },
  {
    slug: "eng-ch6-experiences",
    number: 10,
    title: "Global Experiences",
    titleEs: "Experiencias Globales",
    level: "A2",
    location: "Manchester",
    icon: "🌍",
    summary: "Present perfect, ever/never, life experiences.",
    grammarTopic: "eng-a2-present-perfect",
    vocabTopic: "eng-a2-technology",
    exerciseTypes: ["multiple_choice", "fill_blank", "translation"],
    prereqChapter: "eng-ch20-going-to",
    estimatedMinutes: 10,
  },
  {
    slug: "eng-ch21-quantifiers",
    number: 11,
    title: "How Much?",
    titleEs: "¿Cuánto?",
    level: "A2",
    location: "Leeds",
    icon: "🛒",
    summary: "some, any, much, many, a lot of — countable and uncountable.",
    grammarTopic: "eng-a2-quantifiers",
    vocabTopic: "eng-a2-shopping",
    exerciseTypes: ["multiple_choice", "fill_blank", "error_correction"],
    prereqChapter: "eng-ch6-experiences",
    estimatedMinutes: 9,
  },
  {
    slug: "eng-ch7-future-plans",
    number: 12,
    title: "Making Plans",
    titleEs: "Haciendo Planes",
    level: "B1",
    location: "Dublin",
    icon: "🍀",
    summary: "will / won't and the first conditional.",
    grammarTopic: "eng-b1-future-conditional",
    vocabTopic: "eng-b1-personality",
    exerciseTypes: ["multiple_choice", "fill_blank", "translation"],
    prereqChapter: "eng-ch21-quantifiers",
    estimatedMinutes: 12,
  },
  {
    slug: "eng-ch22-modals",
    number: 13,
    title: "Rules of the Road",
    titleEs: "Las Reglas del Camino",
    level: "B1",
    location: "Belfast",
    icon: "🚦",
    summary: "should, must, have to — advice and obligation.",
    grammarTopic: "eng-b1-modals",
    vocabTopic: "eng-b1-health-body",
    exerciseTypes: ["multiple_choice", "fill_blank", "translation"],
    prereqChapter: "eng-ch7-future-plans",
    estimatedMinutes: 10,
  },
  {
    slug: "eng-ch8-storytelling",
    number: 14,
    title: "Tell Me a Story",
    titleEs: "Cuéntame una Historia",
    level: "B1",
    location: "Cardiff",
    icon: "📖",
    summary: "Past continuous, used to, past perfect, narrative tenses.",
    grammarTopic: "eng-b1-narrative",
    vocabTopic: "eng-b1-feelings",
    exerciseTypes: ["multiple_choice", "fill_blank", "error_correction"],
    prereqChapter: "eng-ch22-modals",
    estimatedMinutes: 12,
  },
  {
    slug: "eng-ch9-real-world",
    number: 15,
    title: "The Real World",
    titleEs: "El Mundo Real",
    level: "B1",
    location: "Liverpool",
    icon: "🎵",
    summary: "Present perfect continuous, for/since, life changes.",
    grammarTopic: "eng-b1-perfect-continuous",
    vocabTopic: "eng-b1-health-body",
    exerciseTypes: ["multiple_choice", "fill_blank", "translation"],
    prereqChapter: "eng-ch8-storytelling",
    estimatedMinutes: 10,
  },
  {
    slug: "eng-ch10-what-if",
    number: 16,
    title: "What If?",
    titleEs: "¿Y si...?",
    level: "B2",
    location: "New York",
    icon: "🗽",
    summary: "Second/third conditional, wish/if only, hypotheticals.",
    grammarTopic: "eng-b2-conditionals",
    vocabTopic: "eng-b2-work-jobs",
    exerciseTypes: ["multiple_choice", "fill_blank", "error_correction"],
    prereqChapter: "eng-ch9-real-world",
    estimatedMinutes: 12,
  },
  {
    slug: "eng-ch11-passive",
    number: 17,
    title: "The Passive Voice",
    titleEs: "La Voz Pasiva",
    level: "B2",
    location: "Boston",
    icon: "🏛️",
    summary: "Passive (all tenses), have something done, processes.",
    grammarTopic: "eng-b2-passive",
    vocabTopic: "eng-b2-education",
    exerciseTypes: ["multiple_choice", "fill_blank", "translation"],
    prereqChapter: "eng-ch10-what-if",
    estimatedMinutes: 12,
  },
  {
    slug: "eng-ch12-beyond-borders",
    number: 18,
    title: "Beyond Borders",
    titleEs: "Más Allá de las Fronteras",
    level: "B2",
    location: "San Francisco",
    icon: "🌉",
    summary: "Reported speech, relative clauses, quantifiers.",
    grammarTopic: "eng-b2-reported-clauses",
    vocabTopic: "eng-b2-environment",
    exerciseTypes: ["multiple_choice", "fill_blank", "error_correction"],
    prereqChapter: "eng-ch11-passive",
    estimatedMinutes: 12,
  },
  {
    slug: "eng-ch13-advanced-structures",
    number: 19,
    title: "Advanced Structures",
    titleEs: "Estructuras Avanzadas",
    level: "C1",
    location: "Chicago",
    icon: "🏙️",
    summary: "Inversion, emphatic structures, cleft sentences.",
    grammarTopic: "eng-c1-inversion",
    vocabTopic: "eng-c1-idioms",
    exerciseTypes: ["multiple_choice", "fill_blank", "error_correction"],
    prereqChapter: "eng-ch12-beyond-borders",
    estimatedMinutes: 15,
  },
  {
    slug: "eng-ch14-art-language",
    number: 20,
    title: "The Art of Language",
    titleEs: "El Arte del Idioma",
    level: "C1",
    location: "Toronto",
    icon: "🎭",
    summary: "Substitution, ellipsis, fronting, intensifying adverbs.",
    grammarTopic: "eng-c1-discourse",
    vocabTopic: "eng-c1-academic",
    exerciseTypes: ["multiple_choice", "fill_blank", "translation"],
    prereqChapter: "eng-ch13-advanced-structures",
    estimatedMinutes: 15,
  },
  {
    slug: "eng-ch15-mastery",
    number: 21,
    title: "Mastery",
    titleEs: "Maestría",
    level: "C1",
    location: "Sydney",
    icon: "🌊",
    summary: "Mixed conditionals, advanced passives, register, literature.",
    grammarTopic: "eng-c1-mixed-conditionals",
    vocabTopic: "eng-c1-literary",
    exerciseTypes: ["multiple_choice", "fill_blank", "translation", "error_correction"],
    prereqChapter: "eng-ch14-art-language",
    estimatedMinutes: 15,
  },
  {
    slug: "eng-ch16-ielts",
    number: 22,
    title: "The Final Challenge",
    titleEs: "El Desafío Final",
    level: "C1",
    location: "IELTS Castle",
    icon: "🏰",
    summary: "Comprehensive review + IELTS exam preparation.",
    grammarTopic: "eng-c1-review",
    vocabTopic: "eng-c1-exam",
    exerciseTypes: ["multiple_choice", "fill_blank", "translation", "error_correction", "sentence_building"],
    prereqChapter: "eng-ch15-mastery",
    estimatedMinutes: 15,
  },
];

export function getEngChapter(slug: string): Chapter | undefined {
  return ENGLISH_CHAPTERS.find((c) => c.slug === slug);
}
export function getEngNextChapter(slug: string): Chapter | undefined {
  const idx = ENGLISH_CHAPTERS.findIndex((c) => c.slug === slug);
  if (idx < 0 || idx + 1 >= ENGLISH_CHAPTERS.length) return undefined;
  return ENGLISH_CHAPTERS[idx + 1];
}
