// Auto-generated by scripts/bootstrap-english-curriculum.mjs — do not edit by hand.
import type { StaticExercise } from "@/types";

type ExerciseDraft = Omit<StaticExercise, "id"> & { id?: string };

export const ENGLISH_CURRICULUM_CHAPTER_EXERCISES: Record<string, ExerciseDraft[]> = {
  "eng-ch26-articles": [
    {
      "type": "multiple_choice",
      "question": "I need ___ umbrella.",
      "instruction": "Выберите a или an",
      "options": [
        "a",
        "an",
        "the",
        "—"
      ],
      "answer": "an",
      "explanation": "Umbrella начинается с гласного звука /ʌ/ → an.",
      "grammarTopic": "articles-basics"
    },
    {
      "type": "fill_blank",
      "question": "She is ___ doctor.",
      "instruction": "Профессия без the",
      "answer": "a",
      "acceptableAnswers": [
        "A"
      ],
      "explanation": "Профессия в общем смысле → a doctor.",
      "grammarTopic": "articles-basics"
    },
    {
      "type": "multiple_choice",
      "question": "___ sun rises in the east.",
      "instruction": "Уникальный объект",
      "options": [
        "A",
        "An",
        "The",
        "—"
      ],
      "answer": "The",
      "explanation": "The sun — единственный в мире объект.",
      "grammarTopic": "articles-basics"
    },
    {
      "type": "translation",
      "question": "Мне нравится музыка.",
      "instruction": "Zero article",
      "answer": "I like music",
      "acceptableAnswers": [
        "i like music"
      ],
      "explanation": "Music — неисчисляемое, без артикля.",
      "grammarTopic": "articles-basics"
    },
    {
      "type": "error_correction",
      "question": "I saw a elephant at the zoo.",
      "instruction": "Исправьте артикль",
      "answer": "I saw an elephant at the zoo.",
      "acceptableAnswers": [
        "I saw an elephant at the zoo"
      ],
      "explanation": "Elephant → an (гласный звук).",
      "grammarTopic": "articles-basics"
    },
    {
      "type": "fill_blank",
      "question": "We go to ___ school every day.",
      "instruction": "Zero article (institution)",
      "answer": "",
      "acceptableAnswers": [
        "—"
      ],
      "explanation": "Go to school (учиться) — без артикля.",
      "grammarTopic": "articles-basics"
    }
  ],

  "eng-ch27-possessives": [
    {
      "type": "multiple_choice",
      "question": "This is ___ phone.",
      "instruction": "Притяжательное (she)",
      "options": [
        "her",
        "she",
        "hers",
        "she's"
      ],
      "answer": "her",
      "explanation": "Her + существительное: her phone.",
      "grammarTopic": "possessives"
    },
    {
      "type": "fill_blank",
      "question": "That's ___ (Tom) car.",
      "instruction": "Saxon genitive",
      "answer": "Tom's",
      "acceptableAnswers": [
        "tom's"
      ],
      "explanation": "Tom's car — притяжательный падеж через 's.",
      "grammarTopic": "possessives"
    },
    {
      "type": "multiple_choice",
      "question": "The dog wagged ___ tail.",
      "instruction": "Its vs it's",
      "options": [
        "its",
        "it's",
        "it",
        "it is"
      ],
      "answer": "its",
      "explanation": "Its = его/её (принадлежность); it's = it is.",
      "grammarTopic": "possessives"
    },
    {
      "type": "translation",
      "question": "Это дом моих родителей.",
      "instruction": "Parents' (мн.ч.)",
      "answer": "This is my parents' house",
      "acceptableAnswers": [
        "this is my parents' house",
        "It's my parents' house"
      ],
      "explanation": "Parents → parents' (апостроф после -s).",
      "grammarTopic": "possessives"
    },
    {
      "type": "sentence_building",
      "question": "Is / this / your / bag / ?",
      "options": [
        "Is",
        "this",
        "your",
        "bag",
        "?"
      ],
      "answer": "Is this your bag?",
      "instruction": "Соберите вопрос",
      "explanation": "Is this your bag? — притяжательное + существительное.",
      "grammarTopic": "possessives"
    },
    {
      "type": "fill_blank",
      "question": "A ___ work never finishes on time.",
      "instruction": "Day's / days'",
      "answer": "day's",
      "acceptableAnswers": [
        "Day's"
      ],
      "explanation": "A day's work — притяжательное от единственного числа.",
      "grammarTopic": "possessives"
    }
  ],

  "eng-ch28-countable": [
    {
      "type": "multiple_choice",
      "question": "How ___ apples do you need?",
      "instruction": "Many / much",
      "options": [
        "many",
        "much",
        "a little",
        "few"
      ],
      "answer": "many",
      "explanation": "Apples — countable → many.",
      "grammarTopic": "countable"
    },
    {
      "type": "fill_blank",
      "question": "There isn't ___ milk left.",
      "instruction": "Much / many",
      "answer": "much",
      "acceptableAnswers": [
        "Much"
      ],
      "explanation": "Milk — uncountable → much.",
      "grammarTopic": "countable"
    },
    {
      "type": "multiple_choice",
      "question": "Which is uncountable?",
      "instruction": "Выберите несчётное",
      "options": [
        "advice",
        "apple",
        "book",
        "chair"
      ],
      "answer": "advice",
      "explanation": "Advice — uncountable (no -s).",
      "grammarTopic": "countable"
    },
    {
      "type": "translation",
      "question": "У меня мало времени.",
      "instruction": "A little + uncountable",
      "answer": "I have a little time",
      "acceptableAnswers": [
        "i have a little time",
        "I've got a little time"
      ],
      "explanation": "Time — uncountable → a little.",
      "grammarTopic": "countable"
    },
    {
      "type": "error_correction",
      "question": "I need some informations.",
      "instruction": "Исправьте существительное",
      "answer": "I need some information.",
      "acceptableAnswers": [
        "I need some information"
      ],
      "explanation": "Information — uncountable, без -s.",
      "grammarTopic": "countable"
    },
    {
      "type": "fill_blank",
      "question": "She bought a ___ eggs.",
      "instruction": "Few / little",
      "answer": "few",
      "acceptableAnswers": [
        "Few"
      ],
      "explanation": "Eggs — countable → a few.",
      "grammarTopic": "countable"
    }
  ],

  "eng-ch29-pp-intro": [
    {
      "type": "multiple_choice",
      "question": "I ___ never been to Scotland.",
      "instruction": "Have / has",
      "options": [
        "have",
        "has",
        "had",
        "am"
      ],
      "answer": "have",
      "explanation": "I → have + never + V3.",
      "grammarTopic": "present-perfect-intro"
    },
    {
      "type": "fill_blank",
      "question": "She has ___ finished her homework.",
      "instruction": "Already / yet",
      "answer": "already",
      "acceptableAnswers": [
        "Already"
      ],
      "explanation": "Already — в утверждении (+).",
      "grammarTopic": "present-perfect-intro"
    },
    {
      "type": "multiple_choice",
      "question": "Have you ___ tried haggis?",
      "instruction": "Ever / never",
      "options": [
        "ever",
        "never",
        "yet",
        "just"
      ],
      "answer": "ever",
      "explanation": "Have you ever…? — вопрос об опыте.",
      "grammarTopic": "present-perfect-intro"
    },
    {
      "type": "translation",
      "question": "Он только что ушёл.",
      "instruction": "Just + present perfect",
      "answer": "He has just left",
      "acceptableAnswers": [
        "he has just left",
        "He's just left"
      ],
      "explanation": "Just — «только что», have/has + V3.",
      "grammarTopic": "present-perfect-intro"
    },
    {
      "type": "error_correction",
      "question": "I have seen him yesterday.",
      "instruction": "PP vs Past Simple",
      "answer": "I saw him yesterday.",
      "acceptableAnswers": [
        "I saw him yesterday"
      ],
      "explanation": "Yesterday → Past Simple, не Present Perfect.",
      "grammarTopic": "present-perfect-intro"
    },
    {
      "type": "fill_blank",
      "question": "They haven't arrived ___.",
      "instruction": "Yet в отрицании",
      "answer": "yet",
      "acceptableAnswers": [
        "Yet"
      ],
      "explanation": "Yet — в − и ? (ещё не).",
      "grammarTopic": "present-perfect-intro"
    }
  ],

  "eng-ch30-conditionals-review": [
    {
      "type": "multiple_choice",
      "question": "If you heat water to 100°C, it ___.",
      "instruction": "Zero conditional",
      "options": [
        "boils",
        "will boil",
        "would boil",
        "boiled"
      ],
      "answer": "boils",
      "explanation": "Zero: If + Present, Present (закон природы).",
      "grammarTopic": "conditionals-review"
    },
    {
      "type": "fill_blank",
      "question": "If it rains, I ___ stay home.",
      "instruction": "1st conditional",
      "answer": "will",
      "acceptableAnswers": [
        "Will",
        "'ll"
      ],
      "explanation": "1st: If + Present → will + V.",
      "grammarTopic": "conditionals-review"
    },
    {
      "type": "multiple_choice",
      "question": "If I ___ rich, I would travel.",
      "instruction": "2nd conditional",
      "options": [
        "were",
        "am",
        "will be",
        "had been"
      ],
      "answer": "were",
      "explanation": "2nd: If + Past → would. If I were…",
      "grammarTopic": "conditionals-review"
    },
    {
      "type": "translation",
      "question": "Если ты позвонишь, я приду.",
      "instruction": "1st conditional",
      "answer": "If you call, I will come",
      "acceptableAnswers": [
        "if you call, i will come",
        "If you call, I'll come"
      ],
      "explanation": "If + Present → will.",
      "grammarTopic": "conditionals-review"
    },
    {
      "type": "error_correction",
      "question": "If it will rain, I will stay home.",
      "instruction": "Will в if-клаузе",
      "answer": "If it rains, I will stay home.",
      "acceptableAnswers": [
        "If it rains, I will stay home",
        "If it rains, I'll stay home."
      ],
      "explanation": "Нельзя will после if — только Present.",
      "grammarTopic": "conditionals-review"
    },
    {
      "type": "fill_blank",
      "question": "If I ___ you, I'd accept the offer.",
      "instruction": "If I were you",
      "answer": "were",
      "acceptableAnswers": [
        "Were"
      ],
      "explanation": "If I were you — устойчивая 2nd conditional.",
      "grammarTopic": "conditionals-review"
    }
  ],

  "eng-ch31-reported-speech": [
    {
      "type": "multiple_choice",
      "question": "She said she ___ tired.",
      "instruction": "Tense backshift",
      "options": [
        "was",
        "is",
        "has been",
        "will be"
      ],
      "answer": "was",
      "explanation": "Present → Past: is → was.",
      "grammarTopic": "reported-speech"
    },
    {
      "type": "fill_blank",
      "question": "He told me ___ wait.",
      "instruction": "Tell + to-infinitive",
      "answer": "to",
      "acceptableAnswers": [
        "To"
      ],
      "explanation": "Told me to wait — проська/приказ.",
      "grammarTopic": "reported-speech"
    },
    {
      "type": "multiple_choice",
      "question": "«I'm happy» → She said she ___ happy.",
      "instruction": "Backshift",
      "options": [
        "was",
        "is",
        "had been",
        "would be"
      ],
      "answer": "was",
      "explanation": "I'm → she was (backshift).",
      "grammarTopic": "reported-speech"
    },
    {
      "type": "translation",
      "question": "Она спросила, где я живу.",
      "instruction": "Reported question",
      "answer": "She asked where I lived",
      "acceptableAnswers": [
        "she asked where i lived",
        "She asked where I live"
      ],
      "explanation": "Ask + wh-word + subject + V (past).",
      "grammarTopic": "reported-speech"
    },
    {
      "type": "error_correction",
      "question": "He said me that he was busy.",
      "instruction": "Say vs tell",
      "answer": "He told me that he was busy.",
      "acceptableAnswers": [
        "He told me that he was busy",
        "He told me he was busy."
      ],
      "explanation": "Tell + person; say + that (без me).",
      "grammarTopic": "reported-speech"
    },
    {
      "type": "fill_blank",
      "question": "She said the Earth ___ round.",
      "instruction": "No backshift (fact)",
      "answer": "is",
      "acceptableAnswers": [
        "Is",
        "was"
      ],
      "explanation": "Общий факт — backshift необязателен: is/was.",
      "grammarTopic": "reported-speech"
    }
  ],

  "eng-ch32-relative-clauses": [
    {
      "type": "multiple_choice",
      "question": "The woman ___ helped me is a doctor.",
      "instruction": "Who / which",
      "options": [
        "who",
        "which",
        "whose",
        "where"
      ],
      "answer": "who",
      "explanation": "Woman (person) → who.",
      "grammarTopic": "relative-clauses"
    },
    {
      "type": "fill_blank",
      "question": "The book ___ I read was exciting.",
      "instruction": "That / which (object)",
      "answer": "that",
      "acceptableAnswers": [
        "That",
        "which",
        "Which",
        ""
      ],
      "explanation": "Object relative — that/which или опущено.",
      "grammarTopic": "relative-clauses"
    },
    {
      "type": "multiple_choice",
      "question": "The man ___ car was stolen called the police.",
      "instruction": "Whose",
      "options": [
        "whose",
        "who's",
        "who",
        "which"
      ],
      "answer": "whose",
      "explanation": "Whose = чей (whose car).",
      "grammarTopic": "relative-clauses"
    },
    {
      "type": "translation",
      "question": "Это дом, где я вырос.",
      "instruction": "Where relative",
      "answer": "This is the house where I grew up",
      "acceptableAnswers": [
        "this is the house where i grew up"
      ],
      "explanation": "Where = in which (место).",
      "grammarTopic": "relative-clauses"
    },
    {
      "type": "sentence_building",
      "question": "The / teacher / who / teaches / English / is / kind",
      "options": [
        "The",
        "teacher",
        "who",
        "teaches",
        "English",
        "is",
        "kind"
      ],
      "answer": "The teacher who teaches English is kind",
      "instruction": "Соберите с who",
      "explanation": "Defining clause без запятых.",
      "grammarTopic": "relative-clauses"
    },
    {
      "type": "fill_blank",
      "question": "That's the restaurant ___ we met.",
      "instruction": "Where / which",
      "answer": "where",
      "acceptableAnswers": [
        "Where",
        "that",
        "Which"
      ],
      "explanation": "Place → where (or that/which).",
      "grammarTopic": "relative-clauses"
    }
  ],

  "eng-ch33-passive-advanced": [
    {
      "type": "multiple_choice",
      "question": "The report ___ yesterday.",
      "instruction": "Past passive",
      "options": [
        "was written",
        "wrote",
        "has written",
        "is writing"
      ],
      "answer": "was written",
      "explanation": "Past passive: was/were + V3.",
      "grammarTopic": "passive-advanced"
    },
    {
      "type": "fill_blank",
      "question": "A new bridge ___ (build) at the moment.",
      "instruction": "Present continuous passive",
      "answer": "is being built",
      "acceptableAnswers": [
        "Is being built"
      ],
      "explanation": "Is being + V3 — процесс сейчас.",
      "grammarTopic": "passive-advanced"
    },
    {
      "type": "multiple_choice",
      "question": "I need to ___ my hair cut.",
      "instruction": "Have something done",
      "options": [
        "have",
        "get",
        "make",
        "do"
      ],
      "answer": "have",
      "explanation": "Have/get something done — услуга.",
      "grammarTopic": "passive-advanced"
    },
    {
      "type": "translation",
      "question": "Закон был принят в прошлом году.",
      "instruction": "Past passive",
      "answer": "The law was passed last year",
      "acceptableAnswers": [
        "the law was passed last year"
      ],
      "explanation": "Was passed — Past Simple passive.",
      "grammarTopic": "passive-advanced"
    },
    {
      "type": "error_correction",
      "question": "The letter has been send.",
      "instruction": "Participio",
      "answer": "The letter has been sent.",
      "acceptableAnswers": [
        "The letter has been sent"
      ],
      "explanation": "Send → sent (V3).",
      "grammarTopic": "passive-advanced"
    },
    {
      "type": "fill_blank",
      "question": "He had his wallet ___.",
      "instruction": "Have + object + V3",
      "answer": "stolen",
      "acceptableAnswers": [
        "Stolen"
      ],
      "explanation": "Had his wallet stolen — causative passive.",
      "grammarTopic": "passive-advanced"
    }
  ],

  "eng-ch34-modals-deduction": [
    {
      "type": "multiple_choice",
      "question": "She ___ be at home — her car is in the driveway.",
      "instruction": "Must (deduction)",
      "options": [
        "must",
        "might",
        "can't",
        "should"
      ],
      "answer": "must",
      "explanation": "Must — почти уверенный вывод (+).",
      "grammarTopic": "modals-deduction"
    },
    {
      "type": "fill_blank",
      "question": "He ___ be tired — he just ran a marathon.",
      "instruction": "Must / can't",
      "answer": "must",
      "acceptableAnswers": [
        "Must"
      ],
      "explanation": "Логичный вывод → must.",
      "grammarTopic": "modals-deduction"
    },
    {
      "type": "multiple_choice",
      "question": "She ___ have forgotten — she never misses meetings.",
      "instruction": "Can't have (past)",
      "options": [
        "can't",
        "must",
        "might",
        "should"
      ],
      "answer": "can't",
      "explanation": "Can't have + V3 — почти уверен, что НЕ было.",
      "grammarTopic": "modals-deduction"
    },
    {
      "type": "translation",
      "question": "Он, возможно, опоздал.",
      "instruction": "Might have",
      "answer": "He might have been late",
      "acceptableAnswers": [
        "he might have been late",
        "He may have been late"
      ],
      "explanation": "Might/may have + V3 — возможно в прошлом.",
      "grammarTopic": "modals-deduction"
    },
    {
      "type": "error_correction",
      "question": "She mustn't be at home — I saw her leave.",
      "instruction": "Can't vs mustn't",
      "answer": "She can't be at home — I saw her leave.",
      "acceptableAnswers": [
        "She can't be at home — I saw her leave."
      ],
      "explanation": "Can't = невозможно; mustn't = запрещено.",
      "grammarTopic": "modals-deduction"
    },
    {
      "type": "fill_blank",
      "question": "They ___ have left already — their bags are still here.",
      "instruction": "Can't have",
      "answer": "can't",
      "acceptableAnswers": [
        "Can't"
      ],
      "explanation": "Can't have left — не могли уйти (улики).",
      "grammarTopic": "modals-deduction"
    }
  ],

  "eng-ch35-ielts-informal": [
    {
      "type": "multiple_choice",
      "question": "Best greeting for a friend named Alex:",
      "instruction": "Informal register",
      "options": [
        "Hi Alex,",
        "Dear Sir or Madam,",
        "To whom it may concern,",
        "Yours faithfully,"
      ],
      "answer": "Hi Alex,",
      "explanation": "Informal → Hi / Dear + first name.",
      "grammarTopic": "ielts-letter-informal"
    },
    {
      "type": "fill_blank",
      "question": "Thanks for your email — great to ___ from you!",
      "instruction": "Opening phrase",
      "answer": "hear",
      "acceptableAnswers": [
        "Hear"
      ],
      "explanation": "Great to hear from you — стандартное opening.",
      "grammarTopic": "ielts-letter-informal"
    },
    {
      "type": "error_correction",
      "question": "Dear Sir or Madam, I am writing to inform you about my holiday.",
      "instruction": "Wrong register",
      "answer": "Hi Sam, Thanks for your email — I wanted to tell you about my holiday!",
      "acceptableAnswers": [
        "Hi Sam, Thanks for your email!"
      ],
      "explanation": "Sir/Madam — formal; другу нужен Hi + имя.",
      "grammarTopic": "ielts-letter-informal"
    },
    {
      "type": "multiple_choice",
      "question": "Best closing for a close friend:",
      "instruction": "Sign-off",
      "options": [
        "Love,",
        "Yours faithfully,",
        "Yours sincerely,",
        "Respectfully yours,"
      ],
      "answer": "Love,",
      "explanation": "Love, / Take care, — informal closings.",
      "grammarTopic": "ielts-letter-informal"
    },
    {
      "type": "sentence_building",
      "question": "Why / don't / you / come / and / visit / ?",
      "options": [
        "Why",
        "don't",
        "you",
        "come",
        "and",
        "visit",
        "?"
      ],
      "answer": "Why don't you come and visit?",
      "instruction": "Informal invitation",
      "explanation": "Why don't you…? — дружеское приглашение.",
      "grammarTopic": "ielts-letter-informal"
    },
    {
      "type": "fill_blank",
      "question": "I'm sorry I haven't written for ___.",
      "instruction": "Informal apology",
      "answer": "ages",
      "acceptableAnswers": [
        "Ages",
        "a long time"
      ],
      "explanation": "Haven't written for ages — типичная фраза.",
      "grammarTopic": "ielts-letter-informal"
    }
  ],

  "eng-ch36-ielts-formal": [
    {
      "type": "multiple_choice",
      "question": "Dear Sir or Madam, → sign-off:",
      "instruction": "Formal pairing",
      "options": [
        "Yours faithfully,",
        "Yours sincerely,",
        "Love,",
        "Cheers,"
      ],
      "answer": "Yours faithfully,",
      "explanation": "Unknown name → Yours faithfully.",
      "grammarTopic": "ielts-letter-formal"
    },
    {
      "type": "fill_blank",
      "question": "I am writing to ___ about the service I received.",
      "instruction": "Complaint opening",
      "answer": "complain",
      "acceptableAnswers": [
        "Complain",
        "enquire"
      ],
      "explanation": "I am writing to complain/enquire about…",
      "grammarTopic": "ielts-letter-formal"
    },
    {
      "type": "error_correction",
      "question": "Dear Sir or Madam, I can't accept this. Cheers, Anna",
      "instruction": "Register + sign-off",
      "answer": "Dear Sir or Madam, I cannot accept this. Yours faithfully, Anna Petrova",
      "acceptableAnswers": [
        "Dear Sir or Madam, I cannot accept this. Yours faithfully, Anna Petrova."
      ],
      "explanation": "Formal: cannot, Yours faithfully, full name.",
      "grammarTopic": "ielts-letter-formal"
    },
    {
      "type": "multiple_choice",
      "question": "Dear Ms Patel, → sign-off:",
      "instruction": "Named addressee",
      "options": [
        "Yours sincerely,",
        "Yours faithfully,",
        "Hi,",
        "Take care,"
      ],
      "answer": "Yours sincerely,",
      "explanation": "Named person → Yours sincerely.",
      "grammarTopic": "ielts-letter-formal"
    },
    {
      "type": "translation",
      "question": "Буду благодарен, если вы пришлёте информацию.",
      "instruction": "Formal request",
      "answer": "I would be grateful if you could send the information",
      "acceptableAnswers": [
        "I would be grateful if you could send the information.",
        "I would appreciate it if you could send the information."
      ],
      "explanation": "Would be grateful if you could… — вежливая формула.",
      "grammarTopic": "ielts-letter-formal"
    },
    {
      "type": "fill_blank",
      "question": "I look forward to ___ from you.",
      "instruction": "Closing line",
      "answer": "hearing",
      "acceptableAnswers": [
        "Hearing"
      ],
      "explanation": "Look forward to + -ing.",
      "grammarTopic": "ielts-letter-formal"
    }
  ],

  "eng-ch37-cambridge-letter": [
    {
      "type": "multiple_choice",
      "question": "Cambridge letter to a teacher you've met:",
      "instruction": "Semi-formal",
      "options": [
        "Dear Mr Lee,",
        "Hey Mr Lee!",
        "Dear Sir or Madam,",
        "Hi Lee,"
      ],
      "answer": "Dear Mr Lee,",
      "explanation": "Semi-formal → Dear + title + surname.",
      "grammarTopic": "cambridge-letter-email"
    },
    {
      "type": "fill_blank",
      "question": "I am writing in response to your ___ about the trip.",
      "instruction": "Semi-formal opening",
      "answer": "email",
      "acceptableAnswers": [
        "Email",
        "letter",
        "message"
      ],
      "explanation": "In response to your email/letter…",
      "grammarTopic": "cambridge-letter-email"
    },
    {
      "type": "error_correction",
      "question": "Hey! Wanna join the club? L8r!",
      "instruction": "Too informal",
      "answer": "Dear Mr Lee, I am writing to ask whether you would like to join the club.",
      "acceptableAnswers": [
        "Dear Mr Lee, I am writing to ask if you would like to join the club."
      ],
      "explanation": "Cambridge B2 — semi-formal, полные формы.",
      "grammarTopic": "cambridge-letter-email"
    },
    {
      "type": "multiple_choice",
      "question": "Best phrase to suggest an idea:",
      "instruction": "Semi-formal",
      "options": [
        "How about meeting on Friday?",
        "I was wondering if we could meet on Friday.",
        "Yo let's meet Friday!",
        "Meet me Friday!!!"
      ],
      "answer": "I was wondering if we could meet on Friday.",
      "explanation": "I was wondering if… — вежливое предложение.",
      "grammarTopic": "cambridge-letter-email"
    },
    {
      "type": "sentence_building",
      "question": "Thank / you / for / your / help / with / this",
      "options": [
        "Thank",
        "you",
        "for",
        "your",
        "help",
        "with",
        "this"
      ],
      "answer": "Thank you for your help with this",
      "instruction": "Polite closing phrase",
      "explanation": "Thank you for… — стандарт semi-formal.",
      "grammarTopic": "cambridge-letter-email"
    },
    {
      "type": "fill_blank",
      "question": "Please let me know if you need any further ___.",
      "instruction": "Semi-formal offer",
      "answer": "information",
      "acceptableAnswers": [
        "Information",
        "details",
        "assistance"
      ],
      "explanation": "Any further information/assistance.",
      "grammarTopic": "cambridge-letter-email"
    }
  ],

  "eng-ch38-ielts-task1": [
    {
      "type": "multiple_choice",
      "question": "Best overview sentence:",
      "instruction": "Task 1 overview",
      "options": [
        "Overall, sales increased steadily before falling in 2020.",
        "I think sales were bad.",
        "In my opinion, the chart is interesting.",
        "People should buy more."
      ],
      "answer": "Overall, sales increased steadily before falling in 2020.",
      "explanation": "Overview = общий тренд без мнения.",
      "grammarTopic": "ielts-task1-report"
    },
    {
      "type": "fill_blank",
      "question": "The figure ___ sharply between 2015 and 2018.",
      "instruction": "Trend verb",
      "answer": "rose",
      "acceptableAnswers": [
        "Rose",
        "increased",
        "Increased"
      ],
      "explanation": "Rose/increased sharply — рост.",
      "grammarTopic": "ielts-task1-report"
    },
    {
      "type": "error_correction",
      "question": "The graph shows that I believe pollution is terrible.",
      "instruction": "No opinion in Task 1",
      "answer": "The graph shows that pollution levels rose significantly.",
      "acceptableAnswers": [
        "The graph shows that pollution levels increased significantly."
      ],
      "explanation": "Task 1 — описание, не мнение.",
      "grammarTopic": "ielts-task1-report"
    },
    {
      "type": "multiple_choice",
      "question": "Compare two figures:",
      "instruction": "Comparison language",
      "options": [
        "X was twice as high as Y.",
        "X is better than Y because I prefer it.",
        "Everyone likes X more.",
        "X should be higher."
      ],
      "answer": "X was twice as high as Y.",
      "explanation": "Twice as high as — объективное сравнение.",
      "grammarTopic": "ielts-task1-report"
    },
    {
      "type": "translation",
      "question": "В целом, оба показателя оставались стабильными.",
      "instruction": "Overview",
      "answer": "Overall, both figures remained stable",
      "acceptableAnswers": [
        "overall, both figures remained stable",
        "Overall, both figures remained steady."
      ],
      "explanation": "Overall + remained stable/steady.",
      "grammarTopic": "ielts-task1-report"
    },
    {
      "type": "fill_blank",
      "question": "There was a ___ decline in exports after 2019.",
      "instruction": "Adjective + noun",
      "answer": "gradual",
      "acceptableAnswers": [
        "Gradual",
        "sharp",
        "Sharp",
        "steady"
      ],
      "explanation": "Gradual/sharp decline — описание тренда.",
      "grammarTopic": "ielts-task1-report"
    }
  ],

  "eng-ch39-ielts-essay": [
    {
      "type": "multiple_choice",
      "question": "Best thesis statement:",
      "instruction": "Clear position",
      "options": [
        "This essay will argue that remote work benefits both employees and employers.",
        "Work is a thing people do.",
        "I like working.",
        "Many people work."
      ],
      "answer": "This essay will argue that remote work benefits both employees and employers.",
      "explanation": "Thesis = чёткая позиция + preview.",
      "grammarTopic": "ielts-essay-structure"
    },
    {
      "type": "fill_blank",
      "question": "This essay will ___ that technology improves education.",
      "instruction": "Thesis verb",
      "answer": "argue",
      "acceptableAnswers": [
        "Argue",
        "discuss",
        "Discuss",
        "examine"
      ],
      "explanation": "This essay will argue/discuss that…",
      "grammarTopic": "ielts-essay-structure"
    },
    {
      "type": "sentence_building",
      "question": "In / conclusion / , / the / benefits / outweigh / the / drawbacks",
      "options": [
        "In",
        "conclusion",
        ",",
        "the",
        "benefits",
        "outweigh",
        "the",
        "drawbacks"
      ],
      "answer": "In conclusion, the benefits outweigh the drawbacks",
      "instruction": "Conclusion opener",
      "explanation": "In conclusion, + итоговая позиция.",
      "grammarTopic": "ielts-essay-structure"
    },
    {
      "type": "error_correction",
      "question": "Introduction: In this essay I will write about things.",
      "instruction": "Weak intro",
      "answer": "Introduction: This essay will examine whether online learning is as effective as classroom teaching.",
      "acceptableAnswers": [
        "This essay will examine whether online learning is effective."
      ],
      "explanation": "Конкретная тема + позиция, не «about things».",
      "grammarTopic": "ielts-essay-structure"
    },
    {
      "type": "multiple_choice",
      "question": "Each body paragraph should start with:",
      "instruction": "Topic sentence",
      "options": [
        "A clear topic sentence",
        "A random fact",
        "In my room",
        "Hello reader"
      ],
      "answer": "A clear topic sentence",
      "explanation": "Topic sentence → support → example.",
      "grammarTopic": "ielts-essay-structure"
    },
    {
      "type": "fill_blank",
      "question": "The main drawback is ___ lack of face-to-face interaction.",
      "instruction": "Article",
      "answer": "the",
      "acceptableAnswers": [
        "The"
      ],
      "explanation": "The lack of… — конкретный недостаток.",
      "grammarTopic": "ielts-essay-structure"
    }
  ],

  "eng-ch40-ielts-cohesion": [
    {
      "type": "multiple_choice",
      "question": "Contrast between two ideas:",
      "instruction": "Linker",
      "options": [
        "However,",
        "Furthermore,",
        "Therefore,",
        "Firstly,"
      ],
      "answer": "However,",
      "explanation": "However — контраст.",
      "grammarTopic": "ielts-essay-cohesion"
    },
    {
      "type": "fill_blank",
      "question": "___, the cost of living has risen significantly.",
      "instruction": "Adding information",
      "answer": "Furthermore",
      "acceptableAnswers": [
        "Furthermore",
        "Moreover",
        "In addition"
      ],
      "explanation": "Furthermore/Moreover — добавление.",
      "grammarTopic": "ielts-essay-cohesion"
    },
    {
      "type": "sentence_building",
      "question": "On / the / other / hand / , / urban / life / offers / more / opportunities",
      "options": [
        "On",
        "the",
        "other",
        "hand",
        ",",
        "urban",
        "life",
        "offers",
        "more",
        "opportunities"
      ],
      "answer": "On the other hand, urban life offers more opportunities",
      "instruction": "Contrast linker",
      "explanation": "On the other hand — другая сторона.",
      "grammarTopic": "ielts-essay-cohesion"
    },
    {
      "type": "error_correction",
      "question": "However moreover the plan failed.",
      "instruction": "Conflicting linkers",
      "answer": "However, the plan failed.",
      "acceptableAnswers": [
        "Moreover, the plan failed."
      ],
      "explanation": "Один linker на переход, не два сразу.",
      "grammarTopic": "ielts-essay-cohesion"
    },
    {
      "type": "multiple_choice",
      "question": "Refer back to «this policy»:",
      "instruction": "Reference",
      "options": [
        "This approach has failed.",
        "A policy has failed.",
        "They failed.",
        "It failed them."
      ],
      "answer": "This approach has failed.",
      "explanation": "This approach — ссылка на policy.",
      "grammarTopic": "ielts-essay-cohesion"
    },
    {
      "type": "fill_blank",
      "question": "___ a result, unemployment fell.",
      "instruction": "Cause → effect",
      "answer": "As",
      "acceptableAnswers": [
        "As"
      ],
      "explanation": "As a result — следствие.",
      "grammarTopic": "ielts-essay-cohesion"
    }
  ],

  "eng-ch41-cambridge-essay": [
    {
      "type": "multiple_choice",
      "question": "Cambridge article for a school magazine needs:",
      "instruction": "Article format",
      "options": [
        "An engaging title and direct address to readers",
        "Only bullet points",
        "No introduction",
        "Dear Sir or Madam"
      ],
      "answer": "An engaging title and direct address to readers",
      "explanation": "Article → заголовок + обращение к читателю.",
      "grammarTopic": "cambridge-essay-article"
    },
    {
      "type": "fill_blank",
      "question": "Have you ever wondered why ___ travel is so popular?",
      "instruction": "Article hook",
      "answer": "solo",
      "acceptableAnswers": [
        "Solo",
        "budget",
        "Budget"
      ],
      "explanation": "Have you ever wondered… — engaging hook.",
      "grammarTopic": "cambridge-essay-article"
    },
    {
      "type": "error_correction",
      "question": "Essay title: Hey guys!!! Stuff about phones lol",
      "instruction": "Wrong register for essay",
      "answer": "Essay title: The Impact of Smartphones on Teenage Communication",
      "acceptableAnswers": [
        "The Impact of Smartphones on Teenage Communication"
      ],
      "explanation": "Essay — нейтральный академический заголовок.",
      "grammarTopic": "cambridge-essay-article"
    },
    {
      "type": "multiple_choice",
      "question": "Article closing for young readers:",
      "instruction": "Audience-aware",
      "options": [
        "So why not give it a try this weekend?",
        "In conclusion, the aforementioned points demonstrate…",
        "Yours faithfully,",
        "The data suggests a correlation."
      ],
      "answer": "So why not give it a try this weekend?",
      "explanation": "Article → прямой призыв к читателю.",
      "grammarTopic": "cambridge-essay-article"
    },
    {
      "type": "translation",
      "question": "В заключение, оба подхода имеют свои достоинства.",
      "instruction": "Essay conclusion",
      "answer": "In conclusion, both approaches have their merits",
      "acceptableAnswers": [
        "in conclusion, both approaches have their merits"
      ],
      "explanation": "In conclusion — essay closing.",
      "grammarTopic": "cambridge-essay-article"
    },
    {
      "type": "fill_blank",
      "question": "An article often uses ___ person to involve the reader.",
      "instruction": "You / we",
      "answer": "second",
      "acceptableAnswers": [
        "Second",
        "you"
      ],
      "explanation": "Articles often use you/we for engagement.",
      "grammarTopic": "cambridge-essay-article"
    }
  ],

  "eng-ch42-ielts-opinion": [
    {
      "type": "multiple_choice",
      "question": "Strong but academic opinion:",
      "instruction": "Opinion phrase",
      "options": [
        "I would argue that education should be free.",
        "I think maybe education is ok.",
        "Education is stuff.",
        "Everyone knows education."
      ],
      "answer": "I would argue that education should be free.",
      "explanation": "I would argue that… — академичное мнение.",
      "grammarTopic": "ielts-opinion-language"
    },
    {
      "type": "fill_blank",
      "question": "It ___ to me that the policy is unfair.",
      "instruction": "Soft opinion",
      "answer": "seems",
      "acceptableAnswers": [
        "Seems",
        "appears"
      ],
      "explanation": "It seems/appears that… — мягкая позиция.",
      "grammarTopic": "ielts-opinion-language"
    },
    {
      "type": "translation",
      "question": "В определённой степени я согласен с этим.",
      "instruction": "To some extent",
      "answer": "To some extent, I agree with this",
      "acceptableAnswers": [
        "to some extent, i agree with this",
        "To a certain extent, I agree with this."
      ],
      "explanation": "To some/a certain extent — частичное согласие.",
      "grammarTopic": "ielts-opinion-language"
    },
    {
      "type": "error_correction",
      "question": "I think I think I think phones are bad.",
      "instruction": "Repetition",
      "answer": "I believe that excessive phone use can harm concentration.",
      "acceptableAnswers": [
        "I would argue that excessive phone use harms concentration."
      ],
      "explanation": "Разнообразие opinion phrases, не I think ×3.",
      "grammarTopic": "ielts-opinion-language"
    },
    {
      "type": "multiple_choice",
      "question": "To what extent do you agree?",
      "instruction": "Partial agreement",
      "options": [
        "While I accept some benefits, I largely disagree.",
        "Yes.",
        "No.",
        "Maybe sometimes."
      ],
      "answer": "While I accept some benefits, I largely disagree.",
      "explanation": "While… — частичное согласие + позиция.",
      "grammarTopic": "ielts-opinion-language"
    },
    {
      "type": "fill_blank",
      "question": "___, this trend is unlikely to reverse.",
      "instruction": "Hedged assertion",
      "answer": "Arguably",
      "acceptableAnswers": [
        "arguably",
        "Clearly",
        "clearly"
      ],
      "explanation": "Arguably/Clearly — оценочная связка.",
      "grammarTopic": "ielts-opinion-language"
    }
  ],

  "eng-ch43-register-shift": [
    {
      "type": "multiple_choice",
      "question": "Formal rewrite of «Can you send it ASAP?»:",
      "instruction": "Register shift",
      "options": [
        "I would be grateful if you could send it at your earliest convenience.",
        "Send it ASAP pls!!!",
        "Gimme the file.",
        "Yo send it quick."
      ],
      "answer": "I would be grateful if you could send it at your earliest convenience.",
      "explanation": "ASAP → at your earliest convenience.",
      "grammarTopic": "register-shift"
    },
    {
      "type": "fill_blank",
      "question": "Informal: «___ a lot!» → Formal: «Thank you very much for your assistance.»",
      "instruction": "Thanks shift",
      "answer": "Thanks",
      "acceptableAnswers": [
        "Thanks",
        "Cheers"
      ],
      "explanation": "Thanks → Thank you very much.",
      "grammarTopic": "register-shift"
    },
    {
      "type": "error_correction",
      "question": "Dear Sir or Madam, I can't wait to hear from u. Cheers!",
      "instruction": "Mixed register",
      "answer": "Dear Sir or Madam, I look forward to hearing from you. Yours faithfully, [Name]",
      "acceptableAnswers": [
        "Dear Sir or Madam, I look forward to hearing from you. Yours faithfully,"
      ],
      "explanation": "Formal salutation + formal body + formal close.",
      "grammarTopic": "register-shift"
    },
    {
      "type": "multiple_choice",
      "question": "Informal equivalent of «I am writing to enquire»:",
      "instruction": "Downshift",
      "options": [
        "Just wanted to ask…",
        "I hereby request information regarding…",
        "Pursuant to your advertisement…",
        "I am writing to inform you that…"
      ],
      "answer": "Just wanted to ask…",
      "explanation": "Just wanted to ask — informal enquiry.",
      "grammarTopic": "register-shift"
    },
    {
      "type": "translation",
      "question": "Не могли бы вы перезвонить? (formal)",
      "instruction": "Upshift",
      "answer": "Would you be able to call me back?",
      "acceptableAnswers": [
        "Would you be able to call me back?",
        "Could you please return my call?",
        "I would appreciate it if you could call me back."
      ],
      "explanation": "Would you be able to… / Could you please…",
      "grammarTopic": "register-shift"
    },
    {
      "type": "fill_blank",
      "question": "Consistent tone means: don't mix «Hi» with «___.»",
      "instruction": "Formal sign-off",
      "answer": "Yours faithfully",
      "acceptableAnswers": [
        "Yours faithfully",
        "Yours sincerely"
      ],
      "explanation": "Hi + Yours faithfully — register clash.",
      "grammarTopic": "register-shift"
    }
  ],
};
