import type { Chapter } from "@/types";

// =====================================================================
// English Course — Chapters (43, aligned with Spanish journey length)
// Story: journey through the English-speaking world
// Existing slugs stay stable for progress; new chapters insert in order.
// =====================================================================

export const ENGLISH_CHAPTERS: Chapter[] = [
  {
    slug: "eng-ch1-first-steps",
    number: 1,
    title: "First Steps",
    titleEs: "First Steps",
    level: "A1",
    location: "London",
    icon: "🇬🇧",
    summary: "be (am/is/are), greetings, personal information.",
    grammarTopic: "eng-a1-be",
    vocabTopic: "eng-a1-personal-info",
    exerciseTypes: ["multiple_choice", "fill_blank", "translation", "error_correction", "sentence_building"],
    estimatedMinutes: 8,
  },
  {
    slug: "eng-ch26-articles",
    number: 2,
    title: "The Article Gate",
    titleEs: "The Article Gate",
    level: "A1",
    location: "British Museum, London",
    icon: "📰",
    summary: "a/an/the and zero article — the first gate after London.",
    grammarTopic: "eng-a1-articles-basics",
    vocabTopic: "eng-a1-everyday-objects",
    exerciseTypes: ["multiple_choice", "fill_blank", "translation", "error_correction", "sentence_building"],
    prereqChapter: "eng-ch1-first-steps",
    estimatedMinutes: 9,
  },
  {
    slug: "eng-ch27-possessives",
    number: 3,
    title: "What's Yours?",
    titleEs: "What's Yours?",
    level: "A1",
    location: "Covent Garden, London",
    icon: "🎒",
    summary: "my/your/his and Saxon genitive: Anna's bag.",
    grammarTopic: "eng-a1-possessives",
    vocabTopic: "eng-a1-family-home",
    exerciseTypes: ["multiple_choice", "fill_blank", "translation", "error_correction", "sentence_building"],
    prereqChapter: "eng-ch26-articles",
    estimatedMinutes: 9,
  },
  {
    slug: "eng-ch2-routines",
    number: 4,
    title: "Daily Routines",
    titleEs: "Daily Routines",
    level: "A1",
    location: "Oxford",
    icon: "📚",
    summary: "Present simple, adverbs of frequency, everyday activities.",
    grammarTopic: "eng-a1-present-simple",
    vocabTopic: "eng-a1-everyday-objects",
    exerciseTypes: ["multiple_choice", "translation", "error_correction"],
    prereqChapter: "eng-ch27-possessives",
    estimatedMinutes: 10,
  },
  {
    slug: "eng-ch17-questions",
    number: 5,
    title: "Ask the Guide",
    titleEs: "Ask the Guide",
    level: "A1",
    location: "Bath",
    icon: "💬",
    summary: "Wh- questions: what, who, where, when, why, how.",
    grammarTopic: "eng-a1-questions",
    vocabTopic: "eng-a1-personal-info",
    exerciseTypes: ["multiple_choice", "translation", "error_correction"],
    prereqChapter: "eng-ch2-routines",
    estimatedMinutes: 9,
  },
  {
    slug: "eng-ch3-around-town",
    number: 6,
    title: "Around Town",
    titleEs: "Around Town",
    level: "A1",
    location: "Cambridge",
    icon: "🏘️",
    summary: "there is / there are, some/any with places in town.",
    grammarTopic: "eng-a1-there-is-are",
    vocabTopic: "eng-a1-places-town",
    exerciseTypes: ["multiple_choice", "translation", "error_correction"],
    prereqChapter: "eng-ch17-questions",
    estimatedMinutes: 9,
  },
  {
    slug: "eng-ch18-can",
    number: 7,
    title: "I Can Do It",
    titleEs: "I Can Do It",
    level: "A1",
    location: "Brighton",
    icon: "💪",
    summary: "can / can't — ability, permission, and requests.",
    grammarTopic: "eng-a1-can",
    vocabTopic: "eng-a1-everyday-objects",
    exerciseTypes: ["multiple_choice", "translation", "error_correction"],
    prereqChapter: "eng-ch3-around-town",
    estimatedMinutes: 9,
  },
  {
    slug: "eng-ch19-prepositions",
    number: 8,
    title: "Find Your Way",
    titleEs: "Find Your Way",
    level: "A1",
    location: "Bristol",
    icon: "📍",
    summary: "Prepositions of place: in, on, at, under, between, next to.",
    grammarTopic: "eng-a1-prepositions",
    vocabTopic: "eng-a1-places-town",
    exerciseTypes: ["multiple_choice", "translation", "error_correction", "sentence_building"],
    prereqChapter: "eng-ch18-can",
    estimatedMinutes: 9,
  },
  {
    slug: "eng-ch4-past-stories",
    number: 9,
    title: "Past Stories",
    titleEs: "Past Stories",
    level: "A2",
    location: "York",
    icon: "⚔️",
    summary: "Past simple (regular & irregular), questions, travel verbs.",
    grammarTopic: "eng-a2-past-simple",
    vocabTopic: "eng-a2-travel",
    exerciseTypes: ["multiple_choice", "fill_blank", "translation", "error_correction", "sentence_building"],
    prereqChapter: "eng-ch19-prepositions",
    estimatedMinutes: 10,
  },
  {
    slug: "eng-ch5-choices",
    number: 10,
    title: "The Right Choice",
    titleEs: "The Right Choice",
    level: "A2",
    location: "Edinburgh",
    icon: "⚖️",
    summary: "Comparatives and superlatives.",
    grammarTopic: "eng-a2-comparatives",
    vocabTopic: "eng-a2-shopping",
    exerciseTypes: ["fill_blank", "translation", "error_correction", "sentence_building"],
    prereqChapter: "eng-ch4-past-stories",
    estimatedMinutes: 10,
  },
  {
    slug: "eng-ch28-countable",
    number: 11,
    title: "Count or Not?",
    titleEs: "Count or Not?",
    level: "A2",
    location: "Edinburgh Market",
    icon: "🍎",
    summary: "Countable vs uncountable nouns; much/many, a few/a little.",
    grammarTopic: "eng-a2-countable",
    vocabTopic: "eng-a2-shopping",
    exerciseTypes: ["multiple_choice", "fill_blank", "translation", "error_correction", "sentence_building"],
    prereqChapter: "eng-ch5-choices",
    estimatedMinutes: 10,
  },
  {
    slug: "eng-ch29-pp-intro",
    number: 12,
    title: "Have You Ever…?",
    titleEs: "Have You Ever…?",
    level: "A2",
    location: "Glasgow Cathedral",
    icon: "✨",
    summary: "Present perfect for experience: have/has + V3, ever/never, just/already/yet.",
    grammarTopic: "eng-a2-present-perfect-intro",
    vocabTopic: "eng-a2-travel",
    exerciseTypes: ["multiple_choice", "fill_blank", "translation", "error_correction", "sentence_building"],
    prereqChapter: "eng-ch28-countable",
    estimatedMinutes: 10,
  },
  {
    slug: "eng-ch20-going-to",
    number: 13,
    title: "Plans Ahead",
    titleEs: "Plans Ahead",
    level: "A2",
    location: "Glasgow",
    icon: "🗓️",
    summary: "be going to — intentions and near-future plans.",
    grammarTopic: "eng-a2-going-to",
    vocabTopic: "eng-a2-travel",
    exerciseTypes: ["fill_blank", "translation", "error_correction", "sentence_building"],
    prereqChapter: "eng-ch29-pp-intro",
    estimatedMinutes: 9,
  },
  {
    slug: "eng-ch6-experiences",
    number: 14,
    title: "Global Experiences",
    titleEs: "Global Experiences",
    level: "A2",
    location: "Manchester",
    icon: "🌍",
    summary: "Present perfect, ever/never, life experiences.",
    grammarTopic: "eng-a2-present-perfect",
    vocabTopic: "eng-a2-technology",
    exerciseTypes: ["multiple_choice", "fill_blank", "translation", "error_correction", "sentence_building"],
    prereqChapter: "eng-ch20-going-to",
    estimatedMinutes: 10,
  },
  {
    slug: "eng-ch21-quantifiers",
    number: 15,
    title: "How Much?",
    titleEs: "How Much?",
    level: "A2",
    location: "Leeds",
    icon: "🔢",
    summary: "some, any, much, many, a lot of — countable and uncountable.",
    grammarTopic: "eng-a2-quantifiers",
    vocabTopic: "eng-a2-shopping",
    exerciseTypes: ["multiple_choice", "fill_blank", "translation", "error_correction", "sentence_building"],
    prereqChapter: "eng-ch6-experiences",
    estimatedMinutes: 9,
  },
  {
    slug: "eng-ch7-future-plans",
    number: 16,
    title: "Making Plans",
    titleEs: "Making Plans",
    level: "B1",
    location: "Dublin",
    icon: "🍀",
    summary: "will / won't and the first conditional.",
    grammarTopic: "eng-b1-future-conditional",
    vocabTopic: "eng-b1-personality",
    exerciseTypes: ["fill_blank", "translation", "error_correction", "sentence_building"],
    prereqChapter: "eng-ch21-quantifiers",
    estimatedMinutes: 12,
  },
  {
    slug: "eng-ch30-conditionals-review",
    number: 17,
    title: "If and When",
    titleEs: "If and When",
    level: "B1",
    location: "Dublin Castle",
    icon: "🔀",
    summary: "Zero, first, and second conditionals — real and hypothetical.",
    grammarTopic: "eng-b1-conditionals-review",
    vocabTopic: "eng-b1-personality",
    exerciseTypes: ["multiple_choice", "fill_blank", "translation", "error_correction", "sentence_building"],
    prereqChapter: "eng-ch7-future-plans",
    estimatedMinutes: 11,
  },
  {
    slug: "eng-ch22-modals",
    number: 18,
    title: "Rules of the Road",
    titleEs: "Rules of the Road",
    level: "B1",
    location: "Belfast",
    icon: "📋",
    summary: "should, must, have to — advice and obligation.",
    grammarTopic: "eng-b1-modals",
    vocabTopic: "eng-b1-health-body",
    exerciseTypes: ["translation", "error_correction", "sentence_building"],
    prereqChapter: "eng-ch30-conditionals-review",
    estimatedMinutes: 10,
  },
  {
    slug: "eng-ch8-storytelling",
    number: 19,
    title: "Tell Me a Story",
    titleEs: "Tell Me a Story",
    level: "B1",
    location: "Cardiff",
    icon: "📖",
    summary: "Past continuous, used to, past perfect, narrative tenses.",
    grammarTopic: "eng-b1-narrative",
    vocabTopic: "eng-b1-feelings",
    exerciseTypes: ["fill_blank", "translation", "error_correction", "sentence_building"],
    prereqChapter: "eng-ch22-modals",
    estimatedMinutes: 12,
  },
  {
    slug: "eng-ch9-real-world",
    number: 20,
    title: "The Real World",
    titleEs: "The Real World",
    level: "B1",
    location: "Liverpool",
    icon: "🎵",
    summary: "Present perfect continuous, for/since, life changes.",
    grammarTopic: "eng-b1-perfect-continuous",
    vocabTopic: "eng-b1-health-body",
    exerciseTypes: ["multiple_choice", "fill_blank", "translation", "error_correction", "sentence_building"],
    prereqChapter: "eng-ch8-storytelling",
    estimatedMinutes: 10,
  },
  {
    slug: "eng-ch31-reported-speech",
    number: 21,
    title: "What They Said",
    titleEs: "What They Said",
    level: "B1",
    location: "Liverpool Docks",
    icon: "📢",
    summary: "Reported speech: say/tell, tense backshift, questions and requests.",
    grammarTopic: "eng-b1-reported-speech",
    vocabTopic: "eng-b1-feelings",
    exerciseTypes: ["multiple_choice", "fill_blank", "translation", "error_correction", "sentence_building"],
    prereqChapter: "eng-ch9-real-world",
    estimatedMinutes: 10,
  },
  {
    slug: "eng-ch32-relative-clauses",
    number: 22,
    title: "Who, Which, That",
    titleEs: "Who, Which, That",
    level: "B1",
    location: "Cardiff Bay",
    icon: "🔗",
    summary: "Defining relative clauses: who, which, that, whose.",
    grammarTopic: "eng-b1-relative-clauses",
    vocabTopic: "eng-b1-health-body",
    exerciseTypes: ["multiple_choice", "fill_blank", "translation", "error_correction", "sentence_building"],
    prereqChapter: "eng-ch31-reported-speech",
    estimatedMinutes: 10,
  },
  {
    slug: "eng-ch10-what-if",
    number: 23,
    title: "What If?",
    titleEs: "What If?",
    level: "B2",
    location: "New York",
    icon: "🗽",
    summary: "Second/third conditional, wish/if only, hypotheticals.",
    grammarTopic: "eng-b2-conditionals",
    vocabTopic: "eng-b2-work-jobs",
    exerciseTypes: ["fill_blank", "translation", "error_correction", "sentence_building"],
    prereqChapter: "eng-ch32-relative-clauses",
    estimatedMinutes: 12,
  },
  {
    slug: "eng-ch11-passive",
    number: 24,
    title: "The Passive Voice",
    titleEs: "The Passive Voice",
    level: "B2",
    location: "Boston",
    icon: "🏛️",
    summary: "Passive (all tenses), have something done, processes.",
    grammarTopic: "eng-b2-passive",
    vocabTopic: "eng-b2-education",
    exerciseTypes: ["fill_blank", "translation", "error_correction", "sentence_building"],
    prereqChapter: "eng-ch10-what-if",
    estimatedMinutes: 12,
  },
  {
    slug: "eng-ch33-passive-advanced",
    number: 25,
    title: "Done and Dusted",
    titleEs: "Done and Dusted",
    level: "B2",
    location: "Boston Harbour",
    icon: "🏗️",
    summary: "Passive in all tenses; have/get something done.",
    grammarTopic: "eng-b2-passive-advanced",
    vocabTopic: "eng-b2-education",
    exerciseTypes: ["multiple_choice", "fill_blank", "translation", "error_correction", "sentence_building"],
    prereqChapter: "eng-ch11-passive",
    estimatedMinutes: 12,
  },
  {
    slug: "eng-ch12-beyond-borders",
    number: 26,
    title: "Beyond Borders",
    titleEs: "Beyond Borders",
    level: "B2",
    location: "San Francisco",
    icon: "🌉",
    summary: "Reported speech and relative clauses.",
    grammarTopic: "eng-b2-reported-clauses",
    vocabTopic: "eng-b2-environment",
    exerciseTypes: ["multiple_choice", "fill_blank", "translation", "error_correction", "sentence_building"],
    prereqChapter: "eng-ch33-passive-advanced",
    estimatedMinutes: 12,
  },
  {
    slug: "eng-ch34-modals-deduction",
    number: 27,
    title: "Must Be True",
    titleEs: "Must Be True",
    level: "B2",
    location: "Sydney Harbour",
    icon: "🔍",
    summary: "Modals of deduction: must/might/can't; must have/might have/can't have.",
    grammarTopic: "eng-b2-modals-deduction",
    vocabTopic: "eng-b2-work-jobs",
    exerciseTypes: ["multiple_choice", "fill_blank", "translation", "error_correction"],
    prereqChapter: "eng-ch12-beyond-borders",
    estimatedMinutes: 11,
  },
  {
    slug: "eng-ch35-ielts-informal",
    number: 28,
    title: "Write to a Friend",
    titleEs: "Write to a Friend",
    level: "B1",
    location: "Melbourne Post Office",
    icon: "✉️",
    summary: "IELTS GT informal letter: greeting, bullets, contractions, closing.",
    grammarTopic: "eng-ielts-letter-informal",
    vocabTopic: "eng-c1-exam",
    exerciseTypes: ["translation", "error_correction", "sentence_building"],
    prereqChapter: "eng-ch34-modals-deduction",
    estimatedMinutes: 12,
  },
  {
    slug: "eng-ch36-ielts-formal",
    number: 29,
    title: "A Formal Complaint",
    titleEs: "A Formal Complaint",
    level: "B2",
    location: "Auckland Civic Centre",
    icon: "📜",
    summary: "IELTS GT formal letter: purpose, bullets, Yours faithfully/sincerely.",
    grammarTopic: "eng-ielts-letter-formal",
    vocabTopic: "eng-c1-academic",
    exerciseTypes: ["translation", "error_correction", "sentence_building"],
    prereqChapter: "eng-ch35-ielts-informal",
    estimatedMinutes: 12,
  },
  {
    slug: "eng-ch37-cambridge-letter",
    number: 30,
    title: "Cambridge Email",
    titleEs: "Cambridge Email",
    level: "B2",
    location: "Wellington Embassy",
    icon: "📧",
    summary: "Cambridge B2 letter/email: semi-formal tone, layout, bullet coverage.",
    grammarTopic: "eng-cambridge-letter-email",
    vocabTopic: "eng-c1-collocations-writing",
    exerciseTypes: ["translation", "error_correction", "sentence_building"],
    prereqChapter: "eng-ch36-ielts-formal",
    estimatedMinutes: 12,
  },
  {
    slug: "eng-ch38-ielts-task1",
    number: 31,
    title: "The Data Report",
    titleEs: "The Data Report",
    level: "B2",
    location: "Vancouver Data Centre",
    icon: "📊",
    summary: "IELTS Academic Task 1: overview, trends, comparisons, no opinion.",
    grammarTopic: "eng-ielts-task1-report",
    vocabTopic: "eng-c1-discourse-markers",
    exerciseTypes: ["translation", "error_correction", "sentence_building"],
    prereqChapter: "eng-ch37-cambridge-letter",
    estimatedMinutes: 13,
  },
  {
    slug: "eng-ch39-ielts-essay",
    number: 32,
    title: "Essay Architecture",
    titleEs: "Essay Architecture",
    level: "B2",
    location: "Toronto University Hall",
    icon: "🏛️",
    summary: "IELTS Task 2 structure: intro, body paragraphs, conclusion, thesis.",
    grammarTopic: "eng-ielts-essay-structure",
    vocabTopic: "eng-c1-academic-writing-lexis",
    exerciseTypes: ["translation", "error_correction", "sentence_building"],
    prereqChapter: "eng-ch38-ielts-task1",
    estimatedMinutes: 13,
  },
  {
    slug: "eng-ch40-ielts-cohesion",
    number: 33,
    title: "Links Between Ideas",
    titleEs: "Links Between Ideas",
    level: "C1",
    location: "Montreal Library",
    icon: "🌉",
    summary: "Cohesion: however, furthermore, on the other hand, referencing.",
    grammarTopic: "eng-ielts-essay-cohesion",
    vocabTopic: "eng-c1-discourse-markers",
    exerciseTypes: ["translation", "error_correction", "sentence_building"],
    prereqChapter: "eng-ch39-ielts-essay",
    estimatedMinutes: 12,
  },
  {
    slug: "eng-ch41-cambridge-essay",
    number: 34,
    title: "Essay or Article?",
    titleEs: "Essay or Article?",
    level: "C1",
    location: "Ottawa Parliament",
    icon: "📰",
    summary: "Cambridge C1 essay vs article: audience, title, register, format.",
    grammarTopic: "eng-cambridge-essay-article",
    vocabTopic: "eng-c1-collocations-writing",
    exerciseTypes: ["translation", "error_correction", "sentence_building"],
    prereqChapter: "eng-ch40-ielts-cohesion",
    estimatedMinutes: 13,
  },
  {
    slug: "eng-ch42-ielts-opinion",
    number: 35,
    title: "State Your View",
    titleEs: "State Your View",
    level: "C1",
    location: "Singapore Exam Hall",
    icon: "💬",
    summary: "Opinion language: I believe, it seems, arguably, to what extent.",
    grammarTopic: "eng-ielts-opinion-language",
    vocabTopic: "eng-b2-media-opinions",
    exerciseTypes: ["multiple_choice", "translation", "error_correction", "sentence_building"],
    prereqChapter: "eng-ch41-cambridge-essay",
    estimatedMinutes: 12,
  },
  {
    slug: "eng-ch43-register-shift",
    number: 36,
    title: "Shift the Register",
    titleEs: "Shift the Register",
    level: "C1",
    location: "IELTS Castle",
    icon: "🎭",
    summary: "Register shift: formal ↔ informal, exam traps, consistent tone.",
    grammarTopic: "eng-cbe-register-shift",
    vocabTopic: "eng-c2-nuance-precision",
    exerciseTypes: ["translation", "error_correction", "sentence_building"],
    prereqChapter: "eng-ch42-ielts-opinion",
    estimatedMinutes: 13,
  },
  {
    slug: "eng-ch13-advanced-structures",
    number: 37,
    title: "Advanced Structures",
    titleEs: "Advanced Structures",
    level: "C1",
    location: "Chicago",
    icon: "🏙️",
    summary: "Inversion, emphatic structures, cleft sentences.",
    grammarTopic: "eng-c1-inversion",
    vocabTopic: "eng-c1-idioms",
    exerciseTypes: ["multiple_choice", "fill_blank", "translation", "error_correction", "sentence_building"],
    prereqChapter: "eng-ch43-register-shift",
    estimatedMinutes: 15,
  },
  {
    slug: "eng-ch14-art-language",
    number: 38,
    title: "The Art of Language",
    titleEs: "The Art of Language",
    level: "C1",
    location: "Toronto",
    icon: "🎭",
    summary: "Substitution, ellipsis, fronting, intensifying adverbs.",
    grammarTopic: "eng-c1-discourse",
    vocabTopic: "eng-c1-academic",
    exerciseTypes: ["fill_blank", "translation", "error_correction", "sentence_building"],
    prereqChapter: "eng-ch13-advanced-structures",
    estimatedMinutes: 15,
  },
  {
    slug: "eng-ch15-mastery",
    number: 39,
    title: "Mastery",
    titleEs: "Mastery",
    level: "C1",
    location: "Sydney",
    icon: "🌊",
    summary: "Mixed conditionals, advanced passives, register, literature.",
    grammarTopic: "eng-c1-mixed-conditionals",
    vocabTopic: "eng-c1-literary",
    exerciseTypes: ["fill_blank", "translation", "error_correction", "sentence_building"],
    prereqChapter: "eng-ch14-art-language",
    estimatedMinutes: 15,
  },
  {
    slug: "eng-ch16-ielts",
    number: 40,
    title: "The Final Challenge",
    titleEs: "The Final Challenge",
    level: "C1",
    location: "IELTS Castle",
    icon: "🏰",
    summary: "Comprehensive review + IELTS exam preparation.",
    grammarTopic: "eng-c1-review",
    vocabTopic: "eng-c1-exam",
    exerciseTypes: ["fill_blank", "translation", "error_correction", "sentence_building"],
    prereqChapter: "eng-ch15-mastery",
    estimatedMinutes: 15,
  },
  {
    slug: "eng-ch23-spotlight",
    number: 41,
    title: "In the Spotlight",
    titleEs: "In the Spotlight",
    level: "C2",
    location: "Broadway, New York",
    icon: "🎬",
    summary: "Cleft sentences, emphatic do, fronting — emphasis like a native.",
    grammarTopic: "eng-c2-cleft-emphasis",
    vocabTopic: "eng-c1-literary",
    exerciseTypes: ["multiple_choice", "fill_blank", "translation", "error_correction", "sentence_building"],
    prereqChapter: "eng-ch16-ielts",
    estimatedMinutes: 15,
  },
  {
    slug: "eng-ch24-unspoken",
    number: 42,
    title: "The Unspoken Words",
    titleEs: "The Unspoken Words",
    level: "C2",
    location: "Dublin",
    icon: "☘️",
    summary: "Ellipsis and substitution: so do I, I hope so, if not.",
    grammarTopic: "eng-c2-ellipsis-substitution",
    vocabTopic: "eng-c1-idioms",
    exerciseTypes: ["multiple_choice", "fill_blank", "translation", "error_correction", "sentence_building"],
    prereqChapter: "eng-ch23-spotlight",
    estimatedMinutes: 15,
  },
  {
    slug: "eng-ch25-between-lines",
    number: 43,
    title: "Between the Lines",
    titleEs: "Between the Lines",
    level: "C2",
    location: "Westminster, London",
    icon: "🎩",
    summary: "Hedging, British understatement, polite disagreement.",
    grammarTopic: "eng-c2-hedging-nuance",
    vocabTopic: "eng-c1-academic",
    exerciseTypes: ["fill_blank", "translation", "error_correction", "sentence_building"],
    prereqChapter: "eng-ch24-unspoken",
    estimatedMinutes: 15,
  },
];

export function getEngChapter(slug: string): Chapter | undefined {
  return ENGLISH_CHAPTERS.find((c) => c.slug === slug);
}
export function getEngNextChapter(slug: string): Chapter | undefined {
  const idx = ENGLISH_CHAPTERS.findIndex((c) => c.slug === slug);
  if (idx < 0 || idx + 1 >= ENGLISH_CHAPTERS.length) return undefined;
  return ENGLISH_CHAPTERS[idx + 1];
}
