import type { InterfaceLanguage } from "@/types";

/** Interface-language glosses for Spanish-course vocabulary (key = Spanish lemma). */
export const SPANISH_VOCAB_GLOSS: Partial<
  Record<InterfaceLanguage, Record<string, string>>
> = {
  en: {
  "a mal tiempo, buena cara": "put on a brave face",
  "a tenor de": "in accordance with",
  "a veces": "Sometimes",
  "abril": "April",
  "abrir": "to open",
  "aburrido": "bored",
  "afirmar": "to assert / affirm",
  "agosto": "August",
  "agradecido": "grateful",
  "ahogarse en un vaso de agua": "make a mountain out of a molehill",
  "al respecto": "in this regard",
  "amargo": "bitter",
  "amarillo / amarilla": "yellow",
  "anunciar": "to announce",
  "apoyar": "support",
  "aprender": "to learn",
  "aprobar": "to pass (an exam) / approve",
  "argumentar": "argue",
  "ascender": "to rise / be promoted",
  "asimismo": "likewise / also",
  "asustado": "scared",
  "asustarse": "get scared",
  "avergonzado": "embarrassed",
  "ayer": "yesterday",
  "ayudar": "help",
  "azul": "blue",
  "bailar": "dance",
  "barato / barata": "cheap",
  "beber": "drink",
  "beis": "beige",
  "blanco / blanca": "white",
  "buenísimo (rioplatense)": "very good",
  "cargar": "charge",
  "caro / cara": "Expensive",
  "carro (américa)": "car",
  "casarse": "marry",
  "celoso": "jealous",
  "cerca": "close",
  "cerrar": "close",
  "chaval / chavala (españa)": "guy/girl",
  "ché (argentina)": "hey / listen",
  "chingón (méxico)": "cool (colloquial)",
  "claro / clara": "light",
  "coche (españa)": "car",
  "coger (españa)": "take",
  "coger el toro por los cuernos": "take the bull by the horns",
  "comer": "There is",
  "compartir": "share (opinion)",
  "competente": "competent",
  "comprar": "buy",
  "computadora (américa)": "computer",
  "con miras a": "for the purpose",
  "concluir": "conclude",
  "confirmar": "confirm",
  "conllevar": "entail",
  "conocer": "be familiar",
  "contagioso": "infectious",
  "contradecir": "contradict",
  "convencer": "convince",
  "correr": "run",
  "costar un ojo de la cara": "cost a fortune",
  "creer": "believe/consider",
  "criticar": "criticize",
  "curarse": "get cured",
  "dar fe de": "testify",
  "dar gato por liebre": "sell a fake",
  "dar la cara": "take responsibility",
  "dar la lata": "bother",
  "dar miedo": "scare / be scary",
  "darle vueltas a algo": "ponder",
  "de índole": "character/nature",
  "de la mañana": "morning",
  "de la noche": "nights",
  "de la tarde": "afternoon/evening",
  "deber": "must",
  "decepcionado": "disappointed",
  "defender": "defend (point of view)",
  "derecha": "right",
  "descargar": "download",
  "despedir": "fire",
  "después / luego": "then/then",
  "devolver": "return (product)",
  "diciembre": "December",
  "discrepar": "disagree",
  "divorciarse": "get a divorce",
  "domingo": "Sunday",
  "dorado / dorada": "gold",
  "dudar": "doubt",
  "dulce": "sweet",
  "echar una mano": "help",
  "ejemplificar": "explain with an example",
  "el abogado / la abogada": "advocate",
  "el abrigo": "coat",
  "el abuelo / la abuela": "grandpa/grandmother",
  "el accionista": "shareholder",
  "el aceite": "oil (vegetable)",
  "el acoso": "harassment/bullying",
  "el aeropuerto": "airport",
  "el aficionado": "fan",
  "el agua": "water",
  "el ahorro": "savings",
  "el alcalde / la alcaldesa": "mayor",
  "el algoritmo": "algorithm",
  "el alivio": "relief",
  "el almuerzo / la comida": "dinner",
  "el alumno / el estudiante": "pupil/student",
  "el ámbito": "sphere",
  "el animal": "animal",
  "el año": "year",
  "el apartamento": "apartments",
  "el árbol": "tree",
  "el archivo": "file",
  "el argumento": "argument",
  "el armario": "closet",
  "el arquitecto": "architect",
  "el arroz": "rice",
  "el artista": "artist/artist",
  "el átomo": "atom",
  "el autobús": "bus",
  "el autor / la autora": "author",
  "el avance": "progress/achievement",
  "el avión": "airplane",
  "el azúcar": "sugar",
  "el baloncesto": "basketball",
  "el bañador": "swimsuit / trunks",
  "el banco": "bank",
  "el baño": "bathroom",
  "el bebé": "baby",
  "el beneficio": "profit",
  "el billete / el boleto": "ticket",
  "el blog": "blog",
  "el bolso": "handbag",
  "el bosque": "forest",
  "el brazo": "arm (from shoulder)",
  "el café": "coffee",
  "el cambio": "change",
  "el cambio climático": "climate change",
  "el campus": "campus",
  "el cansancio": "fatigue",
  "el cargador": "charger",
  "el catedrático": "professor",
  "el cementerio": "cemetery",
  "el centro": "center",
  "el check-in / facturación": "check-in for flight",
  "el chequeo médico": "medical examination",
  "el científico": "scientist",
  "el cine": "movie",
  "el cinturón": "belt",
  "el ciudadano": "citizen",
  "el cliente": "client",
  "el clima / el tiempo": "weather",
  "el cocinero / la cocinera": "cook",
  "el cometido": "task/function",
  "el compañero de trabajo": "colleague",
  "el congreso": "congress/parliament",
  "el contraargumento": "counterargument",
  "el contrato": "contract",
  "el corazón": "heart",
  "el correo electrónico": "email mail",
  "el cuadro": "painting",
  "el cuello": "neck",
  "el cuento": "story",
  "el cumpleaños": "birthday",
  "el cuñado / la cuñada": "brother-in-law/sister-in-law",
  "el cupón": "coupon",
  "el dato": "data",
  "el debate": "debate",
  "el dedo": "finger",
  "el deporte": "sport",
  "el derecho": "right",
  "el desayuno": "breakfast",
  "el descanso": "break",
  "el descubrimiento": "opening",
  "el descuento / la rebaja": "discount",
  "el desierto": "desert",
  "el destino": "direction",
  "el determinismo": "determinism",
  "el devenir": "formation / progress",
  "el día": "day",
  "el diente": "tooth",
  "el dinero": "money",
  "el discernimiento": "insight",
  "el disfraz": "costume",
  "el doctorado": "graduate school",
  "el dolor": "pain",
  "el dolor de cabeza": "headache",
  "el dolor de garganta": "sore throat",
  "el enlace": "link",
  "el ensayo": "essay",
  "el entramado": "plexus",
  "el entrenador": "trainer",
  "el equipaje": "baggage",
  "el equipo": "team",
  "el escepticismo": "skepticism",
  "el espacio": "space",
  "el espectador": "viewer",
  "el espejo": "mirror",
  "el estilo": "style",
  "el estómago": "stomach",
  "el examen": "exam",
  "el experimento": "experiment",
  "el fantasma": "ghost",
  "el feminismo": "feminism",
  "el fundamento": "base",
  "el fútbol": "football",
  "el futuro": "future",
  "el garaje": "garage",
  "el género literario": "literary genre",
  "el genoma": "genome",
  "el gimnasio": "gym",
  "el gobierno": "government",
  "el hermano": "Brother",
  "el hijo / la hija": "son/daughter",
  "el hobby / la afición": "hobby",
  "el hombro": "shoulder",
  "el horario": "schedule",
  "el horno": "oven",
  "el hospital": "hospital",
  "el hotel": "hotel",
  "el hueso": "bone",
  "el huevo": "egg",
  "el impairment": "impairment",
  "el impuesto": "tax",
  "el influencer": "influencer",
  "el ingeniero": "engineer",
  "el inodoro": "toilet",
  "el internet": "Internet",
  "el invierno": "winter",
  "el itinerario": "route",
  "el jabón": "soap",
  "el jardín": "garden",
  "el jefe / la jefa": "boss",
  "el laboratorio": "laboratory",
  "el lago": "lake",
  "el lavado de imagen": "reputation laundering",
  "el limón": "lemon",
  "el mapa": "map",
  "el mar": "sea",
  "el marido / el esposo": "husband",
  "el máster": "master's degree",
  "el matiz": "shade (of meaning)",
  "el médico": "doctor",
  "el médico / la médica": "doctor",
  "el medioambiente": "environment",
  "el mensaje": "message",
  "el mercado": "market",
  "el mes": "month",
  "el miedo": "fear",
  "el minuto": "minute",
  "el monstruo": "monster",
  "el mostrador": "counter",
  "el móvil": "mobile",
  "el museo": "museum",
  "el naranja / el zumo": "orange / juice",
  "el nieto / la nieta": "grandson/granddaughter",
  "el nombre": "Name",
  "el novio / la novia": "guy/girl",
  "el otoño": "autumn",
  "el oxímoron": "oxymoron",
  "el padre": "father",
  "el país": "country",
  "el paisaje": "scenery",
  "el pan": "bread",
  "el paradigma": "paradigm",
  "el paro / el desempleo": "unemployment",
  "el parque": "park",
  "el partido": "match",
  "el partido político": "political party",
  "el pasado": "past",
  "el pasajero": "passenger",
  "el pasaporte": "passport",
  "el pelo": "hair",
  "el peluquero / la peluquera": "hairdresser",
  "el periódico": "newspaper",
  "el periodista": "journalist",
  "el personaje": "character",
  "el pescado": "fish",
  "el pib": "GDP",
  "el pie": "sole",
  "el pijama": "pajamas",
  "el piso": "apartment/floor",
  "el plátano": "banana",
  "el podcast": "podcast",
  "el poema": "poem",
  "el polisíndeton": "polysyndeton",
  "el pollo": "chicken",
  "el portátil": "laptop",
  "el postre": "dessert",
  "el pragmatismo": "pragmatism",
  "el precio": "price",
  "el prejuicio": "prejudice",
  "el presidente": "president",
  "el préstamo": "loan",
  "el presupuesto": "budget",
  "el primo / la prima": "cousin/sister",
  "el producto": "product/item",
  "el profesor": "teacher",
  "el profesor / la profesora": "teacher",
  "el programa": "broadcast",
  "el proyecto": "project",
  "el puente": "bridge",
  "el punto de vista": "point of view",
  "el queso": "cheese",
  "el racismo": "racism",
  "el ratón": "mouse",
  "el rayo": "lightning",
  "el razonamiento": "reasoning",
  "el realismo mágico": "magical realism",
  "el recuerdo": "souvenir",
  "el recurso literario": "literary device",
  "el referendum": "referendum",
  "el refugiado": "refugee",
  "el reportaje": "reportage",
  "el resfriado": "cold",
  "el restaurante": "restaurant",
  "el retraso": "delay",
  "el río": "river",
  "el ritmo": "rhythm",
  "el salón": "living room",
  "el semáforo": "traffic light",
  "el semestre / el cuatrimestre": "semester",
  "el símbolo": "symbol",
  "el símil": "comparison",
  "el síntoma": "symptom",
  "el sobrino / la sobrina": "nephew/niece",
  "el sofá": "sofa",
  "el sombrero": "hat",
  "el subtexto": "subtext",
  "el suegro / la suegra": "father-in-law / mother-in-law",
  "el sueldo": "salary",
  "el suelo": "floor",
  "el supermercado": "supermarket",
  "el taxi": "Taxi",
  "el teatro": "theater",
  "el techo": "ceiling/roof",
  "el teclado": "keyboard",
  "el teléfono": "telephone",
  "el tenis": "tennis",
  "el ticket / el recibo": "check",
  "el tío / la tía": "uncle/aunt",
  "el titular": "title",
  "el título": "diploma",
  "el tomate": "tomato",
  "el trabajo": "Job",
  "el traje": "costume",
  "el trasfondo": "background",
  "el tren": "train",
  "el turno": "change",
  "el usuario": "user",
  "el vampiro": "vampire",
  "el verano": "summer",
  "el verso": "poem",
  "el verso libre": "free verse",
  "el vestido": "dress",
  "el viaje": "drive",
  "el viento": "wind",
  "el vino": "wine",
  "el virus": "virus",
  "el voluntariado": "volunteering",
  "el wifi": "Wi-Fi",
  "el yerno / la nuera": "son-in-law/daughter-in-law",
  "emitir": "broadcast",
  "emocionado": "excited",
  "empezar": "start off",
  "en definitiva": "ultimately",
  "en relación con": "in connection with / regarding",
  "en virtud de": "based on",
  "encargar / pedir": "order",
  "enero": "January",
  "enfermo": "sick",
  "enojado / enfadado": "wicked",
  "enseñar": "teach",
  "entrenar": "train",
  "entrevista de trabajo": "interview",
  "entusiasmarse": "get inspired",
  "enviar": "send",
  "escribir": "write",
  "escuchar": "listen",
  "esperar": "wait/hope",
  "esquiar": "ski",
  "estar": "to be (state)",
  "estar a favor": "be for",
  "estar agradecido": "be grateful",
  "estar como una cabra": "be out of your mind",
  "estar de acuerdo": "be in agreement",
  "estar embrujado": "be bewitched",
  "estar en contra": "be against",
  "estar en desacuerdo": "disagree",
  "estar en el quinto pino": "be the devil knows where",
  "estar en las nubes": "have your head in the clouds",
  "estar en paro": "be unemployed",
  "estar enfermo": "be sick",
  "estar forrado": "to have money (colloquial)",
  "estar furioso": "be furious",
  "estar harto": "be fed up",
  "estar hasta el cuello": "be sick and tired",
  "estar seguro": "be sure",
  "estudiar": "to study",
  "exportar": "export",
  "febrero": "February",
  "feliz / contento": "happy",
  "fiaca (argentina)": "laziness",
  "finalmente / al final": "finally",
  "fotografía": "photography (hobby)",
  "fundamentar": "justify",
  "ganar": "win",
  "granate": "burgundy",
  "gratuito": "free",
  "gris": "grey",
  "guagua (caribe)": "bus",
  "guardar": "save",
  "guay (españa)": "Cool",
  "hablar": "speak",
  "hace calor": "hot",
  "hace frío": "Cold",
  "hace sol": "sunny",
  "hacer": "do",
  "hacer ejercicio": "exercise",
  "hacer hincapié": "emphasize",
  "hacerse el sueco": "play the fool",
  "hoy": "Today",
  "hoy en día": "these days",
  "idóneo": "suitable / proper",
  "ilustrar": "illustrate",
  "imparcial": "candid",
  "importar": "import",
  "importar un pepino / un comino": "be completely indifferent",
  "incumbir": "touch / be in charge",
  "informar": "inform",
  "instalar": "install",
  "ir": "go",
  "izquierda": "left",
  "jueves": "Thursday",
  "jugar": "play",
  "jugo (américa)": "juice",
  "julio": "July",
  "junio": "June",
  "justificar": "justify",
  "la acción": "promotion",
  "la aduana": "customs",
  "la alegoría": "allegory",
  "la alegría": "joy",
  "la alergia": "allergy",
  "la alfombra": "carpet",
  "la aliteración": "alliteration",
  "la ambientación": "setting/setting",
  "la ambigüedad": "ambiguity",
  "la ambigüedad deliberada": "deliberate ambiguity",
  "la ambulancia": "ambulance",
  "la anáfora": "anaphora",
  "la aplicación / la app": "application",
  "la asignatura": "item",
  "la bacteria": "bacterium",
  "la banca": "banking",
  "la batería": "battery",
  "la beca": "scholarship",
  "la biblioteca": "library",
  "la biotecnología": "biotechnology",
  "la boca": "mouth",
  "la boda": "wedding",
  "la bolsa": "package/bag",
  "la brecha digital": "digital divide",
  "la brecha salarial": "salary inequality",
  "la bruja": "witch",
  "la bufanda": "scarf",
  "la cabeza": "head",
  "la caja": "cash register",
  "la calabaza": "pumpkin",
  "la calle": "street",
  "la cama": "bed",
  "la cámara": "camera",
  "la camisa": "shirt",
  "la camiseta": "t-shirt",
  "la cara": "face",
  "la carne": "meat",
  "la carpeta": "folder",
  "la cartera / la billetera": "wallet",
  "la casa": "house",
  "la cebolla": "onion",
  "la cena": "dinner",
  "la censura": "censorship",
  "la cerveza": "beer",
  "la chaqueta": "jacket",
  "la ciudad": "city",
  "la ciudadanía": "citizenship",
  "la cocina": "kitchen",
  "la competición": "competition",
  "la competitividad": "competitiveness",
  "la computadora / el ordenador": "computer",
  "la comunidad": "community",
  "la conclusión": "conclusion",
  "la connotación": "connotation",
  "la contraseña": "password",
  "la corrupción": "corruption",
  "la coyuntura": "setting/situation",
  "la crisis": "crisis",
  "la crítica": "criticism",
  "la cultura": "culture",
  "la cura": "medicine/treatment",
  "la democracia": "democracy",
  "la denotación": "denotation",
  "la desigualdad": "inequality",
  "la dialéctica": "dialectics",
  "la dieta": "diet",
  "la discapacidad": "disability",
  "la discriminación": "discrimination",
  "la ducha": "shower",
  "la economía": "economy",
  "la elipsis": "ellipsis",
  "la elocuencia": "eloquence",
  "la emigración": "emigration",
  "la empresa": "enterprise",
  "la energía renovable": "renewable energy",
  "la ensalada": "salad",
  "la entidad": "organization/entity",
  "la entrevista": "interview",
  "la epistemología": "epistemology",
  "la escalera": "ladder",
  "la escuela": "school",
  "la escultura": "sculpture",
  "la esencia": "essence",
  "la espalda": "back",
  "la esquina": "corner",
  "la estación": "station",
  "la estrofa": "stanza",
  "la evidencia": "proof",
  "la exclusión social": "social exclusion",
  "la excursion": "excursion",
  "la exposición": "exhibition",
  "la facultad": "faculty",
  "la fake news": "fake news",
  "la falacia": "sophistry / logical fallacy",
  "la falda": "skirt",
  "la familia": "family",
  "la farmacia": "pharmacy",
  "la fecha": "date",
  "la fiebre": "temperature",
  "la flor": "flower",
  "la fruta": "fruit",
  "la ganga": "bargain",
  "la garantía": "guarantee",
  "la garganta": "throat",
  "la genética": "genetics",
  "la gentrificación": "gentrification",
  "la globalización": "globalization",
  "la gorra": "cap",
  "la gripe": "flu",
  "la guía": "guide / guide",
  "la habitación": "room (in a hotel)",
  "la habitación / el cuarto": "room",
  "la herida": "wound",
  "la hermana": "sister",
  "la hipérbole": "hyperbola",
  "la hipoteca": "mortgage",
  "la hipótesis": "hypothesis",
  "la hora": "hour",
  "la idiosincrasia": "originality",
  "la iglesia": "church",
  "la igualdad": "equality",
  "la ilusión": "inspiration",
  "la immigración": "immigration",
  "la índole": "character/nature",
  "la inflación": "inflation",
  "la inmigración": "immigration",
  "la innovación": "innovation",
  "la integración": "integration",
  "la inteligencia artificial": "artificial intelligence",
  "la intrínseco": "intrinsic",
  "la inversión": "investment",
  "la investigación": "research / investigation",
  "la ironía": "irony",
  "la isla": "island",
  "la jornada": "working day",
  "la justicia": "justice",
  "la lámpara": "lamp",
  "la lavadora": "washing machine",
  "la leche": "milk",
  "la ley": "law",
  "la libertad": "freedom",
  "la libertad de expresión": "freedom of speech",
  "la liquidación": "sale",
  "la literatura universal": "world literature",
  "la llave": "key",
  "la llegada": "arrival",
  "la madre": "mother",
  "la maleta": "suitcase",
  "la mañana": "morning",
  "la manifestación": "demonstration",
  "la manipulation": "manipulation",
  "la mano": "hand (hand)",
  "la manzana": "apple",
  "la marca": "make/brand",
  "la marca blanca": "own brand",
  "la marginación": "marginalization",
  "la máscara": "mask",
  "la matrícula": "enrollment",
  "la medalla": "medal",
  "la medicina": "medicine",
  "la mesa": "table",
  "la metáfora": "metaphor",
  "la molécula": "molecule",
  "la montaña": "mountain",
  "la mujer / la esposa": "wife",
  "la nanotecnología": "nanotechnology",
  "la naranja": "orange",
  "la nariz": "nose",
  "la narrativa": "narration",
  "la nevera / el frigorífico": "fridge",
  "la noche": "night",
  "la nostalgia": "nostalgia",
  "la nota / la calificación": "grade",
  "la novela": "novel",
  "la nube": "cloud",
  "la obra": "work",
  "la obra maestra": "masterpiece",
  "la oferta y la demanda": "supply and demand",
  "la oficina": "office",
  "la oficina de turismo": "tourist office",
  "la ontología": "ontology",
  "la operación": "operation",
  "la opinión": "opinion",
  "la oreja": "ear",
  "la pantalla": "screen",
  "la paradoja": "paradox",
  "la patata / la papa": "potato",
  "la pelota / el balón": "ball",
  "la pérdida": "lesion",
  "la personificación": "personification",
  "la piel": "leather",
  "la pierna": "leg",
  "la pintura": "painting",
  "la piscina": "pool",
  "la playa": "beach",
  "la plaza": "square",
  "la pobreza": "poverty",
  "la poesía": "poetry",
  "la política": "policy",
  "la pollítica": "policy",
  "la portada": "front page",
  "la postura": "position",
  "la premisa": "premise",
  "la primavera": "spring",
  "la privatización": "privatization",
  "la prosa": "prose",
  "la publicidad": "advertising",
  "la puerta": "door",
  "la puerta de embarque": "boarding gate",
  "la rabia": "rage",
  "la radio": "radio",
  "la raqueta": "racket",
  "la recesión": "recession",
  "la receta": "recipe",
  "la reunión": "meeting",
  "la revista": "magazine",
  "la ropa": "cloth",
  "la ropa interior": "underwear",
  "la sal": "salt",
  "la salida": "departure",
  "la salud": "health",
  "la sangre": "blood",
  "la semana": "week",
  "la silla": "chair",
  "la sinergia": "synergy",
  "la sinestesia": "synesthesia",
  "la sociedad": "society",
  "la sopa": "soup",
  "la sorpresa": "astonishment",
  "la sostenibilidad": "sustainability",
  "la tablet": "tablet",
  "la talla": "size",
  "la tarde": "day/evening",
  "la tarea": "task",
  "la tarjeta de crédito": "credit card",
  "la televisión / la tele": "TV",
  "la temperatura": "temperature",
  "la teoría": "theory",
  "la tesis": "thesis",
  "la tienda": "shop",
  "la toalla": "towel",
  "la tormenta": "storm",
  "la tradición": "tradition",
  "la trama": "plot",
  "la tristeza": "sadness",
  "la universidad": "university",
  "la vacuna": "vaccine",
  "la ventana": "window",
  "la verdura": "vegetable",
  "la vergüenza": "shame",
  "la violencia": "violence",
  "la vivienda": "housing",
  "la voz narrativa": "narrator's voice",
  "lana (méxico)": "money",
  "las botas": "boots",
  "las elecciones": "elections",
  "las noticias": "news",
  "las redes sociales": "social networks",
  "las vacaciones": "vacation",
  "las zapatillas": "sneakers",
  "leer": "read",
  "lejos": "far",
  "limpio / limpia": "clean",
  "llamarse": "be called",
  "llover": "go (about rain)",
  "los auriculares": "headphones",
  "los calcetines": "socks",
  "los deberes": "homework",
  "los derechos humanos": "human rights",
  "los guantes": "gloves",
  "los ojos": "eyes",
  "los pantalones": "trousers",
  "los vaqueros": "jeans",
  "los zapatos": "shoes/boots",
  "lunes": "Monday",
  "majo / maja (españa)": "cute/nice",
  "mañana": "Tomorrow",
  "mande (méxico)": "What? / Sorry?",
  "marrón": "brown",
  "martes": "Tuesday",
  "marzo": "March",
  "más vale tarde que nunca": "better late than never",
  "matizar": "clarify / soften",
  "matricularse": "sign up",
  "mayo": "May",
  "mayor": "senior",
  "menor": "younger",
  "menos cuarto": "quarter to quarter",
  "miércoles": "Wednesday",
  "montar en bici": "ride a bike",
  "morado / morada": "violet",
  "muchas veces": "often",
  "nadar": "swim",
  "naranja": "orange",
  "necesitar": "need",
  "negar": "deny",
  "negro / negra": "black",
  "nervioso": "nervous",
  "nevar": "go (about snow)",
  "no dar pie con bola": "not going well",
  "no dar puntada sin hilo": "act with intent",
  "no obstante": "nevertheless",
  "no tener ni idea": "have no idea",
  "no ver tres en un burro": "can't see beyond your own nose",
  "noviembre": "november",
  "nunca": "never",
  "objetar": "mind",
  "objetivamente": "objectively",
  "objetivo": "objective",
  "octubre": "October",
  "ordenador (españa)": "computer",
  "orgulloso": "proud",
  "oscuro / oscura": "dark",
  "pagar": "pay",
  "parecer": "seem",
  "patinar": "skate",
  "pensar": "think",
  "perder": "lose",
  "perderse": "get lost",
  "perdone / disculpe": "Sorry",
  "pibe / piba (argentina)": "guy/girl",
  "pintar": "paint",
  "plata (américa)": "money",
  "plateado / plateada": "silver",
  "poder": "be able",
  "poner en duda": "question",
  "ponerse las botas": "eat up/get rich",
  "por consiguiente": "hence",
  "practicar": "practice",
  "preguntar": "ask",
  "preocupado": "concerned",
  "prieto (méxico)": "dark/swarthy",
  "primero": "first / first",
  "probar": "try on",
  "probarse": "try on",
  "proceder a": "start",
  "quedarse de brazos cruzados": "fold your arms/do nothing",
  "querer": "want",
  "rebajado": "with a discount",
  "rebatir": "dispute",
  "reconocer": "confess",
  "refutar": "refute",
  "renunciar / dimitir": "quit",
  "resaltar": "highlight",
  "reservar": "book",
  "responder": "reply",
  "resultar pertinente": "be appropriate",
  "rico / sabroso": "delicious",
  "rojo / roja": "red",
  "rosa": "pink",
  "sábado": "Saturday",
  "saber": "know",
  "sano / saludable": "healthy",
  "sano y salvo": "safe and sound",
  "sentir": "feel",
  "septiembre": "September",
  "ser": "be (constantly)",
  "ser pan comido": "keep it simple",
  "siempre": "Always",
  "sin techo": "homeless",
  "sorprendido": "surprised",
  "subjetivo": "subjective",
  "subrayar": "emphasize",
  "sucio / sucia": "filthy",
  "suponer": "assume",
  "suscitar": "call",
  "suspender": "fail",
  "tarde": "late",
  "temprano": "early",
  "tener": "have",
  "tener la sartén por el mango": "keep everything under control",
  "tener miedo": "afraid",
  "terminar": "end",
  "tirar la casa por la ventana": "walk in grand style",
  "tocar la guitarra": "play guitar",
  "todavía": "more",
  "tomar (américa)": "take/take transport",
  "tomar el pelo": "tease",
  "tomar la temperatura": "measure temperature",
  "tos": "cough",
  "trabajar": "work",
  "tranquilo": "calm",
  "trascender": "go beyond",
  "tratar": "treat",
  "triste": "sad",
  "turquesa": "turquoise",
  "vale (españa)": "ok/okay",
  "vender": "sell",
  "venir": "come",
  "ver": "see",
  "verde": "green",
  "viajar": "travel",
  "viernes": "Friday",
  "violeta": "violet",
  "viral": "viral",
  "vivir": "live",
  "vos (argentina)": "you (Argentine form)",
  "votar": "vote",
  "y cuarto": "quarter of an hour",
  "y media": "half (hour)",
  "ya": "already",
  "zumo (españa)": "juice",
  },
  es: {
  "a mal tiempo, buena cara": "a mal tiempo, buena cara",
  "a tenor de": "de acuerdo con",
  "a veces": "A veces",
  "abril": "Abril",
  "abrir": "abrir",
  "aburrido": "aburrido",
  "afirmar": "afirmar",
  "agosto": "Agosto",
  "agradecido": "agradecido",
  "ahogarse en un vaso de agua": "ahogarse en un vaso de agua",
  "al respecto": "al respecto",
  "amargo": "amargo",
  "amarillo / amarilla": "amarillo",
  "anunciar": "anunciar",
  "apoyar": "apoyo",
  "aprender": "aprender",
  "aprobar": "aprobar",
  "argumentar": "argumentar",
  "ascender": "ascender",
  "asimismo": "asimismo",
  "asustado": "asustado",
  "asustarse": "asustarse",
  "avergonzado": "avergonzado",
  "ayer": "ayer",
  "ayudar": "ayuda",
  "azul": "azul",
  "bailar": "bailar",
  "barato / barata": "barato",
  "beber": "beber",
  "beis": "beige",
  "blanco / blanca": "blanco",
  "buenísimo (rioplatense)": "muy bien",
  "cargar": "cargar",
  "caro / cara": "Caro",
  "carro (américa)": "auto",
  "casarse": "casarse",
  "celoso": "celoso",
  "cerca": "cerca",
  "cerrar": "cerca",
  "chaval / chavala (españa)": "chico/chica",
  "ché (argentina)": "oye / escucha",
  "chingón (méxico)": "genial (coloquial)",
  "claro / clara": "luz",
  "coche (españa)": "auto",
  "coger (españa)": "llevar",
  "coger el toro por los cuernos": "tomar el toro por los cuernos",
  "comer": "Hay",
  "compartir": "compartir (opinión)",
  "competente": "competente",
  "comprar": "comprar",
  "computadora (américa)": "computadora",
  "con miras a": "para el propósito",
  "concluir": "concluir",
  "confirmar": "confirmar",
  "conllevar": "implicar",
  "conocer": "estar familiarizado",
  "contagioso": "infeccioso",
  "contradecir": "contradecir",
  "convencer": "convencer",
  "correr": "correr",
  "costar un ojo de la cara": "cuesta una fortuna",
  "creer": "creer/considerar",
  "criticar": "criticar",
  "curarse": "curarse",
  "dar fe de": "testificar",
  "dar gato por liebre": "vender una falsificación",
  "dar la cara": "asumir la responsabilidad",
  "dar la lata": "molestar",
  "dar miedo": "asustar / dar miedo",
  "darle vueltas a algo": "reflexionar",
  "de índole": "carácter/naturaleza",
  "de la mañana": "mañana",
  "de la noche": "noches",
  "de la tarde": "tarde/noche",
  "deber": "debe",
  "decepcionado": "decepcionado",
  "defender": "defender (punto de vista)",
  "derecha": "bien",
  "descargar": "descargar",
  "despedir": "fuego",
  "después / luego": "entonces/entonces",
  "devolver": "devolución (producto)",
  "diciembre": "Diciembre",
  "discrepar": "discrepar",
  "divorciarse": "divorciarse",
  "domingo": "Domingo",
  "dorado / dorada": "oro",
  "dudar": "duda",
  "dulce": "dulce",
  "echar una mano": "ayuda",
  "ejemplificar": "explica con un ejemplo",
  "el abogado / la abogada": "defensor",
  "el abrigo": "abrigo",
  "el abuelo / la abuela": "abuelo/abuela",
  "el accionista": "accionista",
  "el aceite": "aceite (vegetal)",
  "el acoso": "acoso/intimidación",
  "el aeropuerto": "aeropuerto",
  "el aficionado": "admirador",
  "el agua": "agua",
  "el ahorro": "ahorros",
  "el alcalde / la alcaldesa": "alcalde",
  "el algoritmo": "algoritmo",
  "el alivio": "alivio",
  "el almuerzo / la comida": "cena",
  "el alumno / el estudiante": "alumno/estudiante",
  "el ámbito": "esfera",
  "el animal": "animal",
  "el año": "año",
  "el apartamento": "apartamentos",
  "el árbol": "árbol",
  "el archivo": "archivo",
  "el argumento": "argumento",
  "el armario": "armario",
  "el arquitecto": "arquitecto",
  "el arroz": "arroz",
  "el artista": "artista/artista",
  "el átomo": "átomo",
  "el autobús": "autobús",
  "el autor / la autora": "autor",
  "el avance": "progreso/logro",
  "el avión": "avión",
  "el azúcar": "azúcar",
  "el baloncesto": "baloncesto",
  "el bañador": "traje de baño / bañadores",
  "el banco": "banco",
  "el baño": "baño",
  "el bebé": "bebé",
  "el beneficio": "ganancia",
  "el billete / el boleto": "boleto",
  "el blog": "blog",
  "el bolso": "bolso",
  "el bosque": "bosque",
  "el brazo": "brazo (desde el hombro)",
  "el café": "café",
  "el cambio": "cambiar",
  "el cambio climático": "cambio climático",
  "el campus": "campus",
  "el cansancio": "fatiga",
  "el cargador": "cargador",
  "el catedrático": "profesor",
  "el cementerio": "cementerio",
  "el centro": "centro",
  "el check-in / facturación": "check-in para el vuelo",
  "el chequeo médico": "examen medico",
  "el científico": "científico",
  "el cine": "película",
  "el cinturón": "cinturón",
  "el ciudadano": "ciudadano",
  "el cliente": "cliente",
  "el clima / el tiempo": "clima",
  "el cocinero / la cocinera": "cocinar",
  "el cometido": "tarea/función",
  "el compañero de trabajo": "colega",
  "el congreso": "congreso/parlamento",
  "el contraargumento": "contraargumento",
  "el contrato": "contrato",
  "el corazón": "corazón",
  "el correo electrónico": "correo electrónico",
  "el cuadro": "cuadro",
  "el cuello": "cuello",
  "el cuento": "historia",
  "el cumpleaños": "cumpleaños",
  "el cuñado / la cuñada": "cuñado/cuñada",
  "el cupón": "cupón",
  "el dato": "datos",
  "el debate": "debate",
  "el dedo": "dedo",
  "el deporte": "deporte",
  "el derecho": "bien",
  "el desayuno": "desayuno",
  "el descanso": "romper",
  "el descubrimiento": "apertura",
  "el descuento / la rebaja": "descuento",
  "el desierto": "desierto",
  "el destino": "dirección",
  "el determinismo": "determinismo",
  "el devenir": "formación / progreso",
  "el día": "día",
  "el diente": "diente",
  "el dinero": "dinero",
  "el discernimiento": "conocimiento",
  "el disfraz": "traje",
  "el doctorado": "Escuela de posgrado",
  "el dolor": "dolor",
  "el dolor de cabeza": "dolor de cabeza",
  "el dolor de garganta": "dolor de garganta",
  "el enlace": "enlace",
  "el ensayo": "ensayo",
  "el entramado": "plexo",
  "el entrenador": "entrenador",
  "el equipaje": "equipaje",
  "el equipo": "equipo",
  "el escepticismo": "escepticismo",
  "el espacio": "espacio",
  "el espectador": "espectador",
  "el espejo": "espejo",
  "el estilo": "estilo",
  "el estómago": "estómago",
  "el examen": "examen",
  "el experimento": "experimento",
  "el fantasma": "fantasma",
  "el feminismo": "feminismo",
  "el fundamento": "base",
  "el fútbol": "fútbol americano",
  "el futuro": "futuro",
  "el garaje": "cochera",
  "el género literario": "genero literario",
  "el genoma": "genoma",
  "el gimnasio": "gimnasia",
  "el gobierno": "gobierno",
  "el hermano": "Hermano",
  "el hijo / la hija": "hijo/hija",
  "el hobby / la afición": "pasatiempo",
  "el hombro": "hombro",
  "el horario": "cronograma",
  "el horno": "horno",
  "el hospital": "hospital",
  "el hotel": "hotel",
  "el hueso": "hueso",
  "el huevo": "huevo",
  "el impairment": "discapacidad",
  "el impuesto": "impuesto",
  "el influencer": "hombre de influencia",
  "el ingeniero": "ingeniero",
  "el inodoro": "baño",
  "el internet": "Internet",
  "el invierno": "invierno",
  "el itinerario": "ruta",
  "el jabón": "jabón",
  "el jardín": "jardín",
  "el jefe / la jefa": "jefe",
  "el laboratorio": "laboratorio",
  "el lago": "lago",
  "el lavado de imagen": "lavado de reputación",
  "el limón": "limón",
  "el mapa": "mapa",
  "el mar": "mar",
  "el marido / el esposo": "marido",
  "el máster": "maestría",
  "el matiz": "sombra (de significado)",
  "el médico": "doctor",
  "el médico / la médica": "doctor",
  "el medioambiente": "ambiente",
  "el mensaje": "mensaje",
  "el mercado": "mercado",
  "el mes": "mes",
  "el miedo": "miedo",
  "el minuto": "minuto",
  "el monstruo": "monstruo",
  "el mostrador": "encimera",
  "el móvil": "móvil",
  "el museo": "museo",
  "el naranja / el zumo": "zumo de naranja",
  "el nieto / la nieta": "nieto/nieta",
  "el nombre": "Nombre",
  "el novio / la novia": "chico/chica",
  "el otoño": "otoño",
  "el oxímoron": "oxímoron",
  "el padre": "padre",
  "el país": "país",
  "el paisaje": "escenario",
  "el pan": "pan",
  "el paradigma": "paradigma",
  "el paro / el desempleo": "desempleo",
  "el parque": "parque",
  "el partido": "fósforo",
  "el partido político": "partido político",
  "el pasado": "pasado",
  "el pasajero": "pasajero",
  "el pasaporte": "pasaporte",
  "el pelo": "cabello",
  "el peluquero / la peluquera": "peluquero",
  "el periódico": "periódico",
  "el periodista": "periodista",
  "el personaje": "personaje",
  "el pescado": "pez",
  "el pib": "PIB",
  "el pie": "único",
  "el pijama": "pijama",
  "el piso": "apartamento/piso",
  "el plátano": "banana",
  "el podcast": "podcast",
  "el poema": "poema",
  "el polisíndeton": "polisíndeton",
  "el pollo": "pollo",
  "el portátil": "computadora portátil",
  "el postre": "postre",
  "el pragmatismo": "pragmatismo",
  "el precio": "precio",
  "el prejuicio": "prejuicio",
  "el presidente": "presidente",
  "el préstamo": "préstamo",
  "el presupuesto": "presupuesto",
  "el primo / la prima": "prima/hermana",
  "el producto": "producto/artículo",
  "el profesor": "maestro",
  "el profesor / la profesora": "maestro",
  "el programa": "transmisión",
  "el proyecto": "proyecto",
  "el puente": "puente",
  "el punto de vista": "Punto de vista",
  "el queso": "queso",
  "el racismo": "racismo",
  "el ratón": "ratón",
  "el rayo": "iluminación",
  "el razonamiento": "razonamiento",
  "el realismo mágico": "realismo mágico",
  "el recuerdo": "recuerdo",
  "el recurso literario": "recurso literario",
  "el referendum": "referéndum",
  "el refugiado": "refugiado",
  "el reportaje": "reportaje",
  "el resfriado": "frío",
  "el restaurante": "restaurante",
  "el retraso": "demora",
  "el río": "río",
  "el ritmo": "ritmo",
  "el salón": "sala de estar",
  "el semáforo": "semáforo",
  "el semestre / el cuatrimestre": "semestre",
  "el símbolo": "símbolo",
  "el símil": "comparación",
  "el síntoma": "síntoma",
  "el sobrino / la sobrina": "sobrino/sobrina",
  "el sofá": "sofá",
  "el sombrero": "sombrero",
  "el subtexto": "sentido solapado",
  "el suegro / la suegra": "suegro / suegra",
  "el sueldo": "salario",
  "el suelo": "piso",
  "el supermercado": "supermercado",
  "el taxi": "Taxi",
  "el teatro": "teatro",
  "el techo": "techo/techo",
  "el teclado": "teclado",
  "el teléfono": "teléfono",
  "el tenis": "tenis",
  "el ticket / el recibo": "controlar",
  "el tío / la tía": "tío/tía",
  "el titular": "título",
  "el título": "diploma",
  "el tomate": "tomate",
  "el trabajo": "Trabajo",
  "el traje": "traje",
  "el trasfondo": "fondo",
  "el tren": "tren",
  "el turno": "cambiar",
  "el usuario": "usuario",
  "el vampiro": "vampiro",
  "el verano": "verano",
  "el verso": "poema",
  "el verso libre": "verso libre",
  "el vestido": "vestido",
  "el viaje": "conducir",
  "el viento": "viento",
  "el vino": "vino",
  "el virus": "virus",
  "el voluntariado": "voluntariado",
  "el wifi": "Wifi",
  "el yerno / la nuera": "yerno/nuera",
  "emitir": "transmisión",
  "emocionado": "entusiasmado",
  "empezar": "empezar",
  "en definitiva": "al final",
  "en relación con": "en relación con / con respecto a",
  "en virtud de": "Residencia en",
  "encargar / pedir": "orden",
  "enero": "Enero",
  "enfermo": "enfermo",
  "enojado / enfadado": "malvado",
  "enseñar": "enseñar",
  "entrenar": "tren",
  "entrevista de trabajo": "entrevista",
  "entusiasmarse": "inspírate",
  "enviar": "enviar",
  "escribir": "escribir",
  "escuchar": "escuchar",
  "esperar": "espera/esperanza",
  "esquiar": "esquí",
  "estar": "ser (estado)",
  "estar a favor": "ser para",
  "estar agradecido": "estar agradecido",
  "estar como una cabra": "estar fuera de tu mente",
  "estar de acuerdo": "estar de acuerdo",
  "estar embrujado": "quedar hechizado",
  "estar en contra": "estar en contra",
  "estar en desacuerdo": "discrepar",
  "estar en el quinto pino": "ser el diablo sabe donde",
  "estar en las nubes": "tener la cabeza en las nubes",
  "estar en paro": "estar desempleado",
  "estar enfermo": "estar enfermo",
  "estar forrado": "tener dinero (coloquial)",
  "estar furioso": "estar furioso",
  "estar harto": "estar harto",
  "estar hasta el cuello": "estar harto de",
  "estar seguro": "estar seguro",
  "estudiar": "estudiar",
  "exportar": "exportar",
  "febrero": "Febrero",
  "feliz / contento": "feliz",
  "fiaca (argentina)": "pereza",
  "finalmente / al final": "finalmente",
  "fotografía": "fotografía (pasatiempo)",
  "fundamentar": "justificar",
  "ganar": "ganar",
  "granate": "borgoña",
  "gratuito": "gratis",
  "gris": "gris",
  "guagua (caribe)": "autobús",
  "guardar": "ahorrar",
  "guay (españa)": "Fresco",
  "hablar": "hablar",
  "hace calor": "caliente",
  "hace frío": "Frío",
  "hace sol": "soleado",
  "hacer": "hacer",
  "hacer ejercicio": "ejercicio",
  "hacer hincapié": "enfatizar",
  "hacerse el sueco": "hacer el tonto",
  "hoy": "Hoy",
  "hoy en día": "estos días",
  "idóneo": "adecuado / adecuado",
  "ilustrar": "ilustrar",
  "imparcial": "sincero",
  "importar": "importar",
  "importar un pepino / un comino": "ser completamente indiferente",
  "incumbir": "tocar / estar a cargo",
  "informar": "informar",
  "instalar": "instalar",
  "ir": "ir",
  "izquierda": "izquierda",
  "jueves": "Jueves",
  "jugar": "jugar",
  "jugo (américa)": "jugo",
  "julio": "Julio",
  "junio": "Junio",
  "justificar": "justificar",
  "la acción": "promoción",
  "la aduana": "aduanas",
  "la alegoría": "alegoría",
  "la alegría": "alegría",
  "la alergia": "alergia",
  "la alfombra": "alfombra",
  "la aliteración": "aliteración",
  "la ambientación": "configuración/configuración",
  "la ambigüedad": "ambigüedad",
  "la ambigüedad deliberada": "ambigüedad deliberada",
  "la ambulancia": "ambulancia",
  "la anáfora": "anáfora",
  "la aplicación / la app": "solicitud",
  "la asignatura": "artículo",
  "la bacteria": "bacteria",
  "la banca": "bancario",
  "la batería": "batería",
  "la beca": "beca",
  "la biblioteca": "biblioteca",
  "la biotecnología": "biotecnología",
  "la boca": "boca",
  "la boda": "boda",
  "la bolsa": "paquete/bolsa",
  "la brecha digital": "brecha digital",
  "la brecha salarial": "desigualdad salarial",
  "la bruja": "bruja",
  "la bufanda": "bufanda",
  "la cabeza": "cabeza",
  "la caja": "caja registradora",
  "la calabaza": "calabaza",
  "la calle": "calle",
  "la cama": "cama",
  "la cámara": "cámara",
  "la camisa": "camisa",
  "la camiseta": "camiseta",
  "la cara": "rostro",
  "la carne": "carne",
  "la carpeta": "carpeta",
  "la cartera / la billetera": "billetera",
  "la casa": "casa",
  "la cebolla": "cebolla",
  "la cena": "cena",
  "la censura": "censura",
  "la cerveza": "cerveza",
  "la chaqueta": "chaqueta",
  "la ciudad": "ciudad",
  "la ciudadanía": "ciudadanía",
  "la cocina": "cocina",
  "la competición": "competencia",
  "la competitividad": "competitividad",
  "la computadora / el ordenador": "computadora",
  "la comunidad": "comunidad",
  "la conclusión": "conclusión",
  "la connotación": "connotación",
  "la contraseña": "contraseña",
  "la corrupción": "corrupción",
  "la coyuntura": "entorno/situación",
  "la crisis": "crisis",
  "la crítica": "crítica",
  "la cultura": "cultura",
  "la cura": "medicina/tratamiento",
  "la democracia": "democracia",
  "la denotación": "denotación",
  "la desigualdad": "desigualdad",
  "la dialéctica": "dialéctica",
  "la dieta": "dieta",
  "la discapacidad": "discapacidad",
  "la discriminación": "discriminación",
  "la ducha": "ducha",
  "la economía": "economía",
  "la elipsis": "elipsis",
  "la elocuencia": "elocuencia",
  "la emigración": "emigración",
  "la empresa": "empresa",
  "la energía renovable": "energía renovable",
  "la ensalada": "ensalada",
  "la entidad": "organización/entidad",
  "la entrevista": "entrevista",
  "la epistemología": "epistemología",
  "la escalera": "escalera",
  "la escuela": "escuela",
  "la escultura": "escultura",
  "la esencia": "esencia",
  "la espalda": "atrás",
  "la esquina": "esquina",
  "la estación": "estación",
  "la estrofa": "estrofa",
  "la evidencia": "prueba",
  "la exclusión social": "exclusión social",
  "la excursion": "excursión",
  "la exposición": "exhibición",
  "la facultad": "facultad",
  "la fake news": "noticias falsas",
  "la falacia": "sofisma / falacia lógica",
  "la falda": "falda",
  "la familia": "familia",
  "la farmacia": "farmacia",
  "la fecha": "fecha",
  "la fiebre": "temperatura",
  "la flor": "flor",
  "la fruta": "fruta",
  "la ganga": "negociar",
  "la garantía": "garantizar",
  "la garganta": "garganta",
  "la genética": "genética",
  "la gentrificación": "gentrificación",
  "la globalización": "globalización",
  "la gorra": "tapa",
  "la gripe": "gripe",
  "la guía": "guía / guía",
  "la habitación": "habitación (en un hotel)",
  "la habitación / el cuarto": "habitación",
  "la herida": "herida",
  "la hermana": "hermana",
  "la hipérbole": "hipérbola",
  "la hipoteca": "hipoteca",
  "la hipótesis": "hipótesis",
  "la hora": "hora",
  "la idiosincrasia": "originalidad",
  "la iglesia": "iglesia",
  "la igualdad": "igualdad",
  "la ilusión": "inspiración",
  "la immigración": "inmigración",
  "la índole": "carácter/naturaleza",
  "la inflación": "inflación",
  "la inmigración": "inmigración",
  "la innovación": "innovación",
  "la integración": "integración",
  "la inteligencia artificial": "inteligencia artificial",
  "la intrínseco": "intrínseco",
  "la inversión": "inversión",
  "la investigación": "la investigación",
  "la ironía": "ironía",
  "la isla": "isla",
  "la jornada": "jornada laboral",
  "la justicia": "justicia",
  "la lámpara": "lámpara",
  "la lavadora": "lavadora",
  "la leche": "leche",
  "la ley": "ley",
  "la libertad": "libertad",
  "la libertad de expresión": "libertad de interlocución",
  "la liquidación": "venta",
  "la literatura universal": "literatura mundial",
  "la llave": "llave",
  "la llegada": "llegada",
  "la madre": "madre",
  "la maleta": "maleta",
  "la mañana": "mañana",
  "la manifestación": "demostración",
  "la manipulation": "manipulación",
  "la mano": "mano (mano)",
  "la manzana": "manzana",
  "la marca": "hacer/marca",
  "la marca blanca": "propia marca",
  "la marginación": "marginalización",
  "la máscara": "mascarilla",
  "la matrícula": "inscripción",
  "la medalla": "medalla",
  "la medicina": "medicamento",
  "la mesa": "mesa",
  "la metáfora": "metáfora",
  "la molécula": "molécula",
  "la montaña": "montaña",
  "la mujer / la esposa": "esposa",
  "la nanotecnología": "nanotecnología",
  "la naranja": "naranja",
  "la nariz": "nariz",
  "la narrativa": "narración",
  "la nevera / el frigorífico": "refrigerador",
  "la noche": "noche",
  "la nostalgia": "nostalgia",
  "la nota / la calificación": "calificación",
  "la novela": "novedoso",
  "la nube": "nube",
  "la obra": "trabajar",
  "la obra maestra": "obra maestra",
  "la oferta y la demanda": "oferta y demanda",
  "la oficina": "oficina",
  "la oficina de turismo": "oficina de turismo",
  "la ontología": "ontología",
  "la operación": "operación",
  "la opinión": "opinión",
  "la oreja": "oreja",
  "la pantalla": "pantalla",
  "la paradoja": "paradoja",
  "la patata / la papa": "papa",
  "la pelota / el balón": "pelota",
  "la pérdida": "lesión",
  "la personificación": "personificación",
  "la piel": "cuero",
  "la pierna": "pierna",
  "la pintura": "cuadro",
  "la piscina": "piscina",
  "la playa": "playa",
  "la plaza": "cuadrado",
  "la pobreza": "pobreza",
  "la poesía": "poesía",
  "la política": "política",
  "la pollítica": "política",
  "la portada": "página delantera",
  "la postura": "posición",
  "la premisa": "premisa",
  "la primavera": "primavera",
  "la privatización": "privatización",
  "la prosa": "prosa",
  "la publicidad": "publicidad",
  "la puerta": "puerta",
  "la puerta de embarque": "puerta de embarque",
  "la rabia": "furia",
  "la radio": "radio",
  "la raqueta": "raqueta",
  "la recesión": "recesión",
  "la receta": "receta",
  "la reunión": "reunión",
  "la revista": "revista",
  "la ropa": "paño",
  "la ropa interior": "ropa interior",
  "la sal": "sal",
  "la salida": "partida",
  "la salud": "salud",
  "la sangre": "sangre",
  "la semana": "semana",
  "la silla": "silla",
  "la sinergia": "sinergia",
  "la sinestesia": "sinestesia",
  "la sociedad": "sociedad",
  "la sopa": "sopa",
  "la sorpresa": "asombro",
  "la sostenibilidad": "sostenibilidad",
  "la tablet": "tableta",
  "la talla": "tamaño",
  "la tarde": "día/tarde",
  "la tarea": "tarea",
  "la tarjeta de crédito": "tarjeta de crédito",
  "la televisión / la tele": "TELEVISOR",
  "la temperatura": "temperatura",
  "la teoría": "teoría",
  "la tesis": "tesis",
  "la tienda": "comercio",
  "la toalla": "toalla",
  "la tormenta": "tormenta",
  "la tradición": "tradición",
  "la trama": "trama",
  "la tristeza": "tristeza",
  "la universidad": "universidad",
  "la vacuna": "vacuna",
  "la ventana": "ventana",
  "la verdura": "verdura",
  "la vergüenza": "lástima",
  "la violencia": "violencia",
  "la vivienda": "alojamiento",
  "la voz narrativa": "voz del narrador",
  "lana (méxico)": "dinero",
  "las botas": "botas",
  "las elecciones": "elecciones",
  "las noticias": "noticias",
  "las redes sociales": "redes sociales",
  "las vacaciones": "vacaciones",
  "las zapatillas": "zapatillas",
  "leer": "leer",
  "lejos": "lejos",
  "limpio / limpia": "limpio",
  "llamarse": "ser llamado",
  "llover": "ir (sobre la lluvia)",
  "los auriculares": "auriculares",
  "los calcetines": "medias",
  "los deberes": "tarea",
  "los derechos humanos": "derechos humanos",
  "los guantes": "guantes",
  "los ojos": "ojos",
  "los pantalones": "pantalones",
  "los vaqueros": "vaqueros",
  "los zapatos": "zapatos/botas",
  "lunes": "Lunes",
  "majo / maja (españa)": "lindo/agradable",
  "mañana": "Mañana",
  "mande (méxico)": "¿Qué? / ¿Lo siento?",
  "marrón": "marrón",
  "martes": "Martes",
  "marzo": "Marzo",
  "más vale tarde que nunca": "más vale tarde que nunca",
  "matizar": "aclarar / suavizar",
  "matricularse": "inscribirse",
  "mayo": "Puede",
  "mayor": "sénior",
  "menor": "más joven",
  "menos cuarto": "cuarto a cuarto",
  "miércoles": "Miércoles",
  "montar en bici": "andar en bicicleta",
  "morado / morada": "violeta",
  "muchas veces": "a menudo",
  "nadar": "nadar",
  "naranja": "naranja",
  "necesitar": "necesidad",
  "negar": "denegar",
  "negro / negra": "negro",
  "nervioso": "nervioso",
  "nevar": "ir (sobre la nieve)",
  "no dar pie con bola": "no va bien",
  "no dar puntada sin hilo": "actuar con intención",
  "no obstante": "sin embargo",
  "no tener ni idea": "no tengo idea",
  "no ver tres en un burro": "no puedes ver más allá de tu propia nariz",
  "noviembre": "noviembre",
  "nunca": "nunca",
  "objetar": "mente",
  "objetivamente": "objetivamente",
  "objetivo": "objetivo",
  "octubre": "Octubre",
  "ordenador (españa)": "computadora",
  "orgulloso": "orgulloso",
  "oscuro / oscura": "oscuro",
  "pagar": "pagar",
  "parecer": "parecer",
  "patinar": "patinar",
  "pensar": "pensar",
  "perder": "perder",
  "perderse": "Piérdase",
  "perdone / disculpe": "Lo siento",
  "pibe / piba (argentina)": "chico/chica",
  "pintar": "pintar",
  "plata (américa)": "dinero",
  "plateado / plateada": "plata",
  "poder": "ser capaz",
  "poner en duda": "pregunta",
  "ponerse las botas": "comer/hacerse rico",
  "por consiguiente": "por eso",
  "practicar": "práctica",
  "preguntar": "preguntar",
  "preocupado": "preocupado",
  "prieto (méxico)": "oscuro/moreno",
  "primero": "primero / primero",
  "probar": "probarse",
  "probarse": "probarse",
  "proceder a": "comenzar",
  "quedarse de brazos cruzados": "cruzar los brazos/no hacer nada",
  "querer": "desear",
  "rebajado": "con un descuento",
  "rebatir": "disputar",
  "reconocer": "confesar",
  "refutar": "refutar",
  "renunciar / dimitir": "abandonar",
  "resaltar": "destacar",
  "reservar": "libro",
  "responder": "responder",
  "resultar pertinente": "ser apropiado",
  "rico / sabroso": "delicioso",
  "rojo / roja": "rojo",
  "rosa": "rosa",
  "sábado": "Sábado",
  "saber": "saber",
  "sano / saludable": "saludable",
  "sano y salvo": "sano y salvo",
  "sentir": "sentir",
  "septiembre": "Septiembre",
  "ser": "ser (constantemente)",
  "ser pan comido": "mantenlo simple",
  "siempre": "Siempre",
  "sin techo": "sin hogar",
  "sorprendido": "sorprendido",
  "subjetivo": "subjetivo",
  "subrayar": "enfatizar",
  "sucio / sucia": "asqueroso",
  "suponer": "asumir",
  "suscitar": "llamar",
  "suspender": "fallar",
  "tarde": "tarde",
  "temprano": "temprano",
  "tener": "tener",
  "tener la sartén por el mango": "mantener todo bajo control",
  "tener miedo": "asustado",
  "terminar": "fin",
  "tirar la casa por la ventana": "caminar con gran estilo",
  "tocar la guitarra": "tocar la guitarra",
  "todavía": "más",
  "tomar (américa)": "tomar/tomar transporte",
  "tomar el pelo": "fastidiar",
  "tomar la temperatura": "medir la temperatura",
  "tos": "tos",
  "trabajar": "trabajar",
  "tranquilo": "calma",
  "trascender": "ir tras",
  "tratar": "tratar",
  "triste": "triste",
  "turquesa": "turquesa",
  "vale (españa)": "bien/bien",
  "vender": "vender",
  "venir": "venir",
  "ver": "ver",
  "verde": "verde",
  "viajar": "viajar",
  "viernes": "Viernes",
  "violeta": "violeta",
  "viral": "viral",
  "vivir": "vivir",
  "vos (argentina)": "tú (forma argentina)",
  "votar": "votar",
  "y cuarto": "cuarto de hora",
  "y media": "media (hora)",
  "ya": "ya",
  "zumo (españa)": "jugo",
  },
  de: {
  "a mal tiempo, buena cara": "gute Miene zum bösen Spiel",
  "a tenor de": "in Übereinstimmung mit",
  "a veces": "Manchmal",
  "abril": "April",
  "abrir": "öffnen",
  "aburrido": "gelangweilt",
  "afirmar": "behaupten",
  "agosto": "August",
  "agradecido": "dankbar",
  "ahogarse en un vaso de agua": "aus einer Mücke einen Elefanten machen",
  "al respecto": "diesbezüglich",
  "amargo": "bitter",
  "amarillo / amarilla": "Gelb",
  "anunciar": "ankündigen",
  "apoyar": "Unterstützung",
  "aprender": "lernen",
  "aprobar": "bestehen / genehmigen",
  "argumentar": "argumentieren",
  "ascender": "aufsteigen",
  "asimismo": "ebenfalls",
  "asustado": "ängstlich",
  "asustarse": "Angst bekommen",
  "avergonzado": "beschämt",
  "ayer": "gestern",
  "ayudar": "helfen",
  "azul": "Blau",
  "bailar": "tanzen",
  "barato / barata": "billig",
  "beber": "trinken",
  "beis": "Beige",
  "blanco / blanca": "Weiß",
  "buenísimo (rioplatense)": "sehr gut",
  "cargar": "Aufladung",
  "caro / cara": "Teuer",
  "carro (américa)": "Auto",
  "casarse": "heiraten",
  "celoso": "eifersüchtig",
  "cerca": "schließen",
  "cerrar": "schließen",
  "chaval / chavala (españa)": "Mann/Mädchen",
  "ché (argentina)": "hey / hör zu",
  "chingón (méxico)": "cool (umgangssprachlich)",
  "claro / clara": "Licht",
  "coche (españa)": "Auto",
  "coger (españa)": "nehmen",
  "coger el toro por los cuernos": "Packt den Stier bei den Hörnern",
  "comer": "Es gibt",
  "compartir": "teilen (Meinung)",
  "competente": "kompetent",
  "comprar": "kaufen",
  "computadora (américa)": "Computer",
  "con miras a": "für den Zweck",
  "concluir": "abschließen",
  "confirmar": "bestätigen",
  "conllevar": "mit sich bringen",
  "conocer": "vertraut sein",
  "contagioso": "ansteckend",
  "contradecir": "widersprechen",
  "convencer": "überzeugen",
  "correr": "laufen",
  "costar un ojo de la cara": "kostet ein Vermögen",
  "creer": "glauben/erwägen",
  "criticar": "kritisieren",
  "curarse": "geheilt werden",
  "dar fe de": "bezeugen",
  "dar gato por liebre": "eine Fälschung verkaufen",
  "dar la cara": "Verantwortung übernehmen",
  "dar la lata": "sich kümmern",
  "dar miedo": "erschrecken / unheimlich sein",
  "darle vueltas a algo": "nachdenken",
  "de índole": "Charakter/Natur",
  "de la mañana": "Morgen",
  "de la noche": "Nächte",
  "de la tarde": "nachmittags/abends",
  "deber": "muss",
  "decepcionado": "enttäuscht",
  "defender": "verteidigen (Standpunkt)",
  "derecha": "Rechts",
  "descargar": "herunterladen",
  "despedir": "Feuer",
  "después / luego": "dann/dann",
  "devolver": "Rückgabe (Produkt)",
  "diciembre": "Dezember",
  "discrepar": "verschiedener Meinung sein",
  "divorciarse": "sich scheiden lassen",
  "domingo": "Sonntag",
  "dorado / dorada": "Gold",
  "dudar": "zweifeln",
  "dulce": "süß",
  "echar una mano": "helfen",
  "ejemplificar": "an einem Beispiel erklären",
  "el abogado / la abogada": "Fürsprecher",
  "el abrigo": "Mantel",
  "el abuelo / la abuela": "Opa/Großmutter",
  "el accionista": "Aktionär",
  "el aceite": "Öl (pflanzlich)",
  "el acoso": "Belästigung/Mobbing",
  "el aeropuerto": "Flughafen",
  "el aficionado": "Lüfter",
  "el agua": "Wasser",
  "el ahorro": "Ersparnisse",
  "el alcalde / la alcaldesa": "Bürgermeister",
  "el algoritmo": "Algorithmus",
  "el alivio": "Erleichterung",
  "el almuerzo / la comida": "Abendessen",
  "el alumno / el estudiante": "Schüler/Student",
  "el ámbito": "Kugel",
  "el animal": "Tier",
  "el año": "Jahr",
  "el apartamento": "Wohnungen",
  "el árbol": "Baum",
  "el archivo": "Datei",
  "el argumento": "Argument",
  "el armario": "Kleiderschrank",
  "el arquitecto": "Architekt",
  "el arroz": "Reis",
  "el artista": "Künstler/Künstler",
  "el átomo": "Atom",
  "el autobús": "Bus",
  "el autor / la autora": "Autor",
  "el avance": "Fortschritt/Leistung",
  "el avión": "Flugzeug",
  "el azúcar": "Zucker",
  "el baloncesto": "Basketball",
  "el bañador": "Badeanzug / Badehose",
  "el banco": "Bank",
  "el baño": "Badezimmer",
  "el bebé": "Baby",
  "el beneficio": "profitieren",
  "el billete / el boleto": "Ticket",
  "el blog": "Blog",
  "el bolso": "Handtasche",
  "el bosque": "Wald",
  "el brazo": "Arm (von der Schulter)",
  "el café": "Kaffee",
  "el cambio": "ändern",
  "el cambio climático": "Klimawandel",
  "el campus": "Campus",
  "el cansancio": "Ermüdung",
  "el cargador": "Ladegerät",
  "el catedrático": "Professor",
  "el cementerio": "Friedhof",
  "el centro": "Center",
  "el check-in / facturación": "Check-in für den Flug",
  "el chequeo médico": "ärztliche Untersuchung",
  "el científico": "Wissenschaftler",
  "el cine": "Film",
  "el cinturón": "Gürtel",
  "el ciudadano": "Bürger",
  "el cliente": "Kunde",
  "el clima / el tiempo": "Wetter",
  "el cocinero / la cocinera": "kochen",
  "el cometido": "Aufgabe/Funktion",
  "el compañero de trabajo": "Kollege",
  "el congreso": "Kongress/Parlament",
  "el contraargumento": "Gegenargument",
  "el contrato": "Vertrag",
  "el corazón": "Herz",
  "el correo electrónico": "E-Mail-Post",
  "el cuadro": "Malerei",
  "el cuello": "Nacken",
  "el cuento": "Geschichte",
  "el cumpleaños": "Geburtstag",
  "el cuñado / la cuñada": "Schwager/Schwägerin",
  "el cupón": "Coupon",
  "el dato": "Daten",
  "el debate": "Debatte",
  "el dedo": "Finger",
  "el deporte": "Sport",
  "el derecho": "Rechts",
  "el desayuno": "Frühstück",
  "el descanso": "brechen",
  "el descubrimiento": "Öffnung",
  "el descuento / la rebaja": "Rabatt",
  "el desierto": "Wüste",
  "el destino": "Richtung",
  "el determinismo": "Determinismus",
  "el devenir": "Bildung / Fortschritt",
  "el día": "Tag",
  "el diente": "Zahn",
  "el dinero": "Geld",
  "el discernimiento": "Einblick",
  "el disfraz": "Kostüm",
  "el doctorado": "Handelshochschule",
  "el dolor": "Schmerz",
  "el dolor de cabeza": "Kopfschmerzen",
  "el dolor de garganta": "Halsschmerzen",
  "el enlace": "Link",
  "el ensayo": "Aufsatz",
  "el entramado": "Plexus",
  "el entrenador": "Trainer",
  "el equipaje": "Gepäck",
  "el equipo": "Team",
  "el escepticismo": "Skepsis",
  "el espacio": "Raum",
  "el espectador": "Zuschauer",
  "el espejo": "Spiegel",
  "el estilo": "Stil",
  "el estómago": "Magen",
  "el examen": "Prüfung",
  "el experimento": "Experiment",
  "el fantasma": "Geist",
  "el feminismo": "Feminismus",
  "el fundamento": "Base",
  "el fútbol": "Fußball",
  "el futuro": "Zukunft",
  "el garaje": "Garage",
  "el género literario": "literarisches Genre",
  "el genoma": "Genom",
  "el gimnasio": "Fitnessstudio",
  "el gobierno": "Regierung",
  "el hermano": "Bruder",
  "el hijo / la hija": "Sohn/Tochter",
  "el hobby / la afición": "Hobby",
  "el hombro": "Schulter",
  "el horario": "Zeitplan",
  "el horno": "Ofen",
  "el hospital": "Krankenhaus",
  "el hotel": "Hotel",
  "el hueso": "Knochen",
  "el huevo": "Ei",
  "el impairment": "Beeinträchtigung",
  "el impuesto": "Steuer",
  "el influencer": "Influencer",
  "el ingeniero": "Ingenieur",
  "el inodoro": "Toilette",
  "el internet": "Internet",
  "el invierno": "Winter",
  "el itinerario": "Route",
  "el jabón": "Seife",
  "el jardín": "Garten",
  "el jefe / la jefa": "Chef",
  "el laboratorio": "Labor",
  "el lago": "See",
  "el lavado de imagen": "Reputationswäsche",
  "el limón": "Zitrone",
  "el mapa": "Karte",
  "el mar": "Meer",
  "el marido / el esposo": "Ehemann",
  "el máster": "Master-Abschluss",
  "el matiz": "Schatten (der Bedeutung)",
  "el médico": "Arzt",
  "el médico / la médica": "Arzt",
  "el medioambiente": "Umfeld",
  "el mensaje": "Nachricht",
  "el mercado": "Markt",
  "el mes": "Monat",
  "el miedo": "Furcht",
  "el minuto": "Minute",
  "el monstruo": "Monster",
  "el mostrador": "Schalter",
  "el móvil": "Mobile",
  "el museo": "Museum",
  "el naranja / el zumo": "Orange / Saft",
  "el nieto / la nieta": "Enkel/Enkelin",
  "el nombre": "Name",
  "el novio / la novia": "Mann/Mädchen",
  "el otoño": "Herbst",
  "el oxímoron": "Oxymoron",
  "el padre": "Vater",
  "el país": "Land",
  "el paisaje": "Landschaft",
  "el pan": "brot",
  "el paradigma": "Paradigma",
  "el paro / el desempleo": "Arbeitslosigkeit",
  "el parque": "Park",
  "el partido": "übereinstimmen",
  "el partido político": "politische Partei",
  "el pasado": "Vergangenheit",
  "el pasajero": "Passagier",
  "el pasaporte": "Reisepass",
  "el pelo": "Haar",
  "el peluquero / la peluquera": "Friseur",
  "el periódico": "Zeitung",
  "el periodista": "Journalist",
  "el personaje": "Charakter",
  "el pescado": "Fisch",
  "el pib": "BIP",
  "el pie": "Sohle, einzig, alleinig",
  "el pijama": "Pyjama",
  "el piso": "Wohnung/Etage",
  "el plátano": "Banane",
  "el podcast": "Podcast",
  "el poema": "Gedicht",
  "el polisíndeton": "Polysyndeton",
  "el pollo": "Huhn",
  "el portátil": "Laptop",
  "el postre": "Nachtisch",
  "el pragmatismo": "Pragmatismus",
  "el precio": "Preis",
  "el prejuicio": "Vorurteil",
  "el presidente": "Präsident",
  "el préstamo": "Darlehen",
  "el presupuesto": "Budget",
  "el primo / la prima": "Cousine/Schwester",
  "el producto": "Produkt/Artikel",
  "el profesor": "Lehrer",
  "el profesor / la profesora": "Lehrer",
  "el programa": "übertragen",
  "el proyecto": "Projekt",
  "el puente": "Brücke",
  "el punto de vista": "Standpunkt",
  "el queso": "Käse",
  "el racismo": "Rassismus",
  "el ratón": "Maus",
  "el rayo": "Blitz",
  "el razonamiento": "Argumentation",
  "el realismo mágico": "magischer Realismus",
  "el recuerdo": "Souvenir",
  "el recurso literario": "literarisches Gerät",
  "el referendum": "Referendum",
  "el refugiado": "Flüchtling",
  "el reportaje": "Reportage",
  "el resfriado": "kalt",
  "el restaurante": "Restaurant",
  "el retraso": "Verzögerung",
  "el río": "Fluss",
  "el ritmo": "Rhythmus",
  "el salón": "Wohnzimmer",
  "el semáforo": "Ampel",
  "el semestre / el cuatrimestre": "Semester",
  "el símbolo": "Symbol",
  "el símil": "Vergleich",
  "el síntoma": "Symptom",
  "el sobrino / la sobrina": "Neffe/Nichte",
  "el sofá": "Sofa",
  "el sombrero": "Hut",
  "el subtexto": "Subtext",
  "el suegro / la suegra": "Schwiegervater / Schwiegermutter",
  "el sueldo": "Gehalt",
  "el suelo": "Boden",
  "el supermercado": "Supermarkt",
  "el taxi": "Taxi",
  "el teatro": "Theater",
  "el techo": "Decke/Dach",
  "el teclado": "Tastatur",
  "el teléfono": "Telefon",
  "el tenis": "Tennis",
  "el ticket / el recibo": "überprüfen",
  "el tío / la tía": "Onkel/Tante",
  "el titular": "Titel",
  "el título": "Diplom",
  "el tomate": "Tomate",
  "el trabajo": "Arbeit",
  "el traje": "Kostüm",
  "el trasfondo": "Hintergrund",
  "el tren": "Zug",
  "el turno": "ändern",
  "el usuario": "Benutzer",
  "el vampiro": "Vampir",
  "el verano": "Sommer",
  "el verso": "Gedicht",
  "el verso libre": "freier Vers",
  "el vestido": "Kleid",
  "el viaje": "fahren",
  "el viento": "Wind",
  "el vino": "Wein",
  "el virus": "Virus",
  "el voluntariado": "Freiwilligenarbeit",
  "el wifi": "W-lan",
  "el yerno / la nuera": "Schwiegersohn/Schwiegertochter",
  "emitir": "übertragen",
  "emocionado": "aufgeregt",
  "empezar": "beginnen",
  "en definitiva": "letztlich",
  "en relación con": "im Zusammenhang mit / bezüglich",
  "en virtud de": "bezogen auf",
  "encargar / pedir": "Befehl",
  "enero": "Januar",
  "enfermo": "krank",
  "enojado / enfadado": "böse",
  "enseñar": "unterrichten",
  "entrenar": "Zug",
  "entrevista de trabajo": "Interview",
  "entusiasmarse": "Lassen Sie sich inspirieren",
  "enviar": "schicken",
  "escribir": "schreiben",
  "escuchar": "Hören",
  "esperar": "warten/hoffen",
  "esquiar": "Ski",
  "estar": "sein (zustand)",
  "estar a favor": "sei für",
  "estar agradecido": "sei dankbar",
  "estar como una cabra": "Sei verrückt",
  "estar de acuerdo": "einig sein",
  "estar embrujado": "verzaubert sein",
  "estar en contra": "dagegen sein",
  "estar en desacuerdo": "verschiedener Meinung sein",
  "estar en el quinto pino": "Sei der Teufel weiß wo",
  "estar en las nubes": "Habe deinen Kopf in den Wolken",
  "estar en paro": "arbeitslos sein",
  "estar enfermo": "krank sein",
  "estar forrado": "Geld haben (umgangssprachlich)",
  "estar furioso": "Sei wütend",
  "estar harto": "satt sein",
  "estar hasta el cuello": "sei krank und müde",
  "estar seguro": "Seien Sie sicher",
  "estudiar": "studieren",
  "exportar": "Export",
  "febrero": "Februar",
  "feliz / contento": "Glücklich",
  "fiaca (argentina)": "Faulheit",
  "finalmente / al final": "Endlich",
  "fotografía": "Fotografie (Hobby)",
  "fundamentar": "rechtfertigen",
  "ganar": "gewinnen",
  "granate": "Burgund",
  "gratuito": "frei",
  "gris": "grau",
  "guagua (caribe)": "Bus",
  "guardar": "speichern",
  "guay (españa)": "Cool",
  "hablar": "sprechen",
  "hace calor": "heiß",
  "hace frío": "Kalt",
  "hace sol": "sonnig",
  "hacer": "Tun",
  "hacer ejercicio": "Übung",
  "hacer hincapié": "betonen",
  "hacerse el sueco": "spiel den Narren",
  "hoy": "Heute",
  "hoy en día": "heutzutage",
  "idóneo": "geeignet / richtig",
  "ilustrar": "veranschaulichen",
  "imparcial": "offen",
  "importar": "Import",
  "importar un pepino / un comino": "völlig gleichgültig sein",
  "incumbir": "berühren / verantwortlich sein",
  "informar": "informieren",
  "instalar": "installieren",
  "ir": "gehen",
  "izquierda": "links",
  "jueves": "Donnerstag",
  "jugar": "spielen",
  "jugo (américa)": "Saft",
  "julio": "Juli",
  "junio": "Juni",
  "justificar": "rechtfertigen",
  "la acción": "Förderung",
  "la aduana": "Zoll",
  "la alegoría": "Allegorie",
  "la alegría": "Freude",
  "la alergia": "Allergie",
  "la alfombra": "Teppich",
  "la aliteración": "Alliteration",
  "la ambientación": "Einstellung/Einstellung",
  "la ambigüedad": "Mehrdeutigkeit",
  "la ambigüedad deliberada": "absichtliche Mehrdeutigkeit",
  "la ambulancia": "Krankenwagen",
  "la anáfora": "Anaphora",
  "la aplicación / la app": "Anwendung",
  "la asignatura": "Artikel",
  "la bacteria": "Bakterium",
  "la banca": "Bankwesen",
  "la batería": "Batterie",
  "la beca": "Stipendium",
  "la biblioteca": "Bibliothek",
  "la biotecnología": "Biotechnologie",
  "la boca": "Mund",
  "la boda": "Hochzeit",
  "la bolsa": "Paket/Beutel",
  "la brecha digital": "digitale Kluft",
  "la brecha salarial": "Gehaltsungleichheit",
  "la bruja": "Hexe",
  "la bufanda": "Schal",
  "la cabeza": "Kopf",
  "la caja": "Kasse",
  "la calabaza": "Kürbis",
  "la calle": "Straße",
  "la cama": "Bett",
  "la cámara": "Kamera",
  "la camisa": "Hemd",
  "la camiseta": "T-Shirt",
  "la cara": "Gesicht",
  "la carne": "Fleisch",
  "la carpeta": "Ordner",
  "la cartera / la billetera": "Geldbörse",
  "la casa": "Haus",
  "la cebolla": "Zwiebel",
  "la cena": "Abendessen",
  "la censura": "Zensur",
  "la cerveza": "Bier",
  "la chaqueta": "Jacke",
  "la ciudad": "Stadt",
  "la ciudadanía": "Staatsbürgerschaft",
  "la cocina": "Küche",
  "la competición": "Wettbewerb",
  "la competitividad": "Wettbewerbsfähigkeit",
  "la computadora / el ordenador": "Computer",
  "la comunidad": "Gemeinschaft",
  "la conclusión": "Abschluss",
  "la connotación": "Konnotation",
  "la contraseña": "Passwort",
  "la corrupción": "Korruption",
  "la coyuntura": "Einstellung/Situation",
  "la crisis": "Krise",
  "la crítica": "Kritik",
  "la cultura": "Kultur",
  "la cura": "Medizin/Behandlung",
  "la democracia": "Demokratie",
  "la denotación": "Bezeichnung",
  "la desigualdad": "Ungleichheit",
  "la dialéctica": "Dialektik",
  "la dieta": "Diät",
  "la discapacidad": "Behinderung",
  "la discriminación": "Diskriminierung",
  "la ducha": "Dusche",
  "la economía": "Wirtschaft",
  "la elipsis": "Ellipse",
  "la elocuencia": "Beredsamkeit",
  "la emigración": "Auswanderung",
  "la empresa": "Unternehmen",
  "la energía renovable": "erneuerbare Energie",
  "la ensalada": "Salat",
  "la entidad": "Organisation/Einheit",
  "la entrevista": "Interview",
  "la epistemología": "Erkenntnistheorie",
  "la escalera": "Leiter",
  "la escuela": "Schule",
  "la escultura": "Skulptur",
  "la esencia": "Wesen",
  "la espalda": "zurück",
  "la esquina": "Ecke",
  "la estación": "Station",
  "la estrofa": "Strophe",
  "la evidencia": "nachweisen",
  "la exclusión social": "soziale Ausgrenzung",
  "la excursion": "Ausflug",
  "la exposición": "Ausstellung",
  "la facultad": "Fakultät",
  "la fake news": "Fake-News",
  "la falacia": "Sophistik / logischer Irrtum",
  "la falda": "Rock",
  "la familia": "Familie",
  "la farmacia": "Apotheke",
  "la fecha": "Datum",
  "la fiebre": "Temperatur",
  "la flor": "Blume",
  "la fruta": "Obst",
  "la ganga": "Schnäppchen",
  "la garantía": "Garantie",
  "la garganta": "Kehle",
  "la genética": "Genetik",
  "la gentrificación": "Gentrifizierung",
  "la globalización": "Globalisierung",
  "la gorra": "Kappe",
  "la gripe": "Grippe",
  "la guía": "Führer / Führer",
  "la habitación": "Zimmer (in einem Hotel)",
  "la habitación / el cuarto": "Zimmer",
  "la herida": "Wunde",
  "la hermana": "Schwester",
  "la hipérbole": "Hyperbel",
  "la hipoteca": "Hypothek",
  "la hipótesis": "Hypothese",
  "la hora": "Stunde",
  "la idiosincrasia": "Originalität",
  "la iglesia": "Kirche",
  "la igualdad": "Gleichwertigkeit",
  "la ilusión": "Inspiration",
  "la immigración": "Einwanderung",
  "la índole": "Charakter/Natur",
  "la inflación": "Inflation",
  "la inmigración": "Einwanderung",
  "la innovación": "Innovation",
  "la integración": "Integration",
  "la inteligencia artificial": "künstliche Intelligenz",
  "la intrínseco": "intrinsisch",
  "la inversión": "Investition",
  "la investigación": "die Forschung / Untersuchung",
  "la ironía": "Ironie",
  "la isla": "Insel",
  "la jornada": "Arbeitstag",
  "la justicia": "Gerechtigkeit",
  "la lámpara": "Lampe",
  "la lavadora": "Waschmaschine",
  "la leche": "Milch",
  "la ley": "Gesetz",
  "la libertad": "Freiheit",
  "la libertad de expresión": "Redefreiheit",
  "la liquidación": "Verkauf",
  "la literatura universal": "Weltliteratur",
  "la llave": "Schlüssel",
  "la llegada": "Ankunft",
  "la madre": "Mutter",
  "la maleta": "Koffer",
  "la mañana": "Morgen",
  "la manifestación": "Demonstration",
  "la manipulation": "Manipulation",
  "la mano": "Hand (Hand)",
  "la manzana": "Apfel",
  "la marca": "Marke/Marke",
  "la marca blanca": "eigene Marke",
  "la marginación": "Marginalisierung",
  "la máscara": "Maske",
  "la matrícula": "Einschreibung",
  "la medalla": "Medaille",
  "la medicina": "Medizin",
  "la mesa": "Tisch",
  "la metáfora": "Metapher",
  "la molécula": "Molekül",
  "la montaña": "Berg",
  "la mujer / la esposa": "Gattin",
  "la nanotecnología": "Nanotechnologie",
  "la naranja": "orange",
  "la nariz": "Nase",
  "la narrativa": "Erzählung",
  "la nevera / el frigorífico": "Kühlschrank",
  "la noche": "Nacht",
  "la nostalgia": "Nostalgie",
  "la nota / la calificación": "Grad",
  "la novela": "Roman",
  "la nube": "Wolke",
  "la obra": "arbeiten",
  "la obra maestra": "Meisterwerk",
  "la oferta y la demanda": "Angebot und Nachfrage",
  "la oficina": "Büro",
  "la oficina de turismo": "Tourismusbüro",
  "la ontología": "Ontologie",
  "la operación": "Betrieb",
  "la opinión": "Meinung",
  "la oreja": "Ohr",
  "la pantalla": "Bildschirm",
  "la paradoja": "Paradox",
  "la patata / la papa": "Kartoffel",
  "la pelota / el balón": "Ball",
  "la pérdida": "Läsion",
  "la personificación": "Personifikation",
  "la piel": "Leder",
  "la pierna": "Bein",
  "la pintura": "Malerei",
  "la piscina": "Pool",
  "la playa": "Strand",
  "la plaza": "Quadrat",
  "la pobreza": "Armut",
  "la poesía": "Poesie",
  "la política": "Politik",
  "la pollítica": "Politik",
  "la portada": "Titelseite",
  "la postura": "Position",
  "la premisa": "Prämisse",
  "la primavera": "Frühling",
  "la privatización": "Privatisierung",
  "la prosa": "Prosa",
  "la publicidad": "Werbung",
  "la puerta": "Tür",
  "la puerta de embarque": "Flugsteig",
  "la rabia": "Wut",
  "la radio": "Radio",
  "la raqueta": "Schläger",
  "la recesión": "Rezession",
  "la receta": "Rezept",
  "la reunión": "treffen",
  "la revista": "Magazin",
  "la ropa": "Tuch",
  "la ropa interior": "Unterwäsche",
  "la sal": "Salz",
  "la salida": "Abfahrt",
  "la salud": "Gesundheit",
  "la sangre": "Blut",
  "la semana": "Woche",
  "la silla": "Stuhl",
  "la sinergia": "Synergie",
  "la sinestesia": "Synästhesie",
  "la sociedad": "Gesellschaft",
  "la sopa": "Suppe",
  "la sorpresa": "Erstaunen",
  "la sostenibilidad": "Nachhaltigkeit",
  "la tablet": "Tablette",
  "la talla": "Größe",
  "la tarde": "Tag/Abend",
  "la tarea": "Aufgabe",
  "la tarjeta de crédito": "Kreditkarte",
  "la televisión / la tele": "Fernseher",
  "la temperatura": "Temperatur",
  "la teoría": "Theorie",
  "la tesis": "These",
  "la tienda": "Geschäft",
  "la toalla": "Handtuch",
  "la tormenta": "Sturm",
  "la tradición": "Tradition",
  "la trama": "Handlung",
  "la tristeza": "Traurigkeit",
  "la universidad": "Universität",
  "la vacuna": "Impfstoff",
  "la ventana": "Fenster",
  "la verdura": "Gemüse",
  "la vergüenza": "Scham",
  "la violencia": "Gewalt",
  "la vivienda": "Gehäuse",
  "la voz narrativa": "Stimme des Erzählers",
  "lana (méxico)": "Geld",
  "las botas": "Stiefel",
  "las elecciones": "Wahlen",
  "las noticias": "Nachricht",
  "las redes sociales": "soziale Netzwerke",
  "las vacaciones": "Urlaub",
  "las zapatillas": "Turnschuhe",
  "leer": "lesen",
  "lejos": "weit",
  "limpio / limpia": "sauber",
  "llamarse": "aufgerufen werden",
  "llover": "gehen (über Regen)",
  "los auriculares": "Kopfhörer",
  "los calcetines": "Socken",
  "los deberes": "Hausaufgaben",
  "los derechos humanos": "Menschenrechte",
  "los guantes": "Handschuhe",
  "los ojos": "Augen",
  "los pantalones": "Hose",
  "los vaqueros": "Jeans",
  "los zapatos": "Schuhe/Stiefel",
  "lunes": "Montag",
  "majo / maja (españa)": "süß/nett",
  "mañana": "Morgen",
  "mande (méxico)": "Was? / Entschuldigung?",
  "marrón": "braun",
  "martes": "Dienstag",
  "marzo": "Marsch",
  "más vale tarde que nunca": "besser spät als nie",
  "matizar": "klären / mildern",
  "matricularse": "Melden Sie sich an",
  "mayo": "Mai",
  "mayor": "Senior",
  "menor": "jünger",
  "menos cuarto": "Viertel für Viertel",
  "miércoles": "Mittwoch",
  "montar en bici": "Fahrrad fahren",
  "morado / morada": "violett",
  "muchas veces": "oft",
  "nadar": "schwimmen",
  "naranja": "orange",
  "necesitar": "brauchen",
  "negar": "leugnen",
  "negro / negra": "Schwarz",
  "nervioso": "nervös",
  "nevar": "gehen (über Schnee)",
  "no dar pie con bola": "geht nicht gut",
  "no dar puntada sin hilo": "mit Absicht handeln",
  "no obstante": "Trotzdem",
  "no tener ni idea": "habe keine Ahnung",
  "no ver tres en un burro": "kann nicht über die eigene Nase hinaussehen",
  "noviembre": "November",
  "nunca": "niemals",
  "objetar": "Geist",
  "objetivamente": "objektiv",
  "objetivo": "Objektiv",
  "octubre": "Oktober",
  "ordenador (españa)": "Computer",
  "orgulloso": "stolz",
  "oscuro / oscura": "dunkel",
  "pagar": "zahlen",
  "parecer": "erscheinen",
  "patinar": "Schlittschuh",
  "pensar": "denken",
  "perder": "verlieren",
  "perderse": "Hau ab",
  "perdone / disculpe": "Entschuldigung",
  "pibe / piba (argentina)": "Mann/Mädchen",
  "pintar": "malen",
  "plata (américa)": "Geld",
  "plateado / plateada": "Silber",
  "poder": "können",
  "poner en duda": "Frage",
  "ponerse las botas": "aufessen/reich werden",
  "por consiguiente": "somit",
  "practicar": "üben",
  "preguntar": "fragen",
  "preocupado": "betroffen",
  "prieto (méxico)": "dunkel/dunkelhäutig",
  "primero": "zuerst / zuerst",
  "probar": "anprobieren",
  "probarse": "anprobieren",
  "proceder a": "Start",
  "quedarse de brazos cruzados": "Arme verschränken/nichts tun",
  "querer": "wollen",
  "rebajado": "mit Rabatt",
  "rebatir": "Disput",
  "reconocer": "bekennen",
  "refutar": "widerlegen",
  "renunciar / dimitir": "aufhören",
  "resaltar": "hervorheben",
  "reservar": "Buch",
  "responder": "Antwort",
  "resultar pertinente": "angemessen sein",
  "rico / sabroso": "lecker",
  "rojo / roja": "Rot",
  "rosa": "Rosa",
  "sábado": "Samstag",
  "saber": "wissen",
  "sano / saludable": "gesund",
  "sano y salvo": "sicher und gesund",
  "sentir": "fühlen",
  "septiembre": "September",
  "ser": "sein (ständig)",
  "ser pan comido": "Halte es einfach",
  "siempre": "Stets",
  "sin techo": "obdachlos",
  "sorprendido": "überrascht",
  "subjetivo": "subjektiv",
  "subrayar": "betonen",
  "sucio / sucia": "schmutzig",
  "suponer": "annehmen",
  "suscitar": "Anruf",
  "suspender": "scheitern",
  "tarde": "spät",
  "temprano": "früh",
  "tener": "haben",
  "tener la sartén por el mango": "alles unter Kontrolle halten",
  "tener miedo": "besorgt",
  "terminar": "Ende",
  "tirar la casa por la ventana": "Gehen Sie im großen Stil",
  "tocar la guitarra": "Gitarre spielen",
  "todavía": "mehr",
  "tomar (américa)": "Transport nehmen/nehmen",
  "tomar el pelo": "necken",
  "tomar la temperatura": "Temperatur messen",
  "tos": "Husten",
  "trabajar": "arbeiten",
  "tranquilo": "ruhig",
  "trascender": "darüber hinausgehen",
  "tratar": "behandeln",
  "triste": "traurig",
  "turquesa": "Türkis",
  "vale (españa)": "ok/okay",
  "vender": "verkaufen",
  "venir": "kommen",
  "ver": "sehen",
  "verde": "Grün",
  "viajar": "reisen",
  "viernes": "Freitag",
  "violeta": "violett",
  "viral": "viral",
  "vivir": "live",
  "vos (argentina)": "du (argentinische Form)",
  "votar": "Abstimmung",
  "y cuarto": "Viertelstunde",
  "y media": "halbe (Stunde)",
  "ya": "bereits",
  "zumo (españa)": "Saft",
  },
};
