/** English UI titles for Spanish course vocabulary topics. */
export const SPANISH_TOPIC_TITLES_EN: Record<string, string> = {
  "a1-familia": "The Family",
  "a1-comida": "Food and Drink",
  "a1-casa": "The Home and Furniture",
  "a1-numeros-tiempo": "Numbers and Time",
  "a1-ciudad": "The City and Directions",
  "a1-colores": "Colors",
  "a1-cuerpo": "The Body and Health",
  "a1-verbos-basicos": "Basic Verbs",
  "a2-viajes": "Travel",
  "a2-trabajo": "Work and Professions",
  "a2-ropa": "Clothing",
  "a2-clima": "Weather and Nature",
  "a2-deportes": "Sports and Hobbies",
  "a2-compras": "Shopping",
  "a2-tecnologia": "Technology",
  "b1-emociones": "Emotions and Feelings",
  "b1-opiniones": "Opinions and Beliefs",
  "b1-educacion": "Education",
  "b1-sociedad": "Society and Politics",
  "b1-salud": "Health and Medicine",
  "b1-medios": "Media and Communication",
  "b2-argumentacion": "Argumentation and Debate",
  "b2-ciencia": "Science and Technology",
  "b2-problemas-sociales": "Social Issues",
  "b2-literatura": "Literature and Art",
  "b2-economia": "Economy and Finance",
  "c1-expresiones-idiomaticas": "Idiomatic Expressions",
  "c1-lenguaje-formal": "Formal Language",
  "c1-regionalismos": "Regional Spanish",
  "c1-conceptos-abstractos": "Abstract Concepts",
  "c1-literario": "Literary Vocabulary",
};
