// =====================================================================
// Pre-authored exercises per chapter (permanent adaptive bank)
// ---------------------------------------------------------------------
// Static exercises — zero AI generation. Adaptive Intelligence picks
// items; AI only explains mistakes after answers.
// Drafts may omit `id` — getChapterExercises assigns stable ids.
// Target depth: ~20 of each type per chapter (grow over time).
// =====================================================================

import type { StaticExercise } from "@/types";
import { withExerciseIds } from "@/lib/exercise-bank";
import { matchesChapterGrammar } from "@/lib/chapter-grammar-match";
import { CHAPTERS } from "@/config/chapters";
import { expandSpanishChapterBank } from "@/config/exercise-banks/spanish-expand";
import { CURRICULUM_CHAPTER_EXERCISES } from "@/config/chapter-exercises-curriculum";
import { SPANISH_CURATED_SUPPLEMENTS } from "@/config/exercise-seeds/spanish-curated-supplements";

/** Draft bank item before id assignment. */
export type ExerciseDraft = Omit<StaticExercise, "id"> & { id?: string };

export type { StaticExercise };

export const CHAPTER_EXERCISES: Record<string, ExerciseDraft[]> = {
  // ===== Chapter 1: ser/estar ======================================
  "chapter-1-despertar": [
    {
      type: "multiple_choice",
      question: "¿Cómo ___ tú? (descripción, no estado)",
      instruction: "ser (какой ты) или estar (как дела сейчас)?",
      options: ["eres", "estás", "soy", "es"],
      answer: "eres",
      explanation:
        "¿Cómo eres? — какой ты характером / внешне (ser). ¿Cómo estás? — как ты себя чувствуешь сейчас (estar). Для имени: ¿Cómo te llamas?",
    },
    {
      type: "fill_blank",
      question: "Yo ___ estudiante. (ser)",
      instruction: "Поставьте глагол ser в правильной форме",
      answer: "soy",
      acceptableAnswers: ["Soy"],
      explanation: "Yo → soy. Профессия — постоянная характеристика, поэтому ser.",
    },
    {
      type: "multiple_choice",
      question: "Mi hermano ___ cansado hoy.",
      instruction: "Выберите глагол для временного состояния",
      options: ["es", "está", "ser", "eres"],
      answer: "está",
      explanation: "«Устал сегодня» — временное состояние → estar: está cansado.",
    },
    {
      type: "translation",
      question: "Я из России.",
      instruction: "Переведите на испанский (используйте ser)",
      answer: "Soy de Rusia",
      acceptableAnswers: ["soy de Rusia", "Soy de rusia", "soy de rusia"],
      explanation: "Происхождение: ser + de + страна. Soy de Rusia.",
    },
    {
      type: "multiple_choice",
      question: "Nosotros ___ muy felices.",
      instruction: "Выберите форму estar для «мы»",
      options: ["somos", "estamos", "están", "son"],
      answer: "estamos",
      explanation: "Чувства/эмоции → estar. Nosotros → estamos.",
    },
    {
      type: "sentence_building",
      question: "¿Cómo / te / llamas?",
      options: ["¿Cómo", "te", "llamas?"],
      answer: "¿Cómo te llamas?",
      instruction: "Соберите вопрос «Как тебя зовут?»",
      explanation: "¿Cómo te llamas? — первое знакомство в испанском.",
    },
    {
      type: "sentence_building",
      question: "Me / llamo / Ana / y / soy / de / España",
      options: ["Me", "llamo", "Ana", "y", "soy", "de", "España"],
      answer: "Me llamo Ana y soy de España",
      instruction: "Соберите фразу представления",
      explanation: "Me llamo… + soy de… — имя и происхождение.",
    },
    {
      type: "fill_blank",
      question: "Mucho ___. (приятно познакомиться)",
      instruction: "Заполните устойчивую фразу",
      answer: "gusto",
      acceptableAnswers: ["Gusto"],
      explanation: "Mucho gusto — очень приятно (после знакомства).",
    },
  ],
  "chapter-2-primer-dialogo": [
    {
      type: "fill_blank",
      question: "Yo ___ (hablar) español todos los días.",
      instruction: "Спрягите глагол hablar в presente",
      answer: "hablo",
      acceptableAnswers: ["Hablo"],
      explanation: "Глагол -ar, yo → hablo. Регулярное спряжение.",
    },
    {
      type: "multiple_choice",
      question: "Ella ___ (comer) una manzana.",
      instruction: "Выберите форму comer для ella",
      options: ["como", "comes", "come", "comemos"],
      answer: "come",
      explanation: "Глагол -er, él/ella/usted → come.",
    },
    {
      type: "fill_blank",
      question: "Nosotros ___ (vivir) en Madrid.",
      instruction: "Поставьте vivir в правильную форму",
      answer: "vivimos",
      acceptableAnswers: ["Vivimos"],
      explanation: "Глагол -ir, nosotros → vivimos.",
    },
    {
      type: "translation",
      question: "Они работают в офисе.",
      instruction: "Переведите на испанский",
      answer: "Ellos trabajan en una oficina",
      acceptableAnswers: ["Trabajan en una oficina", "trabajan en una oficina", "Ellos trabajan en una oficina"],
      explanation: "Ellos → trabajan (-ar). trabajar = работать.",
    },
    {
      type: "multiple_choice",
      question: "¿Qué ___ (hacer) tú los fines de semana?",
      instruction: "Выберите неправильную форму hacer для tú",
      options: ["haces", "hago", "hace", "hacéis"],
      answer: "haces",
      explanation: "Tú → haces. Hacer неправильный: yo hago, tú haces, él hace.",
    },
    {
      type: "sentence_building",
      question: "Yo / hablo / español / todos / los / días",
      options: ["Yo", "hablo", "español", "todos", "los", "días"],
      answer: "Yo hablo español todos los días",
      instruction: "Соберите фразу о ежедневной практике",
      explanation: "Presente: yo hablo. todos los días = каждый день.",
    },
    {
      type: "sentence_building",
      question: "¿Qué / haces / los / fines / de / semana?",
      options: ["¿Qué", "haces", "los", "fines", "de", "semana?"],
      answer: "¿Qué haces los fines de semana?",
      instruction: "Соберите вопрос о выходных",
      explanation: "¿Qué haces…? — Что ты делаешь…? fines de semana = выходные.",
    },
  ],

  // ===== Chapter 3: artículos ======================================
  "chapter-3-biblioteca": [
    {
      type: "multiple_choice",
      question: "___ libro está en la mesa.",
      instruction: "Выберите артикль для известной конкретной вещи мужского рода (одна книга)",
      options: ["El", "La", "Un", "Una"],
      answer: "El",
      explanation: "Libro — мужской род, одна известная книга → el libro.",
    },
    {
      type: "fill_blank",
      question: "Compro ___ pan en la panadería.",
      instruction: "Хлеб как продукт часто без артикля (или el, если конкретный)",
      answer: "el",
      acceptableAnswers: ["el", "El", ""],
      explanation:
        "Compro pan — хлеб вообще (нулевой артикль). Compro el pan — этот / обычный хлеб. *Un pan* — одна буханка, не «хлеб как вещество».",
    },
    {
      type: "multiple_choice",
      question: "Vivo en ___ casa bonita.",
      instruction: "Выберите артикль для «какой-то» дома женского рода (один дом)",
      options: ["un", "una", "el", "la"],
      answer: "una",
      explanation: "Casa — женский род, один ещё не конкретный дом → una casa.",
    },
    {
      type: "translation",
      question: "Девочки играют в парке.",
      instruction: "Переведите: несколько девочек (женский род, много)",
      answer: "Las niñas juegan en el parque",
      acceptableAnswers: ["las niñas juegan en el parque", "Las niñas juegan en el parque"],
      explanation: "Las niñas — женский род, много; el parque — мужской род, один известный парк.",
    },
    {
      type: "multiple_choice",
      question: "Bebo ___ agua fría.",
      instruction: "Какой артикль перед agua? (не путать с abuela)",
      options: ["la", "el", "un", "las"],
      answer: "el",
      explanation:
        "Agua — женского рода, но одна вещь и ударение на первой a (Á-gua) → el agua. Во множественном: las aguas. Не путать: la abuela (ударение на -bue-).",
    },
    {
      type: "sentence_building",
      question: "Un / libro / interesante / en / la / mesa",
      options: ["Un", "libro", "interesante", "en", "la", "mesa"],
      answer: "Un libro interesante en la mesa",
      instruction: "Соберите фразу с артиклем un",
      explanation: "un libro — какая-то одна книга; en la mesa — на столе.",
    },
    {
      type: "sentence_building",
      question: "El / agua / está / fría",
      options: ["El", "agua", "está", "fría"],
      answer: "El agua está fría",
      instruction: "Соберите фразу с el agua",
      explanation: "el agua (не la) + estar для состояния: está fría.",
    },
  ],

  // ===== Chapter 4: números/tiempo =================================
  "chapter-4-numeros-tiempo": [
    {
      type: "fill_blank",
      question: "Tengo ___ años. (25)",
      instruction: "Напишите число прописью",
      answer: "veinticinco",
      acceptableAnswers: ["Veinticinco"],
      explanation: "25 → veinticinco. Числа 21-29 пишутся слитно.",
    },
    {
      type: "multiple_choice",
      question: "¿Qué día es después del lunes?",
      instruction: "Какой день идёт после понедельника?",
      options: ["martes", "miércoles", "domingo", "viernes"],
      answer: "martes",
      explanation: "Понедельник → вторник: lunes → martes.",
    },
    {
      type: "translation",
      question: "Сейчас три часа дня.",
      instruction: "Переведите время на испанский",
      answer: "Son las tres de la tarde",
      acceptableAnswers: ["son las tres", "Son las tres", "son las tres de la tarde"],
      explanation: "С 2:00 → son las + часы. После полудня → de la tarde.",
    },
    {
      type: "multiple_choice",
      question: "El ___ es el primer día de la semana.",
      instruction: "Какой день первый?",
      options: ["lunes", "domingo", "sábado", "viernes"],
      answer: "lunes",
      explanation: "В испанском календаре неделя начинается с lunes (понедельник).",
    },
    {
      type: "fill_blank",
      question: "Hay ___ días en una semana. (7)",
      instruction: "Напишите число прописью",
      answer: "siete",
      acceptableAnswers: ["Siete"],
      explanation: "7 → siete.",
    },
    {
      type: "sentence_building",
      question: "Son / las / tres / de / la / tarde",
      options: ["Son", "las", "tres", "de", "la", "tarde"],
      answer: "Son las tres de la tarde",
      instruction: "Соберите фразу о времени",
      explanation: "Son las + часы; de la tarde = дня (после полудня).",
    },
  ],

  // ===== Chapter 5: tener expressions ==============================
  "chapter-5-mercado": [
    {
      type: "fill_blank",
      question: "Yo ___ hambre.",
      instruction: "Forma: tener · presente",
      answer: "Tengo",
      acceptableAnswers: ["tengo"],
      explanation: "Tener hambre = быть голодным.",
    },
    {
      type: "multiple_choice",
      question: "¿De qué color es la hierba?",
      instruction: "Выберите цвет травы",
      options: ["verde", "rojo", "azul", "amarillo"],
      answer: "verde",
      explanation: "La hierba es verde (трава зелёная).",
    },
    {
      type: "fill_blank",
      question: "Tienes ___ (suerte) de viajar.",
      instruction: "Какое выражение с tener подходит?",
      answer: "suerte",
      acceptableAnswers: ["Suerte"],
      explanation: "Tener suerte = быть удачливым.",
    },
    {
      type: "translation",
      question: "Мне холодно.",
      instruction: "Используйте выражение с tener",
      answer: "Tengo frío",
      acceptableAnswers: ["tengo frío", "Tengo frio"],
      explanation: "Tener frío = мёрзнуть. Tener + существительное для состояния.",
    },
    {
      type: "multiple_choice",
      question: "¿Cuánto cuesta este libro? — Cuesta ___ euros. (15)",
      instruction: "Выберите правильное число",
      options: ["quince", "cinco", "cincuenta", "diez"],
      answer: "quince",
      explanation: "15 → quince.",
    },
  ],

  // ===== Chapter 6: gustar =========================================
  "chapter-6-cuerpo": [
    {
      type: "multiple_choice",
      question: "Me ___ el café.",
      instruction: "Выберите форму gustar для ед.ч.",
      options: ["gusta", "gustan", "gusto", "gustas"],
      answer: "gusta",
      explanation: "El café (ед.ч.) → gusta. Me gusta el café = мне нравится кофе.",
    },
    {
      type: "fill_blank",
      question: "Me ___ los libros. (gustar, мн.ч.)",
      instruction: "Поставьте gustar для множественного числа",
      answer: "gustan",
      acceptableAnswers: ["Gustan"],
      explanation: "Los libros (мн.ч.) → gustan. Me gustan los libros.",
    },
    {
      type: "multiple_choice",
      question: "Cuando estoy enfermo, voy al ___.",
      instruction: "Куда идут когда болеют?",
      options: ["médico", "profesor", "parque", "banco"],
      answer: "médico",
      explanation: "El médico = врач. Voy al médico cuando estoy enfermo.",
    },
    {
      type: "translation",
      question: "Мне нравится испанский.",
      instruction: "Используйте gustar",
      answer: "Me gusta el español",
      acceptableAnswers: ["me gusta el español"],
      explanation: "El español (ед.ч.) → me gusta.",
    },
    {
      type: "fill_blank",
      question: "Me duele la ___ (голова).",
      instruction: "Какое слово означает «голова»?",
      answer: "cabeza",
      acceptableAnswers: ["Cabeza"],
      explanation: "La cabeza = голова. Me duele la cabeza = у меня болит голова.",
    },
    {
      type: "sentence_building",
      question: "Me / gusta / el / café / pero / no / me / gusta / el / té",
      options: ["Me", "gusta", "el", "café", "pero", "no", "me", "gusta", "el", "té"],
      answer: "Me gusta el café pero no me gusta el té",
      instruction: "Соберите фразу с gustar",
      explanation: "Me gusta + ед.ч.; me gustan + мн.ч. Pero = но.",
    },
  ],

  // ===== Chapter 18: género y número ==============================
  "chapter-18-genero-numero": [
    {
      type: "multiple_choice",
      question: "___ casa es grande. (артикль)",
      instruction: "Выберите артикль для casa",
      options: ["La", "El", "Los", "Unos"],
      answer: "La",
      explanation: "Casa — женский род → la casa.",
    },
    {
      type: "fill_blank",
      question: "Los ___ (libro, много книг)",
      instruction: "Поставьте существительное во множественное число",
      answer: "libros",
      acceptableAnswers: ["Libros"],
      explanation: "libro → libros (−o → −os).",
    },
    {
      type: "error_correction",
      question: "El mesa es roja.",
      instruction: "Исправьте род артикля",
      answer: "La mesa es roja.",
      acceptableAnswers: ["la mesa es roja"],
      explanation: "Mesa — женский род → la mesa.",
    },
    {
      type: "translation",
      question: "Белые дома",
      instruction: "Согласуйте род и число",
      answer: "Las casas blancas",
      acceptableAnswers: ["las casas blancas"],
      explanation: "casa (ж.р. мн.) → las casas blancas.",
    },
    {
      type: "sentence_building",
      question: "Las / casas / son / blancas",
      options: ["Las", "casas", "son", "blancas"],
      answer: "Las casas son blancas",
      instruction: "Соберите фразу о множественном числе",
      explanation: "casas (ж.р., мн.) → las casas son blancas.",
    },
  ],

  // ===== Chapter 19: preposiciones de lugar =======================
  "chapter-19-preposiciones": [
    {
      type: "multiple_choice",
      question: "El libro está ___ la mesa.",
      instruction: "Выберите предлог места",
      options: ["en", "a", "de", "por"],
      answer: "en",
      explanation: "en = в/на (местонахождение).",
    },
    {
      type: "fill_blank",
      question: "Voy ___ Madrid.",
      instruction: "Предлог направления",
      answer: "a",
      acceptableAnswers: ["A"],
      explanation: "a + город = направление: voy a Madrid.",
    },
    {
      type: "multiple_choice",
      question: "El gato está ___ el sofá.",
      instruction: "«под»",
      options: ["debajo de", "encima de", "delante de", "entre"],
      answer: "debajo de",
      explanation: "debajo de = под.",
    },
    {
      type: "translation",
      question: "Ключи на столе.",
      instruction: "Используйте en",
      answer: "Las llaves están en la mesa",
      acceptableAnswers: ["las llaves están en la mesa", "Las llaves estan en la mesa"],
      explanation: "estar en = находиться на/в.",
    },
  ],

  // ===== Chapter 20: preguntas ====================================
  "chapter-20-preguntas": [
    {
      type: "multiple_choice",
      question: "___ te llamas?",
      instruction: "Как тебя зовут?",
      options: ["Cómo", "Qué", "Quién", "Dónde"],
      answer: "Cómo",
      explanation: "¿Cómo te llamas? = Как тебя зовут?",
    },
    {
      type: "fill_blank",
      question: "¿___ vives? (где)",
      instruction: "Вопросительное слово",
      answer: "Dónde",
      acceptableAnswers: ["dónde", "Donde", "donde"],
      explanation: "¿Dónde? = где?",
    },
    {
      type: "multiple_choice",
      question: "¿___ es tu profesor?",
      instruction: "Кто?",
      options: ["Quién", "Qué", "Cuándo", "Cuál"],
      answer: "Quién",
      explanation: "¿Quién? = кто?",
    },
    {
      type: "translation",
      question: "Почему ты изучаешь испанский?",
      instruction: "Используйте ¿por qué?",
      answer: "¿Por qué estudias español?",
      acceptableAnswers: ["por qué estudias español", "¿Por que estudias español?"],
      explanation: "¿Por qué? = почему?",
    },
    {
      type: "sentence_building",
      question: "¿Dónde / vives / tú?",
      options: ["¿Dónde", "vives", "tú?"],
      answer: "¿Dónde vives tú?",
      instruction: "Соберите вопрос «Где ты живёшь?»",
      explanation: "¿Dónde vives? — вопрос о месте жительства.",
    },
    {
      type: "sentence_building",
      question: "¿Cuántos / años / tienes?",
      options: ["¿Cuántos", "años", "tienes?"],
      answer: "¿Cuántos años tienes?",
      instruction: "Соберите вопрос о возрасте",
      explanation: "¿Cuántos años tienes? = Сколько тебе лет?",
    },
  ],

  // ===== Chapter 21: comparativos =================================
  "chapter-21-comparativos": [
    {
      type: "multiple_choice",
      question: "Madrid es ___ grande ___ Toledo.",
      instruction: "Сравнение «больше чем»",
      options: ["más / que", "más / de", "tan / que", "muy / que"],
      answer: "más / que",
      explanation: "más + прилагательное + que.",
    },
    {
      type: "fill_blank",
      question: "Ana es ___ alta ___ María. (такая же)",
      instruction: "Равная степень",
      answer: "tan",
      acceptableAnswers: ["Tan"],
      explanation: "tan + adj + como = такая же… как.",
    },
    {
      type: "translation",
      question: "Это самый большой город.",
      instruction: "Превосходная степень",
      answer: "Es la ciudad más grande",
      acceptableAnswers: ["es la ciudad más grande", "Es el ciudad más grande"],
      explanation: "el/la más + adj.",
    },
    {
      type: "error_correction",
      question: "Juan es más alto de Pedro.",
      instruction: "Исправьте предлог сравнения",
      answer: "Juan es más alto que Pedro.",
      acceptableAnswers: ["juan es más alto que pedro"],
      explanation: "Сравнение с que, не de (кроме чисел).",
    },
    {
      type: "sentence_building",
      question: "Madrid / es / más / grande / que / Toledo",
      options: ["Madrid", "es", "más", "grande", "que", "Toledo"],
      answer: "Madrid es más grande que Toledo",
      instruction: "Соберите сравнительную фразу",
      explanation: "más + прилагательное + que.",
    },
  ],

  // ===== Chapter 22: futuro simple ================================
  "chapter-22-futuro": [
    {
      type: "fill_blank",
      question: "Mañana ___ (hablar) con ella. (yo)",
      instruction: "Futuro simple",
      answer: "hablaré",
      acceptableAnswers: ["Hablare", "hablaré"],
      explanation: "yo → infinitivo + é: hablaré.",
    },
    {
      type: "multiple_choice",
      question: "Ellos ___ mañana.",
      instruction: "venir в будущем",
      options: ["vendrán", "vienen", "vinieron", "venían"],
      answer: "vendrán",
      explanation: "venir → vendrán (неправильный корень).",
    },
    {
      type: "translation",
      question: "Мы поедем в Испанию.",
      instruction: "Futuro de ir",
      answer: "Iremos a España",
      acceptableAnswers: ["iremos a españa", "Nosotros iremos a España"],
      explanation: "ir → iremos.",
    },
    {
      type: "multiple_choice",
      question: "¿Qué ___ tú el próximo año?",
      instruction: "hacer в будущем",
      options: ["harás", "haces", "hiciste", "hacías"],
      answer: "harás",
      explanation: "hacer → harás.",
    },
    {
      type: "sentence_building",
      question: "Mañana / hablaré / con / mi / profesor",
      options: ["Mañana", "hablaré", "con", "mi", "profesor"],
      answer: "Mañana hablaré con mi profesor",
      instruction: "Соберите фразу в futuro simple",
      explanation: "Mañana + futuro: hablaré.",
    },
  ],

  // ===== Chapter 7: pretérito perfecto ============================
  "chapter-7-pasado-perfecto": [
    {
      type: "fill_blank",
      question: "Hoy ___ (comer) pizza. (yo)",
      instruction: "Поставьте в pretérito perfecto",
      answer: "he comido",
      acceptableAnswers: ["He comido"],
      explanation: "haber (he) + comido. Pretérito perfecto для сегодняшнего действия.",
    },
    {
      type: "multiple_choice",
      question: "¿Has ___ en España? (estar)",
      instruction: "Выберите participio для estar",
      options: ["estado", "estando", "esté", "estuvo"],
      answer: "estado",
      explanation: "Participio estar → estado. ¿Has estado en España?",
    },
    {
      type: "fill_blank",
      question: "Ella ___ (escribir) un correo.",
      instruction: "Поставьте escribir в perfecto",
      answer: "ha escrito",
      acceptableAnswers: ["Ha escrito"],
      explanation: "haber (ha) + escrito. Escribir → escrito (неправильный).",
    },
    {
      type: "translation",
      question: "Я уже поел.",
      instruction: "Используйте pretérito perfecto + ya",
      answer: "Ya he comido",
      acceptableAnswers: ["ya he comido", "He comido ya"],
      explanation: "Ya + haber + participio. Ya he comido.",
    },
    {
      type: "sentence_building",
      question: "Hoy / he / comido / en / un / restaurante",
      options: ["Hoy", "he", "comido", "en", "un", "restaurante"],
      answer: "Hoy he comido en un restaurante",
      instruction: "Соберите фразу в pretérito perfecto",
      explanation: "he + participio: hoy he comido = сегодня я поел.",
    },
    {
      type: "multiple_choice",
      question: "Hoy hemos ___ mucho.",
      instruction: "Выберите participio для trabajar",
      options: ["trabajado", "trabajando", "trabajo", "trabajé"],
      answer: "trabajado",
      explanation: "Trabajar → trabajado. Hemos trabajado = мы поработали.",
    },
  ],
  "chapter-8-pasado-indefinido": [
    {
      type: "fill_blank",
      question: "Ayer ___ (ir) al cine. (yo)",
      instruction: "Поставьте ir в indefinido",
      answer: "fui",
      acceptableAnswers: ["Fui"],
      explanation: "Ir → fui (indefinido, yo). Полностью неправильный.",
    },
    {
      type: "multiple_choice",
      question: "El año pasado ___ en Barcelona. (vivir, yo)",
      instruction: "Выберите форму vivir в indefinido",
      options: ["viví", "vivía", "he vivido", "vivo"],
      answer: "viví",
      explanation: "Vivir в indefinido, yo → viví. «В прошлом году» = конкретный момент.",
    },
    {
      type: "translation",
      question: "Вчера я купил книгу.",
      instruction: "Используйте pretérito indefinido",
      answer: "Ayer compré un libro",
      acceptableAnswers: ["ayer compré un libro", "Compré un libro ayer"],
      explanation: "Comprar → compré (yo, indefinido). Ayer = маркер indefinido.",
    },
    {
      type: "fill_blank",
      question: "¿___ al partido ayer?",
      instruction: "Поставьте вопрос с ir в indefinido",
      answer: "Fuiste",
      acceptableAnswers: ["fuiste"],
      explanation: "Ir → fuiste (tú, indefinido).",
    },
    {
      type: "multiple_choice",
      question: "Hace dos años ellos ___ a Japón.",
      instruction: "Выберите форму",
      options: ["fueron", "iban", "van", "han ido"],
      answer: "fueron",
      explanation: "«Два года назад» = конкретный момент → indefinido: fueron.",
    },
    {
      type: "sentence_building",
      question: "Ayer / compré / un / libro / interesante",
      options: ["Ayer", "compré", "un", "libro", "interesante"],
      answer: "Ayer compré un libro interesante",
      instruction: "Соберите фразу о вчерашней покупке",
      explanation: "Ayer + pretérito indefinido: compré.",
    },
  ],

  // ===== Chapter 9: imperfecto =====================================
  "chapter-9-imperfecto": [
    {
      type: "fill_blank",
      question: "Cuando era niño, ___ (jugar) al fútbol.",
      instruction: "Поставьте jugar в imperfecto",
      answer: "jugaba",
      acceptableAnswers: ["Jugaba"],
      explanation: "Привычное действие в прошлом → imperfecto: jugaba.",
    },
    {
      type: "multiple_choice",
      question: "Hacía sol y los pájaros ___.",
      instruction: "Выберите описание фона в прошлом",
      options: ["cantaban", "cantaron", "han cantado", "cantan"],
      answer: "cantaban",
      explanation: "Описание фона → imperfecto: cantaban.",
    },
    {
      type: "translation",
      question: "Когда я был маленьким, я жил в Москве.",
      instruction: "Используйте imperfecto для описания",
      answer: "Cuando era pequeño, vivía en Moscú",
      acceptableAnswers: ["cuando era pequeño vivía en Moscú", "Cuando era niño vivía en Moscú"],
      explanation: "Описание прошлого → era (ser, imperfecto) + vivía (vivir, imperfecto).",
    },
    {
      type: "fill_blank",
      question: "Todos los días ___ (comer) a las dos.",
      instruction: "Привычка в прошлом — какое время?",
      answer: "comía",
      acceptableAnswers: ["Comía", "comíamos"],
      explanation: "Привычное действие в прошлом → imperfecto: comía.",
    },
    {
      type: "multiple_choice",
      question: "¿Cómo ___ tu abuela?",
      instruction: "Описание внешности в прошлом",
      options: ["era", "fue", "es", "ha sido"],
      answer: "era",
      explanation: "Описание характеристики в прошлом → imperfecto: era.",
    },
    {
      type: "sentence_building",
      question: "Cuando / era / niño / jugaba / al / fútbol",
      options: ["Cuando", "era", "niño", "jugaba", "al", "fútbol"],
      answer: "Cuando era niño jugaba al fútbol",
      instruction: "Соберите фразу о детстве",
      explanation: "Cuando era niño + imperfecto jugaba — привычка в прошлом.",
    },
  ],

  // ===== Chapter 10: por/para ======================================
  "chapter-10-por-para": [
    {
      type: "multiple_choice",
      question: "Estudio español ___ viajar.",
      instruction: "Выберите предлог цели",
      options: ["para", "por", "en", "de"],
      answer: "para",
      explanation: "Цель → para. Estudio para viajar = учусь чтобы путешествовать.",
    },
    {
      type: "fill_blank",
      question: "Caminamos ___ el parque.",
      instruction: "Какой предлог места/пути?",
      answer: "por",
      acceptableAnswers: ["Por"],
      explanation: "Движение через место → por. Por el parque = по парку.",
    },
    {
      type: "translation",
      question: "Это подарок для тебя.",
      instruction: "Используйте para",
      answer: "Es un regalo para ti",
      acceptableAnswers: ["es un regalo para ti"],
      explanation: "Получатель → para. Regalo para ti = подарок для тебя.",
    },
    {
      type: "multiple_choice",
      question: "Lo compré ___ 10 euros.",
      instruction: "Выберите предлог цены/обмена",
      options: ["por", "para", "con", "de"],
      answer: "por",
      explanation: "Обмен/цена → por. Por 10 euros = за 10 евро.",
    },
    {
      type: "fill_blank",
      question: "___ favor, ayúdame.",
      instruction: "Какое устойчивое выражение?",
      answer: "Por",
      acceptableAnswers: ["por"],
      explanation: "Por favor = пожалуйста. Устойчивое выражение.",
    },
    {
      type: "sentence_building",
      question: "Estudio / español / para / viajar",
      options: ["Estudio", "español", "para", "viajar"],
      answer: "Estudio español para viajar",
      instruction: "Соберите фразу с para (цель)",
      explanation: "para + infinitivo = чтобы / для того чтобы.",
    },
  ],

  // ===== Chapter 11: subjuntivo presente ==========================
  "chapter-11-subjuntivo": [
    {
      type: "fill_blank",
      question: "Quiero que tú ___ (hablar).",
      instruction: "Поставьте hablar в subjuntivo",
      answer: "hables",
      acceptableAnswers: ["Hables"],
      explanation: "Después de «quiero que» → subjuntivo. Hablar → hables (tú).",
    },
    {
      type: "multiple_choice",
      question: "Espero que él ___ pronto.",
      instruction: "Выберите subjuntivo для venir",
      options: ["venga", "viene", "vendrá", "vino"],
      answer: "venga",
      explanation: "После esperar que → subjuntivo. Venir → venga.",
    },
    {
      type: "fill_blank",
      question: "Dudo que ___ (ser) verdad.",
      instruction: "Сомнение → какое наклонение?",
      answer: "sea",
      acceptableAnswers: ["Sea"],
      explanation: "Dudar que → subjuntivo. Ser → sea.",
    },
    {
      type: "translation",
      question: "Я хочу, чтобы ты пришёл.",
      instruction: "Используйте subjuntivo",
      answer: "Quiero que vengas",
      acceptableAnswers: ["quiero que vengas"],
      explanation: "Querer que + subjuntivo. Venir → vengas (tú).",
    },
    {
      type: "multiple_choice",
      question: "Ojalá ___ buen tiempo mañana.",
      instruction: "Выберите форму",
      options: ["haga", "hace", "hará", "hizo"],
      answer: "haga",
      explanation: "Ojalá → siempre subjuntivo. Hacer → haga.",
    },
  ],

  // ===== Chapter 12: imperativo ====================================
  "chapter-12-imperativo": [
    {
      type: "fill_blank",
      question: "¡___ la fruta!",
      instruction: "Поставьте в утвердительное повелительное (tú)",
      answer: "Come",
      acceptableAnswers: ["come"],
      explanation: "Tú afirmativo: comer → come.",
    },
    {
      type: "multiple_choice",
      question: "¡No ___ eso!",
      instruction: "Выберите отрицательное повелительное",
      options: ["digas", "di", "dices", "dijiste"],
      answer: "digas",
      explanation: "Отрицательное → subjuntivo: decir → no digas.",
    },
    {
      type: "translation",
      question: "Скажи мне правду!",
      instruction: "Используйте утвердительное повелительное",
      answer: "¡Dime la verdad!",
      acceptableAnswers: ["dime la verdad", "¡Dime la verdad!"],
      explanation: "Decir → di + me = dime. Di + me = dime.",
    },
    {
      type: "fill_blank",
      question: "¡___ los deberes!",
      instruction: "Утвердительное повелительное от hacer",
      answer: "Haz",
      acceptableAnswers: ["haz"],
      explanation: "Hacer → haz (tú, imperativo). Неправильная форма.",
    },
    {
      type: "multiple_choice",
      question: "¡___ usted, por favor! (sentarse)",
      instruction: "Вежливое повелительное для usted",
      options: ["siéntese", "siéntate", "sienta", "sentarse"],
      answer: "siéntese",
      explanation: "Usted → subjuntivo: sentarse → siéntese.",
    },
  ],

  // ===== Chapter 13: condicional ===================================
  "chapter-13-condicional": [
    {
      type: "fill_blank",
      question: "Me ___ (gustar) un café. (вежливо)",
      instruction: "Поставьте в condicional для вежливости",
      answer: "gustaría",
      acceptableAnswers: ["Gustaría"],
      explanation: "Condicional для вежливости: gustar → gustaría.",
    },
    {
      type: "multiple_choice",
      question: "Si tuviera dinero, ___ un coche.",
      instruction: "Выберите condicional",
      options: ["compraría", "compro", "compré", "compra"],
      answer: "compraría",
      explanation: "Si + subjuntivo + condicional: compraría.",
    },
    {
      type: "translation",
      question: "Я бы хотел путешествовать.",
      instruction: "Используйте condicional",
      answer: "Me gustaría viajar",
      acceptableAnswers: ["me gustaría viajar"],
      explanation: "Gustar → gustaría. Me gustaría = мне бы хотелось.",
    },
    {
      type: "fill_blank",
      question: "¿Podría ___ (ayudar)me?",
      instruction: "Вежливая просьба через condicional",
      answer: "ayudar",
      acceptableAnswers: ["ayudar"],
      explanation: "Podría + infinitivo. ¿Podría ayudarme? = Не могли бы вы помочь?",
    },
    {
      type: "multiple_choice",
      question: "Yo que tú, lo ___ diferente.",
      instruction: "Совет — какое наклонение?",
      options: ["haría", "hago", "hice", "haga"],
      answer: "haría",
      explanation: "«На твоём месте» → condicional: haría.",
    },
  ],

  // ===== Chapters 14-17 (advanced) — simplified ====================
  "chapter-14-estilo-indirecto": [
    {
      type: "multiple_choice",
      question: "Él dijo que ___ cansado.",
      instruction: "Косвенная речь — выберите время",
      options: ["estaba", "está", "estará", "esté"],
      answer: "estaba",
      explanation: "После dijo (прошедшее) presente → imperfecto: está → estaba.",
    },
    {
      type: "fill_blank",
      question: "María dice que ___ (venir) mañana.",
      instruction: "Косвенная речь после presente",
      answer: "vendrá",
      acceptableAnswers: ["vendrá", "viene"],
      explanation: "После dice (presente) время не меняется: viene / vendrá.",
    },
    {
      type: "translation",
      question: "Он сказал, что придёт завтра.",
      instruction: "Косвенная речь в прошедшем",
      answer: "Dijo que vendría mañana",
      acceptableAnswers: ["dijo que vendría mañana", "Dijo que iba a venir mañana"],
      explanation: "Futuro → condicional в косвенной речи: vendrá → vendría.",
    },
    {
      type: "fill_blank",
      question: "Me preguntó ___ estaba cansado.",
      instruction: "Какое слово для косвенного вопроса?",
      answer: "si",
      acceptableAnswers: ["Si"],
      explanation: "Косвенный вопрос «ли» → si. Me preguntó si... = Он спросил, ... ли.",
    },
    {
      type: "multiple_choice",
      question: "Dijo: \"Hoy llego tarde.\" → Dijo que ___ tarde.",
      instruction: "Преобразуйте в косвенную речь",
      options: ["llegaba", "llega", "llegará", "llegue"],
      answer: "llegaba",
      explanation: "Presente → imperfecto в косвенной (после прошедшего): llego → llegaba.",
    },
  ],

  "chapter-15-voz-pasiva": [
    {
      type: "multiple_choice",
      question: "El libro ___ escrito por Cervantes.",
      instruction: "Выберите форму пассива",
      options: ["fue", "es", "está", "fue siendo"],
      answer: "fue",
      explanation: "Ser + participio: fue escrito. Прошедшее → fue.",
    },
    {
      type: "fill_blank",
      question: "___ habla español aquí. (пассив с se)",
      instruction: "Какая конструкция для «здесь говорят»?",
      answer: "Se",
      acceptableAnswers: ["se"],
      explanation: "Pasiva refleja: se habla = «говорят» (без указания кем).",
    },
    {
      type: "translation",
      question: "Письмо отправлено.",
      instruction: "Используйте ser + participio",
      answer: "La carta es enviada",
      acceptableAnswers: ["la carta es enviada", "La carta ha sido enviada"],
      explanation: "Ser + participio: es enviada.",
    },
    {
      type: "multiple_choice",
      question: "Se ___ coches en esta fábrica.",
      instruction: "Выберите форму pasiva refleja",
      options: ["venden", "vende", "vendieron", "vendían"],
      answer: "venden",
      explanation: "Pasiva refleje с мн.ч.: se venden coches = «продаются машины».",
    },
    {
      type: "fill_blank",
      question: "El museo ___ (construir) en 1990.",
      instruction: "Пассив в прошедшем",
      answer: "fue construido",
      acceptableAnswers: ["Fue construido"],
      explanation: "Ser (fue) + participio (construido).",
    },
  ],

  "chapter-16-perifrasis": [
    {
      type: "fill_blank",
      question: "Voy ___ (estudiar) español.",
      instruction: "Какая перифраза для ближайшего будущего?",
      answer: "a estudiar",
      acceptableAnswers: ["a estudiar"],
      explanation: "Ir a + infinitivo = собираться сделать. Voy a estudiar.",
    },
    {
      type: "multiple_choice",
      question: "Tengo que ___ más.",
      instruction: "Какая перифраза долженствования?",
      options: ["estudiar", "estudiando", "estudié", "estudio"],
      answer: "estudiar",
      explanation: "Tener que + infinitivo = должен. Tengo que estudiar.",
    },
    {
      type: "translation",
      question: "Я только что пришёл.",
      instruction: "Используйте acabar de",
      answer: "Acabo de llegar",
      acceptableAnswers: ["acabo de llegar"],
      explanation: "Acabar de + infinitivo = только что. Acabo de llegar.",
    },
    {
      type: "fill_blank",
      question: "Sigo ___ (aprender) cada día.",
      instruction: "Перифраза продолжения",
      answer: "aprendiendo",
      acceptableAnswers: ["Aprendiendo"],
      explanation: "Seguir + gerundio = продолжать. Sigo aprendiendo.",
    },
    {
      type: "multiple_choice",
      question: "Llevo ___ dos horas.",
      instruction: "Выберите форму для длительности",
      options: ["estudiando", "estudiar", "estudié", "estudio"],
      answer: "estudiando",
      explanation: "Llevar + gerundio = длительность. Llevo estudiando dos horas.",
    },
    {
      type: "sentence_building",
      question: "Acabo / de / terminar / la / redacción",
      instruction: "Составьте перифразу acabar de",
      options: ["Acabo", "de", "terminar", "la", "redacción"],
      answer: "Acabo de terminar la redacción",
      explanation: "Acabar de + infinitivo = только что закончил.",
      grammarTopic: "c1-perifrasis-verbales",
    },
    {
      type: "sentence_building",
      question: "Llevo / tres / horas / estudiando / sin / parar",
      instruction: "Составьте перифразу llevar + gerundio",
      options: ["Llevo", "tres", "horas", "estudiando", "sin", "parar"],
      answer: "Llevo tres horas estudiando sin parar",
      explanation: "Llevar + gerundio — длительность действия.",
      grammarTopic: "c1-perifrasis-verbales",
    },
    {
      type: "sentence_building",
      question: "Voy / a / empezar / a / leer / ahora",
      instruction: "Составьте ir a + infinitivo",
      options: ["Voy", "a", "empezar", "a", "leer", "ahora"],
      answer: "Voy a empezar a leer ahora",
      explanation: "Ir a + infinitivo — ближайшее будущее.",
      grammarTopic: "c1-perifrasis-verbales",
    },
    {
      type: "sentence_building",
      question: "Debe / de / haber / un / error / en / el / texto",
      instruction: "Составьте перифразу deber de (догадка)",
      options: ["Debe", "de", "haber", "un", "error", "en", "el", "texto"],
      answer: "Debe de haber un error en el texto",
      explanation: "Deber de — вероятность, догадка.",
      grammarTopic: "c1-perifrasis-verbales",
    },
    {
      type: "sentence_building",
      question: "Sigo / pensando / en / la / misma / idea",
      instruction: "Составьте seguir + gerundio",
      options: ["Sigo", "pensando", "en", "la", "misma", "idea"],
      answer: "Sigo pensando en la misma idea",
      explanation: "Seguir + gerundio — продолжать делать.",
      grammarTopic: "c1-perifrasis-verbales",
    },
  ],

  "chapter-17-dele": [
    {
      type: "multiple_choice",
      question: "Si ___ estudiado, habría aprobado.",
      instruction: "Выберите pluscuamperfecto subjuntivo",
      options: ["hubiera", "he", "había", "habría"],
      answer: "hubiera",
      explanation: "Si + pluscuamperfecto subjuntivo + condicional compuesto: hubiera.",
    },
    {
      type: "fill_blank",
      question: "Por mucho que ___, no lo conseguiré. (intentar)",
      instruction: "Concessive clause — какое наклонение?",
      answer: "intente",
      acceptableAnswers: ["Intente"],
      explanation: "Por mucho que + subjuntivo: intente (гипотетично).",
    },
    {
      type: "translation",
      question: "Как бы то ни было, я поеду.",
      instruction: "Используйте subjuntivo",
      answer: "Sea como sea, iré",
      acceptableAnswers: ["sea como sea iré", "Sea como sea, voy a ir"],
      explanation: "Sea como sea = как бы то ни было. Устойчивое выражение с subjuntivo.",
    },
    {
      type: "fill_blank",
      question: "Estoy cansado de ___ (esperar).",
      instruction: "Перифраза состояния",
      answer: "esperar",
      acceptableAnswers: ["esperar"],
      explanation: "Estar cansado de + infinitivo = устать от чего-то.",
    },
    {
      type: "multiple_choice",
      question: "No creo que ___ razón.",
      instruction: "Отрицание мнения — какое наклонение?",
      options: ["tenga", "tiene", "tendrá", "tenía"],
      answer: "tenga",
      explanation: "No creer que → subjuntivo: tenga.",
    },
    {
      type: "sentence_building",
      question: "Sea / como / sea / iré",
      instruction: "Составьте устойчивое выражение",
      options: ["Sea", "como", "sea", "iré"],
      answer: "Sea como sea iré",
      acceptableAnswers: ["Sea como sea, iré", "sea como sea ire"],
      explanation: "Sea como sea — «как бы то ни было».",
      grammarTopic: "c1-matices-estilisticos",
    },
    {
      type: "sentence_building",
      question: "Por / mucho / que / intente / no / lo / conseguiré",
      instruction: "Составьте уступительную конструкцию",
      options: ["Por", "mucho", "que", "intente", "no", "lo", "conseguiré"],
      answer: "Por mucho que intente no lo conseguiré",
      acceptableAnswers: [
        "Por mucho que intente, no lo conseguiré",
        "por mucho que intente no lo conseguire",
      ],
      explanation: "Por mucho que + subjuntivo — «сколько бы ни…».",
      grammarTopic: "c1-matices-estilisticos",
    },
    {
      type: "sentence_building",
      question: "Le / ruego / que / me / envíe / la / documentación",
      instruction: "Составьте формальную просьбу (usted)",
      options: ["Le", "ruego", "que", "me", "envíe", "la", "documentación"],
      answer: "Le ruego que me envíe la documentación",
      explanation: "Le ruego que + subjuntivo — очень вежливая просьба.",
      grammarTopic: "c1-matices-estilisticos",
    },
    {
      type: "sentence_building",
      question: "¿Podría / indicarme / dónde / está / la / sala?",
      instruction: "Составьте вежливый вопрос с condicional",
      options: ["¿Podría", "indicarme", "dónde", "está", "la", "sala?"],
      answer: "¿Podría indicarme dónde está la sala?",
      explanation: "¿Podría…? — вежливость через condicional.",
      grammarTopic: "c1-matices-estilisticos",
    },
    {
      type: "sentence_building",
      question: "No / obstante / debemos / continuar / con / el / plan",
      instruction: "Составьте формальный связующий оборот",
      options: ["No", "obstante", "debemos", "continuar", "con", "el", "plan"],
      answer: "No obstante, debemos continuar con el plan",
      explanation: "No obstante — «несмотря на это» (формальный регистр).",
      grammarTopic: "c1-matices-estilisticos",
    },
    {
      type: "sentence_building",
      question: "A / fin / de / cuentas / lo / importante / es / aprender",
      instruction: "Составьте устойчивое вводное выражение",
      options: ["A", "fin", "de", "cuentas", "lo", "importante", "es", "aprender"],
      answer: "A fin de cuentas, lo importante es aprender",
      explanation: "A fin de cuentas — «в конечном счёте».",
      grammarTopic: "c1-matices-estilisticos",
    },
    {
      type: "sentence_building",
      question: "Me / gustaría / que / lo / revisáramos / juntos",
      instruction: "Составьте мягкое предложение с subjuntivo",
      options: ["Me", "gustaría", "que", "lo", "revisáramos", "juntos"],
      answer: "Me gustaría que lo revisáramos juntos",
      explanation: "Me gustaría que + imperfecto de subjuntivo — мягкое предложение.",
      grammarTopic: "c1-matices-estilisticos",
    },
  ],

  // ===== Chapter 23: DELE contraste de pasados ========================
  "chapter-23-cronicas": [
    {
      type: "multiple_choice",
      question: "Ayer ___ a Marta en el mercado.",
      instruction: "Выберите правильное прошедшее время",
      options: ["vi", "veía", "he visto", "había visto"],
      answer: "vi",
      explanation: "«Ayer» — маркер indefinido: событие в закрытом прошлом → vi.",
    },
    {
      type: "multiple_choice",
      question: "Cuando era niño, ___ al fútbol todos los días.",
      instruction: "Привычка в прошлом — какое время?",
      options: ["jugaba", "jugué", "he jugado", "había jugado"],
      answer: "jugaba",
      explanation: "Привычка/повторение в прошлом (todos los días) → imperfecto: jugaba.",
    },
    {
      type: "multiple_choice",
      question: "Esta mañana ___ dos cafés.",
      instruction: "Период не закрыт — выберите время",
      options: ["he tomado", "tomé", "tomaba", "había tomado"],
      answer: "he tomado",
      explanation: "«Esta mañana» связана с настоящим → perfecto: he tomado (норма Испании).",
    },
    {
      type: "multiple_choice",
      question: "Cuando llegué a casa, mi hermano ya ___.",
      instruction: "Действие раньше другого прошлого",
      options: ["se había ido", "se fue", "se iba", "se ha ido"],
      answer: "se había ido",
      explanation: "«Ya… cuando» — предпрошедшее → pluscuamperfecto: se había ido.",
    },
    {
      type: "fill_blank",
      question: "___ (ducharse, yo) cuando sonó el teléfono.",
      instruction: "Фон + событие: поставьте глагол в нужное время",
      answer: "Me duchaba",
      acceptableAnswers: ["me duchaba", "Me estaba duchando", "me estaba duchando", "Estaba duchándome", "estaba duchándome"],
      explanation: "Фон — imperfecto (me duchaba / estaba duchándome), событие — indefinido (sonó).",
    },
    {
      type: "fill_blank",
      question: "Anoche no ___ (dormir, yo) bien.",
      instruction: "Обратите внимание на маркер anoche",
      answer: "dormí",
      acceptableAnswers: ["Dormí"],
      explanation: "«Anoche» → indefinido. Dormir неправильный: dormí.",
    },
    {
      type: "error_correction",
      question: "Ayer conocía a tu hermana en la fiesta.",
      instruction: "Исправьте время глагола",
      answer: "Ayer conocí a tu hermana en la fiesta.",
      acceptableAnswers: ["conocí", "Ayer conocí a tu hermana en la fiesta"],
      explanation: "«Познакомился» (событие) → conocí. Conocía = «был знаком» (фон).",
    },
  ],

  // ===== Chapter 24: DELE carta formal ================================
  "chapter-24-carta": [
    {
      type: "multiple_choice",
      question: "___ señora: Le escribo para solicitar información.",
      instruction: "Выберите формальное обращение",
      options: ["Estimada", "Querida", "Hola", "Oye"],
      answer: "Estimada",
      explanation: "Формальное письмо → Estimado/Estimada. Querida — для друзей.",
    },
    {
      type: "multiple_choice",
      question: "Le agradecería que me ___ más información.",
      instruction: "Вежливая просьба — какая форма?",
      options: ["enviara", "envía", "enviará", "envíe"],
      answer: "enviara",
      explanation: "Le agradecería que + subjuntivo imperfecto: enviara.",
    },
    {
      type: "multiple_choice",
      question: "___ , Juan Pérez (final de una carta formal)",
      instruction: "Выберите формальное прощание",
      options: ["Atentamente", "Un beso", "Chao", "Besitos"],
      answer: "Atentamente",
      explanation: "Atentamente — стандартное формальное прощание. Un beso — только близким.",
    },
    {
      type: "fill_blank",
      question: "Quisiera presentar una ___ por el mal servicio.",
      instruction: "Формальная жалоба — какое слово?",
      answer: "reclamación",
      acceptableAnswers: ["Reclamación", "queja"],
      explanation: "Presentar una reclamación — подать официальную жалобу.",
    },
    {
      type: "fill_blank",
      question: "Me ___ (dirigir) a usted con motivo de la oferta de trabajo.",
      instruction: "Формула начала письма",
      answer: "dirijo",
      acceptableAnswers: ["Dirijo"],
      explanation: "Me dirijo a usted con motivo de… — классическая формула причины письма.",
    },
    {
      type: "fill_blank",
      question: "A la ___ de su respuesta, le saluda atentamente.",
      instruction: "Формула завершения",
      answer: "espera",
      acceptableAnswers: ["Espera"],
      explanation: "A la espera de su respuesta — «в ожидании вашего ответа».",
    },
    {
      type: "translation",
      question: "Я хотел бы подать жалобу.",
      instruction: "Переведите формально (quisiera…)",
      answer: "Quisiera presentar una reclamación",
      acceptableAnswers: ["quisiera presentar una reclamación", "Quisiera presentar una reclamación."],
      explanation: "Quisiera + infinitivo — вежливая форма. Presentar una reclamación — подать жалобу.",
    },
  ],

  // ===== Chapter 25: DELE conectores ==================================
  "chapter-25-conectores": [
    {
      type: "multiple_choice",
      question: "___ lugar, hay que analizar las causas del problema.",
      instruction: "Коннектор начала эссе",
      options: ["En primer", "Al primer", "El primero", "Primero de"],
      answer: "En primer",
      explanation: "En primer lugar — «во-первых», стандартное начало redacción.",
    },
    {
      type: "multiple_choice",
      question: "El plan es caro; ___, es necesario.",
      instruction: "Формальное противопоставление",
      options: ["no obstante", "porque", "además", "por ejemplo"],
      answer: "no obstante",
      explanation: "No obstante — «тем не менее», формальнее, чем sin embargo.",
    },
    {
      type: "multiple_choice",
      question: "De ahí que ___ necesario actuar ya.",
      instruction: "Внимание: de ahí que требует особого наклонения",
      options: ["sea", "es", "será", "era"],
      answer: "sea",
      explanation: "De ahí que — всегда subjuntivo: sea. Классическая ловушка DELE.",
    },
    {
      type: "multiple_choice",
      question: "No creo que la medida ___ suficiente.",
      instruction: "Мнение с отрицанием",
      options: ["sea", "es", "será", "sería"],
      answer: "sea",
      explanation: "No creo que + subjuntivo: sea. Creo que + indicativo: es.",
    },
    {
      type: "fill_blank",
      question: "En ___, la educación es la clave del futuro. (вывод)",
      instruction: "Коннектор заключения",
      answer: "definitiva",
      acceptableAnswers: ["conclusión", "resumen", "Definitiva"],
      explanation: "En definitiva / en conclusión / en resumen — коннекторы вывода.",
    },
    {
      type: "sentence_building",
      question: "Por un lado / es útil / por otro / es caro",
      instruction: "Составьте предложение из фрагментов",
      options: ["Por un lado", "es útil", "por otro", "es caro"],
      answer: "Por un lado es útil por otro es caro",
      acceptableAnswers: ["por un lado es útil por otro es caro", "Por un lado es útil, por otro es caro"],
      explanation: "Por un lado…, por otro (lado)… — конструкция «с одной стороны… с другой…».",
    },
  ],

  // ===== Chapter 26: DELE expresión oral ==============================
  "chapter-26-voz-plaza": [
    {
      type: "multiple_choice",
      question: "En primer ___ se ve a una familia comiendo.",
      instruction: "Описание фото: передний план",
      options: ["plano", "lugar", "piso", "punto"],
      answer: "plano",
      explanation: "En primer plano — «на переднем плане» (фото). En primer lugar — «во-первых» (эссе).",
    },
    {
      type: "multiple_choice",
      question: "___ unos treinta años.",
      instruction: "Гипотеза о возрасте — экзаменатор ждёт futuro de conjetura",
      options: ["Tendrán", "Tienen", "Tenían", "Tuvieron"],
      answer: "Tendrán",
      explanation: "Догадка о настоящем → futuro: Tendrán unos treinta años — «им лет тридцать».",
    },
    {
      type: "multiple_choice",
      question: "Puede que ___ amigos.",
      instruction: "Puede que + …?",
      options: ["sean", "son", "serán", "eran"],
      answer: "sean",
      explanation: "Puede que — всегда subjuntivo: sean. Parece que + indicativo: son.",
    },
    {
      type: "multiple_choice",
      question: "Entiendo tu postura, ___ yo lo veo de otra manera.",
      instruction: "Вежливое несогласие",
      options: ["pero", "porque", "así que", "o sea"],
      answer: "pero",
      explanation: "Entiendo tu postura, pero… — вежливое несогласие в interacción.",
    },
    {
      type: "fill_blank",
      question: "Al ___ hay unas montañas.",
      instruction: "Описание фото: задний план",
      answer: "fondo",
      acceptableAnswers: ["Fondo"],
      explanation: "Al fondo — «на заднем плане».",
    },
    {
      type: "translation",
      question: "Я полностью с тобой согласен.",
      instruction: "Переведите фразу согласия",
      answer: "Estoy totalmente de acuerdo contigo",
      acceptableAnswers: ["estoy totalmente de acuerdo contigo", "Estoy totalmente de acuerdo contigo."],
      explanation: "Estar de acuerdo con — «быть согласным с». Totalmente усиливает.",
    },
  ],

  // ===== Chapter 27: C2 oraciones hendidas ============================
  "chapter-27-hendidas": [
    {
      type: "multiple_choice",
      question: "Fue Juan ___ rompió el vaso.",
      instruction: "Выделяем лицо",
      options: ["quien", "que cual", "cuyo", "donde"],
      answer: "quien",
      explanation: "Fue X quien… — выделительная конструкция для лица.",
    },
    {
      type: "multiple_choice",
      question: "Es en Madrid ___ vive mi hermana.",
      instruction: "Выделяем место",
      options: ["donde", "quien", "cuando", "cuyo"],
      answer: "donde",
      explanation: "Es en X donde… — выделение места.",
    },
    {
      type: "multiple_choice",
      question: "Es con ella ___ quiero hablar.",
      instruction: "Внимание: предлог повторяется",
      options: ["con quien", "que", "quien", "cual"],
      answer: "con quien",
      explanation: "Предлог повторяется: Es CON ella CON quien… «Es con ella que» — так по-французски, в испанском так не говорят.",
    },
    {
      type: "multiple_choice",
      question: "___ me molesta es el ruido.",
      instruction: "Выделяем причину раздражения",
      options: ["Lo que", "El que", "Que", "Cual"],
      answer: "Lo que",
      explanation: "Lo que + verbo + es… — выделение действия/объекта.",
    },
    {
      type: "fill_blank",
      question: "Fue ayer ___ lo supe.",
      instruction: "Выделяем время",
      answer: "cuando",
      acceptableAnswers: ["Cuando"],
      explanation: "Fue + время + cuando… — ser согласуется со временем события.",
    },
    {
      type: "sentence_building",
      question: "Lo que / necesito / es / dormir",
      instruction: "Составьте выделительную конструкцию",
      options: ["Lo que", "necesito", "es", "dormir"],
      answer: "Lo que necesito es dormir",
      acceptableAnswers: ["lo que necesito es dormir"],
      explanation: "Lo que necesito es… — «что мне нужно, так это…».",
    },
    {
      type: "sentence_building",
      question: "Fue / Juan / quien / rompió / el / vaso",
      instruction: "Составьте выделительную конструкцию (лицо)",
      options: ["Fue", "Juan", "quien", "rompió", "el", "vaso"],
      answer: "Fue Juan quien rompió el vaso",
      acceptableAnswers: ["fue juan quien rompio el vaso"],
      explanation: "Fue X quien… — выделение лица: «именно Хuan (тот, кто)…».",
    },
    {
      type: "sentence_building",
      question: "Es / en Madrid / donde / vive / mi / hermana",
      instruction: "Составьте выделительную конструкцию (место)",
      options: ["Es", "en Madrid", "donde", "vive", "mi", "hermana"],
      answer: "Es en Madrid donde vive mi hermana",
      acceptableAnswers: ["es en madrid donde vive mi hermana"],
      explanation: "Es en X donde… — выделение места: «именно в Мадриде живёт…».",
    },
    {
      type: "sentence_building",
      question: "Es / con ella / con quien / quiero / hablar",
      instruction: "Повторите предлог в выделительной конструкции",
      options: ["Es", "con ella", "con quien", "quiero", "hablar"],
      answer: "Es con ella con quien quiero hablar",
      acceptableAnswers: [
        "es con ella con quien quiero hablar",
        "Es con ella con quien quiero hablar.",
      ],
      explanation: "Es CON ella CON quien… — предлог повторяется в hendida.",
    },
    {
      type: "sentence_building",
      question: "Lo que / me molesta / es / el / ruido",
      instruction: "Составьте конструкцию Lo que… es…",
      options: ["Lo que", "me molesta", "es", "el", "ruido"],
      answer: "Lo que me molesta es el ruido",
      acceptableAnswers: ["lo que me molesta es el ruido"],
      explanation: "Lo que + verbo + es… — выделение того, что раздражает.",
    },
    {
      type: "sentence_building",
      question: "Fue / ayer / cuando / lo / supe",
      instruction: "Составьте выделительную конструкцию (время)",
      options: ["Fue", "ayer", "cuando", "lo", "supe"],
      answer: "Fue ayer cuando lo supe",
      acceptableAnswers: ["fue ayer cuando lo supe"],
      explanation: "Fue + tiempo + cuando… — выделение момента времени.",
    },
  ],

  // ===== Chapter 28: C2 conjetura y rumor =============================
  "chapter-28-conjetura": [
    {
      type: "multiple_choice",
      question: "— ¿Qué hora es? — No sé, ___ las diez.",
      instruction: "Догадка о настоящем",
      options: ["serán", "son", "eran", "fueron"],
      answer: "serán",
      explanation: "Futuro de conjetura: serán las diez — «наверное, часов десять».",
    },
    {
      type: "multiple_choice",
      question: "El presidente ___ el acuerdo, según fuentes no oficiales.",
      instruction: "Неподтверждённая информация (пресса)",
      options: ["habría aceptado", "aceptó", "ha aceptado", "aceptará"],
      answer: "habría aceptado",
      explanation: "Condicional de rumor: habría aceptado — «по сообщениям, принял».",
    },
    {
      type: "multiple_choice",
      question: "___ las dos cuando llegó a casa.",
      instruction: "Догадка о прошлом",
      options: ["Serían", "Son", "Serán", "Han sido"],
      answer: "Serían",
      explanation: "Condicional de conjetura: serían las dos — «было, наверное, часа два».",
    },
    {
      type: "multiple_choice",
      question: "___ de estar en casa — la luz está encendida.",
      instruction: "Вероятность ~90%: deber или deber de?",
      options: ["Debe", "Tiene", "Ha", "Va"],
      answer: "Debe",
      explanation: "Debe de estar — вероятность. Debe estar (без de) — долженствование.",
    },
    {
      type: "fill_blank",
      question: "___ salido ya — no contesta al teléfono.",
      instruction: "Догадка о недавнем прошлом: futuro perfecto de conjetura",
      answer: "Habrá",
      acceptableAnswers: ["habrá"],
      explanation: "Habrá salido — «наверное, уже ушёл»: futuro perfecto как догадка.",
    },
    {
      type: "translation",
      question: "Ему, наверное, лет сорок.",
      instruction: "Переведите через futuro de conjetura",
      answer: "Tendrá unos cuarenta años",
      acceptableAnswers: ["tendrá unos cuarenta años", "Tendrá unos 40 años"],
      explanation: "Догадка → futuro: Tendrá unos cuarenta años.",
    },
    {
      type: "sentence_building",
      question: "Serán / las / diez / ahora",
      instruction: "Составьте догадку о времени (futuro de conjetura)",
      options: ["Serán", "las", "diez", "ahora"],
      answer: "Serán las diez ahora",
      acceptableAnswers: ["seran las diez ahora", "Serán las diez"],
      explanation: "Futuro de conjetura: serán las diez — «наверное, сейчас десять».",
    },
    {
      type: "sentence_building",
      question: "Habrá / salido / ya",
      instruction: "Составьте догадку о недавнем прошлом",
      options: ["Habrá", "salido", "ya"],
      answer: "Habrá salido ya",
      acceptableAnswers: ["Ya habrá salido", "habrá salido ya"],
      explanation: "Habrá salido — «наверное, уже ушёл» (futuro perfecto de conjetura).",
    },
  ],

  // ===== Chapter 29: C2 estilo culto ==================================
  "chapter-29-culto": [
    {
      type: "multiple_choice",
      question: "___ la reunión, todos se fueron.",
      instruction: "Participio absoluto (согласуйте!)",
      options: ["Terminada", "Terminado", "Terminando", "Terminar"],
      answer: "Terminada",
      explanation: "Participio absoluto согласуется: la reunión (f.) → Terminada.",
    },
    {
      type: "multiple_choice",
      question: "Una vez ___ los documentos, no hay vuelta atrás.",
      instruction: "Согласуйте причастие",
      options: ["firmados", "firmado", "firmada", "firmando"],
      answer: "firmados",
      explanation: "Los documentos (m. pl.) → firmados.",
    },
    {
      type: "multiple_choice",
      question: "«porque aumentaron los precios» → (estilo culto) ___",
      instruction: "Выберите книжный аналог (номинализация)",
      options: [
        "Debido al aumento de los precios",
        "Porque los precios subieron",
        "Ya que suben los precios",
        "Como los precios",
      ],
      answer: "Debido al aumento de los precios",
      explanation: "Книжный стиль заменяет глагол существительным: debido al aumento de…",
    },
    {
      type: "multiple_choice",
      question: "El proyecto es caro; ___, lo aprobaremos.",
      instruction: "Самый формальный коннектор противопоставления",
      options: ["no obstante", "pero", "aunque sí", "es que"],
      answer: "no obstante",
      explanation: "No obstante — книжное «тем не менее».",
    },
    {
      type: "fill_blank",
      question: "Queda ___ fumar en todo el edificio.",
      instruction: "Формальный запрет: queda + participio",
      answer: "prohibido",
      acceptableAnswers: ["Prohibido"],
      explanation: "Queda prohibido — формальный запрет (queda + participio).",
    },
    {
      type: "error_correction",
      question: "Terminado la reunión, todos se fueron.",
      instruction: "Исправьте согласование",
      answer: "Terminada la reunión, todos se fueron.",
      acceptableAnswers: ["Terminada"],
      explanation: "La reunión — женский род → Terminada.",
    },
    {
      type: "sentence_building",
      question: "Terminada / la reunión / todos / se / fueron",
      instruction: "Составьте фразу с participio absoluto",
      options: ["Terminada", "la reunión", "todos", "se", "fueron"],
      answer: "Terminada la reunión todos se fueron",
      acceptableAnswers: [
        "Terminada la reunión, todos se fueron",
        "terminada la reunion todos se fueron",
      ],
      explanation: "Participio absoluto: Terminada la reunión,… — «когда собрание закончилось…».",
    },
  ],

  // ===== Chapter 30: C2 ironía y registro =============================
  "chapter-30-ironia": [
    {
      type: "multiple_choice",
      question: "«¡No me digas!» normalmente expresa ___",
      instruction: "Прагматика разговорной речи: что выражает фраза?",
      options: ["sorpresa / ironía", "una prohibición", "una orden", "un saludo"],
      answer: "sorpresa / ironía",
      explanation: "¡No me digas! — «да ну!, не может быть» (удивление, часто ироничное).",
    },
    {
      type: "multiple_choice",
      question: "«¡Qué va!» significa ___",
      instruction: "Разговорный регистр: что означает фраза?",
      options: ["nada de eso (negación)", "entusiasmo", "¿cómo estás?", "un saludo"],
      answer: "nada de eso (negación)",
      explanation: "¡Qué va! — разговорное энергичное отрицание («вовсе нет»).",
    },
    {
      type: "multiple_choice",
      question: "Versión formal de «¿Me pasas el agua?»: ___",
      instruction: "Смена регистра: бар → министерство",
      options: [
        "¿Sería tan amable de pasarme el agua?",
        "¡Agua, ya!",
        "Dame agua.",
        "¿Agua o qué?",
      ],
      answer: "¿Sería tan amable de pasarme el agua?",
      explanation: "Condicional + формула вежливости = высокий регистр.",
    },
    {
      type: "multiple_choice",
      question: "«Que te crees tú eso» expresa ___",
      instruction: "Ирония через структуру: что выражает фраза?",
      options: ["incredulidad irónica", "acuerdo", "un cumplido", "una petición"],
      answer: "incredulidad irónica",
      explanation: "Que te crees tú eso — «это ты так думаешь» (ироничное недоверие).",
    },
    {
      type: "fill_blank",
      question: "En Argentina en lugar de «tú» se usa «___».",
      instruction: "Региональная норма",
      answer: "vos",
      acceptableAnswers: ["Vos"],
      explanation: "Voseo: в Аргентине vos (vos tenés, vos sos).",
    },
    {
      type: "translation",
      question: "Как ни странно, он отказался.",
      instruction: "Переведите с «por extraño que…»",
      answer: "Por extraño que parezca, se negó",
      acceptableAnswers: ["por extraño que parezca, se negó", "Por extraño que parezca se negó"],
      explanation: "Por + adjetivo + que + subjuntivo: por extraño que parezca — «как ни странно».",
    },
    {
      type: "sentence_building",
      question: "Por / extraño / que / parezca / se / negó",
      instruction: "Составьте фразу с por extraño que…",
      options: ["Por", "extraño", "que", "parezca", "se", "negó"],
      answer: "Por extraño que parezca se negó",
      acceptableAnswers: [
        "Por extraño que parezca, se negó",
        "por extraño que parezca se negó",
      ],
      explanation: "Por extraño que parezca — «как ни странно» + subjuntivo.",
    },
  ],
};

/** Get exercises for a chapter slug (ids assigned, bank expanded). */
export function getChapterExercises(chapterSlug: string): StaticExercise[] {
  const chapter = CHAPTERS.find((c) => c.slug === chapterSlug);
  const grammarTopic = chapter?.grammarTopic ?? null;
  const curated = [
    ...(CHAPTER_EXERCISES[chapterSlug] ?? []),
    ...(CURRICULUM_CHAPTER_EXERCISES[chapterSlug] ?? []),
    ...((SPANISH_CURATED_SUPPLEMENTS as unknown as Record<string, ExerciseDraft[]>)[
      chapterSlug
    ] ?? []),
  ];
  const expanded = expandSpanishChapterBank(chapterSlug, curated);
  const aligned = grammarTopic
    ? expanded.filter((ex) => matchesChapterGrammar(grammarTopic, ex.grammarTopic))
    : expanded;
  const allowed = chapter?.exerciseTypes;
  const typeFiltered =
    allowed && allowed.length > 0
      ? aligned.filter((ex) => allowed.includes(ex.type))
      : aligned;
  const tagged = typeFiltered.map((ex) => ({
    ...ex,
    grammarTopic: ex.grammarTopic ?? grammarTopic ?? undefined,
  }));
  return withExerciseIds("spanish", chapterSlug, tagged);
}
