import type { Chapter, Level } from "@/types";

// =====================================================================
// Curriculum — chapters as a learning journey (Hippogriff adventure)
// ---------------------------------------------------------------------
// Slugs for existing chapters stay stable (progress is keyed by slug).
// New chapters insert into the array order / prereq chain.
// =====================================================================

export const CHAPTERS: Chapter[] = [
  {
    slug: "chapter-1-despertar",
    number: 1,
    title: "Пробуждение",
    titleEs: "El Despertar",
    level: "A1",
    location: "Академия",
    icon: "🌅",
    summary: "Первая тема: приветствия и два глагола «быть» — ser (кто ты) и estar (как ты сейчас).",
    grammarTopic: "a1-ser-estar",
    vocabTopic: "a1-familia",
    exerciseTypes: ["multiple_choice", "fill_blank", "translation", "error_correction", "sentence_building"],
    estimatedMinutes: 8,
  },
  {
    slug: "chapter-2-primer-dialogo",
    number: 2,
    title: "Первый разговор",
    titleEs: "El Primer Diálogo",
    level: "A1",
    location: "Лес",
    icon: "🌲",
    summary: "Настоящее время: три группы глаголов (-ar / -er / -ir) и как меняется окончание.",
    grammarTopic: "a1-presente",
    vocabTopic: "a1-verbos-basicos",
    exerciseTypes: ["multiple_choice", "fill_blank", "translation", "error_correction", "sentence_building"],
    prereqChapter: "chapter-1-despertar",
    estimatedMinutes: 10,
  },
  {
    slug: "chapter-3-biblioteca",
    number: 3,
    title: "Тайны библиотеки",
    titleEs: "Los Secretos de la Biblioteca",
    level: "A1",
    location: "Древняя библиотека",
    icon: "📚",
    summary: "Артикли el, la, un, una: конкретная вещь или «какая-то»; особый случай — el agua (не la abuela).",
    grammarTopic: "a1-articulos",
    vocabTopic: "a1-casa",
    exerciseTypes: ["multiple_choice", "fill_blank", "translation", "error_correction", "sentence_building"],
    prereqChapter: "chapter-2-primer-dialogo",
    estimatedMinutes: 8,
  },
  {
    slug: "chapter-18-genero-numero",
    number: 4,
    title: "Род и число",
    titleEs: "Género y Número",
    level: "A1",
    location: "Зал рукописей",
    icon: "🔤",
    summary: "Род и число существительных: мужской/женский, один/много; исключения problema, mano, agua.",
    grammarTopic: "a1-genero-numero",
    vocabTopic: "a1-casa",
    exerciseTypes: ["multiple_choice", "fill_blank", "error_correction", "translation", "sentence_building"],
    prereqChapter: "chapter-3-biblioteca",
    estimatedMinutes: 9,
  },
  {
    slug: "chapter-4-numeros-tiempo",
    number: 5,
    title: "Ход времени",
    titleEs: "El Ritmo del Tiempo",
    level: "A1",
    location: "Городские часы",
    icon: "🕐",
    summary: "Числа 1–100, дни недели, месяцы и как сказать время: es la una, son las dos.",
    grammarTopic: "a1-numeros-1-100",
    vocabTopic: "a1-numeros-tiempo",
    exerciseTypes: ["multiple_choice", "fill_blank", "translation", "error_correction", "sentence_building"],
    prereqChapter: "chapter-18-genero-numero",
    estimatedMinutes: 9,
  },
  {
    slug: "chapter-19-preposiciones",
    number: 6,
    title: "Карта города",
    titleEs: "El Mapa de la Ciudad",
    level: "A1",
    location: "Площадь Толедо",
    icon: "🗺️",
    summary: "Предлоги места: en, a, de, sobre, debajo, delante — где что находится.",
    grammarTopic: "a1-preposiciones-lugar",
    vocabTopic: "a1-ciudad",
    exerciseTypes: ["multiple_choice", "fill_blank", "translation", "error_correction", "sentence_building"],
    prereqChapter: "chapter-4-numeros-tiempo",
    estimatedMinutes: 9,
  },
  {
    slug: "chapter-5-mercado",
    number: 7,
    title: "Рынок Толедо",
    titleEs: "El Mercado de Toledo",
    level: "A1",
    location: "Толедо",
    icon: "🛒",
    summary: "Выражения с tener: tener hambre, frío, sueño, razón — «у меня голод», не через estar.",
    grammarTopic: "a1-tener-expressions",
    vocabTopic: "a1-colores",
    exerciseTypes: ["multiple_choice", "fill_blank", "translation", "error_correction", "sentence_building"],
    prereqChapter: "chapter-19-preposiciones",
    estimatedMinutes: 10,
  },
  {
    slug: "chapter-6-cuerpo",
    number: 8,
    title: "Целитель",
    titleEs: "El Curandero",
    level: "A1",
    location: "Аптека Толедо",
    icon: "🌿",
    summary: "Глагол gustar: «мне нравится кофе» = me gusta el café, а не «я нравлюсь кофе».",
    grammarTopic: "a1-gustar",
    vocabTopic: "a1-cuerpo",
    exerciseTypes: ["multiple_choice", "fill_blank", "translation", "error_correction", "sentence_building"],
    prereqChapter: "chapter-5-mercado",
    estimatedMinutes: 9,
  },
  {
    slug: "chapter-20-preguntas",
    number: 9,
    title: "Вопросы гиппогрифа",
    titleEs: "Las Preguntas del Hipogrifo",
    level: "A1",
    location: "Двор академии",
    icon: "💬",
    summary: "Вопросительные слова: qué, quién, dónde, cuándo, cómo, por qué и знаки ¿…?",
    grammarTopic: "a1-preguntas",
    vocabTopic: "a1-verbos-basicos",
    exerciseTypes: ["multiple_choice", "fill_blank", "translation", "error_correction", "sentence_building"],
    prereqChapter: "chapter-6-cuerpo",
    estimatedMinutes: 9,
  },
  {
    slug: "chapter-31-verbos-frecuentes",
    number: 10,
    title: "Карта частых глаголов",
    titleEs: "El Mapa de los Verbos",
    level: "A1",
    location: "Картографическая комната",
    icon: "🗺️",
    summary: "Частые неправильные глаголы: ir, tener, hacer, poder, querer, decir.",
    grammarTopic: "a1-verbos-frecuentes",
    vocabTopic: "a1-verbos-basicos",
    exerciseTypes: ["multiple_choice", "fill_blank", "translation", "error_correction", "sentence_building"],
    prereqChapter: "chapter-20-preguntas",
    estimatedMinutes: 9,
  },
  {
    slug: "chapter-7-pasado-perfecto",
    number: 11,
    title: "Воспоминания",
    titleEs: "Los Recuerdos",
    level: "A2",
    location: "Древняя библиотека",
    icon: "💭",
    summary: "Pretérito Perfecto — прошлое, связанное с «сейчас»: he comido, has ido.",
    grammarTopic: "a2-preterito-perfecto",
    vocabTopic: "a2-viajes",
    exerciseTypes: ["multiple_choice", "fill_blank", "translation", "error_correction", "sentence_building"],
    prereqChapter: "chapter-31-verbos-frecuentes",
    estimatedMinutes: 10,
  },
  {
    slug: "chapter-8-pasado-indefinido",
    number: 12,
    title: "Испытание Толедо",
    titleEs: "La Prueba de Toledo",
    level: "A2",
    location: "Замок Толедо",
    icon: "⚔️",
    summary: "Pretérito Indefinido — законченный факт в прошлом: ayer fui, en 2018 viajé.",
    grammarTopic: "a2-preterito-indefinido",
    vocabTopic: "a2-trabajo",
    exerciseTypes: ["multiple_choice", "fill_blank", "error_correction", "translation", "sentence_building"],
    prereqChapter: "chapter-7-pasado-perfecto",
    estimatedMinutes: 10,
  },
  {
    slug: "chapter-9-imperfecto",
    number: 13,
    title: "Туман прошлого",
    titleEs: "La Niebla del Pasado",
    level: "A2",
    location: "Туманный лес",
    icon: "🌫️",
    summary: "Pretérito Imperfecto — фон прошлого: привычки, описания, «когда я был ребёнком».",
    grammarTopic: "a2-imperfecto",
    vocabTopic: "a2-clima",
    exerciseTypes: ["multiple_choice", "fill_blank", "translation", "error_correction", "sentence_building"],
    prereqChapter: "chapter-8-pasado-indefinido",
    estimatedMinutes: 10,
  },
  {
    slug: "chapter-10-por-para",
    number: 14,
    title: "Перекрёсток Мадрида",
    titleEs: "El Cruce de Madrid",
    level: "A2",
    location: "Мадрид",
    icon: "🚇",
    summary: "Para — цель и «для кого»; por — причина, маршрут, цена, время суток.",
    grammarTopic: "a2-por-para",
    vocabTopic: "a2-compras",
    exerciseTypes: ["multiple_choice", "fill_blank", "translation", "error_correction", "sentence_building"],
    prereqChapter: "chapter-9-imperfecto",
    estimatedMinutes: 10,
  },
  {
    slug: "chapter-21-comparativos",
    number: 15,
    title: "Состязание на площади",
    titleEs: "El Torneo de la Plaza",
    level: "A2",
    location: "Пласа Майор",
    icon: "⚖️",
    summary: "Сравнения: más… que, menos… que, tan… como, el más…; mejor, peor, mayor.",
    grammarTopic: "a2-comparativos",
    vocabTopic: "a2-deportes",
    exerciseTypes: ["multiple_choice", "fill_blank", "translation", "error_correction", "sentence_building"],
    prereqChapter: "chapter-10-por-para",
    estimatedMinutes: 10,
  },
  {
    slug: "chapter-22-futuro",
    number: 16,
    title: "Пророчество",
    titleEs: "La Profecía",
    level: "A2",
    location: "Обсерватория",
    icon: "🔮",
    summary: "Futuro simple — будущее одним словом: hablaré, tendré (не только ir a + infinitivo).",
    grammarTopic: "a2-futuro-simple",
    vocabTopic: "a2-tecnologia",
    exerciseTypes: ["multiple_choice", "fill_blank", "translation", "error_correction", "sentence_building"],
    prereqChapter: "chapter-21-comparativos",
    estimatedMinutes: 10,
  },
  {
    slug: "chapter-11-subjuntivo",
    number: 17,
    title: "Сердце города",
    titleEs: "El Corazón de la Ciudad",
    level: "B1",
    location: "Пуэрта-дель-Соль",
    icon: "❤️",
    summary: "Presente de Subjuntivo — желание, сомнение, эмоция: quiero que vengas.",
    grammarTopic: "b1-subjuntivo",
    vocabTopic: "b1-emociones",
    exerciseTypes: ["multiple_choice", "fill_blank", "translation", "error_correction", "sentence_building"],
    prereqChapter: "chapter-22-futuro",
    estimatedMinutes: 12,
  },
  {
    slug: "chapter-12-imperativo",
    number: 18,
    title: "Приказ командира",
    titleEs: "La Orden del Comandante",
    level: "B1",
    location: "Военная академия",
    icon: "🎖️",
    summary: "Imperativo — приказы и просьбы: habla, no hables, venga.",
    grammarTopic: "b1-imperativo",
    vocabTopic: "b1-opiniones",
    exerciseTypes: ["multiple_choice", "fill_blank", "translation", "error_correction", "sentence_building"],
    prereqChapter: "chapter-11-subjuntivo",
    estimatedMinutes: 10,
  },
  {
    slug: "chapter-13-condicional",
    number: 19,
    title: "Если бы...",
    titleEs: "Si Pudiera...",
    level: "B1",
    location: "Сады Севильи",
    icon: "🌹",
    summary: "Condicional — «я бы» и вежливые просьбы: hablaría, podría, me gustaría.",
    grammarTopic: "b1-condicional",
    vocabTopic: "b1-sociedad",
    exerciseTypes: ["multiple_choice", "fill_blank", "translation", "error_correction", "sentence_building"],
    prereqChapter: "chapter-12-imperativo",
    estimatedMinutes: 10,
  },
  {
    slug: "chapter-32-pronombre-se",
    number: 20,
    title: "Зеркальный зал",
    titleEs: "La Sala de los Espejos",
    level: "B1",
    location: "Зеркальный зал Севильи",
    icon: "🪞",
    summary: "Местоимение se — пять значений: возвратное, взаимное, безличное, пассивное, «случайно».",
    grammarTopic: "b1-pronombre-se",
    vocabTopic: "b1-sociedad",
    exerciseTypes: ["multiple_choice", "fill_blank", "translation", "error_correction", "sentence_building"],
    prereqChapter: "chapter-13-condicional",
    estimatedMinutes: 10,
  },
  {
    slug: "chapter-33-relativos",
    number: 21,
    title: "Нити истории",
    titleEs: "Los Hilos de la Historia",
    level: "B1",
    location: "Архив рассказов",
    icon: "🧵",
    summary: "Относительные местоимения: que, quien, lo que, cuyo, donde — связка двух фраз.",
    grammarTopic: "b1-relativos",
    vocabTopic: "b1-educacion",
    exerciseTypes: ["multiple_choice", "fill_blank", "translation", "error_correction", "sentence_building"],
    prereqChapter: "chapter-32-pronombre-se",
    estimatedMinutes: 10,
  },
  {
    slug: "chapter-34-pluscuamperfecto",
    number: 22,
    title: "Два слоя прошлого",
    titleEs: "Dos Capas del Pasado",
    level: "B1",
    location: "Часовая башня",
    icon: "⏳",
    summary: "Pluscuamperfecto — «уже было до того»: había comido, cuando llegaste.",
    grammarTopic: "b1-pluscuamperfecto",
    vocabTopic: "b1-educacion",
    exerciseTypes: ["multiple_choice", "fill_blank", "translation", "error_correction", "sentence_building"],
    prereqChapter: "chapter-33-relativos",
    estimatedMinutes: 10,
  },
  {
    slug: "chapter-35-subjuntivo-imperfecto",
    number: 23,
    title: "Если бы в прошлом",
    titleEs: "Si en el Pasado",
    level: "B1",
    location: "Сад «что могло быть»",
    icon: "🌿",
    summary: "Imperfecto de Subjuntivo — «если бы» и желания в прошлом: si tuviera, quería que vinieras.",
    grammarTopic: "b1-subjuntivo-imperfecto",
    vocabTopic: "b1-opiniones",
    exerciseTypes: ["multiple_choice", "fill_blank", "translation", "error_correction", "sentence_building"],
    prereqChapter: "chapter-34-pluscuamperfecto",
    estimatedMinutes: 10,
  },
  {
    slug: "chapter-36-pronombres-objetos",
    number: 24,
    title: "Маленькие слова",
    titleEs: "Las Palabras Pequeñas",
    level: "B1",
    location: "Лингвистическая мастерская",
    icon: "🔤",
    summary: "Прямое и косвенное дополнение: lo/la = «это», le = «ему/ей», se lo (не le lo).",
    grammarTopic: "b1-pronombres-objetos",
    vocabTopic: "b1-medios",
    exerciseTypes: ["multiple_choice", "fill_blank", "translation", "error_correction", "sentence_building"],
    prereqChapter: "chapter-35-subjuntivo-imperfecto",
    estimatedMinutes: 10,
  },
  {
    slug: "chapter-37-adverbios",
    number: 25,
    title: "Оттенки речи",
    titleEs: "Matices del Habla",
    level: "B1",
    location: "Палитра слов",
    icon: "🎨",
    summary: "Наречия: rápidamente (-mente), muy vs mucho; quizás + subjuntivo.",
    grammarTopic: "b1-adverbios",
    vocabTopic: "b1-sociedad",
    exerciseTypes: ["multiple_choice", "fill_blank", "translation", "error_correction", "sentence_building"],
    prereqChapter: "chapter-36-pronombres-objetos",
    estimatedMinutes: 9,
  },
  {
    slug: "chapter-23-cronicas",
    number: 26,
    title: "Хроники странника",
    titleEs: "Las Crónicas del Viajero",
    level: "B1",
    location: "Архив Севильи",
    icon: "📜",
    summary: "DELE: как выбрать Perfecto, Indefinido или Imperfecto; Pluscuamperfecto — в главе «Два слоя прошлого».",
    grammarTopic: "dele-contraste-pasados",
    vocabTopic: "b1-educacion",
    exerciseTypes: ["multiple_choice", "fill_blank", "translation", "error_correction", "sentence_building"],
    prereqChapter: "chapter-37-adverbios",
    estimatedMinutes: 12,
  },
  {
    slug: "chapter-24-carta",
    number: 27,
    title: "Письмо гиппогрифу",
    titleEs: "La Carta al Hipogrifo",
    level: "B1",
    location: "Почтовый двор Севильи",
    icon: "✉️",
    summary: "DELE письмо: обращения, вежливые просьбы, прощания — готовые формулы.",
    grammarTopic: "dele-carta-formal",
    vocabTopic: "b1-medios",
    exerciseTypes: ["multiple_choice", "fill_blank", "translation", "error_correction", "sentence_building"],
    prereqChapter: "chapter-23-cronicas",
    estimatedMinutes: 12,
  },
  {
    slug: "chapter-14-estilo-indirecto",
    number: 28,
    title: "Сплетни Барселоны",
    titleEs: "Los Cotilleos de Barcelona",
    level: "B2",
    location: "Барселона",
    icon: "🗣️",
    summary: "Estilo indirecto — передача чужих слов: dijo que vendría; сдвиг времён после прошедшего.",
    grammarTopic: "b2-estilo-indirecto",
    vocabTopic: "b2-argumentacion",
    exerciseTypes: ["multiple_choice", "fill_blank", "translation", "error_correction", "sentence_building"],
    prereqChapter: "chapter-24-carta",
    estimatedMinutes: 12,
  },
  {
    slug: "chapter-15-voz-pasiva",
    number: 29,
    title: "Тайны Готического квартала",
    titleEs: "Misterios del Barrio Gótico",
    level: "B2",
    location: "Готический квартал",
    icon: "🏛️",
    summary: "Voz pasiva — fue escrito; pasiva refleja — se habla español; estado — está cerrada.",
    grammarTopic: "b2-voz-pasiva",
    vocabTopic: "b2-ciencia",
    exerciseTypes: ["multiple_choice", "fill_blank", "translation", "error_correction", "sentence_building"],
    prereqChapter: "chapter-14-estilo-indirecto",
    estimatedMinutes: 12,
  },
  {
    slug: "chapter-38-subjuntivo-compuestos",
    number: 30,
    title: "Субъунктив в совершенном",
    titleEs: "Subjuntivo Compuesto",
    level: "B2",
    location: "Зал времени",
    icon: "⌛",
    summary: "Subjuntivo compuesto — haya hablado, hubiera hablado (то же правило, другое время).",
    grammarTopic: "b2-subjuntivo-compuestos",
    vocabTopic: "b2-argumentacion",
    exerciseTypes: ["multiple_choice", "fill_blank", "translation", "error_correction", "sentence_building"],
    prereqChapter: "chapter-15-voz-pasiva",
    estimatedMinutes: 11,
  },
  {
    slug: "chapter-39-condicionales-compuestos",
    number: 31,
    title: "Три мира «если»",
    titleEs: "Tres Mundos del Si",
    level: "B2",
    location: "Развилка судеб",
    icon: "🔀",
    summary: "Condicional compuesto — habría ido; три типа si: real, irreal, irreal в прошлом.",
    grammarTopic: "b2-condicionales-compuestos",
    vocabTopic: "b2-ciencia",
    exerciseTypes: ["multiple_choice", "fill_blank", "translation", "error_correction", "sentence_building"],
    prereqChapter: "chapter-38-subjuntivo-compuestos",
    estimatedMinutes: 11,
  },
  {
    slug: "chapter-40-relativos-avanzado",
    number: 32,
    title: "Формальные нити",
    titleEs: "Hilos Formales",
    level: "B2",
    location: "Салон Salamanca",
    icon: "📚",
    summary: "Продвинутые относительные: el cual, lo que, adonde — для формального регистра.",
    grammarTopic: "b2-relativos-avanzado",
    vocabTopic: "b2-argumentacion",
    exerciseTypes: ["multiple_choice", "fill_blank", "translation", "error_correction", "sentence_building"],
    prereqChapter: "chapter-39-condicionales-compuestos",
    estimatedMinutes: 10,
  },
  {
    slug: "chapter-41-conectores-discursivos",
    number: 33,
    title: "Мосты между мыслями",
    titleEs: "Puentes entre Ideas",
    level: "B2",
    location: "Мост Salamanca",
    icon: "🌉",
    summary: "Связки для текста B2+: sin embargo, por lo tanto; часть требует subjuntivo.",
    grammarTopic: "b2-conectores",
    vocabTopic: "b2-argumentacion",
    exerciseTypes: ["multiple_choice", "fill_blank", "translation", "error_correction", "sentence_building"],
    prereqChapter: "chapter-40-relativos-avanzado",
    estimatedMinutes: 10,
  },
  {
    slug: "chapter-25-conectores",
    number: 34,
    title: "Мост аргументов",
    titleEs: "El Puente de los Argumentos",
    level: "B2",
    location: "Университет Саламанки",
    icon: "🌉",
    summary: "DELE сочинение: скелет абзацев (en primer lugar…) + мнение с subjuntivo.",
    grammarTopic: "dele-conectores-redaccion",
    vocabTopic: "b2-argumentacion",
    exerciseTypes: ["multiple_choice", "fill_blank", "translation", "error_correction", "sentence_building"],
    prereqChapter: "chapter-41-conectores-discursivos",
    estimatedMinutes: 12,
  },
  {
    slug: "chapter-26-voz-plaza",
    number: 35,
    title: "Голос площади",
    titleEs: "La Voz de la Plaza",
    level: "B2",
    location: "Пласа-де-Эспанья",
    icon: "🎤",
    summary: "DELE устная часть: описание фото, гипотезы, мнение, согласие — живая речь.",
    grammarTopic: "dele-expresion-oral",
    vocabTopic: "b2-problemas-sociales",
    exerciseTypes: ["multiple_choice", "fill_blank", "translation", "error_correction", "sentence_building"],
    prereqChapter: "chapter-25-conectores",
    estimatedMinutes: 12,
  },
  {
    slug: "chapter-16-perifrasis",
    number: 36,
    title: "Мастер слова",
    titleEs: "El Maestro de las Palabras",
    level: "C1",
    location: "Литературный салон",
    icon: "✒️",
    summary: "Перифразы: acabar de, llevar + gerundio, deber de — готовые глагольные связки.",
    grammarTopic: "c1-perifrasis-verbales",
    vocabTopic: "c1-expresiones-idiomaticas",
    exerciseTypes: ["multiple_choice", "fill_blank", "error_correction", "translation", "sentence_building"],
    prereqChapter: "chapter-26-voz-plaza",
    estimatedMinutes: 15,
  },
  {
    slug: "chapter-17-dele",
    number: 37,
    title: "Замок DELE",
    titleEs: "El Castillo DELE",
    level: "C1",
    location: "Замок DELE",
    icon: "🏰",
    summary: "Регистр и вежливость: tú / usted, формулы просьбы — не новая грамматика, а уместность.",
    grammarTopic: "c1-matices-estilisticos",
    vocabTopic: "c1-lenguaje-formal",
    exerciseTypes: ["multiple_choice", "fill_blank", "translation", "error_correction", "sentence_building"],
    prereqChapter: "chapter-16-perifrasis",
    estimatedMinutes: 15,
  },
  {
    slug: "chapter-42-subjuntivo-avanzado",
    number: 38,
    title: "Спорные случаи subjuntivo",
    titleEs: "Subjuntivo: Casos Dudosos",
    level: "C1",
    location: "Зал дебатов",
    icon: "⚖️",
    summary: "Спорные случаи subjuntivo: aunque, donde, como — факт или гипотеза.",
    grammarTopic: "c1-subjuntivo-avanzado",
    vocabTopic: "c1-lenguaje-formal",
    exerciseTypes: ["multiple_choice", "fill_blank", "error_correction", "translation", "sentence_building"],
    prereqChapter: "chapter-17-dele",
    estimatedMinutes: 12,
  },
  {
    slug: "chapter-43-indirecto-avanzado",
    number: 39,
    title: "Полная сетка передачи речи",
    titleEs: "Estilo Indirecto Completo",
    level: "C1",
    location: "Архив протоколов",
    icon: "📋",
    summary: "Полная сетка estilo indirecto: все сдвиги времён, subjuntivo, указатели hoy → aquel día.",
    grammarTopic: "c1-indirecto-avanzado",
    vocabTopic: "c1-lenguaje-formal",
    exerciseTypes: ["multiple_choice", "fill_blank", "translation", "error_correction", "sentence_building"],
    prereqChapter: "chapter-42-subjuntivo-avanzado",
    estimatedMinutes: 12,
  },
  {
    slug: "chapter-44-pronombres-avanzado",
    number: 40,
    title: "Lo bueno de todo",
    titleEs: "Lo Bueno de Todo",
    level: "C1",
    location: "Лингвистический музей",
    icon: "🏛️",
    summary: "Продвинутые местоимения: lo bueno, a María la veo, leísmo / laísmo.",
    grammarTopic: "c1-pronombres-avanzado",
    vocabTopic: "c1-expresiones-idiomaticas",
    exerciseTypes: ["multiple_choice", "fill_blank", "translation", "error_correction", "sentence_building"],
    prereqChapter: "chapter-43-indirecto-avanzado",
    estimatedMinutes: 11,
  },
  {
    slug: "chapter-45-ser-estar-matices",
    number: 41,
    title: "Два «быть» снова",
    titleEs: "Ser y Estar Otra Vez",
    level: "C1",
    location: "Зал зеркал смысла",
    icon: "🪞",
    summary: "Ser vs estar в сложных парах: es listo vs está listo — смысл меняется.",
    grammarTopic: "c1-ser-estar-avanzado",
    vocabTopic: "c1-conceptos-abstractos",
    exerciseTypes: ["multiple_choice", "fill_blank", "translation", "error_correction", "sentence_building"],
    prereqChapter: "chapter-44-pronombres-avanzado",
    estimatedMinutes: 11,
  },
  {
    slug: "chapter-27-hendidas",
    number: 42,
    title: "Зеркальный лабиринт",
    titleEs: "El Laberinto de los Espejos",
    level: "C2",
    location: "Альгамбра",
    icon: "🪞",
    summary: "Oraciones hendidas — fue Juan quien…, lo que necesito es… — выделение важного.",
    grammarTopic: "c2-oraciones-hendidas",
    vocabTopic: "c1-expresiones-idiomaticas",
    exerciseTypes: ["multiple_choice", "fill_blank", "translation", "error_correction", "sentence_building"],
    prereqChapter: "chapter-45-ser-estar-matices",
    estimatedMinutes: 15,
  },
  {
    slug: "chapter-28-conjetura",
    number: 43,
    title: "Шёпот слухов",
    titleEs: "El Susurro de los Rumores",
    level: "C2",
    location: "Редакция газеты, Мадрид",
    icon: "🗞️",
    summary: "Futuro de conjetura — Serán las diez (≈ наверное десять); condicional de rumor — habría mil.",
    grammarTopic: "c2-conjetura-rumor",
    vocabTopic: "c1-conceptos-abstractos",
    exerciseTypes: ["multiple_choice", "fill_blank", "translation", "error_correction", "sentence_building"],
    prereqChapter: "chapter-27-hendidas",
    estimatedMinutes: 15,
  },
  {
    slug: "chapter-29-culto",
    number: 44,
    title: "Перо академика",
    titleEs: "La Pluma del Académico",
    level: "C2",
    location: "Королевская академия",
    icon: "🖋️",
    summary: "Книжный стиль: participio absoluto (Terminada la reunión…), номинализация.",
    grammarTopic: "c2-estilo-culto",
    vocabTopic: "c1-lenguaje-formal",
    exerciseTypes: ["multiple_choice", "fill_blank", "translation", "error_correction", "sentence_building"],
    prereqChapter: "chapter-28-conjetura",
    estimatedMinutes: 15,
  },
  {
    slug: "chapter-30-ironia",
    number: 45,
    title: "Маски иронии",
    titleEs: "Las Máscaras de la Ironía",
    level: "C2",
    location: "Театр Сервантеса",
    icon: "🎭",
    summary: "Ирония, сарказм и смена регистра — формы известны, важна уместность.",
    grammarTopic: "c2-ironia-registry",
    vocabTopic: "c1-regionalismos",
    exerciseTypes: ["multiple_choice", "fill_blank", "translation", "error_correction", "sentence_building"],
    prereqChapter: "chapter-29-culto",
    estimatedMinutes: 15,
  },
];

// ---------- Helpers --------------------------------------------------

/** Get a chapter by slug. */
export function getChapter(slug: string): Chapter | undefined {
  return CHAPTERS.find((c) => c.slug === slug);
}

/** Get the first chapter (entry point). */
export function getFirstChapter(): Chapter {
  return CHAPTERS[0];
}

/**
 * Get the first chapter for a given CEFR level.
 * Used during onboarding — a B2 user starts at the B2 chapter, not A1.
 */
export function getFirstChapterForLevel(level: Level): Chapter {
  const ch = CHAPTERS.find((c) => c.level === level);
  return ch ?? CHAPTERS[0];
}

/**
 * Get the slug of the first chapter for a level (for redirects).
 */
export function getFirstChapterSlugForLevel(level: Level | null): string {
  if (!level) return CHAPTERS[0].slug;
  const ch = CHAPTERS.find((c) => c.level === level);
  return ch?.slug ?? CHAPTERS[0].slug;
}

/** Get the next chapter after a given slug. */
export function getNextChapter(slug: string): Chapter | undefined {
  const idx = CHAPTERS.findIndex((c) => c.slug === slug);
  if (idx < 0 || idx + 1 >= CHAPTERS.length) return undefined;
  return CHAPTERS[idx + 1];
}

/** Get all chapters for a given level. */
export function getChaptersByLevel(level: Chapter["level"]): Chapter[] {
  return CHAPTERS.filter((c) => c.level === level);
}

/** Roman numeral for display (I, II, III...). */
export function toRoman(num: number): string {
  const romans: [number, string][] = [
    [10, "X"], [9, "IX"], [5, "V"], [4, "IV"], [1, "I"],
  ];
  let result = "";
  let n = num;
  for (const [val, sym] of romans) {
    while (n >= val) {
      result += sym;
      n -= val;
    }
  }
  return result;
}
