// Auto-generated by scripts/bootstrap-curriculum-chapters.mjs — do not edit by hand.
import type { StaticExercise } from "@/types";

type ExerciseDraft = Omit<StaticExercise, "id"> & { id?: string };

export const CURRICULUM_CHAPTER_EXERCISES: Record<string, ExerciseDraft[]> = {
  "chapter-31-verbos-frecuentes": [
    {
      "type": "multiple_choice",
      "question": "Yo ___ al mercado los sábados.",
      "instruction": "Выберите форму ir",
      "options": [
        "voy",
        "vas",
        "va",
        "van"
      ],
      "answer": "voy",
      "explanation": "Yo → voy (ir — неправильный глагол).",
      "grammarTopic": "verbos-frecuentes"
    },
    {
      "type": "fill_blank",
      "question": "¿Qué ___ hacer hoy?",
      "instruction": "Поставьте querer (tú)",
      "answer": "quieres",
      "acceptableAnswers": [
        "Quieres"
      ],
      "explanation": "Querer: yo quiero, tú quieres, él quiere.",
      "grammarTopic": "verbos-frecuentes"
    },
    {
      "type": "multiple_choice",
      "question": "No ___ decir la verdad.",
      "instruction": "Выберите poder (yo)",
      "options": [
        "puedo",
        "puede",
        "podemos",
        "pueden"
      ],
      "answer": "puedo",
      "explanation": "Yo no puedo — poder o→ue в настоящем.",
      "grammarTopic": "verbos-frecuentes"
    },
    {
      "type": "translation",
      "question": "У меня есть два брата.",
      "instruction": "Переведите с tener",
      "answer": "Tengo dos hermanos",
      "acceptableAnswers": [
        "tengo dos hermanos"
      ],
      "explanation": "Tener для «у меня есть»: Tengo dos hermanos.",
      "grammarTopic": "verbos-frecuentes"
    },
    {
      "type": "fill_blank",
      "question": "Ella ___ la comida en casa.",
      "instruction": "Поставьте hacer (ella)",
      "answer": "hace",
      "acceptableAnswers": [
        "Hace"
      ],
      "explanation": "Hacer: yo hago, tú haces, él/ella hace.",
      "grammarTopic": "verbos-frecuentes"
    },
    {
      "type": "sentence_building",
      "question": "¿ / Qué / dices / tú / ?",
      "options": [
        "¿",
        "Qué",
        "dices",
        "tú",
        "?"
      ],
      "answer": "¿Qué dices tú?",
      "instruction": "Соберите вопрос «Что ты говоришь?»",
      "explanation": "Decir: yo digo, tú dices. ¿Qué dices?",
      "grammarTopic": "verbos-frecuentes"
    }
  ],

  "chapter-32-pronombre-se": [
    {
      "type": "multiple_choice",
      "question": "___ habla español en esta región.",
      "instruction": "Вставьте нужное слово в начало",
      "options": [
        "Se",
        "Me",
        "Te",
        "Le"
      ],
      "answer": "Se",
      "explanation": "Se habla español — «здесь говорят по-испански».",
      "grammarTopic": "pronombre-se"
    },
    {
      "type": "fill_blank",
      "question": "María ___ levanta a las siete.",
      "instruction": "Вставьте пропущенное слово",
      "answer": "se",
      "acceptableAnswers": [
        "Se"
      ],
      "explanation": "María se levanta — встаёт (действие на себя).",
      "grammarTopic": "pronombre-se"
    },
    {
      "type": "multiple_choice",
      "question": "«Se me rompió el vaso» выражает…",
      "instruction": "Что передаёт эта конструкция?",
      "options": [
        "случайность",
        "приказ",
        "будущее",
        "сравнение"
      ],
      "answer": "случайность",
      "explanation": "Se me rompió — «у меня разбился» (не специально).",
      "grammarTopic": "pronombre-se"
    },
    {
      "type": "translation",
      "question": "Здесь продаются книги.",
      "instruction": "Переведите на испанский",
      "answer": "Se venden libros aquí",
      "acceptableAnswers": [
        "se venden libros aquí",
        "Aquí se venden libros"
      ],
      "explanation": "Se venden libros — «книги продаются / здесь продают книги».",
      "grammarTopic": "pronombre-se"
    },
    {
      "type": "error_correction",
      "question": "Se vende casas en el centro.",
      "instruction": "Исправьте согласование",
      "answer": "Se venden casas en el centro.",
      "acceptableAnswers": [
        "Se venden casas en el centro"
      ],
      "explanation": "Casas — мн.ч. → se venden.",
      "grammarTopic": "pronombre-se"
    },
    {
      "type": "fill_blank",
      "question": "Ana y Luis ___ ven cada día.",
      "instruction": "Вставьте пропущенное слово",
      "answer": "se",
      "acceptableAnswers": [
        "Se"
      ],
      "explanation": "Se ven = видят друг друга.",
      "grammarTopic": "pronombre-se"
    },
    {
      "type": "translation",
      "question": "Она встаёт в семь часов.",
      "instruction": "Переведите на испанский",
      "answer": "Se levanta a las siete",
      "acceptableAnswers": [
        "Ella se levanta a las siete",
        "Se levanta a las siete."
      ],
      "explanation": "Levantarse → se levanta.",
      "grammarTopic": "pronombre-se"
    },
    {
      "type": "translation",
      "question": "Мне забылось имя. / Я забыл имя (случайно).",
      "instruction": "Переведите на испанский",
      "answer": "Se me olvidó el nombre",
      "acceptableAnswers": [
        "Se me olvidó el nombre.",
        "Se me ha olvidado el nombre"
      ],
      "explanation": "Se me olvidó — «у меня забылось», не специально.",
      "grammarTopic": "pronombre-se"
    }
  ],

  "chapter-33-relativos": [
    {
      "type": "multiple_choice",
      "question": "La mujer ___ habla es mi profesora.",
      "instruction": "Выберите правильный вариант",
      "options": ["que", "quien", "cuyo", "donde"],
      "answer": "que",
      "explanation": "Без предлога для людей и вещей обычно que: la mujer que habla.",
      "grammarTopic": "relativos"
    },
    {
      "type": "multiple_choice",
      "question": "___ me gusta es la libertad.",
      "instruction": "Выберите правильный вариант",
      "options": ["Lo que", "La que", "El que", "Donde"],
      "answer": "Lo que",
      "explanation": "Lo que = «то, что» (абстрактное).",
      "grammarTopic": "relativos"
    },
    {
      "type": "multiple_choice",
      "question": "Este es el parque ___ jugábamos de niños.",
      "instruction": "Выберите правильный вариант",
      "options": ["donde", "que", "quien", "cuyo"],
      "answer": "donde",
      "explanation": "Donde связывает место: el parque donde…",
      "grammarTopic": "relativos"
    },
    {
      "type": "multiple_choice",
      "question": "La persona ___ escribí no respondió.",
      "instruction": "Выберите правильный вариант",
      "options": ["a quien", "que", "cuyo", "donde"],
      "answer": "a quien",
      "explanation": "После предлога a для человека: a quien (не голое que).",
      "grammarTopic": "relativos"
    },
    {
      "type": "fill_blank",
      "question": "El chico ___ padre es médico estudia mucho.",
      "instruction": "Заполните пропуск",
      "answer": "cuyo",
      "acceptableAnswers": ["Cuyo"],
      "explanation": "Cuyo = «чей» и согласуется с тем, что принадлежит: cuyo padre.",
      "grammarTopic": "relativos"
    },
    {
      "type": "fill_blank",
      "question": "Conozco a alguien ___ sabe ruso.",
      "instruction": "Заполните пропуск",
      "answer": "que",
      "acceptableAnswers": ["Que", "quien", "Quien"],
      "explanation": "После alguien чаще que; quien тоже возможен.",
      "grammarTopic": "relativos"
    },
    {
      "type": "fill_blank",
      "question": "El tema ___ hablamos es difícil.",
      "instruction": "Заполните пропуск",
      "answer": "del que",
      "acceptableAnswers": ["Del que", "de que"],
      "explanation": "После de нужен артикль: del que / de la que, не голое de que.",
      "grammarTopic": "relativos"
    },
    {
      "type": "fill_blank",
      "question": "No hay nada ___ me asuste.",
      "instruction": "Заполните пропуск",
      "answer": "que",
      "acceptableAnswers": ["Que"],
      "explanation": "После nada/algo/alguien часто que + subjuntivo: nada que me asuste.",
      "grammarTopic": "relativos"
    },
    {
      "type": "translation",
      "question": "Это дом, где я вырос.",
      "instruction": "Переведите на испанский",
      "answer": "Es la casa donde crecí",
      "acceptableAnswers": [
        "Esta es la casa donde crecí",
        "Ésta es la casa donde crecí",
        "Es la casa donde me crié",
        "Esta es la casa donde me crié",
        "La casa donde crecí",
        "Es la casa en la que crecí",
        "Esta es la casa en la que crecí",
        "Es la casa en donde crecí",
        "Es la casa donde crecí."
      ],
      "explanation": "Место → donde (или en la que): Es la casa donde crecí.",
      "grammarTopic": "relativos"
    },
    {
      "type": "translation",
      "question": "Книга, которую я прочитал, интересная.",
      "instruction": "Переведите на испанский",
      "answer": "El libro que leí es interesante",
      "acceptableAnswers": [
        "El libro que leí es interesante.",
        "El libro que he leído es interesante",
        "El libro que yo leí es interesante"
      ],
      "explanation": "Для вещи без предлога — que: el libro que leí.",
      "grammarTopic": "relativos"
    },
    {
      "type": "translation",
      "question": "То, что ты сказал, правда.",
      "instruction": "Переведите на испанский",
      "answer": "Lo que dijiste es verdad",
      "acceptableAnswers": [
        "Lo que dijiste es verdad.",
        "Lo que has dicho es verdad",
        "Lo que tú dijiste es verdad"
      ],
      "explanation": "«То, что» → lo que.",
      "grammarTopic": "relativos"
    },
    {
      "type": "translation",
      "question": "Ищу место, где было бы тихо.",
      "instruction": "Переведите на испанский",
      "answer": "Busco un sitio donde haya silencio",
      "acceptableAnswers": [
        "Busco un sitio donde haya silencio.",
        "Busco un lugar donde haya silencio",
        "Busco un sitio donde esté en silencio",
        "Busco un sitio en el que haya silencio"
      ],
      "explanation": "После donde в значении «такой, где бы…» часто subjuntivo: donde haya.",
      "grammarTopic": "relativos"
    },
    {
      "type": "error_correction",
      "question": "La que me gusta es la libertad.",
      "instruction": "Исправьте ошибку",
      "answer": "Lo que me gusta es la libertad.",
      "acceptableAnswers": ["Lo que me gusta es la libertad"],
      "explanation": "Абстрактное «то, что» — lo que, не la que.",
      "grammarTopic": "relativos"
    },
    {
      "type": "error_correction",
      "question": "El tema de que hablamos es difícil.",
      "instruction": "Исправьте ошибку",
      "answer": "El tema del que hablamos es difícil.",
      "acceptableAnswers": [
        "El tema del que hablamos es difícil"
      ],
      "explanation": "После de: del que / de la que (с артиклем).",
      "grammarTopic": "relativos"
    },
    {
      "type": "error_correction",
      "question": "Es el chico cual padre es médico.",
      "instruction": "Исправьте ошибку",
      "answer": "Es el chico cuyo padre es médico.",
      "acceptableAnswers": ["Es el chico cuyo padre es médico"],
      "explanation": "«Чей» → cuyo (не cual).",
      "grammarTopic": "relativos"
    },
    {
      "type": "error_correction",
      "question": "La persona que escribí no respondió.",
      "instruction": "Исправьте ошибку",
      "answer": "La persona a quien escribí no respondió.",
      "acceptableAnswers": [
        "La persona a quien escribí no respondió",
        "La persona a la que escribí no respondió"
      ],
      "explanation": "Писать кому-то → a quien / a la que.",
      "grammarTopic": "relativos"
    },
    {
      "type": "sentence_building",
      "question": "El / libro / que / leí / es / interesante",
      "options": ["El", "libro", "que", "leí", "es", "interesante"],
      "answer": "El libro que leí es interesante",
      "instruction": "Составьте предложение из слов",
      "explanation": "El libro que leí — «книга, которую я прочитал».",
      "grammarTopic": "relativos"
    },
    {
      "type": "sentence_building",
      "question": "Lo / que / dijiste / es / verdad",
      "options": ["Lo", "que", "dijiste", "es", "verdad"],
      "answer": "Lo que dijiste es verdad",
      "instruction": "Составьте предложение из слов",
      "explanation": "Lo que = «то, что».",
      "grammarTopic": "relativos"
    },
    {
      "type": "sentence_building",
      "question": "Busco / un / sitio / donde / haya / silencio",
      "options": ["Busco", "un", "sitio", "donde", "haya", "silencio"],
      "answer": "Busco un sitio donde haya silencio",
      "instruction": "Составьте предложение из слов",
      "explanation": "Donde + subjuntivo: donde haya silencio.",
      "grammarTopic": "relativos"
    },
    {
      "type": "sentence_building",
      "question": "Mi / hermano / cuya / novia / es / médica / vive / aquí",
      "options": ["Mi", "hermano", "cuya", "novia", "es", "médica", "vive", "aquí"],
      "answer": "Mi hermano cuya novia es médica vive aquí",
      "instruction": "Составьте предложение из слов",
      "explanation": "Cuya согласуется с novia (ж.р.).",
      "grammarTopic": "relativos"
    }
  ],

  "chapter-34-pluscuamperfecto": [
    {
      "type": "multiple_choice",
      "question": "Cuando llegué, ya ___ (comer).",
      "instruction": "Выберите правильный вариант",
      "options": [
        "había comido",
        "he comido",
        "comí",
        "comía"
      ],
      "answer": "había comido",
      "explanation": "Действие раньше другого в прошлом → había + participio.",
      "grammarTopic": "pluscuamperfecto"
    },
    {
      "type": "fill_blank",
      "question": "Ya ___ (salir) cuando llamaste.",
      "instruction": "Salir → participio",
      "answer": "había salido",
      "acceptableAnswers": [
        "Había salido"
      ],
      "explanation": "Salir → salido: había salido.",
      "grammarTopic": "pluscuamperfecto"
    },
    {
      "type": "translation",
      "question": "Она уже прочитала книгу, когда я пришёл.",
      "instruction": "Переведите предложение",
      "answer": "Ya había leído el libro cuando llegué",
      "acceptableAnswers": [
        "ya había leído el libro cuando llegué"
      ],
      "explanation": "Había leído — «уже прочитала (до того)».",
      "grammarTopic": "pluscuamperfecto"
    },
    {
      "type": "error_correction",
      "question": "Cuando llegué, ya he comido.",
      "instruction": "Исправьте время",
      "answer": "Cuando llegué, ya había comido.",
      "acceptableAnswers": [
        "Cuando llegué, ya había comido"
      ],
      "explanation": "Оба события в прошлом → pluscuamperfecto, не perfecto.",
      "grammarTopic": "pluscuamperfecto"
    },
    {
      "type": "multiple_choice",
      "question": "Pluscuamperfecto = ___ + participio",
      "instruction": "Формула",
      "options": [
        "había/habías/había…",
        "he/has/ha…",
        "hube/hubiste…",
        "habré/habrás…"
      ],
      "answer": "había/habías/había…",
      "explanation": "Imperfecto de haber + participio.",
      "grammarTopic": "pluscuamperfecto"
    },
    {
      "type": "fill_blank",
      "question": "Nunca ___ (ver) esa película antes de ayer.",
      "instruction": "Ver → participio",
      "answer": "había visto",
      "acceptableAnswers": [
        "Había visto"
      ],
      "explanation": "Ver → visto: había visto.",
      "grammarTopic": "pluscuamperfecto"
    }
  ],

  "chapter-35-subjuntivo-imperfecto": [
    {
      "type": "multiple_choice",
      "question": "Si ___ (tener) dinero, viajaría.",
      "instruction": "Выберите правильный вариант",
      "options": [
        "tuviera",
        "tengo",
        "tendré",
        "tuve"
      ],
      "answer": "tuviera",
      "explanation": "Si + subj. imperf. + condicional: нереальное условие.",
      "grammarTopic": "subjuntivo-imperfecto"
    },
    {
      "type": "fill_blank",
      "question": "Quería que ___ (venir) a la fiesta.",
      "instruction": "Venir → subjuntivo",
      "answer": "vinieras",
      "acceptableAnswers": [
        "Vinieras",
        "viniese"
      ],
      "explanation": "Quería que + subjuntivo: vinieras/viniese.",
      "grammarTopic": "subjuntivo-imperfecto"
    },
    {
      "type": "translation",
      "question": "Если бы я знал, я бы позвонил.",
      "instruction": "Si + subj. + condicional",
      "answer": "Si lo supiera, llamaría",
      "acceptableAnswers": [
        "si lo supiera, llamaría"
      ],
      "explanation": "Si lo supiera, llamaría — классическая пара.",
      "grammarTopic": "subjuntivo-imperfecto"
    },
    {
      "type": "error_correction",
      "question": "Si tengo tiempo, iría.",
      "instruction": "Исправьте si-клаузу",
      "answer": "Si tuviera tiempo, iría.",
      "acceptableAnswers": [
        "Si tuviera tiempo, iría"
      ],
      "explanation": "Нереальное условие → subjuntivo imperfecto.",
      "grammarTopic": "subjuntivo-imperfecto"
    },
    {
      "type": "multiple_choice",
      "question": "Ojalá ___ (lluvia) mañana.",
      "instruction": "Ojalá + subjuntivo",
      "options": [
        "llueva",
        "llueve",
        "llovió",
        "lloverá"
      ],
      "answer": "llueva",
      "explanation": "Ojalá + subjuntivo (presente или imperfecto).",
      "grammarTopic": "subjuntivo-imperfecto"
    },
    {
      "type": "fill_blank",
      "question": "Si ___ (ser) más joven, correría más.",
      "instruction": "Заполните пропуск",
      "answer": "fuera",
      "acceptableAnswers": [
        "Fuera",
        "fuese"
      ],
      "explanation": "Ser → fuera/fuese en subjuntivo imperfecto.",
      "grammarTopic": "subjuntivo-imperfecto"
    }
  ],

  "chapter-36-pronombres-objetos": [
    {
      "type": "multiple_choice",
      "question": "¿Ves el libro? — Sí, ___ veo.",
      "instruction": "Выберите правильный вариант",
      "options": [
        "lo",
        "le",
        "se",
        "la"
      ],
      "answer": "lo",
      "explanation": "El libro (м.р.) → lo veo.",
      "grammarTopic": "pronombres-objetos"
    },
    {
      "type": "fill_blank",
      "question": "Le doy el regalo → ___ doy el regalo.",
      "instruction": "Замените le + OD",
      "answer": "Se lo",
      "acceptableAnswers": [
        "se lo",
        "Se lo doy"
      ],
      "explanation": "Le + lo → se lo (не le lo).",
      "grammarTopic": "pronombres-objetos"
    },
    {
      "type": "translation",
      "question": "Я её вижу каждый день.",
      "instruction": "Переведите предложение",
      "answer": "La veo cada día",
      "acceptableAnswers": [
        "la veo cada día"
      ],
      "explanation": "La = её (прямое дополнение).",
      "grammarTopic": "pronombres-objetos"
    },
    {
      "type": "error_correction",
      "question": "Le lo digo la verdad.",
      "instruction": "Исправьте местоимения",
      "answer": "Se lo digo.",
      "acceptableAnswers": [
        "Se lo digo",
        "Se lo digo la verdad."
      ],
      "explanation": "Le lo → se lo.",
      "grammarTopic": "pronombres-objetos"
    },
    {
      "type": "multiple_choice",
      "question": "¿___ escribes a María?",
      "instruction": "Выберите правильный вариант",
      "options": [
        "Le",
        "Lo",
        "La",
        "Se"
      ],
      "answer": "Le",
      "explanation": "A María → le escribes (косвенное).",
      "grammarTopic": "pronombres-objetos"
    },
    {
      "type": "fill_blank",
      "question": "No ___ (entender) — habla más despacio.",
      "instruction": "Заполните пропуск",
      "answer": "lo",
      "acceptableAnswers": [
        "Lo"
      ],
      "explanation": "No lo entiendo — «не понимаю (это)».",
      "grammarTopic": "pronombres-objetos"
    }
  ],

  "chapter-37-adverbios": [
    {
      "type": "multiple_choice",
      "question": "Habla muy ___.",
      "instruction": "Muy + adjetivo",
      "options": [
        "rápido",
        "rápidamente",
        "mucho",
        "muy"
      ],
      "answer": "rápido",
      "explanation": "Muy + прилагательное (rápido), не наречие.",
      "grammarTopic": "adverbios"
    },
    {
      "type": "fill_blank",
      "question": "Corre ___ (lento).",
      "instruction": "-mente от lento",
      "answer": "lentamente",
      "acceptableAnswers": [
        "Lentamente"
      ],
      "explanation": "Lento → lentamente (-mente).",
      "grammarTopic": "adverbios"
    },
    {
      "type": "multiple_choice",
      "question": "Quizás ___ (llover) mañana.",
      "instruction": "Quizás + subjuntivo",
      "options": [
        "llueva",
        "llueve",
        "llovió",
        "lloverá"
      ],
      "answer": "llueva",
      "explanation": "Quizás + subjuntivo.",
      "grammarTopic": "adverbios"
    },
    {
      "type": "translation",
      "question": "Он работает много.",
      "instruction": "Mucho + глагол",
      "answer": "Trabaja mucho",
      "acceptableAnswers": [
        "trabaja mucho"
      ],
      "explanation": "Mucho с глаголом — «много (делает)».",
      "grammarTopic": "adverbios"
    },
    {
      "type": "sentence_building",
      "question": "Es / una / persona / muy / amable",
      "options": [
        "Es",
        "una",
        "persona",
        "muy",
        "amable"
      ],
      "answer": "Es una persona muy amable",
      "instruction": "Соберите фразу с muy",
      "explanation": "Muy amable — «очень добрый».",
      "grammarTopic": "adverbios"
    },
    {
      "type": "fill_blank",
      "question": "___ (probable) llegará tarde.",
      "instruction": "Заполните пропуск наречием",
      "answer": "Probablemente",
      "acceptableAnswers": [
        "probablemente"
      ],
      "explanation": "Probable → probablemente.",
      "grammarTopic": "adverbios"
    }
  ],

  "chapter-38-subjuntivo-compuestos": [
    {
      "type": "multiple_choice",
      "question": "Es posible que ya ___ (terminar).",
      "instruction": "Выберите правильный вариант",
      "options": [
        "haya terminado",
        "hube terminado",
        "terminara",
        "terminó"
      ],
      "answer": "haya terminado",
      "explanation": "Es posible que + presente de subj. compuesto.",
      "grammarTopic": "subjuntivo-compuestos"
    },
    {
      "type": "fill_blank",
      "question": "Si ___ (haber + ir), no estaríamos aquí.",
      "instruction": "Plusc. de subj.",
      "answer": "hubiera ido",
      "acceptableAnswers": [
        "Hubiera ido",
        "hubiese ido"
      ],
      "explanation": "Si hubiera ido — нереальное в прошлом.",
      "grammarTopic": "subjuntivo-compuestos"
    },
    {
      "type": "translation",
      "question": "Сомневаюсь, что он уже приехал.",
      "instruction": "Subj. compuesto",
      "answer": "Dudo que haya llegado",
      "acceptableAnswers": [
        "dudo que haya llegado"
      ],
      "explanation": "Dudo que + haya + participio.",
      "grammarTopic": "subjuntivo-compuestos"
    },
    {
      "type": "error_correction",
      "question": "Es posible que ya terminó.",
      "instruction": "После es posible que",
      "answer": "Es posible que ya haya terminado.",
      "acceptableAnswers": [
        "Es posible que ya haya terminado"
      ],
      "explanation": "Триггер subjuntivo → haya terminado.",
      "grammarTopic": "subjuntivo-compuestos"
    },
    {
      "type": "multiple_choice",
      "question": "Subjuntivo compuesto = ___ + participio",
      "instruction": "Формула",
      "options": [
        "haya/hayas…",
        "había/habías…",
        "he/has…",
        "hubo/hubiste…"
      ],
      "answer": "haya/hayas…",
      "explanation": "Presente de subjuntivo de haber + participio.",
      "grammarTopic": "subjuntivo-compuestos"
    },
    {
      "type": "fill_blank",
      "question": "Ojalá ___ (haber + ver) la exposición.",
      "instruction": "Subj. pluscuamperfecto",
      "answer": "hubiera visto",
      "acceptableAnswers": [
        "Hubiera visto",
        "hubiese visto"
      ],
      "explanation": "Ojalá hubiera visto — сожаление о прошлом.",
      "grammarTopic": "subjuntivo-compuestos"
    }
  ],

  "chapter-39-condicionales-compuestos": [
    {
      "type": "multiple_choice",
      "question": "Si hubiera sabido, ___ (ir).",
      "instruction": "Выберите правильный вариант",
      "options": [
        "habría ido",
        "iría",
        "fui",
        "haya ido"
      ],
      "answer": "habría ido",
      "explanation": "Si hubiera + condicional compuesto — прошлое, которое не случилось.",
      "grammarTopic": "condicionales-compuestos"
    },
    {
      "type": "fill_blank",
      "question": "___ (haber + estudiar) más, habría aprobado.",
      "instruction": "Si + pluscuam. + cond. comp.",
      "answer": "Si hubiera estudiado",
      "acceptableAnswers": [
        "Si hubiera estudiado",
        "Si hubiese estudiado"
      ],
      "explanation": "Si hubiera estudiado, habría aprobado.",
      "grammarTopic": "condicionales-compuestos"
    },
    {
      "type": "translation",
      "question": "Если бы ты позвонил, я бы приехал.",
      "instruction": "Переведите предложение",
      "answer": "Si llamaras, vendría",
      "acceptableAnswers": [
        "si llamaras, vendría",
        "Si llamases, vendría"
      ],
      "explanation": "Si + imperf. subj. + condicional.",
      "grammarTopic": "condicionales-compuestos"
    },
    {
      "type": "error_correction",
      "question": "Si hubiera sabido, iría.",
      "instruction": "Согласуйте времена",
      "answer": "Si hubiera sabido, habría ido.",
      "acceptableAnswers": [
        "Si hubiera sabido, habría ido"
      ],
      "explanation": "Hubiera → habría (cond. compuesto).",
      "grammarTopic": "condicionales-compuestos"
    },
    {
      "type": "multiple_choice",
      "question": "Si llueve, ___ en casa.",
      "instruction": "Si real",
      "options": [
        "me quedo",
        "me quedaría",
        "me hubiera quedado",
        "me quedara"
      ],
      "answer": "me quedo",
      "explanation": "Реальное условие → indicativo presente.",
      "grammarTopic": "condicionales-compuestos"
    },
    {
      "type": "fill_blank",
      "question": "Habríamos ganado si ___ (haber + jugar) mejor.",
      "instruction": "Cond. compuesto",
      "answer": "hubiéramos jugado",
      "acceptableAnswers": [
        "Hubiéramos jugado",
        "hubiésemos jugado"
      ],
      "explanation": "Si hubiéramos jugado…",
      "grammarTopic": "condicionales-compuestos"
    }
  ],

  "chapter-40-relativos-avanzado": [
    {
      "type": "multiple_choice",
      "question": "La propuesta, ___ firmó el director, es clara.",
      "instruction": "El cual",
      "options": [
        "la cual",
        "que",
        "donde",
        "cuyo"
      ],
      "answer": "la cual",
      "explanation": "El/la cual — формальное относительное.",
      "grammarTopic": "relativos-avanzado"
    },
    {
      "type": "fill_blank",
      "question": "La ciudad ___ nací es pequeña.",
      "instruction": "Adonde / donde",
      "answer": "donde",
      "acceptableAnswers": [
        "Donde",
        "adonde"
      ],
      "explanation": "Donde/adonde nací — место рождения.",
      "grammarTopic": "relativos-avanzado"
    },
    {
      "type": "translation",
      "question": "То, что сказал преподаватель, важно.",
      "instruction": "Переведите на испанский (lo que)",
      "answer": "Lo que dijo el profesor es importante",
      "acceptableAnswers": [
        "lo que dijo el profesor es importante",
        "Lo que dijo el profesor es importante.",
        "Lo que el profesor dijo es importante",
        "lo que el profesor dijo es importante"
      ],
      "explanation": "Lo que = «то, что». Образец: Lo que dijo el profesor es importante.",
      "grammarTopic": "relativos-avanzado"
    },
    {
      "type": "sentence_building",
      "question": "El / informe / del / cual / hablamos / es / largo",
      "options": [
        "El",
        "informe",
        "del",
        "cual",
        "hablamos",
        "es",
        "largo"
      ],
      "answer": "El informe del cual hablamos es largo",
      "instruction": "Соберите с del cual",
      "explanation": "Del cual — формальная связка.",
      "grammarTopic": "relativos-avanzado"
    },
    {
      "type": "multiple_choice",
      "question": "«El cual» чаще в…",
      "instruction": "Регистр",
      "options": [
        "формальном тексте",
        "SMS",
        "детской речи",
        "слэнге"
      ],
      "answer": "формальном тексте",
      "explanation": "El cual — письменный/формальный стиль.",
      "grammarTopic": "relativos-avanzado"
    },
    {
      "type": "fill_blank",
      "question": "No entendí ___ dijiste.",
      "instruction": "Lo que",
      "answer": "lo que",
      "acceptableAnswers": [
        "Lo que"
      ],
      "explanation": "Lo que dijiste — «то, что ты сказал».",
      "grammarTopic": "relativos-avanzado"
    }
  ],

  "chapter-41-conectores-discursivos": [
    {
      "type": "multiple_choice",
      "question": "Estudio mucho; ___, apruebo.",
      "instruction": "Причина → следствие",
      "options": [
        "por consiguiente",
        "sin embargo",
        "aunque",
        "mientras"
      ],
      "answer": "por consiguiente",
      "explanation": "Por consiguiente — «следовательно».",
      "grammarTopic": "conectores"
    },
    {
      "type": "fill_blank",
      "question": "___, no estoy de acuerdo.",
      "instruction": "Противопоставление",
      "answer": "Sin embargo",
      "acceptableAnswers": [
        "sin embargo",
        "No obstante"
      ],
      "explanation": "Sin embargo / no obstante — «однако».",
      "grammarTopic": "conectores"
    },
    {
      "type": "multiple_choice",
      "question": "___ lugar, debemos definir el problema.",
      "instruction": "Структура текста",
      "options": [
        "En primer",
        "En definitiva",
        "Por tanto",
        "A pesar de"
      ],
      "answer": "En primer",
      "explanation": "En primer lugar — первый пункт.",
      "grammarTopic": "conectores"
    },
    {
      "type": "translation",
      "question": "В итоге, решение было правильным.",
      "instruction": "En definitiva / en suma",
      "answer": "En definitiva, la decisión fue correcta",
      "acceptableAnswers": [
        "en definitiva, la decisión fue correcta",
        "En suma, la decisión fue correcta"
      ],
      "explanation": "En definitiva — «в итоге».",
      "grammarTopic": "conectores"
    },
    {
      "type": "sentence_building",
      "question": "No / obstante / / el / plan / es / viable",
      "options": [
        "No",
        "obstante",
        ",",
        "el",
        "plan",
        "es",
        "viable"
      ],
      "answer": "No obstante, el plan es viable",
      "instruction": "Соберите с no obstante",
      "explanation": "No obstante + запятая.",
      "grammarTopic": "conectores"
    },
    {
      "type": "fill_blank",
      "question": "___ de todo, gracias por venir.",
      "instruction": "Начало речи",
      "answer": "Ante",
      "acceptableAnswers": [
        "Ante"
      ],
      "explanation": "Ante todo — «прежде всего».",
      "grammarTopic": "conectores"
    }
  ],

  "chapter-42-subjuntivo-avanzado": [
    {
      "type": "multiple_choice",
      "question": "Aunque ___ (llover), salimos.",
      "instruction": "Известный факт",
      "options": [
        "llueve",
        "llueva",
        "llovió",
        "lloviera"
      ],
      "answer": "llueve",
      "explanation": "Aunque + indicativo — известный/реальный факт.",
      "grammarTopic": "subjuntivo-avanzado"
    },
    {
      "type": "fill_blank",
      "question": "Aunque ___ (tener) dinero, no lo haría.",
      "instruction": "Гипотеза",
      "answer": "tuviera",
      "acceptableAnswers": [
        "Tuviera",
        "tuviese"
      ],
      "explanation": "Aunque + subjuntivo — гипотетическое уступление.",
      "grammarTopic": "subjuntivo-avanzado"
    },
    {
      "type": "error_correction",
      "question": "Busco un sitio donde hay silencio.",
      "instruction": "Найдите и исправьте ошибку",
      "answer": "Busco un sitio donde haya silencio.",
      "acceptableAnswers": [
        "Busco un sitio donde haya silencio"
      ],
      "explanation": "Antecedente no definido → subjuntivo.",
      "grammarTopic": "subjuntivo-avanzado"
    },
    {
      "type": "translation",
      "question": "Как ни странно, он согласился.",
      "instruction": "Por + adj + que + subj.",
      "answer": "Por extraño que parezca, aceptó",
      "acceptableAnswers": [
        "por extraño que parezca, aceptó"
      ],
      "explanation": "Por extraño que parezca + subjuntivo.",
      "grammarTopic": "subjuntivo-avanzado"
    },
    {
      "type": "multiple_choice",
      "question": "Hazlo como ___ (decir).",
      "instruction": "Como + indicativo",
      "options": [
        "digo",
        "diga",
        "dijera",
        "diré"
      ],
      "answer": "digo",
      "explanation": "Como + indicativo — «как я говорю» (способ).",
      "grammarTopic": "subjuntivo-avanzado"
    },
    {
      "type": "fill_blank",
      "question": "Donde ___ (haber) humo, hay fuego.",
      "instruction": "Пословица",
      "answer": "hay",
      "acceptableAnswers": [
        "Hay"
      ],
      "explanation": "Donde hay — indicativo (общая истина).",
      "grammarTopic": "subjuntivo-avanzado"
    },
    {
      "type": "sentence_building",
      "question": "Busco / un / sitio / donde / haya / silencio",
      "instruction": "Составьте предложение с subjuntivo (antecedente no definido)",
      "options": ["Busco", "un", "sitio", "donde", "haya", "silencio"],
      "answer": "Busco un sitio donde haya silencio",
      "explanation": "Busco un sitio donde haya… — место ещё не найдено → subjuntivo.",
      "grammarTopic": "subjuntivo-avanzado"
    },
    {
      "type": "sentence_building",
      "question": "Por / extraño / que / parezca / aceptó",
      "instruction": "Составьте конструкцию por + adj + que + subj.",
      "options": ["Por", "extraño", "que", "parezca", "aceptó"],
      "answer": "Por extraño que parezca, aceptó",
      "explanation": "Por extraño que parezca — уступительная конструкция с subjuntivo.",
      "grammarTopic": "subjuntivo-avanzado"
    },
    {
      "type": "sentence_building",
      "question": "Aunque / llueva / mañana / saldremos / igual",
      "instruction": "Составьте гипотетическое уступление",
      "options": ["Aunque", "llueva", "mañana", "saldremos", "igual"],
      "answer": "Aunque llueva mañana, saldremos igual",
      "explanation": "Aunque + subjuntivo — гипотетическое «даже если».",
      "grammarTopic": "subjuntivo-avanzado"
    },
    {
      "type": "sentence_building",
      "question": "Hazlo / como / te / lo / expliqué",
      "instruction": "Составьте предложение: como + indicativo (способ)",
      "options": ["Hazlo", "como", "te", "lo", "expliqué"],
      "answer": "Hazlo como te lo expliqué",
      "explanation": "Como te lo expliqué — indicativo: «как я объяснил».",
      "grammarTopic": "subjuntivo-avanzado"
    },
    {
      "type": "sentence_building",
      "question": "Donde / haya / voluntad / hay / camino",
      "instruction": "Составьте пословицу с subjuntivo",
      "options": ["Donde", "haya", "voluntad", "hay", "camino"],
      "answer": "Donde haya voluntad, hay camino",
      "explanation": "Donde haya… — общая истина с subjuntivo в придаточном.",
      "grammarTopic": "subjuntivo-avanzado"
    }
  ],

  "chapter-43-indirecto-avanzado": [
    {
      "type": "multiple_choice",
      "question": "Dijo: «Vengo mañana» → Dijo que ___ al día siguiente.",
      "instruction": "Сдвиг указателя",
      "options": [
        "vendría",
        "viene",
        "vino",
        "venga"
      ],
      "answer": "vendría",
      "explanation": "Mañana → al día siguiente + condicional.",
      "grammarTopic": "indirecto-avanzado"
    },
    {
      "type": "fill_blank",
      "question": "Dijo: «Estoy aquí» → Dijo que ___ allí.",
      "instruction": "Está → estaba",
      "answer": "estaba",
      "acceptableAnswers": [
        "Estaba"
      ],
      "explanation": "Presente → imperfecto en estilo indirecto.",
      "grammarTopic": "indirecto-avanzado"
    },
    {
      "type": "translation",
      "question": "Он сказал, что уже поел.",
      "instruction": "Plusc. en indirecto",
      "answer": "Dijo que ya había comido",
      "acceptableAnswers": [
        "dijo que ya había comido"
      ],
      "explanation": "Perfecto → pluscuamperfecto.",
      "grammarTopic": "indirecto-avanzado"
    },
    {
      "type": "error_correction",
      "question": "Dijo que viene mañana.",
      "instruction": "Исправьте сдвиг",
      "answer": "Dijo que vendría al día siguiente.",
      "acceptableAnswers": [
        "Dijo que vendría al día siguiente"
      ],
      "explanation": "После dijo — сдвиг времён и указателей.",
      "grammarTopic": "indirecto-avanzado"
    },
    {
      "type": "multiple_choice",
      "question": "Pidió que ___ (callar).",
      "instruction": "Выберите правильный вариант",
      "options": [
        "callara",
        "calló",
        "calla",
        "callaría"
      ],
      "answer": "callara",
      "explanation": "Pedir que + subjuntivo.",
      "grammarTopic": "indirecto-avanzado"
    },
    {
      "type": "fill_blank",
      "question": "«Hoy no puedo» → Dijo que ___ aquel día no podía.",
      "instruction": "Hoy → aquel día",
      "answer": "aquel",
      "acceptableAnswers": [
        "Aquel"
      ],
      "explanation": "Hoy → aquel día en estilo indirecto.",
      "grammarTopic": "indirecto-avanzado"
    },
    {
      "type": "sentence_building",
      "question": "Dijo / que / vendría / al / día / siguiente",
      "instruction": "Составьте estilo indirecto со сдвигом времени",
      "options": ["Dijo", "que", "vendría", "al", "día", "siguiente"],
      "answer": "Dijo que vendría al día siguiente",
      "explanation": "Mañana → al día siguiente; futuro → condicional.",
      "grammarTopic": "indirecto-avanzado"
    },
    {
      "type": "sentence_building",
      "question": "Me / pidió / que / no / lo / contara / a / nadie",
      "instruction": "Составьте косвенную речь с subjuntivo",
      "options": ["Me", "pidió", "que", "no", "lo", "contara", "a", "nadie"],
      "answer": "Me pidió que no lo contara a nadie",
      "explanation": "Pedir que + imperfecto de subjuntivo en estilo indirecto.",
      "grammarTopic": "indirecto-avanzado"
    },
    {
      "type": "sentence_building",
      "question": "Afirmó / que / ya / había / terminado / el / trabajo",
      "instruction": "Составьте pluscuamperfecto en indirecto",
      "options": ["Afirmó", "que", "ya", "había", "terminado", "el", "trabajo"],
      "answer": "Afirmó que ya había terminado el trabajo",
      "explanation": "Pretérito perfecto → pluscuamperfecto en estilo indirecto.",
      "grammarTopic": "indirecto-avanzado"
    },
    {
      "type": "sentence_building",
      "question": "Le / dijo / que / aquel / día / no / podía / venir",
      "instruction": "Составьте сдвиг указателя hoy → aquel día",
      "options": ["Le", "dijo", "que", "aquel", "día", "no", "podía", "venir"],
      "answer": "Le dijo que aquel día no podía venir",
      "explanation": "Hoy → aquel día; presente → imperfecto.",
      "grammarTopic": "indirecto-avanzado"
    },
    {
      "type": "sentence_building",
      "question": "Quería / saber / si / ya / habíamos / reservado",
      "instruction": "Составьте вопрос в estilo indirecto",
      "options": ["Quería", "saber", "si", "ya", "habíamos", "reservado"],
      "answer": "Quería saber si ya habíamos reservado",
      "explanation": "¿Ya habéis reservado? → si + pluscuamperfecto.",
      "grammarTopic": "indirecto-avanzado"
    }
  ],

  "chapter-44-pronombres-avanzado": [
    {
      "type": "multiple_choice",
      "question": "___ bueno es que llegaste.",
      "instruction": "Lo + adjetivo",
      "options": [
        "Lo",
        "El",
        "La",
        "Le"
      ],
      "answer": "Lo",
      "explanation": "Lo bueno = «хорошая сторона / то хорошее, что…».",
      "grammarTopic": "pronombres-avanzado"
    },
    {
      "type": "fill_blank",
      "question": "A María ___ veo cada día.",
      "instruction": "Заполните пропуск",
      "answer": "la",
      "acceptableAnswers": [
        "La"
      ],
      "explanation": "A María la veo — ударение на OD.",
      "grammarTopic": "pronombres-avanzado"
    },
    {
      "type": "translation",
      "question": "Самое сложное — начать.",
      "instruction": "Lo + adjetivo",
      "answer": "Lo difícil es empezar",
      "acceptableAnswers": [
        "lo difícil es empezar"
      ],
      "explanation": "Lo difícil es… — «самое сложное — …».",
      "grammarTopic": "pronombres-avanzado"
    },
    {
      "type": "error_correction",
      "question": "A la ciudad le visitamos.",
      "instruction": "Laísmo",
      "answer": "Visitamos la ciudad.",
      "acceptableAnswers": [
        "Visitamos la ciudad",
        "La visitamos."
      ],
      "explanation": "Visitar — прямое дополнение → la, не le.",
      "grammarTopic": "pronombres-avanzado"
    },
    {
      "type": "multiple_choice",
      "question": "Leísmo — это…",
      "instruction": "Региональная особенность",
      "options": [
        "le вместо lo для OD",
        "lo вместо le",
        "se вместо le",
        "удвоение местоимений"
      ],
      "answer": "le вместо lo для OD",
      "explanation": "Leísmo: le vi вместо lo vi (в некоторых регионах).",
      "grammarTopic": "pronombres-avanzado"
    },
    {
      "type": "fill_blank",
      "question": "___ importante es participar.",
      "instruction": "Lo + adj.",
      "answer": "Lo",
      "acceptableAnswers": [
        "lo"
      ],
      "explanation": "Lo importante es…",
      "grammarTopic": "pronombres-avanzado"
    },
    {
      "type": "sentence_building",
      "question": "Lo / difícil / es / empezar / a / tiempo",
      "instruction": "Составьте конструкцию lo + adjetivo",
      "options": ["Lo", "difícil", "es", "empezar", "a", "tiempo"],
      "answer": "Lo difícil es empezar a tiempo",
      "explanation": "Lo difícil es… — «самое сложное — …».",
      "grammarTopic": "pronombres-avanzado"
    },
    {
      "type": "sentence_building",
      "question": "A / María / la / vi / en / la / conferencia",
      "instruction": "Составьте предложение с ударением на OD",
      "options": ["A", "María", "la", "vi", "en", "la", "conferencia"],
      "answer": "A María la vi en la conferencia",
      "explanation": "A María la vi — местоимение перед глаголом, a + имя.",
      "grammarTopic": "pronombres-avanzado"
    },
    {
      "type": "sentence_building",
      "question": "Lo / que / más / me / gusta / es / viajar",
      "instruction": "Составьте конструкцию lo que… es…",
      "options": ["Lo", "que", "más", "me", "gusta", "es", "viajar"],
      "answer": "Lo que más me gusta es viajar",
      "explanation": "Lo que más me gusta es… — «то, что мне больше всего нравится — …».",
      "grammarTopic": "pronombres-avanzado"
    },
    {
      "type": "sentence_building",
      "question": "Lo / bueno / de / todo / es / que / aprendimos",
      "instruction": "Составьте lo bueno de todo es que…",
      "options": ["Lo", "bueno", "de", "todo", "es", "que", "aprendimos"],
      "answer": "Lo bueno de todo es que aprendimos",
      "explanation": "Lo bueno de todo es que… — «хорошая сторона всего в том, что…».",
      "grammarTopic": "pronombres-avanzado"
    },
    {
      "type": "sentence_building",
      "question": "No / se / lo / dije / porque / no / estaba",
      "instruction": "Составьте предложение с двойным местоимением",
      "options": ["No", "se", "lo", "dije", "porque", "no", "estaba"],
      "answer": "No se lo dije porque no estaba",
      "explanation": "Se lo dije — IO (se) + OD (lo) перед глаголом.",
      "grammarTopic": "pronombres-avanzado"
    }
  ],

  "chapter-45-ser-estar-matices": [
    {
      "type": "multiple_choice",
      "question": "Juan ___ listo (inteligente).",
      "instruction": "Выберите правильный вариант",
      "options": [
        "es",
        "está",
        "era",
        "estaba"
      ],
      "answer": "es",
      "explanation": "Es listo — умный по характеру (ser).",
      "grammarTopic": "ser-estar-avanzado"
    },
    {
      "type": "fill_blank",
      "question": "Juan ___ listo (preparado).",
      "instruction": "Заполните пропуск",
      "answer": "está",
      "acceptableAnswers": [
        "Está"
      ],
      "explanation": "Está listo — готов (estar).",
      "grammarTopic": "ser-estar-avanzado"
    },
    {
      "type": "translation",
      "question": "Она злая (характер).",
      "instruction": "Переведите предложение",
      "answer": "Es mala",
      "acceptableAnswers": [
        "es mala"
      ],
      "explanation": "Характер → ser: es mala.",
      "grammarTopic": "ser-estar-avanzado"
    },
    {
      "type": "error_correction",
      "question": "La sopa es fría — está fría (temp.).",
      "instruction": "Еда: ser/estar",
      "answer": "La sopa está fría.",
      "acceptableAnswers": [
        "La sopa está fría"
      ],
      "explanation": "Температура еды → está fría.",
      "grammarTopic": "ser-estar-avanzado"
    },
    {
      "type": "multiple_choice",
      "question": "Es aburrido vs Está aburrido — разница…",
      "instruction": "Пары ser/estar",
      "options": [
        "скучный vs скучает",
        "устал vs усталость",
        "высокий vs высоко",
        "богатый vs богат"
      ],
      "answer": "скучный vs скучает",
      "explanation": "Es aburrido — «он скучный»; está aburrido — «ему скучно».",
      "grammarTopic": "ser-estar-avanzado"
    },
    {
      "type": "fill_blank",
      "question": "La fiesta ___ divertida (в целом).",
      "instruction": "Заполните пропуск",
      "answer": "es",
      "acceptableAnswers": [
        "Es"
      ],
      "explanation": "Оценка события в целом → ser.",
      "grammarTopic": "ser-estar-avanzado"
    },
    {
      "type": "sentence_building",
      "question": "Juan / es / listo / pero / hoy / no / está / listo",
      "instruction": "Составьте пару ser/estar con listo",
      "options": ["Juan", "es", "listo", "pero", "hoy", "no", "está", "listo"],
      "answer": "Juan es listo pero hoy no está listo",
      "explanation": "Es listo (умный) vs está listo (готов) — разные значения.",
      "grammarTopic": "ser-estar-avanzado"
    },
    {
      "type": "sentence_building",
      "question": "La / sopa / está / fría / pero / el / plato / es / frío",
      "instruction": "Составьте контраст ser/estar с frío",
      "options": ["La", "sopa", "está", "fría", "pero", "el", "plato", "es", "frío"],
      "answer": "La sopa está fría pero el plato es frío",
      "explanation": "Está fría (температура) vs es frío (материал/на ощупь).",
      "grammarTopic": "ser-estar-avanzado"
    },
    {
      "type": "sentence_building",
      "question": "Es / aburrido / el / libro / pero / estoy / aburrido / ya",
      "instruction": "Составьте пару es/está aburrido",
      "options": ["Es", "aburrido", "el", "libro", "pero", "estoy", "aburrido", "ya"],
      "answer": "Es aburrido el libro pero estoy aburrido ya",
      "explanation": "Es aburrido (скучный) vs estoy aburrido (мне скучно).",
      "grammarTopic": "ser-estar-avanzado"
    },
    {
      "type": "sentence_building",
      "question": "El / examen / es / difícil / y / estoy / muy / nervioso",
      "instruction": "Составьте ser (характеристика) + estar (состояние)",
      "options": ["El", "examen", "es", "difícil", "y", "estoy", "muy", "nervioso"],
      "answer": "El examen es difícil y estoy muy nervioso",
      "explanation": "Es difícil (сложный) + estoy nervioso (волнуюсь).",
      "grammarTopic": "ser-estar-avanzado"
    },
    {
      "type": "sentence_building",
      "question": "Mi / abuela / es / viva / y / todavía / está / viva",
      "instruction": "Составьте пару ser/estar con vivo",
      "options": ["Mi", "abuela", "es", "viva", "y", "todavía", "está", "viva"],
      "answer": "Mi abuela es viva y todavía está viva",
      "explanation": "Es viva (живой характер) vs está viva (жива, не умерла).",
      "grammarTopic": "ser-estar-avanzado"
    }
  ],
};
