import type { GrammarLevel, StaticExercise } from "@/types";

// =====================================================================
// DELE exam exercise bank (Spanish course)
// ---------------------------------------------------------------------
// Ready-made exam-style items following the same schema as the chapter
// bank. Served by /api/exercises/generate when exam mode is on.
// Sessions are bank-only — no AI fill.
// =====================================================================

export type DeleExercise = StaticExercise & {
  level: GrammarLevel;
  /** DELE skill area, shown as the exercise topic. */
  deleTopic: string;
};

export const DELE_EXERCISES: DeleExercise[] = [
  // ----- multiple_choice ---------------------------------------------
  {
    id: "dele-mc-1",
    type: "multiple_choice",
    level: "B1",
    deleTopic: "DELE: Carta formal",
    question: "___ señores: Me dirijo a ustedes para solicitar información sobre el curso.",
    instruction: "Формальное обращение в письме DELE",
    options: ["Muy", "Queridos", "Hola", "Buenos"],
    answer: "Muy",
    explanation: "«Muy señores míos:» — классическое формальное обращение. Queridos — только для близких.",
  },
  {
    id: "dele-mc-2",
    type: "multiple_choice",
    level: "B1",
    deleTopic: "DELE: Contraste de pasados",
    question: "Cuando ___ pequeño, vivía en Sevilla.",
    instruction: "Фон в прошлом — какое время?",
    options: ["era", "fui", "he sido", "sería"],
    answer: "era",
    explanation: "Описание фона и характеристик в прошлом → imperfecto: era.",
  },
  {
    id: "dele-mc-3",
    type: "multiple_choice",
    level: "B1",
    deleTopic: "DELE: Contraste de pasados",
    question: "Ayer ___ una carta al ayuntamiento.",
    instruction: "Завершённое действие с ayer",
    options: ["escribí", "escribía", "he escrito", "escribo"],
    answer: "escribí",
    explanation: "Ayer — закрытый период → pretérito indefinido: escribí.",
  },
  {
    id: "dele-mc-4",
    type: "multiple_choice",
    level: "B2",
    deleTopic: "DELE: Conectores",
    question: "Los datos son claros; ___, muchos expertos no están de acuerdo.",
    instruction: "Противопоставление в эссе",
    options: ["sin embargo", "por lo tanto", "además", "es decir"],
    answer: "sin embargo",
    explanation: "Противопоставление → sin embargo. Por lo tanto — следствие, además — добавление.",
  },
  {
    id: "dele-mc-5",
    type: "multiple_choice",
    level: "B2",
    deleTopic: "DELE: Opinión",
    question: "No creo que esta medida ___ eficaz.",
    instruction: "Мнение с отрицанием — какое наклонение?",
    options: ["sea", "es", "será", "sería"],
    answer: "sea",
    explanation: "No creo que + subjuntivo: sea. Утвердительное creo que — с indicativo.",
  },
  {
    id: "dele-mc-6",
    type: "multiple_choice",
    level: "B2",
    deleTopic: "DELE: Conectores",
    question: "De ahí que el gobierno ___ tomar medidas urgentes.",
    instruction: "После de ahí que…",
    options: ["deba", "debe", "deberá", "debía"],
    answer: "deba",
    explanation: "De ahí que — всегда subjuntivo: deba. Частая ловушка на DELE B2.",
  },
  {
    id: "dele-mc-7",
    type: "multiple_choice",
    level: "C1",
    deleTopic: "DELE: Registro formal",
    question: "___ lo dispuesto en el contrato, la empresa abonará la cantidad acordada.",
    instruction: "Формальный коннектор (административный стиль)",
    options: ["Conforme a", "Según dice", "Como pone", "Igual que"],
    answer: "Conforme a",
    explanation: "«Conforme a lo dispuesto…» — формула административного регистра. Остальные варианты — разговорные.",
  },
  {
    id: "dele-mc-8",
    type: "multiple_choice",
    level: "C2",
    deleTopic: "DELE: Oraciones hendidas",
    question: "___ en 2010 cuando se aprobó la ley.",
    instruction: "Выделительная конструкция (oración hendida)",
    options: ["Fue", "Era", "Estuvo", "Ha sido"],
    answer: "Fue",
    explanation: "Клефт с обстоятельством времени: Fue en 2010 cuando… — ser в indefinido.",
  },
  {
    id: "dele-mc-9",
    type: "multiple_choice",
    level: "C2",
    deleTopic: "DELE: Conjetura",
    question: "— ¿Dónde está Marta? — No sé, ___ salido ya.",
    instruction: "Догадка о прошлом",
    options: ["habrá", "ha", "había", "hubo"],
    answer: "habrá",
    explanation: "Futuro perfecto для догадки о прошлом: habrá salido — «наверное, уже ушла».",
  },

  // ----- fill_blank ----------------------------------------------------
  {
    id: "dele-fb-1",
    type: "fill_blank",
    level: "B1",
    deleTopic: "DELE: Carta formal",
    question: "Le agradecería que me ___ (enviar) el programa del curso.",
    instruction: "Вежливая просьба в формальном письме",
    answer: "enviara",
    acceptableAnswers: ["enviase"],
    explanation: "Le agradecería que + subjuntivo imperfecto: enviara/enviase.",
  },
  {
    id: "dele-fb-2",
    type: "fill_blank",
    level: "B1",
    deleTopic: "DELE: Carta formal",
    question: "A la ___ de su respuesta, le saluda atentamente.",
    instruction: "Формула завершения письма",
    answer: "espera",
    explanation: "«A la espera de su respuesta…» — стандартная формула перед прощанием.",
  },
  {
    id: "dele-fb-3",
    type: "fill_blank",
    level: "B2",
    deleTopic: "DELE: Conectores",
    question: "No ___ estudió la carrera, sino que también hizo un máster.",
    instruction: "Конструкция no…, sino que…",
    answer: "solo",
    acceptableAnswers: ["sólo", "solamente"],
    explanation: "No solo…, sino (que) también… — «не только…, но и…».",
  },
  {
    id: "dele-fb-4",
    type: "fill_blank",
    level: "B2",
    deleTopic: "DELE: Opinión",
    question: "Es fundamental que las autoridades ___ (actuar) cuanto antes.",
    instruction: "Оценочная конструкция — наклонение?",
    answer: "actúen",
    acceptableAnswers: ["actuen"],
    explanation: "Es fundamental que + subjuntivo: actúen.",
  },
  {
    id: "dele-fb-5",
    type: "fill_blank",
    level: "C1",
    deleTopic: "DELE: Registro formal",
    question: "Adjunto ___ (remitir) el informe solicitado.",
    instruction: "Формула делового письма C1",
    answer: "remito",
    explanation: "«Adjunto remito…» — формальная формула «прилагаю/направляю».",
  },
  {
    id: "dele-fb-6",
    type: "fill_blank",
    level: "C2",
    deleTopic: "DELE: Conjetura",
    question: "___ las diez cuando terminó la reunión. (ser, conjetura)",
    instruction: "Догадка о времени в прошлом",
    answer: "Serían",
    acceptableAnswers: ["serían", "serian", "Serian"],
    explanation: "Condicional de conjetura о прошлом: Serían las diez — «было, наверное, часов десять».",
  },
  {
    id: "dele-fb-7",
    type: "fill_blank",
    level: "C2",
    deleTopic: "DELE: Oraciones hendidas",
    question: "Lo ___ me preocupa es la falta de tiempo.",
    instruction: "Выделение с lo…",
    answer: "que",
    explanation: "Lo que me preocupa es… — клефт-конструкция «то, что меня беспокоит…».",
  },

  // ----- translation (RU-authored; non-RU interfaces get AI items) -----
  {
    id: "dele-tr-1",
    type: "translation",
    level: "B1",
    deleTopic: "DELE: Carta formal",
    question: "Пишу Вам, чтобы попросить дополнительную информацию.",
    instruction: "Переведите формулу формального письма",
    answer: "Le escribo para pedir más información.",
    acceptableAnswers: [
      "Le escribo para pedir informacion adicional.",
      "Le escribo para solicitar más información.",
      "Me dirijo a usted para pedir más información.",
    ],
    explanation: "Le escribo para + infinitivo / Me dirijo a usted para… — формулы причины письма.",
  },
  {
    id: "dele-tr-2",
    type: "translation",
    level: "B2",
    deleTopic: "DELE: Opinión",
    question: "С одной стороны, это удобно; с другой — дорого.",
    instruction: "Переведите с коннекторами эссе",
    answer: "Por un lado, es cómodo; por otro, es caro.",
    acceptableAnswers: [
      "Por un lado es comodo, por otro lado es caro.",
      "Por una parte, es cómodo; por otra, es caro.",
    ],
    explanation: "Por un lado…, por otro (lado)… — базовая пара коннекторов для «двух сторон».",
  },
  {
    id: "dele-tr-3",
    type: "translation",
    level: "B2",
    deleTopic: "DELE: Conectores",
    question: "Поэтому необходимо принять меры.",
    instruction: "Переведите со связкой следствия",
    answer: "Por lo tanto, es necesario tomar medidas.",
    acceptableAnswers: [
      "Por consiguiente, es necesario tomar medidas.",
      "Por eso es necesario tomar medidas.",
    ],
    explanation: "Por lo tanto / por consiguiente — коннекторы следствия для redacción.",
  },
  {
    id: "dele-tr-4",
    type: "translation",
    level: "C1",
    deleTopic: "DELE: Registro formal",
    question: "Заранее благодарю Вас за внимание.",
    instruction: "Формальная формула благодарности",
    answer: "Le agradezco de antemano su atención.",
    acceptableAnswers: [
      "Le agradezco de antemano su atencion.",
      "Agradezco de antemano su atención.",
    ],
    explanation: "De antemano — «заранее»; стандартное завершение формального письма.",
  },
  {
    id: "dele-tr-5",
    type: "translation",
    level: "C2",
    deleTopic: "DELE: Conjetura",
    question: "Наверное, они уже приехали.",
    instruction: "Передайте догадку без quizás",
    answer: "Ya habrán llegado.",
    acceptableAnswers: ["Habrán llegado ya.", "Habran llegado ya."],
    explanation: "Futuro perfecto de conjetura: habrán llegado — догадка о завершённом действии.",
  },

  // ----- error_correction ---------------------------------------------
  {
    id: "dele-ec-1",
    type: "error_correction",
    level: "B1",
    deleTopic: "DELE: Carta formal",
    question: "Querido señor García: Le escribo para solicitar una beca.",
    instruction: "Найдите ошибку регистра в формальном письме",
    answer: "Estimado señor García: Le escribo para solicitar una beca.",
    acceptableAnswers: ["Estimado señor García: le escribo para solicitar una beca."],
    explanation: "В формальном письме — Estimado, не Querido (это для друзей и семьи).",
  },
  {
    id: "dele-ec-2",
    type: "error_correction",
    level: "B2",
    deleTopic: "DELE: Opinión",
    question: "No creo que es una buena idea.",
    instruction: "Исправьте наклонение",
    answer: "No creo que sea una buena idea.",
    explanation: "No creo que + subjuntivo: sea. Indicativo здесь — типичная ошибка на экзамене.",
  },
  {
    id: "dele-ec-3",
    type: "error_correction",
    level: "B2",
    deleTopic: "DELE: Conectores",
    question: "A pesar que llovía, salimos a pasear.",
    instruction: "Исправьте коннектор",
    answer: "A pesar de que llovía, salimos a pasear.",
    explanation: "Правильно: a pesar DE que + verbo. Пропуск de — частая ошибка в redacción.",
  },
  {
    id: "dele-ec-4",
    type: "error_correction",
    level: "C1",
    deleTopic: "DELE: Registro formal",
    question: "Le ruego que me contesta lo antes posible.",
    instruction: "Исправьте форму глагола",
    answer: "Le ruego que me conteste lo antes posible.",
    explanation: "Le ruego que + subjuntivo: conteste.",
  },
  {
    id: "dele-ec-5",
    type: "error_correction",
    level: "C2",
    deleTopic: "DELE: Oraciones hendidas",
    question: "Fue María quien lo hizo, no yo. Fue por eso que me fui.",
    instruction: "Исправьте вторую фразу (норма peninsular)",
    answer: "Fue María quien lo hizo, no yo. Fue por eso por lo que me fui.",
    explanation: "В нормативном европейском испанском: fue por eso POR LO QUE… («que galicado» считается ошибкой).",
  },

  // ----- sentence_building ---------------------------------------------
  {
    id: "dele-sb-1",
    type: "sentence_building",
    level: "B1",
    deleTopic: "DELE: Carta formal",
    question: "Соберите формулу начала формального письма",
    instruction: "Составьте предложение из слов",
    options: ["Me", "dirijo", "a", "usted", "con", "motivo", "de", "la", "oferta"],
    answer: "Me dirijo a usted con motivo de la oferta",
    explanation: "Me dirijo a usted con motivo de… — классическое начало формального письма.",
  },
  {
    id: "dele-sb-2",
    type: "sentence_building",
    level: "B2",
    deleTopic: "DELE: Conectores",
    question: "Соберите вывод эссе",
    instruction: "Составьте предложение из слов",
    options: ["En", "definitiva,", "los", "beneficios", "superan", "a", "los", "riesgos"],
    answer: "En definitiva, los beneficios superan a los riesgos",
    explanation: "En definitiva — коннектор вывода; идеален для последнего абзаца redacción.",
  },
  {
    id: "dele-sb-3",
    type: "sentence_building",
    level: "B2",
    deleTopic: "DELE: Opinión",
    question: "Соберите фразу мнения для устной части",
    instruction: "Составьте предложение из слов",
    options: ["Desde", "mi", "punto", "de", "vista,", "la", "medida", "es", "necesaria"],
    answer: "Desde mi punto de vista, la medida es necesaria",
    explanation: "Desde mi punto de vista… — формула мнения для монолога и дебатов.",
  },
  {
    id: "dele-sb-4",
    type: "sentence_building",
    level: "C1",
    deleTopic: "DELE: Registro formal",
    question: "Соберите формальную просьбу",
    instruction: "Составьте предложение из слов",
    options: ["Le", "agradecería", "que", "me", "remitiera", "la", "documentación", "pertinente"],
    answer: "Le agradecería que me remitiera la documentación pertinente",
    explanation: "Condicional + subjuntivo imperfecto + лексика culta (remitir, pertinente) — уровень C1.",
  },
  {
    id: "dele-sb-5",
    type: "sentence_building",
    level: "C2",
    deleTopic: "DELE: Oraciones hendidas",
    question: "Соберите выделительную конструкцию",
    instruction: "Составьте предложение из слов",
    options: ["Lo", "que", "más", "me", "sorprende", "es", "su", "actitud"],
    answer: "Lo que más me sorprende es su actitud",
    explanation: "Lo que más… es… — клефт для выделения; ценится в устной и письменной части C1–C2.",
  },
];

/** Bank slice for a type; exact level first, otherwise adjacent levels. */
export function getDeleExercises(
  type: StaticExercise["type"],
  level: GrammarLevel,
): DeleExercise[] {
  const byType = DELE_EXERCISES.filter((ex) => ex.type === type);
  const exact = byType.filter((ex) => ex.level === level);
  if (exact.length > 0) return exact;
  const order: GrammarLevel[] = ["A1", "A2", "B1", "B2", "C1", "C2"];
  const idx = order.indexOf(level);
  const near = byType.filter(
    (ex) => Math.abs(order.indexOf(ex.level) - idx) === 1,
  );
  return near.length > 0 ? near : byType;
}
