/**
 * Grammar + chapter journey order for the English course.
 * Matches ENGLISH_CHAPTERS grammarTopic sequence; reference-only topics
 * (no chapter) appear after the nearest step.
 */
export const ENGLISH_GRAMMAR_CURRICULUM_ORDER = [
  // A1
  "eng-a1-be",
  "eng-a1-articles-basics",
  "eng-a1-possessives",
  "eng-a1-present-simple",
  "eng-a1-questions",
  "eng-a1-there-is-are",
  "eng-a1-can",
  "eng-a1-can-ability", // reference supplement (same as eng-a1-can)
  "eng-a1-prepositions",
  // A2
  "eng-a2-past-simple",
  "eng-a2-comparatives",
  "eng-a2-countable",
  "eng-a2-present-perfect-intro",
  "eng-a2-going-to",
  "eng-a2-present-perfect",
  "eng-a2-quantifiers",
  // B1
  "eng-b1-future-conditional",
  "eng-b1-conditionals-review",
  "eng-b1-modals",
  "eng-b1-narrative",
  "eng-b1-perfect-continuous",
  "eng-b1-reported-speech",
  "eng-b1-relative-clauses",
  // B2
  "eng-b2-conditionals",
  "eng-b2-passive",
  "eng-b2-passive-advanced",
  "eng-b2-reported-clauses",
  // IELTS / Cambridge writing block
  "eng-b2-modals-deduction",
  "eng-ielts-letter-informal",
  "eng-ielts-letter-formal",
  "eng-cambridge-letter-email",
  "eng-ielts-task1-report",
  "eng-ielts-essay-structure",
  "eng-ielts-essay-cohesion",
  "eng-cambridge-essay-article",
  "eng-ielts-opinion-language",
  "eng-cbe-register-shift",
  // C1
  "eng-c1-inversion",
  "eng-c1-discourse",
  "eng-c1-mixed-conditionals",
  "eng-c1-review",
  // C2
  "eng-c2-cleft-emphasis",
  "eng-c2-ellipsis-substitution",
  "eng-c2-hedging-nuance",
] as const;

export const ENGLISH_CHAPTER_GRAMMAR_ORDER = [
  "eng-a1-be",
  "eng-a1-articles-basics",
  "eng-a1-possessives",
  "eng-a1-present-simple",
  "eng-a1-questions",
  "eng-a1-there-is-are",
  "eng-a1-can",
  "eng-a1-prepositions",
  "eng-a2-past-simple",
  "eng-a2-comparatives",
  "eng-a2-countable",
  "eng-a2-present-perfect-intro",
  "eng-a2-going-to",
  "eng-a2-present-perfect",
  "eng-a2-quantifiers",
  "eng-b1-future-conditional",
  "eng-b1-conditionals-review",
  "eng-b1-modals",
  "eng-b1-narrative",
  "eng-b1-perfect-continuous",
  "eng-b1-reported-speech",
  "eng-b1-relative-clauses",
  "eng-b2-conditionals",
  "eng-b2-passive",
  "eng-b2-passive-advanced",
  "eng-b2-reported-clauses",
  "eng-b2-modals-deduction",
  "eng-ielts-letter-informal",
  "eng-ielts-letter-formal",
  "eng-cambridge-letter-email",
  "eng-ielts-task1-report",
  "eng-ielts-essay-structure",
  "eng-ielts-essay-cohesion",
  "eng-cambridge-essay-article",
  "eng-ielts-opinion-language",
  "eng-cbe-register-shift",
  "eng-c1-inversion",
  "eng-c1-discourse",
  "eng-c1-mixed-conditionals",
  "eng-c1-review",
  "eng-c2-cleft-emphasis",
  "eng-c2-ellipsis-substitution",
  "eng-c2-hedging-nuance",
] as const;
