import type { StaticExercise } from "@/types";

/**
 * Small seasonal English exercise pool (~16 items).
 * Merged into Daily practice only while Halloween season is on.
 */
export const HALLOWEEN_EXERCISES_ENGLISH: StaticExercise[] = [
  {
    id: "english:halloween:translation:01",
    type: "translation",
    question: "Призрак в старом доме.",
    questionTranslations: {
      es: "El fantasma está en la casa vieja.",
      de: "Der Geist ist im alten Haus.",
    },
    instruction: "Translate to English",
    instructionKey: "translate_to_en",
    answer: "The ghost is in the old house",
    acceptableAnswers: [
      "A ghost is in the old house",
      "The ghost is in an old house",
    ],
    explanation: "ghost = призрак.",
    vocabTopic: "eng-a2-halloween",
  },
  {
    id: "english:halloween:translation:02",
    type: "translation",
    question: "Ведьма летает ночью.",
    questionTranslations: {
      es: "La bruja vuela de noche.",
      de: "Die Hexe fliegt nachts.",
    },
    instruction: "Translate to English",
    instructionKey: "translate_to_en",
    answer: "The witch flies at night",
    acceptableAnswers: ["The witch is flying at night"],
    explanation: "witch = ведьма; fly = летать.",
    vocabTopic: "eng-a2-halloween",
  },
  {
    id: "english:halloween:translation:03",
    type: "translation",
    question: "Мне страшно.",
    questionTranslations: {
      es: "Tengo miedo.",
      de: "Ich habe Angst.",
    },
    instruction: "Translate to English",
    instructionKey: "translate_to_en",
    answer: "I am scared",
    acceptableAnswers: ["I'm scared", "I feel scared", "I'm afraid"],
    explanation: "scared / afraid = бояться.",
    vocabTopic: "eng-a2-halloween",
  },
  {
    id: "english:halloween:translation:04",
    type: "translation",
    question: "Тыква у двери большая.",
    questionTranslations: {
      es: "La calabaza junto a la puerta es grande.",
      de: "Der Kürbis an der Tür ist groß.",
    },
    instruction: "Translate to English",
    instructionKey: "translate_to_en",
    answer: "The pumpkin by the door is big",
    acceptableAnswers: [
      "The pumpkin next to the door is big",
      "There is a big pumpkin by the door",
    ],
    explanation: "pumpkin = тыква.",
    vocabTopic: "eng-a2-halloween",
  },
  {
    id: "english:halloween:translation:05",
    type: "translation",
    question: "Не бойся — это только костюм.",
    questionTranslations: {
      es: "No tengas miedo: es solo un disfraz.",
      de: "Hab keine Angst — es ist nur ein Kostüm.",
    },
    instruction: "Translate to English",
    instructionKey: "translate_to_en",
    answer: "Don't be afraid — it's only a costume",
    acceptableAnswers: [
      "Don't be scared — it's just a costume",
      "Don't be afraid, it's only a costume",
    ],
    explanation: "costume = костюм.",
    vocabTopic: "eng-a2-halloween",
  },
  {
    id: "english:halloween:fill_blank:01",
    type: "fill_blank",
    question: "The ___ lives in the dark castle. (vampire)",
    instruction: "Fill in the blank",
    answer: "vampire",
    explanation: "vampire = вампир.",
    vocabTopic: "eng-a2-halloween",
  },
  {
    id: "english:halloween:fill_blank:02",
    type: "fill_blank",
    question: "The children wear a ___ on Halloween. (costume)",
    instruction: "Fill in the blank",
    answer: "costume",
    explanation: "costume = костюм / маскарадный наряд.",
    vocabTopic: "eng-a2-halloween",
  },
  {
    id: "english:halloween:fill_blank:03",
    type: "fill_blank",
    question: "The house looks ___. (haunted)",
    instruction: "Fill in the blank",
    answer: "haunted",
    acceptableAnswers: ["scary", "spooky"],
    explanation: "haunted = с привидениями.",
    vocabTopic: "eng-a2-halloween",
  },
  {
    id: "english:halloween:fill_blank:04",
    type: "fill_blank",
    question: "At night we heard a noise in the ___. (cemetery)",
    instruction: "Fill in the blank",
    answer: "cemetery",
    acceptableAnswers: ["graveyard"],
    explanation: "cemetery / graveyard = кладбище.",
    vocabTopic: "eng-a2-halloween",
  },
  {
    id: "english:halloween:multiple_choice:01",
    type: "multiple_choice",
    question: "Which word means a place for the dead?",
    instruction: "Choose the correct option",
    options: ["cemetery", "library", "market", "station"],
    answer: "cemetery",
    explanation: "cemetery = кладбище.",
    vocabTopic: "eng-a2-halloween",
  },
  {
    id: "english:halloween:multiple_choice:02",
    type: "multiple_choice",
    question: "What is a monster?",
    instruction: "Choose the correct option",
    options: [
      "a huge scary creature",
      "a teacher",
      "a friend",
      "a park",
    ],
    answer: "a huge scary creature",
    explanation: "monster = монстр.",
    vocabTopic: "eng-a2-halloween",
  },
  {
    id: "english:halloween:multiple_choice:03",
    type: "multiple_choice",
    question: "Which sentence is correct?",
    instruction: "Choose the correct option",
    options: [
      "The witch flies",
      "The witch fly",
      "Witch the flies",
      "The witches flies",
    ],
    answer: "The witch flies",
    explanation: "3rd person singular: fly → flies.",
    vocabTopic: "eng-a2-halloween",
  },
  {
    id: "english:halloween:error_correction:01",
    type: "error_correction",
    question: "The ghost are in the kitchen.",
    instruction: "Fix the mistake",
    answer: "The ghost is in the kitchen.",
    acceptableAnswers: ["The ghost is in the kitchen"],
    explanation: "ghost = singular → is.",
    vocabTopic: "eng-a2-halloween",
  },
  {
    id: "english:halloween:error_correction:02",
    type: "error_correction",
    question: "The children has fear.",
    instruction: "Fix the mistake",
    answer: "The children are scared.",
    acceptableAnswers: [
      "The children are afraid.",
      "The children have fear.",
    ],
    explanation: "Prefer be scared / be afraid; or have fear (children → have).",
    vocabTopic: "eng-a2-halloween",
  },
  {
    id: "english:halloween:sentence_building:01",
    type: "sentence_building",
    question: "The / monster / is / very / big",
    instruction: "Build the sentence",
    instructionKey: "build_sentence",
    options: ["The", "monster", "is", "very", "big"],
    answer: "The monster is very big",
    explanation: "be + adjective.",
    vocabTopic: "eng-a2-halloween",
  },
  {
    id: "english:halloween:sentence_building:02",
    type: "sentence_building",
    question: "The / night / scares / me",
    instruction: "Build the sentence",
    instructionKey: "build_sentence",
    options: ["The", "night", "scares", "me"],
    answer: "The night scares me",
    explanation: "scare + object.",
    vocabTopic: "eng-a2-halloween",
  },
];
