// =====================================================================
// Curated vocabulary catalog by CEFR level and topic.
// ---------------------------------------------------------------------
// Static data — served instantly, costs zero tokens and zero DB queries.
// Each topic has 12-20 words with Spanish term, Russian translation,
// and an example sentence. Users can add any word to their personal
// dictionary from the vocabulary-topics page.
// =====================================================================

export interface VocabWord {
  word: string;
  translation: string;
  example: string;
}

export interface VocabTopic {
  slug: string;
  level: "A1" | "A2" | "B1" | "B2" | "C1";
  topic: string;
  topicEs: string;
  icon: string;
  words: VocabWord[];
}

export const VOCAB_TOPICS: VocabTopic[] = [
  // ===== A1 ==========================================================
  {
    slug: "a1-familia",
    level: "A1",
    topic: "Семья",
    topicEs: "La Familia",
    icon: "👨‍👩‍👧‍👦",
    words: [
      { word: "la familia", translation: "семья", example: "Mi familia es grande." },
      { word: "el padre", translation: "отец", example: "Mi padre es médico." },
      { word: "la madre", translation: "мать", example: "Mi madre cocina muy bien." },
      { word: "el hermano", translation: "брат", example: "Tengo un hermano mayor." },
      { word: "la hermana", translation: "сестра", example: "Mi hermana estudia en Madrid." },
      { word: "el hijo / la hija", translation: "сын / дочь", example: "Sus hijos son pequeños." },
      { word: "el abuelo / la abuela", translation: "дедушка / бабушка", example: "Mis abuelos viven en Sevilla." },
      { word: "el tío / la tía", translation: "дядя / тётя", example: "Mi tía es profesora." },
      { word: "el primo / la prima", translation: "двоюродный брат / сестра", example: "Mis primos son divertidos." },
      { word: "el marido / el esposo", translation: "муж", example: "Su marido es arquitecto." },
      { word: "la mujer / la esposa", translation: "жена", example: "Su mujer es enfermera." },
      { word: "el novio / la novia", translation: "парень / девушка", example: "Mi novia es italiana." },
      { word: "el bebé", translation: "младенец", example: "El bebé tiene seis meses." },
      { word: "el nieto / la nieta", translation: "внук / внучка", example: "Sus nietos viven en México." },
      { word: "mayor", translation: "старший", example: "Mi hermano es mayor que yo." },
      { word: "menor", translation: "младший", example: "Mi hermana es menor." },
      { word: "casarse", translation: "жениться", example: "Se casaron el año pasado." },
      { word: "vivir", translation: "жить", example: "Vivimos juntos en Barcelona." },
    ],
  },
  {
    slug: "a1-comida",
    level: "A1",
    topic: "Еда и напитки",
    topicEs: "La Comida y la Bebida",
    icon: "🍽️",
    words: [
      { word: "el pan", translation: "хлеб", example: "Quiero un poco de pan." },
      { word: "el agua", translation: "вода", example: "Necesito agua, por favor." },
      { word: "el café", translation: "кофе", example: "Tomo café por la mañana." },
      { word: "la leche", translation: "молоко", example: "La leche está fría." },
      { word: "el arroz", translation: "рис", example: "Me gusta el arroz con pollo." },
      { word: "la carne", translation: "мясо", example: "No como carne, soy vegetariano." },
      { word: "el pollo", translation: "курица", example: "Pollo con patatas, por favor." },
      { word: "el pescado", translation: "рыба", example: "El pescado está muy bueno." },
      { word: "la fruta", translation: "фрукт", example: "Como fruta todos los días." },
      { word: "la manzana", translation: "яблоко", example: "Una manzana roja, por favor." },
      { word: "el plátano", translation: "банан", example: "Los plátanos son dulces." },
      { word: "el naranja / el zumo", translation: "апельсин / сок", example: "Zumo de naranja natural." },
      { word: "el queso", translation: "сыр", example: "El queso manchego es famoso." },
      { word: "el huevo", translation: "яйцо", example: "Dos huevos fritos, por favor." },
      { word: "la ensalada", translation: "салат", example: "Una ensalada mixta." },
      { word: "la sopa", translation: "суп", example: "La sopa está caliente." },
      { word: "el postre", translation: "десерт", example: "¿Qué hay de postre?" },
      { word: "beber", translation: "пить", example: "Bebo mucha agua." },
      { word: "comer", translation: "есть", example: "Comemos a las dos." },
      { word: "el desayuno", translation: "завтрак", example: "El desayuno es la primera comida." },
    ],
  },
  {
    slug: "a1-casa",
    level: "A1",
    topic: "Дом и мебель",
    topicEs: "La Casa y el Mueble",
    icon: "🏠",
    words: [
      { word: "la casa", translation: "дом", example: "Mi casa es bonita." },
      { word: "el piso", translation: "квартира / этаж", example: "Vivo en un piso pequeño." },
      { word: "la habitación / el cuarto", translation: "комната", example: "Mi habitación es grande." },
      { word: "la cocina", translation: "кухня", example: "La cocina está limpia." },
      { word: "el baño", translation: "ванная", example: "¿Dónde está el baño?" },
      { word: "el salón", translation: "гостиная", example: "Vemos la tele en el salón." },
      { word: "la puerta", translation: "дверь", example: "Cierra la puerta, por favor." },
      { word: "la ventana", translation: "окно", example: "Abre la ventana, hace calor." },
      { word: "la mesa", translation: "стол", example: "Los libros están en la mesa." },
      { word: "la silla", translation: "стул", example: "Siéntate en esta silla." },
      { word: "la cama", translation: "кровать", example: "Mi cama es cómoda." },
      { word: "el sofá", translation: "диван", example: "El sofá es nuevo." },
      { word: "el armario", translation: "шкаф", example: "La ropa está en el armario." },
      { word: "la lámpara", translation: "лампа", example: "Enciende la lámpara." },
      { word: "la llave", translation: "ключ", example: "¿Tienes las llaves?" },
      { word: "la escalera", translation: "лестница", example: "Sube por la escalera." },
      { word: "el jardín", translation: "сад", example: "Tenemos un jardín pequeño." },
      { word: "el garaje", translation: "гараж", example: "El coche está en el garaje." },
    ],
  },
  {
    slug: "a1-numeros-tiempo",
    level: "A1",
    topic: "Время и дни недели",
    topicEs: "El Tiempo y los Días",
    icon: "🕐",
    words: [
      { word: "el día", translation: "день", example: "Todos los días estudio español." },
      { word: "la noche", translation: "ночь", example: "Por la noche duermo." },
      { word: "la mañana", translation: "утро", example: "Por la mañana desayuno." },
      { word: "la tarde", translation: "день/вечер", example: "Por la tarde trabajo." },
      { word: "la semana", translation: "неделя", example: "Hay siete días en una semana." },
      { word: "el mes", translation: "месяц", example: "Doce meses tiene un año." },
      { word: "el año", translation: "год", example: "El año que viene viajaré." },
      { word: "hoy", translation: "сегодня", example: "Hoy hace sol." },
      { word: "mañana", translation: "завтра", example: "Mañana tengo examen." },
      { word: "ayer", translation: "вчера", example: "Ayer fui al cine." },
      { word: "lunes", translation: "понедельник", example: "El lunes trabajo mucho." },
      { word: "martes", translation: "вторник", example: "El martes tengo clase." },
      { word: "miércoles", translation: "среда", example: "El miércoles juego al tenis." },
      { word: "jueves", translation: "четверг", example: "El jueves voy al gimnasio." },
      { word: "viernes", translation: "пятница", example: "El viernes salgo con amigos." },
      { word: "sábado", translation: "суббота", example: "El sábado descanso." },
      { word: "domingo", translation: "воскресенье", example: "El domingo visito a mi familia." },
      { word: "la hora", translation: "час", example: "¿Qué hora es?" },
      { word: "el minuto", translation: "минута", example: "Cinco minutos más." },
      { word: "siempre", translation: "всегда", example: "Siempre desayuno café." },
    ],
  },
  {
    slug: "a1-ciudad",
    level: "A1",
    topic: "Город и ориентация",
    topicEs: "La Ciudad y las Direcciones",
    icon: "🏙️",
    words: [
      { word: "la ciudad", translation: "город", example: "Madrid es una ciudad grande." },
      { word: "la calle", translation: "улица", example: "Mi calle es muy ruidosa." },
      { word: "la plaza", translation: "площадь", example: "Nos vemos en la plaza." },
      { word: "el parque", translation: "парк", example: "El parque está cerca." },
      { word: "la tienda", translation: "магазин", example: "Hay una tienda al lado." },
      { word: "el restaurante", translation: "ресторан", example: "El restaurante es caro." },
      { word: "el café", translation: "кафе", example: "Vamos al café de la esquina." },
      { word: "el hotel", translation: "отель", example: "El hotel está en el centro." },
      { word: "el hospital", translation: "больница", example: "El hospital es nuevo." },
      { word: "la farmacia", translation: "аптека", example: "Necesito ir a la farmacia." },
      { word: "el banco", translation: "банк", example: "El banco abre a las nueve." },
      { word: "la escuela", translation: "школа", example: "La escuela está cerca de casa." },
      { word: "la estación", translation: "станция", example: "La estación de tren está allí." },
      { word: "el aeropuerto", translation: "аэропорт", example: "El aeropuerto está lejos." },
      { word: "el cine", translation: "кино", example: "Vamos al cine esta noche." },
      { word: "la biblioteca", translation: "библиотека", example: "Estudio en la biblioteca." },
      { word: "cerca", translation: "близко", example: "Está cerca de aquí." },
      { word: "lejos", translation: "далеко", example: "No está lejos." },
      { word: "derecha", translation: "право", example: "Gire a la derecha." },
      { word: "izquierda", translation: "лево", example: "A la izquierda del banco." },
    ],
  },
  {
    slug: "a1-colores",
    level: "A1",
    topic: "Цвета",
    topicEs: "Los Colores",
    icon: "🎨",
    words: [
      { word: "rojo / roja", translation: "красный", example: "El coche es rojo." },
      { word: "azul", translation: "синий", example: "Mi camisa es azul." },
      { word: "verde", translation: "зелёный", example: "La hierba es verde." },
      { word: "amarillo / amarilla", translation: "жёлтый", example: "El sol es amarillo." },
      { word: "blanco / blanca", translation: "белый", example: "Una camisa blanca." },
      { word: "negro / negra", translation: "чёрный", example: "Tengo un gato negro." },
      { word: "naranja", translation: "оранжевый", example: "El naranja es mi color favorito." },
      { word: "rosa", translation: "розовый", example: "Una rosa rosa." },
      { word: "morado / morada", translation: "фиолетовый", example: "Las uvas son moradas." },
      { word: "marrón", translation: "коричневый", example: "El pelo marrón." },
      { word: "gris", translation: "серый", example: "El cielo está gris." },
      { word: "claro / clara", translation: "светлый", example: "Azul claro, por favor." },
      { word: "oscuro / oscura", translation: "тёмный", example: "Prefiero el azul oscuro." },
    ],
  },
  {
    slug: "a1-cuerpo",
    level: "A1",
    topic: "Тело и здоровье",
    topicEs: "El Cuerpo y la Salud",
    icon: "🫀",
    words: [
      { word: "la cabeza", translation: "голова", example: "Me duele la cabeza." },
      { word: "el pelo", translation: "волосы", example: "Tiene el pelo largo." },
      { word: "los ojos", translation: "глаза", example: "Sus ojos son azules." },
      { word: "la nariz", translation: "нос", example: "La nariz es pequeña." },
      { word: "la boca", translation: "рот", example: "Abre la boca, por favor." },
      { word: "la oreja", translation: "ухо", example: "No oigo bien de la oreja izquierda." },
      { word: "la mano", translation: "рука (кисть)", example: "Me lavé las manos." },
      { word: "el brazo", translation: "рука (от плеча)", example: "Tengo dolor en el brazo." },
      { word: "la pierna", translation: "нога", example: "Me duele la pierna." },
      { word: "el pie", translation: "ступня", example: "Los pies están fríos." },
      { word: "el diente", translation: "зуб", example: "Tengo un diente roto." },
      { word: "el corazón", translation: "сердце", example: "El corazón late rápido." },
      { word: "estar enfermo", translation: "быть больным", example: "Estoy enfermo, no voy a trabajar." },
      { word: "la medicina", translation: "лекарство", example: "Toma la medicina después de comer." },
      { word: "el médico / la médica", translation: "врач", example: "Voy al médico mañana." },
      { word: "la fiebre", translation: "температура", example: "Tengo fiebre." },
      { word: "el dolor", translation: "боль", example: "Tengo dolor de garganta." },
    ],
  },
  {
    slug: "a1-verbos-basicos",
    level: "A1",
    topic: "Базовые глаголы",
    topicEs: "Verbos Básicos",
    icon: "⚡",
    words: [
      { word: "ser", translation: "быть (постоянно)", example: "Soy estudiante." },
      { word: "estar", translation: "быть (состояние)", example: "Estoy bien." },
      { word: "tener", translation: "иметь", example: "Tengo dos hermanos." },
      { word: "hacer", translation: "делать", example: "Hago los deberes." },
      { word: "ir", translation: "идти", example: "Voy a la escuela." },
      { word: "venir", translation: "приходить", example: "¿Viene Juan?" },
      { word: "ver", translation: "видеть", example: "Veo la tele." },
      { word: "comer", translation: "есть", example: "Como en casa." },
      { word: "beber", translation: "пить", example: "Bebo agua." },
      { word: "hablar", translation: "говорить", example: "Hablo español." },
      { word: "escuchar", translation: "слушать", example: "Escucho música." },
      { word: "leer", translation: "читать", example: "Leo un libro." },
      { word: "escribir", translation: "писать", example: "Escribo un correo." },
      { word: "trabajar", translation: "работать", example: "Trabajo en una oficina." },
      { word: "estudiar", translation: "учиться", example: "Estudio inglés." },
      { word: "vivir", translation: "жить", example: "Vivo en Madrid." },
      { word: "pensar", translation: "думать", example: "Pienso en ti." },
      { word: "querer", translation: "хотеть", example: "Quiero un café." },
      { word: "poder", translation: "мочь", example: "Puedo ayudarte." },
      { word: "deber", translation: "должен", example: "Debo estudiar más." },
    ],
  },

  // ===== A2 ==========================================================
  {
    slug: "a2-viajes",
    level: "A2",
    topic: "Путешествия",
    topicEs: "Los Viajes",
    icon: "✈️",
    words: [
      { word: "el viaje", translation: "поездка", example: "Hicimos un viaje a Italia." },
      { word: "viajar", translation: "путешествовать", example: "Me gusta viajar por España." },
      { word: "el billete / el boleto", translation: "билет", example: "Compré el billete online." },
      { word: "el pasaporte", translation: "паспорт", example: "Necesito renovar el pasaporte." },
      { word: "la maleta", translation: "чемодан", example: "Hice la maleta ayer." },
      { word: "el avión", translation: "самолёт", example: "El avión llega a las tres." },
      { word: "el tren", translation: "поезд", example: "El tren se retrasó." },
      { word: "el autobús", translation: "автобус", example: "Tomamos el autobús 47." },
      { word: "el taxi", translation: "такси", example: "Llamé un taxi." },
      { word: "el hotel", translation: "отель", example: "Reservé una habitación de hotel." },
      { word: "reservar", translation: "бронировать", example: "Reservé una mesa." },
      { word: "la habitación", translation: "номер (в отеле)", example: "Quiero una habitación doble." },
      { word: "el destino", translation: "направление", example: "¿Cuál es tu destino?" },
      { word: "la llegada", translation: "прибытие", example: "La llegada es a las diez." },
      { word: "la salida", translation: "отправление", example: "La salida es a las ocho." },
      { word: "el mapa", translation: "карта", example: "Mira el mapa de la ciudad." },
      { word: "la guía", translation: "гид / путеводитель", example: "Compramos una guía de Roma." },
      { word: "perderse", translation: "заблудиться", example: "Nos perdimos en el centro." },
    ],
  },
  {
    slug: "a2-trabajo",
    level: "A2",
    topic: "Работа и профессии",
    topicEs: "El Trabajo y las Profesiones",
    icon: "💼",
    words: [
      { word: "el trabajo", translation: "работа", example: "Mi trabajo es interesante." },
      { word: "trabajar", translation: "работать", example: "Trabajo de lunes a viernes." },
      { word: "el jefe / la jefa", translation: "начальник", example: "Mi jefe es exigente." },
      { word: "el compañero de trabajo", translation: "коллега", example: "Mis compañeros son simpáticos." },
      { word: "la oficina", translation: "офис", example: "Llego a la oficina a las nueve." },
      { word: "la reunión", translation: "собрание", example: "Hay una reunión a las diez." },
      { word: "el sueldo", translation: "зарплата", example: "Piden un aumento de sueldo." },
      { word: "el contrato", translation: "контракт", example: "Firmé un contrato temporal." },
      { word: "entrevista de trabajo", translation: "собеседование", example: "Tengo una entrevista mañana." },
      { word: "el médico", translation: "врач", example: "El médico me recetó medicina." },
      { word: "el profesor / la profesora", translation: "учитель", example: "Mi profesora es muy buena." },
      { word: "el ingeniero", translation: "инженер", example: "Es ingeniero de software." },
      { word: "el abogado / la abogada", translation: "адвокат", example: "Necesito un abogado." },
      { word: "el arquitecto", translation: "архитектор", example: "El arquitecto diseñó la casa." },
      { word: "el peluquero / la peluquera", translation: "парикмахер", example: "Voy a la peluquería." },
      { word: "el cocinero / la cocinera", translation: "повар", example: "Es un cocinero excelente." },
      { word: "el periodista", translation: "журналист", example: "Trabaja de periodista." },
      { word: "estar en paro", translation: "быть безработным", example: "Está en paro desde hace meses." },
    ],
  },
  {
    slug: "a2-ropa",
    level: "A2",
    topic: "Одежда",
    topicEs: "La Ropa",
    icon: "👕",
    words: [
      { word: "la ropa", translation: "одежда", example: "Compré ropa nueva." },
      { word: "la camisa", translation: "рубашка", example: "Una camisa blanca." },
      { word: "la camiseta", translation: "футболка", example: "Llevo una camiseta de algodón." },
      { word: "los pantalones", translation: "брюки", example: "Estos pantalones son cortos." },
      { word: "el vestido", translation: "платье", example: "Un vestido rojo." },
      { word: "la falda", translation: "юбка", example: "Una falda negra." },
      { word: "la chaqueta", translation: "куртка", example: "Ponte la chaqueta, hace frío." },
      { word: "el abrigo", translation: "пальто", example: "Necesito un abrigo de invierno." },
      { word: "los zapatos", translation: "туфли / ботинки", example: "Me compré zapatos nuevos." },
      { word: "las zapatillas", translation: "кроссовки", example: "Uso zapatillas para correr." },
      { word: "las botas", translation: "сапоги", example: "Las botas son de cuero." },
      { word: "el sombrero", translation: "шляпа", example: "Lleva un sombrero grande." },
      { word: "los guantes", translation: "перчатки", example: "Ponte los guantes." },
      { word: "la bufanda", translation: "шарф", example: "Una bufanda de lana." },
      { word: "el traje", translation: "костюм", example: "Lleva traje para la boda." },
      { word: "la talla", translation: "размер", example: "¿Qué talla usa?" },
      { word: "probarse", translation: "примерять", example: "Quiero probarme esta camisa." },
      { word: "caro / cara", translation: "дорогой", example: "Es demasiado caro." },
    ],
  },
  {
    slug: "a2-clima",
    level: "A2",
    topic: "Погода и природа",
    topicEs: "El Tiempo y la Naturaleza",
    icon: "🌤️",
    words: [
      { word: "el clima / el tiempo", translation: "погода", example: "El tiempo está bueno." },
      { word: "hace sol", translation: "солнечно", example: "Hoy hace sol." },
      { word: "hace calor", translation: "жарко", example: "En verano hace mucho calor." },
      { word: "hace frío", translation: "холодно", example: "Hace frío en diciembre." },
      { word: "llover", translation: "идти (о дожде)", example: "Está lloviendo." },
      { word: "nevar", translation: "идти (о снеге)", example: "Nieva en la sierra." },
      { word: "el viento", translation: "ветер", example: "Hay mucho viento hoy." },
      { word: "la nube", translation: "облако", example: "El cielo está nublado." },
      { word: "la tormenta", translation: "гроза", example: "Hubo una tormenta terrible." },
      { word: "la temperatura", translation: "температура", example: "La temperatura es de veinte grados." },
      { word: "el bosque", translation: "лес", example: "Paseamos por el bosque." },
      { word: "el mar", translation: "море", example: "El mar está tranquilo." },
      { word: "el río", translation: "река", example: "El río es largo." },
      { word: "la montaña", translation: "гора", example: "Subimos la montaña a pie." },
      { word: "la playa", translation: "пляж", example: "Pasamos el día en la playa." },
      { word: "el árbol", translation: "дерево", example: "Los árboles son altos." },
      { word: "la flor", translation: "цветок", example: "Las flores son bonitas." },
      { word: "el animal", translation: "животное", example: "Los animales del bosque." },
    ],
  },
  {
    slug: "a2-deportes",
    level: "A2",
    topic: "Спорт и хобби",
    topicEs: "Los Deportes y los Aficiones",
    icon: "⚽",
    words: [
      { word: "el deporte", translation: "спорт", example: "Me encanta el deporte." },
      { word: "jugar", translation: "играть", example: "Juego al fútbol los sábados." },
      { word: "el fútbol", translation: "футбол", example: "El fútbol es el deporte más popular." },
      { word: "el baloncesto", translation: "баскетбол", example: "Juega al baloncesto." },
      { word: "el tenis", translation: "теннис", example: "Juego al tenis los lunes." },
      { word: "nadar", translation: "плавать", example: "Nado en la piscina." },
      { word: "correr", translation: "бегать", example: "Corro cinco kilómetros al día." },
      { word: "la piscina", translation: "бассейн", example: "Voy a la piscina." },
      { word: "el gimnasio", translation: "спортзал", example: "Entreno en el gimnasio." },
      { word: "el equipo", translation: "команда", example: "Mi equipo ganó el partido." },
      { word: "el partido", translation: "матч", example: "Vimos el partido en la tele." },
      { word: "ganar", translation: "выигрывать", example: "Ganamos tres a cero." },
      { word: "perder", translation: "проигрывать", example: "Perdimos el partido." },
      { word: "el aficionado", translation: "болельщик", example: "Soy aficionado del Real Madrid." },
      { word: "el hobby / la afición", translation: "хобби", example: "Mi afición es leer." },
      { word: "tocar la guitarra", translation: "играть на гитаре", example: "Toca la guitarra muy bien." },
      { word: "pintar", translation: "рисовать", example: "Pinta paisajes." },
      { word: "bailar", translation: "танцевать", example: "Bailamos salsa." },
    ],
  },
  {
    slug: "a2-compras",
    level: "A2",
    topic: "Покупки",
    topicEs: "Las Compras",
    icon: "🛒",
    words: [
      { word: "comprar", translation: "покупать", example: "Compré pan en la panadería." },
      { word: "la tienda", translation: "магазин", example: "Hay muchas tiendas en el centro." },
      { word: "el supermercado", translation: "супермаркет", example: "Voy al supermercado los viernes." },
      { word: "el precio", translation: "цена", example: "¿Cuál es el precio?" },
      { word: "caro / cara", translation: "дорогой", example: "Es demasiado caro." },
      { word: "barato / barata", translation: "дешёвый", example: "Está muy barato." },
      { word: "pagar", translation: "платить", example: "Pago con tarjeta." },
      { word: "la tarjeta de crédito", translation: "кредитная карта", example: "¿Aceptan tarjeta de crédito?" },
      { word: "el dinero", translation: "деньги", example: "Necesito sacar dinero." },
      { word: "el cambio", translation: "сдача", example: "Guarde el cambio." },
      { word: "el descuento / la rebaja", translation: "скидка", example: "Hay un descuento del 20%." },
      { word: "la talla", translation: "размер", example: "¿Lo tienen en otra talla?" },
      { word: "la caja", translation: "касса", example: "Pague en la caja." },
      { word: "el ticket / el recibo", translation: "чек", example: "Guarde el recibo." },
      { word: "probar", translation: "примерять", example: "¿Puedo probármelo?" },
      { word: "vender", translation: "продавать", example: "Venden fruta fresca." },
    ],
  },
  {
    slug: "a2-tecnologia",
    level: "A2",
    topic: "Технологии",
    topicEs: "La Tecnología",
    icon: "📱",
    words: [
      { word: "el teléfono", translation: "телефон", example: "Mi teléfono es nuevo." },
      { word: "el móvil", translation: "мобильный", example: "Uso el móvil para todo." },
      { word: "la computadora / el ordenador", translation: "компьютер", example: "Trabajo con el ordenador." },
      { word: "el internet", translation: "интернет", example: "No tengo internet en casa." },
      { word: "el correo electrónico", translation: "эл. почта", example: "Te envié un correo." },
      { word: "el mensaje", translation: "сообщение", example: "Te dejé un mensaje." },
      { word: "la aplicación / la app", translation: "приложение", example: "Descargué una app nueva." },
      { word: "la pantalla", translation: "экран", example: "La pantalla es grande." },
      { word: "el teclado", translation: "клавиатура", example: "El teclado está sucio." },
      { word: "el ratón", translation: "мышь", example: "Necesito un ratón nuevo." },
      { word: "la cámara", translation: "камера", example: "Saqué fotos con la cámara." },
      { word: "la batería", translation: "батарея", example: "La batería está baja." },
      { word: "cargar", translation: "заряжать", example: "Tengo que cargar el móvil." },
      { word: "descargar", translation: "скачивать", example: "Descargué la película." },
      { word: "la contraseña", translation: "пароль", example: "Olvidé mi contraseña." },
      { word: "el wifi", translation: "вай-фай", example: "¿Cuál es la contraseña del wifi?" },
    ],
  },

  // ===== B1 ==========================================================
  {
    slug: "b1-emociones",
    level: "B1",
    topic: "Эмоции и чувства",
    topicEs: "Las Emociones y los Sentimientos",
    icon: "😊",
    words: [
      { word: "feliz / contento", translation: "счастливый", example: "Estoy muy contento con el resultado." },
      { word: "triste", translation: "грустный", example: "Se siente triste hoy." },
      { word: "enojado / enfadado", translation: "злой", example: "Está enfadado conmigo." },
      { word: "asustado", translation: "напуганный", example: "El niño está asustado." },
      { word: "sorprendido", translation: "удивлённый", example: "Estoy sorprendido por la noticia." },
      { word: "aburrido", translation: "скучающий", example: "Estoy aburrido en casa." },
      { word: "nervioso", translation: "нервный", example: "Estoy nervioso por el examen." },
      { word: "emocionado", translation: "взволнованный", example: "Estoy emocionado por el viaje." },
      { word: "celoso", translation: "ревнивый", example: "Es celoso de su amigo." },
      { word: "orgulloso", translation: "гордый", example: "Estoy orgulloso de ti." },
      { word: "avergonzado", translation: "смущённый", example: "Se sintió avergonzado." },
      { word: "decepcionado", translation: "разочарованный", example: "Estoy decepcionado con la película." },
      { word: "preocupado", translation: "обеспокоенный", example: "Estoy preocupado por ella." },
      { word: "tranquilo", translation: "спокойный", example: "Quédate tranquilo." },
      { word: "agradecido", translation: "благодарный", example: "Estoy muy agradecido." },
      { word: "la ilusión", translation: "воодушевление", example: "Tengo mucha ilusión por este proyecto." },
      { word: "la nostalgia", translation: "ностальгия", example: "Siento nostalgia de mi infancia." },
      { word: "sentir", translation: "чувствовать", example: "Siento que algo va mal." },
    ],
  },
  {
    slug: "b1-opiniones",
    level: "B1",
    topic: "Мнения и убеждения",
    topicEs: "Las Opiniones y las Creencias",
    icon: "💭",
    words: [
      { word: "la opinión", translation: "мнение", example: "En mi opinión, tienes razón." },
      { word: "creer", translation: "верить / считать", example: "Creo que es verdad." },
      { word: "pensar", translation: "думать / полагать", example: "Pienso que debemos ir." },
      { word: "parecer", translation: "казаться", example: "Me parece una buena idea." },
      { word: "estar de acuerdo", translation: "быть согласным", example: "Estoy de acuerdo contigo." },
      { word: "estar en desacuerdo", translation: "не соглашаться", example: "Estoy en desacuerdo." },
      { word: "defender", translation: "защищать (точку зрения)", example: "Defendió su opinión con datos." },
      { word: "argumentar", translation: "аргументировать", example: "Argumentó muy bien." },
      { word: "convencer", translation: "убеждать", example: "Me convenció con sus argumentos." },
      { word: "dudar", translation: "сомневаться", example: "Dudo que venga." },
      { word: "negar", translation: "отрицать", example: "Niega haberlo dicho." },
      { word: "afirmar", translation: "утверждать", example: "Afirma que es inocente." },
      { word: "el punto de vista", translation: "точка зрения", example: "Desde mi punto de vista, es correcto." },
      { word: "estar seguro", translation: "быть уверенным", example: "Estoy seguro de que vendrá." },
      { word: "suponer", translation: "предполагать", example: "Supongo que tienes razón." },
      { word: "el debate", translation: "дебаты", example: "Participé en un debate." },
    ],
  },
  {
    slug: "b1-educacion",
    level: "B1",
    topic: "Образование",
    topicEs: "La Educación",
    icon: "🎓",
    words: [
      { word: "la escuela", translation: "школа", example: "Mis hijos van a la escuela pública." },
      { word: "la universidad", translation: "университет", example: "Estudia en la universidad." },
      { word: "el examen", translation: "экзамен", example: "Tengo un examen mañana." },
      { word: "estudiar", translation: "учиться", example: "Estudio español todos los días." },
      { word: "aprender", translation: "изучать", example: "Quiero aprender a tocar el piano." },
      { word: "enseñar", translation: "преподавать", example: "Enseña historia en el instituto." },
      { word: "el profesor", translation: "преподаватель", example: "El profesor explicó el tema." },
      { word: "el alumno / el estudiante", translation: "ученик / студент", example: "Los estudiantes hacen preguntas." },
      { word: "la asignatura", translation: "предмет", example: "Mi asignatura favorita es la historia." },
      { word: "la nota / la calificación", translation: "оценка", example: "Saqué buena nota en el examen." },
      { word: "aprobar", translation: "сдать (экзамен)", example: "Aprobé el examen de conducir." },
      { word: "suspender", translation: "провалить", example: "Suspendí matemáticas." },
      { word: "los deberes", translation: "домашнее задание", example: "Tengo que hacer los deberes." },
      { word: "el título", translation: "диплом", example: "Obtuvo el título de licenciado." },
      { word: "la matrícula", translation: "зачисление", example: "La matrícula es en septiembre." },
      { word: "el campus", translation: "кампус", example: "El campus es muy grande." },
    ],
  },
  {
    slug: "b1-sociedad",
    level: "B1",
    topic: "Общество и политика",
    topicEs: "La Sociedad y la Política",
    icon: "🏛️",
    words: [
      { word: "la sociedad", translation: "общество", example: "Vivimos en una sociedad compleja." },
      { word: "la política", translation: "политика", example: "No me interesa la política." },
      { word: "el gobierno", translation: "правительство", example: "El gobierno anunció nuevas medidas." },
      { word: "las elecciones", translation: "выборы", example: "Las elecciones son en noviembre." },
      { word: "el presidente", translation: "президент", example: "El presidente habló en la tele." },
      { word: "el partido político", translation: "политическая партия", example: "Votó por otro partido." },
      { word: "votar", translation: "голосовать", example: "Voté en las elecciones." },
      { word: "la ley", translation: "закон", example: "Hay que respetar la ley." },
      { word: "el derecho", translation: "право", example: "Estudia derecho en la universidad." },
      { word: "la justicia", translation: "справедливость", example: "Lucha por la justicia social." },
      { word: "la libertad", translation: "свобода", example: "La libertad es un derecho fundamental." },
      { word: "la igualdad", translation: "равенство", example: "Defiende la igualdad de género." },
      { word: "la democracia", translation: "демократия", example: "Vivimos en una democracia." },
      { word: "el país", translation: "страна", example: "Nuestro país es hermoso." },
      { word: "la cultura", translation: "культура", example: "Me interesa la cultura española." },
      { word: "la tradición", translation: "традиция", example: "Es una tradición familiar." },
    ],
  },
  {
    slug: "b1-salud",
    level: "B1",
    topic: "Здоровье и медицина",
    topicEs: "La Salud y la Medicina",
    icon: "🏥",
    words: [
      { word: "la salud", translation: "здоровье", example: "La salud es lo más importante." },
      { word: "sano / saludable", translation: "здоровый", example: "Llevo una vida sana." },
      { word: "enfermo", translation: "больной", example: "Estuvo enfermo una semana." },
      { word: "el síntoma", translation: "симптом", example: "¿Qué síntomas tiene?" },
      { word: "la gripe", translation: "грипп", example: "Tengo la gripe." },
      { word: "el resfriado", translation: "простуда", example: "Estoy resfriado." },
      { word: "la alergia", translation: "аллергия", example: "Tengo alergia al polen." },
      { word: "la receta", translation: "рецепт", example: "Necesito una receta médica." },
      { word: "tomar la temperatura", translation: "измерить температуру", example: "Voy a tomarte la temperatura." },
      { word: "la cura", translation: "лекарство / лечение", example: "No hay cura para este virus." },
      { word: "tratar", translation: "лечить", example: "El médico lo trató bien." },
      { word: "curarse", translation: "вылечиться", example: "Se curó rápidamente." },
      { word: "el hospital", translation: "больница", example: "Lo llevaron al hospital." },
      { word: "la operación", translation: "операция", example: "Le hicieron una operación." },
      { word: "la dieta", translation: "диета", example: "Sigo una dieta equilibrada." },
      { word: "hacer ejercicio", translation: "заниматься спортом", example: "Hago ejercicio tres veces por semana." },
    ],
  },
  {
    slug: "b1-medios",
    level: "B1",
    topic: "СМИ и новости",
    topicEs: "Los Medios de Comunicación",
    icon: "📰",
    words: [
      { word: "las noticias", translation: "новости", example: "Veo las noticias todos los días." },
      { word: "el periódico", translation: "газета", example: "Leo el periódico por la mañana." },
      { word: "la revista", translation: "журнал", example: "Compré una revista de viajes." },
      { word: "la televisión / la tele", translation: "телевидение", example: "Vemos la tele después de cenar." },
      { word: "la radio", translation: "радио", example: "Escucho la radio en el coche." },
      { word: "el programa", translation: "передача", example: "Mi programa favorito." },
      { word: "el periodista", translation: "журналист", example: "El periodista hizo buenas preguntas." },
      { word: "el titular", translation: "заголовок", example: "El titular era muy llamativo." },
      { word: "informar", translation: "информировать", example: "Nos informaron del cambio." },
      { word: "anunciar", translation: "объявлять", example: "Anunciaron su dimisión." },
      { word: "la entrevista", translation: "интервью", example: "Hicieron una entrevista al actor." },
      { word: "el reportaje", translation: "репортаж", example: "Un reportaje sobre el cambio climático." },
      { word: "emitir", translation: "транслировать", example: "Emiten el partido en directo." },
      { word: "la publicidad", translation: "реклама", example: "Hay demasiada publicidad." },
      { word: "las redes sociales", translation: "соцсети", example: "Uso las redes sociales para trabajar." },
    ],
  },

  // ===== B2 ==========================================================
  {
    slug: "b2-argumentacion",
    level: "B2",
    topic: "Аргументация и дискуссия",
    topicEs: "La Argumentación y el Debate",
    icon: "🎯",
    words: [
      { word: "el argumento", translation: "аргумент", example: "Presentó argumentos sólidos." },
      { word: "refutar", translation: "опровергать", example: "Refutó todas las acusaciones." },
      { word: "rebatir", translation: "оспаривать", example: "Nadie pudo rebatir su teoría." },
      { word: "contradecir", translation: "противоречить", example: "Sus hechos contradicen su teoría." },
      { word: "justificar", translation: "оправдывать", example: "Justificó su decisión." },
      { word: "fundamentar", translation: "обосновывать", example: "Fundamentó su tesis con datos." },
      { word: "la hipótesis", translation: "гипотеза", example: "Planteó una hipótesis interesante." },
      { word: "la conclusión", translation: "вывод", example: "Llegamos a la misma conclusión." },
      { word: "la premisa", translation: "предпосылка", example: "Partimos de una premisa falsa." },
      { word: "el razonamiento", translation: "рассуждение", example: "Su razonamiento es lógico." },
      { word: "la evidencia", translation: "доказательство", example: "No hay evidencia suficiente." },
      { word: "la tesis", translation: "тезис", example: "Defendió su tesis doctoral." },
      { word: "poner en duda", translation: "ставить под сомнение", example: "Pusieron en duda su palabra." },
      { word: "subrayar", translation: "подчёркивать", example: "Quiero subrayar este punto." },
      { word: "resaltar", translation: "выделять", example: "Resaltó la importancia del tema." },
      { word: "matizar", translation: "уточнять / смягчать", example: "Quisiera matizar lo que dije." },
    ],
  },
  {
    slug: "b2-ciencia",
    level: "B2",
    topic: "Наука и технологии",
    topicEs: "La Ciencia y la Tecnología",
    icon: "🔬",
    words: [
      { word: "el descubrimiento", translation: "открытие", example: "Anunciaron un gran descubrimiento." },
      { word: "la investigación", translation: "исследование", example: "Publicó sus investigaciones." },
      { word: "el experimento", translation: "эксперимент", example: "El experimento fue un éxito." },
      { word: "el avance", translation: "прогресс / достижение", example: "Un gran avance en la medicina." },
      { word: "la hipótesis", translation: "гипотеза", example: "Confirmaron la hipótesis inicial." },
      { word: "el dato", translation: "данные", example: "Los datos son concluyentes." },
      { word: "la teoría", translation: "теория", example: "La teoría de la relatividad." },
      { word: "el científico", translation: "учёный", example: "Los científicos hacen investigaciones." },
      { word: "la inteligencia artificial", translation: "искусственный интеллект", example: "La IA está en todas partes." },
      { word: "el algoritmo", translation: "алгоритм", example: "Crearon un algoritmo nuevo." },
      { word: "la innovación", translation: "инновация", example: "La innovación tecnológica avanza." },
      { word: "el espacio", translation: "космос", example: "La exploración del espacio." },
      { word: "el medioambiente", translation: "окружающая среда", example: "Hay que proteger el medioambiente." },
      { word: "la sostenibilidad", translation: "устойчивость", example: "Apuestan por la sostenibilidad." },
      { word: "el cambio climático", translation: "изменение климата", example: "El cambio climático es real." },
    ],
  },
  {
    slug: "b2-problemas-sociales",
    level: "B2",
    topic: "Социальные проблемы",
    topicEs: "Los Problemas Sociales",
    icon: "🌍",
    words: [
      { word: "la pobreza", translation: "бедность", example: "La pobreza es un problema grave." },
      { word: "la desigualdad", translation: "неравенство", example: "La desigualdad económica crece." },
      { word: "el paro / el desempleo", translation: "безработица", example: "El paro afecta a los jóvenes." },
      { word: "la discriminación", translation: "дискриминация", example: "Luchamos contra la discriminación." },
      { word: "el racismo", translation: "расизм", example: "Hay que combatir el racismo." },
      { word: "la inmigración", translation: "иммиграция", example: "La inmigración es un tema complejo." },
      { word: "la emigración", translation: "эмиграция", example: "La emigración de jóvenes preocupa." },
      { word: "la violencia", translation: "насилие", example: "Cero tolerancia a la violencia." },
      { word: "la corrupción", translation: "коррупция", example: "Denunciaron casos de corrupción." },
      { word: "el refugiado", translation: "беженец", example: "Acogen a los refugiados." },
      { word: "los derechos humanos", translation: "права человека", example: "Defiende los derechos humanos." },
      { word: "la marginación", translation: "маргинализация", example: "Sufren marginación social." },
      { word: "la integración", translation: "интеграция", example: "Fomentan la integración de inmigrantes." },
      { word: "la brecha digital", translation: "цифровое неравенство", example: "La brecha digital separa generaciones." },
      { word: "el feminismo", translation: "феминизм", example: "El feminismo ha avanzado mucho." },
    ],
  },
  {
    slug: "b2-literatura",
    level: "B2",
    topic: "Литература и искусство",
    topicEs: "La Literatura y el Arte",
    icon: "📚",
    words: [
      { word: "la novela", translation: "роман", example: "Escribió una novela histórica." },
      { word: "el cuento", translation: "рассказ", example: "Leemos cuentos de Borges." },
      { word: "el poema", translation: "стихотворение", example: "Recitó un poema de Neruda." },
      { word: "el autor / la autora", translation: "автор", example: "Mi autora favorita es Allende." },
      { word: "el personaje", translation: "персонаж", example: "Los personajes son complejos." },
      { word: "la trama", translation: "сюжет", example: "La trama es fascinante." },
      { word: "el género literario", translation: "литературный жанр", example: "El ensayo es un género literario." },
      { word: "la pintura", translation: "живопись", example: "Admiro la pintura de Goya." },
      { word: "el cuadro", translation: "картина", example: "El cuadro está en el museo." },
      { word: "el museo", translation: "музей", example: "Visité el Museo del Prado." },
      { word: "la escultura", translation: "скульптура", example: "Una escultura de bronce." },
      { word: "la exposición", translation: "выставка", example: "Fuimos a una exposición de arte." },
      { word: "el artista", translation: "художник / артист", example: "Es un artista talentoso." },
      { word: "la obra maestra", translation: "шедевр", example: "El Guernica es una obra maestra." },
      { word: "la crítica", translation: "критика", example: "La crítica fue positiva." },
    ],
  },
  {
    slug: "b2-economia",
    level: "B2",
    topic: "Экономика и финансы",
    topicEs: "La Economía y las Finanzas",
    icon: "💰",
    words: [
      { word: "la economía", translation: "экономика", example: "La economía mundial crece." },
      { word: "la crisis", translation: "кризис", example: "Sufrimos una crisis económica." },
      { word: "la inflación", translation: "инфляция", example: "La inflación sube este año." },
      { word: "la recesión", translation: "рецессия", example: "El país entra en recesión." },
      { word: "el presupuesto", translation: "бюджет", example: "Aprobamos el presupuesto anual." },
      { word: "la inversión", translation: "инвестиция", example: "Hicieron una gran inversión." },
      { word: "el beneficio", translation: "прибыль", example: "Los beneficios aumentaron." },
      { word: "la pérdida", translation: "убыток", example: "Tuvieron pérdidas este trimestre." },
      { word: "el mercado", translation: "рынок", example: "El mercado laboral es difícil." },
      { word: "la oferta y la demanda", translation: "предложение и спрос", example: "La ley de oferta y demanda." },
      { word: "el ahorro", translation: "накопления", example: "Tiene unos ahorros importantes." },
      { word: "el préstamo", translation: "заём", example: "Pidió un préstamo al banco." },
      { word: "la hipoteca", translation: "ипотека", example: "Pagan la hipoteca cada mes." },
      { word: "el impuesto", translation: "налог", example: "Subieron los impuestos." },
      { word: "la empresa", translation: "предприятие", example: "Trabajo en una empresa grande." },
    ],
  },

  // ===== C1 ==========================================================
  {
    slug: "c1-expresiones-idiomaticas",
    level: "C1",
    topic: "Идиомы и выражения",
    topicEs: "Expresiones Idiomáticas",
    icon: "🗣️",
    words: [
      { word: "estar en las nubes", translation: "витать в облаках", example: "Siempre está en las nubes." },
      { word: "costar un ojo de la cara", translation: "стоить целое состояние", example: "Ese coche cuesta un ojo de la cara." },
      { word: "no tener ni idea", translation: "не иметь ни малейшего понятия", example: "No tengo ni idea de dónde está." },
      { word: "dar la lata", translation: "надоедать", example: "Deja de dar la lata." },
      { word: "hacerse el sueco", translation: "прикидываться дураком", example: "Se hace el sueco cuando le pregunto." },
      { word: "estar hasta el cuello", translation: "быть по горло сытым", example: "Estoy hasta el cuello de trabajo." },
      { word: "tirar la casa por la ventana", translation: "гулять на широкую ногу", example: "En su boda tiraron la casa por la ventana." },
      { word: "no ver tres en un burro", translation: "не видеть дальше собственного носа", example: "Sin gafas no veo tres en un burro." },
      { word: "ser pan comido", translation: "быть проще простого", example: "Este examen es pan comido." },
      { word: "coger el toro por los cuernos", translation: "взять быка за рога", example: "Hay que coger el toro por los cuernos." },
      { word: "estar como una cabra", translation: "быть не в своём уме", example: "Está como una cabra si cree eso." },
      { word: "no dar pie con bola", translation: "не ладиться", example: "Hoy no doy pie con bola." },
      { word: "ahogarse en un vaso de agua", translation: "делать из мухи слона", example: "Te ahogas en un vaso de agua." },
      { word: "dar gato por liebre", translation: "всучить подделку", example: "Me dieron gato por liebre." },
      { word: "tomar el pelo", translation: "дразнить", example: "Deja de tomarle el pelo." },
    ],
  },
  {
    slug: "c1-lenguaje-formal",
    level: "C1",
    topic: "Формальный регистр",
    topicEs: "Lenguaje Formal",
    icon: "🎩",
    words: [
      { word: "por consiguiente", translation: "следовательно", example: "No estudió; por consiguiente, suspendió." },
      { word: "no obstante", translation: "тем не менее", example: "Llovió; no obstante, salimos." },
      { word: "asimismo", translation: "равным образом", example: "Asimismo, quiero añadir un punto." },
      { word: "en definitiva", translation: "в конечном счёте", example: "En definitiva, es tu decisión." },
      { word: "a tenor de", translation: "в соответствии с", example: "A tenor de los resultados, es positivo." },
      { word: "con miras a", translation: "с целью", example: "Trabajamos con miras a mejorar." },
      { word: "al respecto", translation: "по этому поводу", example: "No dijo nada al respecto." },
      { word: "en virtud de", translation: "на основании", example: "En virtud de la ley vigente." },
      { word: "suscitar", translation: "вызывать", example: "Suscitó un debate interesante." },
      { word: "conllevar", translation: "влечь за собой", example: "El cambio conlleva riesgos." },
      { word: "trascender", translation: "выходить за рамки", example: "Su obra trascendió fronteras." },
      { word: "resultar pertinente", translation: "быть уместным", example: "No resulta pertinente comentarlo." },
      { word: "objetivamente", translation: "объективно", example: "Hay que analizarlo objetivamente." },
      { word: "el discernimiento", translation: "проницательность", example: "Mostró gran discernimiento." },
    ],
  },
  {
    slug: "c1-regionalismos",
    level: "C1",
    topic: "Регионализмы",
    topicEs: "Regionalismos del Español",
    icon: "🌎",
    words: [
      { word: "vos (Argentina)", translation: "ты (аргентинская форма)", example: "¿Vos querés un café?" },
      { word: "ché (Argentina)", translation: "эй / послушай", example: "Che, ¿vamos al cine?" },
      { word: "plata (América)", translation: "деньги", example: "No tengo plata." },
      { word: "lana (México)", translation: "деньги", example: "Cuesta mucha lana." },
      { word: "guay (España)", translation: "круто", example: "¡Qué guay!" },
      { word: "vale (España)", translation: "окей / ладно", example: "Vale, nos vemos luego." },
      { word: "mande (México)", translation: "что? / простите?", example: "—¿Juan? —¿Mande?" },
      { word: "computadora (América)", translation: "компьютер", example: "Mi computadora es nueva." },
      { word: "ordenador (España)", translation: "компьютер", example: "Mi ordenador es nuevo." },
      { word: "coche (España)", translation: "машина", example: "Mi coche es rojo." },
      { word: "carro (América)", translation: "машина", example: "Mi carro es rojo." },
      { word: "zumo (España)", translation: "сок", example: "Quiero un zumo de naranja." },
      { word: "jugo (América)", translation: "сок", example: "Quiero un jugo de naranja." },
      { word: "coger (España)", translation: "брать", example: "Voy a coger el autobús." },
      { word: "tomar (América)", translation: "брать / брать транспорт", example: "Voy a tomar el autobús." },
    ],
  },
  {
    slug: "c1-conceptos-abstractos",
    level: "C1",
    topic: "Абстрактные концепции",
    topicEs: "Conceptos Abstractos",
    icon: "🧠",
    words: [
      { word: "la esencia", translation: "сущность", example: "La esencia del problema es otro." },
      { word: "el fundamento", translation: "основание", example: "El fundamento de su teoría." },
      { word: "el ámbito", translation: "сфера", example: "En el ámbito de la ciencia." },
      { word: "el trasfondo", translation: "подоплёка", example: "Hay un trasfondo político." },
      { word: "la índole", translation: "характер / природа", example: "Es un problema de índole económica." },
      { word: "el devenir", translation: "становление / ход", example: "El devenir histórico." },
      { word: "el entramado", translation: "сплетение", example: "Un entramado de mentiras." },
      { word: "el impairment", translation: "обесценение", example: "El impairment de activos." },
      { word: "la intrínseco", translation: "внутренне присущий", example: "El valor intrínseco." },
      { word: "la connotación", translation: "коннотация", example: "Tiene connotaciones negativas." },
      { word: "la denotación", translation: "денотация", example: "La denotación literal de la palabra." },
      { word: "el paradigma", translation: "парадигма", example: "Un cambio de paradigma." },
      { word: "la coyuntura", translation: "обстановка / ситуация", example: "En la coyuntura actual." },
      { word: "el prejuicio", translation: "предрассудок", example: "Hay que superar los prejuicios." },
    ],
  },
  {
    slug: "c1-literario",
    level: "C1",
    topic: "Литературная лексика",
    topicEs: "Léxico Literario",
    icon: "✒️",
    words: [
      { word: "la metáfora", translation: "метафора", example: "Usa una metáfora hermosa." },
      { word: "la alegoría", translation: "аллегория", example: "La obra es una alegoría." },
      { word: "el símbolo", translation: "символ", example: "La paloma es símbolo de paz." },
      { word: "la elocuencia", translation: "красноречие", example: "Habló con elocuencia." },
      { word: "el matiz", translation: "оттенок (смысла)", example: "Hay un matiz importante." },
      { word: "la prosa", translation: "проза", example: "Escribe en prosa poética." },
      { word: "el verso", translation: "стих", example: "Recitó los versos de memoria." },
      { word: "la estrofa", translation: "строфа", example: "La primera estrofa del poema." },
      { word: "el ritmo", translation: "ритм", example: "El ritmo de la narración." },
      { word: "la ambientación", translation: "обстановка (в произведении)", example: "La ambientación es fantástica." },
      { word: "la voz narrativa", translation: "голос рассказчика", example: "La voz narrativa es en primera persona." },
      { word: "el recurso literario", translation: "литературный приём", example: "Usa muchos recursos literarios." },
      { word: "la ironía", translation: "ирония", example: "La ironía recorre toda la obra." },
      { word: "la paradoja", translation: "парадокс", example: "Es una paradoja fascinante." },
    ],
  },
];

// ---------- Helpers --------------------------------------------------

/** Group topics by level. */
export function groupVocabByLevel(): Record<string, VocabTopic[]> {
  const grouped: Record<string, VocabTopic[]> = {};
  for (const topic of VOCAB_TOPICS) {
    (grouped[topic.level] ||= []).push(topic);
  }
  return grouped;
}

/** Count total words across all topics. */
export function totalVocabWords(): number {
  return VOCAB_TOPICS.reduce((sum, t) => sum + t.words.length, 0);
}
