// =====================================================================
// Curated vocabulary catalog by CEFR level and topic.
// ---------------------------------------------------------------------
// Static data — served instantly, costs zero tokens and zero DB queries.
// Each topic has 12-20 words with Spanish term, Russian translation,
// and an example sentence. Users can add any word to their personal
// dictionary from the vocabulary-topics page.
// =====================================================================

export interface VocabWord {
  word: string;
  translation: string;
  example: string;
}

export interface VocabTopic {
  slug: string;
  level: "A1" | "A2" | "B1" | "B2" | "C1";
  topic: string;
  topicEs: string;
  icon: string;
  words: VocabWord[];
}

export const VOCAB_TOPICS: VocabTopic[] = [
  // ===== A1 ==========================================================
  {
    slug: "a1-familia",
    level: "A1",
    topic: "Семья",
    topicEs: "La Familia",
    icon: "👨‍👩‍👧‍👦",
    words: [
      { word: "la familia", translation: "семья", example: "Mi familia es grande." },
      { word: "el padre", translation: "отец", example: "Mi padre es médico." },
      { word: "la madre", translation: "мать", example: "Mi madre cocina muy bien." },
      { word: "el hermano", translation: "брат", example: "Tengo un hermano mayor." },
      { word: "la hermana", translation: "сестра", example: "Mi hermana estudia en Madrid." },
      { word: "el hijo / la hija", translation: "сын / дочь", example: "Sus hijos son pequeños." },
      { word: "el abuelo / la abuela", translation: "дедушка / бабушка", example: "Mis abuelos viven en Sevilla." },
      { word: "el tío / la tía", translation: "дядя / тётя", example: "Mi tía es profesora." },
      { word: "el primo / la prima", translation: "двоюродный брат / сестра", example: "Mis primos son divertidos." },
      { word: "el marido / el esposo", translation: "муж", example: "Su marido es arquitecto." },
      { word: "la mujer / la esposa", translation: "жена", example: "Su mujer es enfermera." },
      { word: "el novio / la novia", translation: "парень / девушка", example: "Mi novia es italiana." },
      { word: "el bebé", translation: "младенец", example: "El bebé tiene seis meses." },
      { word: "el nieto / la nieta", translation: "внук / внучка", example: "Sus nietos viven en México." },
      { word: "mayor", translation: "старший", example: "Mi hermano es mayor que yo." },
      { word: "menor", translation: "младший", example: "Mi hermana es menor." },
      { word: "casarse", translation: "жениться", example: "Se casaron el año pasado." },
      { word: "vivir", translation: "жить", example: "Vivimos juntos en Barcelona." },
      { word: "el sobrino / la sobrina", translation: "племянник / племянница", example: "Mi sobrina tiene cinco años." },
      { word: "el suegro / la suegra", translation: "свёкор / свекровь", example: "Mis suegros viven cerca." },
      { word: "el yerno / la nuera", translation: "зять / невестка", example: "Su yerno es dentista." },
      { word: "el cuñado / la cuñada", translation: "шурин / золовка", example: "Mi cuñada es española." },
      { word: "divorciarse", translation: "развестись", example: "Se divorciaron hace dos años." },
      { word: "la boda", translation: "свадьба", example: "La boda fue preciosa." },
      { word: "llamarse", translation: "называться", example: "Mi hermano se llama Carlos." },
      { word: "el nombre", translation: "имя", example: "¿Cuál es tu nombre?" },
    ],
  },
  {
    slug: "a1-comida",
    level: "A1",
    topic: "Еда и напитки",
    topicEs: "La Comida y la Bebida",
    icon: "🍽️",
    words: [
      { word: "el pan", translation: "хлеб", example: "Quiero un poco de pan." },
      { word: "el agua", translation: "вода", example: "Necesito agua, por favor." },
      { word: "el café", translation: "кофе", example: "Tomo café por la mañana." },
      { word: "la leche", translation: "молоко", example: "La leche está fría." },
      { word: "el arroz", translation: "рис", example: "Me gusta el arroz con pollo." },
      { word: "la carne", translation: "мясо", example: "No como carne, soy vegetariano." },
      { word: "el pollo", translation: "курица", example: "Pollo con patatas, por favor." },
      { word: "el pescado", translation: "рыба", example: "El pescado está muy bueno." },
      { word: "la fruta", translation: "фрукт", example: "Como fruta todos los días." },
      { word: "la manzana", translation: "яблоко", example: "Una manzana roja, por favor." },
      { word: "el plátano", translation: "банан", example: "Los plátanos son dulces." },
      { word: "el naranja / el zumo", translation: "апельсин / сок", example: "Zumo de naranja natural." },
      { word: "el queso", translation: "сыр", example: "El queso manchego es famoso." },
      { word: "el huevo", translation: "яйцо", example: "Dos huevos fritos, por favor." },
      { word: "la ensalada", translation: "салат", example: "Una ensalada mixta." },
      { word: "la sopa", translation: "суп", example: "La sopa está caliente." },
      { word: "el postre", translation: "десерт", example: "¿Qué hay de postre?" },
      { word: "beber", translation: "пить", example: "Bebo mucha agua." },
      { word: "comer", translation: "есть", example: "Comemos a las dos." },
      { word: "el desayuno", translation: "завтрак", example: "El desayuno es la primera comida." },
      { word: "el almuerzo / la comida", translation: "обед", example: "La comida es a las dos." },
      { word: "la cena", translation: "ужин", example: "Cenamos a las nueve." },
      { word: "el aceite", translation: "масло (растительное)", example: "Aceite de oliva, por favor." },
      { word: "la sal", translation: "соль", example: "Pásame la sal, por favor." },
      { word: "el azúcar", translation: "сахар", example: "Un café con azúcar." },
      { word: "la cebolla", translation: "лук", example: "Corta la cebolla pequeña." },
      { word: "el tomate", translation: "помидор", example: "Una ensalada de tomate." },
      { word: "la patata / la papa", translation: "картофель", example: "Patatas fritas, por favor." },
      { word: "el limón", translation: "лимон", example: "Zumo de limón." },
      { word: "la naranja", translation: "апельсин", example: "Las naranjas de Valencia." },
      { word: "la verdura", translation: "овощ", example: "Como muchas verduras." },
      { word: "el vino", translation: "вино", example: "Una copa de vino tinto." },
      { word: "la cerveza", translation: "пиво", example: "Dos cervezas, por favor." },
      { word: "rico / sabroso", translation: "вкусный", example: "¡Está muy rico!" },
      { word: "amargo", translation: "горький", example: "El café está amargo." },
      { word: "dulce", translation: "сладкий", example: "El pastel es muy dulce." },
    ],
  },
  {
    slug: "a1-casa",
    level: "A1",
    topic: "Дом и мебель",
    topicEs: "La Casa y el Mueble",
    icon: "🏠",
    words: [
      { word: "la casa", translation: "дом", example: "Mi casa es bonita." },
      { word: "el piso", translation: "квартира / этаж", example: "Vivo en un piso pequeño." },
      { word: "la habitación / el cuarto", translation: "комната", example: "Mi habitación es grande." },
      { word: "la cocina", translation: "кухня", example: "La cocina está limpia." },
      { word: "el baño", translation: "ванная", example: "¿Dónde está el baño?" },
      { word: "el salón", translation: "гостиная", example: "Vemos la tele en el salón." },
      { word: "la puerta", translation: "дверь", example: "Cierra la puerta, por favor." },
      { word: "la ventana", translation: "окно", example: "Abre la ventana, hace calor." },
      { word: "la mesa", translation: "стол", example: "Los libros están en la mesa." },
      { word: "la silla", translation: "стул", example: "Siéntate en esta silla." },
      { word: "la cama", translation: "кровать", example: "Mi cama es cómoda." },
      { word: "el sofá", translation: "диван", example: "El sofá es nuevo." },
      { word: "el armario", translation: "шкаф", example: "La ropa está en el armario." },
      { word: "la lámpara", translation: "лампа", example: "Enciende la lámpara." },
      { word: "la llave", translation: "ключ", example: "¿Tienes las llaves?" },
      { word: "la escalera", translation: "лестница", example: "Sube por la escalera." },
      { word: "el jardín", translation: "сад", example: "Tenemos un jardín pequeño." },
      { word: "el garaje", translation: "гараж", example: "El coche está en el garaje." },
      { word: "el techo", translation: "потолок / крыша", example: "El techo tiene una gotera." },
      { word: "el suelo", translation: "пол", example: "El suelo es de madera." },
      { word: "la alfombra", translation: "ковёр", example: "Hay una alfombra en el salón." },
      { word: "la nevera / el frigorífico", translation: "холодильник", example: "La leche está en la nevera." },
      { word: "el horno", translation: "духовка", example: "Ponlo en el horno diez minutos." },
      { word: "el espejo", translation: "зеркало", example: "Mírate en el espejo." },
      { word: "el cuadro", translation: "картина", example: "Hay un cuadro en la pared." },
      { word: "la toalla", translation: "полотенце", example: "Secarse con la toalla." },
      { word: "el jabón", translation: "мыло", example: "Lávate las manos con jabón." },
      { word: "la ducha", translation: "душ", example: "Me ducho por la mañana." },
      { word: "el inodoro", translation: "туалет", example: "El inodoro está estropeado." },
      { word: "la lavadora", translation: "стиральная машина", example: "Pon la ropa en la lavadora." },
      { word: "limpio / limpia", translation: "чистый", example: "La casa está muy limpia." },
      { word: "sucio / sucia", translation: "грязный", example: "El baño está sucio." },
    ],
  },
  {
    slug: "a1-numeros-tiempo",
    level: "A1",
    topic: "Время и дни недели",
    topicEs: "El Tiempo y los Días",
    icon: "🕐",
    words: [
      { word: "el día", translation: "день", example: "Todos los días estudio español." },
      { word: "la noche", translation: "ночь", example: "Por la noche duermo." },
      { word: "la mañana", translation: "утро", example: "Por la mañana desayuno." },
      { word: "la tarde", translation: "день/вечер", example: "Por la tarde trabajo." },
      { word: "la semana", translation: "неделя", example: "Hay siete días en una semana." },
      { word: "el mes", translation: "месяц", example: "Doce meses tiene un año." },
      { word: "el año", translation: "год", example: "El año que viene viajaré." },
      { word: "hoy", translation: "сегодня", example: "Hoy hace sol." },
      { word: "mañana", translation: "завтра", example: "Mañana tengo examen." },
      { word: "ayer", translation: "вчера", example: "Ayer fui al cine." },
      { word: "lunes", translation: "понедельник", example: "El lunes trabajo mucho." },
      { word: "martes", translation: "вторник", example: "El martes tengo clase." },
      { word: "miércoles", translation: "среда", example: "El miércoles juego al tenis." },
      { word: "jueves", translation: "четверг", example: "El jueves voy al gimnasio." },
      { word: "viernes", translation: "пятница", example: "El viernes salgo con amigos." },
      { word: "sábado", translation: "суббота", example: "El sábado descanso." },
      { word: "domingo", translation: "воскресенье", example: "El domingo visito a mi familia." },
      { word: "la hora", translation: "час", example: "¿Qué hora es?" },
      { word: "el minuto", translation: "минута", example: "Cinco minutos más." },
      { word: "enero", translation: "январь", example: "En enero hace frío." },
      { word: "febrero", translation: "февраль", example: "Mi cumpleaños es en febrero." },
      { word: "marzo", translation: "март", example: "En marzo empieza la primavera." },
      { word: "abril", translation: "апрель", example: "En abril llueve mucho." },
      { word: "mayo", translation: "май", example: "El cinco de mayo." },
      { word: "junio", translation: "июнь", example: "En junio terminan las clases." },
      { word: "julio", translation: "июль", example: "En julio voy de vacaciones." },
      { word: "agosto", translation: "август", example: "Agosto es un mes caluroso." },
      { word: "septiembre", translation: "сентябрь", example: "En septiembre vuelvo al trabajo." },
      { word: "octubre", translation: "октябрь", example: "En octubre caen las hojas." },
      { word: "noviembre", translation: "ноябрь", example: "Noviembre es otoñal." },
      { word: "diciembre", translation: "декабрь", example: "En diciembre es Navidad." },
      { word: "y media", translation: "половина (часа)", example: "Son las tres y media." },
      { word: "y cuarto", translation: "четверть часа", example: "Son las cuatro y cuarto." },
      { word: "menos cuarto", translation: "без четверти", example: "Son las cinco menos cuarto." },
      { word: "de la mañana", translation: "утра", example: "Son las ocho de la mañana." },
      { word: "de la tarde", translation: "дня / вечера", example: "A las cinco de la tarde." },
      { word: "de la noche", translation: "ночи", example: "A las once de la noche." },
      { word: "siempre", translation: "всегда", example: "Siempre desayuno café." },
      { word: "nunca", translation: "никогда", example: "Nunca como carne." },
      { word: "a veces", translation: "иногда", example: "A veces voy andando." },
      { word: "muchas veces", translation: "часто", example: "Voy muchas veces al cine." },
      { word: "primero", translation: "сначала / первый", example: "Primero, desayuno." },
      { word: "después / luego", translation: "потом / затем", example: "Después, voy al trabajo." },
      { word: "finalmente / al final", translation: "наконец", example: "Al final, llegué a casa." },
      { word: "temprano", translation: "рано", example: "Me levanto temprano." },
      { word: "tarde", translation: "поздно", example: "Llegué tarde a clase." },
      { word: "ya", translation: "уже", example: "Ya terminé los deberes." },
      { word: "todavía", translation: "ещё", example: "Todavía no he comido." },
      { word: "hoy en día", translation: "в наши дни", example: "Hoy en día, todo es digital." },
      { word: "la fecha", translation: "дата", example: "¿Qué fecha es hoy?" },
      { word: "el cumpleaños", translation: "день рождения", example: "¡Feliz cumpleaños!" },
      { word: "el pasado", translation: "прошлое", example: "En el pasado, todo era distinto." },
      { word: "el futuro", translation: "будущее", example: "En el futuro, viajaré a Japón." },
    ],
  },
  {
    slug: "a1-ciudad",
    level: "A1",
    topic: "Город и ориентация",
    topicEs: "La Ciudad y las Direcciones",
    icon: "🏙️",
    words: [
      { word: "la ciudad", translation: "город", example: "Madrid es una ciudad grande." },
      { word: "la calle", translation: "улица", example: "Mi calle es muy ruidosa." },
      { word: "la plaza", translation: "площадь", example: "Nos vemos en la plaza." },
      { word: "el parque", translation: "парк", example: "El parque está cerca." },
      { word: "la tienda", translation: "магазин", example: "Hay una tienda al lado." },
      { word: "el restaurante", translation: "ресторан", example: "El restaurante es caro." },
      { word: "el café", translation: "кафе", example: "Vamos al café de la esquina." },
      { word: "el hotel", translation: "отель", example: "El hotel está en el centro." },
      { word: "el hospital", translation: "больница", example: "El hospital es nuevo." },
      { word: "la farmacia", translation: "аптека", example: "Necesito ir a la farmacia." },
      { word: "el banco", translation: "банк", example: "El banco abre a las nueve." },
      { word: "la escuela", translation: "школа", example: "La escuela está cerca de casa." },
      { word: "la estación", translation: "станция", example: "La estación de tren está allí." },
      { word: "el aeropuerto", translation: "аэропорт", example: "El aeropuerto está lejos." },
      { word: "el cine", translation: "кино", example: "Vamos al cine esta noche." },
      { word: "la biblioteca", translation: "библиотека", example: "Estudio en la biblioteca." },
      { word: "cerca", translation: "близко", example: "Está cerca de aquí." },
      { word: "lejos", translation: "далеко", example: "No está lejos." },
      { word: "derecha", translation: "право", example: "Gire a la derecha." },
      { word: "izquierda", translation: "лево", example: "A la izquierda del banco." },
      { word: "el semáforo", translation: "светофор", example: "Pasa cuando el semáforo esté verde." },
      { word: "la esquina", translation: "угол", example: "La tienda está en la esquina." },
      { word: "el centro", translation: "центр", example: "Vivo en el centro de la ciudad." },
      { word: "el museo", translation: "музей", example: "El museo del Prado es famoso." },
      { word: "la iglesia", translation: "церковь", example: "Hay una iglesia antigua aquí." },
      { word: "el puente", translation: "мост", example: "Cruzamos el puente." },
      { word: "el mercado", translation: "рынок", example: "Compramos fruta en el mercado." },
      { word: "la oficina de turismo", translation: "туристическое бюро", example: "Pregunta en la oficina de turismo." },
      { word: "perdone / disculpe", translation: "извините", example: "Perdone, ¿dónde está el museo?" },
    ],
  },
  {
    slug: "a1-colores",
    level: "A1",
    topic: "Цвета",
    topicEs: "Los Colores",
    icon: "🎨",
    words: [
      { word: "rojo / roja", translation: "красный", example: "El coche es rojo." },
      { word: "azul", translation: "синий", example: "Mi camisa es azul." },
      { word: "verde", translation: "зелёный", example: "La hierba es verde." },
      { word: "amarillo / amarilla", translation: "жёлтый", example: "El sol es amarillo." },
      { word: "blanco / blanca", translation: "белый", example: "Una camisa blanca." },
      { word: "negro / negra", translation: "чёрный", example: "Tengo un gato negro." },
      { word: "naranja", translation: "оранжевый", example: "El naranja es mi color favorito." },
      { word: "rosa", translation: "розовый", example: "Una rosa rosa." },
      { word: "morado / morada", translation: "фиолетовый", example: "Las uvas son moradas." },
      { word: "marrón", translation: "коричневый", example: "El pelo marrón." },
      { word: "gris", translation: "серый", example: "El cielo está gris." },
      { word: "claro / clara", translation: "светлый", example: "Azul claro, por favor." },
      { word: "oscuro / oscura", translation: "тёмный", example: "Prefiero el azul oscuro." },
      { word: "dorado / dorada", translation: "золотой", example: "Un reloj dorado." },
      { word: "plateado / plateada", translation: "серебряный", example: "Zapatos plateados." },
      { word: "beis", translation: "бежевый", example: "Un jersey beis." },
      { word: "turquesa", translation: "бирюзовый", example: "El mar es turquesa." },
      { word: "violeta", translation: "фиолетовый", example: "Una flor violeta." },
      { word: "granate", translation: "бордовый", example: "Un vestido granate." },
    ],
  },
  {
    slug: "a1-cuerpo",
    level: "A1",
    topic: "Тело и здоровье",
    topicEs: "El Cuerpo y la Salud",
    icon: "🫀",
    words: [
      { word: "la cabeza", translation: "голова", example: "Me duele la cabeza." },
      { word: "el pelo", translation: "волосы", example: "Tiene el pelo largo." },
      { word: "los ojos", translation: "глаза", example: "Sus ojos son azules." },
      { word: "la nariz", translation: "нос", example: "La nariz es pequeña." },
      { word: "la boca", translation: "рот", example: "Abre la boca, por favor." },
      { word: "la oreja", translation: "ухо", example: "No oigo bien de la oreja izquierda." },
      { word: "la mano", translation: "рука (кисть)", example: "Me lavé las manos." },
      { word: "el brazo", translation: "рука (от плеча)", example: "Tengo dolor en el brazo." },
      { word: "la pierna", translation: "нога", example: "Me duele la pierna." },
      { word: "el pie", translation: "ступня", example: "Los pies están fríos." },
      { word: "el diente", translation: "зуб", example: "Tengo un diente roto." },
      { word: "el corazón", translation: "сердце", example: "El corazón late rápido." },
      { word: "estar enfermo", translation: "быть больным", example: "Estoy enfermo, no voy a trabajar." },
      { word: "la medicina", translation: "лекарство", example: "Toma la medicina después de comer." },
      { word: "el médico / la médica", translation: "врач", example: "Voy al médico mañana." },
      { word: "la fiebre", translation: "температура", example: "Tengo fiebre." },
      { word: "el dolor", translation: "боль", example: "Tengo dolor de garganta." },
      { word: "el cuello", translation: "шея", example: "Me duele el cuello." },
      { word: "la espalda", translation: "спина", example: "Tengo dolor de espalda." },
      { word: "el estómago", translation: "живот", example: "Me duele el estómago." },
      { word: "el dedo", translation: "палец", example: "Me corté el dedo." },
      { word: "el hombro", translation: "плечо", example: "Le duele el hombro." },
      { word: "la cara", translation: "лицо", example: "Se lavó la cara." },
      { word: "la piel", translation: "кожа", example: "Tiene la piel suave." },
      { word: "el hueso", translation: "кость", example: "Se rompió un hueso." },
      { word: "la sangre", translation: "кровь", example: "Análisis de sangre." },
      { word: "la garganta", translation: "горло", example: "Me duele la garganta." },
      { word: "tos", translation: "кашель", example: "Tengo tos." },
    ],
  },
  {
    slug: "a1-verbos-basicos",
    level: "A1",
    topic: "Базовые глаголы",
    topicEs: "Verbos Básicos",
    icon: "⚡",
    words: [
      { word: "ser", translation: "быть (постоянно)", example: "Soy estudiante." },
      { word: "estar", translation: "быть (состояние)", example: "Estoy bien." },
      { word: "tener", translation: "иметь", example: "Tengo dos hermanos." },
      { word: "hacer", translation: "делать", example: "Hago los deberes." },
      { word: "ir", translation: "идти", example: "Voy a la escuela." },
      { word: "venir", translation: "приходить", example: "¿Viene Juan?" },
      { word: "ver", translation: "видеть", example: "Veo la tele." },
      { word: "comer", translation: "есть", example: "Como en casa." },
      { word: "beber", translation: "пить", example: "Bebo agua." },
      { word: "hablar", translation: "говорить", example: "Hablo español." },
      { word: "escuchar", translation: "слушать", example: "Escucho música." },
      { word: "leer", translation: "читать", example: "Leo un libro." },
      { word: "escribir", translation: "писать", example: "Escribo un correo." },
      { word: "trabajar", translation: "работать", example: "Trabajo en una oficina." },
      { word: "estudiar", translation: "учиться", example: "Estudio inglés." },
      { word: "vivir", translation: "жить", example: "Vivo en Madrid." },
      { word: "pensar", translation: "думать", example: "Pienso en ti." },
      { word: "querer", translation: "хотеть", example: "Quiero un café." },
      { word: "poder", translation: "мочь", example: "Puedo ayudarte." },
      { word: "deber", translation: "должен", example: "Debo estudiar más." },
      { word: "necesitar", translation: "нуждаться", example: "Necesito ayuda." },
      { word: "saber", translation: "знать", example: "Sé la respuesta." },
      { word: "conocer", translation: "быть знакомым", example: "Conozco a María." },
      { word: "comprar", translation: "покупать", example: "Compré pan." },
      { word: "vender", translation: "продавать", example: "Venden café aquí." },
      { word: "abrir", translation: "открывать", example: "Abre la ventana." },
      { word: "cerrar", translation: "закрывать", example: "Cierra la puerta." },
      { word: "empezar", translation: "начинать", example: "La clase empieza a las nueve." },
      { word: "terminar", translation: "заканчивать", example: "Terminé el trabajo." },
      { word: "preguntar", translation: "спрашивать", example: "Pregúntale a la profesora." },
      { word: "responder", translation: "отвечать", example: "Respondió correctamente." },
      { word: "ayudar", translation: "помогать", example: "Te ayudo con eso." },
      { word: "esperar", translation: "ждать / надеяться", example: "Te espero en el café." },
    ],
  },

  // ===== A2 ==========================================================
  {
    slug: "a2-viajes",
    level: "A2",
    topic: "Путешествия",
    topicEs: "Los Viajes",
    icon: "✈️",
    words: [
      { word: "el viaje", translation: "поездка", example: "Hicimos un viaje a Italia." },
      { word: "viajar", translation: "путешествовать", example: "Me gusta viajar por España." },
      { word: "el billete / el boleto", translation: "билет", example: "Compré el billete online." },
      { word: "el pasaporte", translation: "паспорт", example: "Necesito renovar el pasaporte." },
      { word: "la maleta", translation: "чемодан", example: "Hice la maleta ayer." },
      { word: "el avión", translation: "самолёт", example: "El avión llega a las tres." },
      { word: "el tren", translation: "поезд", example: "El tren se retrasó." },
      { word: "el autobús", translation: "автобус", example: "Tomamos el autobús 47." },
      { word: "el taxi", translation: "такси", example: "Llamé un taxi." },
      { word: "el hotel", translation: "отель", example: "Reservé una habitación de hotel." },
      { word: "reservar", translation: "бронировать", example: "Reservé una mesa." },
      { word: "la habitación", translation: "номер (в отеле)", example: "Quiero una habitación doble." },
      { word: "el destino", translation: "направление", example: "¿Cuál es tu destino?" },
      { word: "la llegada", translation: "прибытие", example: "La llegada es a las diez." },
      { word: "la salida", translation: "отправление", example: "La salida es a las ocho." },
      { word: "el mapa", translation: "карта", example: "Mira el mapa de la ciudad." },
      { word: "la guía", translation: "гид / путеводитель", example: "Compramos una guía de Roma." },
      { word: "perderse", translation: "заблудиться", example: "Nos perdimos en el centro." },
      { word: "el equipaje", translation: "багаж", example: "Mi equipaje pesa mucho." },
      { word: "el retraso", translation: "задержка", example: "El vuelo tiene retraso." },
      { word: "la aduana", translation: "таможня", example: "Pasan por la aduana." },
      { word: "el check-in / facturación", translation: "регистрация на рейс", example: "El check-in abre dos horas antes." },
      { word: "la puerta de embarque", translation: "выход на посадку", example: "Puerta de embarque B12." },
      { word: "el pasajero", translation: "пассажир", example: "Los pasajeros esperan el tren." },
      { word: "el itinerario", translation: "маршрут", example: "Seguimos el itinerario planificado." },
      { word: "la excursion", translation: "экскурсия", example: "Hicimos una excursión al museo." },
      { word: "el recuerdo", translation: "сувенир", example: "Compré un recuerdo para mi madre." },
      { word: "la playa", translation: "пляж", example: "Pasamos las vacaciones en la playa." },
      { word: "el apartamento", translation: "апартаменты", example: "Alquilamos un apartamento." },
    ],
  },
  {
    slug: "a2-trabajo",
    level: "A2",
    topic: "Работа и профессии",
    topicEs: "El Trabajo y las Profesiones",
    icon: "💼",
    words: [
      { word: "el trabajo", translation: "работа", example: "Mi trabajo es interesante." },
      { word: "trabajar", translation: "работать", example: "Trabajo de lunes a viernes." },
      { word: "el jefe / la jefa", translation: "начальник", example: "Mi jefe es exigente." },
      { word: "el compañero de trabajo", translation: "коллега", example: "Mis compañeros son simpáticos." },
      { word: "la oficina", translation: "офис", example: "Llego a la oficina a las nueve." },
      { word: "la reunión", translation: "собрание", example: "Hay una reunión a las diez." },
      { word: "el sueldo", translation: "зарплата", example: "Piden un aumento de sueldo." },
      { word: "el contrato", translation: "контракт", example: "Firmé un contrato temporal." },
      { word: "entrevista de trabajo", translation: "собеседование", example: "Tengo una entrevista mañana." },
      { word: "el médico", translation: "врач", example: "El médico me recetó medicina." },
      { word: "el profesor / la profesora", translation: "учитель", example: "Mi profesora es muy buena." },
      { word: "el ingeniero", translation: "инженер", example: "Es ingeniero de software." },
      { word: "el abogado / la abogada", translation: "адвокат", example: "Necesito un abogado." },
      { word: "el arquitecto", translation: "архитектор", example: "El arquitecto diseñó la casa." },
      { word: "el peluquero / la peluquera", translation: "парикмахер", example: "Voy a la peluquería." },
      { word: "el cocinero / la cocinera", translation: "повар", example: "Es un cocinero excelente." },
      { word: "el periodista", translation: "журналист", example: "Trabaja de periodista." },
      { word: "estar en paro", translation: "быть безработным", example: "Está en paro desde hace meses." },
      { word: "el sueldo", translation: "зарплата", example: "Piden un aumento de sueldo." },
      { word: "ascender", translation: "повышать", example: "Ascendieron a mi jefe." },
      { word: "despedir", translation: "уволить", example: "Despidieron a tres empleados." },
      { word: "renunciar / dimitir", translation: "уволиться", example: "Renunció por motivos personales." },
      { word: "el turno", translation: "смена", example: "Trabajo en el turno de noche." },
      { word: "la jornada", translation: "рабочий день", example: "La jornada laboral es de 8 horas." },
      { word: "las vacaciones", translation: "отпуск", example: "Cojo las vacaciones en agosto." },
      { word: "el descanso", translation: "перерыв", example: "Hacemos un descanso de 15 minutos." },
      { word: "la tarea", translation: "задача", example: "Tengo muchas tareas pendientes." },
      { word: "el proyecto", translation: "проект", example: "Trabajo en un proyecto nuevo." },
      { word: "el cliente", translation: "клиент", example: "El cliente siempre tiene razón." },
    ],
  },
  {
    slug: "a2-ropa",
    level: "A2",
    topic: "Одежда",
    topicEs: "La Ropa",
    icon: "👕",
    words: [
      { word: "la ropa", translation: "одежда", example: "Compré ropa nueva." },
      { word: "la camisa", translation: "рубашка", example: "Una camisa blanca." },
      { word: "la camiseta", translation: "футболка", example: "Llevo una camiseta de algodón." },
      { word: "los pantalones", translation: "брюки", example: "Estos pantalones son cortos." },
      { word: "el vestido", translation: "платье", example: "Un vestido rojo." },
      { word: "la falda", translation: "юбка", example: "Una falda negra." },
      { word: "la chaqueta", translation: "куртка", example: "Ponte la chaqueta, hace frío." },
      { word: "el abrigo", translation: "пальто", example: "Necesito un abrigo de invierno." },
      { word: "los zapatos", translation: "туфли / ботинки", example: "Me compré zapatos nuevos." },
      { word: "las zapatillas", translation: "кроссовки", example: "Uso zapatillas para correr." },
      { word: "las botas", translation: "сапоги", example: "Las botas son de cuero." },
      { word: "el sombrero", translation: "шляпа", example: "Lleva un sombrero grande." },
      { word: "los guantes", translation: "перчатки", example: "Ponte los guantes." },
      { word: "la bufanda", translation: "шарф", example: "Una bufanda de lana." },
      { word: "el traje", translation: "костюм", example: "Lleva traje para la boda." },
      { word: "la talla", translation: "размер", example: "¿Qué talla usa?" },
      { word: "probarse", translation: "примерять", example: "Quiero probarme esta camisa." },
      { word: "caro / cara", translation: "дорогой", example: "Es demasiado caro." },
      { word: "los calcetines", translation: "носки", example: "Me compré calcetines nuevos." },
      { word: "la ropa interior", translation: "нижнее бельё", example: "Compré ropa interior." },
      { word: "el pijama", translation: "пижама", example: "Me pongo el pijama." },
      { word: "el bañador", translation: "купальник / плавки", example: "Llevaba un bañador azul." },
      { word: "la gorra", translation: "кепка", example: "Una gorra negra." },
      { word: "el cinturón", translation: "ремень", example: "Un cinturón de cuero marrón." },
      { word: "el bolso", translation: "сумочка", example: "Compró un bolso rojo." },
      { word: "la cartera / la billetera", translation: "кошелёк", example: "Perdí la cartera." },
      { word: "los vaqueros", translation: "джинсы", example: "Llevo vaqueros azules." },
      { word: "la marca", translation: "марка / бренд", example: "Es una marca famosa." },
      { word: "rebajado", translation: "со скидкой", example: "Está rebajado un 30%." },
    ],
  },
  {
    slug: "a2-clima",
    level: "A2",
    topic: "Погода и природа",
    topicEs: "El Tiempo y la Naturaleza",
    icon: "🌤️",
    words: [
      { word: "el clima / el tiempo", translation: "погода", example: "El tiempo está bueno." },
      { word: "hace sol", translation: "солнечно", example: "Hoy hace sol." },
      { word: "hace calor", translation: "жарко", example: "En verano hace mucho calor." },
      { word: "hace frío", translation: "холодно", example: "Hace frío en diciembre." },
      { word: "llover", translation: "идти (о дожде)", example: "Está lloviendo." },
      { word: "nevar", translation: "идти (о снеге)", example: "Nieva en la sierra." },
      { word: "el viento", translation: "ветер", example: "Hay mucho viento hoy." },
      { word: "la nube", translation: "облако", example: "El cielo está nublado." },
      { word: "la tormenta", translation: "гроза", example: "Hubo una tormenta terrible." },
      { word: "la temperatura", translation: "температура", example: "La temperatura es de veinte grados." },
      { word: "el bosque", translation: "лес", example: "Paseamos por el bosque." },
      { word: "el mar", translation: "море", example: "El mar está tranquilo." },
      { word: "el río", translation: "река", example: "El río es largo." },
      { word: "la montaña", translation: "гора", example: "Subimos la montaña a pie." },
      { word: "la playa", translation: "пляж", example: "Pasamos el día en la playa." },
      { word: "el árbol", translation: "дерево", example: "Los árboles son altos." },
      { word: "la flor", translation: "цветок", example: "Las flores son bonitas." },
      { word: "el animal", translation: "животное", example: "Los animales del bosque." },
      { word: "la estación", translation: "время года", example: "Mi estación favorita es el otoño." },
      { word: "la primavera", translation: "весна", example: "En primavera florecen las flores." },
      { word: "el verano", translation: "лето", example: "En verano hace calor." },
      { word: "el otoño", translation: "осень", example: "En otoño caen las hojas." },
      { word: "el invierno", translation: "зима", example: "En invierno nieva." },
      { word: "la tormenta", translation: "гроза", example: "Hubo una tormenta anoche." },
      { word: "el rayo", translation: "молния", example: "Cayó un rayo." },
      { word: "el desierto", translation: "пустыня", example: "El desierto del Sahara." },
      { word: "el lago", translation: "озеро", example: "Nadamos en el lago." },
      { word: "la isla", translation: "остров", example: "Una isla tropical." },
      { word: "el paisaje", translation: "пейзаж", example: "Qué paisaje tan bonito." },
    ],
  },
  {
    slug: "a2-deportes",
    level: "A2",
    topic: "Спорт и хобби",
    topicEs: "Los Deportes y los Aficiones",
    icon: "⚽",
    words: [
      { word: "el deporte", translation: "спорт", example: "Me encanta el deporte." },
      { word: "jugar", translation: "играть", example: "Juego al fútbol los sábados." },
      { word: "el fútbol", translation: "футбол", example: "El fútbol es el deporte más popular." },
      { word: "el baloncesto", translation: "баскетбол", example: "Juega al baloncesto." },
      { word: "el tenis", translation: "теннис", example: "Juego al tenis los lunes." },
      { word: "nadar", translation: "плавать", example: "Nado en la piscina." },
      { word: "correr", translation: "бегать", example: "Corro cinco kilómetros al día." },
      { word: "la piscina", translation: "бассейн", example: "Voy a la piscina." },
      { word: "el gimnasio", translation: "спортзал", example: "Entreno en el gimnasio." },
      { word: "el equipo", translation: "команда", example: "Mi equipo ganó el partido." },
      { word: "el partido", translation: "матч", example: "Vimos el partido en la tele." },
      { word: "ganar", translation: "выигрывать", example: "Ganamos tres a cero." },
      { word: "perder", translation: "проигрывать", example: "Perdimos el partido." },
      { word: "el aficionado", translation: "болельщик", example: "Soy aficionado del Real Madrid." },
      { word: "el hobby / la afición", translation: "хобби", example: "Mi afición es leer." },
      { word: "tocar la guitarra", translation: "играть на гитаре", example: "Toca la guitarra muy bien." },
      { word: "pintar", translation: "рисовать", example: "Pinta paisajes." },
      { word: "bailar", translation: "танцевать", example: "Bailamos salsa." },
      { word: "el fútbol", translation: "футбол", example: "El fútbol es el deporte más popular." },
      { word: "la raqueta", translation: "ракетка", example: "Compré una raqueta nueva." },
      { word: "la pelota / el balón", translation: "мяч", example: "Pásame la pelota." },
      { word: "entrenar", translation: "тренироваться", example: "Entreno tres días a la semana." },
      { word: "el entrenador", translation: "тренер", example: "El entrenador nos motivó." },
      { word: "la competición", translation: "соревнование", example: "Ganó la competición nacional." },
      { word: "la medalla", translation: "медаль", example: "Ganó una medalla de oro." },
      { word: "patinar", translation: "кататься на коньках", example: "Patino sobre hielo." },
      { word: "esquiar", translation: "кататься на лыжах", example: "Esquiamos en los Pirineos." },
      { word: "montar en bici", translation: "ездить на велосипеде", example: "Montamos en bici por el parque." },
      { word: "fotografía", translation: "фотография (хобби)", example: "La fotografía es mi afición." },
    ],
  },
  {
    slug: "a2-compras",
    level: "A2",
    topic: "Покупки",
    topicEs: "Las Compras",
    icon: "🛒",
    words: [
      { word: "comprar", translation: "покупать", example: "Compré pan en la panadería." },
      { word: "la tienda", translation: "магазин", example: "Hay muchas tiendas en el centro." },
      { word: "el supermercado", translation: "супермаркет", example: "Voy al supermercado los viernes." },
      { word: "el precio", translation: "цена", example: "¿Cuál es el precio?" },
      { word: "caro / cara", translation: "дорогой", example: "Es demasiado caro." },
      { word: "barato / barata", translation: "дешёвый", example: "Está muy barato." },
      { word: "pagar", translation: "платить", example: "Pago con tarjeta." },
      { word: "la tarjeta de crédito", translation: "кредитная карта", example: "¿Aceptan tarjeta de crédito?" },
      { word: "el dinero", translation: "деньги", example: "Necesito sacar dinero." },
      { word: "el cambio", translation: "сдача", example: "Guarde el cambio." },
      { word: "el descuento / la rebaja", translation: "скидка", example: "Hay un descuento del 20%." },
      { word: "la talla", translation: "размер", example: "¿Lo tienen en otra talla?" },
      { word: "la caja", translation: "касса", example: "Pague en la caja." },
      { word: "el ticket / el recibo", translation: "чек", example: "Guarde el recibo." },
      { word: "probar", translation: "примерять", example: "¿Puedo probármelo?" },
      { word: "vender", translation: "продавать", example: "Venden fruta fresca." },
      { word: "la ganga", translation: "выгодная покупка", example: "¡Qué ganga!" },
      { word: "el mostrador", translation: "прилавок", example: "Pregunté en el mostrador." },
      { word: "la bolsa", translation: "пакет / сумка", example: "Necesito una bolsa." },
      { word: "la garantía", translation: "гарантия", example: "Tiene dos años de garantía." },
      { word: "devolver", translation: "вернуть (товар)", example: "Quiero devolver esta camisa." },
      { word: "el producto", translation: "продукт / товар", example: "Este producto es excelente." },
      { word: "la marca blanca", translation: "собственная марка", example: "Es un producto de marca blanca." },
      { word: "la liquidación", translation: "распродажа", example: "Hay liquidación en la tienda." },
      { word: "el cupón", translation: "купон", example: "Tengo un cupón de descuento." },
      { word: "gratuito", translation: "бесплатный", example: "La entrega es gratuita." },
      { word: "encargar / pedir", translation: "заказать", example: "Encargué un libro online." },
    ],
  },
  {
    slug: "a2-tecnologia",
    level: "A2",
    topic: "Технологии",
    topicEs: "La Tecnología",
    icon: "📱",
    words: [
      { word: "el teléfono", translation: "телефон", example: "Mi teléfono es nuevo." },
      { word: "el móvil", translation: "мобильный", example: "Uso el móvil para todo." },
      { word: "la computadora / el ordenador", translation: "компьютер", example: "Trabajo con el ordenador." },
      { word: "el internet", translation: "интернет", example: "No tengo internet en casa." },
      { word: "el correo electrónico", translation: "эл. почта", example: "Te envié un correo." },
      { word: "el mensaje", translation: "сообщение", example: "Te dejé un mensaje." },
      { word: "la aplicación / la app", translation: "приложение", example: "Descargué una app nueva." },
      { word: "la pantalla", translation: "экран", example: "La pantalla es grande." },
      { word: "el teclado", translation: "клавиатура", example: "El teclado está sucio." },
      { word: "el ratón", translation: "мышь", example: "Necesito un ratón nuevo." },
      { word: "la cámara", translation: "камера", example: "Saqué fotos con la cámara." },
      { word: "la batería", translation: "батарея", example: "La batería está baja." },
      { word: "cargar", translation: "заряжать", example: "Tengo que cargar el móvil." },
      { word: "descargar", translation: "скачивать", example: "Descargué la película." },
      { word: "la contraseña", translation: "пароль", example: "Olvidé mi contraseña." },
      { word: "el wifi", translation: "вай-фай", example: "¿Cuál es la contraseña del wifi?" },
      { word: "el archivo", translation: "файл", example: "Guardé el archivo en el escritorio." },
      { word: "la carpeta", translation: "папка", example: "Ponlo en la carpeta de fotos." },
      { word: "el enlace", translation: "ссылка", example: "Te envié un enlace." },
      { word: "el portátil", translation: "ноутбук", example: "Compré un portátil nuevo." },
      { word: "la tablet", translation: "планшет", example: "Uso la tablet para leer." },
      { word: "los auriculares", translation: "наушники", example: "Escucho música con auriculares." },
      { word: "el cargador", translation: "зарядка", example: "Olvidé el cargador en casa." },
      { word: "instalar", translation: "устанавливать", example: "Instalé un programa nuevo." },
      { word: "guardar", translation: "сохранять", example: "Guarda el documento." },
      { word: "enviar", translation: "отправлять", example: "Te envío el archivo." },
      { word: "el usuario", translation: "пользователь", example: "Crea un usuario nuevo." },
    ],
  },

  // ===== B1 ==========================================================
  {
    slug: "b1-emociones",
    level: "B1",
    topic: "Эмоции и чувства",
    topicEs: "Las Emociones y los Sentimientos",
    icon: "😊",
    words: [
      { word: "feliz / contento", translation: "счастливый", example: "Estoy muy contento con el resultado." },
      { word: "triste", translation: "грустный", example: "Se siente triste hoy." },
      { word: "enojado / enfadado", translation: "злой", example: "Está enfadado conmigo." },
      { word: "asustado", translation: "напуганный", example: "El niño está asustado." },
      { word: "sorprendido", translation: "удивлённый", example: "Estoy sorprendido por la noticia." },
      { word: "aburrido", translation: "скучающий", example: "Estoy aburrido en casa." },
      { word: "nervioso", translation: "нервный", example: "Estoy nervioso por el examen." },
      { word: "emocionado", translation: "взволнованный", example: "Estoy emocionado por el viaje." },
      { word: "celoso", translation: "ревнивый", example: "Es celoso de su amigo." },
      { word: "orgulloso", translation: "гордый", example: "Estoy orgulloso de ti." },
      { word: "avergonzado", translation: "смущённый", example: "Se sintió avergonzado." },
      { word: "decepcionado", translation: "разочарованный", example: "Estoy decepcionado con la película." },
      { word: "preocupado", translation: "обеспокоенный", example: "Estoy preocupado por ella." },
      { word: "tranquilo", translation: "спокойный", example: "Quédate tranquilo." },
      { word: "agradecido", translation: "благодарный", example: "Estoy muy agradecido." },
      { word: "la ilusión", translation: "воодушевление", example: "Tengo mucha ilusión por este proyecto." },
      { word: "la nostalgia", translation: "ностальгия", example: "Siento nostalgia de mi infancia." },
      { word: "sentir", translation: "чувствовать", example: "Siento que algo va mal." },
      { word: "la alegría", translation: "радость", example: "Sintió mucha alegría." },
      { word: "la tristeza", translation: "грусть", example: "La tristeza desapareció." },
      { word: "el miedo", translation: "страх", example: "Tiene miedo a las arañas." },
      { word: "la rabia", translation: "ярость", example: "Sintió rabia e impotencia." },
      { word: "la sorpresa", translation: "удивление", example: "Fue una sorpresa enorme." },
      { word: "la vergüenza", translation: "стыд", example: "Sintió mucha vergüenza." },
      { word: "el alivio", translation: "облегчение", example: "Suspiró de alivio." },
      { word: "estar harto", translation: "быть сытым по горло", example: "Estoy harto de esperar." },
      { word: "estar furioso", translation: "быть в ярости", example: "Estaba furioso con él." },
      { word: "estar agradecido", translation: "быть благодарным", example: "Estoy agradecido por tu ayuda." },
      { word: "entusiasmarse", translation: "воодушевляться", example: "Se entusiasmó con la idea." },
    ],
  },
  {
    slug: "b1-opiniones",
    level: "B1",
    topic: "Мнения и убеждения",
    topicEs: "Las Opiniones y las Creencias",
    icon: "💭",
    words: [
      { word: "la opinión", translation: "мнение", example: "En mi opinión, tienes razón." },
      { word: "creer", translation: "верить / считать", example: "Creo que es verdad." },
      { word: "pensar", translation: "думать / полагать", example: "Pienso que debemos ir." },
      { word: "parecer", translation: "казаться", example: "Me parece una buena idea." },
      { word: "estar de acuerdo", translation: "быть согласным", example: "Estoy de acuerdo contigo." },
      { word: "estar en desacuerdo", translation: "не соглашаться", example: "Estoy en desacuerdo." },
      { word: "defender", translation: "защищать (точку зрения)", example: "Defendió su opinión con datos." },
      { word: "argumentar", translation: "аргументировать", example: "Argumentó muy bien." },
      { word: "convencer", translation: "убеждать", example: "Me convenció con sus argumentos." },
      { word: "dudar", translation: "сомневаться", example: "Dudo que venga." },
      { word: "negar", translation: "отрицать", example: "Niega haberlo dicho." },
      { word: "afirmar", translation: "утверждать", example: "Afirma que es inocente." },
      { word: "el punto de vista", translation: "точка зрения", example: "Desde mi punto de vista, es correcto." },
      { word: "estar seguro", translation: "быть уверенным", example: "Estoy seguro de que vendrá." },
      { word: "suponer", translation: "предполагать", example: "Supongo que tienes razón." },
      { word: "el debate", translation: "дебаты", example: "Participé en un debate." },
      { word: "la postura", translation: "позиция", example: "Defendió su postura con datos." },
      { word: "estar a favor", translation: "быть за", example: "Estoy a favor de la propuesta." },
      { word: "estar en contra", translation: "быть против", example: "Estoy en contra del recorte." },
      { word: "compartir", translation: "разделять (мнение)", example: "Comparto tu opinión." },
      { word: " discrepar", translation: "расходиться во мнениях", example: "Discrepo totalmente." },
      { word: "reconocer", translation: "признавать", example: "Reconozco que tienes razón." },
      { word: "negar", translation: "отрицать", example: "Niega los hechos." },
      { word: "confirmar", translation: "подтверждать", example: "Confirmó la reserva." },
      { word: "criticar", translation: "критиковать", example: "Criticó la decisión." },
      { word: "apoyar", translation: "поддерживать", example: "Apoyo tu iniciativa." },
    ],
  },
  {
    slug: "b1-educacion",
    level: "B1",
    topic: "Образование",
    topicEs: "La Educación",
    icon: "🎓",
    words: [
      { word: "la escuela", translation: "школа", example: "Mis hijos van a la escuela pública." },
      { word: "la universidad", translation: "университет", example: "Estudia en la universidad." },
      { word: "el examen", translation: "экзамен", example: "Tengo un examen mañana." },
      { word: "estudiar", translation: "учиться", example: "Estudio español todos los días." },
      { word: "aprender", translation: "изучать", example: "Quiero aprender a tocar el piano." },
      { word: "enseñar", translation: "преподавать", example: "Enseña historia en el instituto." },
      { word: "el profesor", translation: "преподаватель", example: "El profesor explicó el tema." },
      { word: "el alumno / el estudiante", translation: "ученик / студент", example: "Los estudiantes hacen preguntas." },
      { word: "la asignatura", translation: "предмет", example: "Mi asignatura favorita es la historia." },
      { word: "la nota / la calificación", translation: "оценка", example: "Saqué buena nota en el examen." },
      { word: "aprobar", translation: "сдать (экзамен)", example: "Aprobé el examen de conducir." },
      { word: "suspender", translation: "провалить", example: "Suspendí matemáticas." },
      { word: "los deberes", translation: "домашнее задание", example: "Tengo que hacer los deberes." },
      { word: "el título", translation: "диплом", example: "Obtuvo el título de licenciado." },
      { word: "la matrícula", translation: "зачисление", example: "La matrícula es en septiembre." },
      { word: "el campus", translation: "кампус", example: "El campus es muy grande." },
      { word: "el catedrático", translation: "профессор", example: "El catedrático dio una conferencia." },
      { word: "la facultad", translation: "факультет", example: "Estudio en la facultad de letras." },
      { word: "el máster", translation: "магистратура", example: "Hago un máster en economía." },
      { word: "el doctorado", translation: "аспирантура", example: "Inicié el doctorado." },
      { word: "la beca", translation: "стипендия", example: "Obtuve una beca para estudiar." },
      { word: "la investigación", translation: "исследование", example: "Publicó su investigación." },
      { word: "el semestre / el cuatrimestre", translation: "семестр", example: "El segundo semestre empieza en febrero." },
      { word: "el horario", translation: "расписание", example: "Mi horario es muy apretado." },
      { word: "la biblioteca", translation: "библиотека", example: "Estudio en la biblioteca." },
      { word: "practicar", translation: "практиковать", example: "Practicamos la conversación." },
      { word: "matricularse", translation: "записаться", example: "Me matriculé en cinco asignaturas." },
    ],
  },
  {
    slug: "b1-sociedad",
    level: "B1",
    topic: "Общество и политика",
    topicEs: "La Sociedad y la Política",
    icon: "🏛️",
    words: [
      { word: "la sociedad", translation: "общество", example: "Vivimos en una sociedad compleja." },
      { word: "la política", translation: "политика", example: "No me interesa la política." },
      { word: "el gobierno", translation: "правительство", example: "El gobierno anunció nuevas medidas." },
      { word: "las elecciones", translation: "выборы", example: "Las elecciones son en noviembre." },
      { word: "el presidente", translation: "президент", example: "El presidente habló en la tele." },
      { word: "el partido político", translation: "политическая партия", example: "Votó por otro partido." },
      { word: "votar", translation: "голосовать", example: "Voté en las elecciones." },
      { word: "la ley", translation: "закон", example: "Hay que respetar la ley." },
      { word: "el derecho", translation: "право", example: "Estudia derecho en la universidad." },
      { word: "la justicia", translation: "справедливость", example: "Lucha por la justicia social." },
      { word: "la libertad", translation: "свобода", example: "La libertad es un derecho fundamental." },
      { word: "la igualdad", translation: "равенство", example: "Defiende la igualdad de género." },
      { word: "la democracia", translation: "демократия", example: "Vivimos en una democracia." },
      { word: "el país", translation: "страна", example: "Nuestro país es hermoso." },
      { word: "la cultura", translation: "культура", example: "Me interesa la cultura española." },
      { word: "la tradición", translation: "традиция", example: "Es una tradición familiar." },
      { word: "la immigración", translation: "иммиграция", example: "El país recibe mucha inmigración." },
      { word: "la pollítica", translation: "политика", example: "Debemos hablar de política." },
      { word: "la ciudadanía", translation: "гражданство", example: "Obtuvo la ciudadanía española." },
      { word: "el ciudadano", translation: "гражданин", example: "Los ciudadanos tienen derechos." },
      { word: "el referendum", translation: "референдум", example: "Se votó en un referendum." },
      { word: "el congreso", translation: "конгресс / парламент", example: "El congreso aprobó la ley." },
      { word: "el alcalde / la alcaldesa", translation: "мэр", example: "La alcaldesa inauguró el evento." },
      { word: "la manifestación", translation: "демонстрация", example: "Hubo una manifestación pacífica." },
      { word: "la comunidad", translation: "сообщество", example: "Somos una comunidad unida." },
      { word: "el voluntariado", translation: "волонтёрство", example: "Hago voluntariado los fines de semana." },
    ],
  },
  {
    slug: "b1-salud",
    level: "B1",
    topic: "Здоровье и медицина",
    topicEs: "La Salud y la Medicina",
    icon: "🏥",
    words: [
      { word: "la salud", translation: "здоровье", example: "La salud es lo más importante." },
      { word: "sano / saludable", translation: "здоровый", example: "Llevo una vida sana." },
      { word: "enfermo", translation: "больной", example: "Estuvo enfermo una semana." },
      { word: "el síntoma", translation: "симптом", example: "¿Qué síntomas tiene?" },
      { word: "la gripe", translation: "грипп", example: "Tengo la gripe." },
      { word: "el resfriado", translation: "простуда", example: "Estoy resfriado." },
      { word: "la alergia", translation: "аллергия", example: "Tengo alergia al polen." },
      { word: "la receta", translation: "рецепт", example: "Necesito una receta médica." },
      { word: "tomar la temperatura", translation: "измерить температуру", example: "Voy a tomarte la temperatura." },
      { word: "la cura", translation: "лекарство / лечение", example: "No hay cura para este virus." },
      { word: "tratar", translation: "лечить", example: "El médico lo trató bien." },
      { word: "curarse", translation: "вылечиться", example: "Se curó rápidamente." },
      { word: "el hospital", translation: "больница", example: "Lo llevaron al hospital." },
      { word: "la operación", translation: "операция", example: "Le hicieron una operación." },
      { word: "la dieta", translation: "диета", example: "Sigo una dieta equilibrada." },
      { word: "hacer ejercicio", translation: "заниматься спортом", example: "Hago ejercicio tres veces por semana." },
      { word: "la herida", translation: "рана", example: "Tiene una herida en el brazo." },
      { word: "el dolor de cabeza", translation: "головная боль", example: "Tengo dolor de cabeza." },
      { word: "el dolor de garganta", translation: "боль в горле", example: "Me duele la garganta." },
      { word: "el cansancio", translation: "усталость", example: "Siento mucho cansancio." },
      { word: "el descanso", translation: "отдых", example: "Necesito un descanso." },
      { word: "contagioso", translation: "заразный", example: "Es un virus muy contagioso." },
      { word: "el virus", translation: "вирус", example: "Es un virus nuevo." },
      { word: "la vacuna", translation: "вакцина", example: "Nos pusimos la vacuna." },
      { word: "la ambulancia", translation: "скорая помощь", example: "Llamamos una ambulancia." },
      { word: "el chequeo médico", translation: "медосмотр", example: "Me hice un chequeo médico." },
      { word: "sano y salvo", translation: "цел и невредим", example: "Llegó sano y salvo." },
    ],
  },
  {
    slug: "b1-medios",
    level: "B1",
    topic: "СМИ и новости",
    topicEs: "Los Medios de Comunicación",
    icon: "📰",
    words: [
      { word: "las noticias", translation: "новости", example: "Veo las noticias todos los días." },
      { word: "el periódico", translation: "газета", example: "Leo el periódico por la mañana." },
      { word: "la revista", translation: "журнал", example: "Compré una revista de viajes." },
      { word: "la televisión / la tele", translation: "телевидение", example: "Vemos la tele después de cenar." },
      { word: "la radio", translation: "радио", example: "Escucho la radio en el coche." },
      { word: "el programa", translation: "передача", example: "Mi programa favorito." },
      { word: "el periodista", translation: "журналист", example: "El periodista hizo buenas preguntas." },
      { word: "el titular", translation: "заголовок", example: "El titular era muy llamativo." },
      { word: "informar", translation: "информировать", example: "Nos informaron del cambio." },
      { word: "anunciar", translation: "объявлять", example: "Anunciaron su dimisión." },
      { word: "la entrevista", translation: "интервью", example: "Hicieron una entrevista al actor." },
      { word: "el reportaje", translation: "репортаж", example: "Un reportaje sobre el cambio climático." },
      { word: "emitir", translation: "транслировать", example: "Emiten el partido en directo." },
      { word: "la publicidad", translation: "реклама", example: "Hay demasiada publicidad." },
      { word: "las redes sociales", translation: "соцсети", example: "Uso las redes sociales para trabajar." },
      { word: "el titular", translation: "заголовок", example: "El titular llamó mi atención." },
      { word: "la portada", translation: "первая полоса", example: "Salió en la portada del periódico." },
      { word: "el blog", translation: "блог", example: "Escribe un blog de viajes." },
      { word: "el podcast", translation: "подкаст", example: "Escucho un podcast cada mañana." },
      { word: "el influencer", translation: "инфлюенсер", example: "Es un influencer muy seguido." },
      { word: "viral", translation: "вирусный", example: "El vídeo se hizo viral." },
      { word: "la censura", translation: "цензура", example: "Condenaron la censura." },
      { word: "la libertad de expresión", translation: "свобода слова", example: "Defienden la libertad de expresión." },
      { word: "la fake news", translation: "фейковые новости", example: "Cuidado con las fake news." },
      { word: "el espectador", translation: "зритель", example: "Los espectadores aplaudieron." },
    ],
  },

  // ===== B2 ==========================================================
  {
    slug: "b2-argumentacion",
    level: "B2",
    topic: "Аргументация и дискуссия",
    topicEs: "La Argumentación y el Debate",
    icon: "🎯",
    words: [
      { word: "el argumento", translation: "аргумент", example: "Presentó argumentos sólidos." },
      { word: "refutar", translation: "опровергать", example: "Refutó todas las acusaciones." },
      { word: "rebatir", translation: "оспаривать", example: "Nadie pudo rebatir su teoría." },
      { word: "contradecir", translation: "противоречить", example: "Sus hechos contradicen su teoría." },
      { word: "justificar", translation: "оправдывать", example: "Justificó su decisión." },
      { word: "fundamentar", translation: "обосновывать", example: "Fundamentó su tesis con datos." },
      { word: "la hipótesis", translation: "гипотеза", example: "Planteó una hipótesis interesante." },
      { word: "la conclusión", translation: "вывод", example: "Llegamos a la misma conclusión." },
      { word: "la premisa", translation: "предпосылка", example: "Partimos de una premisa falsa." },
      { word: "el razonamiento", translation: "рассуждение", example: "Su razonamiento es lógico." },
      { word: "la evidencia", translation: "доказательство", example: "No hay evidencia suficiente." },
      { word: "la tesis", translation: "тезис", example: "Defendió su tesis doctoral." },
      { word: "poner en duda", translation: "ставить под сомнение", example: "Pusieron en duda su palabra." },
      { word: "subrayar", translation: "подчёркивать", example: "Quiero subrayar este punto." },
      { word: "resaltar", translation: "выделять", example: "Resaltó la importancia del tema." },
      { word: "matizar", translation: "уточнять / смягчать", example: "Quisiera matizar lo que dije." },
      { word: "el contraargumento", translation: "контраргумент", example: "Presentó un contraargumento sólido." },
      { word: "objetar", translation: "возражать", example: "Nadie objetó la propuesta." },
      { word: "concluir", translation: "заключать", example: "Concluyo que tienes razón." },
      { word: "ilustrar", translation: "иллюстрировать", example: "Voy a ilustrarlo con un ejemplo." },
      { word: "ejemplificar", translation: "пояснять на примере", example: "Lo ejemplificó muy bien." },
      { word: "la falacia", translation: "софизм / логическая ошибка", example: "Su argumento es una falacia." },
      { word: "el prejuicio", translation: "предубеждение", example: "Actúa por prejuicio." },
      { word: "imparcial", translation: "беспристрастный", example: "El juez debe ser imparcial." },
      { word: "subjetivo", translation: "субъективный", example: "Es una opinión subjetiva." },
      { word: "objetivo", translation: "объективный", example: "Buscamos un análisis objetivo." },
    ],
  },
  {
    slug: "b2-ciencia",
    level: "B2",
    topic: "Наука и технологии",
    topicEs: "La Ciencia y la Tecnología",
    icon: "🔬",
    words: [
      { word: "el descubrimiento", translation: "открытие", example: "Anunciaron un gran descubrimiento." },
      { word: "la investigación", translation: "исследование", example: "Publicó sus investigaciones." },
      { word: "el experimento", translation: "эксперимент", example: "El experimento fue un éxito." },
      { word: "el avance", translation: "прогресс / достижение", example: "Un gran avance en la medicina." },
      { word: "la hipótesis", translation: "гипотеза", example: "Confirmaron la hipótesis inicial." },
      { word: "el dato", translation: "данные", example: "Los datos son concluyentes." },
      { word: "la teoría", translation: "теория", example: "La teoría de la relatividad." },
      { word: "el científico", translation: "учёный", example: "Los científicos hacen investigaciones." },
      { word: "la inteligencia artificial", translation: "искусственный интеллект", example: "La IA está en todas partes." },
      { word: "el algoritmo", translation: "алгоритм", example: "Crearon un algoritmo nuevo." },
      { word: "la innovación", translation: "инновация", example: "La innovación tecnológica avanza." },
      { word: "el espacio", translation: "космос", example: "La exploración del espacio." },
      { word: "el medioambiente", translation: "окружающая среда", example: "Hay que proteger el medioambiente." },
      { word: "la sostenibilidad", translation: "устойчивость", example: "Apuestan por la sostenibilidad." },
      { word: "el cambio climático", translation: "изменение климата", example: "El cambio climático es real." },
      { word: "la biotecnología", translation: "биотехнология", example: "La biotecnología avanza rápido." },
      { word: "la nanotecnología", translation: "нанотехнология", example: "Usos de la nanotecnología." },
      { word: "el genoma", translation: "геном", example: "El genoma humano fue descifrado." },
      { word: "la genética", translation: "генетика", example: "La genética estudia la herencia." },
      { word: "el átomo", translation: "атом", example: "El átomo es la unidad básica." },
      { word: "la molécula", translation: "молекула", example: "La molécula de agua." },
      { word: "la bacteria", translation: "бактерия", example: "Es una bacteria inofensiva." },
      { word: "la vacuna", translation: "вакцина", example: "Desarrollaron una vacuna nueva." },
      { word: "el laboratorio", translation: "лаборатория", example: "Trabaja en un laboratorio." },
      { word: "la energía renovable", translation: "возобновляемая энергия", example: "Apuestan por la energía renovable." },
    ],
  },
  {
    slug: "b2-problemas-sociales",
    level: "B2",
    topic: "Социальные проблемы",
    topicEs: "Los Problemas Sociales",
    icon: "🌍",
    words: [
      { word: "la pobreza", translation: "бедность", example: "La pobreza es un problema grave." },
      { word: "la desigualdad", translation: "неравенство", example: "La desigualdad económica crece." },
      { word: "el paro / el desempleo", translation: "безработица", example: "El paro afecta a los jóvenes." },
      { word: "la discriminación", translation: "дискриминация", example: "Luchamos contra la discriminación." },
      { word: "el racismo", translation: "расизм", example: "Hay que combatir el racismo." },
      { word: "la inmigración", translation: "иммиграция", example: "La inmigración es un tema complejo." },
      { word: "la emigración", translation: "эмиграция", example: "La emigración de jóvenes preocupa." },
      { word: "la violencia", translation: "насилие", example: "Cero tolerancia a la violencia." },
      { word: "la corrupción", translation: "коррупция", example: "Denunciaron casos de corrupción." },
      { word: "el refugiado", translation: "беженец", example: "Acogen a los refugiados." },
      { word: "los derechos humanos", translation: "права человека", example: "Defiende los derechos humanos." },
      { word: "la marginación", translation: "маргинализация", example: "Sufren marginación social." },
      { word: "la integración", translation: "интеграция", example: "Fomentan la integración de inmigrantes." },
      { word: "la brecha digital", translation: "цифровое неравенство", example: "La brecha digital separa generaciones." },
      { word: "el feminismo", translation: "феминизм", example: "El feminismo ha avanzado mucho." },
      { word: "la gentrificación", translation: "джентрификация", example: "La gentrificación del centro histórico." },
      { word: "la vivienda", translation: "жильё", example: "El precio de la vivienda sube." },
      { word: "sin techo", translation: "бездомный", example: "Ayudan a los sin techo." },
      { word: "la exclusión social", translation: "социальное исключение", example: "Luchan contra la exclusión social." },
      { word: "la discapacidad", translation: "инвалидность", example: "Adaptaron el edificio para personas con discapacidad." },
      { word: "la brecha salarial", translation: "зарплатное неравенство", example: "La brecha salarial entre hombres y mujeres." },
      { word: "el acoso", translation: "домогательство / травля", example: "Denunció el acoso laboral." },
      { word: "el lavado de imagen", translation: "отмывание репутации", example: "Intentó un lavado de imagen." },
      { word: "la manipulation", translation: "манипуляция", example: "Es una clara manipulación mediática." },
    ],
  },
  {
    slug: "b2-literatura",
    level: "B2",
    topic: "Литература и искусство",
    topicEs: "La Literatura y el Arte",
    icon: "📚",
    words: [
      { word: "la novela", translation: "роман", example: "Escribió una novela histórica." },
      { word: "el cuento", translation: "рассказ", example: "Leemos cuentos de Borges." },
      { word: "el poema", translation: "стихотворение", example: "Recitó un poema de Neruda." },
      { word: "el autor / la autora", translation: "автор", example: "Mi autora favorita es Allende." },
      { word: "el personaje", translation: "персонаж", example: "Los personajes son complejos." },
      { word: "la trama", translation: "сюжет", example: "La trama es fascinante." },
      { word: "el género literario", translation: "литературный жанр", example: "El ensayo es un género literario." },
      { word: "la pintura", translation: "живопись", example: "Admiro la pintura de Goya." },
      { word: "el cuadro", translation: "картина", example: "El cuadro está en el museo." },
      { word: "el museo", translation: "музей", example: "Visité el Museo del Prado." },
      { word: "la escultura", translation: "скульптура", example: "Una escultura de bronce." },
      { word: "la exposición", translation: "выставка", example: "Fuimos a una exposición de arte." },
      { word: "el artista", translation: "художник / артист", example: "Es un artista talentoso." },
      { word: "la obra maestra", translation: "шедевр", example: "El Guernica es una obra maestra." },
      { word: "la crítica", translation: "критика", example: "La crítica fue positiva." },
      { word: "la poesía", translation: "поэзия", example: "La poesía de García Lorca." },
      { word: "el ensayo", translation: "эссе", example: "Escribió un ensayo sobre arte." },
      { word: "el teatro", translation: "театр", example: "Vamos al teatro esta noche." },
      { word: "la obra", translation: "произведение", example: "Es su mejor obra." },
      { word: "la narrativa", translation: "повествование", example: "La narrativa contemporánea." },
      { word: "el estilo", translation: "стиль", example: "Tiene un estilo muy personal." },
      { word: "la ambientación", translation: "сеттинг / обстановка", example: "La ambientación del siglo XIX." },
      { word: "el realismo mágico", translation: "магический реализм", example: "García Márquez y el realismo mágico." },
      { word: "el verso libre", translation: "свободный стих", example: "Escribe en verso libre." },
      { word: "la literatura universal", translation: "мировая литература", example: "Estudia literatura universal." },
    ],
  },
  {
    slug: "b2-economia",
    level: "B2",
    topic: "Экономика и финансы",
    topicEs: "La Economía y las Finanzas",
    icon: "💰",
    words: [
      { word: "la economía", translation: "экономика", example: "La economía mundial crece." },
      { word: "la crisis", translation: "кризис", example: "Sufrimos una crisis económica." },
      { word: "la inflación", translation: "инфляция", example: "La inflación sube este año." },
      { word: "la recesión", translation: "рецессия", example: "El país entra en recesión." },
      { word: "el presupuesto", translation: "бюджет", example: "Aprobamos el presupuesto anual." },
      { word: "la inversión", translation: "инвестиция", example: "Hicieron una gran inversión." },
      { word: "el beneficio", translation: "прибыль", example: "Los beneficios aumentaron." },
      { word: "la pérdida", translation: "убыток", example: "Tuvieron pérdidas este trimestre." },
      { word: "el mercado", translation: "рынок", example: "El mercado laboral es difícil." },
      { word: "la oferta y la demanda", translation: "предложение и спрос", example: "La ley de oferta y demanda." },
      { word: "el ahorro", translation: "накопления", example: "Tiene unos ahorros importantes." },
      { word: "el préstamo", translation: "заём", example: "Pidió un préstamo al banco." },
      { word: "la hipoteca", translation: "ипотека", example: "Pagan la hipoteca cada mes." },
      { word: "el impuesto", translation: "налог", example: "Subieron los impuestos." },
      { word: "la empresa", translation: "предприятие", example: "Trabajo en una empresa grande." },
      { word: "la bolsa", translation: "биржа", example: "La bolsa subió un 2%." },
      { word: "la acción", translation: "акция", example: "Compré acciones de la empresa." },
      { word: "el accionista", translation: "акционер", example: "Los accionistas aprobaron el plan." },
      { word: "la banca", translation: "банковское дело", example: "Trabaja en la banca." },
      { word: "el PIB", translation: "ВВП", example: "El PIB creció este trimestre." },
      { word: "la globalización", translation: "глобализация", example: "La globalización tiene pros y contras." },
      { word: "la privatización", translation: "приватизация", example: "Se opuso a la privatización." },
      { word: "exportar", translation: "экспортировать", example: "España exporta aceite de oliva." },
      { word: "importar", translation: "импортировать", example: "Importan tecnología de Asia." },
      { word: "la competitividad", translation: "конкурентоспособность", example: "Mejorar la competitividad." },
    ],
  },

  // ===== C1 ==========================================================
  {
    slug: "c1-expresiones-idiomaticas",
    level: "C1",
    topic: "Идиомы и выражения",
    topicEs: "Expresiones Idiomáticas",
    icon: "🗣️",
    words: [
      { word: "estar en las nubes", translation: "витать в облаках", example: "Siempre está en las nubes." },
      { word: "costar un ojo de la cara", translation: "стоить целое состояние", example: "Ese coche cuesta un ojo de la cara." },
      { word: "no tener ni idea", translation: "не иметь ни малейшего понятия", example: "No tengo ni idea de dónde está." },
      { word: "dar la lata", translation: "надоедать", example: "Deja de dar la lata." },
      { word: "hacerse el sueco", translation: "прикидываться дураком", example: "Se hace el sueco cuando le pregunto." },
      { word: "estar hasta el cuello", translation: "быть по горло сытым", example: "Estoy hasta el cuello de trabajo." },
      { word: "tirar la casa por la ventana", translation: "гулять на широкую ногу", example: "En su boda tiraron la casa por la ventana." },
      { word: "no ver tres en un burro", translation: "не видеть дальше собственного носа", example: "Sin gafas no veo tres en un burro." },
      { word: "ser pan comido", translation: "быть проще простого", example: "Este examen es pan comido." },
      { word: "coger el toro por los cuernos", translation: "взять быка за рога", example: "Hay que coger el toro por los cuernos." },
      { word: "estar como una cabra", translation: "быть не в своём уме", example: "Está como una cabra si cree eso." },
      { word: "no dar pie con bola", translation: "не ладиться", example: "Hoy no doy pie con bola." },
      { word: "ahogarse en un vaso de agua", translation: "делать из мухи слона", example: "Te ahogas en un vaso de agua." },
      { word: "dar gato por liebre", translation: "всучить подделку", example: "Me dieron gato por liebre." },
      { word: "tomar el pelo", translation: "дразнить", example: "Deja de tomarle el pelo." },
      { word: "dar la cara", translation: "брать ответственность", example: "Tienes que dar la cara." },
      { word: "echar una mano", translation: "помочь", example: "¿Me echas una mano?" },
      { word: "quedarse de brazos cruzados", translation: "сложить руки / бездействовать", example: "No te quedes de brazos cruzados." },
      { word: "tener la sartén por el mango", translation: "держать всё под контролем", example: "Aquí ella tiene la sartén por el mango." },
      { word: "no dar puntada sin hilo", translation: "действовать с умыслом", example: "Él no da puntada sin hilo." },
      { word: "estar en el quinto pino", translation: "быть чёрт знает где", example: "Vive en el quinto pino." },
      { word: "importar un pepino / un comino", translation: "быть совершенно безразличным", example: "Me importa un pepino." },
      { word: "darle vueltas a algo", translation: "обдумывать", example: "Le di vueltas al asunto." },
      { word: "ponerse las botas", translation: "наесться / нажиться", example: "Se puso las botas." },
      { word: "más vale tarde que nunca", translation: "лучше поздно, чем никогда", example: "Más vale tarde que nunca." },
      { word: "a mal tiempo, buena cara", translation: "всякому горю противопоставлять улыбку", example: "Hay que poner a mal tiempo, buena cara." },
    ],
  },
  {
    slug: "c1-lenguaje-formal",
    level: "C1",
    topic: "Формальный регистр",
    topicEs: "Lenguaje Formal",
    icon: "🎩",
    words: [
      { word: "por consiguiente", translation: "следовательно", example: "No estudió; por consiguiente, suspendió." },
      { word: "no obstante", translation: "тем не менее", example: "Llovió; no obstante, salimos." },
      { word: "asimismo", translation: "равным образом", example: "Asimismo, quiero añadir un punto." },
      { word: "en definitiva", translation: "в конечном счёте", example: "En definitiva, es tu decisión." },
      { word: "a tenor de", translation: "в соответствии с", example: "A tenor de los resultados, es positivo." },
      { word: "con miras a", translation: "с целью", example: "Trabajamos con miras a mejorar." },
      { word: "al respecto", translation: "по этому поводу", example: "No dijo nada al respecto." },
      { word: "en virtud de", translation: "на основании", example: "En virtud de la ley vigente." },
      { word: "suscitar", translation: "вызывать", example: "Suscitó un debate interesante." },
      { word: "conllevar", translation: "влечь за собой", example: "El cambio conlleva riesgos." },
      { word: "trascender", translation: "выходить за рамки", example: "Su obra trascendió fronteras." },
      { word: "resultar pertinente", translation: "быть уместным", example: "No resulta pertinente comentarlo." },
      { word: "objetivamente", translation: "объективно", example: "Hay que analizarlo objetivamente." },
      { word: "el discernimiento", translation: "проницательность", example: "Mostró gran discernimiento." },
      { word: "en relación con", translation: "в связи с / относительно", example: "En relación con su carta…" },
      { word: "dar fe de", translation: "свидетельствовать", example: "Doy fe de su honestidad." },
      { word: "hacer hincapié", translation: "делать упор", example: "Hizo hincapié en la puntualidad." },
      { word: "de índole", translation: "характера / природы", example: "Cuestiones de índole económica." },
      { word: "la entidad", translation: "организация / сущность", example: "Una entidad bancaria." },
      { word: "el cometido", translation: "задача / функция", example: "Cumplió su cometido." },
      { word: "competente", translation: "компетентный", example: "Es una persona muy competente." },
      { word: "idóneo", translation: "подходящий / надлежащий", example: "Es el lugar idóneo." },
      { word: "incumbir", translation: "касаться / быть в компетенции", example: "El asunto no me incumbe." },
      { word: "proceder a", translation: "приступить к", example: "Procederemos a la votación." },
    ],
  },
  {
    slug: "c1-regionalismos",
    level: "C1",
    topic: "Регионализмы",
    topicEs: "Regionalismos del Español",
    icon: "🌎",
    words: [
      { word: "vos (Argentina)", translation: "ты (аргентинская форма)", example: "¿Vos querés un café?" },
      { word: "ché (Argentina)", translation: "эй / послушай", example: "Che, ¿vamos al cine?" },
      { word: "plata (América)", translation: "деньги", example: "No tengo plata." },
      { word: "lana (México)", translation: "деньги", example: "Cuesta mucha lana." },
      { word: "guay (España)", translation: "круто", example: "¡Qué guay!" },
      { word: "vale (España)", translation: "окей / ладно", example: "Vale, nos vemos luego." },
      { word: "mande (México)", translation: "что? / простите?", example: "—¿Juan? —¿Mande?" },
      { word: "computadora (América)", translation: "компьютер", example: "Mi computadora es nueva." },
      { word: "ordenador (España)", translation: "компьютер", example: "Mi ordenador es nuevo." },
      { word: "coche (España)", translation: "машина", example: "Mi coche es rojo." },
      { word: "carro (América)", translation: "машина", example: "Mi carro es rojo." },
      { word: "zumo (España)", translation: "сок", example: "Quiero un zumo de naranja." },
      { word: "jugo (América)", translation: "сок", example: "Quiero un jugo de naranja." },
      { word: "coger (España)", translation: "брать", example: "Voy a coger el autobús." },
      { word: "tomar (América)", translation: "брать / брать транспорт", example: "Voy a tomar el autobús." },
      { word: "prieto (México)", translation: "тёмный / смуглый", example: "Es de piel prieta." },
      { word: "chingón (México)", translation: "крутой (разговорное)", example: "¡Está chingón!" },
      { word: "buenísimo (rioplatense)", translation: "очень хороший", example: "Está buenísimo." },
      { word: "pibe / piba (Argentina)", translation: "парень / девушка", example: "Los pibes juegan al fútbol." },
      { word: "fiaca (Argentina)", translation: "лень", example: "Tengo fiaca hoy." },
      { word: "guagua (Caribe)", translation: "автобус", example: "Tomé la guagua." },
      { word: "chaval / chavala (España)", translation: "парень / девушка", example: "Los chavales de hoy." },
      { word: "majo / maja (España)", translation: "милый / приятный", example: "Es muy maja." },
      { word: "estar forrado", translation: "быть при деньгах (разговорное)", example: "Está forrado." },
    ],
  },
  {
    slug: "c1-conceptos-abstractos",
    level: "C1",
    topic: "Абстрактные концепции",
    topicEs: "Conceptos Abstractos",
    icon: "🧠",
    words: [
      { word: "la esencia", translation: "сущность", example: "La esencia del problema es otro." },
      { word: "el fundamento", translation: "основание", example: "El fundamento de su teoría." },
      { word: "el ámbito", translation: "сфера", example: "En el ámbito de la ciencia." },
      { word: "el trasfondo", translation: "подоплёка", example: "Hay un trasfondo político." },
      { word: "la índole", translation: "характер / природа", example: "Es un problema de índole económica." },
      { word: "el devenir", translation: "становление / ход", example: "El devenir histórico." },
      { word: "el entramado", translation: "сплетение", example: "Un entramado de mentiras." },
      { word: "el impairment", translation: "обесценение", example: "El impairment de activos." },
      { word: "la intrínseco", translation: "внутренне присущий", example: "El valor intrínseco." },
      { word: "la connotación", translation: "коннотация", example: "Tiene connotaciones negativas." },
      { word: "la denotación", translation: "денотация", example: "La denotación literal de la palabra." },
      { word: "el paradigma", translation: "парадигма", example: "Un cambio de paradigma." },
      { word: "la coyuntura", translation: "обстановка / ситуация", example: "En la coyuntura actual." },
      { word: "el prejuicio", translation: "предрассудок", example: "Hay que superar los prejuicios." },
      { word: "la idiosincrasia", translation: "самобытность", example: "La idiosincrasia de un pueblo." },
      { word: "la ontología", translation: "онтология", example: "La ontología estudia el ser." },
      { word: "la epistemología", translation: "эпистемология", example: "La epistemología de la ciencia." },
      { word: "el determinismo", translation: "детерминизм", example: "El determinismo económico." },
      { word: "la dialéctica", translation: "диалектика", example: "La dialéctica de Hegel." },
      { word: "el pragmatismo", translation: "прагматизм", example: "El pragmatismo americano." },
      { word: "el escepticismo", translation: "скептицизм", example: "Mantuvo un saludable escepticismo." },
      { word: "la ambigüedad", translation: "двусмысленность", example: "Hay ambigüedad en sus palabras." },
      { word: "la paradoja", translation: "парадокс", example: "Es una paradoja fascinante." },
      { word: "la sinergia", translation: "синергия", example: "Hay sinergia entre los equipos." },
    ],
  },
  {
    slug: "c1-literario",
    level: "C1",
    topic: "Литературная лексика",
    topicEs: "Léxico Literario",
    icon: "✒️",
    words: [
      { word: "la metáfora", translation: "метафора", example: "Usa una metáfora hermosa." },
      { word: "la alegoría", translation: "аллегория", example: "La obra es una alegoría." },
      { word: "el símbolo", translation: "символ", example: "La paloma es símbolo de paz." },
      { word: "la elocuencia", translation: "красноречие", example: "Habló con elocuencia." },
      { word: "el matiz", translation: "оттенок (смысла)", example: "Hay un matiz importante." },
      { word: "la prosa", translation: "проза", example: "Escribe en prosa poética." },
      { word: "el verso", translation: "стих", example: "Recitó los versos de memoria." },
      { word: "la estrofa", translation: "строфа", example: "La primera estrofa del poema." },
      { word: "el ritmo", translation: "ритм", example: "El ritmo de la narración." },
      { word: "la ambientación", translation: "обстановка (в произведении)", example: "La ambientación es fantástica." },
      { word: "la voz narrativa", translation: "голос рассказчика", example: "La voz narrativa es en primera persona." },
      { word: "el recurso literario", translation: "литературный приём", example: "Usa muchos recursos literarios." },
      { word: "la ironía", translation: "ирония", example: "La ironía recorre toda la obra." },
      { word: "la paradoja", translation: "парадокс", example: "Es una paradoja fascinante." },
      { word: "la hipérbole", translation: "гипербола", example: "Usa mucha hipérbole." },
      { word: "la sinestesia", translation: "синестезия", example: "Un ejemplo de sinestesia literaria." },
      { word: "la personificación", translation: "олицетворение", example: "La personificación de la muerte." },
      { word: "el símil", translation: "сравнение", example: "Un símil muy logrado." },
      { word: "la anáfora", translation: "анафора", example: "Usa la anáfora al principio de cada verso." },
      { word: "el oxímoron", translation: "оксюморон", example: "Un oscuro resplandor es un oxímoron." },
      { word: "la aliteración", translation: "аллитерация", example: "La aliteración crea ritmo." },
      { word: "el polisíndeton", translation: "полисиндетон", example: "Usa polisíndeton para ralentizar el ritmo." },
      { word: "la elipsis", translation: "эллипсис", example: "La elipsis es común en la poesía moderna." },
      { word: "el subtexto", translation: "подтекст", example: "Hay un subtexto político en la obra." },
      { word: "la ambigüedad deliberada", translation: "намеренная двусмысленность", example: "Cultiva la ambigüedad deliberada." },
    ],
  },
];

// ---------- Helpers --------------------------------------------------

/** Group topics by level. */
export function groupVocabByLevel(): Record<string, VocabTopic[]> {
  const grouped: Record<string, VocabTopic[]> = {};
  for (const topic of VOCAB_TOPICS) {
    (grouped[topic.level] ||= []).push(topic);
  }
  return grouped;
}

/** Count total words across all topics. */
export function totalVocabWords(): number {
  return VOCAB_TOPICS.reduce((sum, t) => sum + t.words.length, 0);
}
