import type { InterfaceLanguage } from "@/types";

/** Gloss in one or more UI languages for tap-to-translate. */
export type HintGloss = Partial<Record<InterfaceLanguage, string>>;

export type HintSense = {
  lemma: string;
  gloss: HintGloss;
};

/**
 * Exact-token overrides (homonyms / clock senses / ser·ir pretérito).
 * Checked before catalog index lookup.
 */
export const SPANISH_TOKEN_OVERRIDES: Record<string, HintSense> = {
  cuarto: {
    lemma: "cuarto",
    gloss: {
      ru: "четверть (часа) / комната",
      en: "quarter (hour) / room",
      es: "cuarto de hora / habitación",
      de: "Viertelstunde / Zimmer",
    },
  },
  media: {
    lemma: "media",
    gloss: {
      ru: "половина (часа)",
      en: "half (past the hour)",
      es: "media hora / y media",
      de: "halb (Uhrzeit)",
    },
  },
  tiempo: {
    lemma: "tiempo",
    gloss: {
      ru: "время / погода",
      en: "time / weather",
      es: "tiempo / clima",
      de: "Zeit / Wetter",
    },
  },
  banco: {
    lemma: "banco",
    gloss: {
      ru: "банк / скамейка",
      en: "bank / bench",
      es: "banco / asiento",
      de: "Bank / Sitzbank",
    },
  },
  planta: {
    lemma: "planta",
    gloss: {
      ru: "этаж / растение",
      en: "floor / plant",
      es: "planta / vegetal",
      de: "Stockwerk / Pflanze",
    },
  },
  // ser / ir share pretérito roots
  fui: {
    lemma: "ser / ir",
    gloss: {
      ru: "был(а) / пошёл(а) (pret. ser/ir)",
      en: "was / went (pret. ser/ir)",
      es: "pretérito de ser/ir (yo)",
      de: "war / ging (Prät. ser/ir)",
    },
  },
  fue: {
    lemma: "ser / ir",
    gloss: {
      ru: "был(а) / пошёл(а) (pret. ser/ir)",
      en: "was / went (pret. ser/ir)",
      es: "pretérito de ser/ir (él/ella)",
      de: "war / ging (Prät. ser/ir)",
    },
  },
  fuimos: {
    lemma: "ser / ir",
    gloss: {
      ru: "были / пошли (pret. ser/ir)",
      en: "were / went (pret. ser/ir)",
      es: "pretérito de ser/ir (nosotros)",
      de: "waren / gingen (Prät. ser/ir)",
    },
  },
  fueron: {
    lemma: "ser / ir",
    gloss: {
      ru: "были / пошли (pret. ser/ir)",
      en: "were / went (pret. ser/ir)",
      es: "pretérito de ser/ir (ellos)",
      de: "waren / gingen (Prät. ser/ir)",
    },
  },
};

/**
 * Frequent inflected forms → infinitive / lemma already in the catalog.
 * Do not list tokens that have SPANISH_TOKEN_OVERRIDES.
 */
export const SPANISH_INFLECTED_FORMS: Record<string, string> = {
  // ser
  soy: "ser",
  eres: "ser",
  es: "ser",
  somos: "ser",
  sois: "ser",
  son: "ser",
  era: "ser",
  eras: "ser",
  éramos: "ser",
  eran: "ser",
  sido: "ser",
  // estar
  estoy: "estar",
  estás: "estar",
  está: "estar",
  estamos: "estar",
  estáis: "estar",
  están: "estar",
  estaba: "estar",
  estabas: "estar",
  estaban: "estar",
  estado: "estar",
  // tener
  tengo: "tener",
  tienes: "tener",
  tiene: "tener",
  tenemos: "tener",
  tenéis: "tener",
  tienen: "tener",
  tuve: "tener",
  tuvo: "tener",
  tuvieron: "tener",
  tenía: "tener",
  tenían: "tener",
  tenido: "tener",
  // haber
  he: "haber",
  has: "haber",
  ha: "haber",
  hemos: "haber",
  habéis: "haber",
  han: "haber",
  hay: "haber",
  había: "haber",
  habían: "haber",
  hubo: "haber",
  // ir (present; pretérito handled in overrides)
  voy: "ir",
  vas: "ir",
  va: "ir",
  vamos: "ir",
  vais: "ir",
  van: "ir",
  iba: "ir",
  ibas: "ir",
  iban: "ir",
  ido: "ir",
  // hacer
  hago: "hacer",
  haces: "hacer",
  hace: "hacer",
  hacemos: "hacer",
  hacéis: "hacer",
  hacen: "hacer",
  hice: "hacer",
  hizo: "hacer",
  hicieron: "hacer",
  hacía: "hacer",
  hecho: "hacer",
  // poder
  puedo: "poder",
  puedes: "poder",
  puede: "poder",
  podemos: "poder",
  pueden: "poder",
  pude: "poder",
  pudo: "poder",
  // querer
  quiero: "querer",
  quieres: "querer",
  quiere: "querer",
  queremos: "querer",
  quieren: "querer",
  quise: "querer",
  quiso: "querer",
  // saber
  sé: "saber",
  sabes: "saber",
  sabe: "saber",
  sabemos: "saber",
  saben: "saber",
  // decir
  digo: "decir",
  dices: "decir",
  dice: "decir",
  decimos: "decir",
  dicen: "decir",
  dije: "decir",
  dijo: "decir",
  dicho: "decir",
  // dar
  doy: "dar",
  das: "dar",
  da: "dar",
  damos: "dar",
  dan: "dar",
  di: "dar",
  dio: "dar",
  dado: "dar",
  // ver
  veo: "ver",
  ves: "ver",
  ve: "ver",
  vemos: "ver",
  ven: "ver",
  vi: "ver",
  vio: "ver",
  visto: "ver",
  // poner
  pongo: "poner",
  pones: "poner",
  pone: "poner",
  ponen: "poner",
  puse: "poner",
  puso: "poner",
  puesto: "poner",
  // venir
  vengo: "venir",
  vienes: "venir",
  viene: "venir",
  vienen: "venir",
  vine: "venir",
  vino: "venir",
  // salir
  salgo: "salir",
  sales: "salir",
  sale: "salir",
  salen: "salir",
  // llegar
  llego: "llegar",
  llegas: "llegar",
  llega: "llegar",
  llegan: "llegar",
  // regular -ar present samples learners click often
  hablo: "hablar",
  hablas: "hablar",
  habla: "hablar",
  hablan: "hablar",
  como: "comer",
  comes: "comer",
  come: "comer",
  comen: "comer",
  vivo: "vivir",
  vives: "vivir",
  vive: "vivir",
  viven: "vivir",
  estudio: "estudiar",
  estudias: "estudiar",
  estudia: "estudiar",
  trabajo: "trabajar",
  trabajas: "trabajar",
  trabaja: "trabajar",
  necesito: "necesitar",
  necesita: "necesitar",
};

/** Core lemmas missing from catalog (or weak coverage) — seeded into the hint index. */
export const SPANISH_CORE_LEMMAS: Record<string, HintGloss> = {
  haber: {
    ru: "есть / иметься (hay); вспом. глагол",
    en: "there is/are (hay); auxiliary",
    es: "haber (hay; auxiliar)",
    de: "es gibt (hay); Hilfsverb",
  },
  decir: { ru: "говорить / сказать", en: "to say / tell", es: "decir", de: "sagen" },
  dar: { ru: "давать", en: "to give", es: "dar", de: "geben" },
  poner: { ru: "класть / ставить", en: "to put", es: "poner", de: "legen / stellen" },
  salir: { ru: "выходить", en: "to go out / leave", es: "salir", de: "hinausgehen" },
  llegar: { ru: "прибывать / приходить", en: "to arrive", es: "llegar", de: "ankommen" },
  dormir: { ru: "спать", en: "to sleep", es: "dormir", de: "schlafen" },
  caminar: { ru: "ходить пешком", en: "to walk", es: "caminar", de: "zu Fuß gehen" },
  // function words
  por: { ru: "из-за / по / через (por)", en: "for / by / through (por)", es: "por", de: "por (wegen/durch)" },
  para: { ru: "для / чтобы (para)", en: "for / in order to (para)", es: "para", de: "para (für/um zu)" },
  con: { ru: "с", en: "with", es: "con", de: "mit" },
  sin: { ru: "без", en: "without", es: "sin", de: "ohne" },
  de: { ru: "из / о / принадлежность (de)", en: "of / from (de)", es: "de", de: "von / aus" },
  a: { ru: "в / к / направление (a)", en: "to / at (a)", es: "a", de: "nach / zu" },
  en: { ru: "в / на", en: "in / on", es: "en", de: "in / auf" },
  sobre: { ru: "на / о", en: "on / about", es: "sobre", de: "auf / über" },
  entre: { ru: "между", en: "between", es: "entre", de: "zwischen" },
  hasta: { ru: "до", en: "until / up to", es: "hasta", de: "bis" },
  desde: { ru: "с / от", en: "from / since", es: "desde", de: "seit / von" },
  muy: { ru: "очень", en: "very", es: "muy", de: "sehr" },
  más: { ru: "больше / более", en: "more", es: "más", de: "mehr" },
  menos: { ru: "меньше", en: "less / fewer", es: "menos", de: "weniger" },
  también: { ru: "тоже", en: "also / too", es: "también", de: "auch" },
  pero: { ru: "но", en: "but", es: "pero", de: "aber" },
  porque: { ru: "потому что", en: "because", es: "porque", de: "weil" },
  como: { ru: "как / как (сравнение)", en: "like / as", es: "como", de: "wie / als" },
  cuando: { ru: "когда", en: "when", es: "cuando", de: "wenn / als" },
  donde: { ru: "где", en: "where", es: "donde", de: "wo" },
  dónde: { ru: "где?", en: "where?", es: "dónde", de: "wo?" },
  quien: { ru: "кто", en: "who", es: "quien", de: "wer" },
  quién: { ru: "кто?", en: "who?", es: "quién", de: "wer?" },
  que: { ru: "что / который", en: "that / which", es: "que", de: "dass / der" },
  qué: { ru: "что? / какой?", en: "what?", es: "qué", de: "was?" },
  cual: { ru: "какой / который", en: "which", es: "cual", de: "welch" },
  cuál: { ru: "какой?", en: "which?", es: "cuál", de: "welch?" },
  no: { ru: "не / нет", en: "not / no", es: "no", de: "nicht / nein" },
  sí: { ru: "да", en: "yes", es: "sí", de: "ja" },
  y: { ru: "и", en: "and", es: "y", de: "und" },
  o: { ru: "или", en: "or", es: "o", de: "oder" },
  // pronouns
  yo: { ru: "я", en: "I", es: "yo", de: "ich" },
  tú: { ru: "ты", en: "you (tú)", es: "tú", de: "du" },
  él: { ru: "он", en: "he", es: "él", de: "er" },
  ella: { ru: "она", en: "she", es: "ella", de: "sie" },
  usted: { ru: "вы (вежл.)", en: "you (formal)", es: "usted", de: "Sie" },
  nosotros: { ru: "мы", en: "we", es: "nosotros", de: "wir" },
  nosotras: { ru: "мы (ж.)", en: "we (f.)", es: "nosotras", de: "wir" },
  vosotros: { ru: "вы (мн.)", en: "you (pl. ES)", es: "vosotros", de: "ihr" },
  ellos: { ru: "они", en: "they (m.)", es: "ellos", de: "sie" },
  ellas: { ru: "они (ж.)", en: "they (f.)", es: "ellas", de: "sie" },
  me: { ru: "мне / меня", en: "me", es: "me", de: "mich / mir" },
  te: { ru: "тебе / тебя", en: "you (obj.)", es: "te", de: "dich / dir" },
  se: { ru: "себя / друг друга (se)", en: "oneself / each other (se)", es: "se", de: "sich" },
  nos: { ru: "нас / нам", en: "us", es: "nos", de: "uns" },
  le: { ru: "ему / ей (дат.)", en: "him/her (IO)", es: "le", de: "ihm / ihr" },
  les: { ru: "им (дат.)", en: "them (IO)", es: "les", de: "ihnen" },
  lo: { ru: "это / его (вин.)", en: "it / him (DO)", es: "lo", de: "es / ihn" },
  la: { ru: "её / артикль la", en: "her / article la", es: "la", de: "sie / Artikel la" },
  el: { ru: "артикль el / него", en: "article el / him", es: "el", de: "Artikel el" },
  los: { ru: "артикли los / их", en: "article los / them", es: "los", de: "Artikel los" },
  las: { ru: "артикли las / их", en: "article las / them", es: "las", de: "Artikel las" },
  un: { ru: "один / артикль un", en: "a / an (m.)", es: "un", de: "ein" },
  una: { ru: "одна / артикль una", en: "a / an (f.)", es: "una", de: "eine" },
  // adjectives & nouns often clicked
  bueno: { ru: "хороший", en: "good", es: "bueno", de: "gut" },
  buena: { ru: "хорошая", en: "good (f.)", es: "buena", de: "gut" },
  malo: { ru: "плохой", en: "bad", es: "malo", de: "schlecht" },
  mala: { ru: "плохая", en: "bad (f.)", es: "mala", de: "schlecht" },
  grande: { ru: "большой", en: "big / large", es: "grande", de: "groß" },
  pequeño: { ru: "маленький", en: "small", es: "pequeño", de: "klein" },
  pequeña: { ru: "маленькая", en: "small (f.)", es: "pequeña", de: "klein" },
  nuevo: { ru: "новый", en: "new", es: "nuevo", de: "neu" },
  nueva: { ru: "новая", en: "new (f.)", es: "nueva", de: "neu" },
  viejo: { ru: "старый", en: "old", es: "viejo", de: "alt" },
  libro: { ru: "книга", en: "book", es: "libro", de: "Buch" },
  amigo: { ru: "друг", en: "friend (m.)", es: "amigo", de: "Freund" },
  amiga: { ru: "подруга", en: "friend (f.)", es: "amiga", de: "Freundin" },
  niño: { ru: "мальчик / ребёнок", en: "boy / child", es: "niño", de: "Junge / Kind" },
  niña: { ru: "девочка", en: "girl", es: "niña", de: "Mädchen" },
  coche: { ru: "машина", en: "car", es: "coche", de: "Auto" },
  té: { ru: "чай", en: "tea", es: "té", de: "Tee" },
  pueblo: { ru: "посёлок / народ", en: "town / people", es: "pueblo", de: "Dorf / Volk" },
  carta: { ru: "письмо / меню", en: "letter / menu", es: "carta", de: "Brief / Speisekarte" },
  cola: { ru: "очередь / хвост", en: "queue / tail", es: "cola", de: "Schlange / Schwanz" },
  piso: { ru: "квартира / этаж", en: "flat / floor", es: "piso", de: "Wohnung / Etage" },
  curso: { ru: "курс / учебный год", en: "course / school year", es: "curso", de: "Kurs / Schuljahr" },
  historia: { ru: "история / рассказ", en: "history / story", es: "historia", de: "Geschichte" },
  parte: { ru: "часть", en: "part", es: "parte", de: "Teil" },
  sierra: { ru: "горы / пила", en: "mountain range / saw", es: "sierra", de: "Gebirge / Säge" },
  pasta: { ru: "паста / деньги (разг.)", en: "pasta / money (coll.)", es: "pasta", de: "Pasta / Kohle" },
  rato: { ru: "время / момент", en: "a while / moment", es: "rato", de: "Weile" },
};

export const ENGLISH_TOKEN_OVERRIDES: Record<string, HintSense> = {
  time: {
    lemma: "time",
    gloss: {
      ru: "время / раз",
      en: "time",
      es: "tiempo / vez",
      de: "Zeit / Mal",
    },
  },
  get: {
    lemma: "get",
    gloss: {
      ru: "получать / становиться / добираться",
      en: "get",
      es: "conseguir / llegar a ser",
      de: "bekommen / werden",
    },
  },
  make: {
    lemma: "make",
    gloss: {
      ru: "делать / готовить",
      en: "make",
      es: "hacer / preparar",
      de: "machen / zubereiten",
    },
  },
  take: {
    lemma: "take",
    gloss: {
      ru: "брать / занимать (время)",
      en: "take",
      es: "tomar / coger",
      de: "nehmen / dauern",
    },
  },
  have: {
    lemma: "have",
    gloss: {
      ru: "иметь / вспомогательный have",
      en: "have",
      es: "tener / auxiliar have",
      de: "haben",
    },
  },
};

export const ENGLISH_INFLECTED_FORMS: Record<string, string> = {
  // be
  am: "be",
  is: "be",
  are: "be",
  was: "be",
  were: "be",
  been: "be",
  being: "be",
  // have
  has: "have",
  had: "have",
  having: "have",
  // do
  does: "do",
  did: "do",
  done: "do",
  doing: "do",
  // go
  goes: "go",
  went: "go",
  gone: "go",
  going: "go",
  // get
  gets: "get",
  got: "get",
  getting: "get",
  // make
  makes: "make",
  made: "make",
  making: "make",
  // take
  takes: "take",
  took: "take",
  taken: "take",
  taking: "take",
  // come
  comes: "come",
  came: "come",
  coming: "come",
  // see
  sees: "see",
  saw: "see",
  seen: "see",
  seeing: "see",
  // know
  knows: "know",
  knew: "know",
  known: "know",
  // think
  thinks: "think",
  thought: "think",
  thinking: "think",
  // want
  wants: "want",
  wanted: "want",
  wanting: "want",
  // say / tell
  says: "say",
  said: "say",
  saying: "say",
  tells: "tell",
  told: "tell",
  telling: "tell",
  // give
  gives: "give",
  gave: "give",
  given: "give",
  // find
  finds: "find",
  found: "find",
  // leave
  leaves: "leave",
  left: "leave",
  // feel
  feels: "feel",
  felt: "feel",
  // become
  becomes: "become",
  became: "become",
  // put
  puts: "put",
  putting: "put",
  // read (homograph present/past — still lemma read)
  reads: "read",
  reading: "read",
  // write
  writes: "write",
  wrote: "write",
  written: "write",
  // work
  works: "work",
  worked: "work",
  working: "work",
  // need
  needs: "need",
  needed: "need",
  // like
  likes: "like",
  liked: "like",
  // live
  lives: "live",
  lived: "live",
  living: "live",
};

/** Core English lemmas for tap-to-translate (RU learner UI + other UI langs). */
export const ENGLISH_CORE_LEMMAS: Record<string, HintGloss> = {
  be: { ru: "быть", en: "be", es: "ser / estar", de: "sein" },
  have: { ru: "иметь", en: "have", es: "tener", de: "haben" },
  do: { ru: "делать / вспом. do", en: "do", es: "hacer / auxiliar", de: "tun / Hilfsverb" },
  go: { ru: "идти / ехать", en: "go", es: "ir", de: "gehen / fahren" },
  get: { ru: "получать / становиться", en: "get", es: "conseguir", de: "bekommen" },
  make: { ru: "делать / готовить", en: "make", es: "hacer", de: "machen" },
  take: { ru: "брать", en: "take", es: "tomar", de: "nehmen" },
  come: { ru: "приходить", en: "come", es: "venir", de: "kommen" },
  see: { ru: "видеть", en: "see", es: "ver", de: "sehen" },
  know: { ru: "знать", en: "know", es: "saber / conocer", de: "wissen / kennen" },
  think: { ru: "думать", en: "think", es: "pensar", de: "denken" },
  want: { ru: "хотеть", en: "want", es: "querer", de: "wollen" },
  say: { ru: "говорить / сказать", en: "say", es: "decir", de: "sagen" },
  tell: { ru: "рассказывать / велеть", en: "tell", es: "contar / decir", de: "erzählen" },
  give: { ru: "давать", en: "give", es: "dar", de: "geben" },
  find: { ru: "находить", en: "find", es: "encontrar", de: "finden" },
  leave: { ru: "уходить / оставлять", en: "leave", es: "irse / dejar", de: "lassen / gehen" },
  feel: { ru: "чувствовать", en: "feel", es: "sentir", de: "fühlen" },
  become: { ru: "становиться", en: "become", es: "llegar a ser", de: "werden" },
  put: { ru: "класть / ставить", en: "put", es: "poner", de: "legen" },
  mean: { ru: "значить / иметь в виду", en: "mean", es: "significar", de: "bedeuten" },
  keep: { ru: "хранить / продолжать", en: "keep", es: "guardar / seguir", de: "behalten" },
  let: { ru: "позволять / пусть", en: "let", es: "dejar / permitir", de: "lassen" },
  begin: { ru: "начинать", en: "begin", es: "empezar", de: "beginnen" },
  seem: { ru: "казаться", en: "seem", es: "parecer", de: "scheinen" },
  help: { ru: "помогать", en: "help", es: "ayudar", de: "helfen" },
  talk: { ru: "говорить / болтать", en: "talk", es: "hablar", de: "reden" },
  turn: { ru: "поворачивать / становиться", en: "turn", es: "girar", de: "drehen" },
  start: { ru: "начинать", en: "start", es: "empezar", de: "starten" },
  show: { ru: "показывать", en: "show", es: "mostrar", de: "zeigen" },
  hear: { ru: "слышать", en: "hear", es: "oír", de: "hören" },
  play: { ru: "играть", en: "play", es: "jugar / tocar", de: "spielen" },
  run: { ru: "бежать / руководить", en: "run", es: "correr", de: "rennen" },
  move: { ru: "двигаться / переезжать", en: "move", es: "mover / mudarse", de: "bewegen" },
  live: { ru: "жить", en: "live", es: "vivir", de: "leben" },
  believe: { ru: "верить", en: "believe", es: "creer", de: "glauben" },
  hold: { ru: "держать", en: "hold", es: "sostener", de: "halten" },
  bring: { ru: "приносить", en: "bring", es: "traer", de: "bringen" },
  happen: { ru: "случаться", en: "happen", es: "pasar / ocurrir", de: "passieren" },
  write: { ru: "писать", en: "write", es: "escribir", de: "schreiben" },
  sit: { ru: "сидеть", en: "sit", es: "sentarse", de: "sitzen" },
  stand: { ru: "стоять", en: "stand", es: "estar de pie", de: "stehen" },
  lose: { ru: "терять / проигрывать", en: "lose", es: "perder", de: "verlieren" },
  pay: { ru: "платить", en: "pay", es: "pagar", de: "bezahlen" },
  meet: { ru: "встречать(ся)", en: "meet", es: "encontrar(se)", de: "treffen" },
  include: { ru: "включать", en: "include", es: "incluir", de: "einschließen" },
  continue: { ru: "продолжать", en: "continue", es: "continuar", de: "fortsetzen" },
  set: { ru: "ставить / набор", en: "set", es: "poner / conjunto", de: "setzen" },
  learn: { ru: "учить(ся)", en: "learn", es: "aprender", de: "lernen" },
  change: { ru: "менять(ся) / сдача", en: "change", es: "cambiar / cambio", de: "ändern / Wechselgeld" },
  lead: { ru: "вести / лидировать", en: "lead", es: "liderar / llevar", de: "führen" },
  understand: { ru: "понимать", en: "understand", es: "entender", de: "verstehen" },
  watch: { ru: "смотреть", en: "watch", es: "mirar", de: "schauen" },
  follow: { ru: "следовать", en: "follow", es: "seguir", de: "folgen" },
  stop: { ru: "останавливать(ся)", en: "stop", es: "parar", de: "stoppen" },
  create: { ru: "создавать", en: "create", es: "crear", de: "erschaffen" },
  speak: { ru: "говорить (на языке)", en: "speak", es: "hablar", de: "sprechen" },
  read: { ru: "читать", en: "read", es: "leer", de: "lesen" },
  allow: { ru: "разрешать", en: "allow", es: "permitir", de: "erlauben" },
  add: { ru: "добавлять", en: "add", es: "añadir", de: "hinzufügen" },
  spend: { ru: "тратить / проводить (время)", en: "spend", es: "gastar / pasar", de: "ausgeben" },
  grow: { ru: "расти", en: "grow", es: "crecer", de: "wachsen" },
  open: { ru: "открывать", en: "open", es: "abrir", de: "öffnen" },
  walk: { ru: "ходить пешком", en: "walk", es: "caminar", de: "zu Fuß gehen" },
  win: { ru: "выигрывать", en: "win", es: "ganar", de: "gewinnen" },
  offer: { ru: "предлагать", en: "offer", es: "ofrecer", de: "anbieten" },
  remember: { ru: "помнить", en: "remember", es: "recordar", de: "erinnern" },
  love: { ru: "любить", en: "love", es: "amar / querer", de: "lieben" },
  consider: { ru: "считать / рассматривать", en: "consider", es: "considerar", de: "überlegen" },
  appear: { ru: "появляться / казаться", en: "appear", es: "aparecer", de: "erscheinen" },
  buy: { ru: "покупать", en: "buy", es: "comprar", de: "kaufen" },
  wait: { ru: "ждать", en: "wait", es: "esperar", de: "warten" },
  serve: { ru: "служить / подавать", en: "serve", es: "servir", de: "dienen" },
  send: { ru: "отправлять", en: "send", es: "enviar", de: "senden" },
  expect: { ru: "ожидать", en: "expect", es: "esperar", de: "erwarten" },
  build: { ru: "строить", en: "build", es: "construir", de: "bauen" },
  stay: { ru: "оставаться", en: "stay", es: "quedarse", de: "bleiben" },
  fall: { ru: "падать", en: "fall", es: "caer", de: "fallen" },
  cut: { ru: "резать", en: "cut", es: "cortar", de: "schneiden" },
  reach: { ru: "достигать", en: "reach", es: "alcanzar", de: "erreichen" },
  remain: { ru: "оставаться", en: "remain", es: "permanecer", de: "bleiben" },
  work: { ru: "работать / работа", en: "work", es: "trabajar / trabajo", de: "arbeiten" },
  need: { ru: "нуждаться / нужно", en: "need", es: "necesitar", de: "brauchen" },
  like: { ru: "нравиться / как", en: "like", es: "gustar / como", de: "mögen / wie" },
  time: { ru: "время / раз", en: "time", es: "tiempo / vez", de: "Zeit" },
  day: { ru: "день", en: "day", es: "día", de: "Tag" },
  year: { ru: "год", en: "year", es: "año", de: "Jahr" },
  good: { ru: "хороший", en: "good", es: "bueno", de: "gut" },
  new: { ru: "новый", en: "new", es: "nuevo", de: "neu" },
  first: { ru: "первый", en: "first", es: "primero", de: "erst" },
  last: { ru: "последний / прошлый", en: "last", es: "último / pasado", de: "letzt" },
  long: { ru: "длинный / долгий", en: "long", es: "largo", de: "lang" },
  great: { ru: "отличный / великий", en: "great", es: "genial / gran", de: "großartig" },
  little: { ru: "маленький / мало", en: "little", es: "pequeño / poco", de: "klein / wenig" },
  own: { ru: "свой / собственный", en: "own", es: "propio", de: "eigen" },
  other: { ru: "другой", en: "other", es: "otro", de: "ander" },
  old: { ru: "старый", en: "old", es: "viejo / antiguo", de: "alt" },
  right: { ru: "правый / правильный", en: "right", es: "derecho / correcto", de: "recht" },
  big: { ru: "большой", en: "big", es: "grande", de: "groß" },
  high: { ru: "высокий", en: "high", es: "alto", de: "hoch" },
  different: { ru: "разный", en: "different", es: "diferente", de: "anders" },
  small: { ru: "маленький", en: "small", es: "pequeño", de: "klein" },
  large: { ru: "крупный", en: "large", es: "grande", de: "groß" },
  next: { ru: "следующий", en: "next", es: "siguiente / próximo", de: "nächst" },
  early: { ru: "рано / ранний", en: "early", es: "temprano", de: "früh" },
  young: { ru: "молодой", en: "young", es: "joven", de: "jung" },
  important: { ru: "важный", en: "important", es: "importante", de: "wichtig" },
  few: { ru: "немного (исчисл.)", en: "few", es: "pocos", de: "wenige" },
  public: { ru: "публичный / общественный", en: "public", es: "público", de: "öffentlich" },
  bad: { ru: "плохой", en: "bad", es: "malo", de: "schlecht" },
  same: { ru: "тот же", en: "same", es: "mismo", de: "gleich" },
  able: { ru: "способный / be able to", en: "able", es: "capaz", de: "fähig" },
  up: { ru: "вверх / get up", en: "up", es: "arriba", de: "oben / auf" },
  out: { ru: "наружу / вне", en: "out", es: "fuera", de: "raus / aus" },
  about: { ru: "о / около", en: "about", es: "sobre / aproximadamente", de: "über / etwa" },
  into: { ru: "в (внутрь)", en: "into", es: "en / hacia dentro", de: "in … hinein" },
  over: { ru: "над / через / more than", en: "over", es: "sobre / más de", de: "über" },
  after: { ru: "после", en: "after", es: "después de", de: "nach" },
  before: { ru: "до / перед", en: "before", es: "antes de", de: "vor" },
  with: { ru: "с", en: "with", es: "con", de: "mit" },
  without: { ru: "без", en: "without", es: "sin", de: "ohne" },
  from: { ru: "из / от", en: "from", es: "de / desde", de: "von / aus" },
  for: { ru: "для / в течение", en: "for", es: "para / por", de: "für" },
  of: { ru: "… (of)", en: "of", es: "de", de: "von" },
  to: { ru: "к / инфинитив to", en: "to", es: "a / to + inf", de: "zu / nach" },
  in: { ru: "в", en: "in", es: "en", de: "in" },
  on: { ru: "на", en: "on", es: "en / sobre", de: "auf" },
  at: { ru: "в / у (at)", en: "at", es: "en / a", de: "an / um" },
  the: { ru: "определённый артикль the", en: "the", es: "el / la / los / las", de: "der / die / das" },
  a: { ru: "неопределённый артикль a/an", en: "a", es: "un / una", de: "ein / eine" },
  an: { ru: "неопределённый артикль a/an", en: "an", es: "un / una", de: "ein / eine" },
  and: { ru: "и", en: "and", es: "y", de: "und" },
  or: { ru: "или", en: "or", es: "o", de: "oder" },
  but: { ru: "но", en: "but", es: "pero", de: "aber" },
  if: { ru: "если", en: "if", es: "si", de: "wenn" },
  when: { ru: "когда", en: "when", es: "cuando", de: "wenn / als" },
  where: { ru: "где", en: "where", es: "donde", de: "wo" },
  why: { ru: "почему", en: "why", es: "por qué", de: "warum" },
  how: { ru: "как", en: "how", es: "cómo", de: "wie" },
  what: { ru: "что / какой", en: "what", es: "qué", de: "was" },
  who: { ru: "кто", en: "who", es: "quién", de: "wer" },
  which: { ru: "который / какой", en: "which", es: "cuál / que", de: "welch" },
  this: { ru: "этот", en: "this", es: "este", de: "dies" },
  that: { ru: "тот / что", en: "that", es: "ese / que", de: "das / dass" },
  these: { ru: "эти", en: "these", es: "estos", de: "diese" },
  those: { ru: "те", en: "those", es: "esos", de: "jene" },
  not: { ru: "не", en: "not", es: "no", de: "nicht" },
  yes: { ru: "да", en: "yes", es: "sí", de: "ja" },
  no: { ru: "нет / никакой", en: "no", es: "no", de: "nein / kein" },
  very: { ru: "очень", en: "very", es: "muy", de: "sehr" },
  more: { ru: "больше", en: "more", es: "más", de: "mehr" },
  most: { ru: "самый / большинство", en: "most", es: "más / la mayoría", de: "meist" },
  some: { ru: "некоторые / немного", en: "some", es: "algunos / algo de", de: "einige" },
  any: { ru: "какой-либо / любой", en: "any", es: "algún / cualquier", de: "irgendein" },
  many: { ru: "много (исчисл.)", en: "many", es: "muchos", de: "viele" },
  much: { ru: "много (неисчисл.)", en: "much", es: "mucho", de: "viel" },
  morning: { ru: "утро", en: "morning", es: "mañana", de: "Morgen" },
  evening: { ru: "вечер", en: "evening", es: "tarde / noche", de: "Abend" },
  night: { ru: "ночь", en: "night", es: "noche", de: "Nacht" },
  today: { ru: "сегодня", en: "today", es: "hoy", de: "heute" },
  tomorrow: { ru: "завтра", en: "tomorrow", es: "mañana", de: "morgen" },
  yesterday: { ru: "вчера", en: "yesterday", es: "ayer", de: "gestern" },
  people: { ru: "люди", en: "people", es: "gente / personas", de: "Leute" },
  thing: { ru: "вещь / штука", en: "thing", es: "cosa", de: "Ding" },
  way: { ru: "способ / путь", en: "way", es: "manera / camino", de: "Weg / Art" },
  life: { ru: "жизнь", en: "life", es: "vida", de: "Leben" },
  world: { ru: "мир", en: "world", es: "mundo", de: "Welt" },
  school: { ru: "школа", en: "school", es: "escuela / colegio", de: "Schule" },
  home: { ru: "дом / домой", en: "home", es: "casa / hogar", de: "Zuhause" },
  food: { ru: "еда", en: "food", es: "comida", de: "Essen" },
  water: { ru: "вода", en: "water", es: "agua", de: "Wasser" },
  money: { ru: "деньги", en: "money", es: "dinero", de: "Geld" },
  friend: { ru: "друг", en: "friend", es: "amigo", de: "Freund" },
  family: { ru: "семья", en: "family", es: "familia", de: "Familie" },
  job: { ru: "работа (место)", en: "job", es: "trabajo / empleo", de: "Job" },
  city: { ru: "город", en: "city", es: "ciudad", de: "Stadt" },
  country: { ru: "страна / сельская местность", en: "country", es: "país / campo", de: "Land" },
  week: { ru: "неделя", en: "week", es: "semana", de: "Woche" },
  month: { ru: "месяц", en: "month", es: "mes", de: "Monat" },
  hour: { ru: "час", en: "hour", es: "hora", de: "Stunde" },
  minute: { ru: "минута", en: "minute", es: "minuto", de: "Minute" },
};
